### ISSUE TITLE
[BUG] 如何在保证其不失去长窗口对话能力的前提下，微调新发布的internlm2-chat-7b 200k长窗口大模型？

### ISSUE THREAD

**Issue by zhhvvv** [InternLM/lmdeploy#1000]
我希望使用**常规长短的语料**进行微调，然后我希望微调后的模型的长窗口对话能力不受到很大的削弱

Checklist
- [x] I have searched related issues but cannot get the expected help.
- [x] The bug has not been fixed in the latest version.

在新发布的internlm/internlm2-chat-7b模型上，应该如何做到垂直领域的微调？微调的语料长度和配比应该如何设计？

**Comment by pppppM** [comment]
数据策略如何设计这个问题太泛了，我们没有办法给出一个明确并行之有效的解决方案。

单纯在训练工具这个层面，推荐使用我们团队的另一个开源工具 `xtuner`，当数据策略确定后，能够帮助你更快地完成训练
