### ISSUE TITLE
[Bug] 更新了0.2.0后，无法量化了

### ISSUE THREAD

**Issue by Hongru0306** [InternLM/lmdeploy#1006]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

![90aebb7c39030e7d005722c2c8332e0](https://github.com/InternLM/lmdeploy/assets/99795077/1801a3bc-57ef-42e7-8b3f-b5fecbf13949)
- 量化操作方面，用0.2.0一直有问题，model的路径无法读取
- 改成0.1.0就可以了，很疑惑:  
![3b8dec06074c29b4e74e99830f2e754](https://github.com/InternLM/lmdeploy/assets/99795077/856c38fb-ebbc-4734-b7d9-d3035da8d61e)

### Reproduction

lmdeploy lite calibrate --model /root/model/Shanghai_AI_Laboratory/internlm-chat-7b --calib_dataset 'c4' --calib_samples 128 --calib_seqlen 2048 --work_dir ./quant_output

### Environment

```Shell
lmdeploy==0.2.0
```

### Error traceback

```Shell
usage: lmdeploy [-h] [-v] {chat,lite,serve,convert,list,check_env} ...
lmdeploy: error: unrecognized arguments: --model --calib_dataset c4 --calib_samples 128 --calib_seqlen 2048 --work_dir ./quant_output
```

**Comment by lvhan028** [comment]
cli更新了。--help可以看到各参数

**Comment by Hongru0306** [comment]
> cli更新了。--help可以看到各参数

好的，谢谢您！

**Comment by lvhan028** [comment]
optional的参数不要用下划线，改用短横线。因为CLI的参数从 fire 改成了 argument parser，下划线的方式不支持了
