### ISSUE TITLE
[Feature] TurbomindEngineConfig supports lora

### ISSUE THREAD

**Issue by seanxuu** [InternLM/lmdeploy#1007]
### Motivation

The existing HF is supporting inference without merging weights.

This is very important for a large number of tests! Merging weights consumes a lot of resources and time.

**Comment by lvhan028** [comment]
Turbomind has no plan to support lora recently. 
But the other engine of LMDeploy `TorchEngine` has supported it. May give it a try.
@grimoire please provide some guide

**Comment by grimoire** [comment]
Hi, you can try out PyTorch Engine.

You can build engine with a dictionary with `adapter_name:adapter_path` pair.

```python
from lmdeploy.messages import PytorchEngineConfig
from lmdeploy.pytorch.engine.engine import Engine
adapters = {'default':'/path/to/adapter'}
engine_config = PytorchEngineConfig(adapters=adapters)
engine = Engine.from_pretrained(model_path,
                                engine_config=engine_config,
                                trust_remote_code=True)
```

And perform inference with engine instance:

```python
generator = engine.create_instance()

for outputs in generator.stream_infer(session_id=session_id,
                                      input_ids=input_ids,
                                      gen_config=gen_config,
                                      adapter_name=adapter_name):
    # read outputs

# close session and release caches
generator.end(session_id)
```

**Comment by Cloopen-ReLiNK** [comment]
> Hi, you can try out PyTorch Engine.
> 
> You can build engine with a dictionary with `adapter_name:adapter_path` pair.
> 
> ```python
> from lmdeploy.messages import PytorchEngineConfig
> from lmdeploy.pytorch.engine.engine import Engine
> adapters = {'default':'/path/to/adapter'}
> engine_config = PytorchEngineConfig(adapters=adapters)
> engine = Engine.from_pretrained(model_path,
>                                 engine_config=engine_config,
>                                 trust_remote_code=True)
> ```
> 
> And perform inference with engine instance:
> 
> ```python
> generator = engine.create_instance()
> 
> for outputs in generator.stream_infer(session_id=session_id,
>                                       input_ids=input_ids,
>                                       gen_config=gen_config,
>                                       adapter_name=adapter_name):
>     # read outputs
> 
> # close session and release caches
> generator.end(session_id)
> ```



> Hi, you can try out PyTorch Engine.
> 
> You can build engine with a dictionary with `adapter_name:adapter_path` pair.
> 
> ```python
> from lmdeploy.messages import PytorchEngineConfig
> from lmdeploy.pytorch.engine.engine import Engine
> adapters = {'default':'/path/to/adapter'}
> engine_config = PytorchEngineConfig(adapters=adapters)
> engine = Engine.from_pretrained(model_path,
>                                 engine_config=engine_config,
>                                 trust_remote_code=True)
> ```
> 
> And perform inference with engine instance:
> 
> ```python
> generator = engine.create_instance()
> 
> for outputs in generator.stream_infer(session_id=session_id,
>                                       input_ids=input_ids,
>                                       gen_config=gen_config,
>                                       adapter_name=adapter_name):
>     # read outputs
> 
> # close session and release caches
> generator.end(session_id)
> ```

python: /project/lib/Analysis/Allocation.cpp:40: std::pair<llvm::SmallVector<unsigned int>, llvm::SmallVector<unsigned int> > mlir::triton::getCvtOrder(mlir::Attribute, mlir::Attribute): Assertion `!(srcMmaLayout && dstMmaLayout) && "Unexpected mma -> mma layout conversion"' failed.
Aborted
加载lora预测报错

**Comment by grimoire** [comment]
@Cloopen-ReLiNK I can not reproduce with [this adapter](https://huggingface.co/chenchi/lora-chatglm2-6b-guodegang). Would you mind provide the adapter?

**Comment by Cloopen-ReLiNK** [comment]
> you mind provide the adapter

Thank you, I will test load the adapter you are using first. If there is any problem, I will provide the adapter.

**Comment by Cloopen-ReLiNK** [comment]
# torch:2.1.1 triton:2.1.0 lmdeploy:0.2.1  cuda:11.7  V100-32G

from lmdeploy.messages import PytorchEngineConfig
from lmdeploy.pytorch.engine.engine import Engine
adapters = {'default':'./lora-chatglm2-6b-guodegang'}
engine_config = PytorchEngineConfig(adapters=adapters)
model_path = '/home/pretrained_model/chatglm2-6b'

engine = Engine.from_pretrained(model_path,
                                engine_config=engine_config,
                                trust_remote_code=True)
								


generator = engine.create_instance()


session_id = '1'
input_ids = engine.tokenizer.encode("你好")
adapter_name = 'default'
from lmdeploy import  GenerationConfig
gen_config = GenerationConfig(top_p=0.8,
                              top_k=40,
                              temperature=0.8,
                              max_new_tokens=1024
							  )
							  				  
for outputs in generator.stream_infer(session_id=session_id,
                                      input_ids=input_ids,
                                      gen_config=gen_config,
                                      adapter_name=adapter_name):
									  pass


generator.infer(session_id=session_id,
                                      prompt_token_ids=input_ids,
                                      gen_config=gen_config,
                                      adapter_name=adapter_name)

**Comment by grimoire** [comment]
I can replicate the error on V100 now. It seems that the flash-attention implementation does not fit devices with sm<80.

**Comment by Cloopen-ReLiNK** [comment]
3090 with cuda11.6, both adapters can run normally.

**Comment by Cloopen-ReLiNK** [comment]
Is there any solution for using V100? flash attention v1？

**Comment by grimoire** [comment]
> But the generated results are inconsistent
This might caused by random sampling.

> Is there any solution for using V100?
I am trying to find a fix, please allow me some time.

**Comment by grimoire** [comment]
@Cloopen-ReLiNK  https://github.com/InternLM/lmdeploy/pull/1027 Please have a try.

**Comment by Cloopen-ReLiNK** [comment]
> @Cloopen-ReLiNK #1027 Please have a try.

solved

**Comment by seanxuu** [comment]
> Hi, you can try out PyTorch Engine.
> 
> You can build engine with a dictionary with `adapter_name:adapter_path` pair.
> 
> ```python
> from lmdeploy.messages import PytorchEngineConfig
> from lmdeploy.pytorch.engine.engine import Engine
> adapters = {'default':'/path/to/adapter'}
> engine_config = PytorchEngineConfig(adapters=adapters)
> engine = Engine.from_pretrained(model_path,
>                                 engine_config=engine_config,
>                                 trust_remote_code=True)
> ```
> 
> And perform inference with engine instance:
> 
> ```python
> generator = engine.create_instance()
> 
> for outputs in generator.stream_infer(session_id=session_id,
>                                       input_ids=input_ids,
>                                       gen_config=gen_config,
>                                       adapter_name=adapter_name):
>     # read outputs
> 
> # close session and release caches
> generator.end(session_id)
> ```

Can it achieve the same abilities as the TurbomindEngine? Because I find TurbomindEngine is better than PytorchEngine.

**Comment by grimoire** [comment]
> Can it achieve the same abilities as the TurbomindEngine?
No, PytorchEngine is slower.

**Comment by seanxuu** [comment]
> > Can it achieve the same abilities as the TurbomindEngine?
> 
> No, PytorchEngine is slower.

Got it. Thank you.
