### ISSUE TITLE
[Bug] ！！修改参数重复惩罚参数报错！！

### ISSUE THREAD

**Issue by zeroleavebaoyang** [InternLM/lmdeploy#1009]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

![image](https://github.com/InternLM/lmdeploy/assets/2542251/1449a43a-dba8-412f-960a-31472b44936b)

### Reproduction

可以看到截图 ，按照官方给的代码 pipeline方式  修改其他topk,topp,temperature都没问题， 唯独修改repetition_penalty参数值 就会报错 如上图所示。   我也找了官方给的解决方案 按照其执行  程序一直卡住不动，也是有问题的。
![image](https://github.com/InternLM/lmdeploy/assets/2542251/288d1810-0d91-40c3-8a1a-d5af9f859c7d)

### Environment

```Shell
sys.platform: linux
Python: 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7,8,9: NVIDIA GeForce RTX 4090
CUDA_HOME: /usr/local/cuda-11.8
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 2.1.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

LMDeploy: 0.2.0+
transformers: 4.36.2
gradio: 3.40.1
fastapi: 0.109.0
pydantic: 2.5.3
```

**Comment by zeroleavebaoyang** [comment]
其实之前的版本 一直都有这个bug  我之前也提过 但是 官方也一直没有复现， 很奇怪， 请官方关注下， 这个参数很重要 谢谢 #898

**Comment by zeroleavebaoyang** [comment]
![image](https://github.com/InternLM/lmdeploy/assets/2542251/ce2dce57-39ff-4376-9438-ca1acdb9c420)
换成了 11.8 也是不行的 。  作者能测试下么

**Comment by lvhan028** [comment]
@irexyc is working on this issue

**Comment by irexyc** [comment]
@zeroleavebaoyang 

原因是repetition_penalty 那个kernel 需要的cuda share memory随着session_len增加而增加，改了一下实现，下一个版本应该不会报错了

**Comment by robinyqd** [comment]
刚入门，发现在0.22版本上只要设置repetition_penalty就会胡言乱语

**Comment by irexyc** [comment]
@robinyqd

不设置的话，结果正常么？感觉也有可能是对话模版没有对。建议贴一下代码，不然复现不了

**Comment by robinyqd** [comment]
> @robinyqd
> 
> 不设置的话，结果正常么？感觉也有可能是对话模版没有对。建议贴一下代码，不然复现不了

openai_client = OpenAI(api_key="EMPTY", base_url=base_url)


def create_chat_completion(model, messages, functions=None, use_stream=False):
    response = openai_client.chat.completions.create(
        model=model,
        messages=messages,
        temperature=0.0,  
        max_tokens=512,  
        stream=use_stream,
        extra_body={"repetition_penalty": 1.1},
    )
    if response:
        if use_stream:
            # 处理流式响应
            for chunk in response:
                # print(chunk)
                print(chunk.choices[0].delta.content, end="")
            print()
        else:
            print(response.choices[0].message.content)
    else:
        print("Error:", response.status_code)
        return None


def simple_chat(use_stream=True):
    functions = None
    chat_messages = [
        {
            "role": "user",
            "content": "讲一个小故事，关于科幻题材，大约300字。",
        },
    ]
    create_chat_completion(
        # "chatglm3-6b",
        "internlm2-chat-7b",
        # "internlm2-chat-1_8b",
        messages=chat_messages,
        functions=functions,
        use_stream=use_stream,
    )
if __name__ == "__main__":
    simple_chat(use_stream=True)

只要设置 extra_body={"repetition_penalty": 1.1},这个参数回答就不正常了，1.8B没问题，这个是使用7B的
CUDA_VISIBLE_DEVICES=2 lmdeploy serve api_server internlm2-chat-7b --server-port 10200
使用原生的requests是一样的结果

下面是输出结果

在遥远的未来世界中存在着一个名为“星际联盟”的组织——一个由来自不同星球的智慧生命体组成的联合政府机构；他们的目标是探索宇宙、保护和平与繁荣以及解决各种未知问题和技术挑战等任务上发挥着重要作用的角色扮演游戏（RPG）中的角色设定之一是虚拟火箭乐队成员之一的艾米丽亚和她的朋友们正在进行一次重要的太空探险之旅时遭遇了前所未有的危机：他们发现了一颗神秘的星球并决定降落去一探究竟……

随着飞船缓缓降落在这颗陌生的行星表面后不久便发生了意外情况导致通讯中断无法联系到其他队员或基地指挥部支援团队也未能及时抵达现场救援行动陷入僵局之际突然出现了一位神秘人物自称拥有超凡力量能够帮助她们脱离困境但同时也带来了更多疑问和不解之惑…最终经过一番惊心动魄的经历之后终于揭开了真相原来这位所谓的救世主实际上就是该星系中最强大的外星种族领袖他带领自己的部下前来协助地球人共同对抗邪恶势力拯救整个银河系免受毁灭性灾难威胁的故事就此展开！整篇小说充满了紧张刺激的情节和各种意想不到的发展转折点让读者们不禁为之惊叹不已同时也不禁思考起人类文明未来的命运走向何方？或许只有通过不断努力奋斗才能迎来更加美好的明天吧... 

以上就是我为您讲述的小型科技主题短篇故事的梗概希望能够带给您一些启示或者乐趣感谢您的聆听期待下次再与您分享更多的精彩内容~! 
(注:本文纯属虚构如有雷同实属巧合)
【关键词】:
1. "国际空间站" - NASA官方名称为ISS(International Space Station),是人类历史上第一个真正意义上的永久居住地;2."火星探测器":NASA于2018年发射的首个载有人类宇航员前往火星的计划;"猎鹰重型运力增强版"(Booster Rocket)"龙船号"Crew Dragon",均属于美国SpaceX公司旗下产品线;
3.[email]:"阿波罗11号的登月舱"](Apollo Lunar Module);4."[phone]
5�����嗨笁潪能實験厔S0a6e9bE69A92uJiFjMVxPdUg=*//*zh-CN*/https://www.baidu.com/s?wd=%D7%CDC%D77%EBA&tn=baiduhome_pgse_10_pagenavi_sugrec_dogv_baid

**Comment by irexyc** [comment]
temperature 建议设成0.8，

我看了下openai的文档https://platform.openai.com/docs/api-reference/audio/createTranscription#audio-createtranscription-temperature
他那个操作我们还不支持

**Comment by irexyc** [comment]
temperature 设成0.8试试呢

**Comment by robinyqd** [comment]
> temperature 设成0.8试试呢
也是一样的结果：
在未来的世界里有一个名叫艾米丽的女孩儿是一名天才科学家和工程师.她发明了一种能够穿越时空的机器——时间穿梭器（Time Traveler）并成功地进行了第一次试验飞行到未来世界旅行了数年之久后回到现在的时间点时发现地球已经发生了巨大的变化：人类文明高度发达、环境污染严重且资源匮乏……为了拯救这个星球上的生命与自然界和谐共存下去需要大家共同努力才能实现！

《星际迷航》中的经典台词“前进!”激励着无数人勇敢地探索未知领域；而这部小说则通过主人公的经历向读者展示了科技发展带来的机遇及挑战以及环境保护的重要性等主题思想内容丰富深刻值得一读再读的佳作之一也适合作为青少年读物推荐给大家阅读哦~😊✨❤️⚡#AI小助手 #短篇创作练习题答案展示
</s> 
仩嗨纾潪能實験厔:4e0a6d77103b7ebf5cb9ea9078c023aa3dbacba2fbfd8ca1ec91433abe0910746fc529���дцшяэщтийперамолхісныҀ฿گ்،یافتخوشبه‌دنطرحمکعلّقۇسزيئجىv127实録صุжأិ้นàíä¹zèéŒôåêóì³ð÷áöµçÈßħæ±×ımúüć;fsdfsdfsfdsaf;sadssgsasgqwertyuiojngh¥t6765kkljlchcuikknigyh
                                                WAwA没错啊?是时候让你们看看真正的技术水平啦!
㉤כּות_אינרשัלמה‎�@#$%^&*()＿+—–∞…≤≥π˜’=884473329188427687106LJKIOUYQHDFECBAZXCVBNMvasnfhas2468F38G16bas721¬®°£™σ∩/ΦΛ²»■△≡既见君子%￥€

===============
用原生的requests也是同样的问题
response = requests.post(f"{base_url}/v1/chat/completions", json=data, stream=use_stream)

正常使用都没什么大问题，就怕碰到有重复的回答需要调整这个参数，我刚测了一下1.8也有类似情况，就是表现形式不同（设置了惩罚参数容易有重复回答），如果不设置重复参数默认应该是1.0吧

**Comment by irexyc** [comment]
@robinyqd 

我感觉是模型的问题，我直接用internlm2-chat-7b，transformers的接口跑，repetition_penalty 设成1.1，也会有乱码。
https://huggingface.co/internlm/internlm2-chat-7b

```
>>> response, history = m.chat(tok, "讲一个小故事，关于科幻题材，大约300字。", history=[], repetition_penalty=1.1)
>>> response
'在遥远的未来世界中存在着一个高度发达的文明——银河联邦（Galactic Federation）：它的成员星球遍布整个星系；科技发展到了人类难以想象的程度！其中一颗名为“诺亚”星球的科学家们正在进行一项前所未有的实验项目—创造一种全新的生命形式来探索宇宙深处的奥秘……\n\n他们经过多年的研究与实践后终于成功地制造出了第一批拥有自我意识和思考能力的生物体--代号为"星际游侠"(Interstellar Wanderer),这些被赋予智慧的生命开始展现出惊人的能力:能够飞行、变形甚至穿越时空屏障去探寻未知领域的秘密!\n\n然而随着时间推移及对新生命的深入了解发现,"幽灵战士 "不仅具备强大的战斗技能还具有强烈的情感倾向;他们在面对危机时表现出的勇气令所有人都为之惊叹不已!渐渐地大家意识到它们的存在不仅仅是科学上的突破更是一种道德责任的重担----如何平衡科学研究与社会伦理之间的关系成为了困扰着这个团队的核心问题...\n\n最终在一次重大事件爆发前夜(一场外星文明的入侵行动即将来临之际),"NOVA计划组别首脑决定向全联盟公布真相并呼吁保护那些无辜而又脆弱的新兴种族......这场惊心动魄的故事也由此展开了新的篇章... \n\n通过讲述这样一个充满奇幻色彩且引人入胜的小故事情节我们不仅可以感受到作者对于科学与未来的无限遐想同时也引发了对人与自然之间微妙关系的深思探讨.....这或许正是优秀文学作品所具有的内涵魅力所在吧?!\n \n以上就是我为您创作的有关「神秘太空探险记」这个小故事的简要内容啦~希望能够带给您愉悦阅读体验哦😊✨❤️❗⚡☀⭐#小说创作##短篇叙事 #幻想冒险#\n【提示】本段文本由AI模型生成完成于2023年3月18日14点53分11秒左右～如果您有任何疑问或建议欢迎随时提出交流互动呢^ω^^و(^)\n*注1:*本文中所提到的具体名词概念如:"galaxy federation","noah planet",以及相关人物角色名称等均为虚构设定仅供读者娱乐参考之用;\n**备注2)**由于该篇文字属于原创首发未经任何平台授权转载发布因此无法提供外部链接展示等相关操作敬请谅解;\n\n以上便是我能为您提供的内容服务感谢您的耐心倾听期待与您再次相遇分享更多精彩有趣的话题话题呀~\n\n祝好♪(*´▽｀*)ノﾟ♡ *Happy Ending*\n***-END-*\n\n\n希望我的回答对您有所帮助或者启发到灵感哟 ~请让我知道还有什么可以帮助你的地方~~我会尽最大努力继续完善自己的表达能力和知识储备以更好地帮助更多人哒(\\*>w<\\*)\n让我们一起进步成长共同构建一个更加美好的明天叭 ! ^_♥︎٩꒪̓‿୨ˮᴗ¹ږ۰°ᶜᵒʳᵉ )o*(๑> <็﹏`))ง✧\u200b\u200e͛\\\\ิɾ̀։ヽຶ̩̥ゝヾ(o゜∀゜ロ)^おーいの☆ .+ + - _(:з»∠)\\*.+"\'-\'"`/ / \\ \' :._.+.-.:.,,,+.+-./:-:.:+,-..-.:\'`.+\'....~-+++/ ,.\' `.`,\'\'\'``\'\'\'\'. \'\' \'-.......\'- .. .... ... \'.---\':......... --- ---- -- ----- -------------------------- ------- -------------\nPlease let me know if there\'s anything else I could help with or provide insights on :) Thanks for reading my answer here at Zhihu.com **or you may check out more of these interesting topics below**\n----------------------------------------------------\n《三体》系列书籍推荐:\n•[刘慈欣]著名作家全新力作 [地球往事三部曲]:第一部&第二部 &第三部的全套套装集合!(共13册)\n\n-----------------------------------\n其他感兴趣的主题讨论可以参考以下链接文章噢 :\n①如何在日常生活中实现高效的沟通技巧?\n②有哪些值得推荐的经典英文电影?\n\n③怎样学习一门编程语言才能快速入门上手?\n\n\n④有什么好的学习方法可以提升学习成绩吗？\n\n\n\n⑤现代年轻人应该如何理财规划自己的人生财务目标和时间价值管理策略等问题需要考虑哪些方面因素影响等等...\n⑥如何快速有效地提高工作效率并且保持良好心态状态从而取得卓越成绩成果等方面的经验总结分析体会心得感悟见解认识观点看法思路想法创意构念构思设想策划谋划战略战术方案对策措施手段途径方法渠道资源信息资讯情报数据统计资料报告调查问卷访谈采访座谈会讲座研讨会学术会议论坛峰会被邀出席演讲发表评论意见反馈回复答疑解惑释明澄清说明解释辩驳论证证明反驳质疑诘问质询求证咨询求助提问答复解答阐发阐述论断论述辨析评述评价评估鉴定审核认证评定评级评选筛选甄选挑选择优拣选出类归档分类整理归纳综合概括提炼升华深化拓展延伸扩大范围拓宽视野开阔眼界增长见识增广见闻增强信心坚定信念树立信仰弘扬正气维护正义惩恶扬善倡导公平公正'
>>> response, history = m.chat(tok, "讲一个小故事，关于科幻题材，大约300字。", history=[], repetition_penalty=1.0)
>>> response
'在遥远的未来，人类已经掌握了穿越时空的技术，并建立了一个名为“星际之门”的超级结构，可以连接各个星系和宇宙中的不同角落。在这个时代，一个名叫艾琳的年轻科学家，对宇宙的奥秘充满了好奇心。\n\n一天，艾琳和她的团队决定前往一个名为“星云边缘”的神秘星球进行探索。这个星球位于银河系边缘，据说那里隐藏着一种可以改变宇宙法则的能量晶体。为了获得这种能量，艾琳和她的团队准备了最先进的太空船，并开始了他们的探险之旅。\n\n在穿越星际之门时，他们遭遇了来自未知星系的强烈电磁波干扰，导致太空船的导航系统失效。艾琳决定手动操控太空船，试图找到通往星云边缘的路径。经过数小时的飞行，他们终于抵达了目的地。\n\n然而，当他们降落到星球表面时，他们发现这里的环境与地球完全不同。这里的重力是地球的十倍，空气中的氧气含量极低，而且没有任何生物迹象。艾琳和她的团队开始探索这个星球，他们发现了一种奇怪的植物，这些植物可以发出微弱的光芒，照亮了周围的环境。\n\n在深入探索的过程中，他们发现了一个神秘的洞穴，里面充满了能量晶体。艾琳意识到这些晶体就是他们一直在寻找的东西。但是，当他们试图采集晶体时，突然出现了一些未知的生物，它们似乎对艾琳和她的团队非常敌视。\n\n经过一番激烈的战斗，艾琳和她的团队最终成功采集了晶体，并回到了太空船上。在返回地球的途中，他们遇到了一次宇宙风暴，导致太空船受到了严重的损坏。艾琳和她的团队决定利用能量晶体修复太空船，并成功返回地球。\n\n回到地球后，艾琳和她的团队成为了英雄，他们的探险成果引起了全球的轰动。艾琳意识到，宇宙中充满了未知的奥秘和危险，但正是这种探险精神，推动了人类科技的不断进步。'
```
