### ISSUE TITLE
[Feature] 推理时可不可以清空上下文？

### ISSUE THREAD

**Issue by seanxuu** [InternLM/lmdeploy#1010]
### Motivation

就像chatgpt一样，如果想重新开始一个对话，直接点击clear就可以了。现在的框架里好像没有这个参数。

### Related resources
像这样<img width="248" alt="image" src="https://github.com/InternLM/lmdeploy/assets/118865326/e6782762-2d42-4eb3-9e96-f7b160830d8f">

**Comment by lvhan028** [comment]
请问在使用哪个接口？
pipline的接口，api_server RESTful API中类openai接口，都是不保存上下文的

**Comment by seanxuu** [comment]
> 请问在使用哪个接口？ pipline的接口，api_server RESTful API中类openai接口，都是不保存上下文的

我的意思是，有没有一个开关可以控制“保存上下文的功能”

**Comment by lvhan028** [comment]
pipeline层没有提供。engine层有相关的接口。可以看下turbomind.py

**Comment by seanxuu** [comment]
> pipeline层没有提供。engine层有相关的接口。可以看下turbomind.py

谢谢
