### ISSUE TITLE
[Bug] 更新lmdeploy0.2.0后kv量化显存没有差距

### ISSUE THREAD

**Issue by Hongru0306** [InternLM/lmdeploy#1015]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

- 您好，十分抱歉再次打扰您！  
- 我开kv量化后，前后显存没有变化！  
- 这个是没开的:  
![949ce6aefa16a95909e71c0f6ff06bf](https://github.com/InternLM/lmdeploy/assets/99795077/660f146a-3758-458c-ad89-bd455f79428c)
- 这个是开启的:  
![9bd7734bea6251fee017e99f54c3ad4](https://github.com/InternLM/lmdeploy/assets/99795077/4d4ecf2e-fd92-4f7f-be63-7a42c4c64ea9)  
我在`weight`文件夹中已经看到了kv量化的权重，但仍然没有变化:  
![32daf3e9737219591af8e3904b7a0f8](https://github.com/InternLM/lmdeploy/assets/99795077/94db4353-757c-4a4d-8fe2-f14d6b7d0bb5)
===========================================
但是！我开w4量化的时候会有明显的显存下降:
![0661ae49a40c4f3bfeb5b2093e21ffc](https://github.com/InternLM/lmdeploy/assets/99795077/358ece5b-04a9-4108-8c59-0e9c46eff1f5)

实在令我费解，求助官方大佬！

### Reproduction

same as above

### Environment

```Shell
lmdeploy==0.2.0
```

### Error traceback

```Shell
None
```

**Comment by lzhangzz** [comment]
这里配置文件里max_cache_entry_count是按总显存的比例指定的，cache block变小了会分配更多的block；把它设成具体的整数就有区别了。

不过看现在设的是10%的显存，量化kv后也就降到5%的样子。
