### ISSUE TITLE
[Bug] 对InternLM模型做4bit量化后问题回答失效

### ISSUE THREAD

**Issue by zhanghui-china** [InternLM/lmdeploy#1016]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

对InternLM模型做4bit量化后问题回答失效

### Reproduction

internlm模型

直接转为 turbomind模型，并部署，一切正常：

<img width="636" alt="41e4e6d01812b2e5999dc81424822e9" src="https://github.com/InternLM/tutorial/assets/63148804/346ee4c2-0f17-49e2-99f8-88c8ae140f41">

<img width="833" alt="2253f644f2e92deb081c1f651057681" src="https://github.com/InternLM/tutorial/assets/63148804/f6e2673d-ab7d-4a30-9b88-559c860d32ed">

先计算minmax
lmdeploy lite calibrate \
  --model  /home/zhanghui/models/internlm/internlm-chat-7b/ \
  --calib_dataset "c4" \
  --calib_samples 128 \
  --calib_seqlen 2048 \
  --work_dir ./quant_output
![image](https://github.com/InternLM/tutorial/assets/63148804/bcb87f25-45f3-4a52-8a9c-e4481da132c4)
![image](https://github.com/InternLM/tutorial/assets/63148804/5f5ebc80-b07a-4d31-88b6-7b07ecac60f9)

再#通过 minmax 获取量化参数
lmdeploy lite kv_qparams \
  --work_dir ./quant_output  \
  --turbomind_dir workspace/triton_models/weights/ \
  --kv_sym False \
  --num_tp 1
![image](https://github.com/InternLM/tutorial/assets/63148804/920fc174-f00c-4c5d-a86d-a6422c53f531)

再进行4bit量化：
lmdeploy lite auto_awq \
  --model  /home/zhanghui/models/internlm/internlm-chat-7b/ \
  --w_bits 4 \
  --w_group_size 128 \
  --work_dir ./quant_output
![image](https://github.com/InternLM/tutorial/assets/63148804/656fae90-bfcd-4456-8abd-10a209fcc007)
![image](https://github.com/InternLM/tutorial/assets/63148804/02065c67-026c-4d1a-8200-53fe9987c04c)

将量化后的模型转为TurboMind格式：
lmdeploy convert  internlm-chat-7b ./quant_output \
    --model-format awq \
    --group-size 128 \
    --dst_path ./workspace_quant
![image](https://github.com/InternLM/tutorial/assets/63148804/4ed0f7df-91b6-4d89-ba38-aa223266c6a6)

![image](https://github.com/InternLM/tutorial/assets/63148804/a87c9e92-b9fa-4b58-87ba-106ae061be95)

lmdeploy chat turbomind ./workspace_quant
![image](https://github.com/InternLM/tutorial/assets/63148804/6b0dc095-8101-420c-8fa9-400eaeb5a27f)

问答失效了！

lmdeploy chat turbomind ./workspace_quant --model-format awq

![image](https://github.com/InternLM/tutorial/assets/63148804/9ffc8000-6b99-4717-a189-2fcb18ddea78)

依然如此

具体流程参见 https://zhuanlan.zhihu.com/p/678960135

### Environment

```Shell
WSL ubuntu 22.04
以及 InternStudio
```

**Comment by RunningLeon** [comment]
@zhanghui-china hi, could you run `lmdeploy check_env` and post the info here?

**Comment by zhanghui-china** [comment]
(base) zhanghui@zhanghui:~$ conda activate lmdeploy
(lmdeploy) zhanghui@zhanghui:~$ lmdeploy check_env
sys.platform: linux
Python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 4090
GPU 1: NVIDIA GeForce RTX 3080 Laptop GPU
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.6, V11.6.124
GCC: gcc (Ubuntu 9.5.0-1ubuntu1~22.04) 9.5.0
PyTorch: 2.1.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.5  (built against CUDA 11.7)
    - Built with CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.16.2+cu121
LMDeploy: 0.1.0+
transformers: 4.36.2
gradio: 3.50.2
fastapi: 0.109.0
pydantic: 2.5.3

**Comment by RunningLeon** [comment]
@zhanghui-china hi, could you try with v0.2.0? it works fine on my side and it has less steps
### examples

#### config
```shell
model_config:

[llama]
model_name = internlm-chat-7b
tensor_para_size = 1
head_num = 32
kv_head_num = 32
vocab_size = 103168
num_layer = 32
inter_size = 11008
norm_eps = 1e-06
attn_bias = 1
start_id = 1
end_id = 2
session_len = 2056
weight_type = int4
rotary_embedding = 128
rope_theta = 10000.0
size_per_head = 128
group_size = 128
max_batch_size = 128
max_context_token_num = 1
step_length = 1
cache_max_entry_count = 0.5
cache_block_seq_len = 128
cache_chunk_size = -1
num_tokens_per_iter = 0
max_prefill_iters = 1
extra_tokens_per_iter = 0
use_context_fmha = 1
quant_policy = 4
max_position_embeddings = 2048
rope_scaling_factor = 0.0
use_logn_attn = 0
```

#### chat dialog
```
请用中文写一个爱情故事,长度300字


<|User|>:请用中文写一个爱情故事,长度300字
<|Bot|>: 从前有一个年轻的男孩，他叫做李明。他是个勤劳的年轻人，每天都会去农场工作。他有一个美丽的女友，名叫小芳。小芳是一个温柔善良的女孩，她总是关心李明，照顾他。

一天，李明在农场工作时，遇到了一个美丽的女孩，名叫小红。小红是一个聪明有才华的女孩，她总是帮助李明解决农场上的问题。小红和李明之间开始了一段浪漫的恋情。

然而，小芳发现了一切。她非常生气，因为她认为李明不应该和别的女孩有关系。小芳决定离开李明，但李明仍然爱着小芳。他决定离开农场，去找小芳。

小芳很高兴见到李明，但她仍然很生气。她告诉李明，她永远不会原谅他。李明感到非常伤心，但他仍然爱着小芳。他决定留在小芳身边，直到她原谅他。

最终，小芳原谅了李明。他们重新开始了他们的生活，并开始了一段新的恋情。小红成为了他们之间的桥梁，因为她是一个聪明的女孩，可以帮助他们解决任何问题。

这个故事告诉我们，爱情是伟大的，它可以克服一切困难。
```

#### script
```shell
lmdeploy lite auto_awq ./internlm-chat-7b --calib-dataset ptb --w-bits 4 --w-group-size 128 --work-dir ./awq
lmdeploy chat turbomind ./awq --model-format awq --quant-policy 4
```

**Comment by zhanghui-china** [comment]
您好，升级到 lmdeploy 0.2.0之后：
<img width="1052" alt="8a8db315a0e7f1c7f9b8276dc2582a7" src="https://github.com/InternLM/lmdeploy/assets/63148804/1fd5e324-3a1d-4baf-aadd-85f93ee44d77">

执行：
lmdeploy lite auto_awq /home/zhanghui/models/internlm/internlm-chat-7b --calib-dataset ptb --w-bits 4 --w-group-size 128 --work-dir ./awq
<img width="686" alt="187a85ee7ab8eac634caa0131e610b4" src="https://github.com/InternLM/lmdeploy/assets/63148804/fa2734b7-530f-4d9a-94da-f2a47d758776">

或者
lmdeploy lite auto_awq /home/zhanghui/models/internlm/internlm-chat-7b --calib-dataset c4 --w-bits 4 --w-group-size 128 --work-dir ./awq
<img width="791" alt="be874a1aa2c0fd6ce392b9596fb418f" src="https://github.com/InternLM/lmdeploy/assets/63148804/fa7a14ee-2f1f-4675-93db-1b10047d5e5a">

都报错。

**Comment by RunningLeon** [comment]
it seems you cannot reach to dataset from web. maybe you could use proxy

**Comment by zhanghui-china** [comment]
问题解决了。解决方法如下：

先做点准备工作：

cp /root/share/temp/datasets/c4/calib_dataloader.py ~/

diff calib_dataloader.py /root/.conda/envs/lmdeploynew/lib/python3.10/site-packages/lmdeploy/lite/utils/calib_dataloader.py

cd /root/.conda/envs/lmdeploynew/lib/python3.10/site-packages/lmdeploy/lite/utils/

cp calib_dataloader.py calib_dataloader.py.old

cp ~/calib_dataloader.py .

cd ~/lmdeploy-internlm2/

lmdeploy lite auto_awq ./internlm2-chat-7b --calib-dataset c4 --w-bits 4 --w-group-size 128 --work-dir ./quant_output

![image](https://github.com/InternLM/lmdeploy/assets/63148804/13dc9890-f147-432b-b0d9-65db36d0fc31)

lmdeploy convert internlm2-chat-7b quant_output --dst-path internlm2-chat-7b-quant --model-format awq --w-bits 4 --w-group-size 128
![image](https://github.com/InternLM/lmdeploy/assets/63148804/038bc06c-227f-477e-8f51-3c2d330d5a51)

![image](https://github.com/InternLM/lmdeploy/assets/63148804/478aba32-9348-4ee5-bd54-454cc35e8126)


生成的目录如下：
![image](https://github.com/InternLM/lmdeploy/assets/63148804/ba8a7117-7849-40ae-823a-f2b993d69a77)

先修改config.ini
![image](https://github.com/InternLM/lmdeploy/assets/63148804/5e1f6bbc-9c38-4353-ba8b-76d31adec768)

cd ~/lmdeploy-internlm2/

lmdeploy chat turbomind ./internlm2-chat-7b-quant
![image](https://github.com/InternLM/lmdeploy/assets/63148804/08fd4fb9-2680-4e91-aef4-8d62f011949b)
可以正常运行了。

**Comment by zhanghui-china** [comment]
顺便提一句，用的是internlm2模型。
