### ISSUE TITLE
cuda必须是11.8吗？

### ISSUE THREAD

**Issue by datalee** [InternLM/lmdeploy#1018]
### 📚 The doc issue

11.7出现显存占用多了很多

**Comment by lvhan028** [comment]
cuda 11.3 及以上都行。
显存多和cuda无关。lmdeploy v0.2.0 版本默认会开辟总内存的50%给k/v cache。
如果觉得显存占用过多，或者遇到 oom的问题，可以调低显存占用比例 cache_max_entry_count 的值

**Comment by datalee** [comment]
> cuda 11.3 及以上都行。 显存多和cuda无关。lmdeploy v0.2.0 版本默认会开辟总内存的50%给k/v cache。 如果觉得显存占用过多，或者遇到 oom的问题，可以调低显存占用比例 cache_max_entry_count 的值

[`调整了cache_max_entry_count为0.1，可以处理10w字的输入，但是输出是重复的：`](https://github.com/InternLM/InternLM/issues/647)

**Comment by lvhan028** [comment]
对于长文本推理，请参考：https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/advance/long_context.md
请问显卡型号是？

**Comment by datalee** [comment]
> 对于长文本推理，请参考：https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/advance/long_context.md 请问显卡型号是？

v100， 32G

**Comment by lvhan028** [comment]
@datalee 我在v100上没有复现你的问题。测试用例可以分享下吗？

**Comment by datalee** [comment]
> @datalee 我在v100上没有复现你的问题。测试用例可以分享下吗？

直接对话确实没问题，我的场景是上下文加上了10w的context，文件是这个，问题是：`总结一下主营业务表现`
输入的文章是附件这份：txt
prompt是
`with open(txt_input,'r',encoding='utf-8') as f:
        txt = f.read()
prompt = f"'''{txt}'''，以上是参考资料，请根据参考资料回答用户问题:{user_input}，注意如果参考资料不足以支撑，你可以回答‘参考资料不足‘"`

**Comment by lvhan028** [comment]
没有看到附件。可以直接把附件拖拽到输入框中

**Comment by datalee** [comment]
> 没有看到附件。可以直接把附件拖拽到输入框中

内网上传不了，泪哭

**Comment by datalee** [comment]
> 没有看到附件。可以直接把附件拖拽到输入框中

内网就是这个网页转txt
[年报](https://vip.stock.finance.sina.com.cn/corp/view/vCB_AllBulletinDetail.php?stockid=603881&id=5939874)

**Comment by lvhan028** [comment]
我用你提供单独这份数据验证了下，还没有复现你遇到的问题。
关于重复的问题，可以把 lmdeploy 升级到 v0.2.2，然后设置下repetition_penalty=1.002
