### ISSUE TITLE
[Bug] 3090 跑不了 internlm2 7B chat

### ISSUE THREAD

**Issue by tpoisonooo** [InternLM/lmdeploy#1019]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

报错 
```shell
[WARNING] gemm_config.in is not found; using default GEMM algo
Exception in thread Thread-21:                                                       
Traceback (most recent call last):                                                   
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner              
    self.run()                                                                       
  File "/usr/lib/python3.8/threading.py", line 870, in run                                                                                                                
    self._target(*self._args, **self._kwargs)                                                                                                                             
  File "/home/khj/.local/lib/python3.8/site-packages/lmdeploy/turbomind/turbomind.py", line 486, in _create_model_instance                                                
    model_inst = self.tm_model.model_comm.create_model_instance(                                                                                                          
RuntimeError: [TM][ERROR] CUDA runtime error: out of memory /lmdeploy/src/turbomind/utils/allocator.h:231
```

### Reproduction

```bash
            backend_config = TurbomindEngineConfig(rope_scaling_factor=2.0, session_len=8000)
            self.pipe = pipeline(model_path, backend_config=backend_config)
            self.gen_config = GenerationConfig(top_p=0.8,
                                        top_k=1,
                                        temperature=0.8,
                                        max_new_tokens=1024)
```

### Environment

```Shell
3090
```

**Comment by lvhan028** [comment]
使用参数：cache_max_entry_count=0.2。表示k/v cache占 total mem的比例。
默认是0.5。在3090上会超出

**Comment by hhnshiyi** [comment]
请问cache_max_entry_count=0.2这个参数哪里可以调节

> 使用参数：cache_max_entry_count=0.2。表示k/v cache占 total mem的比例。 默认是0.5。在3090上会超出

**Comment by lvhan028** [comment]
如果你用的pipeline接口，可以看下 https://github.com/InternLM/lmdeploy/blob/main/docs/en/inference/pipeline.md 文档，里面介绍了方法。
如果用的是CLI工具，比如 lmdeploy chat, lmdeploy serve，通过参数 --cache-max-entry-count 来设置。--help有详细的命令说明

**Comment by gengpeip** [comment]
> 使用参数：cache_max_entry_count=0.2。表示k/v cache占 total mem的比例。 默认是0.5。在3090上会超出

请问T4的话，应该设置多少？

**Comment by lvhan028** [comment]
T4(16G) 跑 7B-FP16 很悬，可以跑 4bit 权重的

**Comment by gengpeip** [comment]
> T4(16G) 跑 7B-FP16 很悬，可以跑 4bit 权重的

嗯嗯，我已经把internlm2-20B量化成了4bit，4张16G的T4还是会爆显存，cache_max_entry_count设为0.1也不行

**Comment by gengpeip** [comment]
> 用的是哪个版本？

0.2.5

**Comment by gengpeip** [comment]
> lmdeploy 在 sm75 上的 kernel 有问题，在 main 分支上修复了，但还没有发版。你可以基于main分支编译源码，再试试看。 另外，你的代码能分享下吗？

好的，感谢回复！我现在手边没电脑，明天给您分享，再次感谢！！

**Comment by gengpeip** [comment]
> lmdeploy 在 sm75 上的 kernel 有问题，在 main 分支上修复了，但还没有发版。你可以基于main分支编译源码，再试试看。 另外，你的代码能分享下吗？
不好意思，我今天上午在复现这个错误的时候发现，'cache_max_entry_count', 'tp'这两个参数并没有被设置成功
运行：lmdeploy chat turbomind ./workspace --tp 4 --cache-max-entry-count 0.1
报错：lmdeploy - WARNING - model_source: workspace
lmdeploy - WARNING - loading from workspace, ignore args ['cache_max_entry_count', 'tp'] please use TurbomindEngineConfig or modify config.ini
lmdeploy - WARNING - model_config:

[llama]
model_name = internlm2-chat
tensor_para_size = 1
head_num = 48
kv_head_num = 8
vocab_size = 92544
num_layer = 48
inter_size = 16384
norm_eps = 1e-05
attn_bias = 0
start_id = 1
end_id = 2
session_len = 32776
weight_type = int4
rotary_embedding = 128
rope_theta = 1000000.0
size_per_head = 128
group_size = 128
max_batch_size = 64
max_context_token_num = 1
step_length = 1
cache_max_entry_count = 0.8
cache_block_seq_len = 128
cache_chunk_size = -1
num_tokens_per_iter = 0
max_prefill_iters = 1
extra_tokens_per_iter = 0
use_context_fmha = 1
quant_policy = 0
max_position_embeddings = 32768
rope_scaling_factor = 0.0
use_logn_attn = 0


Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/lmdeploy/turbomind/turbomind.py", line 229, in _create_weight_func
    model_comm.create_shared_weights(device_id, rank)
RuntimeError: [TM][ERROR] CUDA runtime error: CUDA-capable device(s) is/are busy or unavailable /lmdeploy/src/turbomind/utils/memory_utils.cu:32 

2024-03-20 03:09:21,848 - lmdeploy - WARNING - Input chat template with model_name is None. Forcing to use internlm2-chat
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/lmdeploy/turbomind/turbomind.py", line 490, in _create_model_instance
    model_inst = self.tm_model.model_comm.create_model_instance(
RuntimeError: [TM][ERROR] CUDA runtime error: CUDA-capable device(s) is/are busy or unavailable /lmdeploy/src/turbomind/triton_backend/llama/LlamaTritonModel.cc:253 

session 1

double enter to end input >>>

**Comment by lvhan028** [comment]
现在不需要手动转模型了，lmdeploy会自动转
```shell
lmdeploy chat turbomind <the/path/of/internlm2-chat-20b-4bit> --model-format awq --tp 4
```
如果是用转好的模型，直接改 workspace/triton_models/weights/config.ini 中的参数。现在命令行中的参数没有覆盖 config.ini

**Comment by gengpeip** [comment]
> 现在不需要手动转模型了，lmdeploy会自动转
> 
> ```shell
> lmdeploy chat turbomind <the/path/of/internlm2-chat-20b-4bit> --model-format awq --tp 4
> ```
> 
> 如果是用转好的模型，直接改 workspace/triton_models/weights/config.ini 中的参数。现在命令行中的参数没有覆盖 config.ini

嗯嗯，感谢回复，已经调试成功了！
