### ISSUE TITLE
Lmdeploy有流式输出的案例吗？

### ISSUE THREAD

**Issue by DirtyKnightForVi** [InternLM/lmdeploy#1021]
如题

**Comment by lvhan028** [comment]
有的。参考[这篇文档](https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/serving/restful_api.md)搭建api_server，在swagger ui中，可以实验 v1/chat/completions 接口。把参数 stream 设置为 True，就可以流式输出了

**Comment by DirtyKnightForVi** [comment]
> 有的。参考[这篇文档](https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/serving/restful_api.md)搭建api_server，在swagger ui中，可以实验 v1/chat/completions 接口。把参数 stream 设置为 True，就可以流式输出了

也就是说还需要把包成api才能使用吗？
我们这边的需求是要包成自己的api服务

**Comment by datalee** [comment]
> > 有的。参考[这篇文档](https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/serving/restful_api.md)搭建api_server，在swagger ui中，可以实验 v1/chat/completions 接口。把参数 stream 设置为 True，就可以流式输出了
> 
> 也就是说还需要把包成api才能使用吗？ 我们这边的需求是要包成自己的api服务

`def chat_completions_v1(self,
                            model: str,
                            messages: Union[str, List[Dict[str, str]]],
                            temperature: Optional[float] = 0.7,
                            top_p: Optional[float] = 1.0,
                            n: Optional[int] = 1,
                            max_tokens: Optional[int] = 512,
                            stop: Optional[Union[str, List[str]]] = None,
                            stream: Optional[bool] = False,
                            presence_penalty: Optional[float] = 0.0,
                            frequency_penalty: Optional[float] = 0.0,
                            user: Optional[str] = None,
                            repetition_penalty: Optional[float] = 1.0,
                            session_id: Optional[int] = -1,
                            ignore_eos: Optional[bool] = False,
                            **kwargs):`
这个函数的入参有stream

**Comment by lvhan028** [comment]
> > 有的。参考[这篇文档](https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/serving/restful_api.md)搭建api_server，在swagger ui中，可以实验 v1/chat/completions 接口。把参数 stream 设置为 True，就可以流式输出了
> 
> 也就是说还需要把包成api才能使用吗？ 我们这边的需求是要包成自己的api服务

PR #974 在处理这个问题

**Comment by LeonG7** [comment]
如何在调用api_server服务时设定max_tokens，现在默认是512，我需要在启动时将这个值设为session_lens的长度

**Comment by lvhan028** [comment]
lmdeploy serve api_server --session-len 4096 

F.Y.I, 可以用 lmdeploy serve api_server --help 查看命令详情
