### ISSUE TITLE
[Question] qwen-vl server支持

### ISSUE THREAD

**Issue by jessiewiswjc** [InternLM/lmdeploy#1028]
### 📚 The doc issue

我看见lmdeploy支持多模态qwen-vl的例子 https://github.com/InternLM/lmdeploy/tree/main/examples/vl#qwen-vl-chat server侧只是gradio，想问一下有能支持Batching能力类似triton server的例子吗

**Comment by lvhan028** [comment]
v0.2.6 已经支持了，可以参考这份文档 https://lmdeploy.readthedocs.io/en/latest/serving/api_server_vl.html
