### ISSUE TITLE
[Bug] KV Cache INT8 校准警告：Token indices sequence length is longer than the specified maximum sequence length for this model (2874305 > 4096)

### ISSUE THREAD

**Issue by deepslee** [InternLM/lmdeploy#1033]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

在实现KV Cache的标定过程中，出现一条关于Token indices sequence length的警告。
警告为：
`Token indices sequence length is longer than the specified maximum sequence length for this model (2874305 > 4096). Running this sequence through the model will result in indexing errors`
![1706091435414](https://github.com/InternLM/lmdeploy/assets/35492306/1cbd2be2-8cad-4960-8c5e-d88ae49379e3)

### Reproduction

`lmdeploy lite calibrate  /data/Chinese-Llama-2-7b/ --calib-dataset 'ptb'     --calib-samples 128   --calib-seqlen 2048  --work-dir /data/dsj/calibrate`

### Environment

```Shell
lmdeploy==0.2.0
```

**Comment by lianqi1998** [comment]
I encountered a problem: When I use awq ,Token indices sequence length is longer than the specified maximum sequence length for this model (1104485 > 131072).

**Comment by Skyseaee** [comment]
您好，请问您解决这个问题了么，最近我们也遇到了换了不同数据集都是类似的 warning

**Comment by lvhan028** [comment]
@AllentDan may follow it up

**Comment by AllentDan** [comment]
一般不影响标定，可以忽略。

**Comment by AllentDan** [comment]
另外 kv cache 的量化现在都改成在线量化了，离线量化废弃了。
