### ISSUE TITLE
[Bug] 长文本输出不稳定时不时间隔停止一下

### ISSUE THREAD

**Issue by 726663676** [InternLM/lmdeploy#1041]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

现象描述：
问题1：输出不是一个个tokens输出，有时一下子输出一堆。
问题2：长文本输出明显的间隔延迟，会持续输出一些tokens会时不时随机间隔停止一下，然后继续生成。如果只是单次请求不会出现这种情况。

问题1疑问：
输出tokens不应该是一个个tokens出来吗，一下子输出一堆tokens输出正常吗？

问题2疑问：
长文本输出不流畅，是会受到其他请求完成操作影响吗？输出一段tokens会停一会（大约0.3-0.5s延迟后又继续生成），这是正常现象吗？

其次发现显卡

### Reproduction

测试：
1.开启一个程序并发5左右同时请求部署的api大模型接口
2.开启另个一个程序请求大模型接口，代码如下：
import openai
openai.api_base = "http://127.0.0.1:11102/v1"
openai.api_key = "none"
openai.api_key = "YOUR_API_KEY"

prompt = "请写800字文章"
def stream():
    response = ""
    for chunk in openai.ChatCompletion.create(
        model="internlm2-chat-20b",
        messages=[
                {"role": "user", "content": str(prompt)}
            ],
        stream=True
    ):
        if hasattr(chunk.choices[0].delta, "content"):
            print(chunk.choices[0].delta.content)
            response += chunk.choices[0].delta.content
            yield response
s = None
for s in stream():
    pass

### Environment

```Shell
lmdeploy设置max_batch_size=3
cache_max_entry_count = 0.50
model_format="awq"
backend="turbomind"
cap="chat"
```

**Comment by AllentDan** [comment]
问题1，正常的，Turbomind 后端的流式输出从来不是按一个一个token的输出的。
问题2，如果有其它请求在一起处理的情况下，是有可能出现的，因为CPU可能在做其他事情。但这并不意味着推理引擎没在处理当前请求。

**Comment by lvhan028** [comment]
@AllentDan 但不流畅就比较奇怪。
@726663676 请问使用的什么显卡呢

**Comment by 726663676** [comment]
@lvhan028 感谢您的回复！使用的系统环境如下：
ubunut：22.04
显卡：GTX4090 2张 24G加载
torch:2.1.2
lmdeploy:0.2.1
cuda:12.2
补充：上面描述的情况请求测试我开启的另外一个程序5个并发的请求输入都是一样的tokens大于7000以上的，并发输如也是一样的。当我改变另一个程序的5个并发的tokens是2000左右的时候，我输入prompt"请写800字文章"的长文本输出间隔中断情况会小很多，间隔中断就变为0.1秒左右了。

**Comment by 726663676** [comment]
@AllentDan 非常感谢您的解答！
