### ISSUE TITLE
是否有计划支持 chatglm3

### ISSUE THREAD

**Issue by shell-nlp** [InternLM/lmdeploy#1043]
### Motivation

是否有计划支持 chatglm3， 如果没有，怎么支持这个模型，有提供适配模型的教程吗？

**Comment by grimoire** [comment]
有计划做，不过时间关系不能保证马上完成。
如果有兴趣适配的话可以参考一下 https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/advance/pytorch_new_model.md

**Comment by shell-nlp** [comment]
> 有计划做，不过时间关系不能保证马上完成。 如果有兴趣适配的话可以参考一下 https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/advance/pytorch_new_model.md

感谢您的回复，有一个疑问， pytorch适配后,TurboMind 是不是就可以直接使用了，还是说，只可以使用 pytorch 后端

**Comment by lvhan028** [comment]
只可以使用pytorch后端
