### ISSUE TITLE
[Bug] The token <|im_end|> can not be used as stop words

### ISSUE THREAD

**Issue by iwanglei1** [InternLM/lmdeploy#1047]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

运行2代模型，因为终止符原因模型输出一堆，直到达到限定长度

### Reproduction

from lmdeploy import pipeline, GenerationConfig, PytorchEngineConfig

backend_config = PytorchEngineConfig(session_len=2024)
gen_config = GenerationConfig(top_p=0.8,
                              top_k=40,
                              temperature=0.8,
                              max_new_tokens=1024)
pipe = pipeline('/internlm2-chat-7b',
                backend_config=backend_config,
                log_level="INFO")
prompts = [[{
    'role': 'user',
    'content': 'Hi, pls intro yourself'
}], [{
    'role': 'user',
    'content': 'Shanghai is'
}]]
response = pipe(prompts, gen_config=gen_config)
print(response)

### Environment

```Shell
lldeploy==0.2.1
```

**Comment by irexyc** [comment]
> pipe = pipeline('/internlm2-chat-7b',

本地模型的路径？你检查下modeling_internlm2.py这个文件，看下build_inputs函数是不是这样的 https://huggingface.co/internlm/internlm2-chat-7b/blob/main/modeling_internlm2.py#L1136-L1146

internlm2-chat-7b 上周改过对话模版，相应的lmdeploy也在0.2.1中改了，如果你的模型用的是旧的话就会有这个问题
