### ISSUE TITLE
[Feature] 请问在使用pipeline推理的时候，怎么获得流式输出呢？没有找到对应的参数

### ISSUE THREAD

**Issue by FelixZhang7** [InternLM/lmdeploy#1055]
### Motivation

代码如下
from lmdeploy import pipeline, TurbomindEngineConfig
from lmdeploy.messages import GenerationConfig

engine_config = TurbomindEngineConfig(session_len=200000, rope_scaling_factor=2.0)
pipe = pipeline(
    "Shanghai_AI_Laboratory/internlm2-chat-20b",
    backend_engine=engine_config,
)
gen_config = GenerationConfig(
    top_p=0.8, top_k=40, temperature=0.8, repetition_penalty=1.02, max_new_tokens=1024
)
response = pipe("背诵《静夜思》", gen_config=gen_config)
print(response.text)

**Comment by lvhan028** [comment]
在 PR #974 中。可以先看看是否符合你的需求呢？
