### ISSUE TITLE
请教下如何在已经4bit量化的模型上继续做KV量化

### ISSUE THREAD

**Issue by zhanghui-china** [InternLM/lmdeploy#1056]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

生成的4bit模型HF格式的模型目录是 ~/lmdeploy-internlm/quant_output
<img width="410" alt="aecba9af63de36531a23d87be836931" src="https://github.com/InternLM/lmdeploy/assets/63148804/63894c2f-2fed-4603-9319-dda288438014">

生成的4bit模型TurboMind格式的目录是 ~/lmdeploy-internlm/internlm-chat-7b-quant
<img width="385" alt="937e968ee9d1166aa2c3c65f64058fe" src="https://github.com/InternLM/lmdeploy/assets/63148804/750c2259-69f8-4ce0-96a6-e11b29a761ce">

### Reproduction

后续操作有几个步骤：
1.计算minmax
lmdeploy lite calibrate \
  --model  /root/share/temp/model_repos/internlm-chat-7b/ \
  --calib_dataset "c4" \
  --calib_samples 128 \
  --calib_seqlen 2048 \
  --work_dir ./dir_a

请问dir_a目录是随便写个空的目录，还是写到前面某个目录中去。

2.通过 minmax 获取量化参数
lmdeploy lite kv_qparams \
  --work_dir ./dir_b  \
  --turbomind_dir **workspace/triton_models/weights/** \
  --kv_sym False \
  --num_tp 1

请问下dir_b是什么目录，是不是上面1步骤留下的目录。
turbomind_dir 是不是应该填前面的internlm-chat-7b-quant目录（这个目录是4bit 量化成HF格式后，再做convert后留下的）

### Environment

```Shell
ubuntu 22.04
```

**Comment by zhanghui-china** [comment]
这边我对InternLM一代模型的操作流程如下：
![image](https://github.com/InternLM/lmdeploy/assets/63148804/6dc6680d-11db-4225-a4f3-2e1d4a908222)

mkdir ~/lmdeploy-internlm
cd ~/lmdeploy-internlm
pip install 'lmdeploy[all]==v0.2.0'
![image](https://github.com/InternLM/lmdeploy/assets/63148804/861c31c7-8738-4f0e-883a-e17918167fd8)

先进行4bit量化：
lmdeploy lite auto_awq /root/shishen/internlm-chat-7b --calib-dataset c4 --w-bits 4 --w-group-size 128 --work-dir ./quant_output

这个命令，会将原始的HF格式的模型权重文件，转换为4bit量化的HF格式的模型权重文件
查看结果目录：./quant_output
![image](https://github.com/InternLM/lmdeploy/assets/63148804/9b8379bb-20e3-4607-ab8c-ee029798f8eb)

lmdeploy convert internlm-chat-7b quant_output --dst-path internlm-chat-7b-quant --model-format awq --group-size 128

这个命令，会将前面转换好的4bit量化的HF格式的模型权重文件，转换为TurboMind格式
查看结果目录：./internlm-chat-7b-quant
![image](https://github.com/InternLM/lmdeploy/assets/63148804/51e8f7c3-cbbc-4e7d-8390-c55a6b8efc64)

测试一下转换好的4bit模型：
lmdeploy chat turbomind ./internlm-chat-7b-quant
![image](https://github.com/InternLM/lmdeploy/assets/63148804/c7f87f55-5cae-4326-88b3-0b7134224a4d)

![image](https://github.com/InternLM/lmdeploy/assets/63148804/5ba2f8cc-8a1d-4c27-ad03-fb12622a82c7)

**Comment by zhanghui-china** [comment]
在这个基础上，我打算在实现lkv量化。
于是，执行了以下命令计算minmax

`# 计算 minmax

export HF_MODEL=./internlm-chat-7b
lmdeploy lite calibrate \
$HF_MODEL \
--calib-dataset 'c4' \
--calib-samples 128 \
--calib-seqlen 2048 \
--work-dir $HF_MODEL`

![image](https://github.com/InternLM/lmdeploy/assets/63148804/d8702a81-1f63-45ee-a618-f27c096cccdc)
![image](https://github.com/InternLM/lmdeploy/assets/63148804/9077e6c0-769a-4e0f-b765-1568cb2dae28)

在原来的HF模型下生成的结果如下：
![image](https://github.com/InternLM/lmdeploy/assets/63148804/44b92fc4-842c-47d9-ad85-20375cfcc424)

生成了4个新的pth文件。

**Comment by zhanghui-china** [comment]
`# 通过 minmax 获取量化参数
lmdeploy lite kv_qparams \
$HF_MODEL \
--turbomind_dir ./internlm-chat-7b-quant/triton_models/weights/ \
--kv_sym False \
--num_tp 1`

![image](https://github.com/InternLM/lmdeploy/assets/63148804/94d7a8a8-c364-4a75-82f9-6a29256b1519)
执行这个命令就报错了！

貌似lmdeploy 0.1.0,0.2.0和0.2.1的命令参数有区别。

根据这个文档  [https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/quantization/kv_int8.md](url)
没看到 lmdeploy lite kv_qparams 这个该怎么使用。

**Comment by RunningLeon** [comment]
hi, from lmdeploy0.2.0, you don't need to explicitly convert hf to turbomind. After you do w4, you can try `lmdeploy chat turbomind ./internlm-chat-7b-4bit --model-format awq --quant-policy 4`. make sure that `./internlm-chat-7b-4bit` has the calibration files like `inputs_stats.pth`, `outputs_stats.pth`, `key_stats.pth` and `value_stats.pth`.

**Comment by zhanghui-china** [comment]
我把操作过程写一下：

conda activate lmdeploynew

cd ~/lmdeploy-internlm2

pip list|grep lmdeploy
![image](https://github.com/InternLM/lmdeploy/assets/63148804/018cde93-5153-4153-a231-f365e30e2cd8)
确认是最新版本。

先将原始HF模型（internlm2-chat-7b)转为 TurboMind格式：

rm -rf workspace

lmdeploy convert internlm2-chat-7b ./internlm2-chat-7b --dst-path ./workspace_internlm2_turbomind
结果目录：./workspace_internlm2_turbomind
修改 ~/lmdeploy-internlm2/workspace_internlm2_turbomind/triton_models/weights/config.ini

cache_max_entry_count = 0.2

试一下原始模型：

lmdeploy chat turbomind ./workspace_internlm2_turbomind
![image](https://github.com/InternLM/lmdeploy/assets/63148804/730565b7-1b08-4c23-a313-204a17328f6d)
显存占用20G：
![image](https://github.com/InternLM/lmdeploy/assets/63148804/0c4db303-5613-4b4b-8f77-6fb6ff04513b)

这部分是第一步骤，通过原始HF模型（目录：./internlm2-chat-7b），生成了TurboMind模型（目录： ./workspace_internlm2_turbomind），并做了验证，没有问题。

**Comment by zhanghui-china** [comment]
开始在原始模型上做4bit量化：

cp ./lmdeploytest/calib_dataloader.py ./anaconda3/envs/lmdeploynew/lib/python3.10/site-packages/lmdeploy/lite/utils/calib_dataloader.py

lmdeploy lite auto_awq ./internlm2-chat-7b --w-bits 4 --w-group-size 128 --work-dir ./internlm2-chat-7b-4bit --calib-dataset c4
生成结果如下： ./internlm2-chat-7b-4bit
![image](https://github.com/InternLM/lmdeploy/assets/63148804/1bd35a77-f8d5-463d-8ef3-6520f4ce22b0)
转成TurboMind格式：
lmdeploy convert internlm2-chat-7b ./internlm2-chat-7b-4bit --dst-path ./workspace_internlm2_4bit_turbomind --model-format awq --group-size 128
结果目录：./workspace_internlm2_4bit_turbomind
vi ./workspace_internlm2_4bit_turbomind/triton_models/weights/config.ini

修改 cache_max_entry_count = 0.2

lmdeploy chat turbomind ./workspace_internlm2_4bit_turbomind
![image](https://github.com/InternLM/lmdeploy/assets/63148804/a6f57bec-851f-4071-bd47-45a26768d1c1)
显存占用：11.1G左右。
![image](https://github.com/InternLM/lmdeploy/assets/63148804/fc6574e2-aece-42e3-bc3d-074d3e22b010)

vi ./workspace_internlm2_4bit_turbomind/triton_models/weights/config.ini

修改 cache_max_entry_count = 0.1

lmdeploy chat turbomind ./workspace_internlm2_4bit_turbomind
![image](https://github.com/InternLM/lmdeploy/assets/63148804/69ab45aa-8668-462f-bc84-39ed0764f4ad)
显存占用：8.6G左右。
![image](https://github.com/InternLM/lmdeploy/assets/63148804/3c589946-999c-4704-b8bf-629e7bac7ff2)

**Comment by zhanghui-china** [comment]
前面两步都没有啥问题。

**Comment by zhanghui-china** [comment]
下面开始做 kv量化。
我打算基于 4bit的HF模型：./internlm2-chat-7b-4bit 做kv量化。

有疑问的命令主要在这里：
在4bit模型基础上继续KV量化：

# 计算

lmdeploy lite calibrate ./internlm2-chat-7b-4bit --calib-dataset 'c4' --calib-samples 128 --calib-seqlen 2048 --work-dir ./workspace_kv
生成的文件如下： ./workspace_kv
![image](https://github.com/InternLM/lmdeploy/assets/63148804/e28f7fe7-7507-4389-b4ef-fb680c650c9b)
# 获取量化参数

lmdeploy lite kv_qparams ./workspace_kv ./workspace_internlm2_4bit_turbomind/triton_models/weights/ --num-tp 1
![image](https://github.com/InternLM/lmdeploy/assets/63148804/b42b6021-84d8-49c9-8125-16f70503dbc8)

生成的参数叠加在 ./workspace_internlm2_4bit_turbomind/triton_models/weights/
![image](https://github.com/InternLM/lmdeploy/assets/63148804/aca804d8-bb9f-4384-9bed-0ae1e5d20beb)

修改 ./workspace_internlm2_4bit_turbomind/triton_models/weights/config.ini

quant_policy = 4

lmdeploy chat turbomind ./workspace_internlm2_4bit_turbomind
![image](https://github.com/InternLM/lmdeploy/assets/63148804/eea7445f-1823-4d22-b837-c2b653ebeac8)
![image](https://github.com/InternLM/lmdeploy/assets/63148804/19bca05c-841b-4a76-be89-f050d013c5ce)

好像量化完，模型问答就失效了。

**Comment by zhanghui-china** [comment]
根据前面老师的提示：
我们将 ./workspace_kv 下的4个文件直接复制到 4bit量化的HF模型目录 ./internlm-chat-7b-4bit下：

cp ./workspace_kv/* ./internlm2-chat-7b-4bit
![image](https://github.com/InternLM/lmdeploy/assets/63148804/d4505e4a-a0d9-4b24-9807-16bdf075147e)
lmdeploy chat turbomind ./internlm2-chat-7b-4bit --model-format awq --quant-policy 4
![image](https://github.com/InternLM/lmdeploy/assets/63148804/d1875c57-6ded-4521-ac9b-9bc262cb9b1f)
![image](https://github.com/InternLM/lmdeploy/assets/63148804/ddfbcfbd-e28e-4265-b374-81d9f12dd162)

模型问答也是失效的。

**Comment by RunningLeon** [comment]
@zhanghui-china hi, you need to input the original hf model instead of int4-hf model in calibration.

>lmdeploy lite calibrate ./internlm2-chat-7b-4bit --calib-dataset 'c4' --calib-samples 128 --calib-seqlen 2048 --work-dir ./workspace_kv
生成的文件如下： ./workspace_kv

**Comment by zhanghui-china** [comment]
所以正确的过程应该是：

lmdeploy lite calibrate **./internlm2-chat-7b** --calib-dataset 'c4' --calib-samples 128 --calib-seqlen 2048 --work-dir ./workspace_kv 

lmdeploy lite kv_qparams ./workspace_kv ./workspace_internlm2_4bit_turbomind/triton_models/weights/ --num-tp 1 

修改weight下config.ini文件：

quant_policy = 4

lmdeploy chat turbomind workspace_internlm2_4bit_turbomind --model-format awq --quant-policy 4

![image](https://github.com/InternLM/lmdeploy/assets/63148804/51c9ce61-914f-4f77-be5e-ae7fe2c3a193)
![image](https://github.com/InternLM/lmdeploy/assets/63148804/f85332c3-6479-42ac-ab7b-f3ff91d49063)

这样做是可以的。

**Comment by zhanghui-china** [comment]
最后整理的结论供大家参考：

关于 int4量化和叠加kv cache的方法终于搞清楚了：

（1）

将HF格式的模型转为turbomind格式
lmdeploy convert internlm2-chat-7b ./internlm2-chat-7b --dst-path ./workspace_internlm2_turbomind

启动原模型：
cache_max_entry_count = 0.2 （config.ini）
lmdeploy chat turbomind ./workspace_internlm2_turbomind


（2）

将HF格式的模型进行4bit量化，直接转为HF格式的4bit模型
lmdeploy lite auto_awq ./internlm2-chat-7b --w-bits 4 --w-group-size 128 --work-dir ./internlm2-chat-7b-4bit
将量化后的HF格式的4bit模型转为 turbomind格式
lmdeploy convert internlm2-chat-7b ./internlm2-chat-7b-4bit --dst-path ./workspace_internlm2_4bit_turbomind --model-format awq --group-size 128

启动4bit模型：
cache_max_entry_count = 0.1
lmdeploy chat turbomind ./workspace_internlm2_4bit_turbomind

（3）
将HF格式的模型进行计算minmax(注意此时不是针对 4bit的HF模型，而是针对原始的HF模型)
lmdeploy lite calibrate ./internlm2-chat-7b --calib-dataset 'c4' --calib-samples 128 --calib-seqlen 2048 --work-dir ./workspace_kv 

获取量化参数（注意此时是把结果放到 turbomind的4bit模型weight目录下
lmdeploy lite kv_qparams ./workspace_kv ./workspace_internlm2_4bit_turbomind/triton_models/weights/ --num-tp 1
quant_policy = 4

启动4bit+kvcache模型：
lmdeploy chat turbomind workspace_internlm2_4bit_turbomind --model-format awq --quant-policy 4

感谢 @H.Lyu 及其lmdeploy团队的老师给与支持。
