### ISSUE TITLE
[Feature] 多卡设置似乎没有生效？

### ISSUE THREAD

**Issue by Patrick-Ni** [InternLM/lmdeploy#1059]
### Motivation

![image](https://github.com/InternLM/lmdeploy/assets/59468866/f5355e97-6c06-4425-b3ba-259044f48bc1)
2卡a100 40g，设置tp=2之后，使用InternLM2-chat-20b进行长文本推理，在加载模型的时候发现模型并没有加载到两张卡上？还是报错OOM，哪怕设置了cache_max_entry_count = 0.1也不行

**Comment by irexyc** [comment]
这个地方应该写错了，应该是 `backend_config`
<img width="870" alt="image" src="https://github.com/InternLM/lmdeploy/assets/16019484/93e88c61-2d31-4f11-bcf8-e47414fc1f50">

40G的话，session_length没办法设置200k，200k大概需要18.75G的kv cache

**Comment by Patrick-Ni** [comment]
非常感谢！问题解决了！！
