### ISSUE TITLE
[Bug] Qwen AWQ int4 量化增加group size=64后，相比于group size=128精度下降明显

### ISSUE THREAD

**Issue by jjjjohnson** [InternLM/lmdeploy#1066]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.

### Describe the bug

在lmdeploy/src/turbomind/kernels/gemm_s_f16/gemm_s4_f16.cu 加上group size=64支持并且重新编译后效果差特别多，是不是group size=64 对于kernel和group size=128的不一样导致的？

Group | rouge1 | rouge2 | rouge3 | rougeLsum
-- | -- | -- | -- | --
64 | 10.3 | 0.838 | 7.708 | 9.29
128 | 29.33 | 11.37 | 20.59 | 23.99

### Reproduction

lmdeploy v0.1.0

### Environment

```Shell
lmdeploy v0.1.0
```

**Comment by lzhangzz** [comment]
group size=64时的量化参数是怎么生成的？

**Comment by jjjjohnson** [comment]
@lzhangzz 
```
# step 1
lmdeploy lite calibrate \
    --model $HF_MODEL \
    --calib_dataset 'wikitext2' \
    --calib_samples 512 \
    --calib_seqlen 1024 \
    --work_dir $WORK_DIR

# step 2
lmdeploy lite auto_awq \
    --model $HF_MODEL \
    --w-bits 4 \
    --work-dir $WORK_DIR \
    --w_group_size 64

# step 3
lmdeploy convert \
    --model-name qwen-14b \
    --model-path $WORK_DIR \
    --model-format awq \
    --group-size 64 \
    --tp 1 --dst_path $WORK_DIR/workspace
```

**Comment by lzhangzz** [comment]
测了一下w4 gemm group size=64，没发现问题。建议通过repeat group size=128时的参数得到group size=64的，这样可以排除用不同group size量化带来的区别

**Comment by jjjjohnson** [comment]
> 测了一下w4 gemm group size=64，没发现问题。建议通过repeat group size=128时的参数得到group size=64的，这样可以排除用不同group size量化带来的区别

请问能具体一点怎么repeat嘛？

**Comment by bisunny** [comment]
请问这个问题后来有解决吗

**Comment by lvhan028** [comment]
这个问题先关掉了，用 issue #1305 继续追踪
