### ISSUE TITLE
问题字数超过一定大小后回答的结果为空[Bug] 

### ISSUE THREAD

**Issue by xxg98** [InternLM/lmdeploy#1080]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

问题字数超过一定大小后回答的结果为空

### Reproduction

lmdeploy serve api_server /root/autodl-tmp/projects/LLM/internlm2-chat-7b --server-name 0.0.0.0 --server-port 6006 --tp 1 --session-len 210000 --rope-scaling-factor 2 --cache-max-entry-count 0.01

### Environment

```Shell
python3.10
cuda11.8
显卡：3090
lmdeploy版本：0.2.1
```

**Comment by xxg98** [comment]
> ### Checklist
> * [ ]  1. I have searched related issues but cannot get the expected help.
> * [ ]  2. The bug has not been fixed in the latest version.
> 
> ### Describe the bug
> 问题字数超过一定大小后回答的结果为空
> 
> ### Reproduction
> lmdeploy serve api_server /root/autodl-tmp/projects/LLM/internlm2-chat-7b --server-name 0.0.0.0 --server-port 6006 --tp 1 --session-len 210000 --rope-scaling-factor 2 --cache-max-entry-count 0.01
> 
> ### Environment
> ```shell
> python3.10
> cuda11.8
> 显卡：3090
> lmdeploy版本：0.2.1
> ```
> 
> ### Error traceback
> _No response_


更正一下，显卡为3090ti

**Comment by xxg98** [comment]
> --cache-max-entry-count 0.01


在将--cache-max-entry-count调整为0.02之后，会出现很多重复的句子

**Comment by irexyc** [comment]
1. 结果为空：

你看下返回的结果，里面应该有个finish_reason，是不是length，是的话应该是你的开辟的kv cache显存不支持推理那么长的文本，你可以看下把log level改成info看一下server端的输出，应该会有提示说session_len被truncate了。

对于internlm2-chat-7b 来说，128 需要16MB，200k的话大概需要24.5G，你可以算一下0.02 大概能推理多长。这个字段的含义在后面的版本会改成剩余显存的百分比，而不是总显存的百分比。

2. 重复的句子

可以参考这个issue，估计就是对话模版跟hf上面的模型不匹配。
https://github.com/InternLM/lmdeploy/issues/1047

**Comment by xxg98** [comment]
> 1. 结果为空：
> 
> 你看下返回的结果，里面应该有个finish_reason，是不是length，是的话应该是你的开辟的kv cache显存不支持推理那么长的文本，你可以看下把log level改成info看一下server端的输出，应该会有提示说session_len被truncate了。
> 
> 对于internlm2-chat-7b 来说，128 需要16MB，200k的话大概需要24.5G，你可以算一下0.02 大概能推理多长。这个字段的含义在后面的版本会改成剩余显存的百分比，而不是总显存的百分比。
> 
> 2. 重复的句子
> 
> 可以参考这个issue，估计就是对话模版跟hf上面的模型不匹配。 #1047

1. 0.01看来有点小了，看来应该调整session-len
2. 是stop，并且提示如下：
[TM][INFO] Set logger level by INFO
[TM][INFO] [forward] Enqueue requests
[TM][INFO] [forward] Wait for requests to complete ...
[TM][WARNING] [RejectInvalidRequests] Skipping invalid infer request for id 9831, code = 6
[TM][INFO] [forward] Request complete for 9831, code 6

**Comment by xxg98** [comment]
> 128 需要16MB


lmdeploy serve api_server /root/autodl-tmp/projects/LLM/internlm2-chat-7b --server-name 0.0.0.0 --server-port 6006 --tp 1 --session-len 128000 --rope-scaling-factor 2 --cache-max-entry-count 0.15
我在使用以上命令启动internlm2-chat-7b支持128k时，占用了大约22G显存，请问您是调整了哪些参数只占用了16G的显存呢：

**Comment by irexyc** [comment]
对于internlm2-chat-7b，一个kv cache block 的大小是16MB，对应的长度是128，200k的话，显存是 200000 / 128 * 16 / 1024 GB = 24.5G.

> Skipping invalid infer request for id 9831, code = 6

这个log就是6在[这里](https://github.com/InternLM/lmdeploy/blob/7f943a26b69b1e8f80aecb0a660b15eb5719b7b5/src/turbomind/models/llama/Request.h#L37)，就是session_len长度超了的意思。

正常的回答里面是没有 <im_start>, [UNUSED_TOKEN_145] 这些token的，如果有，就像上面说的，是对话模版跟tokenizer不匹配导致的。

**Comment by xxg98** [comment]
> 对于internlm2-chat-7b，一个kv cache block 的大小是16MB，对应的长度是128，200k的话，显存是 200000 / 128 * 16 / 1024 GB = 24.5G.
> 
> > Skipping invalid infer request for id 9831, code = 6
> 
> 这个log就是6在[这里](https://github.com/InternLM/lmdeploy/blob/7f943a26b69b1e8f80aecb0a660b15eb5719b7b5/src/turbomind/models/llama/Request.h#L37)，就是session_len长度超了的意思。
> 
> 正常的回答里面是没有 <im_start>, [UNUSED_TOKEN_145] 这些token的，如果有，就像上面说的，是对话模版跟tokenizer不匹配导致的。


128k长度照这个公式算应该是15.6GB，但是实际上占用了22GB，是我哪里的参数没有调整对吗？

**Comment by irexyc** [comment]
显存的大小约等于 模型的显存 + kvcache 显存，kvcache 可以通过 cache-max-entry-count控制，你用的版本代表总量的百分比。如果你设置0.15，那么kv cache用的是 24 * 0.15，其他的是模型占用的。

**Comment by xxg98** [comment]
> 显存的大小约等于 模型的显存 + kvcache 显存，kvcache 可以通过 cache-max-entry-count控制，你用的版本这个值代表总量的百分比，下个版本含义会变，最上面有提到。
> 
> 当前版本如果你设置0.15，那么kv cache用的是 24 * 0.15，其他的是模型占用的。


我好像明白您的意思了如果我要推理128k，就意味着kv cache要满足15.6GB，而这个大小是需要通过cache-max-entry-count来调整的，因此24 * 0.15 = 3.6GB实际上只能支持到大约32k左右，internlm2-chat-7b占用了19GB
