### ISSUE TITLE
[Feature]支持百川13b 4位量化么 

### ISSUE THREAD

**Issue by duliangang** [InternLM/lmdeploy#1089]
### Motivation

https://huggingface.co/baichuan-inc/Baichuan2-13B-Chat-4bits

**Comment by lvhan028** [comment]
可以支持baichuan2-13b的量化，不过lmdeploy还不支持baichuan2-13b的推理。因为其中的alibi在现在的代码结构中不是那么好加。等近期重构之后，我们会加上来
