### ISSUE TITLE
有没有不用docker部署的方案

### ISSUE THREAD

**Issue by djkcyl** [InternLM/lmdeploy#110]
我想直接在机器上跑，不用docker，能否实现

**Comment by lvhan028** [comment]
你可以使用 lmdeploy/pytorch/chat.py

**Comment by djkcyl** [comment]
我没说清楚，我想在机器上不用docker起一个docker里的那种api服务，然后用webui

**Comment by tpoisonooo** [comment]
这里有个 dockerfile， 按内容把自己的设备配置一下。 https://github.com/InternLM/lmdeploy/blob/main/docker/Dockerfile

**Comment by tpoisonooo** [comment]
安装过啥，dockerfile 里都写了。

**Comment by APX103** [comment]
作为补充，tritonserver:22.12-py3这个镜像中已有环境配置并没有写在dockerfile中。

根据[镜像对应的release文档](https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel-22-12.html#rel-22-12)可以看出它的运行环境、软件版本

![image](https://github.com/InternLM/lmdeploy/assets/61487970/4324b59d-34ee-4683-8eaf-2fbfc0b9692d)

也许会有帮助。

**Comment by lvhan028** [comment]
@AllentDan app.py直接封装turbomind的python api吧，不再和triton Inference server交互了

**Comment by AllentDan** [comment]
PR #162
