### ISSUE TITLE
加载本地InternLM2模型报错

### ISSUE THREAD

**Issue by syp1997** [InternLM/lmdeploy#1102]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

'./internlm2-chat-20b/'是我把模型下载后存在本地的路径

pipe = pipeline('./internlm2-chat-20b/')
response = pipe(['Hi, pls intro yourself', 'Shanghai is'])

ValueError: Unrecognized configuration class <class 'transformers_modules.internlm2-chat-20b.configuration_internlm2.InternLM2Config'> to build an AutoTokenizer.

### Reproduction

pipe = pipeline('./internlm2-chat-20b/')
response = pipe(['Hi, pls intro yourself', 'Shanghai is'])

### Environment

```Shell
torch 2.0.0
lmdeploy 0.2.2
transformers 4.37.2
```

**Comment by lvhan028** [comment]
Hi, 麻烦先用以下代码验证 internl2-chat-20b 的 tokenizer 是否正常
``` python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('./internlm2-chat-20b', trust_remote_code=True)
```

**Comment by syp1997** [comment]
检查后 发现模型没下载完整 现在已经解决
