### ISSUE TITLE
[Bug] api_serve方式部署internLM2-20b-chat模型时，输出中断

### ISSUE THREAD

**Issue by LeonG7** [InternLM/lmdeploy#1103]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

用
`CUDA_VILIABLE_DEVICES=0,1 lmdeploy serve api_server ./internlm2-chat-20b-turbomind --server-name 0.0.0.0 --server-port 9002 --tp 2 --rope-scaling-factor 3.0 --cache-max-entry-count 0.5 --session-len 110000`，
部署了模型后，发送一个post请求
```{
    "model": "internlm2-chat-20b",
    "messages": [
        {
            "role": "user",
            "content": "详细介绍中国二十四节气"
        }
    ],
    "stream":false
}```
结果返回到一半就停止了
```
{
    "id": "36",
    "object": "chat.completion",
    "created": 1706855993,
    "model": "internlm2-chat-20b",
    "choices": [
        {
            "index": 0,
            "message": {
                "role": "assistant",
                "content": "中国二十四节气是中国古代农耕文化的重要组成部分，也是世界非物质文化遗产之一。它们是根据太阳在黄道上的位置变化而制定的，反映了自然界中季节、气候和物候等方面的规律。以下是每个节气的详细介绍：\n\n1. **立春**（Lì Chūn）：每年2月3日或4日，标志着春季的开始。此时气温逐渐回暖，万物复苏，春耕开始。\n\n2. **雨水**（Yǔ Shuǐ）：每年2月18日或19日，表示降雨增多，气温回升，田间开始耕作。\n\n3. **惊蛰**（Jīng Zhé）：每年3月5日或6日，意为春雷响动，惊醒蛰伏的昆虫和动物，春耕进入高峰期。\n\n4. **春分**（Chūn Fēn）：每年3月20日或21日，昼夜平分，气温继续回升，植物生长迅速。\n\n5. **清明**（Qīng Míng）：每年4月4日或5日，表示天气晴朗，适合祭祖扫墓和踏青游玩。\n\n6. **谷雨**（Gǔ Yǔ）：每年4月19日或20日，意味着雨水增多，适宜播种谷物。\n\n7. **立夏**（Lì Xià）：每年5月5日或6日，标志着夏季的开始，气温升高，农作物生长旺盛。\n\n8. **小满**（Xiǎo Mǎn）：每年5月20日或21日，表示麦穗开始饱满，但未完全成熟。\n\n9. **芒种**（Máng Zhòng）：每年6月5日或6日，意为麦类成熟，开始收割，同时开始插秧。\n\n10. **夏至**（ Xià Zhì）：每年6月21日或22日，白昼最长，夜晚最短，气温达到最高点。\n\n11. **小暑**（Xiǎo Shǔ）：每年7月7日或8日，表示天气炎热，农作物生长迅速。\n\n12. **大暑**（Dà Shǔ）：每年7月22日或23日，是一年中最热的时候，需注意防暑降温。\n\n13. **立秋**（Lì Qiū）：每年8月7日或8日"
            },
            "finish_reason": "length"
        }
    ],
    "usage": {
        "prompt_tokens": 106,
        "total_tokens": 619,
        "completion_tokens": 513
    }
}
```
显示` "finish_reason": "length"`

### Reproduction



`CUDA_VILIABLE_DEVICES=0,1 lmdeploy serve api_server ./internlm2-chat-20b-turbomind --server-name 0.0.0.0 --server-port 9002 --tp 2 --rope-scaling-factor 3.0 --cache-max-entry-count 0.5 --session-len 110000`

`curl --location --request POST 'http://xxxxxxx/v1/chat/completions' \
--header 'Content-Type: application/json' \
--data-raw '{
    "model": "internlm2-chat-20b",
    "messages": [
        {
            "role": "user",
            "content": "详细介绍中国二十四节气"
        }
    ],
    "max_tokens":10000,
    "stream":false
}'`

### Environment

```Shell
lmdeploy                      0.2.1
transformers                  4.34.0
python                        3.8.18
```

### Error traceback

```Shell
原因是模型启动时max-tokens默认是512，而且没办法在启动服务时设定该值，目前只能修改源码或者在调用服务时增加参数：`"max_tokens":10000`。
```

**Comment by AllentDan** [comment]
使用建议大概浏览器体验下 swagger UI，上面有个参数叫 max_tokens 可以调
