### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Patrick-Ni** [InternLM/lmdeploy#1104]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.

### Describe the bug

模型推理的时候，出现推理时间很长（几乎无法生成），某一张卡的gpu利用率为100%，其他显卡的利用率都是0的情况，该怎么解决？
![image](https://github.com/InternLM/lmdeploy/assets/59468866/ce39a055-f408-419a-a228-31dbadb0fc19)
就像这样，我敢肯定是卡住了，但是不知道哪里卡住了。我之前的想法是设置一个时间监控器，超过一定时间kill掉这个模型并且重新加载model，但是del model似乎无法释放显卡中的显存？

### Reproduction

![image](https://github.com/InternLM/lmdeploy/assets/59468866/295d4bde-8307-4ce9-a24a-cf2af1b55c8e)
![image](https://github.com/InternLM/lmdeploy/assets/59468866/bb27bd19-87a8-4aee-a560-9d2567a44bd3)
[error.txt](https://github.com/InternLM/lmdeploy/files/14136589/error.txt)

### Environment

```Shell
InternLM2-chat-20b，lmdeploy==0.2.2，设备是4卡a100 40g，
```

**Comment by lvhan028** [comment]
我用下面的代码，没有复现你的问题。GPU没有卡主。看你的代码，应该有一个测试集。
能不能分享下完整的数据和代码呢？我直接测试下看看。

```python
from lmdeploy import pipeline, TurbomindEngineConfig, GenerationConfig


with open('benchmark/error.txt', 'r', encoding='utf-8') as f:
    text = f.read()

engine_config = TurbomindEngineConfig(
    session_len=220000, 
    rope_scaling_factor=2.0, 
    tp=4,
    cache_max_entry_count=0.68
)

pipe = pipeline(
    "/workspace/models-140/InternLM/internlm2-chat-20b",
    backend_config=engine_config)

gen_config = GenerationConfig(top_p=0.9,
                              top_k=40,
                              temperature=0.2,
                              max_new_tokens=400)

response = pipe(text, gen_config=gen_config)
print(response)
```
