### ISSUE TITLE
【bug】 使用pipeline加载huggingface模型时指定tp=4但是实际只使用了一张卡

### ISSUE THREAD

**Issue by FelixZhang7** [InternLM/lmdeploy#1106]
### 📚 The doc issue

代码如下

if __name__ == "__main__":
    engine_config = TurbomindEngineConfig(
        session_len=32000, rope_scaling_factor=2.0, tp=4
    )
    pipe = pipeline(
        "/maikelei01/Shanghai_AI_Laboratory/internlm2-chat-20b",
        backend_engine=engine_config）
    gen_config = GenerationConfig(top_p=0.8,
                                  top_k=40,
                                  temperature=0.8,
                                  max_new_tokens=1024)
    response = pipe(prompt, gen_config=gen_config)
    print(response)

**Comment by lvhan028** [comment]
初始化 pipeline的时候，不是 `backend_engine=engine_config`， 而是 `backend_config=engine_config`
