### ISSUE TITLE
InternLM-20b-chat 部署时出现：Failed, NCCL error

### ISSUE THREAD

**Issue by syp1997** [InternLM/lmdeploy#1108]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

Failed, NCCL error /lmdeploy/src/turbomind/utils/nccl_utils.cc:296 'unhandled cuda error (run with NCCL_DEBUG=INFO for details)'
Illegal instruction (core dumped)

### Reproduction

<img width="1240" alt="截屏2024-02-02 下午7 42 10" src="https://github.com/InternLM/lmdeploy/assets/50142167/d4f4101f-9476-4734-84f5-fa2fa6c77b36">

### Environment

```Shell
torch 2.0.0
lmdeploy 0.2.2
transformers 4.37.2
Driver Version: 515.86.01    
CUDA Version: 11.7
```

**Comment by lvhan028** [comment]
设置下环境变量 `export NCCL_DEBUG=INFO`，然后再运行下命令，看下更详细一些的信息是什么呢？

**Comment by syp1997** [comment]
NCCL INFO NET/Plugin : Plugin load (libnccl-net.so) returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory
NCCL INFO NET/Plugin : No plugin found, using internal implementation
NCCL INFO cudaDriverVersion 11070

init.cc:1582 NCCL WARN Cuda failure 'CUDA driver version is insufficient for CUDA runtime version'
Failed, NCCL error /lmdeploy/src/turbomind/utils/nccl_utils.cc:296 'unhandled cuda error (run with NCCL_DEBUG=INFO for details)'
Illegal instruction (core dumped)

**Comment by irexyc** [comment]
@syp1997 

> init.cc:1582 NCCL WARN Cuda failure 'CUDA driver version is insufficient for CUDA runtime version'

应该是cuda driver的版本过低了，可以用nvidia-smi看一下。

<img width="647" alt="image" src="https://github.com/InternLM/lmdeploy/assets/16019484/7e8a9403-ec38-4638-bd04-3925bb508b45">


如果你没有用LD_LIBRARY_PATH指定cuda lib的话，那么默认lmdeploy 会安装一个cuda 11.7的runtime
