### ISSUE TITLE
[Bug] 原来在xtuner chat和app.py中，都可以传递参数的，在lmdeploy chat和lmdeploy的pipeline中如何传参。

### ISSUE THREAD

**Issue by zhanghui-china** [InternLM/lmdeploy#1111]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

对于xtuner训练好的模型，使用 xtuner chat ./merged --temperature 0.8 --top-p 0.8 --repetition-penalty 1.002 --prompt-template internlm2_chat 要传多个参数才能保证输出正常。

现在使用lmdeploy chat和lmdeploy的pipeline不知道怎么传递这些参数，导致输出异常。

### Reproduction

启动lmdeploy server端：
<img width="832" alt="9b61a78fd21c42d5ffca59fd5ea11cc" src="https://github.com/InternLM/lmdeploy/assets/63148804/d79b8c3f-6488-42cf-97ad-267d0f1b45bc">

启动lmdeploy client端并传递参数：
<img width="635" alt="30bb1f2d05724253d12684f2faa8557" src="https://github.com/InternLM/lmdeploy/assets/63148804/9110ea40-7b9e-46ff-ae73-cd92982f738e">

由于相关参数未传递进去，导致输出格式未按要求。

### Environment

```Shell
zhanghui@zhanghui:~/shishen-full$  lmdeploy check_env
/home/zhanghui/anaconda3/envs/lmdeploy021/lib/python3.10/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
sys.platform: linux
Python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3080 Laptop GPU
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.6, V11.6.124
GCC: gcc (Ubuntu 9.5.0-1ubuntu1~22.04) 9.5.0
PyTorch: 2.2.0+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.5  (built against CUDA 11.7)
    - Built with CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF,

LMDeploy: 0.2.2+
transformers: 4.37.2
gradio: Not Found
fastapi: 0.109.0
pydantic: 2.6.0
```

**Comment by zhanghui-china** [comment]
老师给了一个方向：看下GenerationConfig
但是从文档没有看出该怎么传。还麻烦专家告知。

**Comment by zhanghui-china** [comment]
batch.py
```
import lmdeploy

from lmdeploy import pipeline, GenerationConfig, TurbomindEngineConfig

backend_config = TurbomindEngineConfig(tp=2)

gen_config = GenerationConfig(max_new_tokens=1024, top_p=0.8, temperature=0.8, repetition_penalty=1.002)

pipe = lmdeploy.pipeline("./merged")

response = pipe(["您好", "酸菜鱼怎么做?"])

print(response)
```
执行结果：
<img width="797" alt="f695d535811626af0e18cae9c79a053" src="https://github.com/InternLM/lmdeploy/assets/63148804/75c81868-bdc3-48e0-9927-8eb759f23c5a">

但是偶尔也会出现如下结果：
<img width="800" alt="2bdc9746e77e401fc80aa1791172f52" src="https://github.com/InternLM/lmdeploy/assets/63148804/eea30971-1119-4cba-94a0-23e22ac70736">

**Comment by zhanghui-china** [comment]
<img width="799" alt="217e16c01af4d959eea16329541f12d" src="https://github.com/InternLM/lmdeploy/assets/63148804/8fd521d6-d2d0-4cb3-8884-e5533885b74b">

**Comment by zhanghui-china** [comment]
同样的batch.py ，输出不稳定

**Comment by irexyc** [comment]
目前，pipeline 初始化 TurboMind 和 pytorch 两个engine时，如果用户不传 ChatTemplateConfig 对话模版的话，会根据模型的名字(路径)来匹配一个。而你给的路径`./merged` 显然没有办法得到具体应该用哪个对话模版。正常来讲，这里期望一个类似`internlm/internlm2-chat-7b` 或者 `/local_path/to/internlm/internlm2-chat-7b 这样的格式，

你的重复大概率是匹配到错误的模版，而不是GenerationConfig的问题。而且你用的也不对，gen_config你都没有传进去。应该是`response = pipe(["您好", "酸菜鱼怎么做?"], gen_config=gen_config)

建议你这样：
```
import lmdeploy

from lmdeploy import pipeline, GenerationConfig, TurbomindEngineConfig
from lmdeploy.model import ChatTemplateConfig

chat_template_config = ChatTemplateConfig(model_name='xxx') # 替换成你模型用的

pipe = lmdeploy.pipeline("./merged", chat_template_config=chat_template_config)
response = pipe(["您好", "酸菜鱼怎么做?"])



```

**Comment by zhanghui-china** [comment]
好像做了几次确实不需要：
<img width="922" alt="0186a92a65d42ccdcd6287e16e48c8a" src="https://github.com/InternLM/lmdeploy/assets/63148804/c9737222-f438-47ce-8247-9889f9603137">
<img width="923" alt="5255d98c0403e6da75e1ef23e70f31c" src="https://github.com/InternLM/lmdeploy/assets/63148804/c9a75be7-60b4-4437-b8ee-26cba28f9467">

**Comment by zhanghui-china** [comment]
把 gen_config加上去：
···
import lmdeploy

from lmdeploy import pipeline, GenerationConfig, TurbomindEngineConfig

from lmdeploy.model import ChatTemplateConfig

backend_config = TurbomindEngineConfig(tp=2)

chat_template_config = ChatTemplateConfig(model_name='internlm-chat-7b') # 替换成你模型用的

gen_config = GenerationConfig(max_new_tokens=1024, top_p=0.8, temperature=0.8, repetition_penalty=1.002)

pipe = lmdeploy.pipeline("./merged", chat_template_config=chat_template_config)

response = pipe(["酸菜鱼怎么做"], gen_config=gen_config)
#response = pipe(["酸菜鱼怎么做"])

print(response)
···

好像也能成功：
<img width="923" alt="33408117bcff4edb5e0e68bdaf29e7d" src="https://github.com/InternLM/lmdeploy/assets/63148804/55c3ccd8-3c61-4d59-96d5-3b00d0147aa8">

**Comment by zhanghui-china** [comment]
另外,lmdeploy chat如何传上述的参数呢？

**Comment by zhanghui-china** [comment]
抱歉，发现一个奇怪的现象：对于二代微调后的模型
当pipeline只有1个对话时：
···
import lmdeploy
from lmdeploy import pipeline, GenerationConfig, TurbomindEngineConfig
from lmdeploy.model import ChatTemplateConfig

backend_config = TurbomindEngineConfig(tp=2)

chat_template_config = ChatTemplateConfig(model_name='internlm2-chat-7b') # 替换成你模型用的

gen_config = GenerationConfig(max_new_tokens=1024, top_p=0.8, temperature=0.8, repetition_penalty=1.002)

pipe = lmdeploy.pipeline("./merged", chat_template_config=chat_template_config)

response = pipe(["酸菜鱼怎么做"], gen_config=gen_config)

print(response)
···
基本上还算正常的：
![image](https://github.com/InternLM/lmdeploy/assets/63148804/0401eb1b-5e9d-40ff-a77a-78eada0fc2cd)
![image](https://github.com/InternLM/lmdeploy/assets/63148804/609017bf-0f90-439b-9752-f7b94d6e5892)

但是换成多个对话：
···
import lmdeploy
from lmdeploy import pipeline, GenerationConfig, TurbomindEngineConfig
from lmdeploy.model import ChatTemplateConfig

backend_config = TurbomindEngineConfig(tp=2)

chat_template_config = ChatTemplateConfig(model_name='internlm2-chat-7b') # 替换成你模型用的

gen_config = GenerationConfig(max_new_tokens=1024, top_p=0.8, temperature=0.8, repetition_penalty=1.002)

pipe = lmdeploy.pipeline("./merged", chat_template_config=chat_template_config)

response = pipe(["酸菜鱼怎么做","水煮肉片怎么做","蚂蚁上树的做法","小笼包怎么做"], gen_config=gen_config)
#response = pipe(["酸菜鱼怎么做","水煮肉片怎么做","蚂蚁上树的做法","小笼包怎么做"])

print(response)
···
<img width="924" alt="81a12eaf7a867be9d9f26cebeec6fa0" src="https://github.com/InternLM/lmdeploy/assets/63148804/88f7a94f-35ce-4ef1-9a01-c5d797475a57">
<img width="936" alt="29aaea704a3d014273e1b332021f201" src="https://github.com/InternLM/lmdeploy/assets/63148804/147ea95d-655b-4f10-867c-a99558e63b3b">

再试一次：
<img width="920" alt="8eddbc9395aae475a0c08a16bed15a3" src="https://github.com/InternLM/lmdeploy/assets/63148804/992613b8-da1c-42e0-b57d-856cfa786cd6">

<img width="932" alt="5d83a3b98a4f210d37d4c290d06387a" src="https://github.com/InternLM/lmdeploy/assets/63148804/1f4ca210-27bf-4642-88c1-65966b0120fd">

**Comment by zhanghui-china** [comment]
另外试了下官方的二代模型：
pipe = lmdeploy.pipeline("./internlm2-chat-7b", chat_template_config=chat_template_config)
其他不变：

![image](https://github.com/InternLM/lmdeploy/assets/63148804/33635a55-7bb2-4154-bfb9-6159ee679c18)

**Comment by zhanghui-china** [comment]
试了下官方的一代模型：
pipe = lmdeploy.pipeline("./internlm-chat-7b", chat_template_config=chat_template_config)
其他不变：

![image](https://github.com/InternLM/lmdeploy/assets/63148804/73b08e9e-f172-43c7-9be8-6f07ecfeceee)

**Comment by zhanghui-china** [comment]
使用pipeline试一下：

vi pipeline.py
```
# 推理 lmdeploy 空间下的模型
from lmdeploy import pipeline, TurbomindEngineConfig, ChatTemplateConfig
pipe = pipeline("./merged-4bit",
                backend_config=TurbomindEngineConfig(model_format='awq'),
                chat_template_config=ChatTemplateConfig(model_name='internlm-chat-7b')
                )

response = pipe(["酸菜鱼怎么做", "水煮鱼怎么做"])
print(response)
```

python pipeline.py
```
(lmdeploy021) zhanghui@zhanghui:~/shishen-full$ python pipeline.py
/home/zhanghui/anaconda3/envs/lmdeploy021/lib/python3.10/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
model_source: hf_model
model_config:

[llama]
model_name = base
tensor_para_size = 1
head_num = 32
kv_head_num = 32
vocab_size = 103168
num_layer = 32
inter_size = 11008
norm_eps = 1e-06
attn_bias = 1
start_id = 1
end_id = 2
session_len = 2056
weight_type = int4
rotary_embedding = 128
rope_theta = 10000.0
size_per_head = 128
group_size = 128
max_batch_size = 128
max_context_token_num = 1
step_length = 1
cache_max_entry_count = 0.8
cache_block_seq_len = 128
cache_chunk_size = -1
num_tokens_per_iter = 0
max_prefill_iters = 1
extra_tokens_per_iter = 0
use_context_fmha = 1
quant_policy = 0
max_position_embeddings = 2048
rope_scaling_factor = 0.0
use_logn_attn = 0


get 419 model params
[WARNING] gemm_config.in is not found; using default GEMM algo
[Response(text="您需要准备以下食材:\n['1条草鱼', '1袋酸菜', '5克盐', '2勺料酒', '2勺淀粉', '1根葱', '5片姜', '1个鸡蛋', '10克胡椒粉', '5克糖', '1勺老抽', '3瓣蒜', '2个干辣椒', '2个小米椒', '1勺豆瓣酱']\n按以下方法制作:\n['草鱼洗干净，切块，用料酒，盐，淀粉，胡椒粉，鸡蛋清，腌制半小时', '姜，蒜，小米椒，干辣椒，切好备用', '酸菜洗干净，切好备用', '锅里放油，油热后放姜，蒜，小米椒，干辣椒，炒香后放豆瓣酱，炒出红油，加水，放酸菜，放鱼块，煮熟后放葱花， 起锅']", generate_token_len=167, session_id=0, finish_reason='stop'), Response(text="您需要准备以下食材:\n['2片姜', '1勺料酒', '1勺盐', '1勺胡椒粉', '1勺淀粉', '1勺酱油', '1勺豆瓣酱', '1条鱼', '1勺油', '1勺干辣椒', '1勺花椒', '1根香菜', '1个鸡蛋', '1根葱', '1勺鸡精', '1勺醋', '1勺火锅底料', '1个土豆', '1个豆腐']\n按以下方法制作:\n['鱼清洗干净，切片，加入料酒，盐，胡椒粉，淀粉，鸡蛋，抓匀，腌制10分钟', '锅中放油，加入葱姜，花椒，干辣椒，火锅底料，豆 瓣酱，炒香，加入水，烧开，加入土豆，豆腐，煮2分钟，捞出，放入盆中', '锅中放油，加入葱姜，花椒，干辣椒，火锅底料，豆瓣酱，炒香，加入水，烧开，加入鱼，煮2分钟，捞出，放入盆中', '撒上香菜，葱，即可']", generate_token_len=213, session_id=1, finish_reason='stop')]
```

看起来基本满足要求。

**Comment by zhanghui-china** [comment]
二代：
vi pipeline.py

# 推理 lmdeploy 空间下的模型
from lmdeploy import pipeline, TurbomindEngineConfig, ChatTemplateConfig
pipe = pipeline("./merged-4bit",
                backend_config=TurbomindEngineConfig(model_format='awq'),
                chat_template_config=ChatTemplateConfig(model_name='internlm2-chat-7b')
                )

response = pipe(["酸菜鱼怎么做", "水煮鱼怎么做"])
print(response)
python pipeline.py

···
(lmdeploy021) zhanghui@zhanghui:~/shishen2-full$ python pipeline.py
/home/zhanghui/anaconda3/envs/lmdeploy021/lib/python3.10/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
model_source: hf_model
model_config:

[llama]
model_name = base
tensor_para_size = 1
head_num = 32
kv_head_num = 8
vocab_size = 92544
num_layer = 32
inter_size = 14336
norm_eps = 1e-05
attn_bias = 0
start_id = 1
end_id = 2
session_len = 2056
weight_type = int4
rotary_embedding = 128
rope_theta = 1000000.0
size_per_head = 128
group_size = 128
max_batch_size = 128
max_context_token_num = 1
step_length = 1
cache_max_entry_count = 0.8
cache_block_seq_len = 128
cache_chunk_size = -1
num_tokens_per_iter = 0
max_prefill_iters = 1
extra_tokens_per_iter = 0
use_context_fmha = 1
quant_policy = 0
max_position_embeddings = 32768
rope_scaling_factor = 0.0
use_logn_attn = 0


get 355 model params
[WARNING] gemm_config.in is not found; using default GEMM algo
[Response(text="您需要准备以下食材:\n['1条草鱼', '1勺淀粉', '1勺料酒', '1勺生抽', '1勺盐', '1勺黑胡椒', '1个鸡蛋', '1把酸菜', '1个小米椒', '1勺姜', '1 勺醋', '1勺糖', '1勺油', '1勺老抽', '1勺蚝油', '1勺豆瓣酱', '1勺葱']\n按以下方法制作:\n['草鱼洗净，鱼骨和鱼段分开。', '鱼骨用料酒、生抽、淀粉、黑胡椒、盐、姜腌渍10分钟。', '鱼段用生抽、淀粉、黑胡椒、盐、姜腌渍10分钟。', '腌渍好后，将鱼段和鱼骨分别放入热油锅炸熟。', '另起锅，放少许油，加入姜、葱、小米 椒、酸菜、豆瓣酱，炒出香味。', '加入开水，放入鱼骨，大火煮10分钟。', '加入鱼段，煮5分钟。', '放盐和糖调味。', '出锅。']", generate_token_len=226, session_id=0, finish_reason='stop'), Response(text="您需要准备以下食材:\n['1勺淀粉', '1勺辣椒面', '5个干辣椒', '1勺生抽', '1勺老抽', '1勺蚝油', '1勺糖', '1 勺醋', '1勺料酒', '1勺胡椒粉', '1勺豆瓣酱', '1勺盐', '1勺味精', '1勺白糖', '1勺白芝麻', '1勺老抽', '1勺淀粉', '1勺生抽', '1勺料酒', '1勺胡椒粉', '1勺盐', '1勺味精', '1勺白糖', '1勺淀粉', '1勺生抽', '1勺老抽', '1勺料酒', '1勺胡椒粉', '1勺盐', '1勺味精', '1勺白糖', '1勺淀粉', '1勺生抽', '1勺老抽', '1勺 料酒', '1勺胡椒粉', '1勺盐', '1勺味精', '1勺白糖', '1勺淀粉', '1勺生抽', '1勺老抽', '1勺料酒', '1勺胡椒粉', '1勺盐', '1勺味精', '1勺白糖', '1勺淀粉', '1勺生抽', '1勺老抽', '1勺料酒', '1勺胡椒粉', '1勺盐', '1勺味精', '1勺白糖', '1勺淀粉', '1勺生抽', '1勺老抽', '1勺料酒', '1勺胡椒粉', '1勺盐', '1勺味精', '1勺白糖', '1勺淀粉', '1勺生抽', '1勺老抽', '1勺料酒', '1勺胡椒粉', '1勺盐', '1勺味精', '1勺白糖', '1勺淀粉', '1勺生抽', '1勺老抽', '1勺料酒', '1勺胡椒粉', '1勺盐', '1勺味精', '1勺白糖', '1勺淀粉', '1勺生抽', '1勺老抽', '1勺料酒', '1勺胡椒粉', '1勺盐', '1勺味精', '1勺白糖', '1勺淀粉', '1勺生抽', '1 勺老抽', '1勺料酒', '1勺胡椒粉', '1勺盐', '1勺味精', '1勺白糖', '1勺淀粉', '1勺生抽', '1勺老抽', '1勺料酒', '1勺胡椒粉', '1勺盐', '1", generate_token_len=513, session_id=1, finish_reason='length')]
···
<img width="695" alt="7e648afb3b3c5725ea526e94559fefe" src="https://github.com/InternLM/lmdeploy/assets/63148804/6a8cd094-2a7b-4b57-97b6-465e2c104d8f">
可能还是因为 一些参数无法输入导致 循环。
