### ISSUE TITLE
[Bug] 推理时能否加上history字段呢

### ISSUE THREAD

**Issue by forest-sys** [InternLM/lmdeploy#1112]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

是否可以像以下代码一样在推理时加上history字段呢
tokenizer = AutoTokenizer.from_pretrained(model_dir, device_map="auto", trust_remote_code=True)
# `torch_dtype=torch.float16` 可以令模型以 float16 精度加载，否则 modelscope 会将模型加载为 float32，导致显存不足
model = AutoModelForCausalLM.from_pretrained(model_dir, device_map="auto",  trust_remote_code=True, torch_dtype=torch.float16)
model = model.eval()
length = 0
for response, history in model.stream_chat(tokenizer, "你好", history=[]):
    print(response[length:], flush=True, end="")
    length = len(response)

### Reproduction

-

### Environment

```Shell
-
```

**Comment by lvhan028** [comment]
lmdeploy 的推理是有状态的推理，对话历史都会记录下来的，所以不需要传入history

**Comment by forest-sys** [comment]
那lmdeploy 的推理最多可以支持多少轮次的对话呢？

**Comment by lvhan028** [comment]
直到达到最大的上下文长度 `session_len`

**Comment by lvhan028** [comment]
我之前的表述不准确。
有状态推理在引擎侧是支持的。pipeline接口并没有暴露出来。
暴露出来的接口是 api_server，可以参考这份文档：
https://lmdeploy.readthedocs.io/en/latest/serving/api_server.html#integrate-with-lmdeploy-apiclient

我们后续是考虑在 pipeline 侧开放相关功能

**Comment by KooSung** [comment]
@lvhan028 请问怎么不使用history，每次都是单轮对话呢？

**Comment by lvhan028** [comment]
如果使用 api_server 的 API "v1/chat/completions" 和 `v1/completions`，请求中的 `messages` 可以加入历史记录
pipeline 接口也可以用这种方式传入历史信息。我们在文档 https://lmdeploy.readthedocs.io/en/latest/inference/pipeline.html 中提供了 "An example for OpenAI format prompt input:"，供参考。

除了上面的方法外，LMDeploy 的推理引擎是支持交互式推理的（有状态推理）。在多轮对话中，用户每次只用把当前轮次的请求传入就好。历史信息已经被引擎存下来了。只不过，这个接口目前没有在 pipeline 层面开放
