### ISSUE TITLE
请问使用lmdeploy部署时如何指定显卡

### ISSUE THREAD

**Issue by ChingKwanCheung** [InternLM/lmdeploy#1113]
我想在指定的显卡上部署模型（比如总共有8张卡，我想在3号卡上部署），实现类似import os
os.environ["CUDA_VISIBLE_DEVICES"] = "3"的功能，请问有相关的参数吗？

**Comment by lvhan028** [comment]
lmdeploy的接口不提供device_id的参数。
你可以在通过环境变量先设置好 export CUDA_VISIBLE_DEVICES="0,1"，然后再使用 lmdeploy 的各功能

**Comment by lvhan028** [comment]
lmdeploy的接口不提供device_id的参数。
你可以在通过环境变量先设置好 export CUDA_VISIBLE_DEVICES="0,1"，然后再使用 lmdeploy 的各功能

**Comment by yungongzi** [comment]
Linux下 可以通过命令行增加 **CUDA_VISIBLE_DEVICES="1"** ‘
例子：CUDA_VISIBLE_DEVICES="1" lmdeploy serve gradio model_path_or_name
