### ISSUE TITLE
[Docs] Any example for using S-LoRA?

### ISSUE THREAD

**Issue by sleepwalker2017** [InternLM/lmdeploy#1114]
### 📚 The doc issue

I see lmdeploy has supported S-LoRA but I can't find any documentation introducing this feature. Any example for this? Thank you.

**Comment by grimoire** [comment]
load model and adapters
```python
from lmdeploy.messages import PytorchEngineConfig
from lmdeploy.pytorch.engine.engine import Engine
adapters = {'adapter0':'/path/to/adapter0', 'adapter1':'/path/to/adapter1'}
engine_config = PytorchEngineConfig(adapters=adapters)
engine = Engine.from_pretrained(model_path,
                                engine_config=engine_config,
                                trust_remote_code=True)
```

enable adapters
```python
generator = engine.create_instance()

for outputs in generator.stream_infer(session_id=session_id,
                                      input_ids=input_ids,
                                      gen_config=gen_config,
                                      adapter_name='adapter0'):
    # read outputs

# close session and release caches
generator.end(session_id)
```

Note that this is an inner API, pipeline and service API would be coming soon.

**Comment by sleepwalker2017** [comment]
> load model and adapters
> 
> ```python
> from lmdeploy.messages import PytorchEngineConfig
> from lmdeploy.pytorch.engine.engine import Engine
> adapters = {'adapter0':'/path/to/adapter0', 'adapter1':'/path/to/adapter1'}
> engine_config = PytorchEngineConfig(adapters=adapters)
> engine = Engine.from_pretrained(model_path,
>                                 engine_config=engine_config,
>                                 trust_remote_code=True)
> ```
> 
> enable adapters
> 
> ```python
> generator = engine.create_instance()
> 
> for outputs in generator.stream_infer(session_id=session_id,
>                                       input_ids=input_ids,
>                                       gen_config=gen_config,
>                                       adapter_name='adapter0'):
>     # read outputs
> 
> # close session and release caches
> generator.end(session_id)
> ```
> 
> Note that this is an inner API, pipeline and service API would be coming soon.

Hello, I try this code and found the following error:
```
Traceback (most recent call last):
  File "/data/lmdeploy/test.py", line 8, in <module>
    engine = Engine.from_pretrained(model_path,
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/pytorch/engine/engine.py", line 174, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/pytorch/engine/engine.py", line 127, in __init__
    _paging_adapters(adapters,
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/pytorch/engine/engine.py", line 65, in _paging_adapters
    model_agent.paging_adapters(weight_maps)
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/pytorch/engine/model_agent.py", line 501, in paging_adapters
    lora_linears = get_indexed_lora_linears(self.patched_model)
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/pytorch/adapter/adapter.py", line 62, in get_indexed_lora_linears
    index = _get_layer_index(name, config)
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/pytorch/adapter/adapter.py", line 39, in _get_layer_index
    from peft.utils.other import COMMON_LAYERS_PATTERN
ImportError: cannot import name 'COMMON_LAYERS_PATTERN' from 'peft.utils.other' (/usr/local/lib/python3.10/dist-packages/peft/utils/other.py)
```

peft.__version__ is 0.8.2.

How can I fix this?

**Comment by grimoire** [comment]
It seems that peft update crashed my logic. Try downgrade peft to 0.7.1.

**Comment by sleepwalker2017** [comment]
> It seems that peft update crashed my logic. Try downgrade peft to 0.7.1.

Thank you. It works.

**Comment by sleepwalker2017** [comment]
> load model and adapters
> 
> ```python
> from lmdeploy.messages import PytorchEngineConfig
> from lmdeploy.pytorch.engine.engine import Engine
> adapters = {'adapter0':'/path/to/adapter0', 'adapter1':'/path/to/adapter1'}
> engine_config = PytorchEngineConfig(adapters=adapters)
> engine = Engine.from_pretrained(model_path,
>                                 engine_config=engine_config,
>                                 trust_remote_code=True)
> ```
> 
> enable adapters
> 
> ```python
> generator = engine.create_instance()
> 
> for outputs in generator.stream_infer(session_id=session_id,
>                                       input_ids=input_ids,
>                                       gen_config=gen_config,
>                                       adapter_name='adapter0'):
>     # read outputs
> 
> # close session and release caches
> generator.end(session_id)
> ```
> 
> Note that this is an inner API, pipeline and service API would be coming soon.

S-LoRA is only supported by torch engine? The torch engine uses pytorch to run inference?

**Comment by grimoire** [comment]
> S-LoRA is only supported by torch engine? The torch engine uses pytorch to run inference?

For now, Yes.

TorchEngine is based on the `transformers` implementation with extra features and optimizations. Some layers would be fused with the help of triton language.

**Comment by lvhan028** [comment]
Not much lower.
PyTorch engine can achieve 11 req/s throughput with llama2-7b model, which is much faster than vLLM.

**Comment by sleepwalker2017** [comment]
> Not much lower. PyTorch engine can achieve 11 req/s throughput with the llama2-7b model, which is much faster than vLLM. It is very convenient for developers to support new LLM models and perform experimental features because it is developed purely by Python.
> 
> We have no plans to support s-lora in the turbomind backend yet.

I see. Do you mean this comparison?  I see vllm is 9.35 and turbomind is 14.42.  So pytorch backend is between them. 

![image](https://github.com/InternLM/lmdeploy/assets/26128514/e4633c12-9e41-4413-9ee3-dfd165095e5d)

**Comment by lvhan028** [comment]
Yes
