### ISSUE TITLE
benchmark中的profile_generation可否修改一下获得精确的FTL

### ISSUE THREAD

**Issue by ehuaa** [InternLM/lmdeploy#1117]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

目前的profile_generation中stream_infer返回的结果的token数不一定为1，可能是任意个数的。
![image](https://github.com/InternLM/lmdeploy/assets/5137359/ebf8f663-af91-400d-86d6-8b94e37eda74)

这里有两个问题：
1）有没有什么方法修改代码可以获得精确的FTL
2）能解释下为啥stream_infer函数 yield出来的不一定是一个个token么，可能是跳跃的，比较好奇背后的原因，谢谢

### Reproduction

python3 profile_generation.py <model_path> <optional arguments>

### Environment

```Shell
v100 * 8
```

**Comment by ehuaa** [comment]
@lvhan028 麻烦大佬帮忙看看谢谢，是因为多个Thread往里面put数据可能速度过快，所以先丢掉老数据么 
![219f07a44b0e198d6eb534d3f045fb4](https://github.com/InternLM/lmdeploy/assets/5137359/9809cb48-f564-465c-8273-4d2b159e7741)

**Comment by lvhan028** [comment]
是的。
