### ISSUE TITLE
[Bug] internlm-chat-20b 量化后转换格式报错 UnboundLocalError: local variable 'head_num' referenced before assignment

### ISSUE THREAD

**Issue by xiangchunyan** [InternLM/lmdeploy#1127]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.

### Describe the bug

通过 `lmdeploy lite auto_awq ` 获取量化后的模型，然后通过以下命令将量化后的模型转换格式的时候报错。
```
lmdeploy convert internlm-chat-20b ./internlm2-chat-20b-4bit-sft-0202 \
  --model-format awq \
  --tp 2 \
  --dst-path ./internlm2-chat-20b-4bit-sft-0202-turbomind \
  --group-size 128
```

### Reproduction

先通过如下命令量化模型
```
export HF_MODEL=internlm2-chat-20b-sft-0202
export WORK_DIR=internlm2-chat-20b-4bit-sft-0202

lmdeploy lite auto_awq \
   $HF_MODEL \
  --calib-dataset 'ptb' \
  --calib-samples 128 \
  --calib-seqlen 4096 \
  --w-bits 4 \
  --w-group-size 128 \
  --work-dir $WORK_DIR
```

然后通过如下命令转换格式
```
lmdeploy convert internlm-chat-20b ./internlm2-chat-20b-4bit-sft-0202 \
  --model-format awq \
  --tp 2 \
  --dst-path ./internlm2-chat-20b-4bit-sft-0202-turbomind \
  --group-size 128
```

报错如下
Traceback (most recent call last):                                                                                                                                  
  File "/opt/conda/envs/xtuner-env/bin/lmdeploy", line 8, in <module>                                                                                               
    sys.exit(run())                                                                                                                                                 
  File "/opt/conda/envs/xtuner-env/lib/python3.10/site-packages/lmdeploy/cli/entrypoint.py", line 18, in run                                                        
    args.run(args)
  File "/opt/conda/envs/xtuner-env/lib/python3.10/site-packages/lmdeploy/cli/cli.py", line 100, in convert
    main(**kwargs)
  File "/opt/conda/envs/xtuner-env/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/converter.py", line 286, in main
    output_model = OUTPUT_MODELS.get(output_format)(input_model=input_model,
  File "/opt/conda/envs/xtuner-env/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/w4.py", line 80, in __init__
    super().__init__(input_model, cfg, to_file, out_dir)
  File "/opt/conda/envs/xtuner-env/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 141, in __init__
    self.cfg = self.get_config(cfg)
  File "/opt/conda/envs/xtuner-env/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/w4.py", line 84, in get_config
    final_cfg = super().get_config(cfg).__dict__
  File "/opt/conda/envs/xtuner-env/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 166, in get_config
    final_cfg.update(dict(head_num=head_num, vocab_size=_vocab_size))
UnboundLocalError: local variable 'head_num' referenced before assignment

### Environment

```Shell
sys.platform: linux
Python: 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3: NVIDIA A100-SXM4-40GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.7, V11.7.99
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 2.0.1+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

LMDeploy: 0.2.2+
transformers: 4.36.2
gradio: 3.50.2
fastapi: 0.108.0
pydantic: 2.6.0
```

**Comment by irexyc** [comment]
model_name 写的不对，convert 目前是按照model_name来匹配source model的格式的，应该是 internlm2-chat-20b
```
lmdeploy convert internlm2-chat-20b ./internlm2-chat-20b-4bit-sft-0202 \
  --model-format awq \
  --tp 2 \
  --dst-path ./internlm2-chat-20b-4bit-sft-0202-turbomind \
  --group-size 128
```
