### ISSUE TITLE
[Bug] 0.2.2版本qwen14b量化后回答失控

### ISSUE THREAD

**Issue by LianxinGao** [InternLM/lmdeploy#1131]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

量化前问：你是谁？
回答：
```
我是通义千问，由阿里云开发的AI助手。我可以回答各种问题、提供信息和与用户进行对话。有什么我可以帮助你的吗？
```

量化后问：你是谁？
```
double enter to end input >>> 你是谁？

你是谁？ 02/06 08:15:10 - turbomind - WARNING - kwargs top_p is deprecated for inference, use GenerationConfig instead.
02/06 08:15:10 - turbomind - WARNING - kwargs top_k is deprecated for inference, use GenerationConfig instead.
02/06 08:15:10 - turbomind - WARNING - kwargs temperature is deprecated for inference, use GenerationConfig instead.
02/06 08:15:10 - turbomind - WARNING - kwargs repetition_penalty is deprecated for inference, use GenerationConfig instead.
02/06 08:15:10 - turbomind - WARNING - kwargs ignore_eos is deprecated for inference, use GenerationConfig instead.
02/06 08:15:10 - turbomind - WARNING - kwargs random_seed is deprecated for inference, use GenerationConfig instead.
02/06 08:15:10 - turbomind - WARNING - kwargs request_output_len is deprecated for inference, use GenerationConfig instead.
为什么在这里？”

“我是这里的主人，”小矮人回答，“我在这里生活了很久。你呢？你是从哪里来的？”

“我是从城市里来的，”我回答，“我迷路了，找不到回家的路。”

小矮人看着我，眼神中充满了同情。“我可以帮你找到回家的路，”他说，“但是你必须答应我一件事。”

“什么事？”我问。

“你必须答应我，无论你走到哪里，都要记住这个小矮人的故事，记住他的善良和智慧，记住他的勇气和坚韧。”小矮人说。

我答应了小矮人的请求，他带我走出了森林，找到了回家的路。我永远都不会忘记小矮人的故事，我会将他的故事传递下去，让更多的人知道他的善良和智慧，他的勇气和坚韧。
```

### Reproduction

量化方法：
```
lmdeploy lite auto_awq \
   /data/glx/finetuned_models/m1m2_14b \
  --calib-dataset 'ptb' \
  --calib-samples 128 \
  --calib-seqlen 2048 \
  --w-bits 4 \
  --w-group-size 128 \
  --work-dir ./m1m2-14b-4bit
```

运行：
```
CUDA_VISIBLE_DEVICES=0 lmdeploy chat turbomind ./m1m2-14b-4bit --model-format awq
```

### Environment

```Shell
...
```

**Comment by irexyc** [comment]
应该是只根据`./m1m2-14b-4bit` 没办法匹配到对话模版，试试这样：

CUDA_VISIBLE_DEVICES=0 lmdeploy chat turbomind ./m1m2-14b-4bit --model-format awq --model-name qwen-7b

**Comment by irexyc** [comment]
v0.2.2 turobmind backend启动的时候获取model_name的逻辑跟pytorch backend有点区别。这个在v0.2.3中修复了。预计今天会传一个最新的版本。

如果着急用的话，可以先改一下安装目录中`lmdeploy/serve/async_engine.py` 这个文件，将 `_build_turbomind` 替换为最新的实现 https://github.com/InternLM/lmdeploy/blob/v0.2.3/lmdeploy/serve/async_engine.py#L92-L155

**Comment by LianxinGao** [comment]
> v0.2.2 turobmind backend启动的时候获取model_name的逻辑跟pytorch backend有点区别。这个在v0.2.3中修复了。预计今天会传一个最新的版本。
> 
> 如果着急用的话，可以先改一下安装目录中`lmdeploy/serve/async_engine.py` 这个文件，将 `_build_turbomind` 替换为最新的实现 https://github.com/InternLM/lmdeploy/blob/v0.2.3/lmdeploy/serve/async_engine.py#L92-L155

好的，我等一下pip update

**Comment by LianxinGao** [comment]
@irexyc 那现在外推32k，还需要配置rope_scaling_factor = 2吗？这个现在在哪个文件里面改？以前是config.ini

**Comment by irexyc** [comment]
一般session_len跟max_position_embeddings是一样的。如果初始化的时候不指定，那么会用模型默认的session_len，不需要外推。但是如果你要推理超过session_len的文本，那么还是需要设置的。 

你可以通过 `lmdeploy serve api_server -h` 看参数信息。

另外lmdeploy 目前的外推试下是跟huggingface 对齐的。跟qwen的实现不一样。

**Comment by LianxinGao** [comment]
> 一般session_len跟max_position_embeddings是一样的。如果初始化的时候不指定，那么会用模型默认的session_len，不需要外推。但是如果你要推理超过session_len的文本，那么还是需要设置的。
> 
> 你可以通过 `lmdeploy serve api_server -h` 看参数信息。
> 
> 另外lmdeploy(turbomind backend) 目前的外推实现是跟huggingface 对齐的。跟qwen的实现不一样。

明白了，谢谢～
