### ISSUE TITLE
[Bug] 经过lmdeploy 4bit量化后的模型该如何使用？

### ISSUE THREAD

**Issue by zhanghui-china** [InternLM/lmdeploy#1141]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

我把基于internlm-chat-7b，使用 xtuner train 自制的 zhangxiaobai_shishen_full模型，通过lmdeploy lite量化成  awq的4bit模型后，不知道如何在app.py中调用，还麻烦告知一下。

### Reproduction

微调和生成HF模型命令：
xtuner train ./internlm_chat_7b_qlora_oasst1_e3_copy.py --deepspeed deepspeed_zero2

export MKL_SERVICE_FORCE_INTEL=1
xtuner convert pth_to_hf ./internlm_chat_7b_qlora_oasst1_e3_copy.py ./work_dirs/internlm_chat_7b_qlora_oasst1_e3_copy.py/epoch_1.pth ./hf

xtuner convert merge ./internlm-chat-7b ./hf ./zhangxiaobai_shishen_full --max-shard-size 2GB

4bit量化命令
lmdeploy lite auto_awq ./zhangxiaobai_shishen_full --w-bits 4 --w-group-size 128 --work-dir ./zhangxiaobai_shishen_full-4bit

试了下几种方式：
（1）使用pipeline
···
import torch
from modelscope import AutoTokenizer, AutoModelForCausalLM
from lmdeploy import pipeline, TurbomindEngineConfig, ChatTemplateConfig

model_name_or_path = "./zhangxiaobai_shishen_full_4bit"
pipe = pipeline(model_name_or_path, backend_config=TurbomindEngineConfig(model_format='awq'), chat_template_config=ChatTemplateConfig(model_name='internlm-chat-7b'))

response = pipe(["酸菜鱼怎么做", "水煮鱼怎么做"])
print(response)
···
<img width="1109" alt="7a33a32526b39d3f64d492f400655f4" src="https://github.com/InternLM/lmdeploy/assets/63148804/d7cb68a9-26be-4c80-93d9-0dde8eb42c7f">

貌似只有这种方式是成功的。

（2）使用通常方式
···
import torch
from modelscope import AutoTokenizer, AutoModelForCausalLM

model_name_or_path = "zhanghuiATchina/zhangxiaobai_shishen_full_4bit"

tokenizer = AutoTokenizer.from_pretrained(model_name_or_path, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(model_name_or_path,
        trust_remote_code=True,
        load_in_4bit=True,
        device_map='auto').eval()

response, history = model.chat(tokenizer, "你好", history=[])
print(response)
response, history = model.chat(tokenizer, "酸菜鱼怎么做", history=history)
print(response)
···
等半天会出现如下信息：
<img width="787" alt="a3a688d1a97298cfbdf2b4fa877974c" src="https://github.com/InternLM/lmdeploy/assets/63148804/2572bcbb-a4e4-49b0-837c-7860be63baee">

<img width="787" alt="040d78d61cedf945d5e1c2e25fc5d6b" src="https://github.com/InternLM/lmdeploy/assets/63148804/f4fabd2b-81ea-4e9f-9d1d-b9bce9b9d0bd">

（3）使用bitsandbytes
···
import torch
from modelscope import AutoTokenizer, AutoModelForCausalLM , BitsAndBytesConfig
#from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

model_name_or_path = "zhanghuiATchina/zhangxiaobai_shishen_full_4bit"

bnb_config = BitsAndBytesConfig( load_in_4bit=True,
        bnb_4bit_use_double_quant=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16
)

tokenizer = AutoTokenizer.from_pretrained(model_name_or_path, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(
        model_name_or_path,
        quantization_config=bnb_config,
        trust_remote_code=True,
        device_map='auto'
).eval()

response, history = model.chat(tokenizer, "你好", history=[])
print(response)
response, history = model.chat(tokenizer, "酸菜鱼怎么做", history=history)
print(response)

···

会卡死在这里：
<img width="1110" alt="86ab8c149f3049d263113202a8affe1" src="https://github.com/InternLM/lmdeploy/assets/63148804/db7de3a8-c613-49f8-ba8e-6e4badb2b2c8">

<img width="1122" alt="4339e937b886146bcace79518a0625c" src="https://github.com/InternLM/lmdeploy/assets/63148804/baee05a8-e710-40c3-bd3c-f46b60afdaef">

### Environment

```Shell
(shishen4bit) zhanghui@zhanghui:~/4bit$ pip list |grep lmdeploy
lmdeploy                      0.2.2
(shishen4bit) zhanghui@zhanghui:~/4bit$
```

**Comment by RunningLeon** [comment]
@zhanghui-china you can use lmdeploy.pipeline for offline inference. 
Just make sure:
1. add `model_format='awq` in `TurbomindEngineConfig`
2. Better name the model as `zhanghuiATchina/internlm-chat-7b-4bits` for automatic chat template matching. 
3. You can refer to this doc: https://github.com/InternLM/lmdeploy/blob/v0.2.2/docs/en/inference/pipeline.md

**Comment by lvhan028** [comment]
lmdeploy量化的模型不能直接用transformers进行加载。
可以参考[这篇文档](https://huggingface.co/docs/transformers/quantization)，尝试构造config.json，让transformers可以加载。

**Comment by puffy310** [comment]
@lvhan028, I'm having issues parsing the response variable, do you have any advice?

**Comment by lvhan028** [comment]
@puffy310 Can you share this issue and the reproduction method?
