### ISSUE TITLE
先微调再量化后的模型应当如何正确启动？[Bug] 

### ISSUE THREAD

**Issue by xxg98** [InternLM/lmdeploy#1143]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

我先微调internlm2-chat-7b，然后4bit量化了该微调后模型，具体脚本已于Reproduction给出，有三个疑问：
1. 当使用```lmdeploy chat turbomind ./workspace_quant/```启动量化后的模型，显存占用仍然会达到20多G，在视频课程中只有不到6G，区别在于我用的interlm2，如图：
![image](https://github.com/InternLM/lmdeploy/assets/98906194/98598bdf-1b51-42aa-852f-83ed83c47aa1)

2. 当使用```lmdeploy serve api_server ./workspace_quant --server-name 0.0.0.0 --server-port 6006 --tp 1 --session-len 128000 --rope-scaling-factor 2 --cache-max-entry-count 0.15 --backend turbomind --model-format awq```启动量化后的模型，可以正常回答（幻觉比较大，比如问了武林外传的主演，不能全部答对），显存只占用10G左右。疑问是：这条命令启动的应该是huggingface格式的模型，而workspace_quant目录下的是转换后的模型（非huggingface格式），为啥也能启动呢？

3. 当使用```lmdeploy serve api_server ./quant_output --server-name 0.0.0.0 --server-port 6006 --tp 1 --session-len 128000 --rope-scaling-factor 2 --cache-max-entry-count 0.15```，无法启动量化后的模型。疑问是：quant_output是huggingface格式的，为什么无法启动？报错如下：
![image](https://github.com/InternLM/lmdeploy/assets/98906194/df010aa8-ad3c-403b-a35d-db21629faf05)

### Reproduction

量化微调后的模型过程如下：
lmdeploy lite calibrate \
  /root/autodl-tmp/projects/LLM/fine_tuning/7b/hf_merge/ \
  --calib-dataset "c4" \
  --calib-samples 128 \
  --calib-seqlen 2048 \
  --work-dir ./quant_output
  
  
lmdeploy lite auto_awq \
  /root/autodl-tmp/projects/LLM/fine_tuning/7b/hf_merge/ \
  --w-bits 4 \
  --w-group-size 128 \
  --work-dir ./quant_output
  

lmdeploy convert  internlm2-chat-7b ./quant_output \
    --model-format awq \
    --group-size 128 \
    --dst-path ./workspace_quant

### Environment

```Shell
python=3.10
cuda=12.1
显卡：3090
lmdeploy：最新版本
internlm2-chat-7b：最新版本
```

**Comment by lvhan028** [comment]
1. 当使用lmdeploy chat turbomind ./workspace_quant/启动量化后的模型，显存占用仍然会达到20多G，在视频课程中只有不到6G，区别在于我用的interlm2

lmdeploy的内存分配策略，在近期的几个版本中，发生了一些变更，记录在[这里](https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/inference/pipeline.md#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)。如果参考的是视频教程的话，应该使用的是 v0.2.0 之前的版本。在之前的版本中，lmdeploy 是阶梯式的申请 kv 缓存，不是一下子开辟好。所以感觉使用的内存少


2. 当使用lmdeploy serve api_server ./workspace_quant --server-name 0.0.0.0 --server-port 6006 --tp 1 --session-len 128000 --rope-scaling-factor 2 --cache-max-entry-count 0.15 --backend turbomind --model-format awq启动量化后的模型，可以正常回答（幻觉比较大，比如问了武林外传的主演，不能全部答对），显存只占用10G左右。疑问是：这条命令启动的应该是huggingface格式的模型，而workspace_quant目录下的是转换后的模型（非huggingface格式），为啥也能启动呢？

`--cache-max-entry-count 0.15` 把 kv 缓存比例调低，内存占用就自然变小了。lmdeploy 内部会判断 `workspace_quant` 是 huggingface 模型，还是 turbomind 模型。如果是前者，会加载huggingface模型，然后执行转换过程。如果是后者，就按照 turbomind 模型格式加载

3. 当使用lmdeploy serve api_server ./quant_output --server-name 0.0.0.0 --server-port 6006 --tp 1 --session-len 128000 --rope-scaling-factor 2 --cache-max-entry-count 0.15，无法启动量化后的模型。疑问是：quant_output是huggingface格式的，为什么无法启动？

需要在命令中加入参数 --model-format awq。这样才能告诉 lmdeploy，`quant_output` 是量化后的huggingface 模型。否则，lmdeploy会按照 fp16/bf16 的数据类型读取模型权重。

**Comment by xxg98** [comment]
> 所以感觉使用的内存少


明白了，谢谢您的耐心回答
