### ISSUE TITLE
[Bug] ImportError: DLL load failed while importing _turbomind: 找不到指定的模块

### ISSUE THREAD

**Issue by 909254** [InternLM/lmdeploy#1146]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

`
(my-env) C:\Users\a9092\Downloads\Compressed\internlm2-7b-4bit>lmdeploy serve gradio  .\  --model-format awq --quant-policy 4  --cache-max-entry-count 0.2 --model-name internlm2-chat-7b
C:\Users\a9092\.conda\envs\my-env\Lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\a9092\.conda\envs\my-env\Scripts\lmdeploy.exe\__main__.py", line 7, in <module>
  File "C:\Users\a9092\.conda\envs\my-env\Lib\site-packages\lmdeploy\cli\entrypoint.py", line 18, in run
    args.run(args)
  File "C:\Users\a9092\.conda\envs\my-env\Lib\site-packages\lmdeploy\cli\serve.py", line 214, in gradio
    run(args.model_path_or_server,
  File "C:\Users\a9092\.conda\envs\my-env\Lib\site-packages\lmdeploy\serve\gradio\app.py", line 49, in run
    run_local(model_path_or_server,
  File "C:\Users\a9092\.conda\envs\my-env\Lib\site-packages\lmdeploy\serve\gradio\turbomind_coupled.py", line 159, in run_local
    InterFace.async_engine = AsyncEngine(
                             ^^^^^^^^^^^^
  File "C:\Users\a9092\.conda\envs\my-env\Lib\site-packages\lmdeploy\serve\async_engine.py", line 68, in __init__
    self._build_turbomind(model_path=model_path,
  File "C:\Users\a9092\.conda\envs\my-env\Lib\site-packages\lmdeploy\serve\async_engine.py", line 104, in _build_turbomind
    from lmdeploy.turbomind.utils import \
  File "C:\Users\a9092\.conda\envs\my-env\Lib\site-packages\lmdeploy\turbomind\__init__.py", line 24, in <module>
    from .turbomind import TurboMind  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a9092\.conda\envs\my-env\Lib\site-packages\lmdeploy\turbomind\turbomind.py", line 25, in <module>
    from .deploy.converter import (get_model_format, supported_formats,
  File "C:\Users\a9092\.conda\envs\my-env\Lib\site-packages\lmdeploy\turbomind\deploy\converter.py", line 15, in <module>
    from .target_model.base import OUTPUT_MODELS, TurbomindModelConfig
  File "C:\Users\a9092\.conda\envs\my-env\Lib\site-packages\lmdeploy\turbomind\deploy\target_model\__init__.py", line 3, in <module>
    from .w4 import TurbomindW4Model  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a9092\.conda\envs\my-env\Lib\site-packages\lmdeploy\turbomind\deploy\target_model\w4.py", line 17, in <module>
    import _turbomind as _tm  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing _turbomind: 找不到指定的模块
`

### Reproduction

lmdeploy serve gradio  .\  --model-format awq --quant-policy 4  --cache-max-entry-count 0.2 --model-name internlm2-chat-7b

### Environment

```Shell
win10 
(my-env) C:\Users\a9092\Downloads\Compressed\internlm2-7b-4bit>lmdeploy check_env
C:\Users\a9092\.conda\envs\my-env\Lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
sys.platform: win32
Python: 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]
CUDA available: False
MUSA available: False
numpy_random_seed: 2147483648
MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.39.33519 版
GCC: n/a
PyTorch: 2.1.2+cpu
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192930151
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX512
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /bigobj /FS -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE /utf-8 /wd4624 /wd4068 /wd4067 /wd4267 /wd4661 /wd4717 /wd4244 /wd4804 /wd4273, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=OFF, TORCH_VERSION=2.1.2, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

LMDeploy: 0.2.3+
transformers: 4.37.0
gradio: 3.50.2
fastapi: 0.109.2
pydantic: 2.6.1
```

**Comment by irexyc** [comment]
powershell里面，echo $env:CUDA_PATH 输出的是什么？

**Comment by 909254** [comment]
重装了Torch解决了

**Comment by wangzhongshi** [comment]
我也遇到了同样的问题，可以详细的说一下你是怎么解决的吗？我几乎尝试了所有lmdeploy与pytorch版本的组合

**Comment by irexyc** [comment]
1. 首先查看显卡驱动支持的最高cuda版本，如果使用的cuda runtime比这个版本高的话是不行的。
<img width="662" alt="image" src="https://github.com/InternLM/lmdeploy/assets/16019484/d252a2e6-df2d-4918-b0aa-e41728448c3a">

2. windows 在使用lmdeploy的时候，除了安装lmdeploy外，还需要安装cudatoolkit(cuda runtime)，cudatoolkit的版本需要显卡驱动支持，也需要和lmdeploy编译时用的cuda版本一致。安装完之后，在powershell里面`echo $env:CUDA_PATH` 应该会打印一个路径

3. 从 0.4.0版本之后，通过 `pip install lmdeploy`安装的lmdeploy是使用cuda 12进行编译的，如果要用cuda 11，需要安装release下面的 assets，如https://github.com/InternLM/lmdeploy/releases/tag/v0.4.1  python 3.10的安装命令 `pip install https://github.com/InternLM/lmdeploy/releases/download/v0.4.1/lmdeploy-0.4.1+cu118-cp310-cp310-win_amd64.whl --extra-index-url https://download.pytorch.org/whl/cu118
`

4. 请使用 lmdeploy 0.4.1 或者之后的版本，之前的版本在启动时添加cuda runtime的路径有问题，可能会造成加载turbomind失败。

**Comment by wangzhongshi** [comment]
已经解决感谢大佬
