### ISSUE TITLE
openmmlab/lmdeploy镜像使用方法

### ISSUE THREAD

**Issue by AlexFly666** [InternLM/lmdeploy#1154]
### 📚 The doc issue

大模型推理部署，看到有docker镜像，但支持哪些参数，如何使用，找不到相关文档

### Suggest a potential alternative/fix

提供openmmlab/lmdeploy镜像的使用文档

**Comment by lvhan028** [comment]
@AllentDan 
和 @AlexFly666 沟通过，他希望 lmdeploy 提供类似 vllm 的服务启动方式，

```shell
# vllm
docker run -d --name llm --gpus 1 -it --ipc=host -p 8000:8000 -v /root/fly/samples/0-model/bloom-560m/:/bloom-560m vllm/vllm-openai:latest --tensor-parallel-size 1 --model /bloom-560m --trust-remote-code



curl http://localhost:8000/v1/completions \
    -H "Content-Type: application/json" \
    -d '{
        "model": "/bloom-560m",
        "prompt": "San Francisco is a",
        "max_tokens": 70,
        "temperature": 0
    }'
```
麻烦予以支持下

**Comment by AllentDan** [comment]
应该可以直接用现有的镜像一行命令启动的：
```shell
docker run --name llm --gpus 1 -it --ipc=host -p 23333:23333 -v /root/fly/samples/0-model/bloom-560m/:/bloom-560m openmmlab/lmdeploy:latest lmdeploy serve api_server /bloom-560m --tp 1
```

**Comment by AlexFly666** [comment]
@AllentDan 
更新了最新镜像，运行报错如下
docker run --name llm --gpus 1 -it --ipc=host -p 23333:23333 -v /root/fly/samples/0-model/bloom-560m/:/bloom-560m openmmlab/lmdeploy:latest lmdeploy serve api_server /bloom-560m --tp 1 

=============================
== Triton Inference Server ==
=============================

NVIDIA Release 22.12 (build 50109463)
Triton Server Version 2.29.0

Copyright (c) 2018-2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

/opt/py38/lib/python3.8/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Traceback (most recent call last):
  File "/opt/py38/bin/lmdeploy", line 11, in <module>
    load_entry_point('lmdeploy', 'console_scripts', 'lmdeploy')()
  File "/opt/lmdeploy/lmdeploy/cli/entrypoint.py", line 18, in run
    args.run(args)
  File "/opt/lmdeploy/lmdeploy/cli/serve.py", line 248, in api_server
    run_api_server(args.model_path,
  File "/opt/lmdeploy/lmdeploy/serve/openai/api_server.py", line 1004, in serve
    VariableInterface.async_engine = AsyncEngine(
  File "/opt/lmdeploy/lmdeploy/serve/async_engine.py", line 68, in __init__
    self._build_turbomind(model_path=model_path,
  File "/opt/lmdeploy/lmdeploy/serve/async_engine.py", line 114, in _build_turbomind
    raise ArgumentError('Please set model_name or backend_config.')
TypeError: __init__() missing 1 required positional argument: 'message'

加上message也不行
docker run --name llm --gpus 1 -it --ipc=host -p 23333:23333 -v /root/fly/samples/0-model/bloom-560m/:/bloom-560m openmmlab/lmdeploy:latest lmdeploy serve api_server /bloom-560m --tp 1 --message "San Francisco is a"

**Comment by AllentDan** [comment]
lmdeploy 不支持 bloom 模型。

**Comment by AlexFly666** [comment]
好的，谢谢，我换个其他试试
