### ISSUE TITLE
HTTP client question

### ISSUE THREAD

**Issue by Dimensionzw** [InternLM/lmdeploy#116]
Is there a regular HTTP request client that does not require complex lmdeploy package installation and gRPC calls, nor does it need streaming transmission, returning all answer results in a single response.

**Comment by lvhan028** [comment]
like openai RESTful APIs?

**Comment by Dimensionzw** [comment]
> 像 openai RESTful API 一样？

Yes, this kind of regular HTTP client would be very convenient for use and integration. Also, as a suggestion, the preprocess and postprocess models can be implemented with the Triton framework ensemble mode, so that all steps can be completed with just one request to the interface. Just like the GPT example in the FasterTransformer project.
https://github.com/triton-inference-server/fastertransformer_backend/tree/main/all_models/gpt

**Comment by AllentDan** [comment]
We are working on it now.

**Comment by lichangW** [comment]
Hi I opened the --allow-http=1 option before running the service_docker_up.sh, but "curl -v  http://0.0.0.0:8000/v2/models/llama2" always return "unknown model"（grpc interface works without problem), does it because restful api is not supported now? thank you.
![image](https://github.com/InternLM/lmdeploy/assets/9452272/f9c8df4d-e30e-46bc-a25c-6f3126c85657)

**Comment by AllentDan** [comment]
> Hi I opened the --allow-http=1 option before running the service_docker_up.sh, but "curl -v http://0.0.0.0:8000/v2/models/llama2" always return "unknown model"（grpc interface works well), does it because restful api is not supported now? thank you. ![image](https://user-images.githubusercontent.com/9452272/257514352-f9c8df4d-e30e-46bc-a25c-6f3126c85657.png)

The restful APIs were added. But they are not through triton server. For more details please refer to https://github.com/InternLM/lmdeploy/blob/main/docs/en/restful_api.md
