### ISSUE TITLE
The inference is stuck, possibly occurring before the invocation of the 'forward' method.

### ISSUE THREAD

**Issue by alexw994** [InternLM/lmdeploy#117]
Hello, I have run the service successfully. However, when I use the app 'lmdeploy.app.py' and send a message to the server, I notice that the inference gets stuck.

These are the logs of Tritonserver.
```
[TM][INFO] [forward][rank=0] INPUT: step [1]
[TM][INFO] [forward][rank=0] INPUT: repetition_penalty [1]
[TM][INFO] [forward][rank=0] INPUT: temperature [1]
[TM][INFO] [forward][rank=0] INPUT: STOP [1]
[TM][INFO] [forward][rank=0] INPUT: START [1]
[TM][INFO] [forward][rank=0] INPUT: random_seed [1]
[TM][INFO] [forward][rank=0] INPUT: input_ids [1, 15]
[TM][INFO] [forward][rank=0] INPUT: stop_words_list [1, 2, 2]
[TM][INFO] [forward][rank=0] INPUT: runtime_top_p [1]
[TM][INFO] [forward][rank=0] INPUT: END [1]
[TM][INFO] [forward][rank=0] INPUT: input_lengths [1]
[TM][INFO] [forward][rank=0] INPUT: CORRID [1]
[TM][INFO] [forward][rank=0] INPUT: request_output_len [1, 1]
[TM][INFO] [forward][rank=0] INPUT: session_len [1]
[TM][INFO] [forward][rank=0] OUTPUT: sequence_length [1, 1]
[TM][INFO] [forward][rank=0] OUTPUT: output_ids [1, 1, 2056]
[TM][INFO] [forward] Enqueue requests
[TM][INFO] [forward] Wait for requests to complete ...
[TM][INFO] [synchronize] batch_size = 0
[TM][INFO] [LlamaCacheManager][create] 140002462050048
[TM][INFO] [LlamaCacheManager][allocate]
[TM][INFO] [LlamaCacheManager][allocate] free = 0
[TM][INFO] [init] infer_request_count = 1
[TM][INFO] [init] batch_size = 1
[TM][INFO] [init] session_len = 2056
[TM][INFO] [init] max_input_length = 15
[TM][INFO] [init] max_context_len = 15
[TM][INFO] [init] slot  sequence_id  history_len  input_len  context_len  tmp_input_len  token_ids.size  cache_len
[TM][INFO] [init]    0   3708069632            0         15           15             15               0          0
[TM][INFO] [decodeContext] base = 0, count = 1
[TM][INFO] [decodeContext] offset = 0, batch_size = 1, token_num = 14, max_input_len = 14, max_context_len = 14
[TM][INFO] context decoding start
```
Based on the source code, I believe it might be stuck before the 'forward' method. 
https://github.com/InternLM/lmdeploy/blob/4b3458f70afd4e5fb22ecbbee41577a2e352cfd9/src/turbomind/models/llama/LlamaV2.cc#L209

Could you give me some advice? Thanks.

**Comment by AllentDan** [comment]
Could you please share the device information you used?

**Comment by alexw994** [comment]
> Could you please share the device information you used? Did the cli client work fine?

I have two P100 cards, and I split the tensor across these two cards.
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  On   | 00000000:00:09.0 Off |                    0 |
| N/A   31C    P0    32W / 250W |   8974MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE...  On   | 00000000:00:0A.0 Off |                    0 |
| N/A   35C    P0    32W / 250W |   8968MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      7559      C   tritonserver                     8970MiB |
|    1   N/A  N/A      7559      C   tritonserver                     8964MiB |
+-----------------------------------------------------------------------------+
```

Through further debugging, I found that it might be a thread deadlock. Here is the log from GDB session.

```
#0  0x00007fc58f7a47d1 in pthread_cond_timedwait@@GLIBC_2.3.2 () from target:/usr/lib/x86_64-linux-gnu/libpthread.so.0
#1  0x000055c6489c942e in std::cv_status std::condition_variable::wait_for<long, std::ratio<1l, 1l> >(std::unique_lock<std::mutex>&, std::chrono::duration<long, std::ratio<1l, 1l> > const&) ()
#2  0x000055c6489b4b08 in main ()
```

```
#0  0x00007ffa88f6f678 in do_futex_wait.constprop.0 () from target:/usr/lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007ffa88f6f7a3 in __new_sem_wait_slow.constprop.0 () from target:/usr/lib/x86_64-linux-gnu/libpthread.so.0
#2  0x0000562802d9d966 in triton::backend::python::Stub::PopMessage() ()
#3  0x0000562802da9dfe in triton::backend::python::Stub::RunCommand() ()
#4  0x0000562802d7d1b8 in main ()
```

```

```

**Comment by alexw994** [comment]
> Could you please share the device information you used? Did the cli client work fine?

The CLI client is experiencing the same issue and the same logs.

**Comment by AllentDan** [comment]
We primarily did not support architectures with compute capability lower than 7.0. But you may try to modify [CMakeLists.txt](https://github.com/InternLM/lmdeploy/blob/main/CMakeLists.txt) and add 6.0 building content. The chance is slim though.

**Comment by alexw994** [comment]
> We primarily did not support architectures with compute capability lower than 7.0. But you may try to modify [CMakeLists.txt](https://github.com/InternLM/lmdeploy/blob/main/CMakeLists.txt) and add 6.0 building content. The chance is slim though.

I tried adding the SM=60 related configuration in CMakeList.txt and recompiled, which indeed resolved the "Stuck" issue. However, it produced incorrect text output. I have given up on this approach, and I think I may need to switch to a better graphics card.

**Comment by sohey1910** [comment]
Same question, using tensor parallel V100, and there is no response from server

**Comment by AllentDan** [comment]
> Same question, using tensor parallel V100, and there is no response from server

V100 was supported and tested OK. Could you provide more details?

**Comment by AllentDan** [comment]
Hi, @alexw994 If you don't mind, would you please share your configuration on SM=60 to lmdpeloy to help more people through a PR?

**Comment by alexw994** [comment]
> Hi, @alexw994 If you don't mind, would you please share your configuration on SM=60 to lmdpeloy to help more people through a PR?

This approach is not successful for me because, after recompiling, the model's outputs are all incorrect text.

**Comment by AllentDan** [comment]
> > Hi, @alexw994 If you don't mind, would you please share your configuration on SM=60 to lmdpeloy to help more people through a PR?
> 
> This approach is not successful for me because, after recompiling, the model's outputs are all incorrect text.

Fine. Possible reason is that our kernel used fp16 tensor core which is not supported by P100.

**Comment by lvhan028** [comment]
Close it since no more activity over two weeks. Feel free to reopen it if it is still an issue
