### ISSUE TITLE
[Bug] Does setting the max_tokens parameter too high result in an empty output?

### ISSUE THREAD

**Issue by coolbeevip** [InternLM/lmdeploy#1170]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

Calling the /v1/chat/completions API sometimes returns an empty string for the content of the assistant. After verification, I found that setting the max_tokens manually to more than 1700 causes this issue.

### Reproduction

```shell
curl http://127.0.0.1:8084/v1/chat/completions \
-H "Content-Type: application/json" \
-d '{
   "model": "vicuna-13b-v1.5",
   "messages": [{"role": "user", "content": "hello"}],
   "max_tokens": 2048,
   "temperature": 0.0
 }'
```

### Environment

```Shell
vicuna 13b 1.5
```

**Comment by AllentDan** [comment]
Yes, if the session length does not support the request output length, it only responds with empty text with finish_reason "length".

**Comment by coolbeevip** [comment]
> Yes, if the session length does not support the request output length, it only responds with empty text with finish_reason "length".

Thank you for your reply

Do you know if this is a configurable parameter? The max_tokens limit for Vicuna 13b is 2048. However, when running Vicuna 13b in lmdeploy, I found that an empty string is returned if max_tokens is more significant than 1700. Can this parameter be configured additional in lmdeploy?

**Comment by AllentDan** [comment]
Yes. It could be more smart a strategy. I've updated it in PR https://github.com/InternLM/lmdeploy/pull/1164
After this change, the max_tokens, if not specified, will be computed inside the server.
