### ISSUE TITLE
[Feature] 请问会支持InternLM-XComposer2模型的部署么

### ISSUE THREAD

**Issue by will-wiki** [InternLM/lmdeploy#1173]
### Motivation

当前仓库已经支持了InternLM-XComposer，但是现在已经更新到了InternLM-XComposer2版本了
不过看代码，InternLM-XComposer2相较InternLM-XComposer在推理generate参数部分新增了im_mask、词表映射层output位置好像也不一样，感觉是不能直接套InternLM-XComposer进行部署，想问下有InternLM-XComposer2部署的计划吗？或者有没有根据InternLM-XComposer部署InternLM-XComposer2的建议呢～

**Comment by lvhan028** [comment]
composer2相对于1，模型结构上有个比较特殊的 plora，目前比较难加入到引擎里。现在在做整体的规划，这个模型在计划内，时间表我们还得再排一排。有更新后，会及时通知到

**Comment by will-wiki** [comment]
确实，那个plora好像是按照im_mask只作用于图像embedding，文本embeding不走lora，不能按照之前那样把lora合并到一块推理貌似。。

**Comment by will-wiki** [comment]
@lvhan028 hello 打扰一下，想问下关于InternLM-XComposer2模型的支持，现在有具体的排期计划吗

**Comment by lvhan028** [comment]
4月份会开始这个工作

**Comment by sshuair** [comment]
> 4月份会开始这个工作

有啥进展吗？

**Comment by irexyc** [comment]
> 有啥进展吗？

大概在23号会支持

**Comment by sshuair** [comment]
> > 有啥进展吗？
> 
> 大概在23号会支持

cool, 新发布会的4K模型也在23号支持吗？[InternLM-XComposer2-4KHD-7B](https://huggingface.co/internlm/internlm-xcomposer2-4khd-7b)

**Comment by lvhan028** [comment]
是的

**Comment by irexyc** [comment]
0.4.0 已经支持了。

**Comment by will-wiki** [comment]
@irexyc @lvhan028 想问下xcomposer2的部署有参考的例子吗，github里没找到，十分感谢～

**Comment by lvhan028** [comment]
https://lmdeploy.readthedocs.io/en/latest/inference/vl_pipeline.html#a-hello-world-example
You can try the "hello, world" example by using internlm-xcomposer2 model

**Comment by will-wiki** [comment]
@lvhan028 这个好像是离线推理的demo，想问下有api服务的例子么，倒是有看到这个[链接](https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/serving/api_server_vl.md#%E5%90%AF%E5%8A%A8%E6%9C%8D%E5%8A%A1)，不过信息好少，有没有什么文档或者部署代码之类的

**Comment by will-wiki** [comment]
@lvhan028 跑了下这个https://lmdeploy.readthedocs.io/en/latest/inference/vl_pipeline.html#a-hello-world-example

```
from lmdeploy import pipeline
from lmdeploy.vl import load_image

pipe = pipeline('Display_Demo/models/internlm-xcomposer2-vl-7b')

image = load_image('https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/tests/data/tiger.jpeg')
response = pipe(('describe this image', image))
print(response)
```
环境
V100，python39，torch2.1.0，lmdeploy0.4.0

报这个错是为什么呢
```
Some weights of the model checkpoint at Display_Demo/models/internlm-xcomposer2-vl-7b were not used when initializing InternLMXComposer2ForCausalLM: {'model.layers.30.feed_forward.w2.weight', 'model.layers.2.feed_forward.w1.Plora_A.weight', 'model.layers.20.feed_forward.w3.Plora_A.weight', 'model.layers.18.attention_norm.weight', 'model.layers.4.feed_forward.w1.Plora_B.weight', 'model.layers.20.feed_forward.w1.Plora_A.weight', 'model.layers.20.attention.wqkv.weight', 'model.layers.10.feed_forward.w3.Plora_B.weight', 'model.layers.27.feed_forward.w3.Plora_B.weight',  .......

Device does not support bf16.
[WARNING] gemm_config.in is not found; using default GEMM algo  
RuntimeError: GET was unable to find an engine to execute this computation
```

**Comment by lvhan028** [comment]
https://lmdeploy.readthedocs.io/en/latest/serving/api_server_vl.html#launch-service 
这个不够么？只要把模型换成 internlm-xcomposer2的就好了

**Comment by will-wiki** [comment]
@lvhan028 
看了下现在Lmdeploy首页的两个demo例子
一个是用[cli直接起的服务](https://github.com/InternLM/lmdeploy/blob/main/docs/en/serving/api_server_vl.md#option-1-launching-with-lmdeploy-cli)，但是打了debug，貌似不是用的这个[Engine](https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/serve/vl_async_engine.py#L12)
搜了下倒是另外一个[pipeline](https://github.com/InternLM/lmdeploy/blob/main/docs/en/inference/vl_pipeline.md#a-hello-world-example)的形式用了这个Engine，我[根据这个代码猜测的](https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/archs.py#L136) 不知道对不对

就是想问下有类似于这种server部署方式的例子吗https://github.com/vllm-project/vllm/blob/4ea1f9678dd93f02424ab3de2149f83a490e6c6f/vllm/entrypoints/api_server.py#L12
启用一个Async的server，然后可以进一步调整，包括sampling parameters、模型prompt template等模块的

**Comment by will-wiki** [comment]
另外，Lmdeploy是不是不支持beam search，类似vllm这个的功能的https://github.com/vllm-project/vllm/blob/4ea1f9678dd93f02424ab3de2149f83a490e6c6f/vllm/sampling_params.py#L36，在api的文档上好像没看到这个参数

**Comment by irexyc** [comment]
@will-wiki 

liuhaotian/llava-v1.6-vicuna-7b, internlm/internlm-xcomposer2-7b 应该都是用的 VLAsyncEngine才对 (继承了 AsyncEngine) ，你那边如果不是的话，可以把启动的命令贴一下。pipeline也好，api_server也好，背后其实都是这个 VLAsyncEngine。

prompt template 自定义的话是需要在server/pipeline启动的时候设置的。不知道这个文档有没有帮助 https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/advance/chat_template.md

sampling parameters 是生成阶段设置的参数。pipeline的话有[gen_config](https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/serve/async_engine.py#L282)可以设置, [APIClient](https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/serve/openai/api_client.py#L94-L111) 或者 [openai](https://lmdeploy.readthedocs.io/en/latest/serving/api_server_vl.html#integrate-with-openai) 接口都有可以设置的

beam search 目前不支持。

**Comment by will-wiki** [comment]
@irexyc 另外服务还有个问题，当多线程请求的时候，图片一多显存会上涨，爆显存请求失败这个倒是可以理解，但是服务会被打挂这有点问题，这个麻烦有空看看呢

报错信息
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  [TM][ERROR] CUDA runtime error: out of memory /lmdeploy/src/turbomind/utils/allocator.h:231 
```

**Comment by irexyc** [comment]
@will-wiki 

服务启动后，剩余显存有多少呢？

有几个地方会影响显存的大小，可以进行调整：

- **vision model 显存回收**
当前LLM有一个 --max-batch-size 的最大并发数量，但是 vision 作为前处理的一部分，不受这个限制，并且显存没有及时的回收。你可以在这个[地方](https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/vl/engine.py#L96)加一行 `outputs = [x.cpu() for x in outputs]`

- vison model batch size。
有个组batch操作，并发数多的话会有一个峰值，你可以手动把[这里](https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/vl/engine.py#L67C41-L67C55)改成1试试.

- kv-cache
这个参数会影响 llm 的 batch_size 和 最大支持的 session_len，可以适当调小，保证显存有足够的buffer, --cache-max-entry-count 0.2 表示加载模型后，申请剩余显存的百分比最为kv-cache

- max-batch-size & session-len
一些中间的buffer跟这两个参数有关，可以适当减小。

**Comment by will-wiki** [comment]
@irexyc V100总显存32G，默认参数启动灵笔2需要29G显存。
昨天试了一下，把[这里](https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/serve/vl_async_engine.py#L54)改成features = self.vl_encoder.infer(images) 多线程请求就不会爆了，这个我理解跟下面的操作性质差不多吧，也都是单线程encode

vison model batch size。
有个组batch操作，并发数多的话会有一个峰值，你可以手动把[这里](https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/vl/engine.py#L67C41-L67C55)改成1试试.

另外还有多线程会把服务打挂的问题，这个主要是因为vision encoder的问题吧，是不是这个得加个处理保障下服务安全

**Comment by irexyc** [comment]
如果服务挂掉是因为显存不够的话，应该算正常现象吧。

主要原因就是 vision encoder 大batch的情况下显存会比启动的时候多很多导致的。后面会弄成可配置的参数。
