### ISSUE TITLE
[Bug] 3090 部署internlm2-chat-20b-4bits，提问卡住不懂

### ISSUE THREAD

**Issue by makefree3** [InternLM/lmdeploy#1177]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

![8eaba988b29483b2a7e2bc5ed72215a](https://github.com/InternLM/lmdeploy/assets/42729515/960779a1-78db-4c74-8af7-0d3b59ddc186)
![eefcc464b1d2ecd5a9353da1cfdd0c5](https://github.com/InternLM/lmdeploy/assets/42729515/66fe4d10-752b-4d30-a2b4-ffbe527a451e)
![eff178161cee8f18a836ebdb2ae70f3](https://github.com/InternLM/lmdeploy/assets/42729515/f9067bcb-fead-47e6-aea3-e0ed755b4fda)

### Reproduction

转换格式：
lmdeploy convert internlm2-chat-20b  /vllmapi/internlm2-chat-20b-4bits --model-format awq --group-size 128 --tp 1
推理
lmdeploy chat turbomind ./workspace
输入你好后，出现警告信息后就开着不动了

### Environment

```Shell
docker环境
```

**Comment by lvhan028** [comment]
我在3090上试了下，还没有复现这个问题。你用的是哪个镜像呢？

**Comment by lvhan028** [comment]
这是我的结果。步骤和你的一样
![image](https://github.com/InternLM/lmdeploy/assets/4560679/c69b716d-2cd7-43d9-9eb8-9d7189ae427c)

**Comment by lvhan028** [comment]
使用了 @makefree3 的环境，复现了卡主的问题。gdb信息如下：
![OGdA9x1A0Q](https://github.com/InternLM/lmdeploy/assets/4560679/39d4d547-c3f8-418f-8b19-cc2e6601bd17)

结合源码：
![img_v3_028b_94aed6f2-e9b6-4f8c-9090-6c03928a33cg](https://github.com/InternLM/lmdeploy/assets/4560679/87a59af6-ba9b-438a-86b8-273d2384f3f7)

在windows系统上，应该要走 #ifdef _MSC_VER 的分支。但是因为是windows上的docker container，所以执行的是 #else 分支。
而这个分支会导致卡主。

解决方法是都换成 cudaStreamSynchronize，但需要验证这种修改会不会影响在LINUX上的性能。

**Comment by lvhan028** [comment]
我们还是建议直接在windows裸机上部署。

**Comment by humphreyde** [comment]
> 我们还是建议直接在windows裸机上部署。

你好，我在windows裸机上本地部署internvl2-8B，运行示例代码：
```
from lmdeploy import pipeline, TurbomindEngineConfig, ChatTemplateConfig, GenerationConfig
from lmdeploy.vl import load_image

model = 'D:\\xxxx\\InternVL2-8B'
system_prompt = '我是书生·万象，英文名是InternVL，是由上海人工智能实验室、清华大学及多家合作单位联合开发的多模态大语言模型。'
chat_template_config = ChatTemplateConfig('internvl-internlm2')
chat_template_config.meta_instruction = system_prompt
pipe = pipeline(model, chat_template_config=chat_template_config,
                backend_config=TurbomindEngineConfig(session_len=8192))

image = load_image('D:\\xxx.jpg')
gen_config = GenerationConfig(top_k=40, top_p=0.8, temperature=0.8)
sess = pipe.chat(('describe this image', image), gen_config=gen_config)
print(sess.response.text)
sess = pipe.chat('What is the woman doing?', session=sess, gen_config=gen_config)
print(sess.response.text)
```
没有任何输出
以下是一些warning：
Flash Attention is not available, use_flash_attn is set to false.
....
gemm_config.in is not found; using default GEMM algo
 
那边仓库说是[lmdeploy][https://github.com/OpenGVLab/InternVL/issues/391]在windows的支持不好的问题，请问有什么好的解决方案吗？
我的环境是：
torch2.2.2+cu121
lmdeploy 0.5.2.post1

**Comment by lvhan028** [comment]
创建 pipeline 的时候，加入参数 log_level="INFO"，然后再运行一遍demo，贴下详细的日志

**Comment by humphreyde** [comment]
> 创建 pipeline 的时候，加入参数 log_level="INFO"，然后再运行一遍demo，贴下详细的日志

换成量化版本解决了
