### ISSUE TITLE
[Feature] Support Qwen in lmdeploy.pytorch backend

### ISSUE THREAD

**Issue by jjjjohnson** [InternLM/lmdeploy#1183]
### Motivation

Any play for supporting Qwen in lmdeploy.pytorch backend? Thx!

**Comment by lvhan028** [comment]
qwen1 or qwen1.5?
#1160 is supporting qwen1.5

**Comment by jjjjohnson** [comment]
qwen1:  Qwen/Qwen-14B-Chat
BTW what is the difference between Qwen1 and Qwen1.5?
