### ISSUE TITLE
[SLORA]  support slora 

### ISSUE THREAD

**Issue by newportchen** [InternLM/lmdeploy#1187]
### Motivation

as wechat talk about, add slora api and document

**Comment by newportchen** [comment]
@lvhan028

**Comment by Loovelj** [comment]
better to support qwen

**Comment by lvhan028** [comment]
@AllentDan may refer to https://docs.vllm.ai/en/latest/models/lora.html and https://github.com/vllm-project/vllm/blob/main/examples/multilora_inference.py
Consider exposing lora adapters during non-stateful inference.

**Comment by AllentDan** [comment]
Yeah. Planned to add it after #1188.

**Comment by sleepwalker2017** [comment]
关注！有支持了麻烦踢我一下

**Comment by AllentDan** [comment]
> 关注！有支持了麻烦踢我一下

PR #1286
