### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by xxg98** [InternLM/lmdeploy#1189]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

微调并合并后的模型（huggingface格式）无法启动，微调的模型是internlm2-chat-7b
![c60521706c14768b662573ad1b5891b](https://github.com/InternLM/lmdeploy/assets/98906194/4267d182-53eb-4725-be93-d1fbb56d042a)

### Reproduction

lmdeploy serve api_server /root/autodl-tmp/projects/LLM/fine_tuning/7b/hf_merge --server-name 0.0.0.0 --server-port 6006 --tp 1 --session-len 128000 --rope-scaling-factor 2 --cache-max-entry-count 0.15

### Environment

```Shell
python：3.10
显卡：3090
cuda：12.2
lmdeploy：0.2.3
xtuner：0.1.14.dev0
```

**Comment by ispobock** [comment]
@xxg98 需要指定一下`model_name`参数，如果不指定则会从你传入的`model_path`去推断，但你这个path `/root/autodl-tmp/projects/LLM/fine_tuning/7b/hf_merge`里并没有包含模型的名字，所以推断不出来，可以把`hf_merge`重命名成`internlm2-chat-7b`试试

**Comment by xxg98** [comment]
> `hf_merge`重命名成`internlm2-`


好嘞，谢谢您
