### ISSUE TITLE
[Feature] Does lmdeploy support model serving for Qwen-VL?

### ISSUE THREAD

**Issue by DreamInvoker** [InternLM/lmdeploy#1194]
### Motivation

https://github.com/InternLM/lmdeploy/tree/main/examples/vl seems to only provide a demo to experience the model, but not an api interface for remote call.

**Comment by lvhan028** [comment]
We are going to support it in Q1

**Comment by DreamInvoker** [comment]
Get, looking forward to that. Thanks!

**Comment by lvhan028** [comment]
It has been released in v0.2.6: https://github.com/InternLM/lmdeploy/releases/tag/v0.2.6

May give it a try.

**Comment by DreamInvoker** [comment]
Thank you very much!
