### ISSUE TITLE
对称kv cache 量化

### ISSUE THREAD

**Issue by seeyourcell** [InternLM/lmdeploy#1201]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

对称kv cache 量化  
python3 -m lmdeploy.lite.apis.kv_qparams --work_dir minmax_llama --turbomind_dir ./workspace_llama/triton_models/weights --kv_sym False --num_tp 1

===========
如果采用非对称量化，不会报错

### Reproduction

python3 -m lmdeploy.turbomind.chat ./workspace_llama
(core dumped)

### Environment

```Shell
python3 -m lmdeploy.turbomind.chat ./workspace_llama
```

**Comment by lvhan028** [comment]
在最新的main分支上，kv 离线量化移除，改为在线量化。支持 int4, int8 两种 kv 量化方式
可以参考文档  https://lmdeploy.readthedocs.io/en/latest/quantization/kv_quant.html
