### ISSUE TITLE
[Bug] Get warning message "exceed session max length. PLease restart the session by reset button."

### ISSUE THREAD

**Issue by jerryzhaoc** [InternLM/lmdeploy#1204]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

推理结果超过一定长度时，会显示警告信息“exceed session max length. PLease restart the session by reset button.”，然后发现输出内容被截断，不是自然结束。

想问下session max length是由哪个配置参数来控制的。

![lmdeploy-screenshot01](https://github.com/InternLM/lmdeploy/assets/132997627/17378aa9-6a93-464e-b971-6154a866c118)

### Reproduction

1. 使用了lmdeploy提供的llama2-70b-chat-4bit的量化模型，并且转换成了TurboMind支持的格式。转换时TP=2，因为打算使用2张3090卡来实现推理。
2. 运行命令lmdeploy serve gradio ./workspace来进行推理
3. 显示前端界面后，输入提示词“以哈尔滨冰雕为题，用英文写一篇不超过300字的文章”
4. 输出部分结果后，显示警告信息“exceed session max length. PLease restart the session by reset button.”。查看输出结果，发现内容被截断，不是自然结束。

### Environment

```Shell
utuntu
lmdeploy-0.2.4
lmdeploy/llama2-70b-chat-4bit模型
没有部署在docker容器内
```

**Comment by AllentDan** [comment]
启动时传参 --session-len 控制。所有的可传参数都可以通过-h查看。

**Comment by jerryzhaoc** [comment]
经过测试发现，每次对话生成的结果字数是由gradio页面上的maximum new tokens设置项控制的，但页面显示的警告信息也是“exceed session max length”，不是很恰当。整个对话session的字数才是由session-len参数控制的。

**Comment by AllentDan** [comment]
哦，这里是有个bug。这就修复好。
