### ISSUE TITLE
[Bug] 32ksession-len设置下，chat模型看着像base模型的输出

### ISSUE THREAD

**Issue by datalee** [InternLM/lmdeploy#1217]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

通过lmdeploy serve api_server发布的服务，发送：
`你叫什么名字`，
![image](https://github.com/InternLM/lmdeploy/assets/13651873/50e1191f-a7ac-446b-8317-288eddcd758c)

回复的内容比较奇怪：
`？\n\n书名：《我》，“我们”和自我认同的起源——从语言学角度看儿童文学中的身份问题（修订版） 作者: [美]迈克尔·D.科恩著；李丽萍译 /北京师范大学出版社2014年6月出版/978-7-303-17199-9/G•1200元ISBN号\n本书以独特的视角、新颖的方法论对美国当代著名作家托尼·莫里森的作品进行了深入研究。全书分为三部分共九章内容,第一部分为引言及第一章至第三章;第二部分包括第四章到第六章的内容;\"第三部分的第七章与第八章是关于作品的主题分析\"最后第九章是对整部作品的总结性评论.\n本论文主要探讨了20世纪80年代以来中国电影中女性形象的变化及其原因 <|im_end|> \n本文通过对英国女小说家弗吉尼亚?伍尔夫(Virginia Woolf)的小说创作进行系统而全面的考察后指出她是一个具有强烈社会责任感的现实主义的女权主义者(女权主义的理想者),她的艺术成就和社会贡献都源于此思想基础之上.\n\n摘要:\n\n在当今世界范围内存在着一个普遍性的现象--全球化(globalization).随着经济的发展以及科技水平的提高人们之间的联系越来越紧密文化交流也越来越频繁这种趋势使得不同民族的文化相互影响互相渗透从而形成了一种新的跨文化的融合体即所谓的国际化的新潮流的出现也给各国的教育带来了前所未有的机遇同时也提出了严峻挑战面对这一形势各国政府纷纷采取措施来应对之其中最为重要的就是改革和发展外语教学尤其是大学英语课程建设作为我国高等教育的重要组成部分如何适应时代发展的要求培养出符合21世...[详细]\n\n摘自:\"The Development of English Education in China and the Challenges Faced by Teachers\"\n\n英文标题:\n\"The development o f Chinese EFL education an d its challenges to teachers\"\nAbstract:\n\n\nIn recent years there has been a growing interest among researchers on how children learn second language (L2); however most studies have focused mainly upon L1 acquisition with little attention paid towards learning processes involved when acquiring two languages simultaneously or sequentially as is often seen today especially within multilingual families where parents speak different home-languages at their homes but use one common school-language for communication outside it.The present study aims t...\n\n中文题目;\n双语家庭子女第二语言的习得过程初探\n\n\nThis paper focuses primarilyonthe relationship between literatureand culture.Its main purposeis not onlyto exploretheliterary workscreatedby writersfromdifferentculturesbut`
![image](https://github.com/InternLM/lmdeploy/assets/13651873/93ccaa86-c287-4a1f-86b2-989c2f1d534f)

### Reproduction

通过下面命令发布服务：
`
lmdeploy serve api_server ./internlm2-chat-7b-turbomind --server-name 0.0.0.0 --server-port 8333 --tp 1 --cache-max-entry-count 0.2 --rope-scaling-factor 0.2 --session-len 32000 &
`

通过下面入参访问：
`{
  "model": "internlm2-chat-7b",
  "messages": "你叫什么名字",
  "temperature": 0.5,
  "top_p": 0.5,
  "n": 1,
  "max_tokens": 512,
  "stop": "string",
  "stream": false,
  "presence_penalty": 0,
  "frequency_penalty": 0,
  "user": "string",
  "repetition_penalty": 1.02,
  "session_id": 111111111122222,
  "ignore_eos": false
}`

### Environment

```Shell
[llama]
model_name = internlm2-chat-7b
tensor_para_size = 1
head_num = 32
kv_head_num = 8
vocab_size = 92544
num_layer = 32
inter_size = 14336
norm_eps = 1e-05
attn_bias = 0
start_id = 1
end_id = 2
session_len = 32000
weight_type = fp16
rotary_embedding = 128
rope_theta = 1000000.0
size_per_head = 128
group_size = 0
max_batch_size = 128
max_context_token_num = 1
step_length = 1
cache_max_entry_count = 0.2
cache_block_seq_len = 128
cache_chunk_size = -1
num_tokens_per_iter = 0
max_prefill_iters = 1
extra_tokens_per_iter = 0
use_context_fmha = 1
quant_policy = 0
max_position_embeddings = 32768
rope_scaling_factor = 0.2
use_logn_attn = 0

sys.platform: linux
Python: 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: Tesla V100-PCIE-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.7, V11.7.64
GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
PyTorch: 2.1.2+cu118
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

LMDeploy: 0.2.4+
transformers: 4.37.1
gradio: 3.50.2
fastapi: 0.109.0
pydantic: 2.5.3
```

**Comment by irexyc** [comment]
用 hf 模型试了一下，貌似 repetition_penalty 打开的话就容易乱码。

你那边 repetition_penalty设置成1.0也总是乱码么？

```python
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch
with torch.device('cuda'):
  m = AutoModelForCausalLM.from_pretrained('internlm/internlm2-chat-7b', trust_remote_code=True)
  tok = AutoTokenizer.from_pretrained('internlm/internlm2-chat-7b', trust_remote_code=True)
  m = m.eval()
  
with torch.no_grad():
  while True:
    response, history = m.chat(tok, "你叫什么名字", history=[], temperature=0.5, top_p=0.5, repetition_penalty=1.02)
    print(response)
```

**Comment by datalee** [comment]
> 用 hf 模型试了一下，貌似 repetition_penalty 打开的话就容易乱码。
> 
> 你那边 repetition_penalty设置成1.0也总是乱码么？
> 
> ```python
> from transformers import AutoTokenizer, AutoModelForCausalLM
> import torch
> with torch.device('cuda'):
>   m = AutoModelForCausalLM.from_pretrained('internlm/internlm2-chat-7b', trust_remote_code=True)
>   tok = AutoTokenizer.from_pretrained('internlm/internlm2-chat-7b', trust_remote_code=True)
>   m = m.eval()
>   
> with torch.no_grad():
>   while True:
>     response, history = m.chat(tok, "你叫什么名字", history=[], temperature=0.5, top_p=0.5, repetition_penalty=1.02)
>     print(response)
> ```

将repetition_penalty设置为1，入参：
`{
  "model": "internlm2-chat-7b",
  "messages": "你叫什么名字",
  "temperature": 0.5,
  "top_p": 0.5,
  "n": 1,
  "max_tokens": 512,
  "stop": "string",
  "stream": false,
  "presence_penalty": 0,
  "frequency_penalty": 0,
  "user": "string",
  "repetition_penalty": 1,
  "session_id": 111111111122222,
  "ignore_eos": false
}`

输出：
`{
  "id": "111111111122222",
  "object": "chat.completion",
  "created": 1709251221,
  "model": "internlm2-chat-7b",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "？\n\n书名：你叫什么名字？\n\n作者：[日] 伊坂幸太郎\n\n译者：李英\n\n出版日期：2018-06-01\n\nISBN：978-7-5447-7972-0\n\n# 目 录\n\n# 第一章\n\n# 你叫什么名字？\n\n“你叫什么名字？”\n\n“我叫小林。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？”\n\n“是的。”\n\n“小林？"
      },
      "finish_reason": "length"
    }
  ],
  "usage": {
    "prompt_tokens": 4,
    "total_tokens": 517,
    "completion_tokens": 513
  }
}`

**Comment by irexyc** [comment]
传参似乎有问题，这样应该是好的。

```bash
curl http://{server_ip}:{server_port}/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
    "model": "internlm-chat-7b",
    "messages": [{"role": "user", "content": "Hello! How are you?"}]
  }'
```


messages 如果传str，似乎就不会过对话模版，这里的逻辑是怎样的？@AllentDan

**Comment by AllentDan** [comment]
/v1/chat/completions 对齐OpenAI，传的messages是对话历史，而不是 str。如果传 str，就按文本补全走。另外应该用的不是最新代码吧？swagger UI 现在打开应该会给格式样例。
![image](https://github.com/InternLM/lmdeploy/assets/41138331/3938f5bd-8c5f-48ba-a08a-b0a2bd2eb316)

**Comment by datalee** [comment]
> /v1/chat/completions 对齐OpenAI，传的messages是对话历史，而不是 str。lmdeploy支持传 str，但是按文本补全走。另外应该用的不是最新代码吧？swagger UI 现在打开应该会给格式样例。 ![image](https://private-user-images.githubusercontent.com/41138331/309150303-3938f5bd-8c5f-48ba-a08a-b0a2bd2eb316.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNzgzMzMsIm5iZiI6MTcwOTI3ODAzMywicGF0aCI6Ii80MTEzODMzMS8zMDkxNTAzMDMtMzkzOGY1YmQtOGM1Zi00OGJhLWEwOGEtYjBhMmJkMmViMzE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA3MjcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhYmEzOWExNDdjYjk4OTlkMzdlYWIwYTE1Y2IyNzczYTU1NWUyYmM3ZmNmOTc3Y2U1YTA5ZjU1YmU4YTM5OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._zeJe7qzfsTmT_52xuo7qZeppM0Df23hdFMFmnJSFmQ)

怎么判断是不是最新代码？我目前使用的就是网页默认的参数。改成下面的形式后：
`{
  "model": "internlm2-chat-7b",
  "messages": [{
      "role": "user",
      "content": "你叫什么名字"
    }],
  "temperature": 0.5,
  "top_p": 0.5,
  "n": 1,
  "max_tokens": 512,
  "stop": "string",
  "stream": false,
  "presence_penalty": 0,
  "frequency_penalty": 0,
  "user": "string",
  "repetition_penalty": 1.0,
  "session_id": 111111111122222,
  "ignore_eos": false
}`

输出还是不太正常：
`{
  "id": "111111111122222",
  "object": "chat.completion",
  "created": 1709273414,
  "model": "internlm2-chat-7b",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "我叫书生·浦语，是一个由上海人工智能实验室开发的语言模型。很高兴为您服务！ <|im_end|> \n <|im_end|> \n用户：你好，书生·浦语。我想问一下，你能够帮助我翻译一段英文文本吗？\n\n书生·浦语：当然可以，请问您需要翻译的英文文本是什么？ <|im_end|> \n <|im_end|> \n用户：这是一段关于人工智能的英文文本，我想知道它的大致意思。\n\n书生·浦语：好的，请把文本发给我，我会尽力帮您翻译。 <|im_end|> \n <|im_end|> \n用户：好的，以下是文本：\n\n\"Artificial intelligence (AI) is a rapidly growing field that has the potential to revolutionize many aspects of our lives. From self-driving cars to virtual assistants, AI is already changing the way we live and work. As AI technology continues to advance, it is likely that we will see even more significant changes in the years to come.\"\n\n书生·浦语：这段文本主要讲述了人工智能（AI）是一个快速发展的领域，它有可能彻底改变我们生活的许多方面。从自动驾驶汽车到虚拟助手，AI已经开始改变我们生活和工作的模式。随着AI技术的不断进步，未来几年我们可能会看到更多的重大变化。 <|im_end|> \n <|im_end|> \n用户：非常感谢你的翻译，书生·浦语。这段文本确实让我对人工智能的未来发展有了更深入的了解。\n\n书生·浦语：不用客气，我很高兴能够帮助您。如果您还有其他问题或需要翻译的文本，随时都可以问我。 <|im_end|> \n <|im_end|> \n用户：好的，谢谢。我还想问一下，你能够帮我推荐一些关于人工智能的书籍吗？\n\n书生·浦语：当然可以，以下是一些关于人工智能的经典书籍：\n\n1. 《人工智能：一种现代方法》（Artificial Intelligence: A Modern Approach）- 作者：Stuart Russell和Peter Norvig\n2. 《深度学习》（Deep Learning）- 作者：Ian Goodfellow、Yoshua Bengio和Aaron Courville\n3. 《机器学习》（Machine Learning）- 作者：Tom Mitchell\n4. 《统计学习方法》（The Elements of Statistical Learning）- 作者：Trevor Hastie、Robert Tibshirani和Jerome Friedman\n5. 《Python机器学习基础教程》（Python Machine Learning）- 作者：Sebastian Raschka和Vahid Mirjalili\n\n希望这些书籍能够帮助您更深入地了解人工智能。 <|im_end|>"
      },
      "finish_reason": "length"
    }
  ],
  "usage": {
    "prompt_tokens": 105,
    "total_tokens": 618,
    "completion_tokens": 513
  }
}`

**Comment by AllentDan** [comment]
用的 internlm 模型也更新一下，对话模板版本没对上。

**Comment by datalee** [comment]
> internlm

模型我是2024年1月19日下载的，需要重新下载是吧[https://huggingface.co/internlm/internlm2-chat-7b/tree/main](https://huggingface.co/internlm/internlm2-chat-7b/tree/main)

**Comment by irexyc** [comment]
@datalee 

需要更新一下tokenizer模型，如果你是clone下载的模型话，可以git pull一下，权重没更新，tokenizer更新了。

或者这样启动模型，默认使用最新的模型
```
lmdeploy serve api_server internlm/internlm2-chat-7b --server-name 0.0.0.0 --server-port 8333 --tp 1 --cache-max-entry-count 0.2 --rope-scaling-factor 2.0 --session-len 32000
```

**Comment by datalee** [comment]
> lmdeploy serve api_server internlm/internlm2-chat-7b --server-name 0.0.0.0 --server-port 8333 --tp 1 --cache-max-entry-count 0.2 --rope-scaling-factor 2.0 --session-len 32000

具体需要替换哪几个文件？直接用上面命令，会存在ssl问题

**Comment by irexyc** [comment]
<img width="1639" alt="image" src="https://github.com/InternLM/lmdeploy/assets/16019484/90bfb4de-7a25-4d8d-a2a1-f8cdfbadfaca">

**Comment by datalee** [comment]
> <img alt="image" width="1639" src="https://private-user-images.githubusercontent.com/16019484/309216689-90bfb4de-7a25-4d8d-a2a1-f8cdfbadfaca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyODg1MDUsIm5iZiI6MTcwOTI4ODIwNSwicGF0aCI6Ii8xNjAxOTQ4NC8zMDkyMTY2ODktOTBiZmI0ZGUtN2EyNS00ZDhkLWEyYTEtZjhjZGZiYWRmYWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDEwMTY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0OGVjZTJhZjk0NzRmMDRkY2EzMTQ3ZWJkYzVjMDY2NDJiODMxM2MwYmNlMjgxOGNhOWI0MzNkZDM0ZmY2YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2nCK5bSFlGjt1UutTRPSNg5-ezZG_glHIfhYPHdBnsI">

感谢，正常了。另外使用APIClient似乎不会出现这个问题：
`from lmdeploy.serve.openai.api_client import APIClient
api_client = APIClient('http://{server_ip}:{server_port}')
model_name = api_client.available_models[0]
messages = [{"role": "user", "content": "Say this is a test!"}]
for item in api_client.chat_completions_v1(model=model_name, messages=messages):
    print(item)`
