### ISSUE TITLE
[Feature] multi-nodes surpport 

### ISSUE THREAD

**Issue by hezeli123** [InternLM/lmdeploy#1222]
### Motivation

70B models or more larger modes should be deployed by multi-nodes( A30/L40s ...).
Multi-nodes surpport will be appreciate.

**Comment by lvhan028** [comment]
Sorry, pipline parallelism has a very low priority in lmdeploy. 
I will put this feature in our backlog.

Is it possible to use lmdeploy's tensor parallelism?
