### ISSUE TITLE
[Bug] 使用培训营给的TurboMind 推理 + Python 代码集成，使用lmdeploy0.1.0的版本是正常的，但是0.2版本会会报错，报错如下：

### ISSUE THREAD

**Issue by lyyilin** [InternLM/lmdeploy#1225]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

![@CK8~OS9S@Z4%N9APC08 5](https://github.com/InternLM/lmdeploy/assets/119745184/9bc73356-6bbb-481d-bc51-c6307a5d567f)

### Reproduction

lmdeploy0.2.2

### Environment

```Shell
lmdeploy0.2.2
```

### Error traceback

```Shell
lmdeploy0.2.2
```

**Comment by lvhan028** [comment]
抱歉，回复太晚了。麻烦提供下问题复现的路径。
