### ISSUE TITLE
Turbomind引擎不支持Qwen 1.5 量化模型？

### ISSUE THREAD

**Issue by hwang824** [InternLM/lmdeploy#1227]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

使用Turbo Mind引擎，加载Qwen 1.5 14B AWQ 量化版，出现报错，

命令行为：
lmdeploy chat turbomind /root/.cache/modelscope/hub/qwen/Qwen1___5-14B-Chat-AWQ --model-format awq

错误信息为：

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/root/miniconda3/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/root/miniconda3/lib/python3.8/site-packages/lmdeploy/cli/entrypoint.py", line 18, in run
    args.run(args)
  File "/root/miniconda3/lib/python3.8/site-packages/lmdeploy/cli/chat.py", line 92, in turbomind
    main(**kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/lmdeploy/turbomind/chat.py", line 69, in main
    tm_model = tm.TurboMind.from_pretrained(
  File "/root/miniconda3/lib/python3.8/site-packages/lmdeploy/turbomind/turbomind.py", line 426, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "/root/miniconda3/lib/python3.8/site-packages/lmdeploy/turbomind/turbomind.py", line 195, in __init__
    self.model_comm = self._from_hf(model_source=model_source,
  File "/root/miniconda3/lib/python3.8/site-packages/lmdeploy/turbomind/turbomind.py", line 287, in _from_hf
    model_arch = get_model_from_config(model_path)
  File "/root/miniconda3/lib/python3.8/site-packages/lmdeploy/turbomind/utils.py", line 159, in get_model_from_config
    return ARCH_MAP[arch]
KeyError: 'Qwen2ForCausalLM'

### Reproduction

lmdeploy chat turbomind /root/.cache/modelscope/hub/qwen/Qwen1___5-14B-Chat-AWQ --model-format awq

### Environment

```Shell
sys.platform: linux
Python: 3.8.10 (default, Jun  4 2021, 15:09:15) [GCC 7.5.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 4090
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 2.1.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.1+cu118
LMDeploy: 0.2.4+
transformers: 4.37.1
gradio: 3.50.2
fastapi: 0.110.0
pydantic: 2.6.3
```

**Comment by lvhan028** [comment]
是的，目前还不支持。
turbomind 扩展模型会集中放在Q2处理
