### ISSUE TITLE
[Docs] W8A8支持v100吗？我看w4A16有明确写出支持的GPU型号，是否W8A8也可以明确下？谢谢

### ISSUE THREAD

**Issue by datalee** [InternLM/lmdeploy#1242]
### 📚 The doc issue

文档地址：https://github.com/InternLM/lmdeploy/blob/main/docs/en/quantization/w8a8.md

![image](https://github.com/InternLM/lmdeploy/assets/13651873/e8dc72fa-7795-4cd8-b0db-cbd185162b22)

**Comment by HIT-cwh** [comment]
目前还不支持在 V100 上运行 W8A8 ，因为 8-bit Triton kernel 尚且不支持在 Turing 架构的 GPU 上运行，请参考 [issue 861](https://github.com/InternLM/lmdeploy/issues/861) 。
我们会尽快补充文档，感谢提醒！

**Comment by datalee** [comment]
> 目前还不支持在 V100 上运行 W8A8 ，因为 8-bit Triton kernel 尚且不支持在 Turing 架构的 GPU 上运行，请参考 [issue 861](https://github.com/InternLM/lmdeploy/issues/861) 。 我们会尽快补充文档，感谢提醒！

感谢
