### ISSUE TITLE
[Bug] Latest doc cannot switch to zh_cn

### ISSUE THREAD

**Issue by ispobock** [InternLM/lmdeploy#1244]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

The [latest version doc](https://lmdeploy.readthedocs.io/en/latest/) cannot switch to [zh_cn](https://lmdeploy.readthedocs.io/zh-cn/latest/index.html). But for [v0.2.4](https://lmdeploy.readthedocs.io/en/v0.2.4/index.html) doc, it works.

<img width="1472" alt="image" src="https://github.com/InternLM/lmdeploy/assets/26454835/aa85257c-6d0a-4c57-8702-89ce84b37c35">

### Reproduction

In https://lmdeploy.readthedocs.io/en/latest/ page, click `以中文阅读`, then the page is still English version.

### Environment

```Shell
N/A
```

**Comment by RunningLeon** [comment]
@ispobock Hi, thanks for your feedback. It will be fixed soon.

**Comment by lvhan028** [comment]
Fixed in PR #1245
