### ISSUE TITLE
pip install最新的v0.2.5，qwen1.5-7b的turbomind 格式转换的支持问题

### ISSUE THREAD

**Issue by littleSunlxy** [InternLM/lmdeploy#1252]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.

### Describe the bug

请问用了最新的v0.2.5，还是不支持qwen1.5-7b的turbomind 格式转换吗，有计划支持吗？
期望用24G卡实现qwen1.5-7b，triton部署，基于lmdeploy，目前是否有可行方案呢？

### Reproduction

lmdeploy convert qwen1.5 Qwen1.5-7B-Chat

### Environment

```Shell
lmdeploy-0.2.5
```

### Error traceback

```Shell
lmdeploy_py39/lib/python3.9/site-packages/lmdeploy/turbomind/deploy/converter.py", line 221, in main
    assert model_name in MODELS.module_dict.keys(), \
AssertionError: 'qwen1.5' is not supported. The supported models are: dict_keys(['base', 'llama', 'internlm', 'vicuna', 'wizardlm', 'internlm-chat-7b', 'internlm-chat', 'internlm-chat-7b-8k', 'internlm-chat-20b', 'internlm-20b', 'internlm2', 'internlm2-1_8b', 'internlm2-7b', 'internlm2-20b', 'internlm2-chat', 'internlm2-chat-1_8b', 'internlm2-chat-7b', 'internlm2-chat-20b', 'baichuan-7b', 'baichuan2-7b', 'puyu', 'llama2', 'llama-2', 'llama-2-chat', 'qwen-7b', 'qwen-14b', 'codellama', 'falcon', 'chatglm2-6b', 'solar', 'solar-70b', 'ultralm', 'ultracm', 'yi', 'yi-chat', 'yi-200k', 'yi-34b', 'Mistral-7B-Instruct', 'Mixtral-8x7B-Instruct', 'gemma', 'deepseek-chat'])
```

**Comment by lvhan028** [comment]
有支持的计划，不过根据现在的排期，是在 4 月份。
3月份 turbomind 的规划是在线量化，还有 VL models 的 pipline 和 serving

**Comment by datalee** [comment]
> 有支持的计划，不过根据现在的排期，是在 4 月份。 3月份 turbomind 的规划是在线量化，还有 VL models 的 pipline 和 serving

那现在对qwen1.5的支持不需要转模型是吧？

**Comment by lvhan028** [comment]
是的。lmdeploy支持直接输入huggingface hub 或者 model scope 上的模型

**Comment by Cristhine** [comment]
> 有支持的计划，不过根据现在的排期，是在 4 月份。 3月份 turbomind 的规划是在线量化，还有 VL models 的 pipline 和 serving

请问qwen-vl如何转模型 没在readme看到怎么把本地参数转化的用法

**Comment by lvhan028** [comment]
不用手动转模型了。lmdeploy会加载 hf 模型，自动做转换。
在明天发布 v0.2.6 后，qwen-vl 的部署会非常简单，参考 https://lmdeploy.readthedocs.io/en/latest/inference/vl_pipeline.html
