### ISSUE TITLE
跑profile_generation.py的时候，每循环一次貌似都加载一次模型是咋回事

### ISSUE THREAD

**Issue by dingjingzhen** [InternLM/lmdeploy#1257]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

![image](https://github.com/InternLM/lmdeploy/assets/21244263/890343fa-1bd5-43e3-9fbf-b16d1bdc010f)

### Reproduction

python profile_generation.py llama-2-13b-chat-hf

### Environment

```Shell
cuda11.8
```

**Comment by dingjingzhen** [comment]
这个特别慢，然后我想问下，真正在生产环境下，难道每次变长变batch都需要重新加载一次吗？这个的意义是啥

**Comment by dingjingzhen** [comment]
这个特别慢，然后我想问下，真正在生产环境下，难道每次变长变batch都需要重新加载一次吗？这个的意义是啥？还是单纯的代码写的不够优雅

**Comment by lvhan028** [comment]
profile_generation测试的是在不同组合下的模型推理性能，目的是检验引擎的批处理能力，指标是每秒生成多少 token
每种组合，都要重新加载模型来测试引擎的。
这里的组合是 batch 大小、输入 token数量、输出 token 数量 组成的。

profile_throughput 测试的是变长输入情况下引擎的推理能力，指标是请求的吞吐量。侧重 continuous batching 的验证

**Comment by dingjingzhen** [comment]
> profile_generation测试的是在不同组合下的模型推理性能，目的是检验引擎的批处理能力，指标是每秒生成多少 token 每种组合，都要重新加载模型来测试引擎的。 这里的组合是 batch 大小、输入 token数量、输出 token 数量 组成的。
> 
> profile_throughput 测试的是变长输入情况下引擎的推理能力，指标是请求的吞吐量。侧重 continuous batching 的验证

我知道了，是我理解的有问题，感谢
