### ISSUE TITLE
Question about persistent Batch Inference

### ISSUE THREAD

**Issue by rollroll90** [InternLM/lmdeploy#126]
Hi, Thank you for the open source LMDeploy project!

There is a image in the documentation that provides a good description of the process of dynamic batching inference, but I couldn't  find more details about how LMDeploy implements this function. 

Is there any document or could you tell me where this part is implemented in the code?

**Comment by lvhan028** [comment]
Turbomind's architecture: 
    docs/en/turbomind.md

Entry of turbomind:
    src/turbomind/models/llama/LlamaV2.cc

Implementation of Request Queue: 
    InternLM/lmdeploy/src/turbomind/models/llama/Request.h

Implementation of Persistent Batch: 
    src/turbomind/models/llama/LlamaBatch.cc
