### ISSUE TITLE
pipeline 推理  sample好像未生效

### ISSUE THREAD

**Issue by chynphh** [InternLM/lmdeploy#1262]
目标是一次调用得到不同的结果

模型，InternLM, 4 bit量化

利用pipeline 推理，相同输入结果始终一致。
已尝试：
1. pipe时传入两个相同的输入 
```
pipe([text1, text1])
```
3. 设置 GenerationConfig
```
GenerationConfig(top_p=0.8,top_k=200, temperature=0.9, max_new_tokens=256, random_seed=2222)
GenerationConfig(top_p=0.8,top_k=200, temperature=0.9, max_new_tokens=256)
GenerationConfig(top_p=0.8,top_k=100, temperature=0.9, max_new_tokens=256)
```

**Comment by zhyncs** [comment]
> 目标是一次调用得到不同的结果
> 
> 模型，InternLM, 4 bit量化
> 
> 利用pipeline 推理，相同输入结果始终一致。 已尝试：
> 
> 1. pipe时传入两个相同的输入
> 
> ```
> pipe([text1, text1])
> ```
> 
> 3. 设置 GenerationConfig
> 
> ```
> GenerationConfig(top_p=0.8,top_k=200, temperature=0.9, max_new_tokens=256, random_seed=2222)
> GenerationConfig(top_p=0.8,top_k=200, temperature=0.9, max_new_tokens=256)
> GenerationConfig(top_p=0.8,top_k=100, temperature=0.9, max_new_tokens=256)
> ```

Are you using TurboMind or PyTorch backend?

**Comment by chynphh** [comment]
> > 目标是一次调用得到不同的结果
> > 模型，InternLM, 4 bit量化
> > 利用pipeline 推理，相同输入结果始终一致。 已尝试：
> > 
> > 1. pipe时传入两个相同的输入
> > 
> > ```
> > pipe([text1, text1])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 3. 设置 GenerationConfig
> > 
> > ```
> > GenerationConfig(top_p=0.8,top_k=200, temperature=0.9, max_new_tokens=256, random_seed=2222)
> > GenerationConfig(top_p=0.8,top_k=200, temperature=0.9, max_new_tokens=256)
> > GenerationConfig(top_p=0.8,top_k=100, temperature=0.9, max_new_tokens=256)
> > ```
> 
> Are you using TurboMind or PyTorch backend?

yes, TurboMind
```
            self.engine_config = TurbomindEngineConfig(model_format='awq')
            self.pipe = pipeline(model_path, backend_config=self.engine_config)
```
