### ISSUE TITLE
同时使用pipeline推理和别的并发框架，会报错

### ISSUE THREAD

**Issue by chynphh** [InternLM/lmdeploy#1263]
```
RuntimeError: Leaving task <Task pending name='Task-252' coro=<AsyncEngine.batch_infer.<locals>._inner_call() running at /home/admin/miniconda/envs
/tmap/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py:310> wait_for=<Future pending cb=[Task.__wakeup()]> cb=[gather.<locals>._done_cal
lback() at /home/admin/miniconda/envs/tmap/lib/python3.10/asyncio/tasks.py:720]> does not match the current task <Task pending name='Task-250' coro
=<AsyncEngine.batch_infer.<locals>._inner_call() running at /home/admin/miniconda/envs/tmap/lib/python3.10/site-packages/lmdeploy/serve/async_engin
e.py:310> cb=[gather.<locals>._done_callback() at /home/admin/miniconda/envs/tmap/lib/python3.10/asyncio/tasks.py:720]>.
ERROR:asyncio:Exception in callback Task.__wakeup(<Future finished result=None>)
handle: <Handle Task.__wakeup(<Future finished result=None>)>
Traceback (most recent call last):
  File "/home/admin/miniconda/envs/tmap/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/admin/miniconda/envs/tmap/lib/python3.10/asyncio/tasks.py", line 315, in __wakeup
    self.__step()
  File "/home/admin/miniconda/envs/tmap/lib/python3.10/asyncio/tasks.py", line 299, in __step
    _leave_task(self._loop, self)
RuntimeError: Leaving task <Task pending name='Task-250' coro=<AsyncEngine.batch_infer.<locals>._inner_call() running at /home/admin/miniconda/envs
/tmap/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py:310> wait_for=<Future pending cb=[Task.__wakeup()]> cb=[gather.<locals>._done_cal
lback() at /home/admin/miniconda/envs/tmap/lib/python3.10/asyncio/tasks.py:720]> does not match the current task <Task pending name='Task-252' coro
=<AsyncEngine.batch_infer.<locals>._inner_call() running at /home/admin/miniconda/envs/tmap/lib/python3.10/site-packages/lmdeploy/serve/async_engin
e.py:310> cb=[gather.<locals>._done_callback() at /home/admin/miniconda/envs/tmap/lib/python3.10/asyncio/tasks.py:720]>.
ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(95, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(95, 1)>
Traceback (most recent call last):
  File "/home/admin/miniconda/envs/tmap/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x7f8db4ae3a80> is already entered
```

背景：需要别的一套框架做部署，控制并发。框架限制，启动时每个线程中会自动生成一个事件循环。

在其中初始化我们的pipeline,并做调用。

最开始会报 https://github.com/InternLM/lmdeploy/issues/1191 中的错误，无法跑通推理，按照其中方法修改后。会报上面的错误，不过是偶发。

**Comment by AllentDan** [comment]
正常应该是不会触发这种问题的，可以给个复现脚本吗？

**Comment by caoquanjie** [comment]
> ```
> RuntimeError: Leaving task <Task pending name='Task-252' coro=<AsyncEngine.batch_infer.<locals>._inner_call() running at /home/admin/miniconda/envs
> /tmap/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py:310> wait_for=<Future pending cb=[Task.__wakeup()]> cb=[gather.<locals>._done_cal
> lback() at /home/admin/miniconda/envs/tmap/lib/python3.10/asyncio/tasks.py:720]> does not match the current task <Task pending name='Task-250' coro
> =<AsyncEngine.batch_infer.<locals>._inner_call() running at /home/admin/miniconda/envs/tmap/lib/python3.10/site-packages/lmdeploy/serve/async_engin
> e.py:310> cb=[gather.<locals>._done_callback() at /home/admin/miniconda/envs/tmap/lib/python3.10/asyncio/tasks.py:720]>.
> ERROR:asyncio:Exception in callback Task.__wakeup(<Future finished result=None>)
> handle: <Handle Task.__wakeup(<Future finished result=None>)>
> Traceback (most recent call last):
>   File "/home/admin/miniconda/envs/tmap/lib/python3.10/asyncio/events.py", line 80, in _run
>     self._context.run(self._callback, *self._args)
>   File "/home/admin/miniconda/envs/tmap/lib/python3.10/asyncio/tasks.py", line 315, in __wakeup
>     self.__step()
>   File "/home/admin/miniconda/envs/tmap/lib/python3.10/asyncio/tasks.py", line 299, in __step
>     _leave_task(self._loop, self)
> RuntimeError: Leaving task <Task pending name='Task-250' coro=<AsyncEngine.batch_infer.<locals>._inner_call() running at /home/admin/miniconda/envs
> /tmap/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py:310> wait_for=<Future pending cb=[Task.__wakeup()]> cb=[gather.<locals>._done_cal
> lback() at /home/admin/miniconda/envs/tmap/lib/python3.10/asyncio/tasks.py:720]> does not match the current task <Task pending name='Task-252' coro
> =<AsyncEngine.batch_infer.<locals>._inner_call() running at /home/admin/miniconda/envs/tmap/lib/python3.10/site-packages/lmdeploy/serve/async_engin
> e.py:310> cb=[gather.<locals>._done_callback() at /home/admin/miniconda/envs/tmap/lib/python3.10/asyncio/tasks.py:720]>.
> ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(95, 1)
> handle: <Handle BaseAsyncIOLoop._handle_events(95, 1)>
> Traceback (most recent call last):
>   File "/home/admin/miniconda/envs/tmap/lib/python3.10/asyncio/events.py", line 80, in _run
>     self._context.run(self._callback, *self._args)
> RuntimeError: cannot enter context: <_contextvars.Context object at 0x7f8db4ae3a80> is already entered
> ```
> 
> 背景：需要别的一套框架做部署，控制并发。框架限制，启动时每个线程中会自动生成一个事件循环。
> 
> 在其中初始化我们的pipeline,并做调用。
> 
> 最开始会报 #1191 中的错误，无法跑通推理，按照其中方法修改后。会报上面的错误，不过是偶发。

有解决吗，我也遇到了
