### ISSUE TITLE
推理服务在多卡上运行报错

### ISSUE THREAD

**Issue by ChingKwanCheung** [InternLM/lmdeploy#1267]
运行：
lmdeploy serve api_server ./internlm2-chat-7b-lmdeploy --server-name 0.0.0.0 --server-port 6002 --tp 2 --cache-max-entry-count 0.2 --rope-scaling-factor 0.2 --session-len 32000
报错：
Failed, NCCL error /lmdeploy/src/turbomind/utils/nccl_utils.cc:296 'unhandled cuda error (run with NCCL_DEBUG=INFO for details)
请问是什么原因呢？
我用的显卡是V100 32G *2

**Comment by lvhan028** [comment]
执行下 `export NCCL_DEBUG=INFO`，再重新跑下上面的代码，看看详细信息是怎样的？
另外，还请提供下 lmdeploy 版本，cuda版本，以及显卡驱动版本等信息

**Comment by ChingKwanCheung** [comment]
> 执行下 `export NCCL_DEBUG=INFO`，再重新跑下上面的代码，看看详细信息是怎样的？ 另外，还请提供下 lmdeploy 版本，cuda版本，以及显卡驱动版本等信息

详细信息是：CUDA driver version is insufficient for CUDA runtime version
lmdeploy==0.2.2
cuda 11.7
驱动版本：515.43.04

**Comment by lvhan028** [comment]
怀疑是 nccl 的版本太高了。
@irexyc could you follow up this issue?

**Comment by irexyc** [comment]
https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html
515.43.04 支持到 cuda 11.7GA

https://pypi.org/project/nvidia-cuda-runtime-cu11
nvidia-cuda-runtime-cu11 目前默认装的是 11.8.89

可以试下升级驱动，或者通过 pip install nvidia-cuda-runtime-cu11==11.7.99，降runtime的版本
