### ISSUE TITLE
Performance of Turbomind engine with Triton inference server is much lower than api_server

### ISSUE THREAD

**Issue by ispobock** [InternLM/lmdeploy#1280]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

@lvhan028 @lzhangzz  We tested the performance for **Turbomind+Triton server**, but the throughput is ~3.4 RPS, which is only half of the throughput of api_server.
```
concurrency: 128
elapsed_time: 292.422s

first_token latency(min, max, ave): 0.074s, 14.585s, 2.547s

number of prompt tokens: 244330
number of completion tokens: 240421
token throughput (completion token): 822.172 token/s
token throughput (prompt + completion token): 1657.712 token/s
RPS (request per second): 3.420 req/s
RPM (request per minute): 205.183 req/min
```
Is this result expected? How to tune the parameters in `config.pbtxt` to improve the performance?

### Reproduction

1. compile code and move `libtransformer-shared.so` and `libtriton_turbomind.so` to `/opt/tritonserver/backends/turbomind/`

2. convert the llama2_13B model and put it to `./workspace` by default:
```
lmdeploy convert llama2 /workdir/llm_models/llama2_13b_chat/
```

3. start triton server with turbomind backend:
```
tritonserver \
        --model-repository=/workdir/lmdeploy/workspace/model_repository \
        --backend-directory /opt/tritonserver/backends \
        --allow-http=0 \
        --allow-grpc=1 \
        --grpc-port=33337 \
        --log-verbose=0 \
        --allow-metrics=1
```

4. test performance with `profile_serving.py`:
```
python benchmark/profile_serving.py 0.0.0.0:33337 /workdir/llm_models/llama2_13b_chat/ /workdir/ShareGPT_V3_unfiltered_cleaned_split.json --num_prompts 1000 --concurrency=128
```

### Environment

```Shell
sys.platform: linux
Python: 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA A100-SXM4-80GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: gcc (GCC) 10.2.1 20210130 (Red Hat 10.2.1-11)
PyTorch: 2.1.2+cu118
LMDeploy: 0.2.5+24bd4b9
transformers: 4.37.1
gradio: 3.50.2
fastapi: 0.109.0
pydantic: 2.6.0
```

**Comment by lvhan028** [comment]
Yes, we know that.
The triton inference server policy LMDeploy uses is as below. It is not sequence batching, nor ensemble mode.
Currently, we are short of hands to investigate more about optimizing TIS integration.

```
model_transaction_policy {
  decoupled: True
}

instance_group [
  {
    # max concurrent instances
    count: 48
    kind: KIND_CPU
  }
]

```

**Comment by ispobock** [comment]
- I tried to change the `instance_group count` and `max_batch_size`, but it seems not work. The RPS is stuck in **3.x**. 
- When I changed the `decoupled` to `False`, the RPS increased to **4.5**.
```
concurrency: 128
elapsed_time: 218.310s

first_token latency(min, max, ave): 2.013s, 63.621s, 23.292s

number of prompt tokens: 244330
number of completion tokens: 240421
token throughput (completion token): 1101.282 token/s
token throughput (prompt + completion token): 2220.470 token/s
RPS (request per second): 4.581 req/s
RPM (request per minute): 274.838 req/min
```
- When I changed the `decoupled` to `False` and `instance_group count` to 128, the RPS increased to **5.1**.
```
concurrency: 128
elapsed_time: 195.904s

first_token latency(min, max, ave): 2.732s, 65.867s, 20.712s

number of prompt tokens: 244330
number of completion tokens: 240421
token throughput (completion token): 1227.239 token/s
token throughput (prompt + completion token): 2474.431 token/s
RPS (request per second): 5.105 req/s
RPM (request per minute): 306.272 req/min
```
Is the above results reasonable?

**Comment by lvhan028** [comment]
As I remembered, `decoupled` has to be set True. Otherwise, the inference result is not right.
We know the current TIS integration is not the optimal. A better way is to use ensemble mode.
But we are short of hands to deal with it.
If you are interested, may give it a try.

**Comment by ispobock** [comment]
@lvhan028 Got it, thanks!

**Comment by ispobock** [comment]
@lvhan028 We removed `preprocessing` and `postprocessing` steps and only test the Turbomind model, the RPS is 5.8 with 128 instances. That means if we did the model ensemble, the throughput will not be better than 5.8 RPS. 
So the problem is not all about the ensemble. There may be some issues in Turbomind TIS backend lib.

**Comment by lvhan028** [comment]
Thanks for the investigation.
But we have no time to fix it.

**Comment by zhyncs** [comment]
Due to time constraints, and the fact that we have already implemented an efficient [Python Backend](https://github.com/InternLM/lmdeploy/pull/1329), we are temporarily putting on **hold** the C++ backend issue. We may revisit it when we have more time in the future.
