### ISSUE TITLE
为什么awq int4在开启tp后会更慢

### ISSUE THREAD

**Issue by bisunny** [InternLM/lmdeploy#1296]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

bs=1时，使用fp16推理时，开启tp会提高吞吐量。但是使用awq int4量化进行推理时，开启tp没有速度提升，甚至更慢

### Reproduction

awq int4 + tp=2

### Environment

```Shell
cu 12.2
```

**Comment by lzhangzz** [comment]
W4A16本身不会影响TP的通信开销，目前看来主要是2种因素影响


1. TP时W4A16 kernel可能没有dispatch到最优的
2. TP本身的通信开销也不小

**Comment by bisunny** [comment]
非常感谢回复，我发现应该是我的模型太小会出现这种情况
