### ISSUE TITLE
[Bug] 设置cache_max_entry_count=0.2后22G/2080ti上未生效，并且有乱码

### ISSUE THREAD

**Issue by tcexeexe** [InternLM/lmdeploy#1298]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

在cuda11.8环境上，采用`pip install lmdeploy`安装v0.2.5版本的lmdeploy，在三卡2080ti 22G环境上运行如下示例代码，报OOM，似乎cache_max_entry_count=0.2没有生效，哪怕设置0.01也会报OOM，不知是否是兼容性问题？
同时缓存似乎是只加载在了一块显卡上，想问下是否可以分布在多块显卡上？
报错
<img width="907" alt="1710732142827" src="https://github.com/InternLM/lmdeploy/assets/28287196/caf0d8c8-5eca-4b6d-837a-ed985c0e8bc9">

### Reproduction

```
from lmdeploy import pipeline, TurbomindEngineConfig

# decrease the ratio of the k/v cache occupation to 20%
backend_config = TurbomindEngineConfig(cache_max_entry_count=0.2)

pipe = pipeline('/home/tcexeexe/.cache/modelscope/hub/Shanghai_AI_Laboratory/internlm2-chat-7b-sft',
                backend_config=backend_config)
response = pipe(['Hi, pls intro yourself', 'Shanghai is'])
print(response)
```

### Environment

```Shell
sys.platform: linux
Python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2: NVIDIA GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
PyTorch: 2.1.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

LMDeploy: 0.2.5+847996d
transformers: 4.37.1
gradio: 3.50.2
fastapi: 0.110.0
pydantic: 2.6.2
(lmdeploy) tcexe
```

**Comment by lvhan028** [comment]
“三卡2080ti 22G”，是说每块卡都有22G？

**Comment by tcexeexe** [comment]
> “三卡2080ti 22G”，是说每块卡都有22G？

对的
<img width="632" alt="1710740082008" src="https://github.com/InternLM/lmdeploy/assets/28287196/000e3355-d9c3-4789-a7dc-d920b67300c6">

**Comment by lvhan028** [comment]
可以设置TurbomindEngineConfig中的tp=2，这样就能用2张卡做张量并行了。
张量并行参数要是2的指数次方，即 2，4，8

**Comment by lvhan028** [comment]
你的脚本中，test_lmdeploy_server.py 中的内容上是怎样的？

**Comment by tcexeexe** [comment]
> from lmdeploy import pipeline, TurbomindEngineConfig
> 
> # decrease the ratio of the k/v cache occupation to 20%
> backend_config = TurbomindEngineConfig(cache_max_entry_count=0.2)
> 
> pipe = pipeline('/home/tcexeexe/.cache/modelscope/hub/Shanghai_AI_Laboratory/internlm2-chat-7b-sft',
>                 backend_config=backend_config)
> response = pipe(['Hi, pls intro yourself', 'Shanghai is'])
> print(response)
原先test_lmdeploy_server.py中代码是这样的
```
from lmdeploy import pipeline, TurbomindEngineConfig

# decrease the ratio of the k/v cache occupation to 20%
backend_config = TurbomindEngineConfig(cache_max_entry_count=0.2)

pipe = pipeline('/home/tcexeexe/.cache/modelscope/hub/Shanghai_AI_Laboratory/internlm2-chat-7b-sft',
                backend_config=backend_config)
response = pipe(['Hi, pls intro yourself', 'Shanghai is'])
print(response)
```
修改后成了这样
```
from lmdeploy import pipeline, TurbomindEngineConfig

# decrease the ratio of the k/v cache occupation to 20%
backend_config = TurbomindEngineConfig(cache_max_entry_count=0.2,tp=2)

pipe = pipeline('/home/tcexeexe/.cache/modelscope/hub/Shanghai_AI_Laboratory/internlm2-chat-7b-sft',
                backend_config=backend_config)
response = pipe(['Hi, pls intro yourself', 'Shanghai is'])
print(response)
```
但是出现了一堆乱码
<img width="843" alt="1710741775075" src="https://github.com/InternLM/lmdeploy/assets/28287196/612e227f-47d0-4f35-bb4e-51f8df7c3d8d">

**Comment by lvhan028** [comment]
lmdeploy 在 sm75 架构上的 kernel 有问题。这个问题在 turbomind-2.1 分支修复了。这个分支会在月底的版本发布。

**Comment by tcexeexe** [comment]
> lmdeploy 在 sm75 架构上的 kernel 有问题。这个问题在 turbomind-2.1 分支修复了。这个分支会在月底的版本发布。

好的

**Comment by linchen111** [comment]
> 在cuda11.8环境上，采用`pip install lmdeploy`安装v0.2.5版本的lmdeploy，在三卡2080ti 22G环境上运行如下示例代码，报OOM，似乎cache_max_entry_count=0.2没有生效，哪怕设置0.01也会报OOM，不知是否是兼容性问题？

这个分支有了吗

**Comment by lvhan028** [comment]
已经合入main分支了，下周会发版

**Comment by linchen111** [comment]
> 已经合入main分支了，下周会发版

十分感谢

**Comment by lvhan028** [comment]
在2080Ti上，比较 lmdeploy 和 llava 吗？

**Comment by lvhan028** [comment]
我们还没有在这个架构上对比过性能。你有 llava 在这个架构上的性能测试数据吗？

**Comment by linchen111** [comment]
> 我们还没有在这个架构上对比过性能。你有 llava 在这个架构上的性能测试数据吗？

我应该以哪种格式给出？

**Comment by lvhan028** [comment]
和ShareGPT那样格式的数据。另外，llava在2080Ti上的测试结果，你有么？

**Comment by linchen111** [comment]
> 和ShareGPT那样格式的数据。另外，llava在2080Ti上的测试结果，你有么？

您好。有的（llava在2080Ti上的测试结果）。

刚才我没表述情况不好意思，您需要测试的哪些指标？

**Comment by lvhan028** [comment]
其实，针对 vlm 模型，我不确定它是否有像 LLM 那样大家达成共识的测试指标，比如 token/s，Request Per Second，first-token latency，per-token latency 等等
因为它涉及到单图，或者多图，还有 prompt

所以，能不能分享下你这边的测试指标，以及对应的测试结果呢？

**Comment by linchen111** [comment]
> 其实，针对 vlm 模型，我不确定它是否有像 LLM 那样大家达成共识的测试指标，比如 token/s，Request Per Second，first-token latency，per-token latency 等等 因为它涉及到单图，或者多图，还有 prompt
> 
> 所以，能不能分享下你这边的测试指标，以及对应的测试结果呢？

可以。我稍后更新到这个issue里面

**Comment by linchen111** [comment]
> 其实，针对 vlm 模型，我不确定它是否有像 LLM 那样大家达成共识的测试指标，比如 token/s，Request Per Second，first-token latency，per-token latency 等等 因为它涉及到单图，或者多图，还有 prompt
> 
> 所以，能不能分享下你这边的测试指标，以及对应的测试结果呢？



Time To First Token=5.0s
Time Per Output Token =0.15 s/token

**Comment by lvhan028** [comment]
我们没有4卡 2080ti 的环境。
你是把图像处理的时间也算上的是吧。

**Comment by linchen111** [comment]
> 我们没有4卡 2080ti 的环境。 你是把图像处理的时间也算上的是吧。

对

**Comment by lvhan028** [comment]
抱歉，我们无法提供多卡 2080ti 上的性能数据，没有这个环境。只有单卡 2080（8G），跑不起来 llava。

这个 issue https://github.com/InternLM/lmdeploy/issues/1357 有关于性能部分的讨论，不知是否对你有借鉴意义

上面的测试结果是 llava transformers 的，还是 llava sglang的？

**Comment by linchen111** [comment]
> 抱歉，我们无法提供多卡 2080ti 上的性能数据，没有这个环境。只有单卡 2080（8G），跑不起来 llava。
> 
> 这个 issue #1357 有关于性能部分的讨论，不知是否对你有借鉴意义
> 
> 上面的测试结果是 llava transformers 的，还是 llava sglang的？

您好，没有关系。
我已经使用lmdeploy较快的运行起34B的Llava

我之前使用的是llava transformers
