### ISSUE TITLE
根据readme.md部署报错  [FT][ERROR] CUDA runtime error: invalid argument /opt/trito

### ISSUE THREAD

**Issue by happened** [InternLM/lmdeploy#130]
step1 :下载internlm-chat-7b模型

step2: 运行docker镜像`docker run -itd --net=host --name internlm_server --gpus all -v ./workspace/:/workspace -v /data/models/:/models -it openmmlab/lmdeploy:latest bash`

step3: 转换模型为turbomind ，因为我是有两台T4 
`root@:/opt/tritonserver/lmdeploy# python3 -m lmdeploy.serve.turbomind.deploy internlm-7b /models/internlm-chat-7b hf --tp 2` 

step4: 切换到目录运行
`root@/opt/tritonserver/lmdeploy#  python3 -m lmdeploy.turbomind.chat internlm ./workspace/ `

报错如下：

[WARNING] gemm_config.in is not found; using default GEMM algo
terminate called after throwing an instance of 'std::runtime_error'
  what():  [FT][ERROR] CUDA runtime error: invalid argument /opt/tritonserver/lmdeploy/src/turbomind/utils/allocator.h:252 

Aborted (core dumped)

**Comment by happened** [comment]
`deepspeed --module lmdeploy.pytorch.chat /models/internlm-chat-7b --num_gpus 2 --max_new_tokens 64 --temperture 0.8 --top_p 0.95 --seed 0 ` 通过deepspeed部署没有问题

**Comment by happened** [comment]
![image](https://github.com/InternLM/lmdeploy/assets/20530955/c95df933-f21d-4479-81ab-8d6f7d8fe93b)
转换Wieturbomind支持多卡么 是否需要设置一些参数？我感觉这个错误应该和卡数量有关，在error的过程中显存都是一张卡上撑满的

**Comment by grimoire** [comment]
python 的 tp 功能在 https://github.com/InternLM/lmdeploy/pull/82 中还没合入，可以尝试这个分支或者用 serving 的方式启动

**Comment by happened** [comment]
感谢你的回复，我使用评论中的 https://github.com/InternLM/lmdeploy/pull/82 对应的分支编译安装了下 现在可以分在两个显卡上运行了
![image](https://github.com/InternLM/lmdeploy/assets/20530955/16c62a6e-a433-4584-b41e-d5414a14f818)
![image](https://github.com/InternLM/lmdeploy/assets/20530955/e6fb51a0-0ae6-4a18-b4f1-67b280eb0a3d)

但是通过`python3 -m lmdeploy.serve.client {server_ip_addresss}:33337 internlm`
这个命令去调用终端不会有任何输出，服务终端有如下输出
![image](https://github.com/InternLM/lmdeploy/assets/20530955/77099599-dfc5-4fa5-ba29-7f4b71ecec92)


这可能是什么原因呀？

**Comment by Hiwyl** [comment]
@happened 和你现象一致，webui也是无任何输出

**Comment by grimoire** [comment]
@lzhangzz

**Comment by happened** [comment]
@Hiwyl  现在最新的main分支已经修复了 可以试下
