### ISSUE TITLE
[Feature] Add new AWQ kernels

### ISSUE THREAD

**Issue by orendar** [InternLM/lmdeploy#1301]
### Motivation

The new AWQ kernels are a mix of GEMM and GEMV, and so are faster and require less memory and scale better than the old ones, but require requantization of old models.

### Related resources

See these PRs:
https://github.com/casper-hansen/AutoAWQ/pull/365
https://github.com/vllm-project/vllm/pull/3289

### Additional context

Thank you for considering this feature request!

**Comment by lzhangzz** [comment]
Well, if you look close enough, you'll see how their new kernels are related to ours (which released 7 months ago).

Just compre https://github.com/mit-han-lab/llm-awq/pull/142 and  https://github.com/InternLM/lmdeploy/pull/202, they even left some variable/function names unchanged.
