### ISSUE TITLE
PyTorch backend issue

### ISSUE THREAD

**Issue by sleepwalker2017** [InternLM/lmdeploy#1303]
I run lmdeploy on 2*A30, and find this.

The GPU util is always 100% for GPU 1, even if there is no request.

![image](https://github.com/InternLM/lmdeploy/assets/26128514/6627fd60-7168-437a-9f30-11284e33e86c)

The script I'm using:
`lmdeploy serve api_server /data/vicuna-13b/vicuna-13b-v1.5/ --backend pytorch --tp 2`

**Comment by sleepwalker2017** [comment]
![image](https://github.com/InternLM/lmdeploy/assets/26128514/ddb0d523-fefd-4c95-b14d-a7852f619ca3)

![image](https://github.com/InternLM/lmdeploy/assets/26128514/9a36323c-7340-4da3-b1bb-e11ca20606c2)

@grimoire   看起来是 NCCL 的耗时占了大头

**Comment by grimoire** [comment]
这个我比较无能为力，这边 distribution 的行为就是 torch 封装的没做啥特殊处理
https://github.com/InternLM/lmdeploy/blob/9a00760743773ac1ced33330fe602ef6c0464ac4/lmdeploy/pytorch/models/llama.py#L69

**Comment by sleepwalker2017** [comment]
> 这个我比较无能为力，这边 distribution 的行为就是 torch 封装的没做啥特殊处理
> 
> https://github.com/InternLM/lmdeploy/blob/9a00760743773ac1ced33330fe602ef6c0464ac4/lmdeploy/pytorch/models/llama.py#L69

好的  我来看看这块

**Comment by sleepwalker2017** [comment]
> 这个我比较无能为力，这边 distribution 的行为就是 torch 封装的没做啥特殊处理
> 
> https://github.com/InternLM/lmdeploy/blob/9a00760743773ac1ced33330fe602ef6c0464ac4/lmdeploy/pytorch/models/llama.py#L69

想请教下   这种协程的代码要如何跟踪执行调用呢？似乎 pdb 在里面无法使用，我现在不知道每层调到哪里了，看代码跳一会就晕了。感谢

**Comment by grimoire** [comment]
协程可以用 pdb的。TP 程序会起子进程，这才是导致 pdb 失效的原因。这边基本就靠打 log 了

tp 情况下是经过
https://github.com/InternLM/lmdeploy/blob/d6a6b3f2024f75526b55f8d2b9fd56881909b714/lmdeploy/pytorch/engine/model_agent.py#L933
进入
https://github.com/InternLM/lmdeploy/blob/d6a6b3f2024f75526b55f8d2b9fd56881909b714/lmdeploy/pytorch/engine/model_agent.py#L335

进入模型的，然后部分模块会在 lmdeploy.pytorch.models 里进行替换。

**Comment by grimoire** [comment]
https://github.com/InternLM/lmdeploy/pull/1392 I have done some optimization, Please have a try.
