### ISSUE TITLE
[Bug] qwen vlm模型推理显存疑问

### ISSUE THREAD

**Issue by Cristhine** [InternLM/lmdeploy#1311]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

qwen本来的fp16模型在a100推理只占20G左右，使用lmdeploy去调用显存占40g，请问这个是什么导致的？
![image](https://github.com/InternLM/lmdeploy/assets/26667855/a3d8f6ea-0287-4ce4-b412-07e14e17b438)

### Reproduction

from lmdeploy import pipeline
from lmdeploy.vl import load_image

pipe = pipeline('../models--Qwen--Qwen-VL-Chat/')

image = load_image('https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/tests/data/tiger.jpeg')
response = pipe(('describe this image', image))
print(response)

### Environment

```Shell
sys.platform: linux
Python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA A100-PCIE-40GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.1, V12.1.105
GCC: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 2.1.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.16.2+cu121
LMDeploy: 0.2.6+unknown
transformers: 4.38.1
gradio: Not Found
fastapi: 0.110.0
pydantic: 2.6.4
```

**Comment by irexyc** [comment]
主要是TurbomindEngineConfig里面的cache_max_entry_count 导致的。

TurboMind 初始化流程是先加载模型权重，然后剩下的显存按照百分比申请kvcache，最后再加载vision的模型。

你可以调整cache_max_entry_count来降低显存的占用。

**Comment by Cristhine** [comment]
> 主要是TurbomindEngineConfig里面的cache_max_entry_count 导致的。
> 
> TurboMind 初始化流程是先加载llm模型权重，然后剩下的显存按照百分比申请kvcache，最后再加载vision的模型。
> 
> 你可以调整cache_max_entry_count来降低显存的占用。

感谢回复已调整，请问这个pipline如何取消history 我尝试for训练调用十次相同的图以及相同的prompts，结果非常不同
调用方式如下：
from lmdeploy import pipeline
from lmdeploy import pipeline, TurbomindEngineConfig
from lmdeploy.vl import load_image
import time

pipe = pipeline('../models--Qwen--Qwen-VL-Chat/', backend_config=TurbomindEngineConfig(cache_max_entry_count=0.1))

before_time = time.time()
for i in range(10):
    image = load_image('./shunyi_97_191125_d949c957200a.jpg')
    response = pipe(('框出图中暴露垃圾的位置', image))
    print(response)

**Comment by irexyc** [comment]
pipeline的__call__接口不带状态，所以没有history。

不一样的结果应该是因为seed造成的，默认情况下会随机一个seed。要固定结果，你可以传一个seed进去，比如
```
gen_config = GenerationConfig(top_k=40, random_seed=0)
response = pipe(('框出图中暴露垃圾的位置', image), gen_config=gen_config)
```

**Comment by Cristhine** [comment]
> pipeline的__call__接口不带状态，所以没有history。
> 
> 不一样的结果应该是因为seed造成的，默认情况下会随机一个seed。要固定结果，你可以传一个seed进去，比如
> 
> ```
> gen_config = GenerationConfig(top_k=40, random_seed=0)
> response = pipe(('框出图中暴露垃圾的位置', image), gen_config=gen_config)
> ```

gen_config = GenerationConfig(top_k=1, top_p=0.3, random_seed=0, temperature=0.5)
pipe = pipeline('../models--Qwen--Qwen-VL-Chat/', backend_config=TurbomindEngineConfig(cache_max_entry_count=0.1), gen_config=gen_config)
尝试了加了这些参数，即便设置的非常严格，输出还是有较大的差异 请问这个是怎么回事，尝试过设置topk=1 top_p=0.3 在原始的qwen模型上基本输出就是一致的了
![image](https://github.com/InternLM/lmdeploy/assets/26667855/dc049182-2881-407f-84ed-8f0dc91f58c5)

**Comment by irexyc** [comment]
```
gen_config = GenerationConfig(top_k=1, top_p=0.3, random_seed=0, temperature=0.5)
pipe = pipeline('../models--Qwen--Qwen-VL-Chat/', backend_config=TurbomindEngineConfig(cache_max_entry_count=0.1), gen_config=gen_config)
```

这个用法不对，gen_config是推理的时候用的，不是创建pipe时候用的。

**Comment by Cristhine** [comment]
> ```
> gen_config = GenerationConfig(top_k=1, top_p=0.3, random_seed=0, temperature=0.5)
> pipe = pipeline('../models--Qwen--Qwen-VL-Chat/', backend_config=TurbomindEngineConfig(cache_max_entry_count=0.1), gen_config=gen_config)
> ```
> 
> 这个用法不对，gen_config是推理的时候用的，不是创建pipe时候用的。

感谢感谢，放到正确位置后输出稳定了
