### ISSUE TITLE
[Bug] 支持对internlm2-chat-7b 按 load_in_4bit 加载吗 

### ISSUE THREAD

**Issue by wwewwt** [InternLM/lmdeploy#1312]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

背景：

我想用llmdeploy 来部署 internlm2-chat-7b，但因为是v100，所以不能使用internlm2-chat-7b-4bits

llmdeploy 使用  internlm2-chat-7b 进行推理的命令：
lmdeploy serve api_server internlm/internlm2-chat-7b

在显存的占用上和下面的推理代码相同（占用16G+）
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("internlm/internlm2-chat-7b", trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("internlm/internlm2-chat-7b", device_map="auto",trust_remote_code=True,)
model = model.eval()

问题，我想降低显存占用
使用以下代码是可以将显存控制在（8G），通过在from_pretrained中添加参数load_in_4bit=True
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("internlm/internlm2-chat-7b", trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("internlm/internlm2-chat-7b", device_map="auto",trust_remote_code=True, load_in_4bit=True)
model = model.eval()

请问llmdeploy 部署 internlm2-chat-7b ，支持使用 load_in_4bit 来加载模型吗，命令该如何写呢？

### Reproduction

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("internlm/internlm2-chat-7b", trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("internlm/internlm2-chat-7b", device_map="auto",trust_remote_code=True, load_in_4bit=True)
model = model.eval()

### Environment

```Shell
Pytorch：2.1.2+cu121
LMDeploy：0.2.4+
transformers：4.37.1
V100
```

**Comment by lvhan028** [comment]
不支持 load_in_4bit 这种方式。
LMDeploy 4bit 量化和推理，可以参考这份文档：https://lmdeploy.readthedocs.io/en/latest/quantization/w4a16.html
