### ISSUE TITLE
serve llava-v1.6-vicuna-7b failed with lmdeploy 0.2.6 version

### ISSUE THREAD

**Issue by wanzhenchn** [InternLM/lmdeploy#1316]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

Serve [llava-v1.6-vicuna-7b](https://huggingface.co/liuhaotian/llava-v1.6-vicuna-7b) failed with lmdeploy 0.2.6 version on **2 *A30 (24GB)**，the reason is that **OOM** as below.

![image](https://github.com/InternLM/lmdeploy/assets/24476563/789325d4-60a5-4627-8187-9f3be4c50280)

### Reproduction

Lmdeploy: 0.2.6
Model: [llava-v1.6-vicuna-7b](https://huggingface.co/liuhaotian/llava-v1.6-vicuna-7b)
```sh

lmdeploy serve api_server /data/models/llava-v1.6-vicuna-7b/ --server-port 80012 --tp 2
```

### Environment

```Shell
sys.platform: linux
Python: 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1: NVIDIA A30
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 2.1.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.16.2+cu121
LMDeploy: 0.2.6+
transformers: 4.37.2
gradio: 4.16.0
fastapi: 0.110.0
```

**Comment by irexyc** [comment]
You can try to reduce the kv cache memory usage by pass `--cache-max-entry-count 0.1`.  

The kv cache memory is used for large batch size and long session length.

```
lmdeploy serve api_server /data/models/llava-v1.6-vicuna-7b/ --server-port 80012 --tp 2 --cache-max-entry-count 0.1
```

**Comment by wanzhenchn** [comment]
> You can try to reduce the kv cache memory usage by pass `--cache-max-entry-count 0.1`.
> 
> The kv cache memory is used for large batch size and long session length.
> 
> ```
> lmdeploy serve api_server /data/models/llava-v1.6-vicuna-7b/ --server-port 80012 --tp 2 --cache-max-entry-count 0.1
> ```

The default value of `--cache-max-entry-count ` is 0.8, which causes unsufficient  free memory for torch framework.

Thanks a lot.

**Comment by wanzhenchn** [comment]
Why isn't the kv cache memory **evenly allocated** on both cards?

![image](https://github.com/InternLM/lmdeploy/assets/24476563/54f07baa-7248-4e97-a9d2-b2dafcc00308)

**Comment by irexyc** [comment]
when you init the vl model with turbomind backend. First, it will allocate memory for llm model weights and then allocate kv cache. The memory on two gpus shoud be same with these two steps. After that, the pipeline will use pytorch to load the vision model, the different memory in the red box is the vision model used.

**Comment by wanzhenchn** [comment]
> the vl pipeline have two parts, the llm and vision. For now, the llm part only support turbomind backend. The vision part is with pytorch backend.
> 
> when you init the pipeline with turbomind backend. First, turbomind will allocate memory for llm model weights and then allocate kv cache. The memory on two gpus shoud be same with these two steps. After that, the pipeline will use pytorch to load the vision model, the different memory in the red box is the vision model used.

I understand that. So when does the vision model support with turbomind backend?

Do you have benchmarked the performance for LMM(large multimodal model) models (like llava-v1.6-vicuna-13b) with the pipeline consists of turbomind backend for llm and pytorch backend for vision model?

**Comment by irexyc** [comment]
We are not likely to support inference the vision model by turbomind as structure of the vision model is not very fixed. We might look into whether using triton or some other tools can improve the vision model performance.

There is no benchmark result from vl yet. Compared to other inference tools, we add the batching strategy to collect images with received server requests, while the performance is mainly affected by llm part as exists models only support single or less images as input.

**Comment by lvhan028** [comment]
@wanzhenchn is there any public benchmark you can share?

**Comment by wanzhenchn** [comment]
> We are not likely to support inference the vision model by turbomind as structure of the vision model is not very fixed. We might look into whether using triton or some other tools can improve the vision model performance.
> 
> There is no benchmark result from vl yet. Compared to other inference tools, we add the batching strategy to collect images with received server requests, while the performance is mainly affected by llm part as exists models only support single or less images as input.

Many thanks for your response. Actually, there are relatively few inference frameworks that support multimodal models at present, and to the best of my knowledge, vllm does not currently support it, and the [LLaVA](https://github.com/haotian-liu/LLaVA) seems to be not very user-friendly.

**Comment by wanzhenchn** [comment]
> @wanzhenchn is there any public benchmark you can share?

I just begin to reaearch and benckmark the framework which has supported LMMs these days. I will be happy to share the benchmark data if it is available.

**Comment by wanzhenchn** [comment]
> The vl pipeline have two parts, the llm and vision. For now, the llm part only support turbomind backend. The vision part is with pytorch backend.
> 
> When you init the vl pipeline. First, turbomind will allocate memory for llm model weights and then allocate kv cache. The memory on two gpus shoud be same with these two steps. After that, the pipeline will use pytorch to load the vision model, the different memory in the red box is the vision model used.

As you said, the gpu1 memory used should be about: **15461 MB + 1.7*1000MB =  17161 MB ≈ 18GB** (the model size of [clip-vit-large-patch14-336](https://huggingface.co/openai/clip-vit-large-patch14-336/tree/main)),

However, the gpu1 memory used **23.9 GB** actually, what's wrong  about it?
@irexyc 
![image](https://github.com/InternLM/lmdeploy/assets/24476563/54f07baa-7248-4e97-a9d2-b2dafcc00308)

**Comment by irexyc** [comment]
> However, the gpu1 memory used 23.9 GB actually, what's wrong about it?

fixed it in https://github.com/InternLM/lmdeploy/pull/1325

**Comment by wanzhenchn** [comment]
> > However, the gpu1 memory used 23.9 GB actually, what's wrong about it?
> 
> fixed it in #1325

If I set the `--cache-max-entry-count 0.001 `, the gpu1's memory usage is **14 GB**, then I increase the value of `--cache-max-entry-count 0.3 `,  the gpu1 will OOM. **It seems that there is still some problems about gpu memory management for vision model with torch backend**

Given the meaning of `cache_max_entry_count` [determines the percentage of **free memory** for k/v blocks](https://github.com/InternLM/lmdeploy/blob/main/docs/en/inference/turbomind_config.md#kv-cache-size), the server should work well when setting `--cache-max-entry-count 0.3 `, the memory usage of gpu1 is about
 `13317 + (24576-13317)*0.3 + 1.7*1000 = 18.3 GB`, However, the OOM occurs.

@irexyc 

![image](https://github.com/InternLM/lmdeploy/assets/24476563/fd70031e-dfca-4476-8727-e674f6c45e8d)

**Comment by irexyc** [comment]
I modifed the vision model loading strategy. Now, the model will be loaded on cpu first and then moved to gpu, so the peck cuda memory should be smaller than previous. You can try again.

**Comment by wanzhenchn** [comment]
> I modifed the vision model loading strategy. Now, the model will be loaded on cpu first and then moved to gpu, so the peck cuda memory should be smaller than previous. You can try again.

LGTM
