### ISSUE TITLE
'InternLMTokenizer' object has no attribute 'backend_tokenizer'

### ISSUE THREAD

**Issue by happened** [InternLM/lmdeploy#132]
在Inference by TurboMind的时候使用命令
`python3 -m lmdeploy.turbomind.chat internlm ./workspace/`报错
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/tritonserver/lmdeploy/lmdeploy/turbomind/chat.py", line 109, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/opt/tritonserver/lmdeploy/lmdeploy/turbomind/chat.py", line 43, in main
    tokenizer = Tokenizer(tokenizer_model_path)
  File "/opt/tritonserver/lmdeploy/lmdeploy/turbomind/tokenizer.py", line 152, in __init__
    self.model = HuggingFaceTokenizer(model_folder)
  File "/opt/tritonserver/lmdeploy/lmdeploy/turbomind/tokenizer.py", line 84, in __init__
    self.model.backend_tokenizer.save(backend_tokenizer_file)
AttributeError: 'InternLMTokenizer' object has no attribute 'backend_tokenizer

我看了下源码，好像这个backend_tokenizer确实没咋用到，这个有用吗

**Comment by grimoire** [comment]
可以去掉，因为 transformers 原来用来生成 token 映射的方式比较慢（两层循环遍历 token 组合），所以这里做个 cache 以免下次重复生成。可以删掉
还有 internlm 的 tp 似乎确实存在问题，正在排查中。

**Comment by happened** [comment]
重新编译并且安装后 用`python3 -m lmdeploy.serve.client {server_ip_addresss}:33337 internlm` 测试了下 ，结果是正常的了

benchmark中关于profile_serving中测试集的dataset能提供一下嘛，看脚本里面对json格式是有要求的

另外profile_generation测试对应tp为2的workspace目录会coredump

**Comment by grimoire** [comment]
@lvhan028 profiling_serving 的 dataset 方面方便提供一些信息吗

coredump 的问题这边的环境上无法复现，能提供更详细的环境信息吗？

**Comment by happened** [comment]
具体步骤如下
```bash
#启动容器 宿主机当前为双T4机器
docker run -itd --net=host --name internlm_server
    --gpus all -v /data/work/deploy-interlm:/workspace 
 -v /data/models/:/models 
 --shm-size 16g 
 --cap-add=SYS_PTRACE --cap-add=SYS_ADMIN --security-opt seccomp=unconfined
 --env NCCL_LAUNCH_MODE=GROUP openmmlab/lmdeploy:latest bash


# 下载仓库并编译
git clone https://github.com/InternLM/lmdeploy.git
mkdir build && cd build 
make && make install

#转换模型为turbomind格式
python3 -m lmdeploy.serve.turbomind.deploy internlm-chat-7b /models/internlm-chat-7b hf  --tokenizer_path /models/internlm-chat-7b/tokenizer.model  --tp 2

#benchmark
cd /opt/tritonserver/lmdeploy
export PYTHONPATH=./:$PYTHONPATH
python3 benchmark/profile_generation.py --model_path /opt/tritonserver/lmdeploy/workspace --model_name internlm --concurrency 4 --input_seqlen 1 --output_seqlen 512--test_round 4
```
操作就是这样 这个会和拆分有关嘛

**Comment by grimoire** [comment]
不清楚，profile_generation 和 lmdeploy.turbomind.chat 用的接口类似，如果 chat 能加载成功的话 profile 应该也可以。

**Comment by lvhan028** [comment]
profile_serving.py用的数据是：
```
wget https://huggingface.co/datasets/anon8231489123/ShareGPT_Vicuna_unfiltered/resolve/main/ShareGPT_V3_unfiltered_cleaned_split.json
```
