### ISSUE TITLE
[Feature] Print the info of the request in the log of api-server

### ISSUE THREAD

**Issue by yetionyo** [InternLM/lmdeploy#1320]
### Motivation

Print the info of the request in the log of api-server (e.g., temperature, prompt ids, prompt), so that we can debug whether the request is prepared correctly.

Just like vllm:
[async_llm_engine.py:436] Received request cmpl-xxxxx: prompt: '<|im_start|>system\n[PROMPT HERE]'

**Comment by lvhan028** [comment]
Sure. @AllentDan please implement this feature asap

**Comment by AllentDan** [comment]
Which version did you use? @yetionyo
