### ISSUE TITLE
Adding support for DeepSeek-VL 7B

### ISSUE THREAD

**Issue by rostandk** [InternLM/lmdeploy#1321]
### Motivation

I ran quite some text on DeepSeek-VL 7B. It is the awesome vision model that nobody is talking about (it is only 1 week old). It is better than Llava 1.6 34B in VQA and OCR. It consistently return JSON when asked and just seems to have a great textual capability.  I would love to have some guidance and how to add it to Lmdeploy. It will make Lmdeploy the to go library for vision.

### Related resources

https://github.com/deepseek-ai/DeepSeek-VL

**Comment by lvhan028** [comment]
@irexyc could you provide the guide?

**Comment by irexyc** [comment]
Added in https://github.com/InternLM/lmdeploy/pull/1332

By the way, @AllentDan is working on DeepSeek-VL

**Comment by lvhan028** [comment]
PR has been merged and will be released in v0.3.0 tomorrow
