### ISSUE TITLE
Any Colab demo? [Feature] 

### ISSUE THREAD

**Issue by teraktor2006** [InternLM/lmdeploy#1322]
### Motivation

colab demo for easy checking

**Comment by lvhan028** [comment]
Not yet. What demo are you expecting, LLM or VLM?

**Comment by lvhan028** [comment]
PR #1428 is dealing with this feature

**Comment by lvhan028** [comment]
The colab demos are provided. Please check them in the guide: https://github.com/InternLM/lmdeploy?tab=readme-ov-file#tutorials
