### ISSUE TITLE
[Bug] Memory leak for api_server

### ISSUE THREAD

**Issue by ispobock** [InternLM/lmdeploy#1334]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

When starting the api_server and sending requests from client, the memory usage of the api_server will increase. If kill the client, the memory usage of server will not drop. 

In our test environment, for every 1000 prompts, the memory usage will increase 0.1% (116G memory overall).

### Reproduction

1. start server:
```
lmdeploy serve api_server ./workspace --server-name 0.0.0.0 --server-port 23333 --tp 1
```
2. start profiling script:
```
python benchmark/profile_restful_api.py --server_addr 0.0.0.0:23333 --tokenizer_path /path/to/tokenizer --dataset /path/to/ShareGPT_V3_unfiltered_cleaned_split.json --concurrency 128 --num_prompts 50000
```
3. observe the memory usage change of api_server process by `htop`

### Environment

```Shell
sys.platform: linux
Python: 3.9.16 (main, Aug 15 2023, 19:38:56) [GCC 8.3.1 20190311 (Red Hat 8.3.1-3)]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA A100-SXM4-80GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: gcc (GCC) 10.2.1 20210130 (Red Hat 10.2.1-11)
PyTorch: 2.1.2+cu118
TorchVision: 0.16.2+cu121
LMDeploy: 0.2.5+
transformers: 4.37.1
gradio: 3.50.2
fastapi: 0.104.1
pydantic: 2.6.0
```

**Comment by zhyncs** [comment]
If LMDeploy is used on a Linux server as a daemon program running for a long time, with the accumulation of requests, it will eventually cause memory OOM and lead to the system killing off the process. Currently, this seems to be a very urgent bug. Hi @AllentDan  could you please take a look at it? Thanks.

**Comment by zhyncs** [comment]
@lvhan028 @AllentDan Before being used in a production environment, it is necessary to conduct stress testing and stability testing. We discovered this issue during this process, and the issue occurs consistently. I am not very clear about your usage scenario. In your actual production deployment, after the program has been running for a long time, have you encountered memory leaks as described in the reported issues? Thanks.

**Comment by lvhan028** [comment]
@zhulinJulia24 may follow it

**Comment by lvhan028** [comment]
Which model are you using?
Have you changed any parameters in `config.ini`?

**Comment by AllentDan** [comment]
Im not sure if it is caused by
https://github.com/InternLM/lmdeploy/blob/f43d099724bb6c8203cc241df87cc0611cd2ad05/lmdeploy/serve/async_engine.py#L211-L212.
The two variables `id2step` and `id2generator` will accumulate automatically. One way to verify it may be using `/v1/chat/interactive` interface and passing the `session_id` in.

**Comment by ispobock** [comment]
> Which model are you using? Have you changed any parameters in `config.ini`?

The model is llama2_13b_chat. The `config.ini` is default.

**Comment by zhulinJulia24** [comment]
> ### Checklist
> * [x]  1. I have searched related issues but cannot get the expected help.
> * [x]  2. The bug has not been fixed in the latest version.
> 
> ### Describe the bug
> When starting the api_server and sending requests from client, the memory usage of the api_server will increase. If kill the client, the memory usage of server will not drop.
> 
> In our test environment, for every 1000 prompts, the memory usage will increase 0.1% (116G memory overall).
> 
> ### Reproduction
> 1. start server:
> 
> ```
> lmdeploy serve api_server ./workspace --server-name 0.0.0.0 --server-port 23333 --tp 1
> ```
> 
> 2. start profiling script:
> 
> ```
> python benchmark/profile_restful_api.py --server_addr 0.0.0.0:23333 --tokenizer_path /path/to/tokenizer --dataset /path/to/ShareGPT_V3_unfiltered_cleaned_split.json --concurrency 128 --num_prompts 50000
> ```
> 
> 3. observe the memory usage change of api_server process by `htop`
> 
> ### Environment
> ```shell
> sys.platform: linux
> Python: 3.9.16 (main, Aug 15 2023, 19:38:56) [GCC 8.3.1 20190311 (Red Hat 8.3.1-3)]
> CUDA available: True
> MUSA available: False
> numpy_random_seed: 2147483648
> GPU 0: NVIDIA A100-SXM4-80GB
> CUDA_HOME: /usr/local/cuda
> NVCC: Cuda compilation tools, release 11.8, V11.8.89
> GCC: gcc (GCC) 10.2.1 20210130 (Red Hat 10.2.1-11)
> PyTorch: 2.1.2+cu118
> TorchVision: 0.16.2+cu121
> LMDeploy: 0.2.5+
> transformers: 4.37.1
> gradio: 3.50.2
> fastapi: 0.104.1
> pydantic: 2.6.0
> ```

I cannot reproduce it on 0.2.6 version by using internlm2-chat-20b model.

**Comment by ispobock** [comment]
> I cannot reproduce it on 0.2.6 version by using internlm2-chat-20b model. I notice you didn't use the latest profile_restful_api.py benchmark file.
> 
> Can your profile_restful_api.py file version.

@zhulinJulia24 I tried the 0.2.6 and the `profile_restful_api.py` is the latest version. The memory leak problem is still there.
How many prompts did you test? How do you observe the memory change of the api_server process?

**Comment by ispobock** [comment]
@AllentDan I tried to add the following code to debug:
```python
import tracemalloc
tracemalloc.start()
lis = []
@app.get('/v1/mem_info', dependencies=[Depends(check_api_key)])
def get_info():
    snapshot = tracemalloc.take_snapshot()
    if len(lis) == 0:
        lis.append(snapshot)
        return "N/A"
    last = lis[-1]
    top_stats = snapshot.compare_to(last, 'lineno')
    return ' \n '.join([stat.__str__() for stat in top_stats[:10]])
```
And found the memory diff is mainly caused by the `dlpack`:
```
 /workdir/miniconda3/lib/python3.11/site-packages/torch/utils/dlpack.py:117: size=74.3 MiB (+74.3 MiB), count=1623178 (+1623178), average=48 B 
 <unknown>:0: size=1415 KiB (+1415 KiB), count=25860 (+25860), average=56 B 
 /workdir/lmdeploy/lmdeploy/turbomind/turbomind.py:516: size=1404 KiB (+1404 KiB), count=25681 (+25681), average=56 B 
 /workdir/lmdeploy/lmdeploy/serve/async_engine.py:533: size=583 KiB (+583 KiB), count=7372 (+7372), average=81 B 
 /workdir/lmdeploy/lmdeploy/serve/async_engine.py:347: size=583 KiB (+583 KiB), count=7372 (+7372), average=81 B 
 /workdir/miniconda3/lib/python3.11/threading.py:258: size=652 KiB (+364 KiB), count=1758 (+982), average=380 B 
 /workdir/miniconda3/lib/python3.11/queue.py:252: size=217 KiB (+217 KiB), count=121 (+121), average=1834 B 
 /workdir/miniconda3/lib/python3.11/tracemalloc.py:115: size=156 KiB (+156 KiB), count=1998 (+1998), average=80 B 
 /workdir/miniconda3/lib/python3.11/tracemalloc.py:193: size=93.4 KiB (+93.4 KiB), count=1993 (+1993), average=48 B 
 /workdir/miniconda3/lib/python3.11/_weakrefset.py:88: size=68.5 KiB (+65.8 KiB), count=139 (+130), average=505 B
```

**Comment by zhulinJulia24** [comment]
> > I cannot reproduce it on 0.2.6 version by using internlm2-chat-20b model. I notice you didn't use the latest profile_restful_api.py benchmark file.
> > Can your profile_restful_api.py file version.
> 
> @zhulinJulia24 I tried the 0.2.6 and the `profile_restful_api.py` is the latest version. The memory leak problem is still there. How many prompts did you test? How do you observe the memory change of the api_server process?


reproduce step:
1. convert model 
`lmdeploy convert llama2 /path-to-Llama-2-13b-chat-hf
`
2. start restful api server
`lmdeploy serve api_server workspace
`
3. start resful profile like: 
`python benchmark/profile_restful_api.py 0.0.0.0:23333 ../workspace/triton_models/tokenizer ../ShareGPT_V3_unfiltered_cleaned_split.json --concurrency 128 --num_prompts 50000`

4. observe gpu memory by using `nvidia-smi`, It's the same during the process.
![image](https://github.com/InternLM/lmdeploy/assets/145004780/77ca42e3-dd82-4ab9-957b-12cc39052bb8)

Do you hava any suggestions?

**Comment by ispobock** [comment]
@zhulinJulia24 I mean the memory leak is about cpu memory, not gpu memory. You can use `htop` or other tools to check the cpu memory change.

**Comment by zhyncs** [comment]
Maybe we could call show_memory in the while loop at intervals. Some code snippets like this:
```python3
import gc
import sys

def show_memory():
    print("*" * 60)
    objects_list = []
    for obj in gc.get_objects():
        size = sys.getsizeof(obj)
        objects_list.append((obj, size))

    sorted_values = sorted(objects_list,
                           key=lambda x: x[1],
                           reverse=True)

    for obj, size in sorted_values[:10]:
        print(f"OBJ: {id(obj)}, "
              f"TYPE: {type(obj)}, "
              f"SIZE: {size/1024/1024:.2f}MB, "
              f"REPR: {str(obj)[:100]}")
```

**Comment by zhulinJulia24** [comment]
> @zhulinJulia24 I mean the memory leak is about cpu memory, not gpu memory. You can use `htop` or other tools to check the cpu memory change.

Thanks, I can reproduce it!

**Comment by ispobock** [comment]
The `dlpack` may be one of the memory leak parts, refer to PR https://github.com/InternLM/lmdeploy/pull/1344. Apart from this, the memory will still increase as new requests come. There must be other factors that may cause memory leaks.

**Comment by zhyncs** [comment]
Hi @AllentDan After fixing https://github.com/InternLM/lmdeploy/pull/1344, the memory leak issue has not been fully resolved. Can you please revisit this problem when you have a moment?

**Comment by AllentDan** [comment]
> Hi @AllentDan After fixing #1344, the memory leak issue has not been fully resolved. Can you please revisit this problem when you have a moment?

Yeah, I've got time for this now. After some research and testing, it seems to me that we have to collect the garbage from the server by the interval.

I will pull a merge request ASAP.

**Comment by AllentDan** [comment]
I compared two backends. Found that the memory leak only happens for turbomind backend. For pytorch backend, after `gc.collect`, the mem is stable at the `7448Mb` level.

**Comment by zhyncs** [comment]
> I compared two backends. Found that the memory leak only happens for turbomind backend. For pytorch backend and internlm2-chat-7b model, after `gc.collect`, the mem is stable at the `7448Mb` level.

@ispobock  has previously tested with Triton Server C++ backend + TurboMind separately and did not find any memory leaks. This indicates that the TurboMind Engine itself should be okay. Therefore, I suspect that the issue may lie in the code related to TurboMind in the API Server. Do you have any ideas on this? @AllentDan

**Comment by AllentDan** [comment]
Then, I suspect the mem leak was caused by pybind part. The difference between api_server and triton server is that api_server will run codes of `pybind` part.

**Comment by AllentDan** [comment]
https://github.com/InternLM/lmdeploy/pull/1360 further fixed a part of the mem leak. But still, about how to release memory when converting dlmanged tensor to triton tensor, I have no idea.

**Comment by ispobock** [comment]
Fixed in https://github.com/InternLM/lmdeploy/pull/1361, close this issue.

**Comment by zhyncs** [comment]
Hi all @lvhan028 @lzhangzz @grimoire @AllentDan @zhulinJulia24  In short, the repair of the API Server depends on https://github.com/InternLM/lmdeploy/pull/1361 https://github.com/InternLM/lmdeploy/pull/1344 The repair of Triton Python Backend Stream mode **also** depends on https://github.com/InternLM/lmdeploy/issues/1363
