### ISSUE TITLE
[Bug] 使用lmdeploy serve api_server进行internlm2-chat-7b-4bits模型推理服务时，返回乱码，无法返回正确数据。

### ISSUE THREAD

**Issue by hello-gary-2022** [InternLM/lmdeploy#1340]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

通过下面的命令启动服务（离线推理）：
lmdeploy serve api_server internlm/internlm2-chat-7b-4bits --backend turbomind --model-format awq  --server-port 23333 --cache-max-entry-count 0.5 --model-name internlm2

问题：  
使用OpenAI兼容的/v1/chat/completions，请求服务时，会返回乱码：

步骤：  
打开文本页面：http://0.0.0.0:23333 ，使用 /v1/chat/completions 接口 
- 控制台输出：- INFO:     13.229.148.92:0 - "POST /v1/chat/completions HTTP/1.1" 200 OK
-  请求参数和返回值见下图
![Post请求参数](https://github.com/InternLM/lmdeploy/assets/99777844/8a646f8d-0753-4706-9291-ce2be540ba3e)
![请求返回值](https://github.com/InternLM/lmdeploy/assets/99777844/a6094200-f8a4-4de4-b9b7-9950f0e11d5d)

备注：internlm2-chat-7b-4bits 无法返回正确的数据，而同样的方法使用internlm/internlm-chat-7b则一切正常。
lmdeploy serve api_server internlm/internlm-chat-7b --server-port 23333 --cache-max-entry-count 0.5

 

### Reproduction

lmdeploy serve api_server internlm/internlm2-chat-7b-4bits --backend turbomind --model-format awq  --server-port 23333 --cache-max-entry-count 0.5 --model-name internlm2

### Environment

```Shell
硬件： T4 ，显存16G
```

### Error traceback

```Shell
pytorch_model-00001-of-00003.bin: 100%|█████| 1.98G/1.98G [00:10<00:00, 189MB/s]
Fetching 14 files:  50%|████████████▌            | 7/14 [00:10<00:11,  1.59s/it]
pytorch_model-00002-of-00003.bin: 100%|█████| 1.98G/1.98G [00:10<00:00, 189MB/s]
Fetching 14 files: 100%|████████████████████████| 14/14 [00:10<00:00,  1.31it/s]
[WARNING] gemm_config.in is not found; using default GEMM algo                  
HINT:    Please open http://0.0.0.0:23333 in a browser for detailed api usage!!!
HINT:    Please open http://0.0.0.0:23333 in a browser for detailed api usage!!!
HINT:    Please open http://0.0.0.0:23333 in a browser for detailed api usage!!!
INFO:     Started server process [132]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:23333 (Press CTRL+C to quit)
INFO:     13.229.148.92:0 - "GET / HTTP/1.1" 200 OK
INFO:     13.229.148.92:0 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     13.229.148.92:0 - "GET /v1/models HTTP/1.1" 200 OK
INFO:     13.229.148.92:0 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     13.229.148.92:0 - "POST /v1/chat/completions HTTP/1.1" 200 OK
```

**Comment by hello-gary-2022** [comment]
OK，我自己编译即可，多谢



---- 回复的原邮件 ----
| 发件人 | Lyu ***@***.***> |
| 日期 | 2024年03月25日 21:49 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [InternLM/lmdeploy] [Bug] 使用lmdeploy serve api_server进行internlm2-chat-7b-4bits模型推理服务时，返回乱码，无法返回正确数据。 (Issue #1340) |

lmdeploy sm75 的kernel有问题，已经在main分支修改了，不过还没有发版。
可以先源码编译 lmdeploy：https://lmdeploy.readthedocs.io/en/latest/build.html
如果有障碍的话，我可以在github上出发编译，然后把编好的包发给你。

**Comment by lvhan028** [comment]
v0.3.0 发布了，可以试试看

**Comment by hello-gary-2022** [comment]
收到



---- 回复的原邮件 ----
| 发件人 | Lyu ***@***.***> |
| 日期 | 2024年04月03日 10:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [InternLM/lmdeploy] [Bug] 使用lmdeploy serve api_server进行internlm2-chat-7b-4bits模型推理服务时，返回乱码，无法返回正确数据。 (Issue #1340) |

v0.3.0 发布了，可以试试看
