### ISSUE TITLE
[Feature] PyTorch Engine add interfaces to support other backend such as FlashInfer

### ISSUE THREAD

**Issue by zhyncs** [InternLM/lmdeploy#1356]
### Motivation

As we know, the current performance of LMDeploy PyTorch Engine **slightly outperforms** vLLM in throughput. Currently, vLLM is being refactored and aims to integrate with FlashInfer. [FlashInfer](https://github.com/flashinfer-ai/flashinfer) has outstanding performance and is expected to bring throughput benefits to vLLM. In addition, many other LLM serving frameworks also use FlashInfer, such as [mlc-llm](https://github.com/mlc-ai/mlc-llm) and [sglang](https://github.com/sgl-project/sglang). I am wondering if the LMDeploy PyTorch Engine, which emphasizes flexibility and ease of use, can consider providing convenience for integrating other backends through interfaces, similar to this kind of abstraction: https://github.com/vllm-project/vllm/pull/3462 If it is worth the time to do this, perhaps we will also assist or take the lead in this matter.

Do you have any any suggestions? Thanks. @lvhan028 @grimoire @RunningLeon

**Comment by lvhan028** [comment]
Hi, @zhyncs thanks for your suggestion.
We've discussed some ideas the other day. Our plan is to develop a kernel package that can be shared by turbomind and pytorch enigne. After that, we might work on its integration to the upstream repository

**Comment by zhyncs** [comment]
> Hi, @zhyncs thanks for your suggestion. We've discussed some ideas the other day. Our plan is to develop a kernel package that can be shared by turbomind and pytorch enigne. After that, we might work on its integration to the upstream repository

Hi @lvhan028  Thank you for your reply. Does this mean that in the future, the PyTorch Engine can use kernels developed by Triton as well as those from TurboMind? If so, does it imply that the PyTorch Engine will also provide a similar abstraction to choose different kernel implementations? If that's the case, it should be easy to integrate other backends like FlashInfer in the future. I'm not sure if I understand it correctly.

**Comment by lvhan028** [comment]
We haven't discussed the detail yet. Let us do more investigation and we'll let you know if there is any update.

**Comment by zhyncs** [comment]
Hi @lvhan028 We have a plan internally to implement prefix cache on LMDeploy. Currently, the SOTA implementation we are aware of in FlashInfer is https://flashinfer.ai/2024/02/02/cascade-inference.html, so if we can integrate it, I think it will save a lot of work.

**Comment by zhyncs** [comment]
> Kernel Python Package is planned to be released in the next three months.

Based on my previous communication with @lzhangzz , `use TurboMind implementation's Attention as a lib` was planned, but now we cannot confirm the specific time. Please stay tuned. It is estimated that if SGLang wants to add support for TurboMind backend in the future, maybe it can be similar to inheriting FlashInfer. cc @merrymercy @Ying1123
