### ISSUE TITLE
Poor performance of serving vision-languange models using batching

### ISSUE THREAD

**Issue by wanzhenchn** [InternLM/lmdeploy#1357]
### Motivation

I have benchmarked the performance of [llava-v1.6-vicuna-13b](https://huggingface.co/liuhaotian/llava-v1.6-vicuna-13b) with api server on 2*A30. The detailed data is as follows.

When using batching, as the batch size increases, **the improvement of token QPS becomes less significant, and the speedup ratio shows a decreasing trend**. 

**Compared to serve LLMs, the speedup from using batching is not significant**.

<img width="1541" alt="image" src="https://github.com/InternLM/lmdeploy/assets/24476563/6ee55a0c-079e-4b9f-acf4-dbd592517067">

- ` Input_Token_Len` denotes the prompt token length, which consists of text and image embedded with vl model
- No stream mode

@irexyc @lvhan028 

follow https://github.com/InternLM/lmdeploy/issues/1316

### Related resources

- [llava-v1.6-vicuna-13b](https://huggingface.co/liuhaotian/llava-v1.6-vicuna-13b)
- 200 prompts and images from [VQAv2](https://github.com/haotian-liu/LLaVA/blob/main/docs/Evaluation.md).
- the profile scripts modified from https://github.com/InternLM/lmdeploy/blob/main/benchmark/profile_restful_api.py

**Comment by irexyc** [comment]
Can you share the used scripts and data ?

**Comment by wanzhenchn** [comment]
> Can you share the used scripts and data ?

- test data: vqav2/llava_vqav2_mscoco_test2015.jsonl, https://drive.google.com/file/d/1atZSBBrAX54yYpxtVVW33zFvcnaHeFPy/view
- [code.zip](https://github.com/InternLM/lmdeploy/files/14771822/code.zip)

```shell
python3 profile_vl_restful_api.py \
  ${http_server_address} \
  /path/to/llava_vqav2_mscoco_test2015.jsonl \
   --concurrency ${bs} \
   --out_len ${request_out_len} \
   --samples 200 \
   --top_k 3 \
   --top_p 0.95 \
   --temperature 0.0 \
   --repetition_penalty 1.15 \
   --device_id ${monitor_device_id} \
   --log_path 'perf.log'
```

**Comment by wanzhenchn** [comment]
> Can you share the used scripts and data ?

Have you finished double-checking the performance data?
@irexyc

**Comment by irexyc** [comment]
Hi, I am working on this issues and will give feedkback week.

**Comment by wanzhenchn** [comment]
> Hi, I am working on this issues and will give feedkback week.

Any progress to share? @irexyc

**Comment by irexyc** [comment]
Sorry for late reply.  I test with llava-v1.6-vicuna-7b and below is my test result.

<img width="690" alt="image" src="https://github.com/InternLM/lmdeploy/assets/16019484/086493ea-3b2d-4d09-b256-9f4d7c0b15ef">


There are some places in your script that need to be modified. If you want to output specific length like 256, you should add `ignore_eos': True` to the pload, therefore the output will not stop until that length. Moreover, you shouldn't use local filepath in the request, you should use [base64](https://platform.openai.com/docs/guides/vision/uploading-base-64-encoded-images) data of image to avoid reading from disk.

The proportion of input token (about 2200) is large compared with output token (257) which limits the speedup ratio, if you use llava1.5 or qwen which use short image features, you will see a better speedup ratio.

**Comment by wanzhenchn** [comment]
> Sorry for late reply. I test with llava-v1.6-vicuna-7b and below is my test result.
> 
> <img alt="image" width="690" src="https://private-user-images.githubusercontent.com/16019484/320259611-086493ea-3b2d-4d09-b256-9f4d7c0b15ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODE1MDYsIm5iZiI6MTcxMjQ4MTIwNiwicGF0aCI6Ii8xNjAxOTQ4NC8zMjAyNTk2MTEtMDg2NDkzZWEtM2IyZC00ZDA5LWIyNTYtOWY0ZDdjMGIxNWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA5MTMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMTFiMzYyYTE5ZTVkYzk1ODgyMWI5MGI2YmQzZjUwZWEyYWFkYjgwYTFjODA4YzY4MTljNWM4ODc2ZGRlNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Osc2nMBw2w1nzG0I1W4mBDTlJgbsSSk0qmC1aXMnLSY">
> There are some places in your script that need to be modified. If you want to output specific length like 256, you should add `ignore_eos': True` to the pload, therefore the output will not stop until that length. Moreover, you shouldn't use local filepath in the request, you should use [base64](https://platform.openai.com/docs/guides/vision/uploading-base-64-encoded-images) data of image to avoid reading from disk.
> 
> The proportion of input token (about 2200) is large compared with output token (257) which limits the speedup ratio, if you use llava1.5 or qwen which use short image features, you will see a better speedup ratio.

Thanks for your checking.

- the parameter `ignore_eos': True` is not required to be passed to pload because the number of tokens generated in the actual scenario may not necessarily be the same as the requested quantity.
- I have used [base64](https://platform.openai.com/docs/guides/vision/uploading-base-64-encoded-images) data of image in scripts above to avoid reading from disk.

However, the token qps re-measured is almost the same as shown in table above based on lmdeploy 0.3.0.

What's the matter? @irexyc

**Comment by irexyc** [comment]
You can set `log_level` to `INFO` and check the server side log. 

<img width="660" alt="image" src="https://github.com/InternLM/lmdeploy/assets/16019484/a2776b3d-1d34-4c1f-b1b6-da80632c8b48">

The red line means the current decoding step has batch size of 128. 

The default `max_batch_size` of TurbomindEngineConfig is 128, but due to `cache_max_entry_count` and `session_len`, the actual running batch size may be little.
