### ISSUE TITLE
[Bug] Triton Server memory leak in python backend decouple mode

### ISSUE THREAD

**Issue by zhyncs** [InternLM/lmdeploy#1363]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

The version of Triton Server currently used in LMDeploy is r22.12 https://github.com/InternLM/lmdeploy/blob/e9d272485f7391a1c605489f0f3fc7f2015db1a5/src/turbomind/triton_backend/CMakeLists.txt#L52-L54 And we are currently using r23.02. Both versions have a memory leak issue when the python backend is in decouple mode and using stream https://github.com/triton-inference-server/server/issues/6270. This issue has been fixed in r23.10 https://github.com/triton-inference-server/python_backend/pull/309

In order to address this issue, we [synchronized](https://github.com/zhyncs/python_backend/commit/2daaf21f0d2b88599d9255b6ea3d940e1c30396f) the fixed commit changes based on r23.02, please refer to the repository at https://github.com/zhyncs/python_backend 

Currently, https://github.com/InternLM/lmdeploy/pull/1329 has been merged into main. I think it is necessary to update the documentation to inform users of this known issue. There are currently two ways to fix it: one is to directly update r22.12 in LMDeploy to r23.10, and the other is similar to our repository's method, only synchronizing the fixed commit.

@lvhan028 @lzhangzz @ispobock @zhulinJulia24 

### Reproduction

N/A

### Environment

```Shell
N/A
```

**Comment by zhyncs** [comment]
> I think it is necessary to update the documentation to inform users of this known issue. There are currently two ways to fix it: one is to directly update r22.12 in LMDeploy to r23.10, and the other is similar to our repository's method, only synchronizing the fixed commit.

@lvhan028 @lzhangzz @zhulinJulia24 Do you have any suggestions? Thanks.

**Comment by irexyc** [comment]
LMDeploy will use cuda 12 by default after 0.2.6, so the base image in Dockerfile and the build deps of triton repositories should also be updated.

**Comment by zhyncs** [comment]
> LMDeploy will use cuda 12 by default after 0.2.6, so the base image in Dockerfile and the build deps of triton repositories should also be updated.
> 
> https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel-24-03.html

Cheers. Shall we update this with r24.03 accordingly?
https://github.com/InternLM/lmdeploy/blob/e9d272485f7391a1c605489f0f3fc7f2015db1a5/src/turbomind/triton_backend/CMakeLists.txt#L52-L54

**Comment by zhyncs** [comment]
I will send a PR asap.
