### ISSUE TITLE
Question about benchmark

### ISSUE THREAD

**Issue by rollroll90** [InternLM/lmdeploy#137]
Hi, I tested LMDeploy with the following steps,
- 1. Get models from https://huggingface.co/internlm/internlm-chat-7b/
- 2. Convert to triton models `python -m lmdeploy.serve.turbomind.deploy interlm-7b interlm-7b hf`
- 3. Run `python3 profile_generation.py --model_path /workspace/ --model_name internlm --concurrency 8 --input_seqlen 1 --output_seqlen 2048 --test_round 8` in provided docker image container `openmmlab/lmdeploy:latest` with A100 80G

The result I get is `throughput: 70.98455828512093 token/s` while the document shows it will reach 640 token/s almost with batch=8. 
![image](https://github.com/InternLM/lmdeploy/assets/139733681/6e8012a0-7f23-49ea-8bc9-84fbedfe817f)

Are there any configurations I need to modify, Thanks

**Comment by jiangjiajun** [comment]
I also tested the generation with another parameters, but get worser result...
```
python3 profile_generation.py --model_path /workspace/ --model_name internlm --concurrency 64 --input_seqlen 1 --output_seqlen 2048 --test_round 8
```
the log shows
```
--------------------------------------------------
concurrency: 64, input_tokens: 1, output_tokens: 2048
elapsed_time: 738.32s
first_token latency(min, max, ave): 45.43s, 94.67s, 89.29s
token latency(min, max, ave): 45.43s, 94.67s, 89.29s
throughput: 22.92672973632506 token/s
--------------------------------------------------
```

**Comment by lvhan028** [comment]
The throughput in `profile_generation.py` should be multiplied by `concurrency`

**Comment by rollroll90** [comment]
> The throughput in `profile_generation.py` should be multiplied by `concurrency`

😂 Thanks, this resolved my confusion.  `profile_generation.py` does calculate average tokens/s for each thread.

In `profile_serving.py`, the `stats` stores `[first_token_latency, generate_token_num, total_latency`, so the following code seems will get total tokens/s for all the processes, but I only get `throughput: 199.67 token/s`, do you know the reason? @lvhan028 

https://github.com/InternLM/lmdeploy/blob/289ffa3cfb4e6ee633cc67a598d8930d6e7f558c/benchmark/profile_serving.py#L176-L179


running command: `python profile_serving.py --tritonserver_addr 0.0.0.0:33437 --model_name internlm --tokenizer_path ../workspace/triton_models/tokenizer/tokenizer.model --dataset_path ShareGPT_V3_unfiltered_cleaned_split.json --concurrency 32 --samples 1000`

![image](https://github.com/InternLM/lmdeploy/assets/139733681/ff5f6673-9b8e-4a52-83a8-4eb8975ffffb)

**Comment by rollroll90** [comment]
@lvhan028 

Yes! I found that `profile_generation.py` does calculate average token/s for each thread.

But while profile serving, I run the following command
```
python profile_serving.py --tritonserver_addr 0.0.0.0:33437 --model_name internlm --tokenizer_path ../workspace/triton_models/tokenizer/tokenizer.model --dataset_path ShareGPT_V3_unfiltered_cleaned_split.json --concurrency 32 --samples 100
```

The result I get is(I think it doesn't need to multiply concurrency)
```
--------------------------------------------------


--------------------------------------------------
cocurrency: 32
elapsed_time: 67.52s
first_token latency(min, max, ave): 0.06s, 0.86s, 0.35s
throughput: 302.31 token/s
--------------------------------------------------
```

Is is right? Since the testing use dataset that length of input/output if not fixed.

**Comment by lvhan028** [comment]
That's a known issue.
The reason is postprocessing(de-tokenize) is very time-consuming.
The inference process of turbomind service is as follows:
```
client:prompt -> [grpc] -> preprocess module:input_ids 
              -> [grpc] -> turbomind module[output_ids] 
              -> [grpc] -> postprocess module:text
```
We found postprocessing module is very time-consuming in streaming chat.
We will optimize it.

**Comment by hljjjmssyh** [comment]
@lvhan028  hi！ 
It looks like turbomind currently only supports streaming chat. Right?

**Comment by lvhan028** [comment]
Yes. If there is requirement for non-stream generation, we can support it

**Comment by hljjjmssyh** [comment]
> 

@lvhan028 yes.  we need it. 
We use internLM to solve other tasks, and fetch all tokens at once. Streaming interface increases the response time.

**Comment by hljjjmssyh** [comment]
> 

Hi! Is there any progress on this feature?

**Comment by lvhan028** [comment]
You can try the latest lmdeploy. A new API `infer` is added in `class Chatbot`
