### ISSUE TITLE
[Bug] 使用A100 每卡80G的机器，在部署qwen1.5 14B时，如果一张卡上启动两个进程，其中一个进程会被挤掉，能不能通过什么参数可以让两个进程平均分配显存

### ISSUE THREAD

**Issue by userandpass** [InternLM/lmdeploy#1390]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

一张卡上启动两个进程，其中一个进程会被挤掉

### Reproduction

CUDA_VISIBLE_DEVICES=4 nohup lmdeploy serve api_server ../Qwen1___5-14B-Chat --server-name 0.0.0.0 --server-port 23337 --tp 1 > log_23337.out 2>&1 &
CUDA_VISIBLE_DEVICES=4 nohup lmdeploy serve api_server ../Qwen1___5-14B-Chat --server-name 0.0.0.0 --server-port 23338 --tp 1 > log_23338.out 2>&1 &

### Environment

```Shell
A100 每卡80G Python3.10 cuda12.1
```

**Comment by lvhan028** [comment]
更新到 lmdeploy v0.3.0 试试看呢？

**Comment by grimoire** [comment]
这边会用加载模型后剩余的显存分配 cache，所以实际会占用更多的显存，推测这可能是你无法用单卡启动多个实例的原因。
可以试试看调整 cache_max_entry_count 和max_prefill_token_num 参数来减少模型的显存占用。注意这些参数同时也会影响 context 长度

**Comment by lvhan028** [comment]
Close it since no more activities over 3 weeks. Feel free to reopen it if it is still an issue
