### ISSUE TITLE
[Feature] deepseek-coder-base model

### ISSUE THREAD

**Issue by ycclnn** [InternLM/lmdeploy#1402]
### Motivation

How can I manage to successfully run the deepseek-coder-6.7b-base model? Converting the model is fine, however the response looks weird.

The prompt I'm giving:
```
"""<｜fim▁begin｜>def quick_sort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[0]
    left = []
    right = []
<｜fim▁hole｜>
        if arr[i] < pivot:
            left.append(arr[i])
        else:
            right.append(arr[i])
    return quick_sort(left) + [pivot] + quick_sort(right)<｜fim▁end｜>"""
```

Need someone point me to the right track cuz I'm new to llm stuff...I tried to change "--chat-template" and "config.ini" but none of them worked.

**Comment by ycclnn** [comment]
``` sh
lmdeploy serve gradio ./workspace --chat-template deepseek-lmdeploy-template.json
2024-04-07 16:02:59,809 - lmdeploy - WARNING - ./workspace seems to be a turbomind workspace, which can only be ran with turbomind engine.
2024-04-07 16:03:01,300 - lmdeploy - INFO - input backend=turbomind, backend_config=TurbomindEngineConfig(model_name=None, model_format=None, tp=1, session_len=None, max_batch_size=128, cache_max_entry_count=0.8, quant_policy=0, rope_scaling_factor=0.0, use_logn_attn=False, download_dir=None, revision=None, max_prefill_token_num=8192)
2024-04-07 16:03:01,300 - lmdeploy - INFO - input chat_template_config=ChatTemplateConfig(model_name='deepseek_base', system='', meta_instruction='', eosys='', user='', eoh='', assistant='', eoa='', separator='', capability='', stop_words=['<｜fim▁end｜>'])
2024-04-07 16:03:01,323 - lmdeploy - INFO - updated chat_template_onfig=ChatTemplateConfig(model_name='deepseek_base', system='', meta_instruction='', eosys='', user='', eoh='', assistant='', eoa='', separator='', capability='', stop_words=['<｜fim▁end｜>'])
2024-04-07 16:03:01,323 - lmdeploy - WARNING - model_source: workspace
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
2024-04-07 16:03:01,401 - lmdeploy - WARNING - model_config:

[llama]
model_name = deepseek_base
tensor_para_size = 1
head_num = 32
kv_head_num = 32
vocab_size = 32256
num_layer = 32
inter_size = 11008
norm_eps = 1e-06
attn_bias = 0
start_id = 32013
end_id = 32014
session_len = 2048
weight_type = bf16
rotary_embedding = 128
rope_theta = 100000.0
size_per_head = 128
group_size = 0
max_batch_size = 128
max_context_token_num = 1
step_length = 1
cache_max_entry_count = 0.8
cache_block_seq_len = 128
cache_chunk_size = -1
num_tokens_per_iter = 8192
max_prefill_iters = 1
extra_tokens_per_iter = 0
use_context_fmha = 1
quant_policy = 0
max_position_embeddings = 8192
rope_scaling_factor = 0.0
use_logn_attn = 0
__pydantic_initialised__ = True


[TM][WARNING] [LlamaTritonModel] `max_context_token_num` = 2048.
2024-04-07 16:03:16,104 - lmdeploy - INFO - updated backend_config=TurbomindEngineConfig(model_name=None, model_format=None, tp=1, session_len=2048, max_batch_size=128, cache_max_entry_count=0.8, quant_policy=0, rope_scaling_factor=0.0, use_logn_attn=False, download_dir=None, revision=None, max_prefill_token_num=8192)
[WARNING] gemm_config.in is not found; using default GEMM algo
[TM][INFO] NCCL group_id = 0
[TM][INFO] [BlockManager] block_size = 64 MB
[TM][INFO] [BlockManager] max_block_count = 136
[TM][INFO] [BlockManager] chunk_size = 136
[TM][INFO] LlamaBatch<T>::Start()
server is gonna mount on: http://0.0.0.0:6006
Running on local URL:  http://0.0.0.0:6006
```

![image](https://github.com/InternLM/lmdeploy/assets/56081290/c74892c8-8b66-417a-9c19-827a18b2b862)
![image](https://github.com/InternLM/lmdeploy/assets/56081290/e89e334b-457f-4d15-8a67-a7b1d9d24be8)

**Comment by AllentDan** [comment]
Do we support the linear rope scaling model? @lvhan028 
https://huggingface.co/deepseek-ai/deepseek-coder-6.7b-base/blob/main/config.json#L18

**Comment by lvhan028** [comment]
yes

**Comment by AllentDan** [comment]
@ycclnn Please set the capability `completion` for chat template JSON file

**Comment by ycclnn** [comment]
Still no luck.
![image](https://github.com/InternLM/lmdeploy/assets/56081290/c90fd798-1cb1-4d41-98c0-63d09fa9ce8b)
``` sh
lmdeploy chat turbomind ./workspace --tp 1  --cap completion --chat-template deepseek-lmdeploy-template.json
2024-04-07 17:55:52,442 - lmdeploy - WARNING - model_source: workspace
2024-04-07 17:55:52,442 - lmdeploy - WARNING - loading from workspace, ignore args ['cache_max_entry_count', 'tp'] please use TurbomindEngineConfig or modify config.ini
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
2024-04-07 17:55:52,520 - lmdeploy - WARNING - model_config:

[llama]
model_name = deepseek_base
tensor_para_size = 1
head_num = 32
kv_head_num = 32
vocab_size = 32256
num_layer = 32
inter_size = 11008
norm_eps = 1e-06
attn_bias = 0
start_id = 32013
end_id = 32014
session_len = 2056
weight_type = bf16
rotary_embedding = 128
rope_theta = 100000.0
size_per_head = 128
group_size = 0
max_batch_size = 64
max_context_token_num = 1
step_length = 1
cache_max_entry_count = 0.8
cache_block_seq_len = 128
cache_chunk_size = -1
num_tokens_per_iter = 0
max_prefill_iters = 1
extra_tokens_per_iter = 0
use_context_fmha = 1
quant_policy = 0
max_position_embeddings = 8192
rope_scaling_factor = 0.0
use_logn_attn = 0
__pydantic_initialised__ = True


[WARNING] gemm_config.in is not found; using default GEMM algo
session 1

double enter to end input >>> <｜fim▁begin｜>def fib(n):\n    <｜fim▁hole｜>\n        return fib(n - 1) + fib(n - 2)<｜fim▁end｜> 

<｜fim▁begin｜>def fib(n):\n    <｜fim▁hole｜>\n        return fib(n - 1) + fib(n - 2)<｜fim▁end｜> 2024-04-07 17:56:13,918 - lmdeploy - WARNING - kwargs ignore_eos is deprecated for inference, use GenerationConfig instead.
2024-04-07 17:56:13,918 - lmdeploy - WARNING - kwargs random_seed is deprecated for inference, use GenerationConfig instead.
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
```

**Comment by ycclnn** [comment]
> Still no luck. ![image](https://private-user-images.githubusercontent.com/56081290/320272401-c90fd798-1cb1-4d41-98c0-63d09fa9ce8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODQxMjksIm5iZiI6MTcxMjQ4MzgyOSwicGF0aCI6Ii81NjA4MTI5MC8zMjAyNzI0MDEtYzkwZmQ3OTgtMWNiMS00ZDQxLTk4YzAtNjNkMDlmYTljZThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA5NTcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5MWUyNGRmNjYyNTYzOWQzZGUyOGQ5OGUyZWMxMjViNmUyYTQ5NTM3ZDc1Y2ZiNjg2ZDY2ZDUxNDAxZjkwYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3ykIw7N5Fnte97vFD6LvSVqzwvjvOWvKLcruWqMKon4)
> 
> ```shell
> lmdeploy chat turbomind ./workspace --tp 1  --cap completion --chat-template deepseek-lmdeploy-template.json
> 2024-04-07 17:55:52,442 - lmdeploy - WARNING - model_source: workspace
> 2024-04-07 17:55:52,442 - lmdeploy - WARNING - loading from workspace, ignore args ['cache_max_entry_count', 'tp'] please use TurbomindEngineConfig or modify config.ini
> Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
> 2024-04-07 17:55:52,520 - lmdeploy - WARNING - model_config:
> 
> [llama]
> model_name = deepseek_base
> tensor_para_size = 1
> head_num = 32
> kv_head_num = 32
> vocab_size = 32256
> num_layer = 32
> inter_size = 11008
> norm_eps = 1e-06
> attn_bias = 0
> start_id = 32013
> end_id = 32014
> session_len = 2056
> weight_type = bf16
> rotary_embedding = 128
> rope_theta = 100000.0
> size_per_head = 128
> group_size = 0
> max_batch_size = 64
> max_context_token_num = 1
> step_length = 1
> cache_max_entry_count = 0.8
> cache_block_seq_len = 128
> cache_chunk_size = -1
> num_tokens_per_iter = 0
> max_prefill_iters = 1
> extra_tokens_per_iter = 0
> use_context_fmha = 1
> quant_policy = 0
> max_position_embeddings = 8192
> rope_scaling_factor = 0.0
> use_logn_attn = 0
> __pydantic_initialised__ = True
> 
> 
> [WARNING] gemm_config.in is not found; using default GEMM algo
> session 1
> 
> double enter to end input >>> <｜fim▁begin｜>def fib(n):\n    <｜fim▁hole｜>\n        return fib(n - 1) + fib(n - 2)<｜fim▁end｜> 
> 
> <｜fim▁begin｜>def fib(n):\n    <｜fim▁hole｜>\n        return fib(n - 1) + fib(n - 2)<｜fim▁end｜> 2024-04-07 17:56:13,918 - lmdeploy - WARNING - kwargs ignore_eos is deprecated for inference, use GenerationConfig instead.
> 2024-04-07 17:56:13,918 - lmdeploy - WARNING - kwargs random_seed is deprecated for inference, use GenerationConfig instead.
> \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
> ```

Before deleting those empty kv pairs from json template, I tried to leave them empty string but the outcome didn't make any difference.

**Comment by AllentDan** [comment]
Please update lmdeploy to 0.3.0

**Comment by ycclnn** [comment]
> Please update lmdeploy to 0.3.0

Still not working for 0.3.0
``` sh
lmdeploy convert deepseek-coder /root/deepseek-coder-6.7b-base/ --tp 1 --tokenizer-path /root/deepseek-coder-6.7b-base/tokenizer.json
lmdeploy chat turbomind ./workspace --tp 1  --cap completion --chat-template deepseek-lmdeploy-template.json
```
![image](https://github.com/InternLM/lmdeploy/assets/56081290/19f3a2b4-ea16-4d45-889f-89ca3e1998e8)
![image](https://github.com/InternLM/lmdeploy/assets/56081290/9886d93c-5a39-42ce-87e8-f7695438bb8e)

**Comment by AllentDan** [comment]
Don't convert model. Using huggingface model directly. For example, `lmdeploy chat turbomind ~/data/deepseek-coder-6.7b-base --chat-template test.json`

**Comment by ycclnn** [comment]
> example

Thanks. But some responses look strange:
![image](https://github.com/InternLM/lmdeploy/assets/56081290/564f9b26-d8f8-4a5a-ad08-10ec14ff6285)
``` sh
lmdeploy serve gradio ./deepseek-coder-6.7b-base/ --chat-template deepseek-lmdeploy-template.json
```
``` sh
(lmdeploy) root@ubuntu:~/yzn# cat deepseek-lmdeploy-template.json
{
    "model_name": "deepseek-coder",
    "capability": "completion",
    "stop_words": ["<｜fim▁end｜>", "<|EOT|>", "<｜end▁of▁sentence｜>"]
}
```

**Comment by ycclnn** [comment]
> > example
> 
> Thanks. But some responses look strange: ![image](https://private-user-images.githubusercontent.com/56081290/320340075-564f9b26-d8f8-4a5a-ad08-10ec14ff6285.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NDQ4OTMsIm5iZiI6MTcxMjU0NDU5MywicGF0aCI6Ii81NjA4MTI5MC8zMjAzNDAwNzUtNTY0ZjliMjYtZDhmOC00YTVhLWFkMDgtMTBlYzE0ZmY2Mjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDAyNDk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMWQ3MjQ0YTQ5YjhlNDY1ODgxMWFiYzA5MjUwNjQ3MmJlYzU2N2ZlZTBjNDQ2Y2E0NTQzZTFmZTYwY2YwOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7oL24eo-KMqhOlMVNn9OzxpmS6uNWuBEo-kku4t-Zxw)
> 
> ```shell
> lmdeploy serve gradio ./deepseek-coder-6.7b-base/ --chat-template deepseek-lmdeploy-template.json
> ```
> 
> ```shell
> (lmdeploy) root@ubuntu:~/yzn# cat deepseek-lmdeploy-template.json
> {
>     "model_name": "deepseek-coder",
>     "capability": "completion",
>     "stop_words": ["<｜fim▁end｜>", "<|EOT|>", "<｜end▁of▁sentence｜>"]
> }
> ```

Is it a model thing or incorrect stop words?

**Comment by AllentDan** [comment]
This is a base model, which means you can only use it to do text completion.

**Comment by ycclnn** [comment]
> This is a base model, which means you can only use it to do text completion.

Im referering to this code completion example and feel like it's similar to codellama infilling mode: https://huggingface.co/deepseek-ai/deepseek-coder-6.7b-base#2%EF%BC%89code-insertion

**Comment by AllentDan** [comment]
> > This is a base model, which means you can only use it to do text completion.
> 
> Im referering to this code completion example and feel like it's similar to codellama infilling mode: https://huggingface.co/deepseek-ai/deepseek-coder-6.7b-base#2%EF%BC%89code-insertion

Yeah, you can do the infilling tasks too, but multi-turn conversations through gradio is not appropriate.

**Comment by ycclnn** [comment]
> > > This is a base model, which means you can only use it to do text completion.
> > 
> > 
> > Im referering to this code completion example and feel like it's similar to codellama infilling mode: https://huggingface.co/deepseek-ai/deepseek-coder-6.7b-base#2%EF%BC%89code-insertion
> 
> Yeah, you can do the infilling tasks too, but multi-turn conversations through gradio is not appropriate.

I get what you saying, but lmdeploy chat has the same problem. Every third response looks very weird:
![image](https://github.com/InternLM/lmdeploy/assets/56081290/15cea7d4-69b2-46c3-9467-564b895d5718)

**Comment by AllentDan** [comment]
> > > > This is a base model, which means you can only use it to do text completion.
> > > 
> > > 
> > > Im referering to this code completion example and feel like it's similar to codellama infilling mode: https://huggingface.co/deepseek-ai/deepseek-coder-6.7b-base#2%EF%BC%89code-insertion
> > 
> > 
> > Yeah, you can do the infilling tasks too, but multi-turn conversations through gradio is not appropriate.
> 
> I get what you saying, but lmdeploy chat has the same problem. Every third response looks very weird: ![image](https://private-user-images.githubusercontent.com/56081290/320343440-15cea7d4-69b2-46c3-9467-564b895d5718.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NDYxNjQsIm5iZiI6MTcxMjU0NTg2NCwicGF0aCI6Ii81NjA4MTI5MC8zMjAzNDM0NDAtMTVjZWE3ZDQtNjliMi00NmMzLTk0NjctNTY0Yjg5NWQ1NzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDAzMTEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2Y2ZkZjNmYWZhZDdhOGI3YmE5NWYyZTM1MTRhODJlNjFiOGUyMTRlMWM2OWVlNTZlOTZmMzM1ZmM2Yzg4NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z0OTEtbA9BqypCdBYx_Rym65kRMD-Ra55EzajMMFOZU)

Let's say, you have to end the session every time you want to input another question for `lmdeploy chat`. Or yes, you can use api_server to do text completion as well.

**Comment by ycclnn** [comment]
I see. Migrating from other frameworks like fastllm which made me confused and did the wrong assumption. There should be chat history being involved... 

Thanks a lot for your reply.
