### ISSUE TITLE
[Feature] 支持DocOwl1.5 

### ISSUE THREAD

**Issue by windar427** [InternLM/lmdeploy#1404]
### Motivation

这个月是否支持DocOwl1.5 多模态模型

### Related resources

https://github.com/X-PLUG/mPLUG-DocOwl/tree/main/DocOwl1.5

**Comment by lvhan028** [comment]
@AllentDan please investigate this model and check if lmdeploy can support it

**Comment by AllentDan** [comment]
Seems it hacked llama implementation like [this](https://github.com/X-PLUG/mPLUG-DocOwl/blob/e2e17dce767a9de25f9965928fc31e54afce66a6/DocOwl1.5/mplug_docowl/model/modeling_llama2.py#L66). Turbomind has to change the implementation as well to adapt it.

**Comment by windar427** [comment]
> Seems it hacked llama implementation like [this](https://github.com/X-PLUG/mPLUG-DocOwl/blob/e2e17dce767a9de25f9965928fc31e54afce66a6/DocOwl1.5/mplug_docowl/model/modeling_llama2.py#L66). Turbomind has to change the implementation as well to adapt it.

Is it convenient to adapt?

**Comment by lvhan028** [comment]
Unfortunately, it is not easy to support a non-llama model in turbomind engine now. 
I think we can come back to this feature after we refactor the enigne
