### ISSUE TITLE
[Feature]请问支持qwen-vl-int4的kv-cache量化么？ 

### ISSUE THREAD

**Issue by LianghuiGuo** [InternLM/lmdeploy#1413]
### Motivation

因为qwen-vl-int4已经做了Int4，不知道是否还有做kv-cache的必要呢？有可能进一步加速推理么？

**Comment by lvhan028** [comment]
#1377 在支持 8bit/4bit kv cache
我们还在评估模型的精度和速度 #1412

**Comment by LianghuiGuo** [comment]
> #1377 在支持 8bit/4bit kv cache 我们还在评估模型的精度和速度 #1412 stay tuned

好的，感谢~
