### ISSUE TITLE
[Feature] prefix-cache

### ISSUE THREAD

**Issue by Vincent131499** [InternLM/lmdeploy#1431]
### Motivation

在启动restful server之后，有几个疑惑：
1.对于相同的前缀，是不是不会重新在从头计算了，他会默认存储相同前缀的kv-cahce；
2.在请求的时候，是不是不需要指定session_id参数，他会直接从存储的kv-cache里面自己去匹配相同的前缀？

**Comment by lvhan028** [comment]
prefix-cache 这个特性还没有加。
可以看 #1407 的讨论

**Comment by Vincent131499** [comment]
我记得最初lmdeploy有个多轮对话的特性，可以缓存cache，现在在restful server里面没有了吗？我看对应的请求参数里面有个session_id

**Comment by lvhan028** [comment]
这个一直有。lmdeploy称之为交互式推理，或者有状态推理。
对应的RESTful API 是 "v1/chat/interactive"

**Comment by Vincent131499** [comment]
这个接口针对多轮对话是不需要重新计算是吧？逻辑和原来一样？

**Comment by lvhan028** [comment]
是的。不用重算。逻辑未变

**Comment by Vincent131499** [comment]
OK 
等待更高级的prefix cache发版！

**Comment by zhyncs** [comment]
> OK 等待更高级的prefix cache发版！

Hi. As mentioned in https://github.com/InternLM/lmdeploy/issues/1407, LMDeploy will support Automatic Prefix Cache. The current PyTorch engine already supports it at https://github.com/InternLM/lmdeploy/pull/1429. Performance benchmark and evaluation are still needed. The support on TurboMind is currently being developed by @ispobock and is expected to be landed around May. Stay tuned.

**Comment by Vincent131499** [comment]
@zhyncs @lvhan028  这个Automatic Prefix Cache的feature，请问五月份会发版吗

**Comment by Vincent131499** [comment]
好的，期待ing

**Comment by zhyncs** [comment]
> @zhyncs @lvhan028 这个Automatic Prefix Cache的feature，请问五月份会发版吗

Hi @Vincent131499 This is the current implementation of TurboMind https://github.com/InternLM/lmdeploy/pull/1450  which meets our internal needs. If you need it, you can [compile from the source code](https://github.com/ispobock/lmdeploy/tree/turbomind_prefix_caching). Currently, we have different opinions on the design of this PR and need to unify them.

**Comment by Vincent131499** [comment]
这个服务启动和客户端请求还需要配置什么参数吗，openai服务默认是开始prefix cache？

**Comment by Vincent131499** [comment]
@zhyncs 这个版本，服务启动和客户端请求还需要配置什么参数吗，openai服务默认是开始prefix cache？

**Comment by ispobock** [comment]
@Vincent131499 客户端不需要操作，服务端可以参考以下命令开启：
```
lmdeploy serve api_server /workdir/llama2_13b_chat --model-name llama2 --server-name 0.0.0.0 --server-port 23333 --tp 1 --enable-prefix-caching
```
加上`--enable-prefix-caching`参数

**Comment by Vincent131499** [comment]
@ispobock 我启动openai服务之后，使用相同的curl去请求，多轮对话时间并没有改善，而且日志里面打印的history_tokens一直是0；
请问这个啥时候发个正式版啊，公司业务上急需！

**Comment by ispobock** [comment]
@Vincent131499 你是用什么API去请求的？可以贴下请求的命令

**Comment by Vincent131499** [comment]
@ispobock 服务启动命令：lmdeploy serve api_server ../pretrained-models/qwen1.5-14b-chat/ --backend turbomind --model-format hf --tp 2 --log-level INFO --model-name qwen --enable-prefix-caching
看日志应该是启用了prefix-cache
![image](https://github.com/InternLM/lmdeploy/assets/26675984/116e5add-79ea-4677-869d-0ae8ac9faba3)

客户端请求：
curl http://0.0.0.0:23333/v1/chat/completions -H "Content-Type: application/json" -d '{
"model": "qwen", 
"stream": false, 
"top_p": 0.95, "top_k": 40, "temperature": 0.2,
"messages": [
{"role": "user", "content": "你叫什么名字"}
]}'

是我请求api的方式不对吗

**Comment by ispobock** [comment]
@Vincent131499 你的message太短了，cache reuse是block粒度的，目前block大小是64个token，你试试长一点的prompt

**Comment by lvhan028** [comment]
> @ispobock 我启动openai服务之后，使用相同的curl去请求，多轮对话时间并没有改善，而且日志里面打印的history_tokens一直是0； 请问这个啥时候发个正式版啊，公司业务上急需！

按计划会在月底发版。我请组内同事推进下review（大家最新在忙着开发，review的进度比较慢）。合入到main分支后，可以自己源码编译

**Comment by Vincent131499** [comment]
@lvhan028 也麻烦合到main后，给个文档操作解释下这个prefix-cache啊

**Comment by zhyncs** [comment]
> @lvhan028 也麻烦合到main后，给个文档操作解释下这个prefix-cache啊

@ispobock may follow up

**Comment by zhyncs** [comment]
ref https://github.com/InternLM/lmdeploy/pull/1597
