### ISSUE TITLE
[Feature] 是否支持InternLM-XComposer2-4KHD-7B的部署

### ISSUE THREAD

**Issue by windar427** [InternLM/lmdeploy#1432]
### Motivation

想问下有InternLM-XComposer2-4KHD-7B部署的计划吗？

**Comment by irexyc** [comment]
好像不同的地方只有视觉部分，会和XComposer2 一起支持。

**Comment by windar427** [comment]
感谢

**Comment by lvhan028** [comment]
It is supported in PR #1458 and will be released in v0.4.0
May give it a try.
