### ISSUE TITLE
Quantilized model speed is much slower than fp16.

### ISSUE THREAD

**Issue by douyh** [InternLM/lmdeploy#1435]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

I run `internlm2-caht-20b-4bits` on 2x4090 gpus
```
lmdeploy serve api_server $model_dir --backend turbomind --model-format awq --server-name 10.64.134.63 --server-port 9000 --session-len 8192 --tp 2
```
and run `interlm-chat-20b` on the same machine.
```
lmdeploy serve api_server $model_dir --backend turbomind --server-name 10.64.134.63 --server-port 8080 --tp 2
```

I've got a very long system prompt(1000+token). And `internlm2-caht-20b-4bits` is much slower than  `interlm-chat-20b` .

What can I do to speed up my model?

### Reproduction

see above

### Environment

```Shell
pytorch 2.1.2 + cuda12.1
```

**Comment by lvhan028** [comment]
like how slower?
Can you use `benchmark/profile_generation.py` to check it?

**Comment by douyh** [comment]
> like how slower? Can you use `benchmark/profile_generation.py` to check it?

I solved the problem by adding "<|im_end|>" to `stop`.

After I did this, 4bits model is really fast.


**But**, I add more strings to `stop`, the model will continue to generate words, though the stop string has been generated.

For example:

```
stop=["<|im_end|>", "<result>"]
```

The `<result>` is a special string for my output string. I want to stop at the special char but it did not work. What should I do?

**Comment by lvhan028** [comment]
Is the string "<result>"  encoded a single token_id?

**Comment by douyh** [comment]
> Currently, LMDeploy can only accept the `stop_words` that can be tokenized into one token.
> 
> ```python
> from transformers import AutoTokenizer
> 
> model_path = 'internlm/internlm2-caht-20b-4bits '
> tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
> 
> token_ids = tokenizer('<result>', return_tensors='pt', add_special_tokens=False)['input_ids']
> print(token_ids)
> ```
> 
> The result is `tensor([[ 333, 1528, 330]])`, meaning `<result>` is tokenized into three tokens. LMDeploy cannot handle this case right now.
> 
> On one hand, you can use other words instead. `result` is supposed to work well. On the other hand, you can add `<result>` to special tokens and retrain the LLM. But I don't know much about training. If you are interested, you may open an issue in [xtuner](https://github.com/InternLM/xtuner)

Thanks for your reply. That's very useful for me.
