### ISSUE TITLE
[Feature] API中VL模型支持interactive mode

### ISSUE THREAD

**Issue by sshuair** [InternLM/lmdeploy#1439]
### Motivation

目前VL模型的API不支持interactive mode，而实际情况中也会像LLM模型一样有多轮对话的需求

**Comment by AllentDan** [comment]
@sshuair 老哥愿意支持个 PR 不 :smile:

**Comment by sshuair** [comment]
> @sshuair 老哥愿意支持个 PR 不 😄

刚接触语言模型，还在学习阶段，如果能赶上，我提一个

**Comment by lvhan028** [comment]
PR #1444 has supported this feature, which will be released in v0.4.0
