### ISSUE TITLE
[Bug]多卡启动一个进程会报0卡内存不足 

### ISSUE THREAD

**Issue by userandpass** [InternLM/lmdeploy#1442]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 172.00 MiB. GPU 0 has a total capacty of 15.57 GiB of which 127.38 MiB is free. Including non-PyTorch memory, this process has 15.45 GiB memory in use. Of the allocated memory 15.33 GiB is allocated by PyTorch, and 711.50 KiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### Reproduction

CUDA_VISIBLE_DEVICES='0,1,2' lmdeploy serve api_server ../Qwen1___5-7B-Chat --server-name 0.0.0.0 --server-port 8011  --tp 1

### Environment

```Shell
T4 8*16G，lmdeploy0.2.6(安装0.3.0版本运行报错：argparse.ArgumentError: argument command: conflicting subparser: chat，因此降了版本)
```

**Comment by RunningLeon** [comment]
@userandpass hi，7B models with fp16 needs at least 14G GPU mem to load and need extra mem for KV cache. You may need to use tp>1

**Comment by userandpass** [comment]
> @userandpass hi，7B models with fp16 needs at least 14G GPU mem to load and need extra mem for KV cache. You may need to use tp>1

CUDA_VISIBLE_DEVICES='0,1,3,4' lmdeploy serve api_server ../Qwen1___5-7B-Chat --server-name 0.0.0.0 --server-port 8011  --tp 4
Think you，I used the default qwen configuration of 'torch_dtype: bfloat16', it said that this type is not supported, only float32 will do, but it needs to use 4 cards to not report out of memory, I executed the command will prompt：
2024-04-17 13:50:46,043 - lmdeploy - ERROR - Init tp model failed with error: [RuntimeError('Trying to create tensor with negative dimension -28: [-28, 64, 8, 128]'), RuntimeError('Trying to create tensor with negative dimension -28: [-28, 64, 8, 128]'), RuntimeError('Trying to create tensor with negative dimension -28: [-28, 64, 8, 128]'), RuntimeError('Trying to create tensor with negative dimension -28: [-28, 64, 8, 128]')]
qwen config.json:
`{
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 32768,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "rms_norm_eps": 1e-06,
  "rope_theta": 1000000.0,
  "sliding_window": 32768,
  "tie_word_embeddings": false,
  "torch_dtype": "float32",
  "transformers_version": "4.37.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}
`

**Comment by RunningLeon** [comment]
hi, 
1. T4 does not support bf16, you can change to fp16 in config.json `torch_dtype: 'float16'`
2. Can you install the latest from main branch or can you try with python<=3.10 on v0.3.0. Could reproduce your issue and it works well with tp=4 on 4 a100 with Qwen1.5-7B-Chat on my machine on main or v0.2.6

**Comment by userandpass** [comment]
> hi,
> 
> 1. T4 does not support bf16, you can change to fp16 in config.json `torch_dtype: 'float16'`
> 2. Can you install the latest from main branch or can you try with python<=3.10 on v0.3.0. Could reproduce your issue and it works well with tp=4 on 4 a100 with Qwen1.5-7B-Chat on my machine on main or v0.2.6

I changed to fp16, it can run on 2 cards, thank you.
