### ISSUE TITLE
[Bug] Build lmdeploy error

### ISSUE THREAD

**Issue by jjjjohnson** [InternLM/lmdeploy#1443]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

I am trying to build lmdeploy v0.1.0 from source but failied.
<img width="1054" alt="image" src="https://github.com/InternLM/lmdeploy/assets/20569095/c1f6323c-4f84-46e3-bf86-83f36e0250de">

Any help is appreciated!

### Reproduction

mkdir -p build && cd build &&\
    cmake .. \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
        -DCMAKE_INSTALL_PREFIX=/opt/tritonserver \
        -DBUILD_PY_FFI=ON \
        -DBUILD_MULTI_GPU=ON \
        -DBUILD_CUTLASS_MOE=OFF \
        -DBUILD_CUTLASS_MIXED_GEMM=OFF \
        -DCMAKE_CUDA_FLAGS="-lineinfo" \
        -DUSE_NVTX=OFF &&\
    make -j$(nproc)

### Environment

```Shell
openmmlab/lmdeploy:v0.1.0
```

**Comment by lvhan028** [comment]
Are you trying to build the latest lmdeploy in docker container openmmlab/lmdeploy:v0.1.0?

**Comment by jjjjohnson** [comment]
No. I am trying to build lmdeploy v0.1.0 from source

**Comment by lvhan028** [comment]
I checked it with `openmmlab/lmdeploy:v0.1.0`. The compilation works well. Here are the steps:
```
# 1. launch a docker container
docker run --gpus all --rm -it openmmlab/lmdeploy:v0.1.0 /bin/bash

# 2. build
cd /opt/lmdeploy
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo     -DCMAKE_EXPORT_COMPILE_COMMANDS=1     -DCMAKE_INSTALL_PREFIX=./install     -DBUILD_PY_FFI=ON     -DBUILD_MULTI_GPU=ON     -DCMAKE_CUDA_FLAGS="-lineinfo"     -DUSE_NVTX=ON
make -j$(nproc) && make install
```

**Comment by jjjjohnson** [comment]
@lvhan028 Thanks I will check my hardware.
