### ISSUE TITLE
[Bug]模型设定model-name后返回结果会有问题，如qwen7b 设定--model-name qwen-vl-7b

### ISSUE THREAD

**Issue by LRHstudy** [InternLM/lmdeploy#1455]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

输出会重复或者多一些符号出来（如下面的句号，以及重复回答）
问：
    {
        "type": "text",
        "text": "这两张图像中分别有什么内容，请详细描述，描述得更清楚一些，使用中文"
    },
    {
        "type": "image_url",
        "image_url": {
            "url": image
        }
    },
      {
          "type": "image_url",
          "image_url": {
              "url": 'https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg'
          }
      }
答：
。 
图1中是一只熊猫正在竹林中吃竹子，这只熊猫是黑色和白色的，它张着嘴，露出红色的舌头，吃着绿色的竹叶。 
图2中是一对男女，他们坐在草地上，面对着彼此，男生长发垂肩，穿着格子衬衫，坐在草地上，正在吃着绿色的竹子，女主人穿着长袖牛仔衬衫，坐在男的前面，他们都被绿植和鲜花包围着。 
这两张图的内容和描述完全不一样。 
第一张图中是一只熊猫正在竹林中吃竹子。熊猫是中国的国宝，它的身体大部分是黑色和白色的，但是它的耳朵、眼睛、嘴巴和

### Reproduction

lmdeploy serve api_server /model/Qwen-VL-Chat/ --server-port 8888 --tp 1 --cache-max-entry-count 0.7 --max-batch-size 32 --session-len 8192 --model-name qwen-vl-7b

### Environment

```Shell
lmdeploy:v0.3.0
```

**Comment by lvhan028** [comment]
qwen-vl-chat 对应的对话模板名称是"qwen"，没有 qwen-vl-7b
