### ISSUE TITLE
Llama 3 support

### ISSUE THREAD

**Issue by zhyncs** [InternLM/lmdeploy#1459]
### Motivation

as titled https://ai.meta.com/blog/meta-llama-3/

**Comment by zhyncs** [comment]
ref https://github.com/meta-llama/llama3

**Comment by zhyncs** [comment]
The Llama 2 -> Llama 3 architecture is virtually identical. Currently, both Turbomind and PyTorch support GQA. Just download the model and validate it.

**Comment by zhyncs** [comment]
I've tested with
```
python3 -m lmdeploy serve api_server --model-name llama2 /workdir/Meta-Llama-3-8B
```
And it works well.
I'll send a pr asap to update `llama3` for doc and conf. @lvhan028 @lzhangzz @grimoire

**Comment by zhyncs** [comment]
benchmark result
```bash
python3 benchmark/profile_restful_api.py 0.0.0.0:23333 /workdir/Meta-Llama-3-8B /workdir/ShareGPT_V3_unfiltered_cleaned_split.json --concurrency 128 --num_prompts 1000
```

```
--------------------------------------------------
concurrency: 128
elapsed_time: 59.242s

number of prompt tokens: 216922
number of completion tokens: 208662
token throughput (completion token): 3522.187 token/s
token throughput (prompt + completion token): 7183.802 token/s
RPS (request per second): 16.880 req/s
RPM (request per minute): 1012.792 req/min
--------------------------------------------------
```

**Comment by zhyncs** [comment]
ref https://github.com/InternLM/lmdeploy/pull/1461

**Comment by zhyncs** [comment]
Hi @grimoire For PyTorch Engine, Llama3 requires transformers version 4.40.0.dev0. We should update this
https://github.com/InternLM/lmdeploy/blob/e8a0c9aa1898ac7afd12d4eb54500c04684b69b5/requirements/runtime.txt#L15

**Comment by grimoire** [comment]
Sure, We plan to loosen the requirement of transformers and warning instead. https://github.com/InternLM/lmdeploy/pull/1453/files

**Comment by zhyncs** [comment]
> Sure, We plan to loosen the requirement of transformers and warning instead. https://github.com/InternLM/lmdeploy/pull/1453/files

ok

**Comment by lzhangzz** [comment]
These are my benchmark results

```
python3 ../benchmark/profile_throughput.py -c 128 -n 10000 --backend turbomind ShareGPT_V3_unfiltered_cleaned_split.json /shared_data/llama3/Meta-Llama-3-8B-Instruct --cache-max-entry-count 0.95

concurrency: 128
elapsed_time: 471.417s

first token latency(s)(min, max, ave): 0.037, 1.888, 0.157
per-token latency(s) percentile(50, 75, 95, 99): [0.019, 0.044, 0.085, 0.133]

number of prompt tokens: 2238364
number of completion tokens: 2005448
token throughput (completion token): 4254.087 token/s
token throughput (prompt + completion token): 9002.251 token/s
RPS (request per second): 21.213 req/s
RPM (request per minute): 1272.759 req/min



python3 ../benchmark/profile_throughput.py -c 128 -n 10000 --backend turbomind ShareGPT_V3_unfiltered_cleaned_split.json /shared_data/llama3/Meta-Llama-3-8B-Instruct --cache-max-entry-count 0.95 --num-tokens-per-iter 256 --max-prefill-iters 64

concurrency: 128
elapsed_time: 456.962s

first token latency(s)(min, max, ave): 0.035, 2.896, 0.495
per-token latency(s) percentile(50, 75, 95, 99): [0.022, 0.037, 0.062, 0.085]

number of prompt tokens: 2238364
number of completion tokens: 2005448
token throughput (completion token): 4388.652 token/s
token throughput (prompt + completion token): 9287.009 token/s
RPS (request per second): 21.884 req/s
RPM (request per minute): 1313.019 req/min



python3 ../benchmark/profile_throughput.py -c 256 -n 10000 --backend turbomind ShareGPT_V3_unfiltered_cleaned_split.json /shared_data/llama3/Meta-Llama-3-8B-Instruct --cache-max-entry-count 0.95 --num-tokens-per-iter 512 --max-prefill-iters 64

concurrency: 256
elapsed_time: 400.223s

first token latency(s)(min, max, ave): 0.078, 4.711, 0.737
per-token latency(s) percentile(50, 75, 95, 99): [0.03, 0.072, 0.137, 0.196]

number of prompt tokens: 2238364
number of completion tokens: 2005448
token throughput (completion token): 5010.823 token/s
token throughput (prompt + completion token): 10603.611 token/s
RPS (request per second): 24.986 req/s
RPM (request per minute): 1499.163 req/min
```

**Comment by zhyncs** [comment]
> These are my benchmark results
> 
> ```
> python3 ../benchmark/profile_throughput.py -c 128 -n 10000 --backend turbomind ShareGPT_V3_unfiltered_cleaned_split.json /shared_data/llama3/Meta-Llama-3-8B-Instruct --cache-max-entry-count 0.95
> 
> concurrency: 128
> elapsed_time: 471.417s
> 
> first token latency(s)(min, max, ave): 0.037, 1.888, 0.157
> per-token latency(s) percentile(50, 75, 95, 99): [0.019, 0.044, 0.085, 0.133]
> 
> number of prompt tokens: 2238364
> number of completion tokens: 2005448
> token throughput (completion token): 4254.087 token/s
> token throughput (prompt + completion token): 9002.251 token/s
> RPS (request per second): 21.213 req/s
> RPM (request per minute): 1272.759 req/min
> 
> 
> 
> python3 ../benchmark/profile_throughput.py -c 128 -n 10000 --backend turbomind ShareGPT_V3_unfiltered_cleaned_split.json /shared_data/llama3/Meta-Llama-3-8B-Instruct --cache-max-entry-count 0.95 --num-tokens-per-iter 256 --max-prefill-iters 64
> 
> concurrency: 128
> elapsed_time: 456.962s
> 
> first token latency(s)(min, max, ave): 0.035, 2.896, 0.495
> per-token latency(s) percentile(50, 75, 95, 99): [0.022, 0.037, 0.062, 0.085]
> 
> number of prompt tokens: 2238364
> number of completion tokens: 2005448
> token throughput (completion token): 4388.652 token/s
> token throughput (prompt + completion token): 9287.009 token/s
> RPS (request per second): 21.884 req/s
> RPM (request per minute): 1313.019 req/min
> 
> 
> 
> python3 ../benchmark/profile_throughput.py -c 256 -n 10000 --backend turbomind ShareGPT_V3_unfiltered_cleaned_split.json /shared_data/llama3/Meta-Llama-3-8B-Instruct --cache-max-entry-count 0.95 --num-tokens-per-iter 512 --max-prefill-iters 64
> 
> concurrency: 256
> elapsed_time: 400.223s
> 
> first token latency(s)(min, max, ave): 0.078, 4.711, 0.737
> per-token latency(s) percentile(50, 75, 95, 99): [0.03, 0.072, 0.137, 0.196]
> 
> number of prompt tokens: 2238364
> number of completion tokens: 2005448
> token throughput (completion token): 5010.823 token/s
> token throughput (prompt + completion token): 10603.611 token/s
> RPS (request per second): 24.986 req/s
> RPM (request per minute): 1499.163 req/min
> ```

Yes, GQA has significantly improved performance. Llama 3 8B Instruct is anticipated to become the new standard model for many domestic companies' SFT tasks.

**Comment by serser** [comment]
LLaMA-3-70B doesn't seem to fit into 48GB GPU memory after awq W4 quantization with turbomind. Have anyone encountered this problem?

**Comment by zhyncs** [comment]
Hi @serser You may try to set `--cache-max-entry-count 0.4` for the KV Cache size.

e.g.
total: 48G
weights: 70*2/4=35G
kv cache: (48-35)*0.4=5.2G
activation and other: 48-35-5.2=7.8G

**Comment by zhyncs** [comment]
I tested on A100 80G, no issues found. To simulate the case of 48G, I intentionally set `cache-max-entry-count` to `0.15`. It shows `48503MiB / 81251MiB`, since 48503/1024=47.4 < 48. I think it's ok for A100 48G.

```bash
# convert
python3 -m lmdeploy lite auto_awq /workdir/Meta-Llama-3-70B-Instruct --calib-dataset 'wikitext2' --calib-samples 128 --calib-seqlen 2048 --w-bits 4 --w-group-size 128 --work-dir /workdir/Meta-Llama-3-70B-Instruct-AWQ

# server
python3 -m lmdeploy serve api_server /workdir/Meta-Llama-3-70B-Instruct-AWQ --cache-max-entry-count 0.15

# client
python3 benchmark/profile_restful_api.py --server_addr 127.0.0.1:23333 --tokenizer_path /workdir/Meta-Llama-3-70B-Instruct --dataset /workdir/ShareGPT_V3_unfiltered_cleaned_split.json --concurrency 128 --num_prompts 1000
```

**Comment by zhyncs** [comment]
> Hi @serser You may try to set `--cache-max-entry-count 0.4` for the KV Cache size.
> 
> e.g. total: 48G weights: 70*2/4=35G kv cache: (48-35)*0.4=5.2G activation and other: 48-35-5.2=7.8G

@serser You may refer to https://github.com/InternLM/lmdeploy/pull/1067

**Comment by serser** [comment]
I am with L40 but only 46068MiB is shown (supposedly it would be 48GB). I've set  `cache_max_entry_count = 0.1` in `TurbomindEngineConfig` (btw, `triton_models/weights/config.ini` this configuration seems not passed to `TurbomindEngineConfig`) and the same error occurs.

```
2024-04-23 10:11:19,967 - lmdeploy - INFO - updated backend_config=TurbomindEngineConfig(model_name=None, model_format=None, tp=1, session_len=8192, max_batch_size=128, cache_max_entry_count=0.1, cache_block_seq_len=64, quant_policy=0, rope_scaling_factor=0.0, use_logn_attn=False, download_dir=None, revision=None, max_prefill_token_num=2048, num_tokens_per_iter=0, max_prefill_iters=1)
[TM][INFO] Set logger level by INFO
[WARNING] gemm_config.in is not found; using default GEMM algo
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mel/.local/lib/python3.9/site-packages/lmdeploy/turbomind/turbomind.py", line 444, in _create_model_instance
    model_inst = self.tm_model.model_comm.create_model_instance(
RuntimeError: [TM][ERROR] CUDA runtime error: out of memory /lmdeploy/src/turbomind/utils/allocator.h:231 
```
Interestingly, when I run AWQ W4 quantized Qwen-1.5-72b-chat with default `cache_max_entry_count = 0.8`, it is with no errors.
