### ISSUE TITLE
[Feature] TurboMind support Baichuan 13b and Baichuan2 13b

### ISSUE THREAD

**Issue by zhyncs** [InternLM/lmdeploy#1472]
### Motivation

https://github.com/InternLM/lmdeploy/blob/65ba649d571e8c6b8dad51b252c9c8c9211b5050/lmdeploy/turbomind/supported_models.py#L95-L97

Hi @lvhan028 @lzhangzz Currently TurboMind does not support Baichuan 13b and Baichuan2 13b. When is it expected to support? Thanks.

**Comment by lvhan028** [comment]
It is a low-priority task. We haven't made a clear schedule for it.

**Comment by zhyncs** [comment]
> It is a low-priority task. We haven't made a clear schedule for it.

ok

**Comment by zhyncs** [comment]
https://github.com/InternLM/lmdeploy/blob/65ba649d571e8c6b8dad51b252c9c8c9211b5050/lmdeploy/pytorch/supported_models.py#L97-L100

It shows that PyTorch Engine doesn't support Baichuan 13b either. Hi @grimoire  Do you have any plan to support it? Thanks.

**Comment by zhyncs** [comment]
https://github.com/InternLM/lmdeploy/blob/65ba649d571e8c6b8dad51b252c9c8c9211b5050/README.md?plain=1#L103-L104

Hi @lvhan028 Maybe we should update the README and remove 13B here. Because in the code, neither of the two engines supports Baichuan 13b.

**Comment by grimoire** [comment]
> Do you have any plan to support it?

No plans for now.

**Comment by zhyncs** [comment]
> No plans for now.

Actually, neither of the two engines supports Baichuan 13B, but it is indicated in the documentation that they do. In order to avoid misleading users, I have already updated the README. https://github.com/InternLM/lmdeploy/pull/1485
