### ISSUE TITLE
RelayAttention discussion

### ISSUE THREAD

**Issue by zhyncs** [InternLM/lmdeploy#1477]
### Motivation

paper: https://arxiv.org/pdf/2402.14808.pdf

code: https://github.com/rayleizhu/vllm-ra

Hi @lvhan028 @lzhangzz 

SenseTime proposed RelayAttention, looking at the comparative data, in some scenarios, it has certain advantages compared to PagedAttention. This issue is not for discussing support for this feature but to discuss whether there is any reference value. Thanks.

**Comment by lvhan028** [comment]
Thank you so much for sharing.
We'll get back to you after internal discussion

**Comment by zhyncs** [comment]
It has made too many assumptions and restrictions, which are overly limiting and not very useful in real-world scenarios.
