### ISSUE TITLE
[Docs] 请问当前lmdeploy支持大模型的工具调用能力吗？

### ISSUE THREAD

**Issue by qiuxuezhe123** [InternLM/lmdeploy#1481]
### 📚 The doc issue

请问当前lmdeploy支持大模型的工具调用能力吗？

**Comment by lvhan028** [comment]
我们没打算做这个功能。还是想让 lmdeploy 更存粹一些，专注在推理上。
你可以看看 [lagent](https://github.com/InternLM/lagent) 项目能不能满足你对 function call 功能的需求
