### ISSUE TITLE
[Feature] 多模态模型量化示例

### ISSUE THREAD

**Issue by douyh** [InternLM/lmdeploy#1483]
### Motivation

VLM量化相关的文档还不是很完善

### Related resources

在这里有找到一些关于LLM量化的文档：https://github.com/InternLM/lmdeploy/blob/main/docs/en/quantization/w4a16.md

想请教一下如果需要量化VLM，应该怎么做，我看到支持的模型列表中有InternVL，比如这样的模型量化应该注意一些什么，是否可以补充一些示例。

非常感谢！

**Comment by AllentDan** [comment]
最新的 LMDeploy 已经支持 InternVL 量化推理，可以尝试更新。
