### ISSUE TITLE
[Bug] DeprecationWarning: concurrency_count has been deprecated. Set the concurrency_limit directly on event listeners e.g. btn.click(fn, ..., concurrency_limit=10) or gr.Interface(concurrency_limit=10). If necessary, the total number of workers can be configured via `max_threads` in launch().

### ISSUE THREAD

**Issue by liuxiao916** [InternLM/lmdeploy#1484]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

<img width="955" alt="image" src="https://github.com/InternLM/lmdeploy/assets/45966993/ce6565c1-1638-4f79-a3e1-6da2b7c33b56">

### Reproduction

lmdeploy serve gradio http://localhost:23333 \
    --server-name 0.0.0.0 \
    --server-port 6006

### Environment

```Shell
gradio                    4.27.0 
gradio-client             0.15.1                  
lmdeploy                  0.4.0
```

**Comment by AllentDan** [comment]
Please try gradio<4.0.0
https://github.com/InternLM/lmdeploy/blob/main/requirements/serve.txt#L1

**Comment by liuxiao916** [comment]
Cool. Thank you.
