### ISSUE TITLE
Question about internrm-chat-7b-8k

### ISSUE THREAD

**Issue by happened** [InternLM/lmdeploy#149]
用tp=2 转换Internlm-chat-7b-8k模型 为turbomind格式，最终生成的weight/config.ini如下，8k不是最大支持8千多个token嘛？ 这个在哪里设置的，我现在调用超过2048就报错了
```ini

[llama]
model_name = internlm-chat-7b
head_num = 32
size_per_head = 128
vocab_size = 103168
num_layer = 32
rotary_embedding = 128
inter_size = 11008
norm_eps = 1e-06
attn_bias = 1
start_id = 1
end_id = 2
weight_type = fp16
max_batch_size = 32
max_context_token_num = 4
session_len = 2056
step_length = 1
cache_max_entry_count = 48
cache_chunk_size = 1
use_context_fmha = 1
quant_policy = 0
tensor_para_size = 2
```

**Comment by lzhangzz** [comment]
this line controls the max session length

```session_len = 2056```


setting it to a proper value according to model type is not implemented yet

**Comment by lvhan028** [comment]
PR #144 在处理这个问题

**Comment by chailt** [comment]
您好，想请教一个问题，我使用的是也是llama模型，当我把默认的 session_len = 2056  修改为 session_len = 4101之后，推理速度慢了大概10倍左右，请问这是什么原因

**Comment by lvhan028** [comment]
可以提供下你的测试方法吗？
