### ISSUE TITLE
[Bug] qwen1.5-32b-chat

### ISSUE THREAD

**Issue by Vincent131499** [InternLM/lmdeploy#1498]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

使用lmdeploy-0.4.0的docker镜像启动容器后，部署qwen1.5-32b-chat模型，在客户端请求异常。
服务部署命令：
lmdeploy serve api_server ../pretrained-models/qwen1.5-32b-chat --backend turbomind --model-format hf --tp 4 --log-level INFO --session-len 8192 --max-batch-size 8 --quant-policy 8 --cache-max-entry-count 0.1 --model-name qwen
客户端请求结果：
![image](https://github.com/InternLM/lmdeploy/assets/26675984/d55cc917-f961-432b-9624-45c4fb2e7dc5)

在服务启动过程中发现如下信息：
2024-04-25 11:01:10,373 - lmdeploy - WARNING - get 1923 model params
2024-04-25 11:01:32,752 - lmdeploy - WARNING - the model may not be loaded successfully with 300 uninitialized params:                                                                                          
['layers.30.attention.w_qkv.0.bias', 'layers.18.ffn_norm.weight', 'layers.26.attention_norm.weight', 'layers.19.feed_forward.w1.0.weight', 'layers.26.attention.wo.0.weight', 'layers.19.attention.wo.0.weight', 'layers.26.feed_forward.w2.0.weight', 'layers.26.feed_forward.w3.0.weight', 'layers.21.feed_forward.w3.0.weight', 'layers.20.attention.w_qkv.0.bias', 'layers.29.attention.wo.0.bias', 'layers.18.attention.w_qkv.0.weight', 'layers.29.feed_forward.w2.0.weight', 'layers.22.ffn_norm.weight', 'layers.21.attention.w_qkv.0.weight', 'layers.22.attention.w_qkv.0.bias', 'layers.21.attention_norm.weight', 'layers.18.attention.wo.0.weight', 'layers.28.feed_forward.w3.0.weight', 'layers.20.attention.wo.0.bias', 'layers.19.attention.wo.0.bias', 'layers.26.attention.wo.0.bias', 'layers.27.attention.wo.0.bias', 'layers.26.ffn_norm.weight', 'layers.27.attention.wo.0.weight', 'layers.18.attention_norm.weight', 'layers.27.feed_forward.w3.0.weight', 'layers.27.attention.w_qkv.0.weight', 'layers.19.attention.w_qkv.0.bias', 'layers.28.feed_forward.w1.0.weight', 'layers.20.feed_forward.w1.0.weight', 'layers.20.attention.wo.0.weight', 'layers.20.attention_norm.weight', 'layers.26.feed_forward.w1.0.weight', 'layers.22.attention_norm.weight', 'layers.18.attention.wo.0.bias', 'layers.28.attention.wo.0.weight', 'layers.19.feed_forward.w2.0.weight', 'layers.26.attention.w_qkv.0.weight', 'layers.19.attention.w_qkv.0.weight', 'layers.22.feed_forward.w1.0.weight', 'layers.22.feed_forward.w2.0.weight', 'layers.20.attention.w_qkv.0.weight', 'layers.18.feed_forward.w3.0.weight', 'layers.18.feed_forward.w2.0.weight', 'layers.20.feed_forward.w2.0.weight', 'layers.20.ffn_norm.weight', 'layers.30.feed_forward.w1.0.weight', 'layers.21.feed_forward.w1.0.weight', 'layers.21.attention.wo.0.bias', 'layers.28.attention_norm.weight', 'layers.29.attention.w_qkv.0.weight', 'layers.26.attention.w_qkv.0.bias', 'layers.19.feed_forward.w3.0.weight', 'layers.27.ffn_norm.weight', 'layers.28.attention.w_qkv.0.weight', 'layers.30.attention.wo.0.bias', 'layers.20.feed_forward.w3.0.weight', 'layers.27.feed_forward.w2.0.weight', 'layers.21.ffn_norm.weight', 'layers.30.feed_forward.w3.0.weight', 'layers.27.attention_norm.weight', 'layers.22.feed_forward.w3.0.weight', 'layers.19.ffn_norm.weight', 'layers.21.attention.wo.0.weight', 'layers.18.feed_forward.w1.0.weight', 'layers.27.attention.w_qkv.0.bias', 'layers.28.attention.wo.0.bias', 'layers.28.ffn_norm.weight', 'layers.28.attention.w_qkv.0.bias', 'layers.29.feed_forward.w1.0.weight', 'layers.29.attention.wo.0.weight', 'layers.29.attention.w_qkv.0.bias', 'layers.29.attention_norm.weight', 'layers.30.feed_forward.w2.0.weight', 'layers.30.attention.wo.0.weight', 'layers.21.feed_forward.w2.0.weight', 'layers.30.attention.w_qkv.0.weight', 'layers.30.ffn_norm.weight', 'layers.30.attention_norm.weight', 'layers.29.ffn_norm.weight', 'layers.21.attention.w_qkv.0.bias', 'layers.27.feed_forward.w1.0.weight', 'layers.18.attention.w_qkv.0.bias', 'layers.22.attention.w_qkv.0.weight', 'layers.22.attention.wo.0.weight', 'layers.19.attention_norm.weight', 'layers.28.feed_forward.w2.0.weight', 'layers.29.feed_forward.w3.0.weight', 'layers.22.attention.wo.0.bias', 'layers.27.attention.w_qkv.1.bias', 'layers.29.feed_forward.w3.1.weight', 'layers.30.feed_forward.w2.1.weight', 'layers.30.attention.wo.1.bias', 'layers.21.attention.wo.1.bias', 'layers.21.feed_forward.w3.1.weight', 'layers.19.attention.wo.1.bias', 'layers.21.attention.wo.1.weight', 'layers.22.feed_forward.w2.1.weight', 'layers.26.feed_forward.w2.1.weight', 'layers.29.feed_forward.w1.1.weight', 'layers.18.feed_forward.w2.1.weight', 'layers.21.attention.w_qkv.1.weight', 'layers.27.attention.w_qkv.1.weight', 'layers.26.feed_forward.w3.1.weight', 'layers.22.feed_forward.w1.1.weight', 'layers.26.feed_forward.w1.1.weight', 'layers.30.feed_forward.w3.1.weight', 'layers.18.attention.wo.1.weight', 'layers.18.attention.w_qkv.1.bias', 'layers.26.attention.w_qkv.1.weight', 'layers.22.attention.w_qkv.1.weight', 'layers.21.attention.w_qkv.1.bias', 'layers.27.feed_forward.w2.1.weight', 'layers.22.feed_forward.w3.1.weight', 'layers.26.attention.wo.1.bias', 'layers.28.attention.w_qkv.1.bias', 'layers.27.attention.wo.1.bias', 'layers.19.attention.w_qkv.1.bias', 'layers.18.attention.w_qkv.1.weight', 'layers.20.feed_forward.w1.1.weight', 'layers.18.feed_forward.w1.1.weight', 'layers.22.attention.w_qkv.1.bias', 'layers.19.feed_forward.w3.1.weight', 'layers.21.feed_forward.w2.1.weight', 'layers.29.attention.w_qkv.1.bias', 'layers.20.feed_forward.w2.1.weight', 'layers.20.attention.wo.1.bias', 'layers.19.feed_forward.w1.1.weight', 'layers.27.attention.wo.1.weight', 'layers.19.feed_forward.w2.1.weight', 'layers.19.attention.w_qkv.1.weight', 'layers.18.attention.wo.1.bias', 'layers.22.attention.wo.1.weight', 'layers.28.feed_forward.w1.1.weight', 'layers.27.feed_forward.w3.1.weight', 'layers.30.attention.wo.1.weight', 'layers.22.attention.wo.1.bias', 'layers.18.feed_forward.w3.1.weight', 'layers.20.attention.wo.1.weight', 'layers.28.feed_forward.w3.1.weight', 'layers.20.attention.w_qkv.1.weight', 'layers.26.attention.w_qkv.1.bias', 'layers.20.feed_forward.w3.1.weight', 'layers.26.attention.wo.1.weight', 'layers.28.feed_forward.w2.1.weight', 'layers.28.attention.wo.1.weight', 'layers.20.attention.w_qkv.1.bias', 'layers.28.attention.w_qkv.1.weight', 'layers.29.feed_forward.w2.1.weight', 'layers.29.attention.wo.1.weight', 'layers.29.attention.wo.1.bias', 'layers.29.attention.w_qkv.1.weight', 'layers.30.feed_forward.w1.1.weight', 'layers.27.feed_forward.w1.1.weight', 'layers.30.attention.w_qkv.1.weight', 'layers.21.feed_forward.w1.1.weight', 'layers.30.attention.w_qkv.1.bias', 'layers.19.attention.wo.1.weight', 'layers.28.attention.wo.1.bias', 'layers.30.attention.wo.2.weight', 'layers.28.attention.w_qkv.2.bias', 'layers.29.attention.w_qkv.2.bias', 'layers.22.attention.w_qkv.2.weight', 'layers.21.attention.w_qkv.2.weight', 'layers.20.feed_forward.w1.2.weight', 'layers.19.attention.w_qkv.2.bias', 'layers.28.feed_forward.w3.2.weight', 'layers.28.attention.wo.2.weight', 'layers.28.attention.wo.2.bias', 'layers.20.attention.wo.2.weight', 'layers.21.feed_forward.w3.2.weight', 'layers.18.attention.w_qkv.2.weight', 'layers.26.feed_forward.w2.2.weight', 'layers.21.attention.w_qkv.2.bias', 'layers.22.attention.wo.2.bias', 'layers.22.attention.wo.2.weight', 'layers.26.attention.w_qkv.2.weight', 'layers.29.attention.w_qkv.2.weight', 'layers.18.feed_forward.w2.2.weight', 'layers.18.feed_forward.w3.2.weight', 'layers.28.feed_forward.w2.2.weight', 'layers.26.attention.wo.2.bias', 'layers.27.feed_forward.w1.2.weight', 'layers.19.feed_forward.w3.2.weight', 'layers.26.feed_forward.w3.2.weight', 'layers.22.attention.w_qkv.2.bias', 'layers.27.attention.wo.2.weight', 'layers.22.feed_forward.w3.2.weight', 'layers.26.attention.w_qkv.2.bias', 'layers.21.feed_forward.w1.2.weight', 'layers.21.feed_forward.w2.2.weight', 'layers.27.attention.wo.2.bias', 'layers.19.attention.wo.2.bias', 'layers.22.feed_forward.w1.2.weight', 'layers.21.attention.wo.2.bias', 'layers.20.attention.w_qkv.2.bias', 'layers.19.feed_forward.w1.2.weight', 'layers.20.feed_forward.w3.2.weight', 'layers.18.feed_forward.w1.2.weight', 'layers.18.attention.w_qkv.2.bias', 'layers.27.feed_forward.w2.2.weight', 'layers.22.feed_forward.w2.2.weight', 'layers.20.attention.w_qkv.2.weight', 'layers.27.attention.w_qkv.2.bias', 'layers.30.attention.w_qkv.2.weight', 'layers.26.attention.wo.2.weight', 'layers.18.attention.wo.2.bias', 'layers.20.attention.wo.2.bias', 'layers.21.attention.wo.2.weight', 'layers.19.attention.w_qkv.2.weight', 'layers.29.attention.wo.2.bias', 'layers.18.attention.wo.2.weight', 'layers.19.feed_forward.w2.2.weight', 'layers.26.feed_forward.w1.2.weight', 'layers.20.feed_forward.w2.2.weight', 'layers.28.feed_forward.w1.2.weight', 'layers.30.feed_forward.w2.2.weight', 'layers.29.feed_forward.w3.2.weight', 'layers.29.feed_forward.w1.2.weight', 'layers.29.feed_forward.w2.2.weight', 'layers.29.attention.wo.2.weight', 'layers.30.feed_forward.w3.2.weight', 'layers.30.feed_forward.w1.2.weight', 'layers.30.attention.wo.2.bias', 'layers.27.feed_forward.w3.2.weight', 'layers.30.attention.w_qkv.2.bias', 'layers.19.attention.wo.2.weight', 'layers.28.attention.w_qkv.2.weight', 'layers.27.attention.w_qkv.2.weight', 'layers.20.attention.wo.3.bias', 'layers.27.attention.wo.3.weight', 'layers.28.feed_forward.w3.3.weight', 'layers.21.attention.w_qkv.3.bias', 'layers.21.attention.wo.3.bias', 'layers.18.attention.wo.3.weight', 'layers.22.feed_forward.w2.3.weight', 'layers.18.feed_forward.w1.3.weight', 'layers.27.attention.w_qkv.3.bias', 'layers.27.feed_forward.w2.3.weight', 'layers.18.attention.w_qkv.3.bias', 'layers.30.feed_forward.w2.3.weight', 'layers.22.feed_forward.w1.3.weight', 'layers.29.feed_forward.w3.3.weight', 'layers.21.attention.wo.3.weight', 'layers.19.attention.wo.3.weight', 'layers.21.feed_forward.w1.3.weight', 'layers.28.feed_forward.w2.3.weight', 'layers.22.feed_forward.w3.3.weight', 'layers.27.attention.w_qkv.3.weight', 'layers.26.feed_forward.w3.3.weight', 'layers.26.attention.wo.3.weight', 'layers.20.attention.wo.3.weight', 'layers.19.attention.w_qkv.3.bias', 'layers.26.attention.w_qkv.3.bias', 'layers.20.attention.w_qkv.3.bias', 'layers.27.attention.wo.3.bias', 'layers.26.attention.w_qkv.3.weight', 'layers.22.attention.wo.3.bias', 'layers.29.attention.w_qkv.3.bias', 'layers.30.attention.wo.3.weight', 'layers.20.feed_forward.w2.3.weight', 'layers.27.feed_forward.w1.3.weight', 'layers.19.feed_forward.w3.3.weight', 'layers.22.attention.wo.3.weight', 'layers.28.attention.wo.3.weight', 'layers.18.attention.w_qkv.3.weight', 'layers.22.attention.w_qkv.3.weight', 'layers.26.attention.wo.3.bias', 'layers.22.attention.w_qkv.3.bias', 'layers.26.feed_forward.w2.3.weight', 'layers.20.feed_forward.w3.3.weight', 'layers.19.attention.w_qkv.3.weight', 'layers.19.attention.wo.3.bias', 'layers.26.feed_forward.w1.3.weight', 'layers.27.feed_forward.w3.3.weight', 'layers.21.feed_forward.w3.3.weight', 'layers.21.attention.w_qkv.3.weight', 'layers.28.feed_forward.w1.3.weight', 'layers.28.attention.w_qkv.3.bias', 'layers.28.attention.w_qkv.3.weight', 'layers.29.feed_forward.w2.3.weight', 'layers.29.feed_forward.w1.3.weight', 'layers.29.attention.wo.3.weight', 'layers.29.attention.wo.3.bias', 'layers.29.attention.w_qkv.3.weight', 'layers.18.feed_forward.w3.3.weight', 'layers.30.feed_forward.w1.3.weight', 'layers.30.attention.w_qkv.3.weight', 'layers.30.attention.w_qkv.3.bias', 'layers.30.attention.wo.3.bias', 'layers.28.attention.wo.3.bias', 'layers.19.feed_forward.w2.3.weight', 'layers.30.feed_forward.w3.3.weight', 'layers.18.feed_forward.w2.3.weight', 'layers.18.attention.wo.3.bias', 'layers.20.attention.w_qkv.3.weight', 'layers.19.feed_forward.w1.3.weight', 'layers.20.feed_forward.w1.3.weight', 'layers.21.feed_forward.w2.3.weight']
2024-04-25 11:01:33,016 - lmdeploy - INFO - updated backend_config=TurbomindEngineConfig(model_name='qwen', model_format='hf', tp=4, session_len=8192, max_batch_size=8, cache_max_entry_count=0.1, cache_block_seq_len=64, quant_policy=8, rope_scaling_factor=0.0, use_logn_attn=False, download_dir=None, revision=None, max_prefill_token_num=8192, num_tokens_per_iter=0, max_prefill_iters=1)
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[WARNING] gemm_config.in is not found; using default GEMM algo

感谢是qwen1.5这个32b的模型没有完全适配，麻烦check下啊

### Reproduction

服务部署命令：
lmdeploy serve api_server ../pretrained-models/qwen1.5-32b-chat --backend turbomind --model-format hf --tp 4 --log-level INFO --session-len 8192 --max-batch-size 8 --quant-policy 8 --cache-max-entry-count 0.1 --model-name qwen

### Environment

```Shell
openmmlab/lmdeploy:v0.4.0
```

**Comment by lvhan028** [comment]
```
2024-04-25 11:01:32,752 - lmdeploy - WARNING - the model may not be loaded successfully with 300 uninitialized params:
```
从日志上看，有很多权重没有读到。模型是完整的么？

**Comment by lvhan028** [comment]
我下载模型复现下看看

**Comment by irexyc** [comment]
pretrained-models/qwen1.5-32b-chat 应该不是 [Qwen/Qwen1.5-32B-Chat](https://huggingface.co/Qwen/Qwen1.5-32B-Chat) 这个模型？因为我看这里面有64层。

server 在启动的时候(log_level=INFO)应该还会打印这种信息，麻烦也提供一下：

```
[llama]
model_name = internvl-internlm2
tensor_para_size = 1
head_num = 48
kv_head_num = 8
vocab_size = 92553
num_layer = 48
inter_size = 16384
...
```

另外可以分享一下 config.json 以及 权重的 index.json 这俩文件么？

**Comment by Vincent131499** [comment]
好的，我检查下模型

**Comment by Vincent131499** [comment]
@irexyc 
部署后打印的model config:
2024-04-25 11:01:07,289 - lmdeploy - WARNING - model_config:

[llama]
model_name = qwen
tensor_para_size = 4
head_num = 40
kv_head_num = 8
vocab_size = 152064
num_layer = 64
inter_size = 27392
norm_eps = 1e-06
attn_bias = 1
start_id = 151643
end_id = 151645
session_len = 8192
weight_type = bf16
rotary_embedding = 128
rope_theta = 1000000.0
size_per_head = 128
group_size = 0
max_batch_size = 8
max_context_token_num = 1
step_length = 1
cache_max_entry_count = 0.1
cache_block_seq_len = 64
cache_chunk_size = -1
num_tokens_per_iter = 8192
max_prefill_iters = 1
extra_tokens_per_iter = 0
use_context_fmha = 1
quant_policy = 8
max_position_embeddings = 32768
rope_scaling_factor = 0.0
use_dynamic_ntk = 0
use_logn_attn = 0
lora_policy = 
lora_r = 0
lora_scale = 0.0
lora_max_wo_r = 0
lora_rank_pattern = 
lora_scale_pattern = 


[TM][INFO] Set logger level by INFO
[TM][WARNING] [LlamaTritonModel] `max_context_token_num` = 8192.


config.json:
![image](https://github.com/InternLM/lmdeploy/assets/26675984/ccc6ad18-ba47-44f4-955c-2455bb555595)

model.safetensors.index.json:
与这个（https://hf-mirror.com/Qwen/Qwen1.5-32B-Chat/blob/main/model.safetensors.index.json）一致

**Comment by lvhan028** [comment]
没有复现。我这边正常
```
root@db4ef768b734:/opt/lmdeploy# CUDA_VISIBLE_DEVICES="0,1,2,3" lmdeploy serve api_server /workspace/models-bigdisk/Qwen1.5-32B-Chat/ --backend turbomind --model-format hf --tp 4 --quant-policy 8
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[WARNING] gemm_config.in is not found; using default GEMM algo                                                                                                                                                                                                                     
[WARNING] gemm_config.in is not found; using default GEMM algo
[WARNING] gemm_config.in is not found; using default GEMM algo
[WARNING] gemm_config.in is not found; using default GEMM algo
HINT:    Please open http://0.0.0.0:23333 in a browser for detailed api usage!!!
HINT:    Please open http://0.0.0.0:23333 in a browser for detailed api usage!!!
HINT:    Please open http://0.0.0.0:23333 in a browser for detailed api usage!!!
INFO:     Started server process [210669]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:23333 (Press CTRL+C to quit)

```

**Comment by Vincent131499** [comment]
@lvhan028 推理结果也都正常嘛？

**Comment by lvhan028** [comment]
正常

**Comment by Vincent131499** [comment]
那我重新下载模型，再测试下

**Comment by lvhan028** [comment]
模型的md5值
```
83a9a3fd62572c30bfad8bf6aaa12a21  config.json
5949a57de5fd3148ac75a187c8daec7e  generation_config.json
b13bd08e9cabeffbd41cb405ad48ac3a  LICENSE
72dacf1de43bc354dc3c521e44ed0b24  merges.txt
4e76b9eb7fad54a9fa3f5bd6d76c47d9  model-00001-of-00017.safetensors
041e83db46bba16dd1dd7e57d1c5e9c5  model-00002-of-00017.safetensors
2b86e76928aa0031cf14890f3aaade21  model-00003-of-00017.safetensors
362945a4dcc3966203cd26c2c364127e  model-00004-of-00017.safetensors
0d9b14b9fab9695335daab7c9043033c  model-00005-of-00017.safetensors
47241d91b551f9bd7b1336d1356b03c7  model-00006-of-00017.safetensors
7c887e3e84eb115ed1b3ad6546548abc  model-00007-of-00017.safetensors
3cd0d39c4135ecd4abcc73b6a629f6c4  model-00008-of-00017.safetensors
0bacfc31fcbadc43e787c6fda26584af  model-00009-of-00017.safetensors
b903db6e4f3dcb1c1272fcb235870073  model-00010-of-00017.safetensors
aec427dd708f18ad0568ecee0ff21d1d  model-00011-of-00017.safetensors
b74c68c5c93f0d85fa5c04cfa7dbfbef  model-00012-of-00017.safetensors
37977db40654874738990e6d07525b20  model-00013-of-00017.safetensors
e86adec9ae64b309fa2403e2feb915ce  model-00014-of-00017.safetensors
badcd0f87c877200d592bf7008de0248  model-00015-of-00017.safetensors
6349b27a3561d2a1db5b3148a2943c17  model-00016-of-00017.safetensors
bf07a7b0693dddeb4de0b3d9cd2e8bb0  model-00017-of-00017.safetensors
df25e2eb3f1ef891b6211e71b2109f09  model.safetensors.index.json
59f86cb5d58b648e6c2461751d98cb16  README.md
cf81d5095f42803bee1e31172c7f6e8f  tokenizer_config.json
1c74fd33061313fafc6e2561d1ac3164  tokenizer.json
613b8e4a622c4a2c90e9e1245fc540d6  vocab.json
```

**Comment by Vincent131499** [comment]
收到

**Comment by Vincent131499** [comment]
是我模型不完整
