### ISSUE TITLE
logger in `lmdeploy/serve/async_engine.py` is hard coded

### ISSUE THREAD

**Issue by YanShuang17** [InternLM/lmdeploy#1503]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

logger in `lmdeploy/serve/async_engine.py` is hard coded and can't be controlled by input env valiable 'TM_LOG_LEVEL'

### Reproduction

...

### Environment

```Shell
...
```

**Comment by AllentDan** [comment]
just set `--log-level INFO` for cli. As for pipeline function, set `log_level` argument 'INFO'

**Comment by AllentDan** [comment]
The issue is closed. Feel free to reopen it if it is still an issue.
