### ISSUE TITLE
[Bug] lmdeploy pytorch backend slora cannot use TP=2

### ISSUE THREAD

**Issue by jjjjohnson** [InternLM/lmdeploy#1512]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

Looks like in Pytorch backend  Slora and TP cannot be turned on at the same time...
<img width="966" alt="image" src="https://github.com/InternLM/lmdeploy/assets/20569095/21eb6f32-25a8-4d68-a16a-cdd07ab48e0c">

### Reproduction

```
lmdeploy serve api_server \
    /path/to/qwen14bchat \
    --model-name qwen-14b \
    --server-port 23333 \
    --backend pytorch \
    --cache-max-entry-count 0.95 \
    --max-batch-size 256 --tp 2 \
    --adapters adap1=path2adap1 
```

### Environment

```Shell
lmdeploy 0.3.0
```

**Comment by grimoire** [comment]
We have not support s-lora TP on **ALL** model since that different model have different qkv linear projection.
If you can provide the adapter, we might be able to add the support you need.

**Comment by jjjjohnson** [comment]
Hi @grimoire  Can you show which model type currently support s-lora TP? I will try to solve the issue and PR.

**Comment by jjjjohnson** [comment]
Qwen14b chat:
<img width="549" alt="image" src="https://github.com/InternLM/lmdeploy/assets/20569095/dd42eaf6-cf80-426c-9c8b-b70699a96ec1">
Qwen14b chat with lora:
<img width="691" alt="image" src="https://github.com/InternLM/lmdeploy/assets/20569095/9d16df97-eb13-49bd-963c-8f6fb36cb429">

And qwen.py `mod.register_parameter(name, dist_param)` is not able to deal with nested c_attn
![image](https://github.com/InternLM/lmdeploy/assets/20569095/253999d1-a9ec-4be0-880b-57b433c40670)

**Comment by grimoire** [comment]
All models with seprated q,k,v proj support tp. chatglm2 has similar pattern like qwen

https://github.com/InternLM/lmdeploy/blob/89fc8504d537f8b02cb368dcd808438f55f13b55/lmdeploy/pytorch/models/chatglm2.py#L124-L137

**Comment by jjjjohnson** [comment]
Thanks @grimoire  Qwen has a combined q,k,v proj called `c_attn`, Looks like Baichuan is also very similar to Qwen.
