### ISSUE TITLE
[Feature] lmdeploy chat <model_path> --chat-template {json}

### ISSUE THREAD

**Issue by Nobody-ML** [InternLM/lmdeploy#1519]
### Motivation

LMDeploy 使用 chat cli 推理时不能传入 chat-template 参数

### Additional context

python 3.10.14; lmdeploy 0.4.0; pytorch 2.2.1+cu121
![20240429173237](https://github.com/InternLM/lmdeploy/assets/128660843/f842ee7c-a079-4838-a267-89e0c191f815)

**Comment by RunningLeon** [comment]
@Nobody-ML hi, lmdeploy chat cli is used for demo purpose and it does not support customized chat template from test.json. You can use `lmdeploy serve api_server` or offline inference pipeline to pass the chat template.

**Comment by lvhan028** [comment]
@RunningLeon I think it's better CLI support --chat-template, as it helps user verifying customized chat template efficiently

**Comment by RunningLeon** [comment]
@Nobody-ML hi, if you have time, could you try PR #1566 ?  THX

**Comment by Nobody-ML** [comment]
It works,I can use lmdeploy chat path --chat-template test.json now,thank you.
