### ISSUE TITLE
ziya启动不了

### ISSUE THREAD

**Issue by xxm1668** [InternLM/lmdeploy#152]
(lmdeploy) ➜ lmdeploy sudo bash workspace/service_docker_up.sh

=============================
== Triton Inference Server ==
=============================

NVIDIA Release 22.12 (build 50109463)
Triton Server Version 2.29.0

Copyright (c) 2018-2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

I0721 03:34:28.851237 1 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x7f6d00000000' with size 268435456
I0721 03:34:28.851696 1 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
I0721 03:34:28.857984 1 model_lifecycle.cc:459] loading: postprocessing:1
I0721 03:34:28.858019 1 model_lifecycle.cc:459] loading: preprocessing:1
I0721 03:34:28.858036 1 model_lifecycle.cc:459] loading: turbomind:1
I0721 03:34:29.000309 1 libfastertransformer.cc:1746] TRITONBACKEND_Initialize: turbomind
I0721 03:34:29.000337 1 libfastertransformer.cc:1753] Triton TRITONBACKEND API version: 1.10
I0721 03:34:29.000340 1 libfastertransformer.cc:1757] 'turbomind' TRITONBACKEND API version: 1.10
I0721 03:34:29.002218 1 libfastertransformer.cc:1784] TRITONBACKEND_ModelInitialize: turbomind (version 1)
I0721 03:34:29.002902 1 libfastertransformer.cc:307] Instance group type: KIND_CPU count: 48
num_nodes=1
tp_pp_size=1
gpu_size=1
world_size=1
model_instance_size=1
I0721 03:34:29.002929 1 libfastertransformer.cc:346] Sequence Batching: disabled
I0721 03:34:29.002934 1 libfastertransformer.cc:357] Dynamic Batching: disabled
[ERROR] Does not find the section llama with name model_name.

**Comment by lvhan028** [comment]
能不能把你用deploy.py部署模型的命令发来看看？

**Comment by xxm1668** [comment]
python3 -m lmdeploy.serve.turbomind.deploy ziya /home/house365ai/xxm/llama-13b-ziya hf

**Comment by xxm1668** [comment]
llama-13b-hf和Ziya-LLaMA-13B-v1.1合并而来的llama-13b-ziya

**Comment by irexyc** [comment]
请提供一下这个文件的内容：`triton_models/weights/config.ini`

**Comment by xxm1668** [comment]
[llama]
model_name = ziya
head_num = 40
size_per_head = 128
vocab_size = 39408
num_layer = 40
rotary_embedding = 128
inter_size = 13824
norm_eps = 1e-06
attn_bias = 0
start_id = 1
end_id = 2
weight_type = fp16
max_batch_size = 32
max_context_token_num = 4
session_len = 2056
step_length = 1
cache_max_entry_count = 48
cache_chunk_size = 1
use_context_fmha = 1
quant_policy = 0
tensor_para_size = 1

**Comment by xxm1668** [comment]
Does not find the section llama with name model_name.大佬求助！

**Comment by irexyc** [comment]
这个ERROR是这里打印的，意思是找不到 [llama] 里面的 model_name，但是你给的 config.ini 是有这些信息的，但是没想到原因。

https://github.com/InternLM/lmdeploy/blob/main/src/turbomind/triton_backend/llama/LlamaTritonModel.cc#L118
https://github.com/InternLM/lmdeploy/blob/main/3rdparty/INIReader.h#L406C1-L406C1

**Comment by irexyc** [comment]
@xxm1668  如果还不行的话，你可以把workspace这个文件夹打包发上来(weights文件夹需要打包config.ini, 不需要打包*weight)
```
tar --exclude='*.weight' -zcvf workspace.tar.gz workspace
```

**Comment by xxm1668** [comment]
[](url)
[workspace.tar.gz](https://github.com/InternLM/lmdeploy/files/12122438/workspace.tar.gz)

**Comment by xxm1668** [comment]
已上传，麻烦看下，谢谢

**Comment by irexyc** [comment]
tritonserver 启动的时候看的是model_repository/这个文件夹，里面有三个模型：
```
lrwxrwxrwx 1 chenxin chenxin 31 Jul 21 11:34 postprocessing -> ../triton_models/postprocessing
lrwxrwxrwx 1 chenxin chenxin 30 Jul 21 11:34 preprocessing -> ../triton_models/preprocessing
lrwxrwxrwx 1 chenxin chenxin 28 Jul 21 11:34 turbomind -> ../triton_models/interactive
```

interactive 模型启动的时候会读取
`model_repository/turbomind/1/weights/config.ini`
也就是这个目录 
`triton_models/interactive/1/weights/config.ini`


而这个文件夹`triton_models/interactive/1/weights/` 正常来讲是要软连接../../weights 目录的，也就是`triton_models/weights`目录。

但是你的`triton_models/interactive/1/weights/`这个目录并没有软链 `triton_models/weights`
你可以看一下你的目录`triton_models/weights/config.ini`是有值的，但是`triton_models/interactive/1/weights/config.ini`是空的


解决方法：
```
cd triton_models/interactive/1/
rm -rf weights
ln -s ../../weights/
```

**Comment by lvhan028** [comment]
@irexyc 检查下是不是deploy.py有什么问题，它要负责把软连接创建好

**Comment by xxm1668** [comment]
问一下，如何使用Int8加载模型ziya-llama-13b呢

**Comment by pppppM** [comment]
目前只有对 KV Cache 做 Int8 量化的功能
https://github.com/InternLM/lmdeploy/blob/7b470f07bc27645a26d0dac334739e8945ef519c/README_zh-CN.md?plain=1#L147-L166

模型权重的 INT8 量化还在开发中

**Comment by xxm1668** [comment]
I0725 06:32:16.420076 1 libfastertransformer.cc:775] Model instance is created on GPU [ 0 ]
I0725 06:32:16.420082 1 libfastertransformer.cc:1839] TRITONBACKEND_ModelInstanceInitialize: turbomind_0_37 (count 48) (instance_id 37)
[TM][INFO] Skipping NCCL param creation.
I0725 06:32:16.420511 1 libfastertransformer.cc:421] Before Loading Model:
after allocation    : free: 52.12 GB, total: 79.15 GB, used: 27.03 GB
I0725 06:32:16.420600 1 libfastertransformer.cc:437] After Loading Model:
after allocation    : free: 52.12 GB, total: 79.15 GB, used: 27.03 GB
[TM][INFO] Barrier(1)
I0725 06:32:16.420658 1 libfastertransformer.cc:775] Model instance is created on GPU [ 0 ]
I0725 06:32:16.420670 1 libfastertransformer.cc:1839] TRITONBACKEND_ModelInstanceInitialize: turbomind_0_38 (count 48) (instance_id 38)
[TM][INFO] Skipping NCCL param creation.
I0725 06:32:16.421090 1 libfastertransformer.cc:421] Before Loading Model:
after allocation    : free: 52.12 GB, total: 79.15 GB, used: 27.03 GB
I0725 06:32:16.421222 1 libfastertransformer.cc:437] After Loading Model:
after allocation    : free: 52.12 GB, total: 79.15 GB, used: 27.03 GB
[TM][INFO] Barrier(1)
I0725 06:32:16.421280 1 libfastertransformer.cc:775] Model instance is created on GPU [ 0 ]
I0725 06:32:16.421285 1 libfastertransformer.cc:1839] TRITONBACKEND_ModelInstanceInitialize: turbomind_0_39 (count 48) (instance_id 39)
[TM][INFO] Skipping NCCL param creation.
I0725 06:32:16.421715 1 libfastertransformer.cc:421] Before Loading Model:
after allocation    : free: 52.12 GB, total: 79.15 GB, used: 27.03 GB
I0725 06:32:16.421786 1 libfastertransformer.cc:437] After Loading Model:
after allocation    : free: 52.12 GB, total: 79.15 GB, used: 27.03 GB
[TM][INFO] Barrier(1)
I0725 06:32:16.421840 1 libfastertransformer.cc:775] Model instance is created on GPU [ 0 ]
I0725 06:32:16.421845 1 libfastertransformer.cc:1839] TRITONBACKEND_ModelInstanceInitialize: turbomind_0_40 (count 48) (instance_id 40)
[TM][INFO] Skipping NCCL param creation.
I0725 06:32:16.422248 1 libfastertransformer.cc:421] Before Loading Model:
after allocation    : free: 52.12 GB, total: 79.15 GB, used: 27.03 GB
I0725 06:32:16.422331 1 libfastertransformer.cc:437] After Loading Model:
after allocation    : free: 52.12 GB, total: 79.15 GB, used: 27.03 GB
[TM][INFO] Barrier(1)
I0725 06:32:16.422391 1 libfastertransformer.cc:775] Model instance is created on GPU [ 0 ]
I0725 06:32:16.422399 1 libfastertransformer.cc:1839] TRITONBACKEND_ModelInstanceInitialize: turbomind_0_41 (count 48) (instance_id 41)
[TM][INFO] Skipping NCCL param creation.
I0725 06:32:16.422840 1 libfastertransformer.cc:421] Before Loading Model:
after allocation    : free: 52.12 GB, total: 79.15 GB, used: 27.03 GB
I0725 06:32:16.422926 1 libfastertransformer.cc:437] After Loading Model:
after allocation    : free: 52.12 GB, total: 79.15 GB, used: 27.03 GB
[TM][INFO] Barrier(1)
I0725 06:32:16.422982 1 libfastertransformer.cc:775] Model instance is created on GPU [ 0 ]
I0725 06:32:16.422987 1 libfastertransformer.cc:1839] TRITONBACKEND_ModelInstanceInitialize: turbomind_0_42 (count 48) (instance_id 42)
[TM][INFO] Skipping NCCL param creation.
I0725 06:32:16.423413 1 libfastertransformer.cc:421] Before Loading Model:
after allocation    : free: 52.12 GB, total: 79.15 GB, used: 27.03 GB
I0725 06:32:16.423497 1 libfastertransformer.cc:437] After Loading Model:
after allocation    : free: 52.12 GB, total: 79.15 GB, used: 27.03 GB
[TM][INFO] Barrier(1)
I0725 06:32:16.423553 1 libfastertransformer.cc:775] Model instance is created on GPU [ 0 ]
I0725 06:32:16.423559 1 libfastertransformer.cc:1839] TRITONBACKEND_ModelInstanceInitialize: turbomind_0_43 (count 48) (instance_id 43)
[TM][INFO] Skipping NCCL param creation.
I0725 06:32:16.424247 1 libfastertransformer.cc:421] Before Loading Model:
after allocation    : free: 52.12 GB, total: 79.15 GB, used: 27.03 GB
I0725 06:32:16.424331 1 libfastertransformer.cc:437] After Loading Model:
after allocation    : free: 52.12 GB, total: 79.15 GB, used: 27.03 GB
[TM][INFO] Barrier(1)
I0725 06:32:16.424390 1 libfastertransformer.cc:775] Model instance is created on GPU [ 0 ]
I0725 06:32:16.424397 1 libfastertransformer.cc:1839] TRITONBACKEND_ModelInstanceInitialize: turbomind_0_44 (count 48) (instance_id 44)
[TM][INFO] Skipping NCCL param creation.
I0725 06:32:16.424859 1 libfastertransformer.cc:421] Before Loading Model:
after allocation    : free: 52.12 GB, total: 79.15 GB, used: 27.03 GB
I0725 06:32:16.424949 1 libfastertransformer.cc:437] After Loading Model:
after allocation    : free: 52.12 GB, total: 79.15 GB, used: 27.03 GB
[TM][INFO] Barrier(1)
I0725 06:32:16.425005 1 libfastertransformer.cc:775] Model instance is created on GPU [ 0 ]
I0725 06:32:16.425016 1 libfastertransformer.cc:1839] TRITONBACKEND_ModelInstanceInitialize: turbomind_0_45 (count 48) (instance_id 45)
[TM][INFO] Skipping NCCL param creation.
I0725 06:32:16.425444 1 libfastertransformer.cc:421] Before Loading Model:
after allocation    : free: 52.12 GB, total: 79.15 GB, used: 27.03 GB
I0725 06:32:16.425496 1 libfastertransformer.cc:437] After Loading Model:
after allocation    : free: 52.12 GB, total: 79.15 GB, used: 27.03 GB
[TM][INFO] Barrier(1)
I0725 06:32:16.425544 1 libfastertransformer.cc:775] Model instance is created on GPU [ 0 ]
I0725 06:32:16.425550 1 libfastertransformer.cc:1839] TRITONBACKEND_ModelInstanceInitialize: turbomind_0_46 (count 48) (instance_id 46)
[TM][INFO] Skipping NCCL param creation.
I0725 06:32:16.426018 1 libfastertransformer.cc:421] Before Loading Model:
after allocation    : free: 52.12 GB, total: 79.15 GB, used: 27.03 GB
I0725 06:32:16.426162 1 libfastertransformer.cc:437] After Loading Model:
after allocation    : free: 52.12 GB, total: 79.15 GB, used: 27.03 GB
[TM][INFO] Barrier(1)
I0725 06:32:16.426232 1 libfastertransformer.cc:775] Model instance is created on GPU [ 0 ]
I0725 06:32:16.426245 1 libfastertransformer.cc:1839] TRITONBACKEND_ModelInstanceInitialize: turbomind_0_47 (count 48) (instance_id 47)
I0725 06:32:16.426619 1 model_lifecycle.cc:694] successfully loaded 'turbomind' version 1
I0725 06:32:16.426793 1 server.cc:563] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I0725 06:32:16.426864 1 server.cc:590] 
+-----------+-------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| Backend   | Path                                                        | Config                                                                                            |
+-----------+-------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| python    | /opt/tritonserver/backends/python/libtriton_python.so       | {"cmdline":{"auto-complete-config":"true","min-compute-capability":"6.000000","backend-directory" |
|           |                                                             | :"/opt/tritonserver/backends","default-max-batch-size":"4"}}                                      |
| turbomind | /opt/tritonserver/backends/turbomind/libtriton_turbomind.so | {"cmdline":{"auto-complete-config":"true","min-compute-capability":"6.000000","backend-directory" |
|           |                                                             | :"/opt/tritonserver/backends","default-max-batch-size":"4"}}                                      |
+-----------+-------------------------------------------------------------+---------------------------------------------------------------------------------------------------+

I0725 06:32:16.426922 1 server.cc:633] 
+----------------+---------+-------------------------------------------------------------------------------------+
| Model          | Version | Status                                                                              |
+----------------+---------+-------------------------------------------------------------------------------------+
| postprocessing | 1       | UNAVAILABLE: Internal: ModuleNotFoundError: No module named '1.tokenizer.tokenizer' |
|                |         |                                                                                     |
|                |         | At:                                                                                 |
|                |         |   /workspace/models/model_repository/postprocessing/1/model.py(13): <module>        |
|                |         |   <frozen importlib._bootstrap>(219): _call_with_frames_removed                     |
|                |         |   <frozen importlib._bootstrap_external>(848): exec_module                          |
|                |         |   <frozen importlib._bootstrap>(686): _load_unlocked                                |
|                |         |   <frozen importlib._bootstrap>(975): _find_and_load_unlocked                       |
|                |         |   <frozen importlib._bootstrap>(991): _find_and_load                                |
| preprocessing  | 1       | UNAVAILABLE: Internal: ModuleNotFoundError: No module named '1.tokenizer.tokenizer' |
|                |         |                                                                                     |
|                |         | At:                                                                                 |
|                |         |   /workspace/models/model_repository/preprocessing/1/model.py(15): <module>         |
|                |         |   <frozen importlib._bootstrap>(219): _call_with_frames_removed                     |
|                |         |   <frozen importlib._bootstrap_external>(848): exec_module                          |
|                |         |   <frozen importlib._bootstrap>(686): _load_unlocked                                |
|                |         |   <frozen importlib._bootstrap>(975): _find_and_load_unlocked                       |
|                |         |   <frozen importlib._bootstrap>(991): _find_and_load                                |
| turbomind      | 1       | READY                                                                               |
+----------------+---------+-------------------------------------------------------------------------------------+

I0725 06:32:16.452403 1 metrics.cc:864] Collecting metrics for GPU 0: NVIDIA A100 80GB PCIe
I0725 06:32:16.452790 1 metrics.cc:757] Collecting CPU metrics
I0725 06:32:16.452929 1 tritonserver.cc:2264] 
+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                      |
+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                     |
| server_version                   | 2.29.0                                                                                                                                     |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda |
|                                  | _shared_memory binary_tensor_data statistics trace logging                                                                                 |
| model_repository_path[0]         | /workspace/models/model_repository                                                                                                         |
| model_control_mode               | MODE_NONE                                                                                                                                  |
| strict_model_config              | 0                                                                                                                                          |
| rate_limit                       | OFF                                                                                                                                        |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                  |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                                   |
| response_cache_byte_size         | 0                                                                                                                                          |
| min_supported_compute_capability | 6.0                                                                                                                                        |
| strict_readiness                 | 1                                                                                                                                          |
| exit_timeout                     | 30                                                                                                                                         |
+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+

I0725 06:32:16.452963 1 server.cc:264] Waiting for in-flight requests to complete.
I0725 06:32:16.452969 1 server.cc:280] Timeout 30: Found 0 model versions that have in-flight inferences
I0725 06:32:16.453024 1 server.cc:295] All models are stopped, unloading models
I0725 06:32:16.453033 1 server.cc:302] Timeout 30: Found 1 live models and 0 in-flight non-inference requests
I0725 06:32:16.453430 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.453606 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.453790 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.453935 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.454126 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.454303 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.454572 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.454772 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.455019 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.455178 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.455365 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.455578 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.455770 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.455973 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.456172 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.456329 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.456540 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.456728 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.456895 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.457076 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.457264 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.457439 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.457568 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.457719 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.457841 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.457984 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.458113 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.458272 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.458408 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.458545 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.458692 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.458790 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.458915 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.459003 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.459111 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.459210 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.459313 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.459418 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.459514 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.459614 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.459705 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.459820 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.459908 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.459997 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.460107 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.460221 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.460315 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.460392 1 libfastertransformer.cc:1861] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0725 06:32:16.460496 1 libfastertransformer.cc:1803] TRITONBACKEND_ModelFinalize: delete model state
I0725 06:32:16.460539 1 libfastertransformer.cc:1807] TRITONBACKEND_ModelFinalize: MPI Finalize
I0725 06:32:16.509342 1 model_lifecycle.cc:579] successfully unloaded 'turbomind' version 1
I0725 06:32:17.453180 1 server.cc:302] Timeout 29: Found 0 live models and 0 in-flight non-inference requests
error: creating server: Internal - failed to load all models

**Comment by lvhan028** [comment]
@xxm1668 
Can you run `tree workspace/triton_models/tokenizer` and share the result to us?

**Comment by xxm1668** [comment]
workspace/triton_models/tokenizer
├── added_tokens.json
├── config.json
├── generation_config.json
├── placeholder
├── pytorch_model.bin.index.json
├── special_tokens_map.json
├── tokenizer_config.json
├── tokenizer.model
└── tokenizer.py

1 directory, 9 files

**Comment by xxm1668** [comment]
@lvhan028 大佬，帮忙解决一下

**Comment by irexyc** [comment]
@xxm1668 

应该还是软连接的错误，我估计你的preprocessing/1/tokenizer 和 postprocessing/1/tokenizer 这两个文件夹都是空的

你可以在 postprocessing/1 和 postprocessing/1 下面：
```
rm tokenizer
ln -s ../../tokenizer
```
