### ISSUE TITLE
[求教]4张t4卡，能用哪个版本？能否使用

### ISSUE THREAD

**Issue by ye7love7** [InternLM/lmdeploy#1542]
T4卡不能装cu12，无法安装torch2.1，我很好奇有人用t4启动了千问1.5的模型，是因为transformers对torch版本没有要求吗？
回归正题，我想使用internlm/internlm-xcomposer2-vl-7b模型，并以openai标准接口提供服务，折腾了一天，使用了cu118的版本，报显卡错误，本地4张t4，cuda11.7，驱动是515，这个环境应该如何安装使用这个项目，万分感谢！

**Comment by lvhan028** [comment]
操作系统是什么？

**Comment by lvhan028** [comment]
和 #1563 问题类似。
关闭此问题，使用 #1563 继续跟进
