### ISSUE TITLE
does not appear to have a file named preprocessor_config.json. Checkout...[Bug] 

### ISSUE THREAD

**Issue by White-Friday** [InternLM/lmdeploy#1543]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

在本地加载模型的时候一直报：does not appear to have a file named preprocessor_config.json. Checkout...，这个错误，但是我们的下载文件里面并没有没有preprocessor_config.json文件 

### Reproduction

```python
from lmdeploy import pipeline, TurbomindEngineConfig
from lmdeploy.vl import load_image
import os
os.environ['CUDA_VISIBLE_DEVICES'] = "5"


pipe = pipeline('OpenGVLab/InternVL-Chat-V1-5-Int8',
                backend_config=TurbomindEngineConfig(session_len=512))

image_urls=[
    'images/1.jpg',
    'images/2.jpg'
]

images = [load_image(img_url) for img_url in image_urls]
response = pipe(('描述下面的图片', images))
print(response)
```

### Environment

```Shell
lmdeploy==0.4.0
tokenizers==0.19.1
tomli==2.0.1
torch==2.2.2
torcheval==0.0.7
torchvision==0.17.1+cu121
```

**Comment by lvhan028** [comment]
支持internvl 1.5的版本还没发。可以使用latest main，自己编译

**Comment by White-Friday** [comment]
@lvhan028 了解，谢谢

**Comment by lvhan028** [comment]
FYI，本周会发 v0.4.1 版本。internvl-1.5 会在这个版本中支持

**Comment by lvhan028** [comment]
"OpenGVLab/InternVL-Chat-V1-5-Int8" LMDeploy 不支持这个模型的 INT8 量化版本
LMDeploy 会提供它的 4bit 权重量化和推理。这个PR正在处理 https://github.com/InternLM/lmdeploy/pull/1553
另外，kv cache 量化已经支持, --quant-policy 4 表示 4bit kv，8 表示 8bit kv

**Comment by AllentDan** [comment]
缺的兩個文件可以考慮從非量化的模型路徑裏拷貝過去試試。
