### ISSUE TITLE
Support for Llama-2 chinese?

### ISSUE THREAD

**Issue by chaoer** [InternLM/lmdeploy#155]
[Llama2-Chinese](https://github.com/FlagAlpha/Llama2-Chinese#gradio%E5%BF%AB%E9%80%9F%E6%90%AD%E5%BB%BA%E9%97%AE%E7%AD%94%E5%B9%B3%E5%8F%B0)

and how to deploy Llama2 with GQA ? ( [serving.md](https://github.com/InternLM/lmdeploy/blob/main/docs/en/serving.md#serving-llama) only contains instructions for Llama1)

**Comment by lvhan028** [comment]
```bash
python3 -m lmdeploy.serve.turbomind.deploy llama2 /path/to/llama-2-7b-chat-hf hf
bash workspace/service_docker_up.sh
```

**Comment by chaoer** [comment]
thanks
