### ISSUE TITLE
[Bug] 关于流式并发相关

### ISSUE THREAD

**Issue by Dingxiangxiang** [InternLM/lmdeploy#1557]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

lmdeploy 4.0版本，pipline的方式流式输出，好像不支持并发 ，请问大佬们是怎么解决的

### Reproduction

lmdeploy pipline推理的

### Environment

```Shell
lmdeploy 4.0
```

**Comment by AllentDan** [comment]
麻烦贴一下使用的脚本。stream_infer 本身就是支持多个 prompt 输入的

**Comment by AllentDan** [comment]
pipeline 并发请调用协程接口 `generate`。
