### ISSUE TITLE
[Bug] 3090量化llama3 70b爆显存

### ISSUE THREAD

**Issue by lg123666** [InternLM/lmdeploy#1562]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

在3090显卡，24g显存，使用lmdeploy lite awq量化llama3 70b在79层爆显存，按照建议增加了PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
在nvidia-smi看只使用了第一张卡，可以使用多张卡吗？
![爆显存](https://github.com/InternLM/lmdeploy/assets/40393969/a27f32e2-3105-4318-bb3b-509d461af951)

### Reproduction

lmdeploy lite auto_awq /Meta-Llama-3-70B-Instruct --work-dir /Meta-Llama-3-70B-Instruct-4bit

### Environment

```Shell
sys.platform: linux
Python: 3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda-11.8
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: gcc (GCC) 9.3.0
PyTorch: 2.2.2+cu118
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.4
    - Built with CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

LMDeploy: 0.4.0+
transformers: 4.40.1
gradio: Not Found
fastapi: 0.111.0
pydantic: 2.7.1
triton: 2.2.0
```

**Comment by AllentDan** [comment]
可以 calib_seqlen 设小一些试试

**Comment by lg123666** [comment]
> 可以 calib_seqlen 设小一些试试

非常感谢~！lmdeploy lite auto_awq /Meta-Llama-3-70B-Instruct --work-dir /Meta-Llama-3-70B-Instruct-4bit --calib-seqlen 1024成功编译。顺便请教下，awq编译的w4a16精度下降大概多少呢？lmdeploy有工具可以直接测试ppl吗？

**Comment by AllentDan** [comment]
可以用 opencompass。https://github.com/open-compass/opencompass/blob/main/docs/zh_cn/advanced_guides/evaluation_turbomind.md

**Comment by lvhan028** [comment]
https://lmdeploy.readthedocs.io/en/latest/advance/long_context.html#perplexity
可以参考上面的文档，计算 ppl

**Comment by lg123666** [comment]
> 可以 calib_seqlen 设小一些试试
llama3 70b awq量化后的模型输出乱码，但是8b的结果是OK的，请问可能是什么原因呢？

![70b](https://github.com/InternLM/lmdeploy/assets/40393969/70b26015-08bb-4ca6-adc4-9ff6197f97ff)

**Comment by AllentDan** [comment]
应该就是量化失败了。目前 lmdeploy 的量化没有搜 ratio 的能力，可以用 auto_awq，或者等 lmdeploy 下个版本试试。

**Comment by lvhan028** [comment]
@AllentDan 基于你最近的工作，量化下llama3-70b，结果正常么？

**Comment by AllentDan** [comment]
> @AllentDan 基于你最近的工作，量化下llama3-70b，结果正常么？

之前的版本就可以量化 llava3_llama70b，对话正常。可能是xtuner 微调过权重变了。目前没有过 70b 搜 scale 很耗时

**Comment by lg123666** [comment]
> 应该就是量化失败了。目前 lmdeploy 的量化没有搜 ratio 的能力，可以用 auto_awq，或者等 lmdeploy 下个版本试试。

这里用的就是auto_awq

**Comment by lg123666** [comment]
> > @AllentDan 基于你最近的工作，量化下llama3-70b，结果正常么？
> 
> 之前的版本就可以量化 llava3_llama70b，对话正常。可能是xtuner 微调过权重变了。目前没有过 70b 搜 scale， 很耗时

没有做微调，用的是原生权重。请问这里auto_awq的scale是预先生成的吗？

**Comment by AllentDan** [comment]
https://github.com/casper-hansen/AutoAWQ 是指这个项目

**Comment by lg123666** [comment]
> 应该就是量化失败了。目前 lmdeploy 的量化没有搜 ratio 的能力，可以用 auto_awq，或者等 lmdeploy 下个版本试试。

用0.42版本还是不行，同时使用[huggingface别人提供的awq](https://huggingface.co/casperhansen/llama-3-70b-instruct-awq/discussions)，也是乱码

**Comment by lvhan028** [comment]
显卡型号是什么呢？

**Comment by lg123666** [comment]
> 显卡型号是什么呢？

3090

**Comment by lvhan028** [comment]
我先下载你分享的模型试试

**Comment by lg123666** [comment]
> 我先下载你分享的模型试试

请问现在lmdeploy对于llama3 70b模型量化失败的问题解决了吗？

**Comment by lvhan028** [comment]
抱歉，我忘记更新状态了。
我下载了 https://huggingface.co/casperhansen/llama-3-70b-instruct-awq，直接用 lmdeploy 来推理，结果没什么问题。
我用的显卡是 A100（80G）

**Comment by lvhan028** [comment]
麻烦分享下你的代码和运行时日志吧。还请把 log_level 设置为 INFO

**Comment by lg123666** [comment]
> Meta-Llama-3-70B-Instruct-4bit

使用最新的0.5版本重新量化也不行

![log1](https://github.com/InternLM/lmdeploy/assets/40393969/b63e866b-46be-4d83-a04e-0a0456bcb7f9)
![log2](https://github.com/InternLM/lmdeploy/assets/40393969/de977996-02ab-4484-95bb-3fbc1d86d8f3)
![log3](https://github.com/InternLM/lmdeploy/assets/40393969/a9ba795e-262c-47e6-baa7-e58b3ba1c23e)
![log4](https://github.com/InternLM/lmdeploy/assets/40393969/11f83a25-a0d9-484f-a72f-a5326f60c758)
