### ISSUE TITLE
[Feature] 请求增加Intern-VL多模态模型的文本和图像的embedding支持

### ISSUE THREAD

**Issue by chiquitita-101** [InternLM/lmdeploy#1576]
### Motivation

Intern-VL系列很强，利用文本和图像的embedding做检索既快又好。现在官方的部署好像没有支持embedding，也没有多模态的文本和图像的embedding，我部署了VL的聊天模型之后，却没法拿到embedding；又另外用triton server部署了一个，很占卡。我感觉是很有用的，球球了

**Comment by lvhan028** [comment]
没太能理解需求。
能不能具体描述下，输入是什么，输出是什么，接口形态期望是怎样的？
返回视觉embeddings，我理解直接用上游库就好了，lmdeploy并没有对视觉模型的推理做什么优化，而且我们也没优化视觉部分的计划。这有些超过 lmdeploy 的功能范围
多模态的文本和图像的embedding，是说 token embedding 和图像 embedding 拼接在一起的结果么？

**Comment by chiquitita-101** [comment]
好吧，我看tensorrt-llm支持多模态模型，所以以为这个也是支持了视觉部分的优化的。如果没有优化视觉部分的计划，就算了吧。

**Comment by lvhan028** [comment]
恩，对视觉模型推理优化有刚需的话，可以用tensorrt-llm，挺好的。
