### ISSUE TITLE
[Feature] Support for LLaVA-NeXT Qwen1.5-110, Qwen1.5-72B,	LLaMA3-8B

### ISSUE THREAD

**Issue by Iven2132** [InternLM/lmdeploy#1583]
### Motivation

It outperforms existing open-source models like Intern-VL-1.5

 https://llava-vl.github.io/blog/2024-05-10-llava-next-stronger-llms/#:~:text=Live%20Demo-,Benchmark%20Results,-Results%20with%20LMMs

### Related resources

https://llava-vl.github.io/blog/2024-05-10-llava-next-stronger-llms/

**Comment by White-Friday** [comment]
请问现在是否已经支持LLaVA-NeXT Qwen1.5-110, Qwen1.5-72B, LLaMA3-8B了吗

**Comment by lvhan028** [comment]
Yes. They are supported.

**Comment by lvhan028** [comment]
It probably has problem when the model is large.
#1563 explains the reason

**Comment by Iven2132** [comment]
> Yes. They are supported.

@lvhan028 So I can use the LLaVA-NeXT Qwen1.5-72B, LLaMA3-8B?

**Comment by lvhan028** [comment]
Sorry, my bad. 
It probably needs to make some changes like PR #1579 does.
I didn't find the checkpoints. Could you share the huggingface repo_id?

**Comment by babla9** [comment]
Do you know what minimum GPU memory requirements would be to serve these VL models? Thanks!

**Comment by Iven2132** [comment]
> Do you know what minimum GPU memory requirements would be to serve these VL models? Thanks!

A100s are best if you want you can run these on Modal, they are giving $30 free credits

**Comment by babla9** [comment]
> > Do you know what minimum GPU memory requirements would be to serve these VL models? Thanks!
> 
> A100s are best if you want you can run these on Modal, they are giving $30 free credits

Thanks, for LLaVA, do you know what the minimum configuration would be? eg 1 x A100 40gb? Would V100s work (eg 2xV100)? Anyway I can serve quantized models using V100s via lmdeploy?

**Comment by Iven2132** [comment]
> > > Do you know what minimum GPU memory requirements would be to serve these VL models? Thanks!
> > 
> > 
> > A100s are best if you want you can run these on Modal, they are giving $30 free credits
> 
> Thanks, for LLaVA, do you know what the minimum configuration would be? eg 1 x A100 40gb? Would V100s work (eg 2xV100)? Anyway I can serve quantized models using V100s via lmdeploy?

I'm not sure but you can run the llava-next 8b model with one A100

**Comment by Iven2132** [comment]
@KevinNuNu Will this support?

**Comment by Iven2132** [comment]
@lvhan028 Will it support Llava-next?

**Comment by lvhan028** [comment]
Regarding llava-next, models in https://huggingface.co/collections/liuhaotian/llava-16-65b9e40155f60fd046a5ccf2 have already been supported except https://huggingface.co/liuhaotian/llava-v1.6-mistral-7b 

We will support the following in June
```
lmms-lab/llama3-llava-next-8b: https://huggingface.co/lmms-lab/llama3-llava-next-8b
lmms-lab/llava-next-72b: https://huggingface.co/lmms-lab/llava-next-72b
lmms-lab/llava-next-110b: https://huggingface.co/lmms-lab/llava-next-110b
```
