### ISSUE TITLE
[Feature] progress bar for inference pipeline

### ISSUE THREAD

**Issue by yilunzhao** [InternLM/lmdeploy#1586]
### Motivation

I am using the LLM inference pipeline as outlined in https://github.com/InternLM/lmdeploy/blob/main/docs/en/inference/pipeline.md, which processes approximately 10,000 examples input in the `pipe`. However, the current version lacks a progress bar to display the processing status. Could this feature be added in a future update?

### Related resources

[vllm implementation](https://github.com/vllm-project/vllm/blob/702bee461f448b0186eb9d673baad29fd923c884/vllm/entrypoints/llm.py#L166)

**Comment by lvhan028** [comment]
It is already supported. 
https://github.com/InternLM/lmdeploy/blob/ca4de27c2a98a804f707c194f121adb3c6d04076/lmdeploy/serve/async_engine.py#L291
set `use_tqdm` True when invoking the callable of pipeline
