### ISSUE TITLE
[Bug] The response of /v1/chat/completions is not correct, when input params message is a string prompt.

### ISSUE THREAD

**Issue by zhulinJulia24** [InternLM/lmdeploy#1599]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

The response of /v1/chat/completions is not correct, when input params message is string prompt.

The response is like the return of /v1/completions, **Should we disable string prompt input of /v1/chat/completions or fix this issue?**

prompt: 这个是不是酒 
{'id': '18', 'object': 'chat.completion', 'created': 1715827721, 'model': 'internlm2', 'choices': [{'index': 0, 'message': {'role': 'assistant', 'content': '鬼花生？\n是，这是一种常见的小吃。\n酒鬼花生，又名油炸花生米，是中国南方地区的传统小吃之一。它通常由花生米、辣椒、花椒等香料组成，经过油炸后，呈现出金黄色的外观，口感酥脆，略带麻辣味。\n\n制作方法通常如下：\n\n1. **准备原料**：\n   - 花生米：选用新鲜的花生米，洗净后晾干。\n   - 调味料：盐、糖、胡椒粉、花椒粉等，根据个人口味调整。\n\n2. **油炸**：\n   - 将花生米放入锅中，用小火干炒至出香味，注意不要炒焦。\n   - 把锅中的花生米取出，稍放凉。\n   - 在锅中倒入油，加热至油温达到180°C左右。\n   - 将花生米放入油锅中，快速翻动，炸至金黄色并浮起。\n   - 用漏勺捞出花生米，沥干油分。\n\n3. **调味**：\n   - 在炸好的花生米上均匀撒上盐、糖、辣椒粉、花椒粉等调料。\n   - 用锅铲轻轻翻炒，使调料均匀附着在花生上。\n\n4. **冷却**：\n   - 将调味后的花生米放在干燥通风的地方，让其自然冷却。\n\n5. **存储**：\n   - 冷却后的花生米可以装入密封的容器中，保存在阴凉干燥的地方。\n\n食用时，可以直接作为零食，也可以作为菜肴的配菜。由于其独特的口感和香气，酒鬼花生深受人们的喜爱，特别是在聚会、酒吧、餐馆等场合，常常作为开胃小吃或下酒菜\n\n需要注意的是，酒鬼花生虽然美味，但热量较高，过量食用可能导致肥胖和其他健康问题。因此，建议适量食用，并结合均衡饮食和适量运动来维持健康。\n\n此外，花生过敏者应避免食用酒鬼花生，以免引起过敏反应。在购买或自制酒鬼花生时，应确保原料新鲜，制作过程卫生，以保证食品的质量和安全。'}, 'logprobs': None, 'finish_reason': 'stop'}], 'usage': {'prompt_tokens': 4, 'total_tokens': 412, 'completion_tokens': 408}}

### Reproduction

1. start a server: `lmdeploy serve api_server /nvme/qa_test_models/internlm/internlm2-chat-20b --model-name internlm2 --server-port 25333 --tp 2 `
2. request /v1/chat/completions by using following code:

```
from lmdeploy.serve.openai.api_client import APIClient

client = APIClient("http://localhost:25333", api_key="dddd")


for output in client.chat_completions_v1(
                    model='internlm2',
                    messages='这个是不是酒',
                    temperature=1.0,
                    top_p=0.8,
                    top_k=40,
                    n=1,
                    repetition_penalty=1.02,
                    max_tokens=2056,
                    stream=False):
    continue

print(output)
```

get response like:

{'id': '3', 'object': 'chat.completion', 'created': 1715828237, 'model': 'internlm2', 'choices': [{'index': 0, 'message': {'role': 'assistant', 'content': '局？\n“局”这个字，可以解释为“规则”。比如棋局，棋子的摆放，走棋的规则。又如牌局，出牌的规则。再如酒局，喝酒的规则。\n如果将喝酒的规则，简化一下，就是“喝酒”。那就不存在酒局了。如果将棋子的摆放和走棋的规则简化一下，那就是“下棋”，也不存在棋局了。\n所以，你问的这个问题，其实不是问题。是酒局，也是喝酒。是棋局，也是下棋。是牌局，也是打牌。\n最后，我有个问题，为什么“这个是不是酒局？”这个句式，这么让人反感。\n————————————————————————————————————————\n有人问为什么反感这个句式，因为太装逼。比如：\n“你猜这个是什么？”“这是啥？”“这个你不出来吗？”“这到底是什么？”“你说是啥？”\n————————————————————————————————————————\n更新：“这到底是啥？”“这个是什么？”“这是什么鬼？”“这是什么玩意儿？”“这到底是个啥？”“这到底是个啥玩意儿？”\n————————————————————————————————————————\n再更新：“你猜这个是什么？”“这是啥？”“这个你看不出来吗？”“这到底是什么？”“你说是啥？”“这到底是啥？”“这个是什么？”“这是什么鬼？”“这是什么玩意儿？”“这到底是个啥？”“这到底是个啥玩意儿？”\n————————————————————————————————————————\n最后更新：“你猜这个是什么？”“这是啥？”“这个你看不出来吗？”“这到底是什么？”“你说是啥？”“这到底是啥？”“这个是什么？”“这是什么鬼？”“这是什么玩意儿？”“这到底是个啥？”“这到底是个啥玩意儿？”\n————————————————————————————————————————\n**（我为什么写这么多，因为我就是想看能不能有人猜到我的回答是什么）**'}, 'logprobs': None, 'finish_reason': 'stop'}], 'usage': {'prompt_tokens': 4, 'total_tokens': 516, 'completion_tokens': 512}}

### Environment

```Shell
sys.platform: linux
Python: 3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA A100-SXM4-80GB
CUDA_HOME: /usr/local/cuda-11.7
NVCC: Cuda compilation tools, release 11.7, V11.7.64
GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
PyTorch: 2.1.0+cu118
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.16.0+cu118
LMDeploy: 0.4.1+
transformers: 4.40.1
gradio: 3.50.2
fastapi: 0.110.2
pydantic: 2.7.0
triton: 2.1.0
```

**Comment by AllentDan** [comment]
这是我们所期望的，并不是一个问题

**Comment by AllentDan** [comment]
我们的 profile_restful_api 目前还在用这个传 string 的能力测速。所以没有去掉这个功能
