### ISSUE TITLE
VLM中OpenAI 格式的输入如何设置多轮对话

### ISSUE THREAD

**Issue by thomas-yanxin** [InternLM/lmdeploy#1609]

**Comment by AllentDan** [comment]
```
curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "gpt-4-turbo",
    "messages": [
      {
        "role": "user",
        "content": [
          {
            "type": "text",
            "text": "What'\''s in this image?"
          },
          {
            "type": "image_url",
            "image_url": {
              "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg"
            }
          }
        ]
      }
    ],
    "max_tokens": 300
  }'
```
just like LLM, the only difference is that the user message may contain the following part:
```
          {
            "type": "image_url",
            "image_url": {
              "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg"
            }
          }
```

**Comment by AllentDan** [comment]
Please refer to https://platform.openai.com/docs/api-reference/chat/create for details.

**Comment by 2kxx** [comment]
多轮对话应该是存在之前的Q1A1的，如果使用OpenAI 格式进行batch对话如何保证上下文呢？

**Comment by 2kxx** [comment]
Hi！佬你跑通了吗，是把openai的格式文件放进去batch的conversation就行了吗？比如
conversation = []
message1 = {
        "role": "user",
        "content": []
    }
message1['content'].append({
        "type": "text",
        "text": f"What'\''s in this image?"
    })
    message1['content'].append({
        "type": "image_url",
        "image_url": {
            "url": f"{img_path}"
        }
    })
conversation.append(message1)
message2 = {
        "role": "user",
        "content": []
    }
message2['content'].append({
        "type": "text",
        "text": f"What'\''s in this image?"
    })
    message2['content'].append({
        "type": "image_url",
        "image_url": {
            "url": f"{img_path}"
        }
    })
conversation.append(message2)
response = pipe(conversation)
