### ISSUE TITLE
lmdeploy搭建的服务，是否支持通过传输stop_words的方式来控制模型输出

### ISSUE THREAD

**Issue by qiuxuezhe123** [InternLM/lmdeploy#1631]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

搭建服务：lmdeploy serve api_server
请求：基于openai的协议进行请求
client.chat.completions.create(model=model,messages=messages,functions=functions,stop=STOP_WORDS)

传入的STOP_WORDS没有生效

### Reproduction

无

### Environment

```Shell
lmdeploy：0.4.0
```

**Comment by lvhan028** [comment]
每个stop_word经过decode后，有几个token id呢？
目前 lmdeploy 只能支持单 token 的 stop_word

**Comment by qiuxuezhe123** [comment]
> 每个stop_word经过decode后，有几个token id呢？ 目前 lmdeploy 只能支持单 token 的 stop_word
加入的strop_word 经过decode后对应两个token id。

那如果我直接修改对模板中的stop_word能够生效吗？比如将下面的对话那边中的stop_words对应的值改为我们这边指定的stop word
![image](https://github.com/InternLM/lmdeploy/assets/65803222/2de2cd9f-1fde-4148-8977-ef13ae98491b)

**Comment by lvhan028** [comment]
只要它是一个token就行

**Comment by qiuxuezhe123** [comment]
> 只要它是一个token就行

好的，谢谢
