### ISSUE TITLE
Are there any plans to support CUDA 11.7?

### ISSUE THREAD

**Issue by dlin511** [InternLM/lmdeploy#1632]
### Motivation

Hi, currently there seems to only be support for CUDA 11.8 and 12. Currently our system only supports CUDA 11.7 which creates issues with the torch install. Does that mean that we currently cannot use lmdeploy?

**Comment by lvhan028** [comment]
Already did. The lmdeploy+cu118 package can be installed in the cuda 11.7 platform

**Comment by dlin511** [comment]
That is true, however, since it is compiled on Cuda 11.8, the torch version that it installs must also be compiled on Cuda 11.8 and the default installation is torch 2.2.2. However, we have to use a torch installation that is compiled with Cuda 11.7 to be able to run the models. It might be too specific of an error, but perhaps there are already existing workarounds? What do you think?

**Comment by lvhan028** [comment]
Can you build lmdeploy from the source?

**Comment by irexyc** [comment]
If your nvidia driver only support cuda 11.7, you may install this way:
```
export LMDEPLOY_VERSION=0.3.0
export PYTHON_VERSION=38
pip install https://github.com/InternLM/lmdeploy/releases/download/v${LMDEPLOY_VERSION}/lmdeploy-${LMDEPLOY_VERSION}+cu118-cp${PYTHON_VERSION}-cp${PYTHON_VERSION}-manylinux2014_x86_64.whl --extra-index-url https://download.pytorch.org/whl/cu117

# there exists torch-2.0.1+cu117 whl package which meets lmdeploy requirement.
```

After installation, you should check the version of  `'nvidia-nccl-cu11', 'nvidia-cuda-runtime-cu11', 'nvidia-cublas-cu11', 'nvidia-curand-cu11'` python packages and make sure the version is lower than your nvidia driver support.

**Comment by datalee** [comment]
你好，问一下：是不是最新版本也可以支持在11.7的cuda上安装？按照上面的安装流程

**Comment by lvhan028** [comment]
yes
