### ISSUE TITLE
[Bug] Two different tokenizers are used in benchmarks

### ISSUE THREAD

**Issue by ispobock** [InternLM/lmdeploy#1642]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

`profile_pipeline_api.py` uses tokenizer in transformers:
https://github.com/InternLM/lmdeploy/blob/01ea4dd6cd37aa53b6f6a9fba749339a3a34141b/benchmark/profile_pipeline_api.py#L64
`profile_restful_api.py` uses lmdeploy tokenizer:
https://github.com/InternLM/lmdeploy/blob/01ea4dd6cd37aa53b6f6a9fba749339a3a34141b/benchmark/profile_restful_api.py#L72

Different tokenizers will cause different sampled requests. Can we unify them to keep the benchmark results comparable?

### Reproduction

1. profile pipeline
```
python3 benchmark/profile_pipeline_api.py /workdir/ShareGPT_V3_unfiltered_cleaned_split.json /workdir/llama2_13b_chat -c 128 -n 1000
```
```
number of prompts: 1000
number of prompt tokens: 248339
number of completion tokens: 241582
token throughput (completion token): 1746.433 token/s
token throughput (prompt + completion token): 3541.714 token/s
RPS (request per second): 7.229 req/s
RPM (request per minute): 433.749 req/min
```
2. profile restful api
```
python3 benchmark/profile_restful_api.py --server_addr 0.0.0.0:23333 --tokenizer_path /workdir/llama2_13b_chat --dataset /workdir/ShareGPT_V3_unfiltered_cleaned_split.json --concurrency 128 --num_prompts 1000
```
```
number of prompt tokens: 244330
number of completion tokens: 239421
token throughput (completion token): 1644.485 token/s
token throughput (prompt + completion token): 3322.687 token/s
RPS (request per second): 6.869 req/s
RPM (request per minute): 412.115 req/min
```

We can see the `number of prompt tokens` is different for the two benchmarks, while the seed is the same.

**Comment by AllentDan** [comment]
Do you mean the `number of prompt tokens` will be the same when they use the same tokenizer class with the same seed?

**Comment by ispobock** [comment]
@AllentDan Yes. These two tokenizers have some diff in the tokenized result, which changed the sampled requests.

**Comment by AllentDan** [comment]
Fixed in the latest main.
