### ISSUE TITLE
Wonderful work!，请问有关于VLM类模型api_server的性能测试内容吗？

### ISSUE THREAD

**Issue by red-fox-yj** [InternLM/lmdeploy#1645]
### 📚 The doc issue

![image](https://github.com/InternLM/lmdeploy/assets/62475359/749182ac-fb3f-43d0-bbae-09c219ac0c40)
如题，我使用llava-1.5-13b模型，直接跑文档的[api_server 性能测试]报错
![image](https://github.com/InternLM/lmdeploy/assets/62475359/2d366f2b-ec5c-4e06-8061-e3f1507f1ccc)
[api_server 性能测试]是仅适用于纯语言模型吗，感激回复！

**Comment by lvhan028** [comment]
没错，api_sever 性能测试是只针对 llm 的。现在还没有 vlm serving的评测脚本，我们需要花些时间思考下怎么处理

**Comment by red-fox-yj** [comment]
> 没错，api_sever 性能测试是只针对 llm 的。现在还没有 vlm serving的评测脚本，我们需要花些时间思考下怎么处理

感谢回复，期待未来更多amazing的工作。
