### ISSUE TITLE
[QA] api传非https图片调用模型

### ISSUE THREAD

**Issue by ybshaw** [InternLM/lmdeploy#1653]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

使用openai调用模型时，图片的路径如果在本地，要怎么构造请求，使得图片可以上传到远程服务器进行处理，并输出

### Reproduction

no

### Environment

```Shell
linux
```

**Comment by red-fox-yj** [comment]
从业务的角度来讲也许可以在chat界面上传图片时就生成图片链接，然后前端整合图片链接再调用API_server的服务？这样或许可以避开这个问题。

**Comment by irexyc** [comment]
目前load_image的实现，如果是服务器的本地路径，应该也是可以的。

**Comment by LRHstudy** [comment]
可以将图像转成base64在上面传过去：

**Comment by LRHstudy** [comment]
可以将图像转成base64传过去：
with open(image_path, "rb") as image_file:
    image = "data:image/jpeg;base64," + base64.b64encode(image_file.read()).decode("utf-8")

**Comment by zhuyr97** [comment]
针对传非https图片的具体实现，将图像转成base64传上去，但是不同的格式不一样，下面的代码在image_to_base64函数部分自动对不同的类型进行了调整，请参考：

from lmdeploy.serve.openai.api_client import APIClient
import base64
from PIL import Image
import requests
from io import BytesIO

api_client = APIClient(f'http://0.0.0.0:xxx')
model_name = api_client.available_models[0]

def image_to_base64(image_path: str) -> str:
    """
    将本地图片转换为 base64 编码的字符串，并返回 data URL 形式。

    :param image_path: 本地图片路径
    :return: 包含 MIME 类型的 base64 编码的 data URL 字符串
    """
    # 打开本地图片文件
    with open(image_path, "rb") as image_file:
        # 读取图片内容
        image_data = image_file.read()
        # 将图片内容进行 base64 编码
        base64_encoded = base64.b64encode(image_data).decode('utf-8')

    # 获取图片的 MIME 类型
    mime_type = Image.open(image_path).get_format_mimetype()
    
    # 返回包含 MIME 类型的 data URL
    return f'data:{mime_type};base64,{base64_encoded}'

image_path = './examples/image1.jpg'
base64_image_url = image_to_base64(image_path)
#print(f'base64_image_url:{base64_image_url}')

# 定义一个消息字典，包含用户角色和内容。这里的消息内容是复合型的，既包括文本也包括一个图片URL。
# 文本部分请求模型描述图片，图片URL指向一个老虎的JPEG图像。
messages = [{ # 这个之后也就可以去concat之前的消息
    'role':
    'user',
    'content': [{  ## 内容数组，可以包含多个元素 (文本和图片) 
        'type': 'text',
        'text': 'Describe the image please, in english',
    }, {
        'type': 'image_url',
        'image_url': {
            'url':
            base64_image_url,
        },
    }]
}]
accumulated_content = ''

# 对于API客户端提供的chat_completions_v1方法进行迭代调用。
# 这个方法接收模型名称和消息列表作为参数，返回模型针对每条消息的回复。
# 这里假定API支持异步或流式返回，因此使用循环来迭代获取每一条回复。
for item in api_client.chat_completions_v1(model=model_name,
                                           messages=messages#  ,stream = True
                                          ):
    print(item)

**Comment by ybshaw** [comment]
> 针对传非https图片的具体实现，将图像转成base64传上去，但是不同的格式不一样，下面的代码在image_to_base64函数部分自动对不同的类型进行了调整，请参考：
> 
> from lmdeploy.serve.openai.api_client import APIClient import base64 from PIL import Image import requests from io import BytesIO
> 
> api_client = APIClient(f'http://0.0.0.0:xxx') model_name = api_client.available_models[0]
> 
> def image_to_base64(image_path: str) -> str: """ 将本地图片转换为 base64 编码的字符串，并返回 data URL 形式。
> 
> ```
> :param image_path: 本地图片路径
> :return: 包含 MIME 类型的 base64 编码的 data URL 字符串
> """
> # 打开本地图片文件
> with open(image_path, "rb") as image_file:
>     # 读取图片内容
>     image_data = image_file.read()
>     # 将图片内容进行 base64 编码
>     base64_encoded = base64.b64encode(image_data).decode('utf-8')
> 
> # 获取图片的 MIME 类型
> mime_type = Image.open(image_path).get_format_mimetype()
> 
> # 返回包含 MIME 类型的 data URL
> return f'data:{mime_type};base64,{base64_encoded}'
> ```
> 
> image_path = './examples/image1.jpg' base64_image_url = image_to_base64(image_path) #print(f'base64_image_url:{base64_image_url}')
> 
> messages = [{ # 这个之后也就可以去concat之前的消息 'role': 'user', 'content': [{ ## 内容数组，可以包含多个元素 (文本和图片) 'type': 'text', 'text': 'Describe the image please, in english', }, { 'type': 'image_url', 'image_url': { 'url': base64_image_url, }, }] }]
> 
> for item in api_client.chat_completions_v1(model=model_name, messages=messages ): print(item)

学到了
