### ISSUE TITLE
换用 LLM 基座的 LLaVA 模型适配

### ISSUE THREAD

**Issue by red-fox-yj** [InternLM/lmdeploy#1655]
### Motivation

您好，在我的业务中，我将经典 LLaVA 模型的基座 LLaMA 换成了其他的 LLM，如此，为了能够成功部署这个新的 LLaVA，我需要特别关注 LMDeploy 的哪部分源码呢？

**Comment by irexyc** [comment]
就目前的逻辑来说，LMDeploy 会根据 [config](https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/archs.py#L136-L146) 信息来判断该模型是什么类型。如果是 VLM 的话，LM 部分会经过一个[在线转化](https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/turbomind/turbomind.py#L223-L303)的过程进行加载，vision 模型会按照 config 中的 [arch](https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/vl/model/builder.py#L16-L45) 信息，调用相关的逻辑进行加载。

如果是以 LLaVA repo 为基础进行的训练，比如只是在 [language_model](https://github.com/haotian-liu/LLaVA/tree/main/llava/model/language_model) 中增加了新的基座，那么可以参考这个 [PR](https://github.com/InternLM/lmdeploy/pull/1579/files#diff-912a04d8ab5b3f99f090babdf3af22d38736b36052c081983ea46b736b1b2678) 中 lmdeploy 文件夹中文件的修改。

**Comment by red-fox-yj** [comment]
您好，我基于您的pr修改了部分代码，现在已经可以将我更换了基座的llava顺利部署上去，但是我在进行推理的时候发现模型回复的是一串无意义的文本，我在这方面还是新手，我应该如何进行调试呢？pipline推理日志如下：
`2024-06-24 09:18:24,394 - lmdeploy - INFO - Using turbomind engine
2024-06-24 09:19:46,657 - lmdeploy - INFO - input backend=turbomind, backend_config=None
2024-06-24 09:19:46,657 - lmdeploy - INFO - input chat_template_config=None
2024-06-24 09:19:46,658 - lmdeploy - INFO - matched chat template name: moss2
2024-06-24 09:19:46,659 - lmdeploy - INFO - start ImageEncoder._forward_loop
2024-06-24 09:19:46,766 - lmdeploy - INFO - updated chat_template_onfig=ChatTemplateConfig(model_name='moss2', system=None, meta_instruction=None, eosys=None, user=None, eoh=None, assistant=None, eoa=None, separator=None, capability=None, stop_words=None)
2024-06-24 09:19:48,003 - lmdeploy - WARNING - model_source: hf_model
2024-06-24 09:19:48,004 - lmdeploy - WARNING - model_name is deprecated in TurbomindEngineConfig and has no effect
2024-06-24 09:20:33,420 - lmdeploy - WARNING - model_config:

[llama]
model_name = XXX
tensor_para_size = 1
head_num = 16
kv_head_num = 8
vocab_size = 137728
num_layer = 32
inter_size = 8192
norm_eps = 1e-05
attn_bias = 0
start_id = 1
end_id = 2
session_len = 32776
weight_type = bf16
rotary_embedding = 128
rope_theta = 1000000.0
size_per_head = 128
group_size = 0
max_batch_size = 128
max_context_token_num = 1
step_length = 1
cache_max_entry_count = 0.8
cache_block_seq_len = 64
cache_chunk_size = -1
enable_prefix_caching = False
num_tokens_per_iter = 0
max_prefill_iters = 1
extra_tokens_per_iter = 0
use_context_fmha = 1
quant_policy = 0
max_position_embeddings = 32768
rope_scaling_factor = 2.0
use_dynamic_ntk = 1
use_logn_attn = 0
lora_policy = 
lora_r = 0
lora_scale = 0.0
lora_max_wo_r = 0
lora_rank_pattern = 
lora_scale_pattern = 


[TM][INFO] Set logger level by INFO
[TM][WARNING] [LlamaTritonModel] `max_context_token_num` = 32776.
[TM][WARNING] [LlamaTritonModel] `num_tokens_per_iter` is not set, default to `max_context_token_num` (32776).
[TM][INFO] Set logger level by INFO
2024-06-24 09:20:33,941 - lmdeploy - WARNING - get 227 model params
2024-06-24 09:20:50,155 - lmdeploy - WARNING - The token <|im_end|>, its length of indexes [63, 127, 1557, 11896, 127, 65] is over than 1. Currently, it can not be used as stop words                                                                               
2024-06-24 09:20:50,155 - lmdeploy - WARNING - The token <|action_end|>, its length of indexes [63, 127, 53913, 4650, 127, 65] is over than 1. Currently, it can not be used as stop words
2024-06-24 09:20:50,155 - lmdeploy - WARNING - The token <|end_of_moss|>, its length of indexes [63, 127, 4650, 11940, 5047, 118, 127, 65] is over than 1. Currently, it can not be used as stop words
2024-06-24 09:20:50,190 - lmdeploy - INFO - updated backend_config=TurbomindEngineConfig(model_name='moss2', model_format=None, tp=1, session_len=None, max_batch_size=128, cache_max_entry_count=0.8, cache_block_seq_len=64, enable_prefix_caching=False, quant_policy=0, rope_scaling_factor=0.0, use_logn_attn=False, download_dir=None, revision=None, max_prefill_token_num=8192, num_tokens_per_iter=0, max_prefill_iters=1)
[TM][INFO] Set logger level by INFO
[WARNING] gemm_config.in is not found; using default GEMM algo
[TM][INFO] NCCL group_id = 0
[TM][INFO] [BlockManager] block_size = 8 MB
[TM][INFO] [BlockManager] max_block_count = 7499
[TM][INFO] [BlockManager] chunk_size = 7499
[TM][INFO] LlamaBatch<T>::Start()
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
2024-06-24 09:20:51,274 - lmdeploy - INFO - prompt='<|im_start|>system\nYou are an AI assistant.<|end_of_system|>\n<|im_start|>user\nHi<|end_of_user|>\n<|im_start|>assistant\n', gen_config=EngineGenerationConfig(n=1, max_new_tokens=512, top_p=0.8, top_k=40, temperature=0.8, repetition_penalty=1.0, ignore_eos=False, random_seed=10732750680167730169, stop_words=[], bad_words=None, min_new_tokens=None, skip_special_tokens=True, logprobs=None), prompt_token_id=[1, 63, 127, 1557, 28173, 127, 65, 30829, 13, 64408, 4340, 665, 90949, 25081, 70983, 999, 1165, 560, 48, 35, 999, 1165, 24035, 112698, 1442, 70642, 24231, 61316, 124819, 73, 1722, 1444, 99541, 43, 115264, 478, 63, 127, 4650, 11940, 30829, 127, 630, 63, 127, 1557, 28173, 127, 65, 14091, 13, 902, 63, 127, 4650, 11940, 14091, 127, 630, 63, 127, 1557, 28173, 127, 65, 75492, 13], adapter_name=None.
2024-06-24 09:20:51,274 - lmdeploy - INFO - session_id=0, history_tokens=0, input_tokens=67, max_new_tokens=512, seq_start=True, seq_end=True, step=0, prep=True
[TM][INFO] Set logger level by INFO
[TM][INFO] [forward] Enqueue requests
[TM][INFO] [forward] Wait for requests to complete ...
[TM][INFO] Set logger level by INFO
[TM][WARNING] [ProcessInferRequests] Request for 0 received.
[TM][INFO] [Forward] [0, 1), dc_bsz = 0, pf_bsz = 1, n_tok = 67, max_q = 67, max_k = 67
[TM][INFO] Set logger level by INFO
[TM][INFO] ------------------------- step = 70 -------------------------
[TM][INFO] ------------------------- step = 80 -------------------------
[TM][INFO] ------------------------- step = 90 -------------------------
[TM][INFO] ------------------------- step = 100 -------------------------
[TM][INFO] ------------------------- step = 110 -------------------------
[TM][INFO] ------------------------- step = 120 -------------------------
[TM][INFO] ------------------------- step = 130 -------------------------
[TM][INFO] ------------------------- step = 140 -------------------------
[TM][INFO] ------------------------- step = 150 -------------------------
[TM][INFO] ------------------------- step = 160 -------------------------
[TM][INFO] ------------------------- step = 170 -------------------------
[TM][INFO] ------------------------- step = 180 -------------------------
[TM][INFO] ------------------------- step = 190 -------------------------
[TM][INFO] ------------------------- step = 200 -------------------------
[TM][INFO] ------------------------- step = 210 -------------------------
[TM][INFO] ------------------------- step = 220 -------------------------
[TM][INFO] ------------------------- step = 230 -------------------------
[TM][INFO] ------------------------- step = 240 -------------------------
[TM][INFO] ------------------------- step = 250 -------------------------
[TM][INFO] ------------------------- step = 260 -------------------------
[TM][INFO] ------------------------- step = 270 -------------------------
[TM][INFO] ------------------------- step = 280 -------------------------
[TM][INFO] ------------------------- step = 290 -------------------------
[TM][INFO] ------------------------- step = 300 -------------------------
[TM][INFO] ------------------------- step = 310 -------------------------
[TM][INFO] ------------------------- step = 320 -------------------------
[TM][INFO] ------------------------- step = 330 -------------------------
[TM][INFO] ------------------------- step = 340 -------------------------
[TM][INFO] ------------------------- step = 350 -------------------------
[TM][INFO] ------------------------- step = 360 -------------------------
[TM][INFO] ------------------------- step = 370 -------------------------
[TM][INFO] ------------------------- step = 380 -------------------------
[TM][INFO] ------------------------- step = 390 -------------------------
[TM][INFO] ------------------------- step = 400 -------------------------
[TM][INFO] ------------------------- step = 410 -------------------------
[TM][INFO] ------------------------- step = 420 -------------------------
[TM][INFO] ------------------------- step = 430 -------------------------
[TM][INFO] ------------------------- step = 440 -------------------------
[TM][INFO] ------------------------- step = 450 -------------------------
[TM][INFO] ------------------------- step = 460 -------------------------
[TM][INFO] ------------------------- step = 470 -------------------------
[TM][INFO] ------------------------- step = 480 -------------------------
[TM][INFO] ------------------------- step = 490 -------------------------
[TM][INFO] ------------------------- step = 500 -------------------------
[TM][INFO] ------------------------- step = 510 -------------------------
[TM][INFO] ------------------------- step = 520 -------------------------
[TM][INFO] ------------------------- step = 530 -------------------------
[TM][INFO] ------------------------- step = 540 -------------------------
[TM][INFO] ------------------------- step = 550 -------------------------
[TM][INFO] ------------------------- step = 560 -------------------------
[TM][INFO] ------------------------- step = 570 -------------------------
[TM][INFO] [Interrupt] slot = 0, id = 0
[TM][INFO] [forward] Request complete for 0, code 0
[Response(text=' flip输出 flip flip资源资源 flip flip配对输出资源 flip波斯 flip flip价值观 flip flip flip推送 flip flip flip flip flip资源 flip价值观 flip flip flip价值观输出 flip fingerprints资源波斯 flip flip flip flip flip推送 flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip波斯价值观 flip打破 flip flip价值观 flip资源资源 flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip资源 flip flip资源波斯 flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip价值观 flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip资源 flip flip资源 flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip价值观 flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip资源 flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip资源 flip flip flip flip flip flip flip flip flip资源 flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip资源 flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip资源 flip flip flip flip flip flip flip flip flip flip flip flip flip flip资源价值观 flip flip flip flip flip flip flip flip flip flip flip资源 flip flip flip flip flip flip flip flip flip flip flip flip价值观 flip flip flip flip flip flip价值观 flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip价值观 flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip价值观 flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip价值观 flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip价值观 flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip flip价值观 flip flip flip flip flip flip flip flip', generate_token_len=513, input_token_len=67, session_id=0, finish_reason='length', token_ids=[15835, 45248, 15835, 15835, 44904, 44904, 15835, 15835, 45809, 45248, 44904, 15835, 41028, 15835, 15835, 79749, 15835, 15835, 15835, 39171, 15835, 15835, 15835, 15835, 15835, 44904, 15835, 79749, 15835, 15835, 15835, 79749, 45248, 15835, 120388, 44904, 41028, 15835, 15835, 15835, 15835, 15835, 39171, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 41028, 79749, 15835, 38640, 15835, 15835, 79749, 15835, 44904, 44904, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 44904, 15835, 15835, 44904, 41028, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 79749, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 44904, 15835, 15835, 44904, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 79749, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 44904, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 44904, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 44904, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 44904, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 44904, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 44904, 79749, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 44904, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 79749, 15835, 15835, 15835, 15835, 15835, 15835, 79749, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 79749, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 79749, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 79749, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 79749, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 79749, 15835, 15835, 15835, 15835, 15835, 15835, 15835, 15835], logprobs=None)]
[TM][INFO] ~LlamaBatch()
[TM][INFO] [InternalThreadEntry] stop requested.
[TM][INFO] [OutputThreadEntry] stop requested.
`
我的基座模型和经典的llama在模型结构上有所不同：
经典llama
`LlavaLlamaForCausalLM(
  (model): LlavaLlamaModel(
    (embed_tokens): Embedding(32000, 4096, padding_idx=0)
    (layers): ModuleList(
      (0-31): 32 x LlamaDecoderLayer(
        (self_attn): LlamaSdpaAttention(
          (**q_proj**): Linear(in_features=4096, out_features=4096, bias=False)
          (**k_proj**): Linear(in_features=4096, out_features=4096, bias=False)
          (**v_proj**): Linear(in_features=4096, out_features=4096, bias=False)
          (**o_proj**): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
    )
    (norm): LlamaRMSNorm()
    (vision_tower): CLIPVisionTower(
      (vision_tower): CLIPVisionModel(
        (vision_model): CLIPVisionTransformer(
          (embeddings): CLIPVisionEmbeddings(
            (patch_embedding): Conv2d(3, 1024, kernel_size=(14, 14), stride=(14, 14), bias=False)
            (position_embedding): Embedding(577, 1024)
          )
          (pre_layrnorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (encoder): CLIPEncoder(
            (layers): ModuleList(
              (0-23): 24 x CLIPEncoderLayer(
                (self_attn): CLIPAttention(
                  (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
                  (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
                  (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
                  (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
                )
                (layer_norm1): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
                (mlp): CLIPMLP(
                  (activation_fn): QuickGELUActivation()
                  (fc1): Linear(in_features=1024, out_features=4096, bias=True)
                  (fc2): Linear(in_features=4096, out_features=1024, bias=True)
                )
                (layer_norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
              )
            )
          )
          (post_layernorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
    )
    (mm_projector): Sequential(
      (0): Linear(in_features=1024, out_features=4096, bias=True)
      (1): GELU(approximate='none')
      (2): Linear(in_features=4096, out_features=4096, bias=True)
    )
  )
  (lm_head): Linear(in_features=4096, out_features=32000, bias=False)
)`
我的基座模型
`LlavaXXXXForCausalLM(
  (model): LlavaXXXXModel(
    (tok_embeddings): Embedding(137728, 2048, padding_idx=2)
    (layers): ModuleList(
      (0-31): 32 x XXXXDecoderLayer(
        (attention): XXXXAttention(
          (**wqkv**): Linear(in_features=2048, out_features=4096, bias=False)
          (wo): Linear(in_features=2048, out_features=2048, bias=False)
          (rotary_emb): XXXXDynamicNTKScalingRotaryEmbedding()
        )
        (feed_forward): XXXXMLP(
          (w1): Linear(in_features=2048, out_features=8192, bias=False)
          (w3): Linear(in_features=2048, out_features=8192, bias=False)
          (w2): Linear(in_features=8192, out_features=2048, bias=False)
          (act_fn): SiLU()
        )
        (attention_norm): XXXXRMSNorm()
        (ffn_norm): XXXXRMSNorm()
      )
    )
    (norm): XXXXRMSNorm()
    (vision_tower): CLIPVisionTower()
    (mm_projector): Sequential(
      (0): Linear(in_features=1024, out_features=2048, bias=True)
      (1): GELU(approximate='none')
      (2): Linear(in_features=2048, out_features=2048, bias=True)
    )
  )
  (output): Linear(in_features=2048, out_features=137728, bias=False)
)`
如上所见主要区别是注意力层的wqkv定义，我的模型关于wqkv是这样定义的：
`self.wqkv = nn.Linear(
            self.hidden_size,
            (self.num_heads + 2 * self.num_key_value_heads) * self.head_dim,
            bias=config.bias,
        )`
为了适应这样的模型结构，我特别修改了lmdeploy/lmdeploy/turbomind/deploy/target_model/fp.py的export_transformer_block方法，具体修改如下：
`def export_transformer_block(self, bin: BaseReader, i: int):
        """Export transformer layer i."""
        assert bin.start_layer_id <= i < bin.end_layer_id
        tp = self.cfg.tensor_para_size
        size_per_head = self.cfg.size_per_head
        # attn
        wqkv, wo = bin.attn(i)
        wqkv, wo = transpose_tensor([wqkv, wo])
        # split wqkv
        wq, wk, wv = split_qkv(wqkv, 16, 8, 128)
        wq = permute(wq, size_per_head)
        wk = permute(wk, size_per_head)
        qkv_w = merge_qkv(wq, wk, wv, tp, dim=2)
        self.save_split(qkv_w, f'layers.{i}.attention.w_qkv.weight', -1)
        self.save_split(wo, f'layers.{i}.attention.wo.weight', 0)
        bqkv, bo = bin.attn_bias(i)
        if bqkv is not None:
            bqkv, bo = transpose_tensor([bqkv, bo])
            bq, bk, bv = split_qkv(bqkv, 16, 8, 128)
            bq = permute(bq, size_per_head)
            bk = permute(bk, size_per_head)
            qkv_b = merge_qkv(bq, bk, bv, tp, dim=1)
            self.save_split(qkv_b, f'layers.{i}.attention.w_qkv.bias', -1)
            self.save_split(bo, f'layers.{i}.attention.wo.bias', copy=True)
        # ffn
        w1, w3, w2 = bin.ffn(i)
        w1, w3, w2 = transpose_tensor([w1, w3, w2])
        self.save_split(w1, f'layers.{i}.feed_forward.w1.weight', -1)
        self.save_split(w3, f'layers.{i}.feed_forward.w3.weight', -1)
        self.save_split(w2, f'layers.{i}.feed_forward.w2.weight', 0)
        # norm
        attn_norm = bin.attn_norm(i)
        ffn_norm = bin.ffn_norm(i)
        self.save_split(attn_norm, f'layers.{i}.attention_norm.weight')
        self.save_split(ffn_norm, f'layers.{i}.ffn_norm.weight')

def split_qkv(wqkv, num_heads, num_key_value_heads, head_dim):
    # 拆分矩阵为 Q、K、V
    qw, kw, vw = torch.split(wqkv, [num_heads*head_dim, num_key_value_heads*head_dim, num_key_value_heads*head_dim], dim=1)
    # 保证内存上连续
    qw = qw.contiguous()
    kw = kw.contiguous()
    vw = vw.contiguous()

    return qw, kw, vw
`
其他关于模型参数名字的适配修改我就不一一列出了。为了定位这个问题我有看过pipline推理时候的数据流代码，在转换模型格式为turbomid之后我看不到需要特别进行修改的代码，因此我猜测问题还是很有可能出现在关于这个模型结构的适配上。希望您可以给出一些建议，感激不尽！

**Comment by irexyc** [comment]
> 如上所见主要区别是注意力层的wqkv定义，我的模型关于wqkv是这样定义的：
```
self.wqkv = nn.Linear(
            self.hidden_size,
            (self.num_heads + 2 * self.num_key_value_heads) * self.head_dim,
            bias=config.bias,
        )
```

类似internlm2的结构么？可以参考一下这个文件 https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/turbomind/deploy/source_model/internlm2.py

**Comment by red-fox-yj** [comment]
@irexyc @lvhan028 感谢回复，服务已经成功启动和推理，期待未来更加wonderful的工作！

**Comment by red-fox-yj** [comment]
@irexyc @lvhan028 感谢回复，服务已经成功启动和推理，期待未来更加wonderful的工作！
