### ISSUE TITLE
[Bug] WSL2环境下，0.4.2做InternVL量化时，磁盘写入速度极低

### ISSUE THREAD

**Issue by ysyx2008** [InternLM/lmdeploy#1667]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

![图片](https://github.com/InternLM/lmdeploy/assets/11251894/ffd76bbf-6807-442f-bd4e-cdb5005ea450)

如上图……量化过程应该基本完成了，但SSD活动率100%，写入速度却极低。

Disk 3/4 是个二合一的Windows跨区卷。

### Reproduction

lmdeploy lite auto_awq /home/yushen/ai/InternVL-Chat-V1-5 --work-dir InternVL-Chat-V1-5-Int4

### Environment

```Shell
Windows11
WSL2
Ubuntu 20.04

目前进程死锁中无法运行脚本，其他信息后续补充
```

**Comment by AllentDan** [comment]
我们存模型用的 huggingface transformers 的 save_pretrained.

**Comment by irexyc** [comment]
@ysyx2008  

hi，请问你的机器上是有两个卡么？可以帮忙验证一下 WSL2 环境下，TP=2模型可以正常推理么？

**Comment by lijing1996** [comment]
你量化之后的输出结果正常嘛？我会输出来很多im_end

**Comment by AllentDan** [comment]
结果正常，你可以试试 https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5-AWQ

**Comment by AllentDan** [comment]
都用的默认参数

**Comment by ysyx2008** [comment]
> @ysyx2008
> 
> hi，请问你的机器上是有两个卡么？可以帮忙验证一下 WSL2 环境下，TP=2模型可以正常推理么？

很遗憾啊， 发生这个问题之后我的硬盘挂了……我估计是SSD的质量问题，不是软件的问题。

损失不小，至今WSL环境都没时间重建。
