### ISSUE TITLE
[Feature] health endpoint

### ISSUE THREAD

**Issue by pseudotensor** [InternLM/lmdeploy#1673]
### Motivation

Common to check health, easy to add /health endpoint so one can check status of endpoint.

**Comment by AllentDan** [comment]
Would you kindly help to pull a merge request to support it?

**Comment by pseudotensor** [comment]
It would take so many steps for such a small number of lines of code, but this is what you'd add for a fastAPI case:

```
@app.get("/health")
async def health() -> Response:
    """Health check."""
    return Response(status_code=200)
```
