### ISSUE TITLE
总是看到一个using default GEMM algo的WARNING，是否会因为使用了默认的GEMM而影响速度或者吞吐量？

### ISSUE THREAD

**Issue by lzcchl** [InternLM/lmdeploy#1680]
如题，如果使用其他配置能够进行加速之类的，那么应该如何操作一下呢？

![1716968908162](https://github.com/InternLM/lmdeploy/assets/34515022/fb875170-01be-43fa-aaf1-09b96e419e4e)

**Comment by lzhangzz** [comment]
影响不大，最多 3% 的样子
