### ISSUE TITLE
[Bug] 下载代码执行internvl-v1.5量化，导入本地模型时报错

### ISSUE THREAD

**Issue by qingchunlizhi** [InternLM/lmdeploy#1681]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

下载代码执行internvl-v1.5量化，导入本地模型时报下面错误：
Traceback (most recent call last):
  File "/lmdeploy/lmdeploy/lite/apis/auto_awq.py", line 83, in <module>
    auto_awq(
  File "/lmdeploy/lmdeploy/lite/apis/auto_awq.py", line 57, in auto_awq
    model, tokenizer, work_dir = calibrate(model, calib_dataset, calib_samples,
  File "/lmdeploy/./lmdeploy/lite/apis/calibrate.py", line 149, in calibrate
    model = load_hf_from_pretrained(model,
  File "/lmdeploy/./lmdeploy/lite/utils/load.py", line 31, in load_hf_from_pretrained
    model = AutoModelForCausalLM.from_pretrained(
  File "/root/miniconda3/envs/internvl/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 569, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.InternVL-Chat-V1-5.configuration_internvl_chat.InternVLChatConfig'> for this kind of AutoModel: AutoModelForCausalLM.
Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, LlamaConfig, CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, FalconConfig, FuyuConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MistralConfig, MixtralConfig, MptConfig, MusicgenConfig, MvpConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PersimmonConfig, PhiConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, Qwen2Config, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, TransfoXLConfig, TrOCRConfig, WhisperConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.

### Reproduction

-

### Environment

```Shell
-
```

**Comment by lvhan028** [comment]
麻烦提供下完整的复现代码。

btw, 我们把量化后的模型已经传到了huggingface，可以直接下载使用。模型和用法都在下面的链接中
https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5-AWQ

**Comment by qingchunlizhi** [comment]
用源码做量化时，模型路径用本地路径就会出现这个问题。主要是load.py的这一行：
`model = AutoModelForCausalLM.from_pretrained(pretrained_model_name_or_path, config=hf_config, **kwargs)`
如果用AutoModel 替换 AutoModelForCausalLM可以加载模型成功。但是模型的type是internvl-chat，后面的映射又会报错。

我发现直接用pip安装lmdeploy执行下面语句是可以导入本地模型的：
`lmdeploy lite auto_awq /models/InternVL-Chat-V1-5 --work-dir /models/InternVL-Chat-V1-5-AWQ`
但是pip包的ptb数据是写死从huggingface上下载的，国内很多电脑不能直接下载，所以我才改了下源码来做量化。您有什么思路处理我上面源码量化遇到的问题吗？

**Comment by qingchunlizhi** [comment]
> 用源码做量化时，模型路径用本地路径就会出现这个问题。主要是load.py的这一行： `model = AutoModelForCausalLM.from_pretrained(pretrained_model_name_or_path, config=hf_config, **kwargs)` 如果用AutoModel 替换 AutoModelForCausalLM可以加载模型成功。但是模型的type是internvl-chat，后面的映射又会报错。
> 
> 我发现直接用pip安装lmdeploy执行下面语句是可以导入本地模型的： `lmdeploy lite auto_awq /models/InternVL-Chat-V1-5 --work-dir /models/InternVL-Chat-V1-5-AWQ` 但是pip包的ptb数据是写死从huggingface上下载的，国内很多电脑不能直接下载，所以我才改了下源码来做量化。您有什么思路处理我上面源码量化遇到的问题吗？

可以支持下量化数据本地导入吗？我看也有其它人遇到我这个问题

**Comment by AllentDan** [comment]
改数据集为啥要改模型加载？感觉数据集本地导入或者解决下载网络的问题可以安排下

**Comment by qingchunlizhi** [comment]
> 改数据集为啥要改模型加载？感觉数据集本地导入或者解决下载网络的问题可以安排下

我的模型也是本地加载的，主要还是网络问题。辛苦安排下：数据集本地导入或者解决下载网络的问题
谢谢！

**Comment by AllentDan** [comment]
还是那个问题，数据集设置应该不用改模型加载的，现在的代码支持本地模型。

**Comment by qingchunlizhi** [comment]
> 还是那个问题，数据集设置应该不用改模型加载的，现在的代码支持本地模型。

纠正一下：只改了数据集从本地加载，模型加载的代码不改，然后传入本地模型路径会在这一行报我上面说的错误：
`model = AutoModelForCausalLM.from_pretrained(pretrained_model_name_or_path, config=hf_config, **kwargs)`
您也可以直接试下，直接执行上面这一行代码导入不了internvl的模型，internvl模型好像是用AutoModel导入的

**Comment by AllentDan** [comment]
你这是用的老代码，v0.4.2 才支持的 vl 模型量化

**Comment by qingchunlizhi** [comment]
> 你这是用的老代码，v0.4.2 才支持的 vl 模型量化
https://github.com/InternLM/lmdeploy/blob/54b7230b4ca08b37b85e5f6e1960e2445dca5288/lmdeploy/lite/utils/load.py#L31
我拉了最新代码的，你看代码中加载模型用的就是AutoModelForCausalLM

**Comment by AllentDan** [comment]
请确保代码正确，VL 模型不会走上面的代码加载。https://github.com/InternLM/lmdeploy/blob/54b7230b4ca08b37b85e5f6e1960e2445dca5288/lmdeploy/lite/apis/calibrate.py#L181

**Comment by qingchunlizhi** [comment]
> 请确保代码正确，VL 模型不会走上面的代码加载。
> 
> https://github.com/InternLM/lmdeploy/blob/54b7230b4ca08b37b85e5f6e1960e2445dca5288/lmdeploy/lite/apis/calibrate.py#L181
抱歉，确实是我git pull的版本有问题
