### ISSUE TITLE
[Bug] output diff when temperature set zero

### ISSUE THREAD

**Issue by zhyncs** [InternLM/lmdeploy#1688]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

I used the latest code from LMDeploy to run the vicuna 13b model. The client used temperature 0 and made two requests, resulting in some differences in the output.

Theoretically, when the temperature is 0, multiple requests should yield consistent results without any differences.

### Reproduction

- modified in `benchmark/profile_restful_api.py`
```python3
import hashlib

def text_to_sha256(text):
    text_bytes = text.encode('utf-8')
    sha256_hash = hashlib.sha256()
    sha256_hash.update(text_bytes)
    hash_digest = sha256_hash.hexdigest()
    return hash_digest
```

```python3
    def _inference(self, req_queue: Queue, res_queue: Queue, session_id: int,
                   stream_output: bool):

        stats = []
        client = APIClient(self.server_addr, api_key=self.api_key)

        for prompt, input_seqlen, output_seqlen in iter(
                req_queue.get, [None, None, None]):
            timestamps = []
            timestamps.append(time.perf_counter())
            for output in client.chat_completions_v1(
                    model=self.model_name,
                    messages=prompt,
                    temperature=self.temperature,
                    top_p=self.top_p,
                    n=1,
                    max_tokens=output_seqlen,
                    stream=stream_output,
                    session_id=session_id,
                    ignore_eos=True):
                timestamps.append(time.perf_counter())
            print(text_to_sha256(output['choices'][0]['message']['content']))
```

- results reproduction
```bash
# server
python3 -m lmdeploy serve api_server /workdir/vicuna-13b-v1.3

# client first try
python3 benchmark/profile_restful_api.py 127.0.0.1:23333 /workdir/vicuna-13b-v1.3 /workdir/ShareGPT_V3_unfiltered_cleaned_split.json --concurrency 128 --num_prompts 128 --temperature 0 | tee first

# client second try
python3 benchmark/profile_restful_api.py 127.0.0.1:23333 /workdir/vicuna-13b-v1.3 /workdir/ShareGPT_V3_unfiltered_cleaned_split.json --concurrency 128 --num_prompts 128 --temperature 0 | tee second

# only keep the hash results and sort
sort first -o first_output
sort second -o second_output

# compare and find the diff
icdiff first_output second_output
```

### Environment

```Shell
sys.platform: linux
Python: 3.9.16 (main, Aug 15 2023, 19:38:56) [GCC 8.3.1 20190311 (Red Hat 8.3.1-3)]
CUDA available: True
GPU 0,1: NVIDIA A100-SXM4-80GB
GCC: gcc (GCC) 10.2.1 20210130 (Red Hat 10.2.1-11)
PyTorch: 2.3.0+cu118
LMDeploy: 0.4.2+e6468e7
triton: 2.3.0
```

**Comment by lzhangzz** [comment]
You may need to set `top_k = 1` and a fixed random seed to stop sampling because we don't have an alternative argmax kernel to bypass sampling.

Also, as split-kv is taking effect automatically, variable batch size and sequence length at runtime may result in different split-kv factor. This will lead to differnt accumulation order and thus differnt outcome.

**Comment by zhyncs** [comment]
> You may need to set `top_k = 1` and a fixed random seed to stop sampling because we don't have an alternative argmax kernel to bypass sampling.

In the `benchmark/profile_restful_api.py`, the seed is default 0 and top_p is default 1.
https://github.com/InternLM/lmdeploy/blob/21be189628d064931edc5f166ee00f61c8fb1412/benchmark/profile_restful_api.py#L226
https://github.com/InternLM/lmdeploy/blob/21be189628d064931edc5f166ee00f61c8fb1412/benchmark/profile_restful_api.py#L67

Do I still need to set `top_k = 1`?

> Also, as split-kv is taking effect automatically, variable batch size and sequence length at runtime may result in different split-kv factor. This will lead to differnt accumulation order and thus differnt outcome.

In terms of design and implementation, do we have to ensure that when temperature is 0, under batch inference, the results of the two requests are completely consistent?

**Comment by zhyncs** [comment]
TurboMind will support `do_sample` sampling parameter ref https://github.com/InternLM/lmdeploy/pull/1966
