### ISSUE TITLE
After I deploy it with 'bash workspace/service_docker_up.sh' how may I call it on other python code?

### ISSUE THREAD

**Issue by Kunlun-Zhu** [InternLM/lmdeploy#169]
I would like to use this deployment as a server that all python code could call it as an api. Is it possible to do that? Thanks a lot!

**Comment by lvhan028** [comment]
You can try the API in `lmdeploy/serve/turbomind/chatbot.py`. 
`lmdeploy/serve/client.py` is an example about how to use the API
