### ISSUE TITLE
[Feature] InternVL-Chat-V1-5-AWQ merge LoRA adapter

### ISSUE THREAD

**Issue by isongxw** [InternLM/lmdeploy#1691]
### Motivation

作者你好，我利用InternVL库用私有数据集对InternVL-Chat-V1-5进行了LoRA Finetune，效果不错，但是推理较慢。InternVL-Chat-V1-5-AWQ 对推理速度进行了优化，我尝试用Transformers库加载InternVL-Chat-V1-5-AWQ模型然后合并LoRA adapter，但是会有权重不匹配的问题。

请问如何将InternVL-Chat-V1-5-AWQ与LoRA adapter进行权重合并？

**Comment by AllentDan** [comment]
更合理的方式应该是量化前合并权重，然后再用 lmdeploy 量化推理。

**Comment by isongxw** [comment]
> 更合理的方式应该是量化前合并权重，然后再用 lmdeploy 量化推理。

可以提供

> 更合理的方式应该是量化前合并权重，然后再用 lmdeploy 量化推理。

感谢回复，请问LMdeploy可以对合并后的权重进行AWQ量化推理吗？是不是需要合并权重后进行AWQ量化之后得到AWQ权重然后再使用LMDeploy进行推理？

**Comment by AllentDan** [comment]
Hi, @isongxw 之前没有尝试过，不过目前lmdeploy 只量化 llama 的部分，如果合并权重后模型结构没改变的话应该是可行的。如果过程中有什么问题，可以提出来。
