### ISSUE TITLE
[Feature] lmdeploy通过命令行可以启动一个gradio应用，这个gradio的应用是不是可以给用户提供UI修改的方法？

### ISSUE THREAD

**Issue by kaiwang0112006** [InternLM/lmdeploy#1710]
### Motivation

如果想用lmdeploy的能力（kv cache....），提供一个大模型应用，需要先启动一个lmdeploy server，再构建一个应用调用fastapi的接口，如果能直接启动一个应用，能定制化的话，这个过程可以被简化。

**Comment by lvhan028** [comment]
lmdeploy 支持 gradio，这里有一份文档 https://lmdeploy.readthedocs.io/en/latest/serving/gradio.html
可以修改 app.py 添加自己想要的 UI 元素
不过，我理解改 UI 这块属于 gradio 的范畴

**Comment by kaiwang0112006** [comment]
> lmdeploy 支持 gradio，这里有一份文档 https://lmdeploy.readthedocs.io/en/latest/serving/gradio.html 可以修改 app.py 添加自己想要的 UI 元素 不过，我理解改 UI 这块属于 gradio 的范畴

lmdeploy serve gradio {model_path}  直接启动gradio的服务，这个服务对应的gradio的app.py文件在哪里呢，用户如果想改UI得找到这个app.py

**Comment by lvhan028** [comment]
https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/serve/gradio/app.py
