### ISSUE TITLE
[Feature] Make torchvision optional

### ISSUE THREAD

**Issue by zhyncs** [InternLM/lmdeploy#1717]
### Motivation

Since v0.4.2, `torchvision` has been introduced into the LMDeploy runtime because it is used in VLMs. 
https://github.com/InternLM/lmdeploy/blob/54b7230b4ca08b37b85e5f6e1960e2445dca5288/requirements/runtime.txt#L16-L18
For some users, like me who might only want to use LLM, theoretically I have no dependency on `torchvision`. But currently, due to the Python code relying on `torchvision`, even if I only use LLM inference, I am still required to install `torchvision`. 
https://github.com/InternLM/lmdeploy/blob/aa8f7d17ec2abc968241cad32070b27eb315d472/lmdeploy/vl/model/cogvlm.py#L6-L8
https://github.com/InternLM/lmdeploy/blob/aa8f7d17ec2abc968241cad32070b27eb315d472/lmdeploy/vl/model/internvl.py#L112-L127
This is not very user-friendly as **the dependencies increase** and this particular **dependency also has a large binary size**. Could you consider making it optional? Thanks. @lvhan028 @irexyc @grimoire @AllentDan

**Comment by lvhan028** [comment]
Hi, @zhyncs 
I've been noted about this issue
The related PR is https://github.com/InternLM/lmdeploy/pull/1714

The reason we put torchvision into runtime.txt is some VLMs require it. 
If we leave users to install torchvision, I am afraid they will suffer the mismatch problem. 

So, I've decided to lazy import the VL module in lmdeploy as mentioned in #1714

**Comment by zhyncs** [comment]
> I've decided to lazy import the VL module in lmdeploy

make sense
