### ISSUE TITLE
[Bug] internlm2-chat-1_8b模型使用4bit KV量化的时候找不到key_stats.pth

### ISSUE THREAD

**Issue by jxfruit** [InternLM/lmdeploy#1720]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

我出现如题所示的问题，模型文件都是用modelscope下载的，但是没有在这个模型文件夹下面找到这个pth的文件，请问下可以在哪里获取这个文件呢

### Reproduction

lmdeploy serve api_server ./internlm2-chat-1_8b/ --server-name 0.0.0.0 --server-port 23333 --max-batch-size 64 --tp 1 --quant-policy 4

### Environment

```Shell
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce GTX 1660 SUPER
CUDA_HOME: None
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 2.1.2
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_90,code=sm_90;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.16.2
LMDeploy: 0.3.0+
transformers: 4.38.2
gradio: 3.50.2
fastapi: 0.110.0
pydantic: 2.7.0
triton: 2.1.0
```

**Comment by lvhan028** [comment]
这个文件是在量化权重时，离线校准的产物。不影响使用的

**Comment by jxfruit** [comment]
> 这个文件是在量化权重时，离线校准的产物。不影响使用的

感谢回复，主要是现在报错了
![image](https://github.com/InternLM/lmdeploy/assets/11846449/0f335b5a-2bde-43c1-8253-3ce04f49a700)

**Comment by lvhan028** [comment]
lmdeploy v0.3.0 还没有支持 quant_policy=4
升级到 lmdeploy v0.4.2 试试看呢？

**Comment by jxfruit** [comment]
> lmdeploy v0.3.0 还没有支持 quant_policy=4 升级到 lmdeploy v0.4.2 试试看呢？

升级到最新版本了，现在能运行起来，但是有请求进来的时候就会中断，不知道是不是显存爆了，但是也不合理啊，因为我没有指定quant_policy的时候都能正常跑，按理说开启quant_policy应该使用更少显存？
附上debug的log
[lmdeploy.log](https://github.com/user-attachments/files/15605471/lmdeploy.log)

**Comment by lvhan028** [comment]
内存的分配策略是：加载权重后，剩下gpu mem的 80%（这个参数可以通过cache_max_entry_count调节）会全部分配给 kv cache。
以此为前提，量化前后，内存的占用是没有多少区别的。不同的是，量化后，kv cache block数量变多了。

**Comment by lvhan028** [comment]
从提供的日志中，发现有一次 "CUDA runtime error: out of memory"，最后还有一些coredump
OOM 可以通过减小cache_max_entry_count解决。
coredump的信息，目前从日志中看不出什么
复现脚本、数据可以提供下么？

**Comment by jxfruit** [comment]
> lmdeploy serve api_server ./internlm2-chat-1_8b/ --server-name 0.0.0.0 --server-port 23333 --max-batch-size 64 --tp 1 --quant-policy 4

您好，没有脚本，就是用的你们提供的lmdeploy，模型就是用的modelscope下载下来的1.8b的，完整的命令如下：
lmdeploy serve api_server ./internlm2-chat-1_8b/ --server-name 0.0.0.0 --server-port 23333 --max-batch-size 64 --tp 1 --quant-policy 4

另外，我看官方文档上说的在使用KV量化之后内存有显著下降，这里是说的显存么
![image](https://github.com/InternLM/lmdeploy/assets/11846449/98ed14dd-2010-4441-ac35-034a5a6af9bb)

**Comment by lvhan028** [comment]
文档描述不准确。
lmdeploy 目前分配 kv 显存时，在加载权重后，把一定比例的剩余显存全部开辟出来给 kv cache（比例通过参数cache_max_entry_count调节，默认是0.8）
所以，不管kv是否量化，显存不会有多大变化。只不过，kv 量化后，kv block的数量相对量化前增多了。

**Comment by jxfruit** [comment]
大佬，再请教一下哈，我用了cache_max_entry_count参数调节到0.5之后，此时没有加上量化参数，启动速度和接口响应速度明显下降了几倍，但是确实没有出现显存oom问题了。但是如果我再加上量化参数quant_policy=4之后，还是会出现coredump，而无论怎么调节cache_max_entry_count都一样，这是啥情况。

**Comment by lvhan028** [comment]
几倍呢？可以用 benchmark/profile_throughput.py 测一个定量的结果。

**Comment by jxfruit** [comment]
/v1/chat/completions 这个接口可以复现coredump，模型用的modelscope上的chat-1_8b。
时间问题，我研究一下这个profile_throughput.py

**Comment by lvhan028** [comment]
@AllentDan may help investigate this issue

**Comment by AllentDan** [comment]
profile_throughput.py 测试有成功吗？ @jxfruit

**Comment by jxfruit** [comment]
> profile_throughput.py 测试有成功吗？ @jxfruit

没有用quant_policy参数，加cache_max_entry_count参数的结果在下面图片里，结果比较接近（![2128F22A](https://github.com/InternLM/lmdeploy/assets/11846449/6a5eabd5-a1da-41eb-bc29-529e917af695)）
但是启动速度确实有差别很大
![image](https://github.com/InternLM/lmdeploy/assets/11846449/e36dd13d-a415-444a-9b10-e6f8c4f18ce9)

现在主要问题是用quant_policy参数报错的问题，大佬帮忙看下

**Comment by AllentDan** [comment]
Fixed in #1909 @jxfruit

**Comment by zhyncs** [comment]
ref https://github.com/zhyncs/lmdeploy-build/releases/tag/3cec493

**Comment by jxfruit** [comment]
> Fixed in #1909 @jxfruit

升级到0.5了，加上--quant-policy 4参数之后，聊天的几个接口都试过了，还是会直接
[1]    8556 abort (core dumped)  lmdeploy serve api_server  --cache-max-entry-count 0.5 --server-port 23333

我的运行环境：
sys.platform: linux
Python: 3.8.19 (default, Mar 20 2024, 19:58:24) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce GTX 1660 SUPER
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 2.1.2
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_90,code=sm_90;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.16.2
LMDeploy: 0.5.0+
transformers: 4.41.2
gradio: 4.26.0
fastapi: 0.110.3
pydantic: 2.7.0
triton: 2.1.0

**Comment by AllentDan** [comment]
试了下 https://github.com/zhyncs/lmdeploy-build/releases/download/3cec493/lmdeploy-0.5.0+cu118+3cec493-cp310-cp310-manylinux2014_x86_64.whl 包，我这边本地 1660s 正常运行。启动命令是 lmdeploy serve api_server /data2/models/internlm2-chat-1_8b --quant-policy 4 --log-level DEBUG --server-port 24444 --max-batch-size 1

**Comment by jxfruit** [comment]
@AllentDan 我删掉lmdeploy，然后用release里面的地址确实是可以了，之前是直接upgrade的就不行。
感谢各位，issue我先关掉了
