### ISSUE TITLE
[Bug] Mini-InternVL1.5-4B does not suceessfully initialized.

### ISSUE THREAD

**Issue by cydiachen** [InternLM/lmdeploy#1721]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

lmdeploy serve api_server Mini-InternVL-Chat-4B-V1-5 --tp 1 --server-port 23333 --backend pytorch
 <Model> test failed!
("Checking failed with error 'InternVLChatConfig' object has no attribute 'hidden_size'", 'Please send issue to LMDeploy with error logs.'

### Reproduction

lmdeploy serve api_server Mini-InternVL-Chat-4B-V1-5 --tp 1 --server-port 23333 --backend pytorch

### Environment

```Shell
TorchVision: 0.16.1+cu121
LMDeploy: 0.4.2+
transformers: 4.41.2
gradio: 3.37.0
fastapi: 0.105.0
pydantic: 2.7.3
triton: 2.1.0
```

**Comment by irexyc** [comment]
We haven't support the mini series of internvl models.

**Comment by cydiachen** [comment]
> We haven't support the mini series of internvl models.

Are there any plans to support the mini series? The majority changes of mini-series lies in a new image encoder. The rest of llm model are supported, such as internlm-2-1.8 and phi3

**Comment by irexyc** [comment]
Shoud start working after this PR 1702. 

The support for `internlm-2-1.8` should be easy, the main work is adding some mapping to make turbomind backend load the model.  

For phi3 model, only pytorch backend supports it. But there is no general logic for processing embedding in the pytorch engine, some patching method should be added. I am not sure if it's easy to support it. @RunningLeon may answer your question.

**Comment by cydiachen** [comment]
> Shoud start working after this PR 1702.
> 
> The support for `internlm-2-1.8` should be easy, the main work is adding some mapping to make turbomind backend load the model.
> 
> For phi3 model, only pytorch backend supports it. But there is no general logic for processing embedding in the pytorch engine, some patching method should be added. I am not sure if it's easy to support it. @RunningLeon may answer your question.

I think the community will like the pytorch-backend on mini-internvl4b. My main concern is that it seem that the internVIT-400M used in MINI-INTERNVL cannot correctly pass its config as the error.

**Comment by irexyc** [comment]
Should be supported with pytorch backend now.
