### ISSUE TITLE
How to trace multiple GPUs using nsight system

### ISSUE THREAD

**Issue by sleepwalker2017** [InternLM/lmdeploy#1722]
Hi all, I'm trying to profile lmdeploy using nsight system.

I use this script:

```
nsys profile -f true -o lmdeploy-tp8-01-long_prompt --trace-fork-before-exec true python test.py
```

I use tp=8, but I can only see 1 GPU in the trace file.

Why is that? How can I trace all the 8 GPUs? 

Thank you.

**Comment by lzhangzz** [comment]
I usually use the nsight system's GUI when detailed stats or timeline are needed. I didn't pay attention to the generated command for profiling but it dose the job. Maybe you can give it a try.

**Comment by sleepwalker2017** [comment]
> I usually use the nsight system's GUI when detailed stats or timeline are needed. I didn't pay attention to the generated command for profiling but it dose the job. Maybe you can give it a try.

I found why, it's because the old `tp` setting in lmdeploy is deprecated, I set it in config, but it didn't work. Thank you.
