### ISSUE TITLE
High GPU memory for running InternVL-Chat-V1-5-AWQ

### ISSUE THREAD

**Issue by tairen99** [InternLM/lmdeploy#1728]
Hi all,

Thank you for your good work!

With the help from @AllentDan, I am able to run the model.

However, the GPU memory usage is very high (  > 84GB ), which is even high than loading the original model InternVL-Chat-V1-5 ( about 54GB )

Can you please let me know usually how much the GPU memory will cost? and if it is possible, how to control the GPU usage?

The sample code is from [link](https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5-AWQ)

**Environment is:**
4 GPUs: NVIDIA A10G each has 23GB
Memory: 192 GB
num of CPU: 48
Docker environment is: nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04
Python version: 3.9.19
transformers version: 4.38.2
lmdeply version: 0.4.2

See the image or detail
![image](https://github.com/InternLM/lmdeploy/assets/32938376/68a293eb-282c-426a-94e3-8c1ca8d60c4e)

Thank you in advance!

**Comment by AllentDan** [comment]
May refer to https://lmdeploy.readthedocs.io/en/latest/inference/pipeline.html#usage
May set a value for `cache_max_entry_count`

**Comment by tairen99** [comment]
> May refer to https://lmdeploy.readthedocs.io/en/latest/inference/pipeline.html#usage May set a value for `cache_max_entry_count`

Hi @AllentDan,

Thank you very much for your help again.

Changing `cache_max_entry_count` close to zero helps. But if I `cache_max_entry_count=0`, it gives me the error.

Do you know how to force the k/v cache only uses the memory rather than the GPU ram?

Do we have any other ways to reduce the GPU ram usage further?

Thank you!

**Comment by AllentDan** [comment]
Nope, lmdeploy turbomind kv cache requires VRAM. May set it a value between 0 and 1.

**Comment by tairen99** [comment]
> Nope, lmdeploy turbomind kv cache requires VRAM. May set it a value between 0 and 1.

Thank you @AllentDan
