### ISSUE TITLE
[Feature] Qwen 2 Support

### ISSUE THREAD

**Issue by suptejas** [InternLM/lmdeploy#1746]
### Motivation

I'd love to use lmdeploy to run inference for Qwen-2 models. It would be great to get support.

**Comment by zhanpengjie** [comment]
same with qwen1.5 can just run

**Comment by lvhan028** [comment]
As @zhanpengjie said, LMDeploy supports Qwen2. It has the same structure with Qwen1.5. 
I am going to close this issue. Feel free to reopen it if it is still an issue.
