### ISSUE TITLE
[Bug] 判断条件检查

### ISSUE THREAD

**Issue by seetimee** [InternLM/lmdeploy#1757]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/serve/proxy/proxy.py里的
if min_latency < latency:这个判断条件是不是有点问题,应该是反过来吧

### Reproduction

None

### Environment

```Shell
None
```

**Comment by lvhan028** [comment]
https://github.com/InternLM/lmdeploy/pull/1692 is addressing this issue.

**Comment by AllentDan** [comment]
Close since it was fixed.
