### ISSUE TITLE
[Feature] 使用已经构建好的input使用lmdeploy来进行推理

### ISSUE THREAD

**Issue by KooSung** [InternLM/lmdeploy#1760]
### Motivation

请问如何使用已经构建好的input使用lmdeploy来进行推理?
背景是多模态输入自定义较多，期望能够直接使用构建好的inputs来进行推理加速。
```
        with torch.inference_mode():
            outputs = self.llm.generate(
                **inputs,
                streamer=None,
                max_new_tokens=1024,
                do_sample=True,
                temperature=0.8,
                top_p=0.8,
                eos_token_id=eos_token_id
            )
```

**Comment by lvhan028** [comment]
LMDeploy不支持这个特性。
离线推理的方式，目前支持的输入情况可以在这份文档中找到：https://lmdeploy.readthedocs.io/en/latest/inference/vl_pipeline.html
在线推理方式，接口是对齐GPT-4V的：https://lmdeploy.readthedocs.io/en/latest/serving/api_server_vl.html

**Comment by irexyc** [comment]
如果用turbomind的接口的话，可以接收embedding形式的输入，应该能做到你说的情况。不过可能需要二次开发，具体使用可以参考[pipeline](https://github.com/InternLM/lmdeploy/blob/c0b0ba9af31e32e55d5887ab701cc16f6d5f0872/lmdeploy/serve/async_engine.py)调用turbomind backend的逻辑

https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/turbomind/turbomind.py#L793-L804

**Comment by KooSung** [comment]
@irexyc 谢谢🙏
