### ISSUE TITLE
[Feature] 多模态的模型支持在线serving吗？

### ISSUE THREAD

**Issue by CSEEduanyu** [InternLM/lmdeploy#1762]
### Motivation

[Feature] 多模态的模型支持在线serving吗？

**Comment by lvhan028** [comment]
支持。文档在这里：https://lmdeploy.readthedocs.io/en/latest/serving/api_server_vl.html

**Comment by CSEEduanyu** [comment]
> 支持。文档在这里：https://lmdeploy.readthedocs.io/en/latest/serving/api_server_vl.html

大佬 有curl传base64的样例不 试了下传base64没跑通 我看代码注释里是说可以传base64的

**Comment by lvhan028** [comment]
@AllentDan 可以提供个样例吗？

**Comment by CSEEduanyu** [comment]
> @AllentDan 可以提供个样例吗？

可以了 但是为啥只有/v1/chat/interactive这个接口能传image_url呢？然后这个接口又没max_tokens的字段。。

**Comment by AllentDan** [comment]
> > @AllentDan 可以提供个样例吗？
> 
> 可以了 但是为啥只有/v1/chat/interactive这个接口能传image_url呢？然后这个接口又没max_tokens的字段。。

有 request_output_len。另外 OpenAI 接口也可以传，可自行查阅 OpenAI 文档 https://platform.openai.com/docs/api-reference/chat/create

**Comment by CSEEduanyu** [comment]
> > > @AllentDan 可以提供个样例吗？
> > 
> > 
> > 可以了 但是为啥只有/v1/chat/interactive这个接口能传image_url呢？然后这个接口又没max_tokens的字段。。
> 
> 有 request_output_len。另外 OpenAI 接口也可以传，可自行查阅 OpenAI 文档 https://platform.openai.com/docs/api-reference/chat/create

/v1/completions的请求参数CompletionRequest里没有image_url呢 我试了这个接口不行

**Comment by AllentDan** [comment]
请仔细查看文档，/v1/chat/completions

**Comment by CSEEduanyu** [comment]
> 请仔细查看文档，/v1/chat/completions

https://github.com/InternLM/lmdeploy/blob/fbd294adaef24dd98aeaf99f9b2246167c723451/lmdeploy/serve/openai/protocol.py#L81

**Comment by CSEEduanyu** [comment]
https://github.com/InternLM/lmdeploy/blob/fbd294adaef24dd98aeaf99f9b2246167c723451/lmdeploy/serve/openai/protocol.py#L294

**Comment by AllentDan** [comment]
https://lmdeploy.readthedocs.io/en/latest/serving/api_server_vl.html#integrate-with-openai

Please read the document.
