### ISSUE TITLE
[Bug] 为什么pipeline输出只有一个1个token？

### ISSUE THREAD

**Issue by Axiaozhu1** [InternLM/lmdeploy#1766]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug
pipeline的第一个输出只有一个token。
输出为
[WARNING] gemm_config.in is not found; using default GEMM algo
[Response(text='你', generate_token_len=1, input_token_len=12, session_id=0, finish_reason='stop', token_ids=[57668], logprobs=None)]

### Reproduction

import lmdeploy

pipe = lmdeploy.pipeline("./model/Llama3-Chinese-8B-Instruct")
response = pipe(["你好"])
print(response)

### Environment

```Shell
accelerate                    0.30.1
addict                        2.4.0
aiofiles                      23.2.1
aiohttp                       3.9.5
aiosignal                     1.3.1
altair                        5.3.0
annotated-types               0.7.0
anyio                         4.4.0
async-timeout                 4.0.3
attrs                         23.2.0
certifi                       2022.12.7
charset-normalizer            2.1.1
click                         8.1.7
cmake                         3.29.3
colorama                      0.4.6
contourpy                     1.2.1
cycler                        0.12.1
datasets                      2.19.2
dill                          0.3.8
dnspython                     2.6.1
einops                        0.8.0
email_validator               2.1.1
exceptiongroup                1.2.1
fastapi                       0.111.0
fastapi-cli                   0.0.4
ffmpy                         0.3.2
filelock                      3.13.1
fire                          0.6.0
flash_attn                    2.4.1
fonttools                     4.53.0
frozenlist                    1.4.1
fsspec                        2024.2.0
gradio                        3.50.2
gradio_client                 0.6.1
grpcio                        1.64.1
h11                           0.14.0
httpcore                      1.0.5
httptools                     0.6.1
httpx                         0.27.0
huggingface-hub               0.23.3
idna                          3.4
importlib_metadata            7.1.0
importlib_resources           6.4.0
Jinja2                        3.1.3
jsonschema                    4.22.0
jsonschema-specifications     2023.12.1
kiwisolver                    1.4.5
lmdeploy                      0.4.2
markdown-it-py                3.0.0
MarkupSafe                    2.1.5
matplotlib                    3.9.0
mdurl                         0.1.2
mmengine-lite                 0.10.4
mpmath                        1.3.0
multidict                     6.0.5
multiprocess                  0.70.16
networkx                      3.2.1
ninja                         1.11.1.1
numpy                         1.26.3
orjson                        3.10.3
packaging                     24.0
pandas                        2.2.2
peft                          0.9.0
pillow                        10.2.0
pip                           24.0
platformdirs                  4.2.2
protobuf                      4.25.3
psutil                        5.9.8
pyarrow                       16.1.0
pyarrow-hotfix                0.6
pybind11                      2.12.0
pydantic                      2.7.3
pydantic_core                 2.18.4
pydub                         0.25.1
Pygments                      2.18.0
pynvml                        11.5.0
pyparsing                     3.1.2
python-dateutil               2.9.0.post0
python-dotenv                 1.0.1
python-multipart              0.0.9
python-rapidjson              1.17
pytz                          2024.1
PyYAML                        6.0.1
referencing                   0.35.1
regex                         2024.5.15
requests                      2.32.3
rich                          13.7.1
rpds-py                       0.18.1
safetensors                   0.4.3
semantic-version              2.10.0
sentencepiece                 0.2.0
setuptools                    69.5.1
shellingham                   1.5.4
shortuuid                     1.0.13
six                           1.16.0
sniffio                       1.3.1
starlette                     0.37.2
sympy                         1.12
termcolor                     2.4.0
tiktoken                      0.7.0
tokenizers                    0.19.1
tomli                         2.0.1
toolz                         0.12.1
torch                         2.1.2+cu121
torchaudio                    2.1.2+cu121
torchvision                   0.16.2+cu121
tqdm                          4.66.4
transformers                  4.40.0
transformers-stream-generator 0.0.5
triton                        2.1.0
tritonclient                  2.46.0
typer                         0.12.3
typing_extensions             4.9.0
tzdata                        2024.1
ujson                         5.10.0
urllib3                       2.2.1
uvicorn                       0.30.1
watchfiles                    0.22.0
websockets                    11.0.3
wheel                         0.43.0
xxhash                        3.4.1
yapf                          0.40.2
yarl                          1.9.4
zipp                          3.19.2
```

**Comment by lvhan028** [comment]
没有复现你遇到的问题。
还请把 `lmdeploy check_env` 的结果贴一下。

另外，麻烦参考下面代码，把 INFO 日志打开，看下详细情况
```
pipe = lmdeploy.pipeline("./model/Llama3-Chinese-8B-Instruct", log_level='INFO')
```

**Comment by lvhan028** [comment]
原来是 windows platform
@irexyc could you help investigate it?

**Comment by irexyc** [comment]
这个模型在huggingface上面有么？

除了"你好"，其他的prompt是什么情况呢。

**Comment by Axiaozhu1** [comment]
在huggingface上有的，https://huggingface.co/FlagAlpha/Llama3-Chinese-8B-Instruct
改了prompt
response = pipe(["你是谁？"])
结果如下：
[Response(text='您', generate_token_len=1, input_token_len=14, session_id=0, finish_reason='stop', token_ids=[88126], logprobs=None)]


用命令行运行时，可以正常输出。
(lmdeploy) C:\Users\MSN>lmdeploy chat D:\ZJ\llm加速\model\Llama3-Chinese-8B-Instruct
Add dll path C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin, please note cuda version should >= 11.3 when compiled with cuda 11
2024-06-14 15:11:17,530 - lmdeploy - WARNING - model_source: hf_model
2024-06-14 15:11:17,530 - lmdeploy - WARNING - kwargs max_batch_size is deprecated to initialize model, use TurbomindEngineConfig instead.
2024-06-14 15:11:17,530 - lmdeploy - WARNING - kwargs cache_max_entry_count is deprecated to initialize model, use TurbomindEngineConfig instead.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
2024-06-14 15:11:17,942 - lmdeploy - WARNING - model_config:

[llama]
model_name = llama3
tensor_para_size = 1
head_num = 32
kv_head_num = 8
vocab_size = 128256
num_layer = 32
inter_size = 14336
norm_eps = 1e-05
attn_bias = 0
start_id = 128000
end_id = 128001
session_len = 8200
weight_type = fp16
rotary_embedding = 128
rope_theta = 500000.0
size_per_head = 128
group_size = 0
max_batch_size = 128
max_context_token_num = 1
step_length = 1
cache_max_entry_count = 0.8
cache_block_seq_len = 64
cache_chunk_size = -1
enable_prefix_caching = False
num_tokens_per_iter = 0
max_prefill_iters = 1
extra_tokens_per_iter = 0
use_context_fmha = 1
quant_policy = 0
max_position_embeddings = 8192
rope_scaling_factor = 0.0
use_dynamic_ntk = 0
use_logn_attn = 0
lora_policy =
lora_r = 0
lora_scale = 0.0
lora_max_wo_r = 0
lora_rank_pattern =
lora_scale_pattern =


2024-06-14 15:11:19,074 - lmdeploy - WARNING - get 227 model params
2024-06-14 15:11:24,386 - lmdeploy - WARNING - Input chat template with model_name is None. Forcing to use llama3
[WARNING] gemm_config.in is not found; using default GEMM algo
session 1

double enter to end input >>> 你好

<|begin_of_text|><|start_header_id|>user<|end_header_id|>

你好<|eot_id|><|start_header_id|>assistant<|end_header_id|>

 2024-06-14 15:11:36,025 - lmdeploy - WARNING - kwargs ignore_eos is deprecated for inference, use GenerationConfig instead.
2024-06-14 15:11:36,025 - lmdeploy - WARNING - kwargs random_seed is deprecated for inference, use GenerationConfig instead.
你好！有什么可以帮到你的吗？

double enter to end input >>> 你是谁？

<|start_header_id|>user<|end_header_id|>

你是谁？<|eot_id|><|start_header_id|>assistant<|end_header_id|>

 我是一个人工智能语言模型，我可以回答您的问题并提供一些帮助。

double enter to end input >>>

**Comment by irexyc** [comment]
```
TM_DEBUG_LEVEL=DEBUG python

>>> from lmdeploy import pipeline
>>> pipe = lmdeploy.pipeline("./model/Llama3-Chinese-8B-Instruct", log_level='INFO')
```

我这里没有合适的机器来跑模型。你这边这样试下呢，应该会打印每一个step的结果，类似这种
```
[TM][INFO] [Finish] slot 0, tokens [128000 128006 882 128007 271 57668 53901 128009 128006 78191 128007 198 57668]
```

**Comment by Axiaozhu1** [comment]
执行代码
import lmdeploy
pipe = lmdeploy.pipeline("./model/Llama3-Chinese-8B-Instruct", log_level='INFO')
print(pipe('你好'))

结果如下：
D:\anaconda\envs\lmdeploy\python.exe D:\ZJ\llm加速\2222.py 
Add dll path C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin, please note cuda version should >= 11.3 when compiled with cuda 11
2024-06-14 20:12:24,582 - lmdeploy - INFO - Using turbomind engine
2024-06-14 20:12:24,582 - lmdeploy - INFO - input backend=turbomind, backend_config=TurbomindEngineConfig(model_name=None, model_format=None, tp=1, session_len=None, max_batch_size=128, cache_max_entry_count=0.8, cache_block_seq_len=64, enable_prefix_caching=False, quant_policy=0, rope_scaling_factor=0.0, use_logn_attn=False, download_dir=None, revision=None, max_prefill_token_num=8192, num_tokens_per_iter=0, max_prefill_iters=1)
2024-06-14 20:12:24,582 - lmdeploy - INFO - input chat_template_config=None
2024-06-14 20:12:24,582 - lmdeploy - INFO - matched chat template name: llama3
2024-06-14 20:12:24,610 - lmdeploy - INFO - updated chat_template_onfig=ChatTemplateConfig(model_name='llama3', system=None, meta_instruction=None, eosys=None, user=None, eoh=None, assistant=None, eoa=None, separator=None, capability=None, stop_words=None)
2024-06-14 20:12:24,610 - lmdeploy - WARNING - model_source: hf_model
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
2024-06-14 20:12:25,021 - lmdeploy - WARNING - model_config:

[llama]
model_name = llama3
tensor_para_size = 1
head_num = 32
kv_head_num = 8
vocab_size = 128256
num_layer = 32
inter_size = 14336
norm_eps = 1e-05
attn_bias = 0
start_id = 128000
end_id = 128001
session_len = 8200
weight_type = fp16
rotary_embedding = 128
rope_theta = 500000.0
size_per_head = 128
group_size = 0
max_batch_size = 128
max_context_token_num = 1
step_length = 1
cache_max_entry_count = 0.8
cache_block_seq_len = 64
cache_chunk_size = -1
enable_prefix_caching = False
num_tokens_per_iter = 0
max_prefill_iters = 1
extra_tokens_per_iter = 0
use_context_fmha = 1
quant_policy = 0
max_position_embeddings = 8192
rope_scaling_factor = 0.0
use_dynamic_ntk = 0
use_logn_attn = 0
lora_policy = 
lora_r = 0
lora_scale = 0.0
lora_max_wo_r = 0
lora_rank_pattern = 
lora_scale_pattern = 


[TM][INFO] Set logger level by INFO
[TM][WARNING] [LlamaTritonModel] `max_context_token_num` = 8200.
[TM][WARNING] [LlamaTritonModel] `num_tokens_per_iter` is not set, default to `max_context_token_num` (8200).
[TM][INFO] Barrier(1)
[TM][INFO] Set logger level by INFO
Convert to turbomind format:   0%|          | 0/32 [00:00<?, ?it/s]2024-06-14 20:12:26,173 - lmdeploy - WARNING - get 227 model params
[TM][INFO] Set logger level by INFO
2024-06-14 20:12:31,634 - lmdeploy - INFO - updated backend_config=TurbomindEngineConfig(model_name=None, model_format=None, tp=1, session_len=None, max_batch_size=128, cache_max_entry_count=0.8, cache_block_seq_len=64, enable_prefix_caching=False, quant_policy=0, rope_scaling_factor=0.0, use_logn_attn=False, download_dir=None, revision=None, max_prefill_token_num=8192, num_tokens_per_iter=0, max_prefill_iters=1)
[WARNING] gemm_config.in is not found; using default GEMM algo
[TM][INFO] NCCL group_id = 0
[TM][INFO] [BlockManager] block_size = 8 MB
[TM][INFO] [BlockManager] max_block_count = 675
[TM][INFO] [BlockManager] chunk_size = 675
[TM][INFO] LlamaBatch<T>::Start()
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Barrier(1)
[TM][INFO] Set logger level by INFO
[TM][INFO] [forward] Enqueue requests
[TM][INFO] [forward] Wait for requests to complete ...
[TM][INFO] Set logger level by INFO
[TM][WARNING] [ProcessInferRequests] Request for 0 received.
2024-06-14 20:12:32,490 - lmdeploy - INFO - prompt='<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n\n你好<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n', gen_config=EngineGenerationConfig(n=1, max_new_tokens=512, top_p=0.8, top_k=40, temperature=0.8, repetition_penalty=1.0, ignore_eos=False, random_seed=7052747007397626466, stop_words=[128009, 128001], bad_words=None, min_new_tokens=None, skip_special_tokens=True, logprobs=None), prompt_token_id=[128000, 128006, 882, 128007, 271, 57668, 53901, 128009, 128006, 78191, 128007, 198], adapter_name=None.
2024-06-14 20:12:32,490 - lmdeploy - INFO - session_id=0, history_tokens=0, input_tokens=12, max_new_tokens=512, seq_start=True, seq_end=True, step=0, prep=True
[TM][INFO] [Forward] [0, 1), dc_bsz = 0, pf_bsz = 1, n_tok = 12, max_q = 12, max_k = 12
[TM][INFO] [Interrupt] slot = 0, id = 0
[TM][INFO] [forward] Request complete for 0, code 0
Response(text='你', generate_token_len=1, input_token_len=12, session_id=0, finish_reason='stop', token_ids=[57668], logprobs=None)
[TM][INFO] ~LlamaBatch()
[TM][INFO] [InternalThreadEntry] stop requested.
[TM][INFO] Set logger level by INFO
[TM][INFO] [OutputThreadEntry] stop requested.

进程已结束,退出代码0

**Comment by Axiaozhu1** [comment]
用命令行的结果是好的
>>> pipe('你好')
2024-06-14 20:15:07,918 - lmdeploy - INFO - prompt='<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n\n你好<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n', gen_config=EngineGenerationConfig(n=1, max_new_tokens=512, top_p=0.8, top_k=40, temperature=0.8, repetition_penalty=1.0, ignore_eos=False, random_seed=14679132919464160973, stop_words=[128009, 128001], bad_words=None, min_new_tokens=None, skip_special_tokens=True, logprobs=None), prompt_token_id=[128000, 128006, 882, 128007, 271, 57668, 53901, 128009, 128006, 78191, 128007, 198], adapter_name=None.
2024-06-14 20:15:07,919 - lmdeploy - INFO - session_id=0, history_tokens=0, input_tokens=12, max_new_tokens=512, seq_start=True, seq_end=True, step=0, prep=True
[TM][INFO] Barrier(1)
[TM][INFO] Set logger level by INFO
[TM][INFO] [forward] Enqueue requests
[TM][INFO] [forward] Wait for requests to complete ...
[TM][INFO] Set logger level by INFO
[TM][WARNING] [ProcessInferRequests] Request for 0 received.
[TM][INFO] [Forward] [0, 1), dc_bsz = 0, pf_bsz = 1, n_tok = 12, max_q = 12, max_k = 12
[TM][INFO] Set logger level by INFO
[TM][INFO] ------------------------- step = 20 -------------------------
[TM][INFO] [Interrupt] slot = 0, id = 0
[TM][INFO] [forward] Request complete for 0, code 0
Response(text='你好！有什么需要帮助您的吗？', generate_token_len=10, input_token_len=12, session_id=0, finish_reason='stop', token_ids=[57668, 53901, 6447, 123100, 86206, 123725, 127442, 103054, 11571], logprobs=None)

**Comment by irexyc** [comment]
在进python前，需要设置环境变量（TM_DEBUG_LEVEL=DEBUG）的，不然不会打印这种信息`[TM][INFO] [Finish] slot 0, tokens [...`

```
TM_DEBUG_LEVEL=DEBUG  python
```

**Comment by Axiaozhu1** [comment]
问题已经解决了，应该是我自己环境的问题，感谢解答

**Comment by Axiaozhu1** [comment]
现在都是正常输出了

**Comment by irexyc** [comment]
@Axiaozhu1 

主要是想知道之前出问题的原因。
