### ISSUE TITLE
[Feature] support edge chips

### ISSUE THREAD

**Issue by PredyDaddy** [InternLM/lmdeploy#1767]
### Motivation

My project only allow me to used orin series. But seems lmdeploy does not support this. Can I know if this is on the way?

**Comment by lvhan028** [comment]
Can [this](https://github.com/BestAnHongjun/LMDeploy-Jetson) project do you the favor?

**Comment by PredyDaddy** [comment]
Thanks for reply. This is an amazing project! But I am looking for vlm deploy on Jeson actually. Do you have any recommend?

**Comment by BestAnHongjun** [comment]
We will make every effort to adapt LMDeploy v0.4.2 to the Jetson Orin series in the near future. Thank you for your interest in the [LMDeploy-Jetson](https://github.com/BestAnHongjun/LMDeploy-Jetson) project!
