### ISSUE TITLE
about getting the deterministic answer from VLM model, such as InternVL-Chat-V1-5-AWQ

### ISSUE THREAD

**Issue by tairen99** [InternLM/lmdeploy#1783]
Hi all,

Thank you for your good work.

I am testing the VLM model: InternVL-Chat-V1-5-AWQ using [link](https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5-AWQ) and I find every time the answer I got is a little different, especially for reading the chart.

How can I get the deterministic answer using VLM: InternVL-Chat-V1-5-AWQ? do you support configure the 'temperature' using `GenerationConfig` in [LLM Offline Inference Pipeline](https://lmdeploy.readthedocs.io/en/latest/inference/pipeline.html#) for VLM?

Thank you in advance!

**Comment by zhyncs** [comment]
> How can I get the deterministic answer using VLM

set `temperature` to 0

> do you support configure the 'temperature' using GenerationConfig

yep. ref to
https://github.com/InternLM/lmdeploy/blob/bd431bfc74a7132c146c67a21fdd3446fc5870c4/docs/en/inference/pipeline.md?plain=1#L58-L64

**Comment by tairen99** [comment]
> > How can I get the deterministic answer using VLM
> 
> set `temperature` to 0
> 
> > do you support configure the 'temperature' using GenerationConfig
> 
> yep. ref to
> 
> https://github.com/InternLM/lmdeploy/blob/bd431bfc74a7132c146c67a21fdd3446fc5870c4/docs/en/inference/pipeline.md?plain=1#L58-L64

Hi @zhyncs and @AllentDan ,

Thank you very much for your response and your previous helps!

According to your suggestion, I set the `temperature=0` in `gen_config` with the following code, but I still get different results, can you please pinpoint potential issues:

    from lmdeploy import pipeline, GenerationConfig
    from lmdeploy.messages import TurbomindEngineConfig
    from lmdeploy.vl import load_image

    model = 'OpenGVLab/InternVL-Chat-V1-5-AWQ'
    image = load_image('https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/tests/data/tiger.jpeg')
    backend_config = TurbomindEngineConfig(model_format='awq')
    gen_config = GenerationConfig(top_p=0.8, 
                               top_k=40, 
                               temperature=0, 
                               max_new_tokens=1024) 
    pipe = pipeline(model, backend_config=backend_config, log_level='INFO')
    for _ in range(5):
        response = pipe(('describe this image', image),  gen_config=gen_config)
        print(response)

Thank you again!

**Comment by AllentDan** [comment]
There was a PR https://github.com/InternLM/lmdeploy/pull/1741 merged lately. May resolve the bug.

**Comment by zhyncs** [comment]
Hi @tairen99 You may try this https://github.com/zhyncs/lmdeploy/actions/runs/9545699162/artifacts/1608042438

which is [built](https://github.com/zhyncs/lmdeploy/actions/runs/9545699162) with [latest commit](https://github.com/InternLM/lmdeploy/commit/46c02412e3d7f38a0cb17fa3036864917eb5c7aa)

**Comment by tairen99** [comment]
> Hi @tairen99 You may try this https://github.com/zhyncs/lmdeploy/actions/runs/9545699162/artifacts/1608042438
> 
> which is [built](https://github.com/zhyncs/lmdeploy/actions/runs/9545699162) with [latest commit](https://github.com/InternLM/lmdeploy/commit/46c02412e3d7f38a0cb17fa3036864917eb5c7aa)

Hi @zhyncs and @AllentDan,

Thank you very much for both of your answers!!

Appreciate you for creating the installation package for me. Unfortunately, the [link](https://github.com/zhyncs/lmdeploy/actions/runs/9545699162/artifacts/1608042438) you created is not working anymore. 

Can I use "`pip install lmdeploy[all]`" or "`pip install lmdeploy`" to install the latest version you committed for the deterministic answer? 

Thank you again!

**Comment by zhyncs** [comment]
Hi @tairen99 You may fork the repo and run the workflow manually https://github.com/InternLM/lmdeploy/blob/main/.github/workflows/cuda11.8-whl-release.yml

**Comment by tairen99** [comment]
> Hi @tairen99 You may fork the repo and run the workflow manually https://github.com/InternLM/lmdeploy/blob/main/.github/workflows/cuda11.8-whl-release.yml

Hi @zhyncs 

Thank you for your suggestion.

I installed the "`lmdeploy-0.4.2-cp39-cp39-manylinux2014_x86_64.whl`" from generated `artifact.zip`, but the it has lmdeploy ERROR. I will open another issue for this.

Thank you.

**Comment by zhyncs** [comment]
@tairen99 https://github.com/zhyncs/lmdeploy-build/releases/tag/da439df May you try this😎

**Comment by tairen99** [comment]
> @tairen99 https://github.com/zhyncs/lmdeploy-build/releases/tag/da439df May you try this😎



> @tairen99 https://github.com/zhyncs/lmdeploy-build/releases/tag/da439df May you try this😎

Hi @zhyncs 

Appreciate it again.

I have tried both " lmdeploy-0.4.2+cu118+da439df-cp39-cp39-manylinux2014_x86_64.whl " and " lmdeploy-0.4.2+cu121+da439df-cp39-cp39-manylinux2014_x86_64.whl" from you shared link, I still met the
 "lmdeploy ERROR" as: "2024-06-24 18:11:48,174 - lmdeploy - ERROR - Truncate max_new_tokens to 221" 
for large input image for both versions. The results are Truncated as the ERROR shown.

Thanks
