### ISSUE TITLE
是否兼容openai中参数n的设置？尝试设置n>1，但仍然只返回一条结果

### ISSUE THREAD

**Issue by hitsz-zxw** [InternLM/lmdeploy#1787]
data = {
        “model”: ****
        "max_tokens": 1000,
        "temperature": 0.8,
        "repetition_penalty": 1.1,
        "n": 3,
        "stop": ["<|end_of_text|>","<|eot_id|>","<|im_end|>","<|im_start|>","<|start_header_id|>"],
    }
    headers = {'Content-Type': 'application/json'}
    response = requests.post(api_url, headers=headers, json=data, stream=True, timeout=60)
    response_data = json.loads(response.content)
    response_content1 = response_data['choices'][0]["text"]
    response_content2 = response_data['choices'][1]["text"]
    response_content3 = response_data['choices'][2]["text"]

以这样的方式无法接收期望的三条回答，response_data['choices']中只有一条回复

**Comment by irexyc** [comment]
n这个参数目前不支持的。

**Comment by bigheiniu** [comment]
你们可以code 里面highlight 下吗？https://github.com/InternLM/lmdeploy/blob/44350f9f9d2ffe125486a8f0cbd5a333f748b59d/lmdeploy/messages.py#L16
Like: Current we did not support n>1.

**Comment by lvhan028** [comment]
Sure. We will highlight it in the docstring and log

**Comment by lvhan028** [comment]
https://github.com/InternLM/lmdeploy/pull/2108 @bigheiniu
