### ISSUE TITLE
[QA] 如何将ckpt保存内容转换为pytorch_model文件

### ISSUE THREAD

**Issue by nb003pl** [InternLM/lmdeploy#179]
请教下如何将训练过程保存的ckpt内容转换为pytorch_model内容？谢谢

比如，使用 zero=4/tensor=2 + 自有数据 预训练了100步，保存的ckpt文件夹内容：
context.pt                gpus-8_pp-0_tp-0_zo-3.pt  gpus-8_pp-0_tp-0_zo-7.pt  optimizer_tp0_pp0_zo1.pt  optimizer_tp0_pp0_zo5.pt  schedulder.pt
gpus-8_pp-0_tp-0_zo-0.pt  gpus-8_pp-0_tp-0_zo-4.pt  model_config.pt           optimizer_tp0_pp0_zo2.pt  optimizer_tp0_pp0_zo6.pt  topo_tp0_pp0.json
gpus-8_pp-0_tp-0_zo-1.pt  gpus-8_pp-0_tp-0_zo-5.pt  model_tp0_pp0.pt          optimizer_tp0_pp0_zo3.pt  optimizer_tp0_pp0_zo7.pt
gpus-8_pp-0_tp-0_zo-2.pt  gpus-8_pp-0_tp-0_zo-6.pt  optimizer_tp0_pp0_zo0.pt  optimizer_tp0_pp0_zo4.pt  sampler.pt

目标：转成可以直接被 lmdeploy.serve.turbomind.deploy加载的模型文件
config.json                modeling_internlm.py              pytorch_model.bin.index.json  tokenization_internlm.py
configuration_internlm.py  pytorch_model-00001-of-00002.bin  README.md                     tokenizer_config.json
generation_config.json     pytorch_model-00002-of-00002.bin  special_tokens_map.json

**Comment by lvhan028** [comment]
是用InternLM训练的吗？
如果是的话，首先请参考[这里](https://github.com/InternLM/InternLM#convert-to-transformers-format)把训练模型换换为huggingface transformers模型结构。然后可以用turbomind.deoloy转成目标格式
