### ISSUE TITLE
"Aborted (core dumped)" when running Qwen2-7B-Instruct [Bug]

### ISSUE THREAD

**Issue by kaishxu** [InternLM/lmdeploy#1792]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

I use the latest lmdeploy version (0.4.2) and git clone the parameters from huggingface. 

the main code is as follows:
pipe = lmdeploy.pipeline(model_path=model_path,
                            chat_template_config=chat_template_config)

gen_config = GenerationConfig(top_p=1,
                              temperature=0.0,
                              max_new_tokens=1024,
                              random_seed=random_seed)

outputs = pipe(input_prompt,
                    gen_config=gen_config)

after "Convert to turbomind format", the error "Aborted (core dumped)" occurs without any other information.

### Reproduction

I use python function of lmdeply, e.g., lmdeploy.pipeline, GenerationConfig. 

### Environment

```Shell
sys.platform: linux
Python: 3.11.3 (main, Apr 19 2023, 23:54:32) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.1, V12.1.66
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
PyTorch: 2.2.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

TorchVision: 0.17.2+cu121
LMDeploy: 0.4.2+
transformers: 4.39.0
gradio: Not Found
fastapi: 0.111.0
pydantic: 2.7.4
triton: 2.2.0

I install pytorch by pip.
```

**Comment by AllentDan** [comment]
Please set `log_level='INFO'` when initializing `pipeline`.

**Comment by kaishxu** [comment]
The last log information is as follows:
[TM][INFO] Set logger level by INFO
[TM][INFO] [forward] Enqueue requests
[TM][INFO] [forward] Wait for requests to complete ...
[TM][WARNING] [ProcessInferRequests] Request for 1 received.
[TM][WARNING] [ProcessInferRequests] Request for 2 received.
[TM][WARNING] [ProcessInferRequests] Request for 3 received.
[TM][WARNING] [ProcessInferRequests] Request for 4 received.
[TM][WARNING] [ProcessInferRequests] Request for 5 received.
[TM][WARNING] [ProcessInferRequests] Request for 6 received.
[TM][WARNING] [ProcessInferRequests] Request for 7 received.
[TM][WARNING] [ProcessInferRequests] Request for 8 received.
[TM][WARNING] [ProcessInferRequests] Request for 9 received.
[TM][WARNING] [ProcessInferRequests] Request for 10 received.
[TM][WARNING] [ProcessInferRequests] Request for 11 received.
[TM][WARNING] [ProcessInferRequests] Request for 12 received.
[TM][WARNING] [ProcessInferRequests] Request for 13 received.
[TM][WARNING] [ProcessInferRequests] Request for 14 received.
[TM][WARNING] [ProcessInferRequests] Request for 15 received.
[TM][WARNING] [ProcessInferRequests] Request for 16 received.
[TM][WARNING] [ProcessInferRequests] Request for 17 received.
[TM][WARNING] [ProcessInferRequests] Request for 18 received.
[TM][WARNING] [ProcessInferRequests] Request for 19 received.
[TM][WARNING] [ProcessInferRequests] Request for 20 received.
[TM][WARNING] [ProcessInferRequests] Request for 21 received.
[TM][WARNING] [ProcessInferRequests] Request for 22 received.
[TM][WARNING] [ProcessInferRequests] Request for 23 received.
[TM][WARNING] [ProcessInferRequests] Request for 24 received.
[TM][WARNING] [ProcessInferRequests] Request for 25 received.
[TM][WARNING] [ProcessInferRequests] Request for 26 received.
[TM][WARNING] [ProcessInferRequests] Request for 27 received.
[TM][WARNING] [ProcessInferRequests] Request for 28 received.
[TM][WARNING] [ProcessInferRequests] Request for 29 received.
[TM][WARNING] [ProcessInferRequests] Request for 30 received.
[TM][WARNING] [ProcessInferRequests] Request for 31 received.
[TM][INFO] [Forward] [0, 32), dc_bsz = 1, pf_bsz = 31, n_tok = 10026, max_q = 516, max_k = 516
...Aborted                 (core dumped)

**Comment by lvhan028** [comment]
Have you enabled tensor parallelism?

**Comment by kaishxu** [comment]
no, I didn't set this parameter.

**Comment by lvhan028** [comment]
Oh, sorry. 
I mistakenly read it as 72B.

**Comment by AllentDan** [comment]
Have you tried loading the model directly from huggingface format instead of converting to turbomind first.

**Comment by kaishxu** [comment]
> Have you tried loading the model directly from huggingface format instead of converting to turbomind first.

I reinstall the package from the source. It works!
