### ISSUE TITLE
[Bug] lmdeploy got nccl error

### ISSUE THREAD

**Issue by linyubupa** [InternLM/lmdeploy#1803]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

2024-06-19 13:51:09,086 - lmdeploy - INFO - input chat_template_config=None
2024-06-19 13:51:11,931 - lmdeploy - INFO - updated chat_template_onfig=ChatTemplateConfig(model_name='qwen', system=None, meta_instruction=None, eosys=None, user=None, eoh=None, assistant=None, eoa=None, separator=None, capability=None, stop_words=None)
2024-06-19 13:51:11,933 - lmdeploy - WARNING - model_source: hf_model
2024-06-19 13:51:11,933 - lmdeploy - WARNING - model_name is deprecated in TurbomindEngineConfig and has no effect
2024-06-19 13:51:12,566 - lmdeploy - WARNING - model_config:

[llama]
model_name = qwen
tensor_para_size = 4
head_num = 32
kv_head_num = 4
vocab_size = 92416
num_layer = 32
inter_size = 13440
norm_eps = 1e-05
attn_bias = 1
start_id = 151643
end_id = 151645
session_len = 65544
weight_type = bf16
rotary_embedding = 128
rope_theta = 1000000.0
size_per_head = 128
group_size = 0
max_batch_size = 4
max_context_token_num = 1
step_length = 1
cache_max_entry_count = 0.8
cache_block_seq_len = 64
cache_chunk_size = -1
enable_prefix_caching = True
num_tokens_per_iter = 0
max_prefill_iters = 1
extra_tokens_per_iter = 0
use_context_fmha = 1
quant_policy = 8
max_position_embeddings = 65536
rope_scaling_factor = 0.0
use_dynamic_ntk = 0
use_logn_attn = 0
lora_policy = 
lora_r = 0
lora_scale = 0.0
lora_max_wo_r = 0
lora_rank_pattern = 
lora_scale_pattern = 

[TM][INFO] Set logger level by INFO
[TM][WARNING] [LlamaTritonModel] `max_context_token_num` = 65544.
[TM][WARNING] [LlamaTritonModel] `num_tokens_per_iter` is not set, default to `max_context_token_num` (65544).
Failed, NCCL error /lmdeploy/src/turbomind/utils/nccl_utils.cc:213 'unhandled cuda error (run with NCCL_DEBUG=INFO for details)'
[node116:1351893:0:1351893] Caught signal 4 (Illegal instruction: illegal operand)
==== backtrace (tid:1351893) ====
 0  /lib/libucs.so.0(ucs_handle_error+0x2e4) [0x7fd72aafaa84]
 1  /lib/libucs.so.0(+0x23aac) [0x7fd72aafbaac]
 2  /lib/libucs.so.0(+0x23b33) [0x7fd72aafbb33]
 3  /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7fda91371520]
 4  /usr/local/lib/python3.10/dist-packages/lmdeploy/lib/_turbomind.cpython-310-x86_64-linux-gnu.so(_ZN9turbomind14ftNcclGroupEndEv+0x36) [0x7fd931b9f9c6]
 5  /usr/local/lib/python3.10/dist-packages/lmdeploy/lib/_turbomind.cpython-310-x86_64-linux-gnu.so(_ZN24AbstractTransformerModel16createNcclParamsEiib+0x870) [0x7fd931acafa0]
 6  /usr/local/lib/python3.10/dist-packages/lmdeploy/lib/_turbomind.cpython-310-x86_64-linux-gnu.so(_ZN16LlamaTritonModelI13__nv_bfloat16E16createNcclParamsEiib+0x37b) [0x7fd931ad1cbb]
 7  /usr/local/lib/python3.10/dist-packages/lmdeploy/lib/_turbomind.cpython-310-x86_64-linux-gnu.so(+0xdd389) [0x7fd931ac4389]
 8  /usr/local/lib/python3.10/dist-packages/lmdeploy/lib/_turbomind.cpython-310-x86_64-linux-gnu.so(+0xd26e2) [0x7fd931ab96e2]
 9  /usr/bin/python3(+0x15a10e) [0x55cc1349510e]
10  /usr/bin/python3(_PyObject_MakeTpCall+0x25b) [0x55cc1348ba7b]
11  /usr/bin/python3(+0x168acb) [0x55cc134a3acb]
12  /usr/bin/python3(_PyEval_EvalFrameDefault+0x614a) [0x55cc13483cfa]
13  /usr/bin/python3(_PyFunction_Vectorcall+0x7c) [0x55cc134959fc]
14  /usr/bin/python3(_PyEval_EvalFrameDefault+0x8ac) [0x55cc1347e45c]
15  /usr/bin/python3(+0x1687f1) [0x55cc134a37f1]
16  /usr/bin/python3(_PyEval_EvalFrameDefault+0x198c) [0x55cc1347f53c]
17  /usr/bin/python3(_PyFunction_Vectorcall+0x7c) [0x55cc134959fc]
18  /usr/bin/python3(_PyObject_FastCallDictTstate+0x16d) [0x55cc1348acbd]
19  /usr/bin/python3(+0x164a64) [0x55cc1349fa64]
20  /usr/bin/python3(+0x150e2b) [0x55cc1348be2b]
21  /usr/bin/python3(PyObject_Call+0xbb) [0x55cc134a442b]
22  /usr/bin/python3(_PyEval_EvalFrameDefault+0x2a27) [0x55cc134805d7]
23  /usr/bin/python3(+0x1687f1) [0x55cc134a37f1]
24  /usr/bin/python3(PyObject_Call+0x122) [0x55cc134a4492]
25  /usr/bin/python3(_PyEval_EvalFrameDefault+0x2a27) [0x55cc134805d7]
26  /usr/bin/python3(+0x1687f1) [0x55cc134a37f1]
27  /usr/bin/python3(PyObject_Call+0x122) [0x55cc134a4492]
28  /usr/bin/python3(_PyEval_EvalFrameDefault+0x2a27) [0x55cc134805d7]
29  /usr/bin/python3(_PyFunction_Vectorcall+0x7c) [0x55cc134959fc]
30  /usr/bin/python3(_PyObject_FastCallDictTstate+0x16d) [0x55cc1348acbd]
31  /usr/bin/python3(+0x164a64) [0x55cc1349fa64]
32  /usr/bin/python3(+0x150e2b) [0x55cc1348be2b]
33  /usr/bin/python3(PyObject_Call+0xbb) [0x55cc134a442b]
34  /usr/bin/python3(_PyEval_EvalFrameDefault+0x2a27) [0x55cc134805d7]
35  /usr/bin/python3(_PyFunction_Vectorcall+0x7c) [0x55cc134959fc]
36  /usr/bin/python3(PyObject_Call+0x122) [0x55cc134a4492]
37  /usr/bin/python3(_PyEval_EvalFrameDefault+0x2a27) [0x55cc134805d7]
38  /usr/bin/python3(_PyFunction_Vectorcall+0x7c) [0x55cc134959fc]
39  /usr/bin/python3(_PyEval_EvalFrameDefault+0x614a) [0x55cc13483cfa]
40  /usr/bin/python3(_PyFunction_Vectorcall+0x7c) [0x55cc134959fc]
41  /usr/bin/python3(_PyEval_EvalFrameDefault+0x6bd) [0x55cc1347e26d]
42  /usr/bin/python3(+0x13f9c6) [0x55cc1347a9c6]
43  /usr/bin/python3(PyEval_EvalCode+0x86) [0x55cc13570256]
44  /usr/bin/python3(+0x260108) [0x55cc1359b108]
45  /usr/bin/python3(+0x2599cb) [0x55cc135949cb]
46  /usr/bin/python3(+0x25fe55) [0x55cc1359ae55]
47  /usr/bin/python3(_PyRun_SimpleFileObject+0x1a8) [0x55cc1359a338]
48  /usr/bin/python3(_PyRun_AnyFileObject+0x43) [0x55cc13599f83]
49  /usr/bin/python3(Py_RunMain+0x2be) [0x55cc1358ca5e]
50  /usr/bin/python3(Py_BytesMain+0x2d) [0x55cc1356302d]
51  /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7fda91358d90]
52  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7fda91358e40]
53  /usr/bin/python3(_start+0x25) [0x55cc13562f25]
=================================
Illegal instruction (core dumped)

### Reproduction

lmdeploy serve api_server /yzwl_data/yumu/model/CodeQwen1___5-7B-Chat --log-level INFO --backend turbomind --model-format hf --model-name qwen --server-port 23334 --tp 4 --max-batch-size 4 --quant-policy 8 --cache-max-entry-count 0.8 --enable-prefix-caching

### Environment

```Shell
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
```

### Error traceback

```Shell
2024-06-19 13:51:09,086 - lmdeploy - INFO - input chat_template_config=None
2024-06-19 13:51:11,931 - lmdeploy - INFO - updated chat_template_onfig=ChatTemplateConfig(model_name='qwen', system=None, meta_instruction=None, eosys=None, user=None, eoh=None, assistant=None, eoa=None, separator=None, capability=None, stop_words=None)
2024-06-19 13:51:11,933 - lmdeploy - WARNING - model_source: hf_model
2024-06-19 13:51:11,933 - lmdeploy - WARNING - model_name is deprecated in TurbomindEngineConfig and has no effect
2024-06-19 13:51:12,566 - lmdeploy - WARNING - model_config:

[llama]
model_name = qwen
tensor_para_size = 4
head_num = 32
kv_head_num = 4
vocab_size = 92416
num_layer = 32
inter_size = 13440
norm_eps = 1e-05
attn_bias = 1
start_id = 151643
end_id = 151645
session_len = 65544
weight_type = bf16
rotary_embedding = 128
rope_theta = 1000000.0
size_per_head = 128
group_size = 0
max_batch_size = 4
max_context_token_num = 1
step_length = 1
cache_max_entry_count = 0.8
cache_block_seq_len = 64
cache_chunk_size = -1
enable_prefix_caching = True
num_tokens_per_iter = 0
max_prefill_iters = 1
extra_tokens_per_iter = 0
use_context_fmha = 1
quant_policy = 8
max_position_embeddings = 65536
rope_scaling_factor = 0.0
use_dynamic_ntk = 0
use_logn_attn = 0
lora_policy = 
lora_r = 0
lora_scale = 0.0
lora_max_wo_r = 0
lora_rank_pattern = 
lora_scale_pattern = 


[TM][INFO] Set logger level by INFO
[TM][WARNING] [LlamaTritonModel] `max_context_token_num` = 65544.
[TM][WARNING] [LlamaTritonModel] `num_tokens_per_iter` is not set, default to `max_context_token_num` (65544).
Failed, NCCL error /lmdeploy/src/turbomind/utils/nccl_utils.cc:213 'unhandled cuda error (run with NCCL_DEBUG=INFO for details)'
[node116:1351893:0:1351893] Caught signal 4 (Illegal instruction: illegal operand)
==== backtrace (tid:1351893) ====
 0  /lib/libucs.so.0(ucs_handle_error+0x2e4) [0x7fd72aafaa84]
 1  /lib/libucs.so.0(+0x23aac) [0x7fd72aafbaac]
 2  /lib/libucs.so.0(+0x23b33) [0x7fd72aafbb33]
 3  /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7fda91371520]
 4  /usr/local/lib/python3.10/dist-packages/lmdeploy/lib/_turbomind.cpython-310-x86_64-linux-gnu.so(_ZN9turbomind14ftNcclGroupEndEv+0x36) [0x7fd931b9f9c6]
 5  /usr/local/lib/python3.10/dist-packages/lmdeploy/lib/_turbomind.cpython-310-x86_64-linux-gnu.so(_ZN24AbstractTransformerModel16createNcclParamsEiib+0x870) [0x7fd931acafa0]
 6  /usr/local/lib/python3.10/dist-packages/lmdeploy/lib/_turbomind.cpython-310-x86_64-linux-gnu.so(_ZN16LlamaTritonModelI13__nv_bfloat16E16createNcclParamsEiib+0x37b) [0x7fd931ad1cbb]
 7  /usr/local/lib/python3.10/dist-packages/lmdeploy/lib/_turbomind.cpython-310-x86_64-linux-gnu.so(+0xdd389) [0x7fd931ac4389]
 8  /usr/local/lib/python3.10/dist-packages/lmdeploy/lib/_turbomind.cpython-310-x86_64-linux-gnu.so(+0xd26e2) [0x7fd931ab96e2]
 9  /usr/bin/python3(+0x15a10e) [0x55cc1349510e]
10  /usr/bin/python3(_PyObject_MakeTpCall+0x25b) [0x55cc1348ba7b]
11  /usr/bin/python3(+0x168acb) [0x55cc134a3acb]
12  /usr/bin/python3(_PyEval_EvalFrameDefault+0x614a) [0x55cc13483cfa]
13  /usr/bin/python3(_PyFunction_Vectorcall+0x7c) [0x55cc134959fc]
14  /usr/bin/python3(_PyEval_EvalFrameDefault+0x8ac) [0x55cc1347e45c]
15  /usr/bin/python3(+0x1687f1) [0x55cc134a37f1]
16  /usr/bin/python3(_PyEval_EvalFrameDefault+0x198c) [0x55cc1347f53c]
17  /usr/bin/python3(_PyFunction_Vectorcall+0x7c) [0x55cc134959fc]
18  /usr/bin/python3(_PyObject_FastCallDictTstate+0x16d) [0x55cc1348acbd]
19  /usr/bin/python3(+0x164a64) [0x55cc1349fa64]
20  /usr/bin/python3(+0x150e2b) [0x55cc1348be2b]
21  /usr/bin/python3(PyObject_Call+0xbb) [0x55cc134a442b]
22  /usr/bin/python3(_PyEval_EvalFrameDefault+0x2a27) [0x55cc134805d7]
23  /usr/bin/python3(+0x1687f1) [0x55cc134a37f1]
24  /usr/bin/python3(PyObject_Call+0x122) [0x55cc134a4492]
25  /usr/bin/python3(_PyEval_EvalFrameDefault+0x2a27) [0x55cc134805d7]
26  /usr/bin/python3(+0x1687f1) [0x55cc134a37f1]
27  /usr/bin/python3(PyObject_Call+0x122) [0x55cc134a4492]
28  /usr/bin/python3(_PyEval_EvalFrameDefault+0x2a27) [0x55cc134805d7]
29  /usr/bin/python3(_PyFunction_Vectorcall+0x7c) [0x55cc134959fc]
30  /usr/bin/python3(_PyObject_FastCallDictTstate+0x16d) [0x55cc1348acbd]
31  /usr/bin/python3(+0x164a64) [0x55cc1349fa64]
32  /usr/bin/python3(+0x150e2b) [0x55cc1348be2b]
33  /usr/bin/python3(PyObject_Call+0xbb) [0x55cc134a442b]
34  /usr/bin/python3(_PyEval_EvalFrameDefault+0x2a27) [0x55cc134805d7]
35  /usr/bin/python3(_PyFunction_Vectorcall+0x7c) [0x55cc134959fc]
36  /usr/bin/python3(PyObject_Call+0x122) [0x55cc134a4492]
37  /usr/bin/python3(_PyEval_EvalFrameDefault+0x2a27) [0x55cc134805d7]
38  /usr/bin/python3(_PyFunction_Vectorcall+0x7c) [0x55cc134959fc]
39  /usr/bin/python3(_PyEval_EvalFrameDefault+0x614a) [0x55cc13483cfa]
40  /usr/bin/python3(_PyFunction_Vectorcall+0x7c) [0x55cc134959fc]
41  /usr/bin/python3(_PyEval_EvalFrameDefault+0x6bd) [0x55cc1347e26d]
42  /usr/bin/python3(+0x13f9c6) [0x55cc1347a9c6]
43  /usr/bin/python3(PyEval_EvalCode+0x86) [0x55cc13570256]
44  /usr/bin/python3(+0x260108) [0x55cc1359b108]
45  /usr/bin/python3(+0x2599cb) [0x55cc135949cb]
46  /usr/bin/python3(+0x25fe55) [0x55cc1359ae55]
47  /usr/bin/python3(_PyRun_SimpleFileObject+0x1a8) [0x55cc1359a338]
48  /usr/bin/python3(_PyRun_AnyFileObject+0x43) [0x55cc13599f83]
49  /usr/bin/python3(Py_RunMain+0x2be) [0x55cc1358ca5e]
50  /usr/bin/python3(Py_BytesMain+0x2d) [0x55cc1356302d]
51  /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7fda91358d90]
52  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7fda91358e40]
53  /usr/bin/python3(_start+0x25) [0x55cc13562f25]
=================================
Illegal instruction (core dumped)
```

**Comment by linyubupa** [comment]
the gpu device broken

**Comment by Greatpanc** [comment]
I meet the same problem。
![image](https://github.com/InternLM/lmdeploy/assets/38004594/579b3b84-c388-4d0a-ae90-2ca4e30c1aac)

env：
![image](https://github.com/InternLM/lmdeploy/assets/38004594/5838cb05-d634-4d62-be8b-fa395a2a56a4)

version：
0.4.2

**Comment by Greatpanc** [comment]
这个问题已经被修复了，该问题是由于nccl和cuda的版本不兼容导致的，可以通过重装nccl解决

通过设置：
export NCCL_DEBUG=INFO
可以看到日志为：
![img_v3_02c2_0e4fc61c-f3f1-4c08-81e3-787f0e62ce6g](https://github.com/InternLM/lmdeploy/assets/38004594/16099dfb-358c-4a76-9c18-39b81bd7a10d)
 我本地的cuda版本为12.2 和nccl不兼容，重装后问题被解决
