### ISSUE TITLE
GPU usage increasing continually while profile_serving benchmark

### ISSUE THREAD

**Issue by del-zhenwu** [InternLM/lmdeploy#182]
![20230731-135215](https://github.com/InternLM/lmdeploy/assets/56623710/96d73edf-1350-438f-8c60-25af099796ba)
with A GPU-card, concurrency from 1 to 16.
model: internlm-7b
infer mode: turbo.
branch: master

**Comment by tpoisonooo** [comment]
fp16 weight requires 16G, and each concurrency requires 1GB to save kv_cache. As the concurrency increases, a total of 30+ GB is normal. 

Try int8 quantization to save memory.

**Comment by tpoisonooo** [comment]
https://github.com/InternLM/lmdeploy/blob/main/docs/en/quantization.md
