### ISSUE TITLE
[Bug] TurboMind execute failure:  1

### ISSUE THREAD

**Issue by jingcheng88** [InternLM/lmdeploy#185]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

When i communicate with the inference server more than one round, there is an error. I must rest the session.

```
TurboMind execute failure:  1
07/31 12:28:43 - service.ft - ERROR - /usr/local/lib/python3.8/dist-packages/lmdeploy/serve/turbomind/chatbot.py - stream_consumer - 553 - got error from turbomind, code StatusCode.TRITON_SERVER_ERR, TurboMind execute failure:  1, token 677
```

### Reproduction

Communicate with the inference server more than one round.

**Comment by lvhan028** [comment]
Can you share your executing command?
I used to meet a similar issue. That's because I didn't specify cuda device when launching the triton inference server in the docker container. If this is your case, you can try the following: 
```
CUDA_VISIBLE_DEVICES=1 tirtonserver --model-repository=/the/path/of/triton/model_repository --allow-grpc=1 --grpc-port=33337
```

**Comment by jingcheng88** [comment]
> 

When i use ```docker run --gpus "devices=1"```, everything is OK.

How can i use multiple GPU? Will Lmdeploy support kubernetes?

**Comment by lvhan028** [comment]
We have no plans to support k8s. 
TurboMind can use multiple GPUs when tensor parallel inference is enabled. 
Since you mentioned k8s, I guess you are looking for a solution in the data parallel scenarios, in which the model instance is duplicated in several GPUs. But unfortunately, turbomind cannot support it now.
