### ISSUE TITLE
wrong about turbomind/triton_models

### ISSUE THREAD

**Issue by emmaduerresarai** [InternLM/lmdeploy#186]
when  i run :

python3 -m lmdeploy.serve.turbomind.deploy llama2 /llama-2-chat-7b-hf in openmmlab/lmdeploy:latest environment with one gpu

meet this error:
---------------
copy triton model templates from "/usr/local/lib/python3.8/dist-packages/lmdeploy/serve/turbomind/triton_models" to "./workspace/triton_models" failed: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/lmdeploy/serve/turbomind/triton_models

**Comment by lvhan028** [comment]
Can you try `openmmlab/lmdeploy:v0.0.2` instead? I am going go build the latest docker image soon

**Comment by emmaduerresarai** [comment]
ok ,it is fine
