### ISSUE TITLE
[Bug] InternVL 1.5性能瓶颈在ViT，有计划支持ViT TM backend+TP推理不？

### ISSUE THREAD

**Issue by DefTruth** [InternLM/lmdeploy#1869]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

针对InternVL 1.5进行了性能瓶颈分析，发现在BS大时，性能瓶颈为ViT 6B。机器L20x2，观察如下：

## InternVL 1.5测试

|bs|iters|平均输入长度|平均输出长度|平均ViT-6B耗时(s)|平均LLM-20B耗时(s)|平均整句耗时(s)|   
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|1|10|2598(2560+38)|101|1.53|3.87|5.4|
|2|10|2598(2560+38)|101|1.57|1.81|3.38|

## InternLM2 20B单独测试

|bs|iters|平均输入长度|平均输出长度|平均LLM-20B耗时(s)|平均整句耗时(s)|   
|:---:|:---:|:---:|:---:|:---:|:---:|
|1|10|2598|101|3.73|3.73|
|2|10|2598|101|2.17|2.17|

可以发现，只要BS=2，ViT模型的耗时在InternVL中占比接近50%，是目前的性能瓶颈。ViT-6B目前是pp2的方式使用HF来跑，性能很低，请问后续有计划支持ViT-6B模型使用TM backend+TP推理不？

### Reproduction

L20x2

### Environment

```Shell
v0.4.2
```

### Error traceback

```Shell
none
```

**Comment by irexyc** [comment]
把 VIT 模型 转成普通的 tensorrt 模型可能是比较好的做法，但我还没有比较过转好的模型与pytorch相比能有多少的提升。

**Comment by lvhan028** [comment]
我们目前没有对 ViT 优化的计划。
@irexyc 提到的转 tensorrt，是一种方案。tensorrt-llm 应该是使用的这种方式，你可以试试看。
