### ISSUE TITLE
return all tokens at once

### ISSUE THREAD

**Issue by lichangW** [InternLM/lmdeploy#189]
### Motivation

Hi, we want an interface to return all generated tokens at once but not in stream style, is there an example or document? Actually, we need a restful api from which we can put setting and prompt in requests and get all output tokens in one response. thanks for help!

**Comment by AllentDan** [comment]
The restful APIs were added.  For more details please refer to https://github.com/InternLM/lmdeploy/blob/main/docs/en/restful_api.md
