### ISSUE TITLE
[Feature] support InternVL-2.0

### ISSUE THREAD

**Issue by rTrQqgH74lc2PT5k** [InternLM/lmdeploy#1900]
### Motivation

internvl2.0会在本周发布，期待可以集成到 lmdeploy里面

### Related resources

参考: https://zhuanlan.zhihu.com/p/706547971

### Additional context

https://github.com/OpenGVLab/InternVL

**Comment by zhyncs** [comment]
InternVL is also an outstanding work of Shanghai AI Lab, which I believe will be supported soon😂

**Comment by lvhan028** [comment]
May try the latest nightly version from here: https://github.com/zhyncs/lmdeploy-build/tags
2B, 4B, 6B, 8B are supposed to work now
