### ISSUE TITLE
[Bug] ValueError: Tokenizer class Qwen2Tokenizer does not exist or is not currently imported.

### ISSUE THREAD

**Issue by zhyncs** [InternLM/lmdeploy#1903]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

```bash
python3 -m lmdeploy serve api_server Qwen2-72B-Instruct --tp 8
```

ref https://github.com/QwenLM/Qwen2/issues/34#issuecomment-1935786103

Maybe we should restrict the `transformers>=4.37.0`. Do you have any suggestions? Thanks. @grimoire @RunningLeon @lvhan028 

https://github.com/InternLM/lmdeploy/blob/c9c225fb3e1aa2cbfa654ec4a49b49d9b2a4fbbd/requirements/runtime.txt#L18

### Reproduction

transformers < 4.37.0

### Environment

```Shell
as mentioned above
```

**Comment by grimoire** [comment]
pytorch engine will perform the version check. Guess we should add checks in our tokenizer wrap too.

**Comment by zhyncs** [comment]
> pytorch engine will perform the version check. Guess we should add checks in our tokenizer wrap too.

ok!

**Comment by zhyncs** [comment]
Hi @grimoire Usually, when a LLM is released now, it is generally first submitted PR to transformers for support, and then the weights are released on Hugging Face. This means that it is actually possible to know from which version of `transformers` the model started to be supported. Should we consider maintaining something like a config.json, or should we handle issues as they arise? For example, in the case of qwen 2, check the tokenizer version so that the transformers version needs to be greater than a specific version.

**Comment by grimoire** [comment]
In my env-check, I try to load the config and transformers will do all other checks for me, including the version check.

https://github.com/InternLM/lmdeploy/blob/c9c225fb3e1aa2cbfa654ec4a49b49d9b2a4fbbd/lmdeploy/pytorch/check_env/__init__.py#L118-L127

That should be enough unless the model fills a wrong version in the config.

**Comment by zhyncs** [comment]
make sense

**Comment by zhyncs** [comment]
I'll land the version check code for TurboMind. Stay tuned.
