### ISSUE TITLE
[Bug] qwen2-0.5b-insturct

### ISSUE THREAD

**Issue by hyyuananran** [InternLM/lmdeploy#1910]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

RuntimeError:Failed to find C compiler. Please specify via CC environment variable

### Reproduction

RuntimeError:Failed to find C compiler. Please specify via CC environment variable

### Environment

```Shell
python38
cuda114
```

### Error traceback

```Shell
RuntimeError:Failed to find C compiler. Please specify via CC environment variable
```

**Comment by lvhan028** [comment]
麻烦提供完整的复现路径。
另外还请把执行 `lmdeploy check_env`的信息也贴上来，方便核对环境信息。

**Comment by hyyuananran** [comment]
感谢大佬您的关注
报错完整信息如下：
![t1](https://github.com/InternLM/lmdeploy/assets/132431095/cb2545e6-3a20-4187-bf2e-6e4e544a7f18)
![t2](https://github.com/InternLM/lmdeploy/assets/132431095/d2a49505-cae6-43a3-9ded-46f2a891d994)

镜像环境信息如下：
![t3](https://github.com/InternLM/lmdeploy/assets/132431095/77503713-17e1-48bd-a226-01d01f966b41)

**Comment by RunningLeon** [comment]
@hyyuananran for v100, pls try use triton==2.1.0.
