### ISSUE TITLE
是否会支持torch 2.3.0 和 triton 2.3.0

### ISSUE THREAD

**Issue by shell-nlp** [InternLM/lmdeploy#1914]
### Motivation

我使用的项目需要支持torch 2.3.0 和 triton 2.3.0 才可以运行，和lmdeploy 不兼容。

**Comment by lvhan028** [comment]
v0.5.0 是支持的。
因为它的性能没有torch2.2.2 + triton 2.2 好，所以我们在依赖项中仍然约束了是2.2.2
但是，用户仍然是可以选择升级的。
有一个类似的issue可以参考：#1857

**Comment by shell-nlp** [comment]
仍然希望可以支持torch 2.3.0 和 triton 2.3.0,  丢失一点性能和与其它系统兼容相比，觉得兼容性更重要

**Comment by lvhan028** [comment]
是已经支持了的。你可以手动更新 torch2.3和triton 2.3

**Comment by shell-nlp** [comment]
需要在requirements中放开对 torch triton
版本 的限制， pip instsll 安装 才不会报 依赖冲突的错误&nbsp; &nbsp;，



---原始邮件---
发件人: "Lyu ***@***.***&gt;
发送时间: 2024年7月23日(周二) 晚上11:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [InternLM/lmdeploy] 是否会支持torch 2.3.0 和 triton 2.3.0 (Issue #1914)




 
是已经支持了的。你可以手动更新 torch2.3和triton 2.3

**Comment by lvhan028** [comment]
抱歉，我们倾向于暂不放开

**Comment by WGS-note** [comment]
> v0.5.0 是支持的。 因为它的性能没有torch2.2.2 + triton 2.2 好，所以我们在依赖项中仍然约束了是2.2.2 但是，用户仍然是可以选择升级的。 有一个类似的issue可以参考：#1857

你好，我看v0.5.0的requirements里还是<=2.2.2啊，我也是项目需要2.3，不兼容了
