### ISSUE TITLE
关于internv2的支持

### ISSUE THREAD

**Issue by White-Friday** [InternLM/lmdeploy#1919]
### Motivation

请问咱们是否有计划支持[InternVL2-26B]

**Comment by lvhan028** [comment]
https://github.com/InternLM/lmdeploy/pull/1911 is addressing internvl2 feature

**Comment by lvhan028** [comment]
The PR is merged. You may try the latest main, or wait for the next release v0.5.1, which will be published in a week

**Comment by rTrQqgH74lc2PT5k** [comment]
> week

期待 v0.5.1版本的pip安装包更新

**Comment by zhyncs** [comment]
duplicate ref https://github.com/InternLM/lmdeploy/issues/1900

**Comment by zhyncs** [comment]
The main branch is now fully supported.
