### ISSUE TITLE
[Bug] how to set the max_batch_size

### ISSUE THREAD

**Issue by hudengjunai** [InternLM/lmdeploy#192]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

I run the benchmark on a800,but only get 1500token/second output .the gpu-mem is only use 50GB. I think the max_batch_size could be much larger. so how to change the max_batch_size?

### Reproduction

run interlm-7b-chat model

### Error traceback

```Shell
--------------------------------------------------
concurrency: 64, input_tokens: 512, output_tokens: 256
elapsed_time: 114.18s
first_token latency(min, max, ave): 5.57s, 11.93s, 11.12s
token latency(min, max, ave): 5.57s, 11.93s, 11.12s
throughput: 1467.354469605604 token/s
```

**Comment by lvhan028** [comment]
`max_batch_size` is configured in `workspace/triton_models/weights/config.ini`
