### ISSUE TITLE
[Bug] Encount TCP error (Port Aready used) when deploy with PytorchEngine 

### ISSUE THREAD

**Issue by Desein-Yang** [InternLM/lmdeploy#1925]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.

### Describe the bug

I use  PytorchEngineConfig(tp=NUM_GPUS,session_len=2048) to deploy int8 model and tp=2, then I found MASTER_PORT will default use 29500 and it is already used. 

### Reproduction

 71         self.gen_config = GenerationConfig(top_p=TOPP, top_k=TOPK,  temperature=TEMPERATURE,  max_new_tokens=MAX_NEW_TOKENS)
 72         chat_template_config = ChatTemplateConfig(TEMPLATE, stop_words=['<|im_end|>', '<|action_end|>', '</s>','<|endoftext|>'], capability='completion') # 0520 base 0510 yi_ies_cs
 73         self.pipe = pipeline(
 74             model_path,
 75             backend_config=backend_config,
 76             chat_template_config=chat_template_config
 77         )

### Environment

```Shell
not environment error
```

### Error traceback

```Shell
The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use)
```

**Comment by grimoire** [comment]
custom the port with env variable `MASTER_PORT`.

**Comment by Desein-Yang** [comment]
> custom the port with env variable `MASTER_PORT`.
代码中用 find_available_port 重置了外部 MASTER_PORT 因此无效
```
         port = _find_available_port()
1115         os.environ.setdefault('MASTER_ADDR', '127.0.0.1')
1116         os.environ.setdefault('MASTER_PORT', str(port))
1117         addr = os.environ['MASTER_ADDR']
1118         port = os.environ['MASTER_PORT']
1119         logger.info(f'MASTER_ADDR={addr}, MASTER_PORT={port}')
```

**Comment by lvhan028** [comment]
@Desein-Yang Is it still an issue? I noticed that you had closed a related PR (https://github.com/InternLM/lmdeploy/pull/1926)

**Comment by grimoire** [comment]
`setdefault` will only update MASTER_PORT if it is NOT given.
