### ISSUE TITLE
llmdeploy 使用openai形式提示词请求报错[Bug] 

### ISSUE THREAD

**Issue by hitzhu** [InternLM/lmdeploy#1939]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

使用llmdeploy部署internvl ，并使用官方openai 形式的提示词demo请求,后端报错
<img width="974" alt="image" src="https://github.com/InternLM/lmdeploy/assets/55450821/9644cb33-6417-4a39-b254-88234f57a752">
<img width="607" alt="image" src="https://github.com/InternLM/lmdeploy/assets/55450821/355056d5-15c7-4de6-bd71-7389842c5544">
<img width="716" alt="image" src="https://github.com/InternLM/lmdeploy/assets/55450821/b77f49ad-6e23-4a43-9b42-9a58d7166658">

### Reproduction

rt

### Environment

```Shell
rt
```

**Comment by lvhan028** [comment]
The `internvl2` feature has been implemented in the latest main branch, but hasn't been released yet. 
It is going to be released in v0.5.1 next week.

**Comment by zhyncs** [comment]
@hitzhu You can install the latest whl from https://github.com/zhyncs/lmdeploy-build/releases/tag/ab5b7ce

**Comment by hitzhu** [comment]
已解决，根据commit记录改源码就可以
