### ISSUE TITLE
多模态批推理如何实现？

### ISSUE THREAD

**Issue by DankoZhang** [InternLM/lmdeploy#1949]
### 📚 The doc issue

多模态批推理是通过如下脚本实现的吗？
<img width="1073" alt="image" src="https://github.com/InternLM/lmdeploy/assets/40423569/2daeec99-ade6-4107-899d-cfb6a2e7ede5">

如果是的话，传入batch的大小和TurbomindEngineConfig中的max_batch_size这个参数有关吗？

**Comment by irexyc** [comment]
运算流程为： 图片提特征 -> LLM

提特征完成的时间有先有后，如果第一个输入先完成提特征进入了LLM，则此时LLM无并发。第二个输入提完特征进入LLM，若此时第一个输入的LLM部分还没算完，则此时LLM部分有并发，若第一个输入的LLM部分已经完成，则此时的LLM部分还是没并发。

如果输入不包含图片的话，并发的概率比较高。图片的处理比较耗时，可能会影响LLM部分的并发。
