### ISSUE TITLE
[Bug] 请问如何启动运行webui？ 执行 python3 -m lmdeploy.app 192.168.1.15:33337 报错

### ISSUE THREAD

**Issue by mdys** [InternLM/lmdeploy#195]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

python3 -m lmdeploy.app 192.168.1.15:33337
请问如何启动 webui呢？ 文档没有看明白。。。麻烦能指导下 不尽感激

### Reproduction

python3 -m lmdeploy.app 192.168.1.15:33337

### Error traceback

```Shell
Traceback (most recent call last):
  File "/root/miniconda3/envs/funasr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/funasr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/funasr/lib/python3.10/site-packages/lmdeploy/app.py", line 169, in <module>
    fire.Fire(run)
  File "/root/miniconda3/envs/funasr/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/funasr/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/funasr/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/miniconda3/envs/funasr/lib/python3.10/site-packages/lmdeploy/app.py", line 115, in run
    _chatbot = Chatbot(triton_server_addr,
  File "/root/miniconda3/envs/funasr/lib/python3.10/site-packages/lmdeploy/serve/turbomind/chatbot.py", line 83, in __init__
    self.model_name = self._get_model_name()
  File "/root/miniconda3/envs/funasr/lib/python3.10/site-packages/lmdeploy/serve/turbomind/chatbot.py", line 313, in _get_model_name
    model_config = client.get_model_config(model_name='turbomind',
  File "/root/miniconda3/envs/funasr/lib/python3.10/site-packages/tritonclient/grpc/_client.py", line 506, in get_model_config
    raise_error_grpc(rpc_error)
  File "/root/miniconda3/envs/funasr/lib/python3.10/site-packages/tritonclient/grpc/_utils.py", line 62, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.UNAVAILABLE] failed to connect to all addresses; last error: UNKNOWN: ipv4:192.168.1.15:33337: Failed to connect to remote host: Connection refused

```
```

**Comment by AllentDan** [comment]
Can you start commands line client through `python3 -m lmdeploy.serve.client {server_ip_addresss}:33337`? You have to launch tritonserver first if you want to use it.
```shell
bash workspace/service_docker_up.sh
```

**Comment by zhangjunyi111** [comment]
> ### Checklist
> * [x]  1. I have searched related issues but cannot get the expected help.
> * [x]  2. The bug has not been fixed in the latest version.
> 
> ### Describe the bug
> python3 -m lmdeploy.app 192.168.1.15:33337 请问如何启动 webui呢？ 文档没有看明白。。。麻烦能指导下 不尽感激
> 
> ### Reproduction
> python3 -m lmdeploy.app 192.168.1.15:33337
> 
> ### Error traceback
> ```shell
> Traceback (most recent call last):
>   File "/root/miniconda3/envs/funasr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/root/miniconda3/envs/funasr/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/root/miniconda3/envs/funasr/lib/python3.10/site-packages/lmdeploy/app.py", line 169, in <module>
>     fire.Fire(run)
>   File "/root/miniconda3/envs/funasr/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
>     component_trace = _Fire(component, args, parsed_flag_args, context, name)
>   File "/root/miniconda3/envs/funasr/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
>     component, remaining_args = _CallAndUpdateTrace(
>   File "/root/miniconda3/envs/funasr/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
>     component = fn(*varargs, **kwargs)
>   File "/root/miniconda3/envs/funasr/lib/python3.10/site-packages/lmdeploy/app.py", line 115, in run
>     _chatbot = Chatbot(triton_server_addr,
>   File "/root/miniconda3/envs/funasr/lib/python3.10/site-packages/lmdeploy/serve/turbomind/chatbot.py", line 83, in __init__
>     self.model_name = self._get_model_name()
>   File "/root/miniconda3/envs/funasr/lib/python3.10/site-packages/lmdeploy/serve/turbomind/chatbot.py", line 313, in _get_model_name
>     model_config = client.get_model_config(model_name='turbomind',
>   File "/root/miniconda3/envs/funasr/lib/python3.10/site-packages/tritonclient/grpc/_client.py", line 506, in get_model_config
>     raise_error_grpc(rpc_error)
>   File "/root/miniconda3/envs/funasr/lib/python3.10/site-packages/tritonclient/grpc/_utils.py", line 62, in raise_error_grpc
>     raise get_error_grpc(rpc_error) from None
> tritonclient.utils.InferenceServerException: [StatusCode.UNAVAILABLE] failed to connect to all addresses; last error: UNKNOWN: ipv4:192.168.1.15:33337: Failed to connect to remote host: Connection refused
> ```

我也遇上的这个问题

**Comment by AllentDan** [comment]
Did you start the tritonserver through `bash workspace/service_docker_up.sh`?
