### ISSUE TITLE
[Feature] Is there any plan to support internvl2 inference?

### ISSUE THREAD

**Issue by zhaoning1987** [InternLM/lmdeploy#1953]
### Motivation

internvl2 has been just released, will it be supported soon, especially under turbomind backend?

**Comment by lvhan028** [comment]
The latest main has supported InternVL2, but hasn't been released yet.
We are going to release it in v0.5.1 before 16th, July. 
The InternVL2 series models except InternVL2-4B can be supported by turbomind engine, as the LLM model of InternVL-4B is phi3, which is not supported by turbomind yet.

**Comment by zhaoning1987** [comment]
> The latest main has supported InternVL2, but hasn't been released yet. We are going to release it in v0.5.1 before 16th, July. The InternVL2 series models except InternVL2-4B can be supported by turbomind engine, as the LLM model of InternVL-4B is phi3, which is not supported by turbomind yet.

赞！
