### ISSUE TITLE
[Feature] Can you please do INT4 Quantization for InternVL2-26B and InternVL2-40B

### ISSUE THREAD

**Issue by tairen99** [InternLM/lmdeploy#1955]
### Motivation

A series of Internvl2 models has been released, I compared their InternVL-8B which is not as good as your [INT4 Weight-only Quantization and Deployment (W4A16) ](https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5-AWQ) on some metrics. So  curious if the INT4 Quantization models of InternVL2-26B or 40B will be better or not.

Thank you all!

**Comment by AllentDan** [comment]
We did not test the them yet. Do you get any trouble doing awq quantization for the two models?

**Comment by BenjaminTamm** [comment]
Get the error : NameError: free variable 'state_dict' referenced before assignment in enclosing scope
When runing " lmdeploy lite auto_awq OpenGVLab/InternVL2-2B --work-dir internVL2-2b-4bit "



> We did not test the them yet. Do you get any trouble doing awq quantization for the two models?

**Comment by AllentDan** [comment]
It is a bug of the latest transformers. https://github.com/huggingface/transformers/issues/31685
Maybe you can downgrade the transformer version to 4.40-

**Comment by serser** [comment]
I've tested with AWQ with no errors.

**Comment by zhyncs** [comment]
@tairen99 40B works well with https://github.com/InternLM/lmdeploy/pull/2023
