### ISSUE TITLE
为什么离线转换lmdeploy convert不支持internlm2.5和Qwen2

### ISSUE THREAD

**Issue by wwwyfff** [InternLM/lmdeploy#1960]
### 📚 The doc issue

![issue](https://github.com/InternLM/lmdeploy/assets/120365110/e96b9d5f-9d1f-4e77-a0e7-c31c7e5c70c3)

AssertionError: 'internlm2_5-7b-chat’is not supported. The supported models are: dict keys(['base', 'llama'cogvlm', 'cogvlm2', 'vicuna", 'wizardlm', "llava-v1', 'mini-gemini-vicuna’, "internlm', "internlm- chat-7b'.
ternlm-chat', 'internlm-chat-7b-8k', "internlm-chat-28b'", "internlm-28b', "internIm2-1 8b', "internIm2-7b', 'internlm2-20b', 'internlm2','internlm2-chat', 'internlm2-chat-1 8b', 'internlm2-chat-7b'
"internvl-internlm2', "internlm-xcomposer2', "internlm-xcomposer2-4khd', "baichuan-base', 'baichuan-7b', 'baich
uan2'，'baichuan2-7b'，"puyu',"1lama2'，'1lama-2'，'llama-2-chat',
odellama','falcon','chatglm',"chatglm2-6b','solar',
-280k','yi-34b','Mistral-7B-Instruct', 'Mixtral-8x7B-Instruct', 'mistral', 'mixtral', 'gemma'
eepseek-chat','internvl-zh','deepseek-vl','deepseek-coder',"yi-vl',
rmes2'，'phi-3'，'chatglm3''glm4','internvl-phi3'])

**Comment by lvhan028** [comment]
Please try `lmdeploy convert internlm2 <the/path/of/internlm2_5-7b-chat>`

**Comment by lvhan028** [comment]
@wwwyfff I am going to close this issue. If you still reproduce it, don't hesitate to reopen it.
