### ISSUE TITLE
internvl 多图文使用openai 接口形式如何传数据[Bug] 

### ISSUE THREAD

**Issue by hitzhu** [InternLM/lmdeploy#1961]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

![image](https://github.com/InternLM/lmdeploy/assets/55450821/50ccfad9-9dbe-4940-8861-37a49dbb037a)使用如图所示的形式传图，模型返回的结果显示似乎只能注意到其中一张图，应该不是模型能力的问题，因为使用chat方式推理就ok

### Reproduction

rt

### Environment

```Shell
rt
```

**Comment by irexyc** [comment]
1. chat 方式是指 这里[https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5] 或者 [这里](https://huggingface.co/OpenGVLab/InternVL2-26B) 的chat么 ?

2. 你构造的messages格式不对，可以参考这里 https://platform.openai.com/docs/guides/vision/multiple-image-inputs

3. 如果要自定以图片在prompt中的位置，使用lmdeploy推理时，不能用 `<image>`，要用 `<IMAGE_TOKEN>`
