### ISSUE TITLE
[Bug] InternVL2-40B generates nonsense outputs

### ISSUE THREAD

**Issue by pseudotensor** [InternLM/lmdeploy#1965]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

See https://github.com/InternLM/lmdeploy/issues/1957 for docker build and run, but this time running like:

```

docker run -d --restart=always --runtime nvidia --gpus '"device=1,7"' \
    -v $HOME/.cache/huggingface:/root/.cache/huggingface \
    --env "HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN" \
    -p 30000:23333 \
    --ipc=host \
    --name internvl40_lmdeploy \
    internvlmain2 \
    lmdeploy serve api_server OpenGVLab/InternVL2-40B --model-name OpenGVLab/InternVL2-40B --tp 2
```

But with:
```
from openai import OpenAI

base_url = '<fill me>'

api_key = 'EMPTY'
client_args = dict(base_url=base_url, api_key=api_key)
openai_client = OpenAI(**client_args)

messages = [{'role': 'user', 'content': 'Who are you?'}]
stream = False
client_kwargs = dict(model='OpenGVLab/InternVL2-40B', max_tokens=200, stream=stream, messages=messages)
client = openai_client.chat.completions

responses = client.create(**client_kwargs)
text = responses.choices[0].message.content
print(text)
```
I get:

```
 leadersCFCF铁路disdisdisdis雪雪雪雪雪雪雪雪雪雪雪雪雪雪 hairyabababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababab
```

or other random variants.

I understand it's an SFT model not a chat model, but it seems lmdeploy still exposes the chat API.  But is something wrong with the model, or does it have no real chat template, or is using the SFT model like this a bad idea?  I can't quite understand the situation. Thanks!

### Reproduction

above

### Environment

```Shell
See https://github.com/InternLM/lmdeploy/issues/1957 for docker build and run, but this time running like:
```

### Error traceback

```Shell
none
```

**Comment by pseudotensor** [comment]
By contrast, the 26B model has no issue.  Will try 26B with --tp 2.

**Comment by pseudotensor** [comment]
--tp 2 with 26B model works fine, so it seems like purely a 40B model issue.

**Comment by zhyncs** [comment]
> By contrast, the 26B model has no issue. Will try 26B with --tp 2.

cc @day9011 https://github.com/InternLM/lmdeploy/issues/1959#issuecomment-2216690063

I'm a little confused 😂 cc @irexyc @lzhangzz

**Comment by hitzhu** [comment]
40B released? when and where?

**Comment by zhyncs** [comment]
> 40B released? when and where?

https://huggingface.co/OpenGVLab/InternVL2-40B

**Comment by hitzhu** [comment]
> > 40B released? when and where?
> 
> https://huggingface.co/OpenGVLab/InternVL2-40B

国内魔塔看还没有

**Comment by day9011** [comment]
> > By contrast, the 26B model has no issue. Will try 26B with --tp 2.
> 
> cc @day9011 [#1959 (comment)](https://github.com/InternLM/lmdeploy/issues/1959#issuecomment-2216690063)
> 
> I'm a little confused 😂 cc @irexyc @lzhangzz

我尝试了--tp 2，是正常了
![image](https://github.com/InternLM/lmdeploy/assets/6396215/464a96f5-559b-476b-81a1-6ff0a5f00f35)

**Comment by lvhan028** [comment]
> --tp 2 with 26B model works fine, so it seems like purely a 40B model issue.

Yes. There is sth wrong with InternVL2-40B inference. 
@irexyc Please investigate this issue.

**Comment by irexyc** [comment]
The problem is caused by using the wrong `tie_word_embeddings` when convert the model.

**Comment by zhyncs** [comment]
fixed at https://github.com/InternLM/lmdeploy/pull/1979

Hi @pseudotensor May you try the latest commit https://github.com/zhyncs/lmdeploy-build/releases/tag/ff2e307

**Comment by pseudotensor** [comment]
Yes, plan to try soon.  I already built the needed docker image.

**Comment by zhyncs** [comment]
fixed at https://github.com/InternLM/lmdeploy/pull/2023
