### ISSUE TITLE
[Feature] 是否能支持MiniCPMv2.5

### ISSUE THREAD

**Issue by LDLINGLINGLING** [InternLM/lmdeploy#1969]
### Motivation

want to add support for MiniCPMV2.5

### Related resources

https://huggingface.co/openbmb/MiniCPM-Llama3-V-2_5

### Additional context

minicpmv2.5 在多模态领域效果非常好，而且参数量也不大，能否增加支持。

**Comment by irexyc** [comment]
It is already supported, you can see the VLMs part of this link

https://github.com/InternLM/lmdeploy?tab=readme-ov-file#supported-models
