### ISSUE TITLE
[Feature] tubromind有计划支持cogvlm2吗？

### ISSUE THREAD

**Issue by jidechao** [InternLM/lmdeploy#1970]
### Motivation

目前采用lmdeploy部署cogvlm2，推理速度有点慢，看了源码，貌似是如果使用tubromind，则自动转换为pytorch推理。后续有计划支持tubromind吗？

**Comment by lvhan028** [comment]
The roadmap of turbomind is as follows:
- optimize GEMM(hopefully we can integrate the feature this month) 
- support  MOE model architecture
- refactor turbomind structure to better accommodate LLMs
- merging turbomind's cuda kernels into pytorch engine

Therefore, we will not be considering the addition of  models such as cogvlm2 until the aforementioned tasks are completed.
