### ISSUE TITLE
[Bug] The official documentation does not automatically update

### ISSUE THREAD

**Issue by zhyncs** [InternLM/lmdeploy#1975]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

README
https://github.com/InternLM/lmdeploy/blob/main/README.md

latest doc
https://lmdeploy.readthedocs.io/en/latest/

As you can see, I added a section called "Excellent Compatibility" in the README, but it did not show up in the latest documentation. @RunningLeon 

### Reproduction

N/A

### Environment

```Shell
N/A
```

### Error traceback

```Shell
N/A
```

**Comment by zhyncs** [comment]
![](https://github.com/InternLM/lmdeploy/assets/46627482/07fe1c98-b74c-400b-a641-56c9c09c386b)
![](https://github.com/InternLM/lmdeploy/assets/46627482/ee96cd7f-a4b1-4525-8b45-61473816809c)

**Comment by RunningLeon** [comment]
@zhyncs hi, thanks for your info. Actually, README.md is not included in readthedocs as you can see the [index.rst](https://github.com/InternLM/lmdeploy/blob/main/docs/en/index.rst). You need to update the index.rst file

**Comment by zhyncs** [comment]
Hi @RunningLeon Should I add the README.md to the index.rst or just update the compatibility section at index.rst
Do you have any suggestions?

**Comment by RunningLeon** [comment]
maybe just update the section in index.rst. README.md is for github and would not be included in index.rst for now.

**Comment by zhyncs** [comment]
OK
