### ISSUE TITLE
[Bug] Mini-InternVL-Chat-2B-V1-5 AWQ量化尝试：NameError: free variable 'state_dict' referenced before assignment in enclosing scope

### ISSUE THREAD

**Issue by crazy-wq** [InternLM/lmdeploy#1978]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

我在尝试着在A800 80G服务器上进行 按照这个 https://mp.weixin.qq.com/s/3kB-cjIc9Tz23HiBfj1Xpg对Mini-InternVL-Chat-2B-V1-5进行量化，只是量化到最后保存模型出现了这个，有遇到过的么？
NameError: free variable 'state_dict' referenced before assignment in enclosing scope

使用的命令就是公众号这行下的命令
用户可以一行命令量化一个 VL 模型，以 Mini-InternVL-Chat-2B-V1-5 为例：

### Reproduction

export HF_MODEL=OpenGVLab/Mini-InternVL-Chat-2B-V1-5
export WORK_DIR=Mini-InternVL-Chat-2B-V1-5-4bit

lmdeploy lite auto_awq \
   $HF_MODEL \
  --calib-dataset 'ptb' \
  --calib-samples 128 \
  --calib-seqlen 2048 \
  --w-bits 4 \
  --w-group-size 128 \
  --batch-size 1 \
  --search-scale False \
  --work-dir $WORK_DIR

### Environment

```Shell
`lmdeploy check_env`
sys.platform: linux
Python: 3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA A800-SXM4-80GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.0, V12.0.140
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 2.2.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

TorchVision: 0.17.2+cu121
LMDeploy: 0.5.0+
transformers: 4.42.3
gradio: Not Found
fastapi: 0.111.0
pydantic: 2.8.2
triton: 2.2.0
```

### Error traceback

```Shell
cated cpu memory exceeds the `shard_size` (5GB default)
  warnings.warn(
Traceback (most recent call last):
  File "/root/miniconda3/envs/lmdeploy/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/root/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/cli/entrypoint.py", line 43, in run
    args.run(args)
  File "/root/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/cli/lite.py", line 139, in auto_awq
    auto_awq(**kwargs)
  File "/root/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/lite/apis/auto_awq.py", line 148, in auto_awq
    save_vl_model(vl_model, model_path, work_dir)
  File "/root/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/lite/apis/auto_awq.py", line 45, in save_vl_model
    vl_model.save_pretrained(dst_path,
  File "/root/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2661, in save_pretrained
    shard = {tensor: state_dict[tensor] for tensor in tensors}
  File "/root/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2661, in <dictcomp>
    shard = {tensor: state_dict[tensor] for tensor in tensors}
NameError: free variable 'state_dict' referenced before assignment in enclosing scope
```

**Comment by sxlyiyiyi** [comment]
> ### Checklist
> * [ ]  1. I have searched related issues but cannot get the expected help.
> * [ ]  2. The bug has not been fixed in the latest version.
> 
> ### Describe the bug
> 我在尝试着在A800 80G服务器上进行 按照这个 [https://mp.weixin.qq.com/s/3kB-cjIc9Tz23HiBfj1Xpg对Mini-InternVL-Chat-2B-V1-5进行量化，只是量化到最后保存模型出现了这个，有遇到过的么？](https://mp.weixin.qq.com/s/3kB-cjIc9Tz23HiBfj1Xpg%E5%AF%B9Mini-InternVL-Chat-2B-V1-5%E8%BF%9B%E8%A1%8C%E9%87%8F%E5%8C%96%EF%BC%8C%E5%8F%AA%E6%98%AF%E9%87%8F%E5%8C%96%E5%88%B0%E6%9C%80%E5%90%8E%E4%BF%9D%E5%AD%98%E6%A8%A1%E5%9E%8B%E5%87%BA%E7%8E%B0%E4%BA%86%E8%BF%99%E4%B8%AA%EF%BC%8C%E6%9C%89%E9%81%87%E5%88%B0%E8%BF%87%E7%9A%84%E4%B9%88%EF%BC%9F) NameError: free variable 'state_dict' referenced before assignment in enclosing scope
> 
> 使用的命令就是公众号这行下的命令 用户可以一行命令量化一个 VL 模型，以 Mini-InternVL-Chat-2B-V1-5 为例：
> 
> ### Reproduction
> export HF_MODEL=OpenGVLab/Mini-InternVL-Chat-2B-V1-5 export WORK_DIR=Mini-InternVL-Chat-2B-V1-5-4bit
> 
> lmdeploy lite auto_awq $HF_MODEL --calib-dataset 'ptb' --calib-samples 128 --calib-seqlen 2048 --w-bits 4 --w-group-size 128 --batch-size 1 --search-scale False --work-dir $WORK_DIR
> 
> ### Environment
> ```shell
> `lmdeploy check_env`
> sys.platform: linux
> Python: 3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0]
> CUDA available: True
> MUSA available: False
> numpy_random_seed: 2147483648
> GPU 0,1,2,3,4,5,6,7: NVIDIA A800-SXM4-80GB
> CUDA_HOME: /usr/local/cuda
> NVCC: Cuda compilation tools, release 12.0, V12.0.140
> GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
> PyTorch: 2.2.2+cu121
> PyTorch compiling details: PyTorch built with:
>   - GCC 9.3
>   - C++ Version: 201703
>   - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
>   - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
>   - OpenMP 201511 (a.k.a. OpenMP 4.5)
>   - LAPACK is enabled (usually provided by MKL)
>   - NNPACK is enabled
>   - CPU capability usage: AVX512
>   - CUDA Runtime 12.1
>   - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
>   - CuDNN 8.9.2
>   - Magma 2.6.1
>   - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 
> 
> TorchVision: 0.17.2+cu121
> LMDeploy: 0.5.0+
> transformers: 4.42.3
> gradio: Not Found
> fastapi: 0.111.0
> pydantic: 2.8.2
> triton: 2.2.0
> ```
> 
> ### Error traceback
> ```shell
> cated cpu memory exceeds the `shard_size` (5GB default)
>   warnings.warn(
> Traceback (most recent call last):
>   File "/root/miniconda3/envs/lmdeploy/bin/lmdeploy", line 8, in <module>
>     sys.exit(run())
>   File "/root/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/cli/entrypoint.py", line 43, in run
>     args.run(args)
>   File "/root/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/cli/lite.py", line 139, in auto_awq
>     auto_awq(**kwargs)
>   File "/root/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/lite/apis/auto_awq.py", line 148, in auto_awq
>     save_vl_model(vl_model, model_path, work_dir)
>   File "/root/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/lite/apis/auto_awq.py", line 45, in save_vl_model
>     vl_model.save_pretrained(dst_path,
>   File "/root/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2661, in save_pretrained
>     shard = {tensor: state_dict[tensor] for tensor in tensors}
>   File "/root/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2661, in <dictcomp>
>     shard = {tensor: state_dict[tensor] for tensor in tensors}
> NameError: free variable 'state_dict' referenced before assignment in enclosing scope
> ```

请问解决了吗

**Comment by crazy-wq** [comment]
> > ### Checklist
> > 
> > * [ ]   1. I have searched related issues but cannot get the expected help.
> > * [ ]   2. The bug has not been fixed in the latest version.
> > 
> > ### Describe the bug
> > 我在尝试着在A800 80G服务器上进行 按照这个 [https://mp.weixin.qq.com/s/3kB-cjIc9Tz23HiBfj1Xpg对Mini-InternVL-Chat-2B-V1-5进行量化，只是量化到最后保存模型出现了这个，有遇到过的么？](https://mp.weixin.qq.com/s/3kB-cjIc9Tz23HiBfj1Xpg%E5%AF%B9Mini-InternVL-Chat-2B-V1-5%E8%BF%9B%E8%A1%8C%E9%87%8F%E5%8C%96%EF%BC%8C%E5%8F%AA%E6%98%AF%E9%87%8F%E5%8C%96%E5%88%B0%E6%9C%80%E5%90%8E%E4%BF%9D%E5%AD%98%E6%A8%A1%E5%9E%8B%E5%87%BA%E7%8E%B0%E4%BA%86%E8%BF%99%E4%B8%AA%EF%BC%8C%E6%9C%89%E9%81%87%E5%88%B0%E8%BF%87%E7%9A%84%E4%B9%88%EF%BC%9F) NameError: free variable 'state_dict' referenced before assignment in enclosing scope
> > 使用的命令就是公众号这行下的命令 用户可以一行命令量化一个 VL 模型，以 Mini-InternVL-Chat-2B-V1-5 为例：
> > ### Reproduction
> > export HF_MODEL=OpenGVLab/Mini-InternVL-Chat-2B-V1-5 export WORK_DIR=Mini-InternVL-Chat-2B-V1-5-4bit
> > lmdeploy lite auto_awq $HF_MODEL --calib-dataset 'ptb' --calib-samples 128 --calib-seqlen 2048 --w-bits 4 --w-group-size 128 --batch-size 1 --search-scale False --work-dir $WORK_DIR
> > ### Environment
> > ```shell
> > `lmdeploy check_env`
> > sys.platform: linux
> > Python: 3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0]
> > CUDA available: True
> > MUSA available: False
> > numpy_random_seed: 2147483648
> > GPU 0,1,2,3,4,5,6,7: NVIDIA A800-SXM4-80GB
> > CUDA_HOME: /usr/local/cuda
> > NVCC: Cuda compilation tools, release 12.0, V12.0.140
> > GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
> > PyTorch: 2.2.2+cu121
> > PyTorch compiling details: PyTorch built with:
> >   - GCC 9.3
> >   - C++ Version: 201703
> >   - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
> >   - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
> >   - OpenMP 201511 (a.k.a. OpenMP 4.5)
> >   - LAPACK is enabled (usually provided by MKL)
> >   - NNPACK is enabled
> >   - CPU capability usage: AVX512
> >   - CUDA Runtime 12.1
> >   - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
> >   - CuDNN 8.9.2
> >   - Magma 2.6.1
> >   - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 
> > 
> > TorchVision: 0.17.2+cu121
> > LMDeploy: 0.5.0+
> > transformers: 4.42.3
> > gradio: Not Found
> > fastapi: 0.111.0
> > pydantic: 2.8.2
> > triton: 2.2.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Error traceback
> > ```shell
> > cated cpu memory exceeds the `shard_size` (5GB default)
> >   warnings.warn(
> > Traceback (most recent call last):
> >   File "/root/miniconda3/envs/lmdeploy/bin/lmdeploy", line 8, in <module>
> >     sys.exit(run())
> >   File "/root/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/cli/entrypoint.py", line 43, in run
> >     args.run(args)
> >   File "/root/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/cli/lite.py", line 139, in auto_awq
> >     auto_awq(**kwargs)
> >   File "/root/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/lite/apis/auto_awq.py", line 148, in auto_awq
> >     save_vl_model(vl_model, model_path, work_dir)
> >   File "/root/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/lite/apis/auto_awq.py", line 45, in save_vl_model
> >     vl_model.save_pretrained(dst_path,
> >   File "/root/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2661, in save_pretrained
> >     shard = {tensor: state_dict[tensor] for tensor in tensors}
> >   File "/root/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2661, in <dictcomp>
> >     shard = {tensor: state_dict[tensor] for tensor in tensors}
> > NameError: free variable 'state_dict' referenced before assignment in enclosing scope
> > ```
>  
> 请问解决了吗

嗯，已解决，参见https://github.com/InternLM/lmdeploy/issues/1955#issuecomment-2217001823
将transformers版本降级为4.40后，正常使用
