### ISSUE TITLE
[Feature] 可否开放C语言 的API

### ISSUE THREAD

**Issue by wenjunlong** [InternLM/lmdeploy#198]
### Motivation

很多生产场景更适合使用C或者C++来进行开发。如果有C语言接口，甚至可以集成到更多的语言平台中。
项目中的example中也有一个C++的例子，但是似乎缺了部分文件。我理解C 的接口可以基于类似的方法封装出来。

**Comment by lvhan028** [comment]
我们没有C API的计划。你看下 [llama2.c](https://github.com/karpathy/llama2.c) 或者 [llama.cpp](https://github.com/ggerganov/llama.cpp) 能不能帮到你呢？

**Comment by wenjunlong** [comment]
> 我们没有C API的计划。你看下 [llama2.c](https://github.com/karpathy/llama2.c) 或者 [llama.cpp](https://github.com/ggerganov/llama.cpp) 能不能帮到你呢？

那我想再请教一下，这个库的基本推理部分有没有依赖于torch或者其他python库，还是说是纯C++实现？如果是后者的话，或许我可以自己实现C++的API

**Comment by tpoisonooo** [comment]
> 

推理部分 turbomind 是纯 C++。

**Comment by wenjunlong** [comment]
> > 
> 
> 推理部分 turbomind 是纯 C++。

如果我基于llama_triton_example.cc这个文件中的例子来实现C++调用，是否可以获得Performance部分中说到的性能呢？

“The output token throughput of TurboMind exceeds 2000 tokens/s, which is about 5% - 15% higher than DeepSpeed overall and outperforms huggingface transformers by up to 2.3x. And the request throughput of TurboMind is 30% higher than vLLM.”

**Comment by lvhan028** [comment]
是的。测的就是 llama_triton_example.cc。python api的结果和它也差不多，大概会降 2-5%
