### ISSUE TITLE
[Feature] 为internVL2添加function calling能力（Tools能力）

### ISSUE THREAD

**Issue by kong1414** [InternLM/lmdeploy#1987]
### Motivation

按照文档所说，目前的 LMDeploy 只支持 InternLM2 或者 InternLM2.5 模型的工具调用。
我了解到 internVL2是由 InternViT-6B-448px-V1-5 + MLP + internlm2-chat-20b 组合而成，是否意味着也能支持工具调用能力？

### Related resources

lmdelploy文档：https://lmdeploy.readthedocs.io/zh-cn/latest/serving/api_server_tools.html
InternVL2模型地址介绍：https://huggingface.co/OpenGVLab/InternVL2-26B

**Comment by lvhan028** [comment]
目前，我们暂没有为其他模型添加 function call功能的计划。
感兴趣的话，不妨自己参考 PR #1763 试着实现下

**Comment by kong1414** [comment]
您好，您的邮件我已经收到，我会尽快查看，谢谢！
