### ISSUE TITLE
[Feature] 我们支持gptq量化模型的推理么

### ISSUE THREAD

**Issue by eigen2017** [InternLM/lmdeploy#1989]
### Motivation

只见对awq的支持，未见对gptq的探讨

**Comment by zhyncs** [comment]
Not yet. Moreover, both GPTQ and AWQ are W4A16, GPTQ has no advantages in accuracy and performance.

**Comment by eigen2017** [comment]
but awq cannot run on gpu v100

**Comment by eigen2017** [comment]
技术咨询您一下 @zhyncs 
比如这个模型
https://huggingface.co/Phind/Phind-CodeLlama-34B-v2
我只有4卡v100共64G显存，想做int4量化，lmdeploy有啥方案没。

**Comment by zhyncs** [comment]
> but awq cannot run on gpu v100

Since I don't have a development environment for V100. Can you refer to this link https://lmdeploy.readthedocs.io/en/latest/quantization/w4a16.html and try it on V100? Please paste the error log. Thanks.

**Comment by eigen2017** [comment]
@zhyncs 麻烦科普一下W4A16，W8A8分别是啥意思。

**Comment by zhyncs** [comment]
W4A16 (4-bit weight, 16-bit activation). W8A8 is similar.

**Comment by zhyncs** [comment]
> Not yet. Moreover, both GPTQ and AWQ are W4A16, GPTQ has no advantages in accuracy and performance.

ref https://friendli.ai/blog/quantization-reduce-llm-size/

**Comment by lzhangzz** [comment]
#2090 adds support for both AWQ and GPTQ models on V100.

**Comment by eigen2017** [comment]
> #2090 adds support for both AWQ and GPTQ models on V100.

great thanks to this pr！

**Comment by eigen2017** [comment]
i saw this pr merged,
https://github.com/InternLM/lmdeploy/pull/2090
so i'll try this gptq model on v100:
https://huggingface.co/TheBloke/Phind-CodeLlama-34B-v2-GPTQ
if succeeded, i'll give a report here and close this issue.

thanks to you all for this great efforts!
@lzhangzz @zhyncs

**Comment by zhyncs** [comment]
Please try v0.6.0a https://github.com/InternLM/lmdeploy/releases/tag/v0.6.0a0

**Comment by eigen2017** [comment]
@zhyncs hi~~ 拉起来报错。

因为060a版本在pypi上没有，所以无法pip install，我从源码安装的，执行的：
cd /opt/lmdeploy
mkdir -p build && cd build
bash ../generate.sh make
make -j$(nproc) && make install
cd ..
pip install -e .

然后在各种报错的引导下，我改了模型的这几处配置：
![微信图片_20240830223657](https://github.com/user-attachments/assets/bd52c14d-2ed4-4edc-936f-8fb44881fb5c)
bf16改为fp16、量化配置group_size从-1改为了128、desc_act true改为false

这里插播一下，在上述修改后，vllm（注意我说的不是lmd）拉起来会报下面的错误：
![vllm](https://github.com/user-attachments/assets/e371b07e-f4f8-4ef6-816a-a879f1be7017)


好，我们再回到lmd。改完配置后，变成了下面这个错误：
![err](https://github.com/user-attachments/assets/9ad7aecd-6365-4217-8a88-be9a9bccd08c)


对全是拍照表示歉意，因为v100是公司内网才能访问，谢谢！

**Comment by lzhangzz** [comment]
@eigen2017 

目前 GPTQ 只支持 group_size=128, desc_act=False 的情况（大部分 Qwen 系列提供的 GPTQ 版本模型）。 直接改 quantization config 不能改变权重本身的性质。

group_size=-1 的模型可以把 scales 和 qzeros 重复 ceil_div(input_dims, 128) 遍转成 group_size=128 的。desc_act 需要多几个重排操作，目前还没有实现。

**Comment by lvhan028** [comment]
"060a版本在pypi上没有" 
是有的 `pip install lmdeploy==0.6.0a0`

**Comment by eigen2017** [comment]
> @eigen2017
> 
> 目前 GPTQ 只支持 group_size=128, desc_act=False 的情况（大部分 Qwen 系列提供的 GPTQ 版本模型）。 直接改 quantization config 不能改变权重本身的性质。
> 
> group_size=-1 的模型可以把 scales 和 qzeros 重复 ceil_div(input_dims, 128) 遍转成 group_size=128 的。desc_act 需要多几个重排操作，目前还没有实现。

所以，这个phind目前还不能lmd加速对吧：
https://huggingface.co/TheBloke/Phind-CodeLlama-34B-v2-GPTQ
