### ISSUE TITLE
AWQ quantized model produces garbled output during multi-GPU inference

### ISSUE THREAD

**Issue by nzomi** [InternLM/lmdeploy#1996]
Dear Developer, I attempted to use AWQ to quantize the internlmxcomposer-4khd model. The results are normal during single-GPU inference, but when using multiple GPUs, the output is completely garbled. Could you please let me know if the reason is that multi-GPU inference is currently not supported?

**Comment by irexyc** [comment]
Please update corresponding file like this.

https://github.com/InternLM/lmdeploy/pull/1932/commits/67f343dbfe23d24fbbb57348cae243b7f116d5a7

**Comment by nzomi** [comment]
@irexyc Thank you for your quick response; it indeed solved the issue. However, I noticed that multi-GPU inference did not accelerate the quantized model. The bottleneck seems to be on the CPU, with all computations being handled by a single CPU, resulting in very high usage of that CPU while the others are at 0%. Do you have any suggestions?

**Comment by irexyc** [comment]
The VLMs model have two parts: vision and llm. We have not optimize the vision part and only the llm part will be benefits by awq. 

Currently, we combine the vision as llm as a pipeline for convenience. In the pipeline, only the preprocess of vision model require much cpu resource. It might be a better choice to split vision and llm into two services for productive use. 

In my test on A100, the awq model with tp=2 use less time than tp=1. I don't know how you do the test, but for a fair comparison, you should use same `max_new_tokens` and set `ignore_eos` to `True` in `GenerationConfig` to make the models have same length of output.

There are some benchmark scripts https://github.com/InternLM/lmdeploy/tree/main/benchmark which you can test the llm part of the model.

**Comment by nzomi** [comment]
Thank you for the response. It does indeed speed up, but not as significantly as the non-quantized model.
