### ISSUE TITLE
lmdeploy serve的并发机制是怎样的

### ISSUE THREAD

**Issue by sunzx8** [InternLM/lmdeploy#1997]
请问如果用lmdeploy serve时面对多个请求是怎么处理的？是一定要用这个请求分发服务器才能并发处理吗？
<img width="852" alt="image" src="https://github.com/InternLM/lmdeploy/assets/136688632/874106a8-cde4-4d82-8cae-59341b1f2d82">

**Comment by zhyncs** [comment]
ref https://github.com/InternLM/lmdeploy/blob/ff2e307f82282e2190340b0586616e16b3a3d9eb/docs/en/inference/turbomind.md?plain=1#L29-L34

**Comment by AllentDan** [comment]
不用，正常 `lmdeploy serve api_server` 启动的服务就是可以支持并发请求

**Comment by sunzx8** [comment]
> 不用，正常 `lmdeploy serve api_server` 启动的服务就是可以支持并发请求

谢谢您，请问该如何设置最高并发数来防止oom这种情况出现，还是说本身就会防止这种现象？

**Comment by AllentDan** [comment]
显存量是启动分配好的，不会随着服务运行提高。

**Comment by sunzx8** [comment]
> 显存量是启动分配好的，不会随着服务运行提高。

谢谢，请问设置这个数值的代码具体在什么位置可以quote一下吗？

**Comment by AllentDan** [comment]
https://lmdeploy.readthedocs.io/en/latest/serving/api_server.html#option-1-launching-with-lmdeploy-cli
