### ISSUE TITLE
[Bug] 部署经过微调的internvl-chat-v1_5模型导致无法停止输出。

### ISSUE THREAD

**Issue by Halflifefa** [InternLM/lmdeploy#2000]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

使用swift微调了internvl-chat-v1_5，没有改提示词模板，合并lora后用lmdeploy部署。出现如下问题：
1. 获取模型输出时会直接卡死，没有任何响应，查阅issue后添加--session-len 32776 --num-tokens-per-iter 8192解决该问题
2. 模型输出无法停止，看起来像是无法获取stop token
3. 输出质量相比transformers直接推理下降较多，用起来更像是一个预训练模型，而非chat，一直答非所问

### Reproduction

无

### Environment

```Shell
0.4.2版本
```

**Comment by irexyc** [comment]
可以把模型放到hf上面么？

**Comment by Halflifefa** [comment]
> 可以把模型放到hf上面么？

已经解决了，是因为无法自动识别模型的template，需要自制一份，并以--chat-template指向它。

**Comment by lylala8** [comment]
你好能详细说明这个制作template吗，里面有什么，这个参数的文档在哪呢
