### ISSUE TITLE
[Bug] InternVL2-40B量化后部署，无法访问

### ISSUE THREAD

**Issue by douyh** [InternLM/lmdeploy#2009]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

使用lmdeploy对InternVL2-40B量化，得到一个模型文件夹InternVL2-40B-AWQ, 具体的量化执行脚本：

![image](https://github.com/user-attachments/assets/183f69eb-d28f-440f-96e4-eec2ebf8577f)

然后使用如下命令起了一个server：
```
model_name=InternVL2-40B-AWQ
lmdeploy serve api_server $model_name --backend turbomind --model-format awq  --server-port 12315 --session-len 20000 --tp 4 --server-name 0.0.0.0  # --model-name $model_name
```

使用openai访问的时候，出现这样的错误
![image](https://github.com/user-attachments/assets/2ce121cf-8a71-4eb3-ae78-3a7ea70b5b91)

请问这个是暂时不支持，还是我的环境问题。lmdeploy是通过pip install安装。

### Reproduction

4卡3090

### Environment

```Shell
4卡3090
```

**Comment by irexyc** [comment]
try the latest build https://github.com/zhyncs/lmdeploy-build/releases

or use `--model-name internvl2-internlm2`

**Comment by douyh** [comment]
> try the latest build https://github.com/zhyncs/lmdeploy-build/releases
> 
> or use `--model-name internvl2-internlm2`

好的我试试

**Comment by douyh** [comment]
> try the latest build https://github.com/zhyncs/lmdeploy-build/releases
> 
> or use `--model-name internvl2-internlm2`

internvl2-26b用最新的版本是没有问题的，可以得到结果。但是40b的模型在server端已经打印了"GET /v1/models HTTP/1.1" 200 OK


但是client这边似乎没有反应，好像卡住了。
![image](https://github.com/user-attachments/assets/c8a20831-0608-4756-8103-f31fc1c7d6a1)




40b的模型在server起来的时候会多打印一行（红框中的内容），26b的模型不会打印。
![image](https://github.com/user-attachments/assets/b2754968-a41b-40cd-9788-0683fcdca090)

**Comment by irexyc** [comment]
服务启动的时候，增加 `--log-level INFO`

把安装目录中这一行改成 `features = await self.vl_encoder.infer(images)`
https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/serve/vl_async_engine.py#L66

然后再看看有没有什么报错，可以把日志发上来。

**Comment by douyh** [comment]
> 服务启动的时候，增加 `--log-level INFO`
> 
> 把安装目录中这一行改成 `features = await self.vl_encoder.infer(images)` https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/serve/vl_async_engine.py#L66
> 
> 然后再看看有没有什么报错，可以把日志发上来。

应该没报错，反应慢应该是因为生成了一堆乱七八糟的东西。
![image](https://github.com/user-attachments/assets/fe44e6bd-bb34-45f5-b31a-55be8905bcdd)

**Comment by irexyc** [comment]
> 应该没报错，反应慢应该是因为生成了一堆乱七八糟的东西。

从开始就乱码，还是开头正常，后面停不下来。

**Comment by douyh** [comment]
> > 应该没报错，反应慢应该是因为生成了一堆乱七八糟的东西。
> 
> 从开始就乱码，还是开头正常，后面停不下来。

第一个次是公司。

BTW我看到一个issue好像和这个情况类似https://github.com/InternLM/lmdeploy/issues/1965

**Comment by irexyc** [comment]
是的，我给忘了，应该是这个问题，需要改下代码。

**Comment by douyh** [comment]
> 是的，我给忘了，应该是这个问题，需要改下代码。

请问这个具体需要怎么做呢？
![image](https://github.com/user-attachments/assets/2966ce39-cee9-46b4-940c-9021dcd75038)

**Comment by irexyc** [comment]
按照这个PR改下安装目录的代码。

https://github.com/InternLM/lmdeploy/pull/1979/files

**Comment by douyh** [comment]
> 按照这个PR改下安装目录的代码。
> 
> https://github.com/InternLM/lmdeploy/pull/1979/files

需要重新转换AWQ的模型吗，还是直接推理呢

**Comment by irexyc** [comment]
不用重新量化模型，改一下就好。

**Comment by douyh** [comment]
> 不用重新量化模型，改一下就好。

但是我本地代码好像已经有这块了
![image](https://github.com/user-attachments/assets/d7eaea5a-ab4f-44d5-9248-9f9501ed3ad5)

**Comment by douyh** [comment]
> 不用重新量化模型，改一下就好。

![image](https://github.com/user-attachments/assets/aff74e72-a2d4-4ea8-b8c9-4f421564238a)
我安装的是这个whl

**Comment by irexyc** [comment]
那暂时想不到原因了，非量化的40b模型，跑起来正常么？

**Comment by douyh** [comment]
> 那暂时想不到原因了，非量化的40b模型，跑起来正常么？
我只有4张3090，没有量化的可能跑不起来，我先试试看。

**Comment by irexyc** [comment]
> 还是可以跑，不量化的模型是正常的😭

@AllentDan 

你有试过 InternVL2-40B 模型量化么？

**Comment by AllentDan** [comment]
#2023 修了

**Comment by douyh** [comment]
> #2023 修了

好用！
