### ISSUE TITLE
[Feature] 希望增加chatglm6b的支持

### ISSUE THREAD

**Issue by datalee** [InternLM/lmdeploy#201]
### Motivation

chatglmv1-6b or chatglmv2-6b确实是目前中文中最能打的，生态也很完备，希望加速推理这块可以弥补起来。

### Related resources

https://huggingface.co/THUDM/chatglm2-6b-32k

**Comment by lvhan028** [comment]
有排期，不过可能会有些久。因为现在的重点是在做量化模型的部署支持

**Comment by lvhan028** [comment]
Moved to backlog
