### ISSUE TITLE
How multimodal batch inference works?

### ISSUE THREAD

**Issue by bonre** [InternLM/lmdeploy#2027]
Thanks for your amazing work!
here are my test code:
![b60139419564254eae64f6620a73d353065ba43acb86b0adab5bb0834a5a92dcQzpcVXNlcnNcYmFuZ3R1XEFwcERhdGFcUm9hbWluZ1xEaW5nVGFsa1wxODk1NTgzNjQyX3YyXEltYWdlRmlsZXNcMTcyMTAzNzI3MTQzMV9EOEUzNTA1RS1CMTBDLTQ5ZGEtODQ1RC1FRUEyMTU1NUIzMEIucG5n](https://github.com/user-attachments/assets/05479061-50c8-497b-bc5f-916df6563d29)
After running i get the result:
![a2fcfb7e65c4d639605f4e6488ab45e8be5ab08fa77f5a0acaf44caa48e2a560QzpcVXNlcnNcYmFuZ3R1XEFwcERhdGFcUm9hbWluZ1xEaW5nVGFsa1wxODk1NTgzNjQyX3YyXEltYWdlRmlsZXNcMTcyMTAzNzMzODYwNV85Q0MxNDIwMC0xMUUzLTQxZDktQUIwRS00QkNERUZDNUYyQUEucG5n](https://github.com/user-attachments/assets/c49049d6-b03b-4bf5-86c0-5bb495992204)
I want to know how multimodal batch inference works, why does using it or not make such a big difference?

**Comment by zhyncs** [comment]
ref https://github.com/InternLM/lmdeploy/issues/1949#issuecomment-2216873308
