### ISSUE TITLE
Serving gradio报错

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#204]
![image](https://github.com/InternLM/lmdeploy/assets/6971044/d84724e1-e098-4ad7-9b02-bdc5e0bdeec0)

报错: no module named lmdeploy.serve.gradio

环境里已安装了lmdeploy 0.0.2 python包。

**Comment by lvhan028** [comment]
lmdeploy.serve.gradio 没有在 lmdeploy 0.0.2 中。等我打个0.0.3的包，你再试下哈
