### ISSUE TITLE
[Bug] Aborted (core dumped)  internlm2.5-7b-chat

### ISSUE THREAD

**Issue by yangzhiqiangq** [InternLM/lmdeploy#2048]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

用internlm2.5-7b-chat 使用 serve 的时候 ，调用API 报错： Aborted (core dumped)
******
INFO:     Uvicorn running on http://0.0.0.0:6007 (Press CTRL+C to quit)
INFO:     127.0.0.1:38844 - "GET /v1/models HTTP/1.1" 200 OK
Aborted (core dumped) 
******
是因为lmdeploy的版本问题吗 
lmdeploy==0.3.0

### Reproduction

lmdeploy serve api_server

### Environment

```Shell
。
```

**Comment by lvhan028** [comment]
Please share the result of executing `lmdeploy check_env`

**Comment by lvhan028** [comment]
What's the command you used to launch the api_server?

**Comment by zhyncs** [comment]
> lmdeploy==0.3.0

May you try the latest version https://github.com/InternLM/lmdeploy/releases/tag/v0.5.1

**Comment by yangzhiqiangq** [comment]
> Please share the result of executing `lmdeploy check_env`
![image](https://github.com/user-attachments/assets/92388e65-b3d5-432b-a035-fc9512e44cfe)

**Comment by yangzhiqiangq** [comment]
> > lmdeploy==0.3.0
> 
> May you try the latest version https://github.com/InternLM/lmdeploy/releases/tag/v0.5.1

>doing... thanks

**Comment by yangzhiqiangq** [comment]
> Please share the result of executing `lmdeploy check_env`

>  pip install lmdeploy==0.5.1 and solved
