### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by xiaoxiangshusheng** [InternLM/lmdeploy#2054]
I used  the lmdeploy code for secondary development, I want to check whether the new code has memory leak, but the code needs ninja to achieve compile. So valgrind tools which ususally used to check memory leak  can be used for lmdeploy to check the situation?
Looking forward to your reply！

**Comment by zhyncs** [comment]
You can use https://github.com/google/sanitizers/wiki/AddressSanitizerLeakSanitizer

**Comment by xiaoxiangshusheng** [comment]
> You can use https://github.com/google/sanitizers/wiki/AddressSanitizerLeakSanitizer

Thanks for your reply. In lmdeploy Cmake list, whether this code change can invoke AddressSanitizer？
![image](https://github.com/user-attachments/assets/c0716c79-1c72-40c9-8d80-87aaa1261133)
