### ISSUE TITLE
[Feature] 你们这个安装包什么鬼，我cuda运行时是12.5的也卸载了？

### ISSUE THREAD

**Issue by HuXinjing** [InternLM/lmdeploy#2056]
### Motivation

`    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
Successfully installed MarkupSafe-2.1.5 accelerate-0.32.1 addict-2.4.0 dnspython-2.6.1 einops-0.8.0 email_validator-2.2.0 fastapi-0.111.1 fastapi-cli-0.0.4 filelock-3.15.4 fire-0.6.0 httptools-0.6.1 huggingface-hub-0.23.5 importlib-metadata-8.0.0 jinja2-3.1.4 lmdeploy-0.5.1 markdown-it-py-3.0.0 mdurl-0.1.2 mmengine-lite-0.10.4 mpmath-1.3.0 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.19.3 nvidia-nvjitlink-cu12-12.5.82 nvidia-nvtx-cu12-12.1.105 peft-0.11.1 psutil-6.0.0 pygments-2.18.0 pynvml-11.5.3 python-dotenv-1.0.1 python-multipart-0.0.9 rich-13.7.1 safetensors-0.4.3 sentencepiece-0.2.0 shellingham-1.5.4 shortuuid-1.0.13 starlette-0.37.2 sympy-1.13.0 termcolor-2.4.0 tokenizers-0.19.1 torch-2.2.2 torchvision-0.17.2 transformers-4.42.4 triton-2.2.0 typer-0.12.3 uvicorn-0.30.1 uvloop-0.19.0 watchfiles-0.22.0 websockets-12.0 yapf-0.40.2 zipp-3.19.2`

### Related resources

无

**Comment by zhyncs** [comment]
You can install with `--no-deps`.

**Comment by irexyc** [comment]
lmdeploy 打包的时候会添加 cuda-runtime依赖 https://github.com/InternLM/lmdeploy/blob/main/setup.py#L44-L47

但是并没有指定小版本，我觉得可能得情况是，lmdeploy 的 requirements 中有torch，torch 的 requirements 中对 cuda-runtime 指定了小版本。https://github.com/search?q=repo%3Apytorch%2Fpytorch%20nvidia-cuda-runtime&type=code

**Comment by irexyc** [comment]
>  Successfully uninstalled ... nvidia-cuda-runtime-cu12-12.1.105

日志里面也有也有这一行。虽然卸载了，但是装了个稍旧版本的runtime，请问你是有什么原因必须用最新的runtime么？

测试过了，先装 nvidia-cuda-runtime-cu12 12.5.82 ，在装最新的pytorch，就会卸载12.5.82 这个版本。

**Comment by HuXinjing** [comment]
你们的readme里没指定小版本啊，你们这么随意卸载万一用户改动了runtime的东西了怎么办？



---原始邮件---
发件人: "Chen ***@***.***&gt;
发送时间: 2024年7月17日(周三) 晚上6:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [InternLM/lmdeploy] [Feature] 你们这个安装包什么鬼，我cuda运行时是12.5的也卸载了？ (Issue #2056)




  
Successfully uninstalled ... nvidia-cuda-runtime-cu12-12.1.105
  
日志里面也有也有这一行。虽然卸载了，但是装了个稍旧版本的runtime，请问你是有什么原因必须用最新的runtime么？
 
测试过了，先装 nvidia-cuda-runtime-cu12 12.5.82 ，在装最新的pytorch，就会卸载12.5.82 这个版本。

**Comment by lvhan028** [comment]
我们并不能预见到这种情况

**Comment by lvhan028** [comment]
你应该去pytorch问：“你们这个安装包什么鬼，我cuda运行时是12.5的也卸载了？”
祝你好运

**Comment by zhyncs** [comment]
> 你们的readme里没指定小版本啊，你们这么随意卸载万一用户改动了runtime的东西了怎么办？

@HuXinjing LMDeploy is Open Source Software under [Apache License](https://www.apache.org/licenses/LICENSE-2.0).

> 8. Limitation of Liability. In no event and under no legal theory, whether in tort (including negligence), contract, or otherwise, unless required by applicable law (such as deliberate and grossly negligent acts) or agreed to in writing, shall any Contributor be liable to You for damages, including any direct, indirect, special, incidental, or consequential damages of any character arising as a result of this License or out of the use or inability to use the Work (including but not limited to damages for loss of goodwill, work stoppage, computer failure or malfunction, or any and all other commercial damages or losses), even if such Contributor has been advised of the possibility of such damages.

If you encounter a problem, please **politely** raise the issue. Otherwise, fuck off and go away.

**Comment by HuXinjing** [comment]
好，马上就去



---原始邮件---
发件人: "Lyu ***@***.***&gt;
发送时间: 2024年7月17日(周三) 晚上6:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [InternLM/lmdeploy] [Feature] 你们这个安装包什么鬼，我cuda运行时是12.5的也卸载了？ (Issue #2056)




 
你应该去pytorch问：“你们这个安装包什么鬼，我cuda运行时是12.5的也卸载了？”
 祝你好运
