### ISSUE TITLE
想问下Lmdeploy支持base model加多lora的部署方式么

### ISSUE THREAD

**Issue by will-wiki** [InternLM/lmdeploy#2057]
https://docs.vllm.ai/en/latest/models/lora.html
这是vllm框架多lora部署方案，想问下lmdeploy有类似的方法么

**Comment by lvhan028** [comment]
pytorch engine 支持多 lora
在 文档 https://lmdeploy.readthedocs.io/en/latest/inference/pipeline.html 中，有 "An example for slora" 的例子

**Comment by will-wiki** [comment]
@lvhan028 感谢回复，想问下PytorchEngine跟TurbomindEngine有啥区别么，主要是性能上的区别么，是否可以切换呢。
另外想问下，现在的MLLM模型，像InternLM-XComposer2.5这种可以支持PytorchEngine服务部署不

**Comment by lvhan028** [comment]
区别：1）性能上 turbomind 更快些；2）支持的模型上 pytorch engine 更多；
关于切换：
1. 如果不指定推理引擎，优先选择turbomind engine，如果它支持了输入的模型的话。否则使用pytorch engine
2. 如果指定了turbomind engine，但是它又不支持输入的模型，那么会使用pytorch engine
3. 如果指定了pytorch engine，就使用pytorch engine

如果你指的 serving LLM 是想要serve lora，是支持的。有 --adapters 选项

InternLM-XComposer2.5 是在 turbomind engine中支持的。这里有文档：https://github.com/InternLM/lmdeploy/blob/main/docs/en/multi_modal/xcomposer2d5.md

**Comment by will-wiki** [comment]
@lvhan028 现在打算用serve lora部署InternLM-XComposer2.5 ，应该怎么部署呢，看了下只有pytorch engine才支持这个--adapters
<img width="1868" alt="image" src="https://github.com/user-attachments/assets/5e5344ae-efe7-4be2-bf44-41e686ea2cb2">

https://github.com/InternLM/lmdeploy/blob/main/docs/en/multi_modal/xcomposer2d5.md 这里好像提到是用turbomind engine支持的，那就是说退化到用 pytorch engine部署，InternLM-XComposer2.5 就可以支持多lora部署了吧？也就是--backend {pytorch,turbomind}选择pytorch，牺牲性能满足要求

**Comment by lvhan028** [comment]
也不是。PyTorchEngine并没有支持InternLM-XComposer2.5
所以，目前是无法满足你的需求的。

**Comment by will-wiki** [comment]
@lvhan028 好吧，那这有在你们后续的计划内吗，比如turbomind engine支持多lora或者InternLM-XComposer2.5模型支持PyTorchEngine什么的

**Comment by zhongtao93** [comment]
会有计划支持 internvl2 系列吗

**Comment by zhongtao93** [comment]
我直接用

> pytorch engine 支持多 lora 在 文档 https://lmdeploy.readthedocs.io/en/latest/inference/pipeline.html 中，有 "An example for slora" 的例子

我用这个方法，将模型改成了internvl 2，没有奔溃，但输出结果为空
<img width="892" alt="image" src="https://github.com/user-attachments/assets/2c353929-9c4d-4bb9-b258-af80057ab86d">

**Comment by RunningLeon** [comment]
> 我直接用
> 
> > pytorch engine 支持多 lora 在 文档 https://lmdeploy.readthedocs.io/en/latest/inference/pipeline.html 中，有 "An example for slora" 的例子
> 
> 我用这个方法，将模型改成了internvl 2，没有奔溃，但输出结果为空 <img alt="image" width="892" src="https://private-user-images.githubusercontent.com/15263824/352118143-2c353929-9c4d-4bb9-b258-af80057ab86d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NTc2MjMsIm5iZiI6MTcyMTk1NzMyMywicGF0aCI6Ii8xNTI2MzgyNC8zNTIxMTgxNDMtMmMzNTM5MjktOWM0ZC00YmI5LWIyNTgtYWY4MDA1N2FiODZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDAxMjg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3Y2RjMjVmZjMwMjdjMmE5Mzc1MTY0ZmI0OTI0Y2JmMzkxOTg5YmI0Zjk5Y2Y4NDY2ZTZjOGEzMWZjYjkzMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q_J_Ba2naQt_V07q_YPYU2DsRfFiu0vKH5yKsAabqcw">

@zhongtao93 输入超长了，可以改大`session_len` ，参考 https://lmdeploy.readthedocs.io/en/latest/inference/vl_pipeline.html#set-context-window-size
