### ISSUE TITLE
[Bug] Client result got no space

### ISSUE THREAD

**Issue by tikikun** [InternLM/lmdeploy#206]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

<img width="1539" alt="image" src="https://github.com/InternLM/lmdeploy/assets/22268502/8d4b45ce-1b61-4a9a-81ac-b82156566183">

Support to have space between wors

### Reproduction

use the latest client.py

**Comment by lvhan028** [comment]
HHi, @tikikun which model are you using?

**Comment by tikikun** [comment]
<img width="1313" alt="image" src="https://github.com/InternLM/lmdeploy/assets/22268502/a6b61989-755c-412b-937c-ed2ad5dc5a1f">

@lvhan028 same result, i think the core issue is within the ChatBot object

**Comment by lvhan028** [comment]
Yes. It is. You can try to use turbomind's python API directly, or [serving with gradio](https://github.com/InternLM/lmdeploy#serving-with-gradio)
I'll try to fix it asap

**Comment by tikikun** [comment]
after a thorough research it seems that sentencepiece cannot decode sequentially the token_id, you need to pass the entire vector into it everytime the result streamed back, so maybe the original version is what it was intended to be.

**Comment by testsuper23** [comment]
Any update on this?

**Comment by lzhangzz** [comment]
fixed in #222

**Comment by lvhan028** [comment]
@testsuper23 I chose to rollback :(
Please try the latest lmdeploy
