### ISSUE TITLE
[Bug] The problem of very low multi-card inference efficiency

### ISSUE THREAD

**Issue by maxin9966** [InternLM/lmdeploy#2066]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

The operational efficiency of a single card is very high. But dual-card inference shows only a 20% improvement in throughput  performance compared to single-card inference. 

I've tested this on two different computers, one equipped with a 40-series graphics card and the other with a 20-series graphics card.

### Reproduction

lmdeploy serve gradio internlm/internlm2_5-7b-chat-4bit --backend turbomind --model-format awq --server-port 1240 --session-len 18000 --cache-max-entry-count 0.9 --model-name gpt --tp 2 --enable-prefix-caching

### Environment

```Shell
lmdeploy 0.5.0 TurboMind
2080ti*2 OR 4070tisuper*2
```

**Comment by zhyncs** [comment]
cc @lzhangzz

**Comment by zhyncs** [comment]
ref https://github.com/InternLM/lmdeploy/pull/2082

**Comment by zhyncs** [comment]
https://github.com/zhyncs/lmdeploy-build/releases/tag/6a6e7f9
