### ISSUE TITLE
webui用不了

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#207]
![image](https://github.com/InternLM/lmdeploy/assets/6971044/95997e98-2f7b-4785-954d-eacf3267872b)

试验了访问http://xx.xx.xx.xx:6006 ，显示"无法访问此网站"

**Comment by lvhan028** [comment]
@AllentDan I think we'd better put it down to FQA

**Comment by frankxyy** [comment]
所以该咋用。。。 127.0.0.1替换为server实际ip也不行

**Comment by AllentDan** [comment]
https://github.com/InternLM/lmdeploy/issues/194
有代理吗？关一下

**Comment by frankxyy** [comment]
@AllentDan 你好，没有代理

**Comment by AllentDan** [comment]
防火墙什么的也设置下？

**Comment by frankxyy** [comment]
@AllentDan 我自己起的gradio demo可以访问，所以感觉不是网络的问题。怀疑是gradio代码和版本的兼容性问题。。

**Comment by AllentDan** [comment]
hmmm, 可以:joy:
