### ISSUE TITLE
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.          

### ISSUE THREAD

**Issue by sunzx8** [InternLM/lmdeploy#2072]
请问这种情况应该怎么排查问题，比如查出special token是哪个

**Comment by lvhan028** [comment]
I haven't a clue. Is it a tokenizer issue?
Can you share more background?

**Comment by sunzx8** [comment]
sure ,when i ran command:
 lmdeploy serve api_server /home/ubuntu/shawn/hf_ms_model/InternVL2-26B --server-port 6688 --tp 4 --session-len 4096 --model-format hf

it showed:
<img width="1062" alt="image" src="https://github.com/user-attachments/assets/a7e816d9-3046-431b-ac03-391ee7d326c9">
I am just confused at this notice. No matter I choose my own finetuned model or official model , it will both had these notices

**Comment by sunzx8** [comment]
这个可以解决一下吗？

**Comment by lvhan028** [comment]
I don't think that's an issue of lmdeploy
I tried the inference of `InternVL2-26B` with `transformers`, and I encounter the same hint, too
```
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
```
Please consult the OpenGVLab for detailed information.
