### ISSUE TITLE
[Bug] docker 镜像v0.5.1版本缺少timm库，拉起intern2vl的模型报错

### ISSUE THREAD

**Issue by bjfk2006** [InternLM/lmdeploy#2100]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

docker 镜像v0.5.1版本缺少timm库，拉起intern2vl的模型报错

### Reproduction

docker run --gpus all -v `pwd`/models:/opt/models --env "HUGGING_FACE_HUB_TOKEN=<secret>" -p 80:23333 --ipc=host -it -d --name lmdeploy-internvl2 openmmlab/lmdeploy:v0.5.1 lmdeploy serve api_server --model-name InternVL2-8B /opt/models/InternVL2-8B

### Environment

```Shell
ubuntu22+V100
```

### Error traceback

```Shell
timm
```

**Comment by lvhan028** [comment]
We intend to do that. 
The VLMs vary a lot in the third-party dependencies.
If we include them all in the docker image, it probably cause package conflicts. 
Therefore, we leave users to build their own image based on openmmlab/lmdeploy:{tag}
