### ISSUE TITLE
[Feature] 离线转换lmdeploy convert是否存在完整的VLM支持

### ISSUE THREAD

**Issue by Telephone1024** [InternLM/lmdeploy#2102]
### Motivation

由于某些原因，我需要以triton inference server方式进行部署，在转化inernVL2-2B时注意到，如果采用如下命令
```python
lmdeploy convert internvl2-internlm2 $WORK_DIR \
  --model-format awq \
  --group-size 128 \
  --dst-path "$DST_DIR" \
  --tokenizer-path "$HF_MODEL/tokenizer_config.json"
```
实际保存的turbomind的triton model中并无vision encoder部分
我想知道：
- 在当前版本0.5.1中是否存在VLM转化的最佳实践
- 如果没有，后续是否会提供更加完整的VLM转化方式呢

**Comment by lvhan028** [comment]
lmdeploy convert不支持 vlm 模型，也暂无计划
