### ISSUE TITLE
[Bug] lmdeploy 部署 InternVL2-4B 后运行失败

### ISSUE THREAD

**Issue by dgedanke** [InternLM/lmdeploy#2109]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

在 [https://www.modelscope.cn/models/OpenGVLab/InternVL2-4B](https://www.modelscope.cn/models/OpenGVLab/InternVL2-4B) 社区下载了 InternVL2-4B，并安装了 lmdeploy，运行官方 demo:

```python
from lmdeploy import pipeline, PytorchEngineConfig, ChatTemplateConfig
from lmdeploy.vl import load_image

model = '/data/swift/models/InternVL2-4B'
system_prompt = '我是书生·万象，英文名是InternVL，是由上海人工智能实验室及多家合作单位联合开发的多模态大语言模型。'
image = load_image('/data/swift/dataset/photo/test.png')
chat_template_config = ChatTemplateConfig('internvl-phi3')
chat_template_config.meta_instruction = system_prompt
pipe = pipeline(model, chat_template_config=chat_template_config,
                backend_config=PytorchEngineConfig(session_len=8192))
response = pipe(('describe this image', image))
print(response.text)
```
改了模型路径与图片路径

### Reproduction

运行上述代码，结果如下：

```sh
Flash Attention 2.0 only supports torch.float16 and torch.bfloat16 dtypes, but the current dype in Phi3ForCausalLM is torch.float32. You should run training or inference using Automatic Mixed-Precision via the `with torch.autocast(device_type='torch_device'):` decorator, or load the model with the `torch_dtype` argument. Example: `model = AutoModel.from_pretrained("openai/whisper-tiny", attn_implementation="flash_attention_2", torch_dtype=torch.float16)`
Flash Attention 2.0 only supports torch.float16 and torch.bfloat16 dtypes, but the current dype in Phi3Model is torch.float32. You should run training or inference using Automatic Mixed-Precision via the `with torch.autocast(device_type='torch_device'):` decorator, or load the model with the `torch_dtype` argument. Example: `model = AutoModel.from_pretrained("openai/whisper-tiny", attn_implementation="flash_attention_2", torch_dtype=torch.float16)`
/tmp/tmp3a5i5av8/main.c: In function ‘list_to_cuuint64_array’:
/tmp/tmp3a5i5av8/main.c:354:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (Py_ssize_t i = 0; i < len; i++) {
   ^
/tmp/tmp3a5i5av8/main.c:354:3: note: use option -std=c99 or -std=gnu99 to compile your code
/tmp/tmp3a5i5av8/main.c: In function ‘list_to_cuuint32_array’:
/tmp/tmp3a5i5av8/main.c:365:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (Py_ssize_t i = 0; i < len; i++) {
   ^
2024-07-23 14:18:00,452 - lmdeploy - ERROR - CalledProcessError: Command '['/usr/bin/gcc', '/tmp/tmp3a5i5av8/main.c', '-O3', '-I/data/anaconda3/envs/lmdeploy/lib/python3.11/site-packages/triton/common/../third_party/cuda/include', '-I/data/anaconda3/envs/lmdeploy/include/python3.11', '-I/tmp/tmp3a5i5av8', '-shared', '-fPIC', '-lcuda', '-o', '/tmp/tmp3a5i5av8/cuda_utils.cpython-311-x86_64-linux-gnu.so', '-L/lib64', '-L/lib', '-L/lib64', '-L/lib']' returned non-zero exit status 1.
2024-07-23 14:18:00,452 - lmdeploy - ERROR - <Triton> test failed!
Please ensure it has been installed correctly.
```

### Environment

```Shell
$ lmdeploy check_env
sys.platform: linux
Python: 3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA GeForce RTX 4090
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.1, V12.1.66
GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
PyTorch: 2.2.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.7  (built against CUDA 12.2)
    - Built with CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF,

TorchVision: 0.17.2+cu121
LMDeploy: 0.5.0+
transformers: 4.42.4
gradio: 3.43.0
fastapi: 0.111.1
pydantic: 2.8.2
triton: 2.2.0
```

**Comment by RunningLeon** [comment]
@dgedanke hi, something wrong with triton. could you try reinstall with `triton==2.1.0` and try again?
> 2024-07-23 14:18:00,452 - lmdeploy - ERROR - CalledProcessError: Command '['/usr/bin/gcc', '/tmp/tmp3a5i5av8/main.c', '-O3', '-I/data/anaconda3/envs/lmdeploy/lib/python3.11/site-packages/triton/common/../third_party/cuda/include', '-I/data/anaconda3/envs/lmdeploy/include/python3.11', '-I/tmp/tmp3a5i5av8', '-shared', '-fPIC', '-lcuda', '-o', '/tmp/tmp3a5i5av8/cuda_utils.cpython-311-x86_64-linux-gnu.so', '-L/lib64', '-L/lib', '-L/lib64', '-L/lib']' returned non-zero exit status 1.
2024-07-23 14:18:00,452 - lmdeploy - ERROR - <Triton> test failed!
Please ensure it has been installed correctly.

**Comment by dgedanke** [comment]
@RunningLeon 
I tried to reinstall with ```triton==2.1.0```.
Although there were some errors, I was eventually able to run it.
```sh
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch 2.2.2 requires triton==2.2.0; platform_system == "Linux" and platform_machine == "x86_64" and python_version < "3.12", but you have triton 2.1.0 which is incompatible.
```
Thank you very much for your reply!

**Comment by Mrgengli** [comment]
@RunningLeon 
hello,internvl2 model after awq quant ,i deployed the awq model in local machine to infer.but got the error below.could you tell me how to fix it please?
![image](https://github.com/user-attachments/assets/1372c0d6-e536-42e0-8e24-12175ec7db36)

**Comment by RunningLeon** [comment]
> @RunningLeon hello,internvl2 model after awq quant ,i deployed the awq model in local machine to infer.but got the error below.could you tell me how to fix it please? ![image](https://private-user-images.githubusercontent.com/114299344/373934622-1372c0d6-e536-42e0-8e24-12175ec7db36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0Mzg4MjQsIm5iZiI6MTcyODQzODUyNCwicGF0aCI6Ii8xMTQyOTkzNDQvMzczOTM0NjIyLTEzNzJjMGQ2LWU1MzYtNDJlMC04ZTI0LTEyMTc1ZWM3ZGIzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQwMTQ4NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTRlYzVlN2Y4N2I2ZWM0NDE0ZDI4YjNhMzQzNzkwODZiYmEwMTFiOTIzNjY4N2NmOGU2YjU4ODE5NGJkMDIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VvHAgtZ_vDj3N2Ligt7x0e7ZhCzaOjOm0HBz6UEmRpU)

cc @AllentDan

**Comment by AllentDan** [comment]
@Mrgengli Please paste the commands and `lmdeploy check_env` result

**Comment by Mrgengli** [comment]
@AllentDan i got a new error ,last erorr is solved,thank you very much ,i want to know how to solve the new eorro below:
2024-10-09 16:10:50,476 - lmdeploy - ERROR - request.py:21 - Engine loop failed with error: module 'triton.language' has no attribute 'inline_asm_elementwise'
lmdeploy check_env is below 
![image](https://github.com/user-attachments/assets/4790856d-e785-4f7f-ae86-0c3ae9ad779f)

![image](https://github.com/user-attachments/assets/c01e7db8-09c5-40d8-964c-c93bd0b86589)

**Comment by AllentDan** [comment]
may upgrade triton to 2.3.0

**Comment by Mrgengli** [comment]
the version of triton change  to 2.3.0,but a new erorr appears.
![image](https://github.com/user-attachments/assets/31644df1-4175-4837-9fc7-f89f7d3b63d8)

**Comment by Mrgengli** [comment]
@AllentDan it seems that if the version of triton is not 2.1.0,this erorr will appear

**Comment by AllentDan** [comment]
Please install flash_attn correctly.

**Comment by Mrgengli** [comment]
@AllentDan thanks for you reply! it seems that it is not the promble with flash_attn,I have another environment with flash_attn which encounters the same problem above.

**Comment by luowei0701** [comment]
@Mrgengli 
Have you solved it?

**Comment by Mrgengli** [comment]
no,I do not solve this problem.this problem is happend only if  i use the awq quant model.

**Comment by Mrgengli** [comment]
@AllentDan I have correctly install flash_att v2 ,and the triton version is 2.3.0.but it still goes wrong when I infer a awq model.how could I can solve this problem?
![image](https://github.com/user-attachments/assets/75c6dd5f-849d-4215-ab0c-f700e90adb92)
