### ISSUE TITLE
如何最大化pipline batch infer的吞吐量/速度[Bug] 

### ISSUE THREAD

**Issue by hitzhu** [InternLM/lmdeploy#2110]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

在使用pipline 进行batch_infer时，分别用4卡a100合和8卡a100，发现速度没区别，GPU利用率也存在很长的空窗，batch_size为32,应该如何设置尽可能加快这个速度

### Reproduction

rt

### Environment

```Shell
rt
```

**Comment by lvhan028** [comment]
Feed a list of prompts to the pipeline, the more, the better.
And I suggest using the latest nightly built version from [here](https://github.com/zhyncs/lmdeploy-build/releases), since we fixed an issue in multi-GPUs scenario.
