### ISSUE TITLE
[Bug] openai格式部署该怎么传入视频？

### ISSUE THREAD

**Issue by stay-leave** [InternLM/lmdeploy#2112]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

请问怎么传入视频？
以下是图像的传入
```
messages=[
    {
      "role": "user",
      "content": [
        {"type": "text", "text": "What’s in this image?"},
        {
          "type": "image_url",
          "image_url": {
            "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg",
          },
        },
      ],
    }
  ],
```

### Reproduction

rt

### Environment

```Shell
rt
```

**Comment by lvhan028** [comment]
It's not a bug. 
video is not supported now. And we have no plan to do that.
