### ISSUE TITLE
[Feature] Support odd count of GPUs

### ISSUE THREAD

**Issue by sisgrad** [InternLM/lmdeploy#2114]
### Motivation

Currently tensor parallelism is supported only for 2^n count of GPUs. Is it possible to support odd counts? I have 3x3090 and the last one could not be used in tensor parallelism. Hovewer, in other projects any count supported.

**Comment by lvhan028** [comment]
We have no plans to do that.
In LMDeploy, the number of attention heads should be evenly divided by `tp`.
