### ISSUE TITLE
[Feature] internvl2的图片预处理参数max_num默认是6，如何进行修改？

### ISSUE THREAD

**Issue by janelu9** [InternLM/lmdeploy#2126]
### Motivation

微调训练时候用的max_num=2，推理时候用的lmdeploy，没有看到这部分入参。或者输入为token_id和input_embeddings进行文字生成的接口有吗？input_embeddings相当于encoder的输出，这部分我可以根据自己数据单独生成。

**Comment by irexyc** [comment]
可以改安装目录中的源码 https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/vl/model/internvl.py#L138-L141

或者修改模型config中的 max_dynamic_patch

**Comment by janelu9** [comment]
> 可以改安装目录中的源码 https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/vl/model/internvl.py#L138-L141
> 
> 或者修改模型config中的 max_dynamic_patch

thank you , 我trace到了这里。这段代码表明dynamic_preprocess直接用的是internvl官方的代码，感觉这个写法用作实时推理时速度不是很快。

**Comment by irexyc** [comment]
如果有更好的办法，欢迎提交PR~
