### ISSUE TITLE
Streaming API with session management 

### ISSUE THREAD

**Issue by sureshbhusare** [InternLM/lmdeploy#214]
Does lmdeploy have streaming API through web server or web socket ? If yes any example or documentation to start that ?

**Comment by AllentDan** [comment]
I will finish it ASAP—hopefully this week.

**Comment by testsuper23** [comment]
Any update on this?

**Comment by AllentDan** [comment]
Opened a merge request already. https://github.com/InternLM/lmdeploy/pull/223

**Comment by testsuper23** [comment]
Thanks for the reply. 
I tried to test the PR #223 but getting error
`lmdeploy/turbomind/tokenizer.py` At line 126(Nontype does not have `<BoS>
`)
Python -3.9.10
GPU A10G.

**Comment by AllentDan** [comment]
> Thanks for the reply. I tried to test the PR #223 but getting error `lmdeploy/turbomind/tokenizer.py` At line 126(Nontype does not have `<BoS> `) Python -3.9.10 GPU A10G.

llama2 is basically not a chat model. So I did not make support to it.

**Comment by testsuper23** [comment]
Ok thanks for the clarification. 
Can you please add model support? I tried `Llama2-70B-chat` and `Llama2-13b-chat`.

**Comment by AllentDan** [comment]
> Ok thanks for the clarification. Can you please add model support? I tried `Llama2-70B-chat` and `Llama2-13b-chat`.

Added. I don't have a chat model of llama2. So the result was not assured. But you can have a try and tell me if it works fine.

**Comment by sureshbhusare** [comment]
```
    if s.find('<BOS>') != -1:
AttributeError: 'NoneType' object has no attribute 'find'
```

I am also facing the same issue Tried running both - 70b and 70b-chat llama2 versions.

**Comment by AllentDan** [comment]
I prefer passing string instead of a list of dict to `messages`. Since [llama2](https://github.com/InternLM/lmdeploy/blob/8cdcb2a92f80bc7752949ad3266edf1bc6595b5c/lmdeploy/model.py#L191C56-L191C56) does not support this template now.

**Comment by sureshbhusare** [comment]
I am getting the error for curl example in the docs provided by you.

**Comment by AllentDan** [comment]
I provided another one now.

**Comment by sureshbhusare** [comment]
I tried the [command](https://github.com/AllentDan/lmdeploy/blob/2bdb6053be287f80f76358c8e5b1f209ace88834/docs/en/restful_api.md?plain=1#L18) token generated but it is not correct output  

```
{"id":"127001","object":"chat.completion","created":1692068663,"model":"llama2","choices":[{"index":0,"message":{"role":"assistant","content":"\n\n[INST] <<SYS>>\n You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe. Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.\n\nIf a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information. \n<</SYS>>\n\nTell me a joke [/INST] \n\n[INST] <<SYS>>\n You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe. Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.\n\nIf a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information. \n<</SYS>>\n\nTell me a joke [/INST] \n\n[INST] <<SYS>>\n You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe. Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.\n\nIf a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information. \n<</SYS>>\n\nTell me a joke [/INST] \n\n[INST] <<SYS>>\n You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe. Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in"},"finish_reason":null}],"usage":{"prompt_tokens":145,"total_tokens":800,"completion_tokens":513}}(inference) 
```

For the other [command](https://github.com/AllentDan/lmdeploy/blob/2bdb6053be287f80f76358c8e5b1f209ace88834/docs/en/restful_api.md?plain=1#L12) error persist.

**Comment by AllentDan** [comment]
Yes, you may add the customized chat template. The model llama2 chat template is not supported. Once added, result will be correct and the other command can also work.

**Comment by AllentDan** [comment]
The restful APIs were added. And the llama2 is also supported. For more details please refer to https://github.com/InternLM/lmdeploy/blob/main/docs/en/restful_api.md

**Comment by HuaYZhao** [comment]
> ```
>     if s.find('<BOS>') != -1:
> AttributeError: 'NoneType' object has no attribute 'find'
> ```
> 
> I am also facing the same issue Tried running both - 70b and 70b-chat llama2 versions.

I also encountered this problem with llama 7b-hf

**Comment by lvhan028** [comment]
> > ```
> >     if s.find('<BOS>') != -1:
> > AttributeError: 'NoneType' object has no attribute 'find'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am also facing the same issue Tried running both - 70b and 70b-chat llama2 versions.
> 
> I also encountered this problem with llama 7b-hf; with lmdeploy==0.0.8

`llama-7b` has no chatting capability. Please try to init it with `model = MODELS.get('llama')(capability='completion')`

```
@MODELS.register_module(name='internlm')
@MODELS.register_module(name='llama')
@MODELS.register_module(name='base')
class BaseModel:
    """Base model."""

    def __init__(self,
                 session_len=2048,
                 top_p=0.8,
                 top_k=None,
                 temperature=0.8,
                 repetition_penalty=1.0,
                 capability='chat',
                 **kwargs):
        self.session_len = session_len
        self.top_p = top_p
        self.top_k = top_k
        self.temperature = temperature
        self.repetition_penalty = repetition_penalty
        self.capability = capability

    def get_prompt(self, prompt, sequence_start=True):
        """Return the prompt that is concatenated with other elements in the
        chat template.

        Args:
            prompt (str): user's input prompt
            sequence_start (bool): indicator for the first round chat of a
               session sequence
        Returns:
            str: the concatenated prompt
        """
        if self.capability == 'completion':
            return prompt
        else:
            return self.decorate_prompt(prompt, sequence_start)

    @abstractmethod
    def decorate_prompt(self, prompt, sequence_start):
        pass
```

**Comment by HuaYZhao** [comment]
Well, I've tried to fix it, and hopefully I can adapt it in the release code so I don't have to manually make changes every time
