### ISSUE TITLE
[Docs] how to install lmdeploy0.5.1 in jetson

### ISSUE THREAD

**Issue by quanfeifan** [InternLM/lmdeploy#2146]
### 📚 The doc issue

how to install lmdeploy0.5.1 in jetson orin nx with jetpack 5.1.1

**Comment by lvhan028** [comment]
Hope this project [LMDeploy-Jetson](https://github.com/BestAnHongjun/LMDeploy-Jetson) can do you the favor

**Comment by lvhan028** [comment]
LMDeploy-Jetson 的作者提交了一个 PR 给 LMDeploy：https://github.com/InternLM/lmdeploy/pull/1820
不过目前应该还不work。
要不你联系下 LMDeploy-Jetson 项目的作者，问问看？

**Comment by lvhan028** [comment]
Close it since no more activities over 3 weeks. Don't hesitate to reopen it if it is still an issue
