### ISSUE TITLE
[Bug]     assert asyncio.get_event_loop() == self._loop_task.get_loop()

### ISSUE THREAD

**Issue by DankoZhang** [InternLM/lmdeploy#2149]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

报这种错是什么原因呢
<img width="1148" alt="image" src="https://github.com/user-attachments/assets/32292a7a-b65d-40bb-a7df-b4b70334d797">

### Reproduction

pipe(batch_data)

### Environment

```Shell
lmdeploy == 0.5.0
```

**Comment by irexyc** [comment]
你是怎么使用的呢？是在多线程中使用pipeline么？

**Comment by DankoZhang** [comment]
> 你是怎么使用的呢？是在多线程中使用pipeline么？

@irexyc 是的，多线程方式使用pipeline，这种方式不行是么

**Comment by irexyc** [comment]
可以这样
``
from lmdeploy import pipeline, VisionConfig
pipe = pipeline(..., vision_config=VisionConfig(thread_safe=True))
```

**Comment by DankoZhang** [comment]
> 可以这样
> 
> ```
> from lmdeploy import pipeline, VisionConfig
> pipe = pipeline(..., vision_config=VisionConfig(thread_safe=True))
> ```

好的感谢，我试试

**Comment by DankoZhang** [comment]
> 可以这样
> 
> ```
> from lmdeploy import pipeline, VisionConfig
> pipe = pipeline(..., vision_config=VisionConfig(thread_safe=True))
> ```

@irexyc 没有thread_safe这个参数呀
<img width="772" alt="image" src="https://github.com/user-attachments/assets/48bc6cfd-f34a-4e30-a5bc-c5a510276eee">

**Comment by irexyc** [comment]
更新下lmdeploy的版本，0.5.1是有的。

**Comment by irexyc** [comment]
先关掉了，如果有问题再打开。

**Comment by DankoZhang** [comment]
> 先关掉了，如果有问题再打开。

已经解决，感谢帮忙
