### ISSUE TITLE
推理时出现重复某个token的问题

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#215]
如题，扩充中文词表的版本，出现重复generate某个token的现象。但该版本用huggingface原始模型推理结果正常。

vocab_size 32000  原版llama结果正常

**Comment by lvhan028** [comment]
用的是哪个模型呢？

**Comment by frankxyy** [comment]
@lvhan028    Llama 扩充中文词表的版本哈

**Comment by lvhan028** [comment]
有模型链接么？我可以下载下来复现看看

**Comment by frankxyy** [comment]
稍等下哈，我整理下

**Comment by frankxyy** [comment]
我这自己处理掉了，是我模型这边预处理的问题。

**Comment by chailt** [comment]
请问是如何解决的，我也出现了这个问题
