### ISSUE TITLE
[Feature] 为什么模型的文件夹名称一定不能是任意的？

### ISSUE THREAD

**Issue by janelu9** [InternLM/lmdeploy#2150]
### Motivation

自己微调出来的模型存在一个名称全是数字（steps）的文件夹，结果加载到lmdeploy后一推断就报错，找了半天原因，百思不得其解，最后发现把文件名改成huggingface上一样就可以了

**Comment by janelu9** [comment]
还有就是 ，为什么lmdeploy在加载模型参数时候，不根据model.safetensors.index.json去找？

**Comment by lvhan028** [comment]
先解释下原因：

1. lmdeploy实现的是交互式推理。具体点说就是，在多轮对话中的第n轮，它不要求用户输入U1A1U1A2U2…U_n，而是只要给Un就好了。在这种模式下，transformers中的apply chat template是不适用的。因为它里面有 for messages的循环。这是我们没有使用apply chat template的主要原因。在model.py 中，应用对话模板的方式有2种，如下所示。其中 `get_prompt`就是在交互式的场景中用的。
```
def get_prompt(self, prompt, sequence_start=True):
        """Return the prompt that is concatenated with other elements in the
        chat template.

        Args:
            prompt (str): user's input prompt
            sequence_start (bool): indicator for the first round chat of a
               session sequence
        Returns:
            str: the concatenated prompt
        """
        if self.capability == 'completion':
            return prompt
        if sequence_start:
            # None is different from ''
            if self.meta_instruction is not None:
                return f'{self.system}{self.meta_instruction}{self.eosys}' \
                    f'{self.user}{prompt}{self.eoh}' \
                    f'{self.assistant}'
            else:
                return f'{self.user}{prompt}{self.eoh}' \
                       f'{self.assistant}'
        else:
            return f'{self.separator}{self.user}{prompt}{self.eoh}' \
                   f'{self.assistant}'

    def messages2prompt(self, messages, sequence_start=True, **kwargs):
        """Return the prompt that is concatenated with other elements in the
        chat template.

        Args:
            messages (str | List): user's input prompt
        Returns:
            str: the concatenated prompt
        """
        if isinstance(messages, str):
            return self.get_prompt(messages, sequence_start)
        box_map = dict(user=self.user,
                       assistant=self.assistant,
                       system=self.system)
        eox_map = dict(user=self.eoh,
                       assistant=self.eoa + self.separator,
                       system=self.eosys)
        ret = ''
        if self.meta_instruction is not None and sequence_start:
            if len(messages) and messages[0]['role'] != 'system':
                ret += f'{self.system}{self.meta_instruction}{self.eosys}'
        for message in messages:
            role = message['role']
            content = message['content']
            ret += f'{box_map[role]}{content}{eox_map[role]}'
        ret += f'{self.assistant}'
        return ret
```
2. 在多模态场景下，比如internvl，internlm-xcomposer，它们都没在tokenizer-config.json中提供对话模板，对话模板是在代码中写死的

关于local模型，可以通过--model-name指定内置模板。这种方式，的确需要有清晰的文档说明。这一点我们改进，放在0.6.0版本里

**Comment by janelu9** [comment]
> 先解释下原因：
> 
> 1. lmdeploy实现的是交互式推理。具体点说就是，在多轮对话中的第n轮，它不要求用户输入U1A1U1A2U2…U_n，而是只要给Un就好了。在这种模式下，transformers中的apply chat template是不适用的。因为它里面有 for messages的循环。这是我们没有使用apply chat template的主要原因。在model.py 中，应用对话模板的方式有2种，如下所示。其中 `get_prompt`就是在交互式的场景中用的。
> 
> ```
> def get_prompt(self, prompt, sequence_start=True):
>         """Return the prompt that is concatenated with other elements in the
>         chat template.
> 
>         Args:
>             prompt (str): user's input prompt
>             sequence_start (bool): indicator for the first round chat of a
>                session sequence
>         Returns:
>             str: the concatenated prompt
>         """
>         if self.capability == 'completion':
>             return prompt
>         if sequence_start:
>             # None is different from ''
>             if self.meta_instruction is not None:
>                 return f'{self.system}{self.meta_instruction}{self.eosys}' \
>                     f'{self.user}{prompt}{self.eoh}' \
>                     f'{self.assistant}'
>             else:
>                 return f'{self.user}{prompt}{self.eoh}' \
>                        f'{self.assistant}'
>         else:
>             return f'{self.separator}{self.user}{prompt}{self.eoh}' \
>                    f'{self.assistant}'
> 
>     def messages2prompt(self, messages, sequence_start=True, **kwargs):
>         """Return the prompt that is concatenated with other elements in the
>         chat template.
> 
>         Args:
>             messages (str | List): user's input prompt
>         Returns:
>             str: the concatenated prompt
>         """
>         if isinstance(messages, str):
>             return self.get_prompt(messages, sequence_start)
>         box_map = dict(user=self.user,
>                        assistant=self.assistant,
>                        system=self.system)
>         eox_map = dict(user=self.eoh,
>                        assistant=self.eoa + self.separator,
>                        system=self.eosys)
>         ret = ''
>         if self.meta_instruction is not None and sequence_start:
>             if len(messages) and messages[0]['role'] != 'system':
>                 ret += f'{self.system}{self.meta_instruction}{self.eosys}'
>         for message in messages:
>             role = message['role']
>             content = message['content']
>             ret += f'{box_map[role]}{content}{eox_map[role]}'
>         ret += f'{self.assistant}'
>         return ret
> ```
> 
> 2. 在多模态场景下，比如internvl，internlm-xcomposer，它们都没在tokenizer-config.json中提供对话模板，对话模板是在代码中写死的
> 
> 关于local模型，可以通过--model-name指定内置模板。这种方式，的确需要有清晰的文档说明。这一点我们改进，放在0.6.0版本里

可以去config文件里判断模型类型啊 通过文件夹名称判断 风险太大了，而且我在pipe的model_name中声明了 模型，推断时候返回的template还是None

**Comment by lvhan028** [comment]
恩，是的。在修改方案了。

**Comment by lvhan028** [comment]
想了下，我们还是通过在文档和工具提示信息中加比较合适。
因为相同架构的模型，它们的对话模板也是可能不一致的。比如基于llama系列模型的微调模型。

**Comment by janelu9** [comment]
> 想了下，我们还是通过在文档和工具提示信息中加比较合适。
> 
> 因为相同架构的模型，它们的对话模板也是可能不一致的。比如基于llama系列模型的微调模型。
> 
> 

能给pipe.generate一个输入是input_id的参数吗？用户可以直接输入token_id 
主要是图文多模态情况下，文件名它解析不出来时候也不报错，但是推理时候 处理出来的decorated是None，即使输入model_name也无效
建议先去tokenizer的config找 chat_template找不到再提示用户通过输入模型名称来判断
还有就是可以根据config.json里面的model_type和vocab_size来推断是哪个模型 推不出来就报错 或者提示没有template 把do_preprocess置为false呗 让用户可以自己添加template

**Comment by lvhan028** [comment]
pipe.generate 支持 input_ids，这个需求可以考虑。

文件名解析部分，目前的做法是，没有匹配到内置的模板，就fallback到基座模型。这和 vllm 没有找到 chat_template 字段就认为是基座模型，逻辑上是一样的。我想，这个逻辑可以保持，我们增加warning log提醒下

如果输入 model_name 无效，这是bug，我们检查下。

根据 config.json推断感觉不太合适。相同架构、相同词表，微调可以使用自定义的对话模板。

**Comment by janelu9** [comment]
> pipe.generate 支持 input_ids，这个需求可以考虑。
> 
> 
> 
> 文件名解析部分，目前的做法是，没有匹配到内置的模板，就fallback到基座模型。这和 vllm 没有找到 chat_template 字段就认为是基座模型，逻辑上是一样的。我想，这个逻辑可以保持，我们增加warning log提醒下
> 
> 
> 
> 如果输入 model_name 无效，这是bug，我们检查下。
> 
> 
> 
> 根据 config.json推断感觉不太合适。相同架构、相同词表，微调可以使用自定义的对话模板。
> 
> 

如果到了看词表还没有找到用户的template，那就用开源默认的，再加个warning没毛病
