### ISSUE TITLE
[Feature] 对api_server的一些建议

### ISSUE THREAD

**Issue by ly19970621** [InternLM/lmdeploy#2152]
### Motivation

我用lmdeploy serve api_server起了一个推理服务InternVL2-26B，发现了以下问题：
1、设置stream=true时，发现每一条都会有"usage":null的内容，生成最后一个token时，"usage"并没有具体的输入和输出tokens信息，这样的话就没有办法统计流式接口的tokens，我理解这不是标准的openai格式，请各位大佬关注修一下。
2、压测接口时，逐渐增加并发数，发现显存占用一直在变多，不请求也没有清除多余显存占用，建议增加每次请求完成后清理显存占用的操作。
3、服务部署成功后，内存似乎没有释放，free -m 发现有大量的内存在buff/cache里，请各位大佬关注一下。
![Snipaste_2024-07-26_15-11-05](https://github.com/user-attachments/assets/4600488b-d919-45a3-82c5-735602cecf9a)

**Comment by akai-shuuichi** [comment]
> ### Motivation
> 我用lmdeploy serve api_server起了一个推理服务InternVL2-26B，发现了以下问题： 1、设置stream=true时，发现每一条都会有"usage":null的内容，生成最后一个token时，"usage"并没有具体的输入和输出tokens信息，这样的话就没有办法统计流式接口的tokens，我理解这不是标准的openai格式，请各位大佬关注修一下。 2、压测接口时，逐渐增加并发数，发现显存占用一直在变多，不请求也没有清除多余显存占用，建议增加每次请求完成后清理显存占用的操作。 3、服务部署成功后，内存似乎没有释放，free -m 发现有大量的内存在buff/cache里，请各位大佬关注一下。 ![Snipaste_2024-07-26_15-11-05](https://private-user-images.githubusercontent.com/65438006/352432165-4600488b-d919-45a3-82c5-735602cecf9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5ODE4NDMsIm5iZiI6MTcyMTk4MTU0MywicGF0aCI6Ii82NTQzODAwNi8zNTI0MzIxNjUtNDYwMDQ4OGItZDkxOS00NWEzLTgyYzUtNzM1NjAyY2VjZjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA4MTIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2YmZjYWI3NmU1MGE0NDk5ZGEzMTg4Y2Y4NmI4ODA0YWNkMmUzYjNlZGNkMTA4NjAzNjQ2ZTU3ZTc3NWRhZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nyDAw8k4VcQeDmhMI-PSXn1JC0rvVV1QlfuqdHqaa74)
> 
> ### Related resources
> _No response_
> 
> ### Additional context
> _No response_

1. openAI对于流的usage处理应当是是 `stream_options: {"include_usage": true}` ，应该实现这个参数的处理

**Comment by lvhan028** [comment]
@AllentDan may check `stream_options: {"include_usage": true}`

**Comment by AllentDan** [comment]
> @AllentDan may check `stream_options: {"include_usage": true}`

We have to return the usage in each streaming response. `include_usage` is different.
> If set, an additional chunk will be streamed before the data: [DONE] message. The usage field on this chunk shows the token usage statistics for the entire request, and the choices field will always be an empty array. All other chunks will also include a usage field, but with a null value.

**Comment by lvhan028** [comment]
> 1、设置stream=true时，发现每一条都会有"usage":null的内容，生成最后一个token时，"usage"并没有具体的输入和输出tokens信息，这样的话就没有办法统计流式接口的tokens，我理解这不是标准的openai格式，请各位大佬关注修一下。
最后一个token会给出输入、输出的token数。流式输出过程中，这个信息是空。是标准的openai格式。
如果最后一个token没有给，烦请提供下复现的方式。

> 2、压测接口时，逐渐增加并发数，发现显存占用一直在变多，不请求也没有清除多余显存占用，建议增加每次请求完成后清理显存占用的操作。
显存一旦申请，不释放。频繁释放再申请会导致性能变差。

> 3、服务部署成功后，内存似乎没有释放，free -m 发现有大量的内存在buff/cache里，请各位大佬关注一下。
可能是transformers引起的
