### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by lyc728** [InternLM/lmdeploy#2154]
现在用的Minicpmv2.5 走的是最简洁的推理
image = load_image('https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/tests/data/tiger.jpeg')
response = pipe(('describe this image', image))
print(response)
报错如下：
  ```
  response = pipe(('describe this image', image))
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/serve/vl_async_engine.py", line 123, in __call__
    return super().__call__(prompts, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/serve/async_engine.py", line 305, in __call__
    return self.batch_infer(prompts,
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/serve/vl_async_engine.py", line 109, in batch_infer
    return super().batch_infer(prompts, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/serve/async_engine.py", line 429, in batch_infer
    _get_event_loop().run_until_complete(gather())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/serve/async_engine.py", line 426, in gather
    await asyncio.gather(
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/serve/async_engine.py", line 411, in _inner_call
    async for out in generator:
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/serve/async_engine.py", line 576, in generate
    prompt_input = await self._get_prompt_input(prompt,
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/serve/vl_async_engine.py", line 59, in _get_prompt_input
    segs = decorated.split(IMAGE_TOKEN)
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by irexyc** [comment]
一般这种报错是因为没有匹配到对话模版

如果不指定对话模版（ChatTemplateConfig），lmdeploy默认是按照文件夹名字（模型在hf上的名字）来匹配的

lmdeploy 目前只支持 openbmb/MiniCPM-Llama3-V-2_5 这个模型，如果你说的模型是这个的话，可以把文件夹名字改成MiniCPM-Llama3-V-2_5 或者创建pipeline的时候指定 pipe = pipeline(..., chat_template_config=ChatTemplateConfig('llama3'))

如果出现类似这个 https://github.com/InternLM/lmdeploy/issues/2129 的问题，是因为 MiniCPM-Llama3-V-2_5 最近改了代码，我们是复用上游hf的代码，可以按照 [这个pr](https://github.com/InternLM/lmdeploy/pull/2139/files) 对本地安装目录中的lmdeploy 代码进行修改

**Comment by lyc728** [comment]
> ChatTemplateConfig

我是自己在swift上面进行微调的，然后进行merge了 好像这边不匹配这个模型

**Comment by lvhan028** [comment]
什么模型？什么配置？什么显卡？怎么测试的？
烦请提供完整的信息

**Comment by lyc728** [comment]
模型：MiniCPM-Llama3-V-2_5

**Comment by lvhan028** [comment]
1. 没有加时间戳
2. 没有约束要生成多少token
3. 只用一条prompt测试

**Comment by lvhan028** [comment]
可以参考下benchmark/profile_throughput.py

**Comment by lyc728** [comment]
我是有一个json文件，可以看出来，也打印了推理的时间，这边我int4提升了20%, kv int8 量化没有提升
```
start = time()
for item in tqdm(ls):
    ask = item['conversations'][0]['content'].split('<image>\n')[1]
    answer = item['conversations'][1]['content']
    img_path = item['image']
    response = pipe((ask, img_path))
    print(response)
end = time() - start
print("end_time", end)
```

**Comment by lvhan028** [comment]
你现在的用法是逐个prompt请求，这样是测的latency，不是throughput。
测 LLM 的throughput 脚本是 profile_throughput.py, 或者 profile_pipeline_api.py
另，LMDeploy 关于 VLM 的benchmark脚本还没有合入 https://github.com/InternLM/lmdeploy/pull/1662。可先参考下

**Comment by lyc728** [comment]
> 你现在的用法是逐个prompt请求，这样是测的latency，不是throughput。 测 LLM 的throughput 脚本是 profile_throughput.py, 或者 profile_pipeline_api.py 另，LMDeploy 关于 VLM 的benchmark脚本还没有合入 [https://github.com/InternLM/lmdeploy/pull/1662。可先参考下](https://github.com/InternLM/lmdeploy/pull/1662%E3%80%82%E5%8F%AF%E5%85%88%E5%8F%82%E8%80%83%E4%B8%8B)

 profile_throughput.py这个代码没看到图片的处理 只看到json传进来，这样多模态不适用把

**Comment by lvhan028** [comment]
我已经说了，profile_throughput.py是 LLM 的，从我们benchmark LLM 的结果看，kv int8的速度优于 half。
也说明了LMDeploy 关于 VLM 的benchmark脚本还没有合入 https://github.com/InternLM/lmdeploy/pull/1662
