### ISSUE TITLE
[Bug] llama3 支持

### ISSUE THREAD

**Issue by lydecho** [InternLM/lmdeploy#2155]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

params.llama3_alpha = params_.original_max_position_embeddings / 2 * PI * inv_diff_freq_factor; 
不应该在 2*PI 加一个括号吗？

### Reproduction

--

### Environment

```Shell
--
```

### Error traceback

```Shell
--
```

**Comment by lvhan028** [comment]
OMG, you are absolutely right. I missed the parentheses.

**Comment by zhyncs** [comment]
> OMG, you are absolutely right. I missed the parentheses.

May we release a hot fix version v0.5.2.post1?

**Comment by lvhan028** [comment]
Yes, working on it. 
It's wired that 0.5.2 passes the model evaluation test.

**Comment by lvhan028** [comment]
The needle in a haystack experiment failed in v0.5.2. Now it works in v0.5.2.post1
