### ISSUE TITLE
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)

### ISSUE THREAD

**Issue by wangzhijian-tal** [InternLM/lmdeploy#216]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

# 1. Download InternLM model

# Make sure you have git-lfs installed (https://git-lfs.com)
git lfs install
git clone https://huggingface.co/internlm/internlm-chat-7b /path/to/internlm-chat-7b

# if you want to clone without large files – just their pointers
# prepend your git clone with the following env var:
GIT_LFS_SKIP_SMUDGE=1

# 2. Convert InternLM model to turbomind's format, which will be in "./workspace" by default
python3 -m lmdeploy.serve.turbomind.deploy internlm-chat-7b /path/to/internlm-chat-7b

I follow above process to convert internlm-chat-7b model, but failed.

### Reproduction

python -m lmdeploy.serve.turbomind.deploy internlm-chat-7b data/model/internlm-chat-7b

tok_embeddings.weight torch.Size([103168, 4096])
norm.weight torch.Size([4096])
output.weight torch.Size([103168, 4096])
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tal-vePFS/ENGINE/wangzhijian/lmdeploy/lmdeploy/serve/turbomind/deploy.py", line 592, in <module>
    fire.Fire(main)
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/tal-vePFS/ENGINE/wangzhijian/lmdeploy/lmdeploy/serve/turbomind/deploy.py", line 562, in main
    res = deploy_hf(model_name, model_path, tokenizer_path,
  File "/tal-vePFS/ENGINE/wangzhijian/lmdeploy/lmdeploy/serve/turbomind/deploy.py", line 490, in deploy_hf
    return export(model_name, num_layer, norm_eps, kv_head_num, model_params,
  File "/tal-vePFS/ENGINE/wangzhijian/lmdeploy/lmdeploy/serve/turbomind/deploy.py", line 174, in export
    model = MODELS.get(model_name)()
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/registry.py", line 451, in get
    self.import_from_location()
  File "/opt/conda/lib/python3.8/site-packages/mmengine/registry/registry.py", line 377, in import_from_location
    print_log(
  File "/opt/conda/lib/python3.8/site-packages/mmengine/logging/logger.py", line 322, in print_log
    logger_instance = MMLogger.get_current_instance()
  File "/opt/conda/lib/python3.8/site-packages/mmengine/logging/logger.py", line 257, in get_current_instance
    cls.get_instance('mmengine')
  File "/opt/conda/lib/python3.8/site-packages/mmengine/utils/manager.py", line 110, in get_instance
    instance = cls(name=name, **kwargs)  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/mmengine/logging/logger.py", line 190, in __init__
    global_rank = _get_rank()
  File "/opt/conda/lib/python3.8/site-packages/mmengine/logging/logger.py", line 355, in _get_rank
    from mmengine.dist import get_rank
  File "/opt/conda/lib/python3.8/site-packages/mmengine/dist/__init__.py", line 2, in <module>
    from .dist import (all_gather_object, all_reduce, all_gather, all_reduce_dict,
  File "/opt/conda/lib/python3.8/site-packages/mmengine/dist/dist.py", line 22, in <module>
    from mmengine.utils.dl_utils import TORCH_VERSION
  File "/opt/conda/lib/python3.8/site-packages/mmengine/utils/dl_utils/__init__.py", line 3, in <module>
    from .collect_env import collect_env
  File "/opt/conda/lib/python3.8/site-packages/mmengine/utils/dl_utils/collect_env.py", line 8, in <module>
    import cv2
  File "/opt/conda/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/opt/conda/lib/python3.8/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/opt/conda/lib/python3.8/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/lib/python3.8/site-packages/cv2/gapi/__init__.py", line 301, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)

**Comment by wangzhijian-tal** [comment]
> @irexyc Let's remove the dependency on mmengine

remove what? cv2?

**Comment by irexyc** [comment]
我感觉是你环境的问题。只 import cv2 会报错不

**Comment by wangzhijian-tal** [comment]
> 

Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/opt/conda/lib/python3.8/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/opt/conda/lib/python3.8/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/lib/python3.8/site-packages/cv2/gapi/__init__.py", line 301, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)
>>> 

cv2的版本不对？

**Comment by wangzhijian-tal** [comment]
> 我感觉是你环境的问题。只 import cv2 会报错不
> 
> 你可以把你的环境列一下 pip list

Package                       Version                  Location
----------------------------- ------------------------ -----------------------------------
absl-py                       1.1.0
accelerate                    0.17.1
addict                        2.4.0
aiohttp                       3.8.4
aiosignal                     1.3.1
alabaster                     0.7.12
aliyun-python-sdk-core        2.13.36
aliyun-python-sdk-kms         2.16.0
anykeystore                   0.2
apex                          0.1
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
asttokens                     2.0.5
async-timeout                 4.0.2
attrs                         21.4.0
audioread                     2.1.9
Babel                         2.10.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
beautifulsoup4                4.11.1
bitsandbytes                  0.40.0.post4
bleach                        5.0.0
blis                          0.7.7
boto3                         1.26.94
botocore                      1.29.94
brotlipy                      0.7.0
cachetools                    5.2.0
catalogue                     2.0.6
certifi                       2022.5.18.1
cffi                          1.15.0
chardet                       4.0.0
charset-normalizer            2.0.12
cheroot                       9.0.0
click                         8.0.4
cloudpickle                   2.1.0
codecov                       2.1.12
colorama                      0.4.4
conda                         4.13.0
conda-build                   3.21.9
conda-package-handling        1.8.1
coverage                      6.4.1
cpm-kernels                   1.0.11
crcmod                        1.7
cryptacular                   1.6.2
cryptography                  37.0.2
cuda-python                   11.7.0
cudf                          22.4.0a0+306.g0cb75a4913
cugraph                       22.4.0a0+102.g4106a188
cuml                          22.4.0a0+108.g2be11269d
cupy-cuda115                  9.6.0
cycler                        0.11.0
cymem                         2.0.6
Cython                        0.29.30
dask                          2022.3.0
dask-cuda                     22.4.0
dask-cudf                     22.4.0a0+306.g0cb75a4913
dataclass-wizard              0.22.2
dataclasses                   0.8
datasets                      2.10.1
debugpy                       1.6.0
decorator                     5.1.1
deepspeed                     0.8.3
defusedxml                    0.7.1
delta-center-client           0.0.4
dill                          0.3.6
distributed                   2022.3.0
docutils                      0.17.1
einops                        0.6.0
entrypoints                   0.4
et-xmlfile                    1.1.0
executing                     0.8.3
expecttest                    0.1.3
fairscale                     0.4.13
fastjsonschema                2.15.3
fastrlock                     0.8
filelock                      3.7.1
fire                          0.5.0
Flask                         2.1.2
fonttools                     4.33.3
frozenlist                    1.3.3
fsspec                        2022.5.0
future                        0.18.2
gevent                        22.10.2
gitdb                         4.0.10
GitPython                     3.1.31
glob2                         0.7
google-auth                   2.7.0
google-auth-oauthlib          0.4.6
graphsurgeon                  0.4.5
greenlet                      2.0.2
grpcio                        1.46.3
HeapDict                      1.0.1
hjson                         3.1.0
huggingface-hub               0.13.3
hupper                        1.12
hypothesis                    4.50.8
icetk                         0.0.4
idna                          3.3
imagesize                     1.3.0
importlib-metadata            6.8.0
importlib-resources           5.7.1
iniconfig                     1.1.1
ipykernel                     6.14.0
ipython                       8.4.0
ipython-genutils              0.2.0
itsdangerous                  2.1.2
jaraco.functools              3.6.0
jedi                          0.18.1
Jinja2                        3.1.2
jmespath                      0.10.0
joblib                        1.1.0
json5                         0.9.8
jsonlines                     3.1.0
jsonschema                    4.6.0
jupyter-client                7.3.4
jupyter-core                  4.10.0
jupyter-tensorboard           0.2.0
jupyterlab                    2.3.2
jupyterlab-pygments           0.2.2
jupyterlab-server             1.2.0
jupytext                      1.13.8
kiwisolver                    1.4.3
langcodes                     3.3.0
Levenshtein                   0.21.0
libarchive-c                  4.0
librosa                       0.8.1
llama                         0.0.0                    /tal-vePFS/ENGINE/lichanglong/llama
llvmlite                      0.36.0
lmdb                          1.3.0
locket                        1.0.0
Markdown                      3.3.7
markdown-it-py                2.2.0
MarkupSafe                    2.1.1
matplotlib                    3.5.2
matplotlib-inline             0.1.3
mdit-py-plugins               0.3.0
mdurl                         0.1.1
Megatron                      0.5.1
megatron-core                 0.2.0
mistune                       0.8.4
mmengine                      0.8.4
mock                          4.0.3
more-itertools                9.1.0
mpmath                        1.3.0
msgpack                       1.0.4
multidict                     6.0.4
multiprocess                  0.70.14
murmurhash                    1.0.7
nbclient                      0.6.4
nbconvert                     6.5.0
nbformat                      5.4.0
nest-asyncio                  1.5.5
networkx                      2.6.3
ninja                         1.11.1
nltk                          3.7
notebook                      6.4.10
numba                         0.53.1
numpy                         1.22.4
nvidia-dali-cuda110           1.14.0
nvidia-pyindex                1.0.9
nvtx                          0.2.5
oauthlib                      3.2.0
onnx                          1.11.0
openai                        0.27.6
opencv-python                 4.8.0.76
opendelta                     0.3.2
openpyxl                      3.1.2
oss2                          2.15.0
packaging                     21.3
pandas                        1.3.5
pandocfilters                 1.5.0
parameterized                 0.8.1
parso                         0.8.3
partd                         1.2.0
PasteDeploy                   3.0.1
pathy                         0.6.1
pbkdf2                        1.3
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.0.1
pip                           21.2.4
pkginfo                       1.8.3
plaster                       1.1.2
plaster-pastedeploy           1.0.1
platformdirs                  3.10.0
pluggy                        1.0.0
polygraphy                    0.33.0
pooch                         1.6.0
preshed                       3.0.6
prettytable                   3.3.0
prometheus-client             0.14.1
prompt-toolkit                3.0.29
protobuf                      3.20.0
psutil                        5.9.1
ptyprocess                    0.7.0
pudb                          2022.1.3
pure-eval                     0.2.2
py                            1.11.0
py-cpuinfo                    9.0.0
pyarrow                       6.0.1
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pybind11                      2.9.2
pycocotools                   2.0+nv0.6.0
pycosat                       0.6.3
pycparser                     2.21
pycryptodome                  3.17
pydantic                      1.8.2
pydot                         1.4.2
Pygments                      2.14.0
Pympler                       1.0.1
pynvml                        11.4.1
pyOpenSSL                     22.0.0
pyparsing                     3.0.9
pypinyin                      0.49.0
pyramid                       2.0.1
pyramid-mailer                0.15.1
pyrsistent                    0.18.1
PySocks                       1.7.1
pytest                        6.2.5
pytest-cov                    3.0.0
pytest-pythonpath             0.7.4
python-dateutil               2.8.2
python-hostlist               1.21
python-Levenshtein            0.21.0
python-nvd3                   0.15.0
python-slugify                6.1.2
python3-openid                3.2.0
pytorch-quantization          2.1.2
pytz                          2022.1
PyYAML                        6.0
pyzmq                         23.1.0
raft                          22.4.0a0+113.gf5d2627
rapidfuzz                     3.0.0
regex                         2022.6.2
repoze.sendmail               4.4.1
requests                      2.27.1
requests-oauthlib             1.3.1
resampy                       0.2.2
responses                     0.18.0
revtok                        0.0.3
rich                          13.3.3
rmm                           22.4.0a0+50.gf82d458
rsa                           4.8
ruamel-yaml-conda             0.15.80
s3transfer                    0.6.0
sacremoses                    0.0.53
safetensors                   0.3.2
scikit-learn                  0.24.2
scipy                         1.6.3
Send2Trash                    1.8.0
sentencepiece                 0.1.97
setuptools                    59.5.0
shellingham                   1.4.0
shortuuid                     1.0.11
six                           1.16.0
sklearn                       0.0.post1
smart-open                    5.2.1
smmap                         5.0.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
SoundFile                     0.10.3.post1
soupsieve                     2.3.1
spacy                         3.3.1
spacy-legacy                  3.0.9
spacy-loggers                 1.0.2
Sphinx                        5.0.1
sphinx-glpi-theme             0.3
sphinx-rtd-theme              1.0.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
SQLAlchemy                    1.4.47
srsly                         2.4.3
stack-data                    0.2.0
sympy                         1.12
tabulate                      0.8.9
tblib                         1.7.0
tensorboard                   2.9.1
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.1
tensorboardX                  2.6
tensorrt                      8.2.5.1
termcolor                     2.3.0
terminado                     0.15.0
text-unidecode                1.3
thinc                         8.0.17
threadpoolctl                 3.1.0
tinycss2                      1.1.1
tokenizers                    0.13.2
toml                          0.10.2
tomli                         2.0.1
toolz                         0.11.2
torch                         1.13.0a0+340c412
torch-tensorrt                1.1.0a0
torchtext                     0.13.0a0
torchvision                   0.13.0a0
tornado                       6.1
tqdm                          4.64.0
traitlets                     5.2.2.post1
transaction                   3.1.0
transformers                  4.26.1
translationstring             1.4
treelite                      2.3.0
treelite-runtime              2.3.0
typer                         0.4.1
typing_extensions             4.2.0
ucx-py                        0.25.0a0+13.ga16f8a2
uff                           0.6.9
urllib3                       1.26.9
urwid                         2.1.2
urwid-readline                0.13
velruse                       1.1.1
venusian                      3.0.0
wasabi                        0.9.1
wcwidth                       0.2.5
web.py                        0.62
webencodings                  0.5.1
WebOb                         1.8.7
websocket                     0.2.1
websocket-client              1.5.3
Werkzeug                      2.1.2
wget                          3.2
wheel                         0.37.1
WTForms                       3.0.1
wtforms-recaptcha             0.3.2
xgboost                       1.5.2
xxhash                        3.2.0
yacs                          0.1.8
yapf                          0.40.1
yarl                          1.8.2
zict                          2.2.0
zipp                          3.8.0
zope.deprecation              5.0
zope.event                    4.6
zope.interface                6.0
zope.sqlalchemy               2.0

**Comment by irexyc** [comment]
先把这个卸载了 `opencv-python 4.8.0.76`

可以装个低版本的试试比如 `pip install opencv-python==4.5.5.64`

如果机器没有显示环境，可以装 `pip install opencv-python-headless`

**Comment by wangzhijian-tal** [comment]
> 先把这个卸载了 `opencv-python 4.8.0.76`
> 
> 可以装个低版本的试试比如 `pip install opencv-python==4.5.5.64`
> 
> 如果机器没有显示环境，可以装 `pip install opencv-python-headless`

好的，谢谢，我去试试

**Comment by wangzhijian-tal** [comment]
> 



> 先把这个卸载了 `opencv-python 4.8.0.76`
> 
> 可以装个低版本的试试比如 `pip install opencv-python==4.5.5.64`
> 
> 如果机器没有显示环境，可以装 `pip install opencv-python-headless`

这个可以解决，感谢
