### ISSUE TITLE
关于多图插入位置的问题请教一下

### ISSUE THREAD

**Issue by liangofthechen** [InternLM/lmdeploy#2160]
### 📚 The doc issue

您好。关于多图插入位置的问题请教一下。以下是我的代码

from lmdeploy import pipeline
from lmdeploy.vl import load_image
from lmdeploy.vl.constants import IMAGE_TOKEN
pipe = pipeline('internlm/internlm-xcomposer2d5-7b')
imgpaths=[]#是图片存储路径列表
images = [load_image(imgpath) for imgpath in imgpaths]
response1 = pipe(('请你根据背景回答以下问题 是一个绿色哭着的脸 是一个上升的箭头 是一个绿色的放大镜 请你告诉我图片是什么', images))
response2 = pipe((f'请你根据背景回答以下问题 {IMAGE_TOKEN}是一个绿色哭着的脸 {IMAGE_TOKEN}是一个上升的箭头 {IMAGE_TOKEN}是一个绿色的放大镜 请你告诉我图片{IMAGE_TOKEN}是什么', images))

我发现使用上面两个Prompt得到的效果都不好。请问是我的图片插入TOKEN有问题吗？正确的方法是什么？

以下是我的环境信息：
sys.platform: linux
Python: 3.9.19 | packaged by conda-forge | (main, Mar 20 2024, 12:50:21) [GCC 12.3.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: Tesla V100-PCIE-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.0, V11.0.221
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 2.2.2+cu118
PyTorch compiling details: PyTorch built with:

GCC 9.3
C++ Version: 201703
Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
OpenMP 201511 (a.k.a. OpenMP 4.5)
LAPACK is enabled (usually provided by MKL)
NNPACK is enabled
CPU capability usage: AVX2
CUDA Runtime 11.8
NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_90,code=sm_90
CuDNN 8.7
Magma 2.6.1
Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF,
TorchVision: 0.17.2+cu118
LMDeploy: 0.5.1+
transformers: 4.33.2
gradio: 3.44.4
fastapi: 0.110.3
pydantic: 2.7.1
triton: 2.2.0
NVIDIA Topology:
GPU0 GPU1 GPU2 GPU3 GPU4 GPU5 GPU6 GPU7 NIC0 CPU Affinity NUMA Affinity GPU NUMA ID
GPU0 X PIX PIX PIX PHB PHB PHB PHB PHB 0-13,28-41 0 N/A
GPU1 PIX X PIX PIX PHB PHB PHB PHB PHB 0-13,28-41 0 N/A
GPU2 PIX PIX X PIX PHB PHB PHB PHB PHB 0-13,28-41 0 N/A
GPU3 PIX PIX PIX X PHB PHB PHB PHB PHB 0-13,28-41 0 N/A
GPU4 PHB PHB PHB PHB X PIX PIX PIX PIX 0-13,28-41 0 N/A
GPU5 PHB PHB PHB PHB PIX X PIX PIX PIX 0-13,28-41 0 N/A
GPU6 PHB PHB PHB PHB PIX PIX X PIX PIX 0-13,28-41 0 N/A
GPU7 PHB PHB PHB PHB PIX PIX PIX X PIX 0-13,28-41 0 N/A
NIC0 PHB PHB PHB PHB PIX PIX PIX PIX X

Legend:

X = Self
SYS = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
PHB = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
PXB = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
PIX = Connection traversing at most a single PCIe bridge
NV# = Connection traversing a bonded set of # NVLinks

NIC Legend:

NIC0: mlx5_bond_0

多谢。

**Comment by RunningLeon** [comment]
@liangofthechen hi, image_token插入位置可以先用transformers推理试试，确认合适位置。参考官方example： https://huggingface.co/internlm/internlm-xcomposer2d5-7b#quickstart
