### ISSUE TITLE
[Bug] Unrecognized keys in `rope_scaling` for 'rope_type'='dynamic': {'type'}

### ISSUE THREAD

**Issue by pseudotensor** [InternLM/lmdeploy#2163]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

During startup, shows these:
```
Fetching 49 files: 100%|??????????| 49/49 [00:00<00:00, 59108.68it/s]
Unrecognized keys in `rope_scaling` for 'rope_type'='dynamic': {'type'}
Unrecognized keys in `rope_scaling` for 'rope_type'='dynamic': {'type'}
Unrecognized keys in `rope_scaling` for 'rope_type'='dynamic': {'type'}
Unrecognized keys in `rope_scaling` for 'rope_type'='dynamic': {'type'}
Unrecognized keys in `rope_scaling` for 'rope_type'='dynamic': {'type'}
Unrecognized keys in `rope_scaling` for 'rope_type'='dynamic': {'type'}
Unrecognized keys in `rope_scaling` for 'rope_type'='dynamic': {'type'}
Unrecognized keys in `rope_scaling` for 'rope_type'='dynamic': {'type'}
Unrecognized keys in `rope_scaling` for 'rope_type'='dynamic': {'type'}
Unrecognized keys in `rope_scaling` for 'rope_type'='dynamic': {'type'}
```

Can't tell if they are fatal or not.  I also noticed them in this issue:

https://github.com/InternLM/lmdeploy/issues/2162

I've rebuilt the docker with latest compatible transformers and still see this.

### Reproduction

```
cd ~/lmdeploy
docker build . -f docker/Dockerfile -t internvlmain --no-cache
```

```
FROM FROM internvlmain

RUN apt-get update && apt-get install -y python3 python3-pip git

WORKDIR /app

RUN pip3 uninstall pkg_resources -y
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools==66.1.1
RUN pip3 uninstall -y ninja && pip3 install ninja
RUN CUDA_HOME=/usr/local/cuda-11.8/ PIP_EXTRA_INDEX_URL=https://download.pytorch.org/whl/cu118 pip3 install timm xformers triton==2.1.0 transformers
RUN MAX_JOBS=4 CUDA_HOME=/usr/local/cuda-11.8/ PIP_EXTRA_INDEX_URL=https://download.pytorch.org/whl/cu118 FLASH_ATTENTION_FORCE_BUILD=TRUE pip3 install flash-attn==2.5.2 --no-build-isolation
RUN pip3 install git+https://github.com/haotian-liu/LLaVA.git --no-deps

COPY . .

CMD ["lmdeploy", "serve", "api_server", "OpenGVLab/InternVL-Chat-V1-5"]
```

```
docker build - < Dockerfile.internvl -t internvl
```

inside image has latest transformers:
```
root@bb4428656bab:/app# python
Python 3.8.10 (default, Mar 25 2024, 10:42:49) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import transformers
>>> transformers.__version__
'4.43.3'

```

### Environment

```Shell
as above
```

### Error traceback

```Shell
as above
```

**Comment by lvhan028** [comment]
may use lmdeploy 0.5.2.post1

**Comment by RunningLeon** [comment]
@pseudotensor hi, what is your base-image `FROM internvlmain`?  It runs fine on myside.

**Comment by pseudotensor** [comment]
Hi, I shared how internvlmain is built above.  It's just from repo.

**Comment by RunningLeon** [comment]
> Hi, I shared how internvlmain is built above. It's just from repo.
> 
> The message is not fatal, things still run.

hi, but in your customer dockerfile, the base image is `internvlmain`. We do not have access to this base image.
> FROM FROM internvlmain

**Comment by pseudotensor** [comment]
Hi, but I shared how I built it:
```
cd ~/lmdeploy
docker build . -f docker/Dockerfile -t internvlmain --no-cache
```

It's just normal lmdeploy build from source.

**Comment by RunningLeon** [comment]
@pseudotensor hi, this is the warning from transformers  when calling `AutoConfig.from_pretrained`. You could try with `"transformers_version": "4.37.2",`
https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5/blob/7e2100537fee41c08e1d0c1436179328dfc4396d/config.json#L140

**Comment by pseudotensor** [comment]
Ok if it's clearly just a warning it's fine.  I'm using latest transformers so I can run llama3.1 as well.
