### ISSUE TITLE
[Bug] 模型接口调用时，直接模型服务崩溃

### ISSUE THREAD

**Issue by WCwalker** [InternLM/lmdeploy#2170]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

![image](https://github.com/user-attachments/assets/eb96ae71-e6f0-44cf-b12f-8fd79669deae)
想请问一下，怎么查看报错信息；另外能不能遇到报错就跳过，而不是直接服务崩溃，谢谢

### Reproduction

lmdeploy serve api_server /home/mingqiang/model/model_file/origin_model/internlm2_5-7b-chat/ --backend turbomind --model-name internlm2_5-7b-chat --tp 4 --server-port 10001 --cache-max-entry-count 0.1

### Environment

```Shell
sys.platform: linux
Python: 3.8.19 (default, Mar 20 2024, 19:58:24) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3: NVIDIA A800 80GB PCIe
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.1, V12.1.105
GCC: gcc (Debian 10.2.1-6) 10.2.1 20210110
PyTorch: 2.2.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

TorchVision: 0.17.2+cu121
LMDeploy: 0.5.1+
transformers: 4.40.1
gradio: Not Found
fastapi: 0.110.2
pydantic: 2.7.1
triton: 2.2.0
NVIDIA Topology: 
        GPU0    GPU1    GPU2    GPU3    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      PIX     PIX     PIX     0-27,56-83      0               N/A
GPU1    PIX      X      PIX     PIX     0-27,56-83      0               N/A
GPU2    PIX     PIX      X      PIX     0-27,56-83      0               N/A
GPU3    PIX     PIX     PIX      X      0-27,56-83      0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

**Comment by WCwalker** [comment]
因为这是偶发性了，同一数据调用，有时会报错，测试10次里面遇到过2次，所以想看看通过什么办法可以避免，感谢

**Comment by lvhan028** [comment]
看不出来什么原因。
能不能先把 tp 关掉试试？你的设备型号是A800-80G，单卡部署 internlm2.5-7b 绰绰有余

**Comment by WCwalker** [comment]
> 看不出来什么原因。 能不能先把 tp 关掉试试？你的设备型号是A800-80G，单卡部署 internlm2.5-7b 绰绰有余
以下时我改了api_serve.py的代码，想用批量处理，不知道是不是改的有问题
@app.post('/v1/chat/completions_batch')
# @app.post('/v1/chat/completions')
async def chat_completions_batch(request: ChatCompletionBatchRequest,
                              raw_request: Request = None):
    
    if request.session_id == -1:
        request.session_id = random.randint(1, 10086)

    error_check_ret = await check_request(request)
    if error_check_ret is not None:
        return error_check_ret

    gen_config = GenerationConfig(
    max_new_tokens=request.max_tokens if request.max_tokens else 1024,
    top_p=request.top_p,
    temperature=0.00001,
    repetition_penalty=1.01,
    ignore_eos=request.ignore_eos,
    stop_words=request.stop)

    logging.info(f"输入：{request}" )
    
    model_name = request.model
    request_id = str(request.session_id)
    created_time = int(time.time())
    generators = []
    for i in range(len(request.messages)):
        result_generator = VariableInterface.async_engine.generate(
            request.messages[i],
            # message_into_prompt(request.messages[i], request.prompt_type),
            request.session_id+i,
            gen_config=gen_config,  # always use stream to enable batching
            stream_response=True,
            sequence_start=True,
            sequence_end=True,
            do_preprocess=not isinstance(request.messages,
                                        str),  # text completion for string input
        )
        generators.append(result_generator)

    def create_stream_response_json(
        index: int,
        text: str,
        finish_reason: Optional[str] = None,
    ) -> str:
        choice_data = ChatCompletionResponseStreamChoice(
            index=index,
            delta=DeltaMessage(role='assistant', content=text),
            finish_reason=finish_reason,
        )
        response = ChatCompletionStreamResponse(
            id=request_id,
            created=created_time,
            model=model_name,
            choices=[choice_data],
        )
        response_json = response.model_dump_json()

        return response_json

    async def completion_stream_generator() -> AsyncGenerator[str, None]:
        # First chunk with role
        for i in range(request.n):
            choice_data = ChatCompletionResponseStreamChoice(
                index=i,
                delta=DeltaMessage(role='assistant'),
                finish_reason=None,
            )
            chunk = ChatCompletionStreamResponse(id=request_id,
                                                 choices=[choice_data],
                                                 model=model_name)
            data = chunk.model_dump_json(exclude_unset=True)
            yield f'data: {data}\n\n'

        async for res in result_generator:
            
            response_json = create_stream_response_json(
                index=0,
                text=res.response,
                finish_reason=res.finish_reason,
            )
            yield f'data: {response_json}\n\n'
        yield 'data: [DONE]\n\n'

    # Streaming response
    # if request.stream:
    #     return StreamingResponse(completion_stream_generator(),
    #                              media_type='text/event-stream')

    # Non-streaming response
    choices = []
    usage = UsageInfo()
    
    async def _inner_call(i, generator):
        final_res = None
        text = ''
        async for res in generator:
            if await raw_request.is_disconnected():
                # Abort the request if the client disconnects.
                VariableInterface.async_engine.stop_session(request.session_id)
                return create_error_response(HTTPStatus.BAD_REQUEST,
                                            'Client disconnected')
            final_res = res
            text += res.response
        assert final_res is not None
        #sky
        text = result_change(text)
        choice_data = ChatCompletionBatchResponseChoice(
            index=0,
            message=ChatMessage(role='assistant', content=text),
            finish_reason=final_res.finish_reason,
            rule_id=i,
        )
        choices.append(choice_data)

        total_tokens = sum([
            final_res.history_token_len, final_res.input_token_len,
            final_res.generate_token_len
        ])
        usage.prompt_tokens += final_res.input_token_len
        usage.completion_tokens += final_res.generate_token_len
        usage.total_tokens += total_tokens
    
    start_time = time.time()

    # await asyncio.gather(
    #     *[_inner_call(i, generators[i]) for i in range(len(generators))])
    try:
        await asyncio.wait_for(
                asyncio.gather(*[_inner_call(i, generators[i]) for i in range(len(generators))]),
                timeout=40
            )
        print("任务完成:")
    except asyncio.TimeoutError:
        # 如果任务在超时时间内未完成，会触发 TimeoutError 异常
        print("任务超时，需要处理超时情况")

        logging.error(request)
        
    end_time = time.time()
    duration = end_time - start_time
    print(f"程序运行时长：{duration}秒")        
    response = ChatCompletionBatchResponse(
        id=request_id,
        created=created_time,
        model=model_name,
        choices=choices,
        usage=usage,
    )
    logging.info(f"输出：{response}" )
    return response

**Comment by lvhan028** [comment]
Why not trying api_server's `v1/chat/completions` directly?

**Comment by WCwalker** [comment]
> Why not trying api_server's `v1/chat/completions` directly?



> Why not trying api_server's `v1/chat/completions` directly?

![image](https://github.com/user-attachments/assets/50e8e133-d844-4b09-955e-94b700424feb)
我加了info后，看到的服务崩溃前的信息，会不会应为总的tokens过长导致报错

**Comment by lvhan028** [comment]
code 6 表示过长了。这种情况下，生成的结果是空串

**Comment by WCwalker** [comment]
> code 6 表示过长了。这种情况下，生成的结果是空串

那我想请教一下，有什么办法避免这种情况出现，是不是要控制输入模型的token数，还是有什么参数可以控制，其实只要服务不崩溃就行

**Comment by lvhan028** [comment]
`--cache-max-entry-count 0.1` 给的太小了。
你的设备是A100-80G，用default value 0.8吧
