### ISSUE TITLE
[Docs] Lmdeploy 部署 VLM 类 openai 服务 接口支持多图吗？

### ISSUE THREAD

**Issue by JunDaLee** [InternLM/lmdeploy#2171]
### 📚 The doc issue

https://lmdeploy.readthedocs.io/zh-cn/latest/serving/api_server_vl.html
文档中给出的示例为单图，请问支持多图吗？谢谢
如果不支持请问我可以使用什么方式达到这种效果？

**Comment by irexyc** [comment]
openai的服务为例子：
https://lmdeploy.readthedocs.io/zh-cn/latest/serving/api_server_vl.html#lmdeploy-apiclient

message可以写成这样：
```
messages = [{
    'role':
    'user',
    'content': [{
        'type': 'text',
        'text': 'Describe the image please',
    }, {
        'type': 'image_url',
        'image_url': {
            'url':
            'https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/tests/data/tiger.jpeg',
        },
    },{
        'type': 'image_url',
        'image_url': {
            'url':
            'https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/tests/data/tiger.jpeg',
        },
    }]
}]
```
除了url，还可以传base64，参考https://platform.openai.com/docs/guides/vision/uploading-base-64-encoded-images


pipeline 接口可以参考 https://lmdeploy.readthedocs.io/zh-cn/latest/inference/vl_pipeline.html#id6


默认按照模型提供的demo的规则，在prompt中插入图片，如果要自己指定位置的话，需要在prompt中插入lmdeploy可识别的特殊的token，比如
```
    messages=[{
        'role':
        'user',
        'content': [{
            'type': 'text',
            'text': 'Describe the image please<IMAGE_TOKEN>',
        }, {
            'type': 'image_url',
            'image_url': {
                'url':
                'https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/tests/data/tiger.jpeg',
            },
        }],
    }],
```

**Comment by JunDaLee** [comment]
十分感谢

**Comment by suay1113** [comment]
> openai的服务为例子： https://lmdeploy.readthedocs.io/zh-cn/latest/serving/api_server_vl.html#lmdeploy-apiclient
> 
> message可以写成这样：
> 
> ```
> messages = [{
>     'role':
>     'user',
>     'content': [{
>         'type': 'text',
>         'text': 'Describe the image please',
>     }, {
>         'type': 'image_url',
>         'image_url': {
>             'url':
>             'https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/tests/data/tiger.jpeg',
>         },
>     },{
>         'type': 'image_url',
>         'image_url': {
>             'url':
>             'https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/tests/data/tiger.jpeg',
>         },
>     }]
> }]
> ```
> 
> 除了url，还可以传base64，参考https://platform.openai.com/docs/guides/vision/uploading-base-64-encoded-images
> 
> pipeline 接口可以参考 https://lmdeploy.readthedocs.io/zh-cn/latest/inference/vl_pipeline.html#id6
> 
> 默认按照模型提供的demo的规则，在prompt中插入图片，如果要自己指定位置的话，需要在prompt中插入lmdeploy可识别的特殊的token，比如
> 
> ```
>     messages=[{
>         'role':
>         'user',
>         'content': [{
>             'type': 'text',
>             'text': 'Describe the image please<IMAGE_TOKEN>',
>         }, {
>             'type': 'image_url',
>             'image_url': {
>                 'url':
>                 'https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/tests/data/tiger.jpeg',
>             },
>         }],
>     }],
> ```

请问，是不支持这样拼接使用吗？

messages =[
        {"role": "system", "content": "You are a helpful assistant."},
        {'role':'user', 'content': [
            {'type': 'text', 'text': 'Describe the image please<IMAGE_TOKEN>'}, 
            {'type': 'image_url','image_url': {'url':'https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/tests/data/tiger.jpeg'}},
            {'type': 'text', 'text': '用中文回答问题'}
        ]}
    ]

在这种情况下，serve仅接受到了
```bash
prompt='<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n<img><IMAGE_TOKEN></img>\nDescribe the image please<|im_end|>\n<|im_start|>assistant\n',
```
