### ISSUE TITLE
InternVL2-8B使用awq量化报错

### ISSUE THREAD

**Issue by wxxcn** [InternLM/lmdeploy#2173]
InternVL2-8B使用awq量化，在保存模型时报错：
<img width="1647" alt="image" src="https://github.com/user-attachments/assets/e334a44a-b761-4d67-b48f-84fabab7b868">

**Comment by AllentDan** [comment]
What is the version of transformers? May use a lower one such as 4.40.0

**Comment by wxxcn** [comment]
it seems the DDP environment cause this problem，while using the single gpu will avoid this problem

**Comment by Mrgengli** [comment]
InternVL2-4B使用awq量化报了错，请问是怎么回事？
![image](https://github.com/user-attachments/assets/67f82419-d0af-4117-aee9-e1a0826e5d0f)

**Comment by lvhan028** [comment]
As @wxxcn said, degrade the transformers's version
