### ISSUE TITLE
关于在vlm模型在awq量化时加入自己的数据的一些问题

### ISSUE THREAD

**Issue by lzcchl** [InternLM/lmdeploy#2174]
您好，我在awq量化vlm模型时，即使打开了search-scale，效果还是不够满意，我看目前默认使用通用数据集ptb进行量化，我想要在量化时加入自己的数据。

那么第一个问题就是，在量化时加入自己的数据集，能否提升效果？

在加入自己的数据并量化之后，发现结果变了更差了，可能是在处理数据时候的问题，我认为我的数据集应该转换成为：提示词tokenizer后的ids+图片VIT后reproject的ids+训练真值tokenizer后的ids（回答）

那么第二个问题是，处理自己的数据的时候，是不是应该处理成 ”提示词+vit结果+真值回答“ 这种模式，或者应该是其他模式？

我在debug的时候发现，我是仿照/lmdeploy/serve/vl_async_engine.py中的 _get_prompt_input 函数得到results，但是results['input_ids']并没有包含图片的内容，而是保存在results['input_embeddings']、results['input_embedding_ranges']，请问后续在哪个位置将这些转成了input_ids呢？这是第三个问题。

**Comment by irexyc** [comment]
> 在加入自己的数据并量化之后，发现结果变了更差了，可能是在处理数据时候的问题，我认为我的数据集应该转换成为：提示词tokenizer后的ids+图片VIT后reproject的ids+训练真值tokenizer后的ids（回答）

embedding 层不量化，所以我觉得数据应该是 文字的 embedding + vit 的 embedding。当然文字的ids和embedding能对应起来。

“图片VIT后reproject的ids” 不太理解这是个什么操作，可以解释一下。

**Comment by lzcchl** [comment]
感谢你们的回复。根据你们的回复，

@AllentDan 谢谢，1，3回复懂了，对于2，这里我用的VIT和 reproject 都是从lmdeploy中拼凑出来的，主要是在lmdeploy/vl/model/xcomposer2.py里面的forward函数（包含vit推理和reproject），至于你问我是否无损，我只能说我的知识点有限，不知道这里什么可能导致损失。

@irexyc 谢谢，这里应该是我理解错了，我以为图片VIT后reproject得到embedding后，后面还有步骤可以从embedding转到ids，其实是没有的对吧，是直接插入到输入input_ids的后面了。

我主要是模仿lmdeploy/lite/utils/calib_dataloader.py里面的get_ptb函数，将我的数据读取并放进get_ptb函数中trainloader。

因为你们都还没提到模型回答怎么加进来，举个例子，比如问“图片中有什么动物？<ImageHere>”，模型回答“老虎”，那么我的量化的时候放进trainloader的是：
 “图片中有什么动物？“的ids + “老虎”的ids +  vit 的 embedding 
还是 
 “图片中有什么动物？“的ids +  vit 的 embedding + “老虎”的ids （和上面就换了一个顺序）

还有一个细节就是，我的提示词，经过vl_prompt_template.messages2prompt (/lmdeploy/serve/vl_async_engine.py)，会有前缀 ”[UNUSED_TOKEN_146]system\nYou are an AI assistant whose name is InternLM-XComposer (浦语·灵笔).\n- InternLM-XComposer (浦语·灵笔) is a .................“，这个会有影响吗，需要去除吗？

**Comment by AllentDan** [comment]
说实话，量化的话就不要每个 prompt 带 system prompt 了，没必要，标定数据集都够用了。你是怎么跑说量化后掉点严重了？量化前后分别多少

**Comment by Skyseaee** [comment]
您好 想问一下后续你们用自己的数据做量化之后会有提升么 @lzcchl
