### ISSUE TITLE
[Bug] 按照文档步骤,在cuda11.4的版本下安装lMdeploy 报错,提示404

### ISSUE THREAD

**Issue by MdcGIt** [InternLM/lmdeploy#2175]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

按照文档步骤,在cuda11.4的版本下安装lMdeploy 报错,提示404

![image](https://github.com/user-attachments/assets/3a75ad99-ea24-4479-ae01-11a467904bf1)

### Reproduction

在cuda11.4的版本下安装lMdeploy 报错,提示404,
![image](https://github.com/user-attachments/assets/66c3c77c-587d-4add-8533-0aae6cd7c8ce)

### Environment

```Shell
没有安装成功,pip安装时提示404
```

**Comment by lvhan028** [comment]
啊，抱歉，我忘记发布 0.5.2 的 cu118 版本了。
你用下 0.5.2.post1吧。
```
export LMDEPLOY_VERSION=0.5.2.post1
```
