### ISSUE TITLE
[Docs] internlm2.5的function call的template的来源

### ISSUE THREAD

**Issue by Lam1360** [InternLM/lmdeploy#2177]
### 📚 The doc issue

internlm2.5的function call的template的来源是哪里？没看到官方有对应的处理逻辑介绍（怎么组装成模型的输入）

**Comment by lvhan028** [comment]
这个是 internlm 团队直接给 lmdeploy 提 PR 实现的。
我看看是不是能请 internlm 团队在model card上做说明
