### ISSUE TITLE
Question regarding the prefix caching

### ISSUE THREAD

**Issue by laserwave** [InternLM/lmdeploy#2181]
### 📚 The doc issue

> Interactive Inference Mode: By caching the k/v of attention during multi-round dialogue processes, the engine remembers dialogue history, thus avoiding repetitive processing of historical sessions.

在文档中提及了对于多轮对话使用了kv cache进行加速，请问适用范围是怎样的：
1. 必须使用某种调用方式，例如启动server吗，使用了pipeline调用发现enable_prefix_caching设置为True和False时prefill时间一致，没有显著提升（相同输入以及输出token）
3. 只对LLM有效吗？对VLM是否有效。对对话模板做了调整，将image token放到prompt的最后，prefill仍然没有加快。
3. 文档里提到中间会使用例如token id这样的compact表示，那么对于image token是怎么做的，多轮里的相同的image token是否直接调用了kv cache

测试的模型用的是InternVL2-AWQ模型

**Comment by RunningLeon** [comment]
hi, `--enable-prefix-caching`只支持在pytorch backend＋ llm上，vlm不支持。pipeline和server都是支持的。

**Comment by lvhan028** [comment]
文档表达的是，交互式对话模式。多轮对话是交互式对话很好的一个展示
对于一个序列, U1A1U2A2U3A3...U_k而言（U_i表示用户的问题，A_i表示模型的响应），交互式（或者说有状态的推理）的推理是，每次，用户只要发送当前轮次的请求 U_i 即可，不需要把 U_i 之前的历史记录带上。因为之前历史信息的 kv cache 都已经存好了。意味着不用重复计算 kv cache。但它也有些弊端，这里暂略去不提。

目前，从openai接口，以及绝大部分推理引擎，支持的都是无状态的推理，也就是说第i轮对话，用户侧需要发送U1A1U2A2U3A3...U_i。为了提高效率，prefix caching的方法被提出。目的也是尽量不要计算历史的kv cache了。

关于上述的 3 个问题：
1. pipeline，server都能打开 enable_prefix_caching 开关。有社区同学测试 system prompt 长的场景，能提高 20% 左右。可以看看 vLLM 的评测脚本：https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_prefix_caching.py
2. 目前只有 LLM 有效
3.  没有调用 kv cache这种事情。对于 InternVL 模型来说，我们是把 image embeddings 根据 image token的位置，拼接到 token_embeddings中的。
