### ISSUE TITLE
[Feature] Fine tuning of quantized 4bit internlm/internlm-xcomposer2-4khd-7b?

### ISSUE THREAD

**Issue by zhuraromdev** [InternLM/lmdeploy#2184]
### Motivation

Hello,

I have successful made quantization of `internlm/internlm-xcomposer2-4khd-7b` model to 4bit. Additionally I am able to call inference to interact with model. However the next step, which I would like to do, is to fine tune the model. 

I would like to ask the question, do you have a tool for fine tuning of quantized model by lmdeploy?
I was trying to use [InternLM-XComposer](https://github.com/InternLM/InternLM-XComposer) for 2.0 model for fine tuning, however have got the issue, which I am still thinking how to fix: `ValueError: The model you want to train is loaded in 8-bit precision.  if you want to fine-tune an 8-bit model, please make sure that you have installed bitsandbytes>=0.37.0`.

Thank you in advance for the answer!

**Comment by lvhan028** [comment]
lmdeploy is an inference framework about LLMs and VLMs
Regarding the fine tuning, I recommend [xtuner](https://github.com/InternLM/xtuner)

**Comment by lvhan028** [comment]
I am not an expert at fine tuning. 
But according to the error log, it suggests `pip install bitsandbytes`

**Comment by lvhan028** [comment]
> lmdeploy is an inference framework about LLMs and VLMs Regarding the fine tuning, I recommend [xtuner](https://github.com/InternLM/xtuner)

Sorry, after checking with the xtuner team, it hasn't supported xcomposer2 fine tuning yet.
