### ISSUE TITLE
[Feature] Can lmdeploy quant InternVL2 to AWQ? 

### ISSUE THREAD

**Issue by janelu9** [InternLM/lmdeploy#2185]
### Motivation

How to deploy a finetuned InternVL2 of AWQ?

**Comment by lvhan028** [comment]
Yes. 
All the **_AWQ models in https://huggingface.co/collections/OpenGVLab/internvl-20-667d3961ab5eb12c7ed1463e are quantized by LMDeploy

**Comment by janelu9** [comment]
> Yes. All the **_AWQ models in https://huggingface.co/collections/OpenGVLab/internvl-20-667d3961ab5eb12c7ed1463e are quantized by LMDeploy

quant failed!
 shard = {tensor: state_dict[tensor] for tensor in tensors}
NameError: cannot access free variable 'state_dict' where it is not associated with a value in enclosing scope

**Comment by lvhan028** [comment]
Pls provide the reproducible code
