### ISSUE TITLE
[Bug] qwen2-7b-instruct使用awq量化之后，前后输出不一致

### ISSUE THREAD

**Issue by JiaXinLI98** [InternLM/lmdeploy#2186]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

使用awq量化，量化前后输出不一致，而且int4-版本对同一个问题多次推理会出现不同的答案

### Reproduction

qwen2-7b-instruct，经过full-sft

### Environment

```Shell
TorchVision: 0.16.2+cu118
LMDeploy: 0.5.0+
transformers: 4.42.0
gradio: 4.37.2
fastapi: 0.111.0
pydantic: 2.8.2
triton: 2.1.0
```

**Comment by lvhan028** [comment]
请提供下最小复现的代码吧

**Comment by lvhan028** [comment]
量化前后输出不一致是肯定的，这不是bug。因为权重已经量化了，而且推理的 kernel 又不一样。
你可以用transformers + autoawq 试试看。

关于说的同一个问题多次推理有不同的答案，还请提供最小复现代码

**Comment by JiaXinLI98** [comment]
> 请提供下最小复现的代码吧

量化代码：
`from awq import AutoAWQForCausalLM
from transformers import AutoTokenizer
import sys
from datasets import load_dataset
import json

model_path = sys.argv[1]
quant_path = sys.argv[2]
data_path = sys.argv[3]
quant_config = { "zero_point": True, "q_group_size": 128, "w_bit": 4, "version": "GEMM" }

model = AutoAWQForCausalLM.from_pretrained(model_path, safetensors=True)
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)

data = []
with open(data_path + "/train.json", 'r', encoding='utf-8') as f:
    for line in f.readlines():
        text = tokenizer.apply_chat_template(json.loads(line), tokenize=False, add_generation_prompt=False)
        data.append(text.strip())

model.quantize(tokenizer, quant_config=quant_config, calib_data=data)

model.save_quantized(quant_path)
tokenizer.save_pretrained(quant_path)`

推理代码：
pipe = pipeline("/root/paddlejob/workspace/env_run/model/qwen2_7b_stage2_4bit_2", model_format='awq', top_p=0.75, top_k=20)
response = pipe(prompts, request_output_len=2048)

**Comment by lvhan028** [comment]
`top_p=0.75` and `top_k=20` 表示你开了random sampling。生成token的时候，会根据参数随机采样的。自然结果有不同

**Comment by JiaXinLI98** [comment]
> 量化前后输出不一致是肯定的，这不是bug。因为权重已经量化了，而且推理的 kernel 又不一样。 你可以用transformers + autoawq 试试看。
> 
> 关于说的同一个问题多次推理有不同的答案，还请提供最小复现代码

原模型是经过微调的，输出是带有固定格式的输出，但是，量化之后的模型失去了微调的特性，其输出已经与原本的开源4bit模型对比，二者输出相似，量化模型在多次输出的结果也是完全不一致，没有微调赋予的特定格式

**Comment by lvhan028** [comment]
如果不能提供最小复现代码，我们也无能为力
