### ISSUE TITLE
lmdeploy对于多模态的推理加速的支持让人着迷😊，ms-swift接入了lmdeploy作为infer和deploy的后端

### ISSUE THREAD

**Issue by Jintao-Huang** [InternLM/lmdeploy#2189]
lmdeploy对于多模态的推理加速的支持让人着迷，ms-swift接入了lmdeploy作为infer和deploy的后端，并作为多模态推理和部署的默认后端。

ms-swift是大模型训练框架，支持300+大语言模型和50+多模态大模型的微调，感兴趣的小伙伴欢迎来玩～

下面是LMDeploy推理加速和部署的文档，感兴趣可以查看😊：

VLM & LMDeploy: https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/LmDeploy%E6%8E%A8%E7%90%86%E5%8A%A0%E9%80%9F%E6%96%87%E6%A1%A3.md#%E9%83%A8%E7%BD%B2

LLM & LMDeploy: https://github.com/modelscope/swift/blob/main/docs/source/LLM/LmDeploy%E6%8E%A8%E7%90%86%E5%8A%A0%E9%80%9F%E4%B8%8E%E9%83%A8%E7%BD%B2.md#%E9%83%A8%E7%BD%B2

**Comment by zhyncs** [comment]
We are delighted that on VLM, LMDeploy is being made the default inference engine for ModelScope Swift. Would it be possible to mention this in the README to help more people learn about and use LMDeploy? Thanks!

**Comment by Jintao-Huang** [comment]
哈哈，我们增加了lmdeploy github的链接在文档中😊

**Comment by lvhan028** [comment]
感谢😊，我们也更新下news
