### ISSUE TITLE
enable_prefix_caching参数无效[Bug] 

### ISSUE THREAD

**Issue by LugerW-A** [InternLM/lmdeploy#2196]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

enable_prefix_caching能够缓存prompt提升速度，但是我实测没有作用。
无论设置为true或者false,时间没有区别

### Reproduction

import time
from lmdeploy import pipeline, TurbomindEngineConfig

pipe = pipeline('./models/InternVL2-8B', backend_config=TurbomindEngineConfig(enable_prefix_caching=True))

loop_number = 20
start_time = time.time() 
for i in range(loop_number):
    response = pipe('who are you?')
end_time = time.time()
print("单次推理耗费掉时间: ", (end_time - start_time) / loop_number)
print(f'nAssistant: {response.text}')

### Environment

```Shell
sys.platform: linux
Python: 3.9.19 (main, May  6 2024, 19:43:03) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA A800-SXM4-80GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.1, V12.1.105
GCC: gcc (Debian 10.2.1-6) 10.2.1 20210110
PyTorch: 2.2.2+cu121
TorchVision: 0.17.2+cu121
LMDeploy: 0.5.2.post1+
transformers: 4.37.2
gradio: Not Found
fastapi: 0.111.1
pydantic: 2.8.2
triton: 2.2.0
```

**Comment by lvhan028** [comment]
Please refer to theprefix caching benchmark script:

https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_prefix_caching.py
