### ISSUE TITLE
[Bug] 基于turbomind框架下的GLM-4V KVCache（Int4\Int8）无效

### ISSUE THREAD

**Issue by Jalen-Zhong** [InternLM/lmdeploy#2199]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

基于turbomind框架下的GLM-4V KVCache（Int4\Int8）无效

### Reproduction

1、cmd命令如下：
`lmdeploy serve api_server ZhipuAI/glm-4v-9b --backend turbomind --server-port 7861 --log-level INFO --quant-policy 4`

2、问题：
GLM-4v提供Int4的量化，参考：https://github.com/THUDM/GLM-4/blob/main/basic_demo/README.md。但基于turbomind框架下的GLM-4V KVCache（Int4\Int8）无效，仍然会爆炸。

### Environment

```Shell
LMDeploy==0.5.13
python==3.9
nvidia 3090 24G
```

### Error traceback

```Shell
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 32.00 MiB. GPU 0 has a total capacity of 23.68 GiB of which 14.81 MiB is free. Process 12513 has 1.39 GiB memory in use. Process 13074 has 1.39 GiB memory in use. Including non-PyTorch memory, this process has 20.87 GiB memory in use. Of the allocated memory 20.15 GiB is allocated by PyTorch, and 448.11 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

**Comment by ElhamAhmedian** [comment]
Any news on this?

**Comment by lvhan028** [comment]
turbomind engine doesn't support glm 4v

**Comment by xiangqi1997** [comment]
how  about 4bit quantize of GLM4V?

**Comment by Jalen-Zhong** [comment]
> turbomind engine doesn't support glm 4v

GLM-4v support int4，but turbomind and pytorch of lmdeploy does not support it

**Comment by lvhan028** [comment]
Turbomind engine doesn't support glm 4v. That's a fact. We mentioned it in the [supported matrix](https://lmdeploy.readthedocs.io/en/latest/supported_models/supported_models.html#models-supported-by-turbomind)

Pytorch engine supports glm 4v in HALF data type. It doesn't support the KV quantization. That's also a fact. 

Regarding glm-4v int4, no matter the weight or the KV, it is not in our top priority now.  Please try its official repo.
We are sorry for the inconvinient.
