### ISSUE TITLE
[Bug] GLM-4v不支持turbomind推理引擎

### ISSUE THREAD

**Issue by Jalen-Zhong** [InternLM/lmdeploy#2208]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

使用lmdeploy serve api_server部署glm-4v-9b模型时，提示不支持turbomind引擎。这与[Supported Models](https://lmdeploy.readthedocs.io/en/latest/supported_models/supported_models.html)中描述不一致。

### Reproduction

`lmdeploy serve api_server /root/.cache/modelscope/hub/ZhipuAI/glm-4v-9b --model-name GLM-4 --backend turbomind --server-port 7861 --tp 2 --quant-policy 4`

### Environment

```Shell
lmdeplot==0.5.2.post1
python==3.9
ubuntu==18.04
```

### Error traceback

```Shell
2024-08-01 11:43:14,814 - lmdeploy - WARNING - Fallback to pytorch engine because `/root/.cache/modelscope/hub/ZhipuAI/glm-4v-9b` not supported by turbomind engine.
HINT:    Please open http://0.0.0.0:7861 in a browser for detailed api usage!!!
HINT:    Please open http://0.0.0.0:7861 in a browser for detailed api usage!!!
HINT:    Please open http://0.0.0.0:7861 in a browser for detailed api usage!!!
INFO:     Started server process [10005]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:7861 (Press CTRL+C to quit)
```

**Comment by lvhan028** [comment]
Yes. Turbomind doesn't support it. 
The supported models by turbomind has been listed here: https://lmdeploy.readthedocs.io/en/latest/supported_models/supported_models.html#models-supported-by-turbomind

This is not a bug.

**Comment by lvhan028** [comment]
The `GLM4` in supported model means glm-4-9b-chat
We'll clarify it in the doc
