### ISSUE TITLE
[Bug] 量化glm4-9b-chat模型报错

### ISSUE THREAD

**Issue by MdcGIt** [InternLM/lmdeploy#2210]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

![image](https://github.com/user-attachments/assets/5fc462b4-ac7a-4861-96f5-d06b39d9172d)
量化glm4-9b-chat模型报错,量化命令如下:  
 export HF_MODEL=/sdd/model/lmdeploy/model/glm-4-9b-chat
 export HF_MODEL=/sdd/model/lmdeploy/model/glm-4-9b-chat
 export trust_remote_code=True
export HF_ENDPOINT=https://hf-mirror.com 
lmdeploy lite auto_awq    $HF_MODEL   --calib-dataset 'ptb'   --calib-samples 128   --calib-seqlen 2048   --w-bits 4   --w-group-size 128   --batch-size 1   --search-scale False   --work-dir $WORK_DIR

### Reproduction

![image](https://github.com/user-attachments/assets/5fc462b4-ac7a-4861-96f5-d06b39d9172d)
量化glm4-9b-chat模型报错,量化命令如下:  
 export HF_MODEL=/sdd/model/lmdeploy/model/glm-4-9b-chat
 export HF_MODEL=/sdd/model/lmdeploy/model/glm-4-9b-chat
 export trust_remote_code=True
export HF_ENDPOINT=https://hf-mirror.com 
lmdeploy lite auto_awq    $HF_MODEL   --calib-dataset 'ptb'   --calib-samples 128   --calib-seqlen 2048   --w-bits 4   --w-group-size 128   --batch-size 1   --search-scale False   --work-dir $WORK_DIR

### Environment

```Shell
(lmdeploy) [root@localhost ~]# lmdeploy check_env
/data/conda/anaconda3/envs/lmdeploy/lib/python3.8/site-packages/transformers/utils/hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
sys.platform: linux
Python: 3.8.19 | packaged by conda-forge | (default, Mar 20 2024, 12:47:35) [GCC 12.3.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3060
GPU 1: Tesla T4
CUDA_HOME: /usr/local/cuda-12.2
NVCC: Cuda compilation tools, release 12.2, V12.2.128
GCC: gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
PyTorch: 2.2.2+cu118
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

TorchVision: 0.17.2+cu118
LMDeploy: 0.5.2+
transformers: 4.43.3
gradio: Not Found
fastapi: 0.111.1
pydantic: 2.8.2
triton: 2.2.0
NVIDIA Topology: 
        GPU0    GPU1    CPU Affinity    NUMA Affinity
GPU0     X      SYS     0-11,24-35      0
GPU1    SYS      X      12-23,36-47     1

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

**Comment by AllentDan** [comment]
Please set `--search-scale False`

**Comment by MdcGIt** [comment]
![image](https://github.com/user-attachments/assets/d6ce7a0a-8052-4c6e-ade2-7924264f6281)
我一张T4 一张RTX3060ti 共28G显存,不够量化么,为啥提示显存不足呀  看错误提示并没有用到我的GPU1 进行量化,好像只有GPU0 参与1  然后显存溢出了

**Comment by AllentDan** [comment]
量化不支持多卡，设计的时候是逐层，内部按 batch_size 1 跑的，理论上再大的模型，一块卡都够了。

**Comment by AllentDan** [comment]
可以试试标定用 `--calib-seqlen 512`

**Comment by MdcGIt** [comment]
好像可以了  这个参数是做什么的呢

**Comment by MdcGIt** [comment]
虽然量化了  但我还是跑不起来  28G显存跑9B量化理论上应该没问题的吧 
![image](https://github.com/user-attachments/assets/63c6badf-b648-4c27-bbd1-0e6bb28910a6)
![image](https://github.com/user-attachments/assets/fbd31ee9-9a38-4630-aacf-5d14b668c10e)

**Comment by AllentDan** [comment]
加一个 `--cache-max-entry-count=0.3` 试试

**Comment by MdcGIt** [comment]
![image](https://github.com/user-attachments/assets/bc66a2b6-fb08-472f-bb02-6c1d6eaf96fa)
加了参数是可以跑起来了,但是我的GPU 0确并没有参与进来，只有gpu1 进行推理，俩个显卡分别为T4和3060ti，这是为什么呢

**Comment by MdcGIt** [comment]
如果加了--tp=2 参数 那么启动就会报以下错误:
![image](https://github.com/user-attachments/assets/f8253014-ddf4-4ebf-b82a-edfa15699d97)

**Comment by AllentDan** [comment]
目前的版本 shape 不能被均分到两块卡上，跑不了。

**Comment by MdcGIt** [comment]
也就是我只能单卡运行了么

**Comment by AllentDan** [comment]
对，单卡。要想提高吞吐量，可以启两个服务，做一下负载均衡。https://lmdeploy.readthedocs.io/en/latest/serving/proxy_server.html

**Comment by MdcGIt** [comment]
那单卡的话 我怎么指定哪个卡运行呢 ？

**Comment by AllentDan** [comment]
'CUDA_VISIBLE_DEVICES' 环境变量

**Comment by MdcGIt** [comment]
好的 那如果只允许单卡的话 那我想跑更大的模型怎么办,比如72b的 ,也没有这么大显存的单卡呀。。。

**Comment by AllentDan** [comment]
大部分模型可以被 tp 整除，只是这个模型 shape 不行。

**Comment by MdcGIt** [comment]
哦哦 好的
