### ISSUE TITLE
[Feature] 如何能让大模型的输出更加随机呢

### ISSUE THREAD

**Issue by xinge666** [InternLM/lmdeploy#2211]
### Motivation

同样的prompt 配置 temperature=0.9,top_p=0.8,top_k=100 ，输出的结果基本一致，没有随机性

代码如下：
backend_config = TurbomindEngineConfig(tp=1
                                       #,model_format='awq'
                                       ,cache_max_entry_count=0.01)
pipe = pipeline('/data0/models/qwen2/Qwen2-7B-Instruct',backend_config=backend_config)
prompts = []
for i in range(10):
    prompts.append([{"role": "system","content": "I am a helpful assistant." },{"role": "user", "content": '给我讲个100字的故事'}])
gen_config = GenerationConfig(max_new_tokens=50 ,temperature=0.9,top_p=0.8,top_k=100)
response = pipe(prompts,gen_config=gen_config)
for res in response:
    print(res.text)
print('*'*100)
![image](https://github.com/user-attachments/assets/60d25501-ec31-4b5d-b8fe-a55005419e10)

对比 VLLM  同样的temperature=0.9,top_p=0.8,top_k=100  输出结果随机性较大
![image](https://github.com/user-attachments/assets/253720c3-e62c-4d27-baca-c1fb1bed7747)

因为需要使用大模型做多次推理投票，没有随机性后，投票效果较差，如何才能让大模型的输出更加随机呢？

已经查看过 issue
https://github.com/InternLM/lmdeploy/issues/1604
https://github.com/InternLM/lmdeploy/issues/975

**Comment by irexyc** [comment]
可以尝试一下，temperature 设置的大一点，top_k=0(关闭topk), top_p=1.0 (全部token作为候选)

**Comment by xinge666** [comment]
> 可以尝试一下，temperature 设置的大一点，top_k=0(关闭topk), top_p=1.0 (全部token作为候选)

没有效果 
gen_config = GenerationConfig(max_new_tokens=50 ,temperature=0.95,top_p=1,top_k=0)


![image](https://github.com/user-attachments/assets/399f4d96-91a6-4d75-af92-83938bfb64e1)

**Comment by irexyc** [comment]
我看了一下，问题应该在于如果传入了gen_cnofig的话，那么对于每个请求，会初始化一个随机种子。对于多个prompts，如果只传了一个gen_config的话，那么这一批prompts会共用这个seed，造成结果基本上是一样的。

你可以按照下面这样试一下。另外 gen_config 最好每一轮都会重新初始化一下，不然他的种子会固定，你可以看一下，调用前后的gen_config.random_seed 变化。
```
prompts = []
for i in range(10):
    prompts.append([{"role": "system","content": "I am a helpful assistant." },{"role": "user", "content": '给我讲个100字的故事'}])

gen_config = GenerationConfig(max_new_tokens=50 ,temperature=0.9,top_p=0.8,top_k=100)
gen_configs = [gen_config] * len(prompts)
response = pipe(prompts,gen_config=gen_configs)
for res in response:
    print(res.text)
```

**Comment by xinge666** [comment]
> 我看了一下，问题应该在于如果传入了gen_cnofig的话，那么对于每个请求，会初始化一个随机种子。对于多个prompts，如果只传了一个gen_config的话，那么这一批prompts会共用这个seed，造成结果基本上是一样的。
> 
> 你可以按照下面这样试一下。另外 gen_config 最好每一轮都会重新初始化一下，不然他的种子会固定，你可以看一下，调用前后的gen_config.random_seed 变化。
> 
> ```
> prompts = []
> for i in range(10):
>     prompts.append([{"role": "system","content": "I am a helpful assistant." },{"role": "user", "content": '给我讲个100字的故事'}])
> 
> gen_config = GenerationConfig(max_new_tokens=50 ,temperature=0.9,top_p=0.8,top_k=100)
> gen_configs = [gen_config] * len(prompts)
> response = pipe(prompts,gen_config=gen_configs)
> for res in response:
>     print(res.text)
> ```

已解决 谢谢大佬
