### ISSUE TITLE
internlm2-chat-20b量化为4bit后，模型文件从原来的38.7G减小到11.5G，但是部署后的显存占用从原来的78.3G降低到68.3G，只降低了10G，正常吗？

### ISSUE THREAD

**Issue by sxk000** [InternLM/lmdeploy#2217]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

首先，感谢上海人工智能实验室及其成员对书生模型、代码框架、技术经验的分享！

internlm2-chat-20b量化为4bit后，模型文件从原来的38.7G减小到11.5G，但是部署后的显存占用从原来的78.3G降低到68.3G，只降低了10G，正常吗？部署模型时，如何进一步降低显存占用呢？

谢谢！

### Reproduction

internlm2-chat-20b量化为4bit后，模型文件从原来的38.7G减小到11.5G，但是部署后的显存占用从原来的78.3G降低到68.3G，只降低了10G，正常吗？部署模型时，如何进一步降低显存占用呢？

量化运行命令：lmdeploy lite auto_awq internlm2-chat-20b --work-dir internlm2-chat-20b-4bit

部署模型命令：
CUDA_VISIBLE_DEVICES=0 python api_server.py --server-port 23343 --model_path internlm2-chat-20b-4bit --model-name internlm2-chat-20b --backend turbomind --model-format awq

### Environment

```Shell
环境：
cuda12.2
python3.12
lmdeploy0.5.1
```

**Comment by RunningLeon** [comment]
@sxk000 hi, 可以试试降低kv cache  `--cache-max-entry-count`  https://lmdeploy.readthedocs.io/en/latest/serving/api_server.html#option-1-launching-with-lmdeploy-cli

**Comment by janelu9** [comment]
支持的并发量和上下文长度肯定不一样喽

**Comment by sxk000** [comment]
> @sxk000 hi, 可以试试降低预分配的kv cache比例 `--cache-max-entry-count` https://lmdeploy.readthedocs.io/en/latest/serving/api_server.html#option-1-launching-with-lmdeploy-cli

这个方法是可行的，我设置以后显存占用可以降到20G，谢谢！
