### ISSUE TITLE
[Bug] RuntimeError: [TM][ERROR]  Assertion fail: D:\a\lmdeploy\lmdeploy\src\turbomind\python\bind.cpp:294 

### ISSUE THREAD

**Issue by NB-Group** [InternLM/lmdeploy#2219]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

在加载[Qwen1.5-32B-Chat-AWQ-G32](https://www.modelscope.cn/models/tclf90/Qwen1.5-32B-Chat-AWQ-G32) *非官方* 量化修复版时报错：
`RuntimeError: [TM][ERROR]  Assertion fail: D:\a\lmdeploy\lmdeploy\src\turbomind\python\bind.cpp:294 `

### Reproduction

```python
from lmdeploy import pipeline, GenerationConfig, TurbomindEngineConfig

backend_config = TurbomindEngineConfig(tp=1, model_format="awq")
gen_config = GenerationConfig(top_p=0.8,
                              top_k=40,
                              temperature=0.8,
                              max_new_tokens=1024)
pipe = pipeline("D:\AI_model\Qwen1.5-32B-Chat-AWQ-G32", backend_config=backend_config, log_level='INFO')
```

### Environment

```Shell
sys.platform: win32
Python: 3.8.16 (default, Mar  2 2023, 03:18:16) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3090
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4
NVCC: Cuda compilation tools, release 12.4, V12.4.131
MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.35.32217.1 版
GCC: n/a
PyTorch: 2.2.2+cu121
PyTorch compiling details: PyTorch built with:
  - C++ Version: 201703
  - MSVC 192930151
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.8.1  (built against CUDA 12.0)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.8.1, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /Zc:__cplusplus /bigobj /FS /utf-8 -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE /wd4624 /wd4068 /wd4067 /wd4267 /wd4661 /wd4717 /wd4244 /wd4804 /wd4273, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF,

TorchVision: 0.17.2+cpu
LMDeploy: 0.5.2.post1+
transformers: 4.42.4
gradio: 3.41.0
fastapi: 0.111.0
pydantic: 2.8.2
triton: Not Found
```

### Error traceback

```Shell
Add dll path C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin, please note cuda version should >= 11.3 when compiled with cuda 11
2024-08-02 14:28:59,833 - lmdeploy - INFO - Using turbomind engine
2024-08-02 14:28:59,833 - lmdeploy - INFO - input backend=turbomind, backend_config=TurbomindEngineConfig(model_name=None, model_format='awq', tp=1, session_len=None, max_batch_size=128, cache_max_entry_count=0.8, cache_block_seq_len=64, enable_prefix_caching=False, quant_policy=0, rope_scaling_factor=0.0, use_logn_attn=False, download_dir=None, revision=None, max_prefill_token_num=8192, num_tokens_per_iter=0, max_prefill_iters=1)
2024-08-02 14:28:59,833 - lmdeploy - INFO - input chat_template_config=None
2024-08-02 14:28:59,932 - lmdeploy - INFO - updated chat_template_onfig=ChatTemplateConfig(model_name='qwen', system=None, meta_instruction=None, eosys=None, user=None, eoh=None, assistant=None, eoa=None, separator=None, capability=None, stop_words=None)
2024-08-02 14:28:59,933 - lmdeploy - INFO - model_source: hf_model
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
2024-08-02 14:29:00,813 - lmdeploy - INFO - model_config:

[llama]
model_name = qwen
model_arch = Qwen2ForCausalLM
tensor_para_size = 1
head_num = 40
kv_head_num = 8
vocab_size = 152064
num_layer = 64
inter_size = 27392
norm_eps = 1e-06
attn_bias = 1
start_id = 151643
end_id = 151645
session_len = 32776
weight_type = int4
rotary_embedding = 128
rope_theta = 1000000.0
size_per_head = 128
group_size = 128
max_batch_size = 128
max_context_token_num = 1
step_length = 1
cache_max_entry_count = 0.8
cache_block_seq_len = 64
cache_chunk_size = -1
enable_prefix_caching = False
num_tokens_per_iter = 8192
max_prefill_iters = 5
extra_tokens_per_iter = 0
use_context_fmha = 1
quant_policy = 0
max_position_embeddings = 32768
original_max_position_embeddings = 0
rope_scaling_type = 
rope_scaling_factor = 0.0
use_dynamic_ntk = 0
low_freq_factor = 1.0
high_freq_factor = 1.0
use_logn_attn = 0
lora_policy = 
lora_r = 0
lora_scale = 0.0
lora_max_wo_r = 0
lora_rank_pattern = 
lora_scale_pattern = 


[TM][WARNING] [LlamaTritonModel] `max_context_token_num` = 32776.
[TM][INFO] Barrier(1)
Convert to turbomind format:   0%|          | 0/64 [00:00<?, ?it/s]2024-08-02 14:29:02,157 - lmdeploy - WARNING - get 771 model params
Traceback (most recent call last):
  File "E:\Code\Python\MOSS_Ultra\test.py", line 12, in <module>
    pipe = pipeline("D:\AI_model\Qwen1.5-32B-Chat-AWQ-G32", backend_config=backend_config, log_level='INFO')
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\api.py", line 89, in pipeline
    return pipeline_class(model_path,
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\serve\async_engine.py", line 190, in __init__
    self._build_turbomind(model_path=model_path,
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\serve\async_engine.py", line 235, in _build_turbomind
    self.engine = tm.TurboMind.from_pretrained(
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\turbomind\turbomind.py", line 340, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\turbomind\turbomind.py", line 144, in __init__
    self.model_comm = self._from_hf(model_source=model_source,
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\turbomind\turbomind.py", line 257, in _from_hf
    output_model.export()
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\turbomind\deploy\target_model\base.py", line 289, in export
    self.export_transformer_block(bin, i)
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\turbomind\deploy\target_model\w4.py", line 128, in export_transformer_block
    self.save_split(qkv_sz, f'layers.{i}.attention.w_qkv.scales_zeros', -1)
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\turbomind\deploy\target_model\base.py", line 267, in save_split
    self.export_weight(split, f'{prefix}.{i}{ext}')
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\turbomind\deploy\target_model\base.py", line 245, in export_weight
    tm_tensor.copy_from(torch_tensor)
RuntimeError: [TM][ERROR]  Assertion fail: D:\a\lmdeploy\lmdeploy\src\turbomind\python\bind.cpp:294
```

**Comment by irexyc** [comment]
目前只支持 128 的 group size，这个量化模型是 group size 是32

**Comment by NB-Group** [comment]
哦，好的，谢谢回复。
[这个仓库](https://www.modelscope.cn/models/tclf90/Qwen1.5-32B-Chat-AWQ-G32)提供的模型里还带有GPTQ-int3量化的版本，它受不受支持呢？

**Comment by irexyc** [comment]
不支持，目前只支持awq w4a16的量化。

**Comment by NB-Group** [comment]
魔搭和huggingface上貌似都没有符合要求的模型。哪如果我在本地进行量化，如何避免出现类似官方模型的量化损失，和无限感叹号等问题？

**Comment by lvhan028** [comment]
PR #2090 会支持 GPTQ

**Comment by NB-Group** [comment]
☺️

**Comment by maxin9966** [comment]
@lvhan028 
最新版0.6.0，groupsize是128，还是报错

模型地址：
https://www.modelscope.cn/models/tclf90/Qwen1.5-32B-Chat-GPTQ-Int3

**Comment by maxin9966** [comment]
## error:
Sep 14 13:24:25 ubuntu22lts systemd[1]: Started Uvicorn server for my app.
Sep 14 13:24:32 ubuntu22lts bash[76171]: [102B blob data]
Sep 14 13:24:32 ubuntu22lts bash[76171]:   File "/home/ma/miniconda3/envs/lmdeploy/bin/lmdeploy", line 8, in <module>
Sep 14 13:24:32 ubuntu22lts bash[76171]:     sys.exit(run())
Sep 14 13:24:32 ubuntu22lts bash[76171]:   File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.9/site-packages/lmdeploy/cli/entrypoint.py", line 36, in run
Sep 14 13:24:32 ubuntu22lts bash[76171]:     args.run(args)
Sep 14 13:24:32 ubuntu22lts bash[76171]:   File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.9/site-packages/lmdeploy/cli/serve.py", line 287, in api_server
Sep 14 13:24:32 ubuntu22lts bash[76171]:     run_api_server(args.model_path,
Sep 14 13:24:32 ubuntu22lts bash[76171]:   File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.9/site-packages/lmdeploy/serve/openai/api_server.py", line 1007, in serve
Sep 14 13:24:32 ubuntu22lts bash[76171]:     VariableInterface.async_engine = pipeline_class(
Sep 14 13:24:32 ubuntu22lts bash[76171]:   File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.9/site-packages/lmdeploy/serve/async_engine.py", line 154, in __init__
Sep 14 13:24:32 ubuntu22lts bash[76171]:     self._build_turbomind(model_path=model_path,
Sep 14 13:24:32 ubuntu22lts bash[76171]:   File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.9/site-packages/lmdeploy/serve/async_engine.py", line 192, in _build_turbomind
Sep 14 13:24:32 ubuntu22lts bash[76171]:     self.engine = tm.TurboMind.from_pretrained(
Sep 14 13:24:32 ubuntu22lts bash[76171]:   File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.9/site-packages/lmdeploy/turbomind/turbomind.py", line 300, in from_pretrained
Sep 14 13:24:32 ubuntu22lts bash[76171]:     return cls(model_path=pretrained_model_name_or_path,
Sep 14 13:24:32 ubuntu22lts bash[76171]:   File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.9/site-packages/lmdeploy/turbomind/turbomind.py", line 110, in __init__
Sep 14 13:24:32 ubuntu22lts bash[76171]:     self.model_comm = self._from_hf(model_source=model_source,
Sep 14 13:24:32 ubuntu22lts bash[76171]:   File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.9/site-packages/lmdeploy/turbomind/turbomind.py", line 230, in _from_hf
Sep 14 13:24:32 ubuntu22lts bash[76171]:     tm_model.export()
Sep 14 13:24:32 ubuntu22lts bash[76171]:   File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.9/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 205, in export
Sep 14 13:24:32 ubuntu22lts bash[76171]:     self.export_transformer_block(bin, i)
Sep 14 13:24:32 ubuntu22lts bash[76171]:   File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.9/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 244, in export_transformer_block
Sep 14 13:24:32 ubuntu22lts bash[76171]:     e.export(bin, i)
Sep 14 13:24:32 ubuntu22lts bash[76171]:   File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.9/site-packages/lmdeploy/turbomind/deploy/exporter.py", line 166, in export
Sep 14 13:24:32 ubuntu22lts bash[76171]:     self.export_attn(i, r.attn(i), 'qweight', self.pack_fn)
Sep 14 13:24:32 ubuntu22lts bash[76171]:   File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.9/site-packages/lmdeploy/turbomind/deploy/exporter.py", line 94, in export_attn
Sep 14 13:24:32 ubuntu22lts bash[76171]:     self.model.save_split(qkv,
Sep 14 13:24:32 ubuntu22lts bash[76171]:   File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.9/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 183, in save_split
Sep 14 13:24:32 ubuntu22lts bash[76171]:     self.export_weight(split, f'{prefix}.{i}{ext}')
Sep 14 13:24:32 ubuntu22lts bash[76171]:   File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.9/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 147, in export_weight
Sep 14 13:24:32 ubuntu22lts bash[76171]:     tm_tensor.copy_from(torch_tensor)
Sep 14 13:24:32 ubuntu22lts bash[76171]: RuntimeError: [TM][ERROR]  Assertion fail: /lmdeploy/src/turbomind/python/bind.cpp:295
Sep 14 13:24:33 ubuntu22lts bash[76171]: [68B blob data]
Sep 14 13:24:33 ubuntu22lts systemd[1]: lm-qwen-32b.service: Main process exited, code=exited, status=1/FAILURE

**Comment by lvhan028** [comment]
That's INT3, which is not supported by LMDeploy

**Comment by ColorfulDick** [comment]
> PR #2090 会支持 GPTQ

在4*4090的服务器上使用lmdeloy最新的main分支，也就是v0.6.1这个版本，执行启动命令
```shell
lmdeploy serve api_server Qwen/Qwen2.5-72B-Instruct-GPTQ-Int8  --server-name 0.0.0.0 --server-port 23333  --tp 4  --cache-max-entry-count 0.5
```
也报了同样的错误，似乎仍不支持GPTQ

**Comment by lvhan028** [comment]
LMDeploy doesn't support GPTQ-Int8
It supports AWQ(group_size=128) and GPTQ-Int4 (group_size=128, no desc_act)
