### ISSUE TITLE
[Feature] 如何实现多用户并发推理？

### ISSUE THREAD

**Issue by RyanOvO** [InternLM/lmdeploy#2224]
### Motivation

model: internlm2.5 chat
基于lmdeploy部署，通过cuda指定两个卡启动，但好像只有一个卡加载了模型，有如下三个问题：
1. 不能通过CUDA_VISIBLE_DEVICES=0,1 这样指定两个卡嘛？
2. 如何实现多用户同时调用API接口？
3. 如何实现单用户batch调用接口？

感谢回复。

### Related resources

None

### Additional context

None

**Comment by irexyc** [comment]
1. 不能。还需要显示的指定tp。server启动需要 --tp 2， pipeline接口需要设置 backend_config(TurbomindEngineConfig / PytorchEngineConfig)
2. 启动服务后，每个用户都可以用api接口，这个接口并不是完全阻塞的，可以并发的调用。
3. api 接口不支持batch输入，但是客户端可以多线程等方式调用api接口，只要前一个请求未处理完都可以实现并发。

**Comment by RyanOvO** [comment]
> 1. 不能。还需要显示的指定tp。server启动需要 --tp 2， pipeline接口需要设置 backend_config(TurbomindEngineConfig / PytorchEngineConfig)
> 2. 启动服务后，每个用户都可以用api接口，这个接口并不是完全阻塞的，可以并发的调用。
> 3. api 接口不支持batch输入，但是客户端可以多线程等方式调用api接口，只要前一个请求未处理完都可以实现并发。

好的，了解了，感谢
