### ISSUE TITLE
[Bug] 项目在 arm64 芯片的 Mac 上在 cmake 步骤中构建失败。

### ISSUE THREAD

**Issue by FellowTraveler** [InternLM/lmdeploy#2228]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

Project fails to build in cmake step; tries to find CUDA even though platform is Silicon Mac. Instead should fail gracefully with message: _"We are unable to get our project to build on Mac."_

### Reproduction

cmake

### Environment

```Shell
M3 Mac
```

### Error traceback

```Shell
% cmake ..
-- The CXX compiler identification is AppleClang 15.0.0.15000309
CMake Error at /opt/homebrew/Cellar/cmake/3.29.2/share/cmake/Modules/Internal/CMakeCUDAFindToolkit.cmake:104 (message):
  Failed to find nvcc.

  Compiler requires the CUDA toolkit.  Please set the CUDAToolkit_ROOT
  variable.
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.29.2/share/cmake/Modules/CMakeDetermineCUDACompiler.cmake:85 (cmake_cuda_find_toolkit)
  CMakeLists.txt:16 (project)


-- Configuring incomplete, errors occurred!
```
```

**Comment by lvhan028** [comment]
LMDeploy doesn't support MacOS. It is developed on CUDA platform
