### ISSUE TITLE
Lmdeploy turbomind backend support rope_scaling?

### ISSUE THREAD

**Issue by Lzhang-hub** [InternLM/lmdeploy#2235]
### 📚 The doc issue

Lmdeploy  turbomind backend support rope_scaling?  like:
```
  "rope_scaling": {
      "factor": 4.0,
      "original_max_position_embeddings": 32768,
      "type": "yarn"
  }
```

**Comment by lvhan028** [comment]
It hasn't supported "yarn" yet.

**Comment by Lzhang-hub** [comment]
Is there some docs about how to use rope_scaling？

**Comment by Lzhang-hub** [comment]
I found it https://lmdeploy.readthedocs.io/en/latest/advance/long_context.html
just set rope_scaling_factor>1.0?

**Comment by lvhan028** [comment]
https://lmdeploy.readthedocs.io/en/latest/advance/long_context.html requires the type of rope_scaling "dynamic" rather than "yarn".

**Comment by thiner** [comment]
Simply add the argument `--rope-scaling-factor 2.0` works for `Qwen2-72b-instruct` model.

**Comment by lvhan028** [comment]
I don't know if `--rope-scaling-factor 2.0` works for qwen2 model. 
According to [qwen2' tech report](https://arxiv.org/pdf/2407.10671), it uses "yarn" for long context inference
