### ISSUE TITLE
[Bug] RuntimeError: [TM][ERROR] CUDA runtime error: out of memory /lmdeploy/src/turbomind/utils/memory_utils.cu:32

### ISSUE THREAD

**Issue by dengruoqing** [InternLM/lmdeploy#2236]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

RuntimeError: [TM][ERROR] CUDA runtime error: out of memory /lmdeploy/src/turbomind/utils/memory_utils.cu:32

### Reproduction

RuntimeError: [TM][ERROR] CUDA runtime error: out of memory /lmdeploy/src/turbomind/utils/memory_utils.cu:32

### Environment

```Shell
A100
单卡40G显存
```

**Comment by lvhan028** [comment]
Please provide the production method

**Comment by seetimee** [comment]
same bug use comand：python /root/swift/swift/cli/deploy.py --host 0.0.0.0 --port 6006 --model_type qwen2-7b-instruct --infer_backend lmdeploy
after OpenCompass batch 8 test it raise the error：terminate called after throwing an instance of 'std::runtime_error'
  what():  [TM][ERROR] CUDA runtime error: out of memory /lmdeploy/src/turbomind/utils/allocator.h:233

**Comment by seetimee** [comment]
4090 24g

**Comment by seetimee** [comment]
nevertheless vllm is stable

**Comment by seetimee** [comment]
I checked faq：https://lmdeploy.readthedocs.io/en/latest/faq.html#inference    ，Is it possible to stably auto configure the --cache-max-entry-count parameter？

**Comment by lvhan028** [comment]
what version of lmdeploy are you using?

**Comment by seetimee** [comment]
0.5.2.post1

**Comment by lvhan028** [comment]
Could you upgrade to lmdeploy v0.5.3 and try it again. 
I haven't used swift yet. 
I couldn't appreciate too much if you can reproduce the issue with lmdeploy api_server and the official qwen2-7b-instruct model

**Comment by seetimee** [comment]
After upgrade to lmdeploy v0.5.3 and try it again.I stably worked.

**Comment by starevelyn** [comment]
> After upgrade to lmdeploy v0.5.3 and try it again.I stably worked.升级到lmdeploy v0.5.3后，再试一次，工作稳定了。

i use Version: 0.7.0， get the same bug ,  same in use swift  to eval ....
conditions are 8gpus, 80g per gpu, to infer a 76b model  ,don't know why
