### ISSUE TITLE
lmdeploy在windows上的支持问题

### ISSUE THREAD

**Issue by humphreyde** [InternLM/lmdeploy#2238]
你好，我在windows裸机上本地部署internvl2-8B，运行示例代码：
```
from lmdeploy import pipeline, TurbomindEngineConfig, ChatTemplateConfig, GenerationConfig
from lmdeploy.vl import load_image

model = 'D:\\xxxx\\InternVL2-8B'
system_prompt = '我是书生·万象，英文名是InternVL，是由上海人工智能实验室、清华大学及多家合作单位联合开发的多模态大语言模型。'
chat_template_config = ChatTemplateConfig('internvl-internlm2')
chat_template_config.meta_instruction = system_prompt
pipe = pipeline(model, chat_template_config=chat_template_config,
                backend_config=TurbomindEngineConfig(session_len=8192))

image = load_image('D:\\xxx.jpg')
gen_config = GenerationConfig(top_k=40, top_p=0.8, temperature=0.8)
sess = pipe.chat(('describe this image', image), gen_config=gen_config)
print(sess.response.text)
sess = pipe.chat('What is the woman doing?', session=sess, gen_config=gen_config)
print(sess.response.text)
```
没有任何输出
以下是一些warning：
Flash Attention is not available, use_flash_attn is set to false.
....
gemm_config.in is not found; using default GEMM algo
 
那边仓库说是[lmdeploy](https://github.com/OpenGVLab/InternVL/issues/391)在windows的支持不好的问题，请问有什么好的解决方案吗？
我的环境是：
torch2.2.2+cu121
lmdeploy 0.5.2.post1

_Originally posted by @humphreyde in https://github.com/InternLM/lmdeploy/issues/1177#issuecomment-2270268388_

**Comment by irexyc** [comment]
这个warning可以不用管。

把日志打开，然后把所有的输出（从加载模型开始和推理结束）发上来看看？
```
pipe = pipeline(model, chat_template_config=chat_template_config,
                backend_config=TurbomindEngineConfig(session_len=8192), log_level='INFO')
```

**Comment by humphreyde** [comment]
> 这个warning可以不用管。
> 
> 把日志打开，然后把所有的输出（从加载模型开始和推理结束）发上来看看？
> 
> ```
> pipe = pipeline(model, chat_template_config=chat_template_config,
>                 backend_config=TurbomindEngineConfig(session_len=8192), log_level='INFO')
> ```

![IMG_20240806_111839](https://github.com/user-attachments/assets/55caa897-e55c-447c-86b9-4a33b6286165)
![IMG_20240806_111938](https://github.com/user-attachments/assets/54aa36cb-8e1e-4af5-b815-e7db94ba47c9)
![IMG_20240806_111953](https://github.com/user-attachments/assets/62b328de-8af7-4c66-ba44-80cca9e86470)

**Comment by irexyc** [comment]
<img width="842" alt="image" src="https://github.com/user-attachments/assets/b2f72e05-508b-4f56-a7f0-53d92d245192">

max_block_count 表示kvcache的能够分配的块数，这个显示已经没有剩余的显存来分配了，所以output的长度直接被砍到0，然后就没输出了。

什么显卡？多大显存？加载完模型剩余显存有多少？

或许可以试试这个 https://huggingface.co/OpenGVLab/InternVL2-8B-AWQ
backend_config=TurbomindEngineConfig(session_len=4096, model_format='awq')

**Comment by humphreyde** [comment]
> <img alt="image" width="842" src="https://private-user-images.githubusercontent.com/16019484/355301481-b2f72e05-508b-4f56-a7f0-53d92d245192.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MTU2NDYsIm5iZiI6MTcyMjkxNTM0NiwicGF0aCI6Ii8xNjAxOTQ4NC8zNTUzMDE0ODEtYjJmNzJlMDUtNTA4Yi00ZjU2LWE3ZjAtNTNkOTJkMjQ1MTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAzMzU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYmM0YzUzOWVhYmZlNzdiYjE3MTZjZWZkMjNlYTY4ZmYzMTUzZTA3ZWQyNmEzOWM3YzI3OTY4OGJjZDBhNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0LznftNp7UAupldKC_XhWZXnkSP0OwtEwR-znEB3r04">
> max_block_count 表示kvcache的能够分配的块数，这个显示已经没有剩余的显存来分配了，所以output的长度直接被砍到0，然后就没输出了。
> 
> 什么显卡？多大显存？加载完模型剩余显存有多少？
> 
> 或许可以试试这个 https://huggingface.co/OpenGVLab/InternVL2-8B-AWQ backend_config=TurbomindEngineConfig(session_len=4096, model_format='awq')

A4000 16G显存，加载完基本拉满了，AWQ是量化版本吗？请问有没有魔塔的链接呀，我上hf下不了

**Comment by irexyc** [comment]
这个mirror 能打开么 https://hf-mirror.com/OpenGVLab/InternVL2-8B-AWQ

能打开的话，可以按照使用说明下载 https://hf-mirror.com/
https://zhuanlan.zhihu.com/p/663712983

**Comment by humphreyde** [comment]
谢谢，可以下载，就是时间有点长，可能要好几个小时了。
所以这个没输出内容是因为显存不够吗？

**Comment by irexyc** [comment]
@humphreyde 

从日志上看，是因为显存导致的无法分配kvcache块。可以试下小一点的模型能否正常推理，比如 https://huggingface.co/liuhaotian/llava-v1.5-7b

**Comment by humphreyde** [comment]
换awq版本可以使用了，感谢！！
