### ISSUE TITLE
[Bug] Infering InternVL2-8B model with  Lmdepoly in trouble

### ISSUE THREAD

**Issue by PancakeAwesome** [InternLM/lmdeploy#2239]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

RuntimeError: This event loop is already running

## 出错日志：
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[1], line 11
      8 chat_template_config.meta_instruction = system_prompt
      9 pipe = pipeline(model, chat_template_config=chat_template_config,
     10                 backend_config=TurbomindEngineConfig(session_len=8192))
---> 11 response = pipe(('describe this image', image))
     12 print(response.text)

File /opt/conda/lib/python3.8/site-packages/lmdeploy/serve/vl_async_engine.py:123, in VLAsyncEngine.__call__(self, prompts, **kwargs)
    121 """Inference a batch of prompts."""
    122 prompts = self._convert_prompts(prompts)
--> 123 return super().__call__(prompts, **kwargs)

File /opt/conda/lib/python3.8/site-packages/lmdeploy/serve/async_engine.py:305, in AsyncEngine.__call__(self, prompts, gen_config, request_output_len, top_k, top_p, temperature, repetition_penalty, ignore_eos, do_preprocess, adapter_name, use_tqdm, **kwargs)
    297 if gen_config is None:
    298     gen_config = GenerationConfig(
    299         max_new_tokens=request_output_len,
    300         top_k=top_k,
   (...)
    303         repetition_penalty=repetition_penalty,
    304         ignore_eos=ignore_eos)
--> 305 return self.batch_infer(prompts,
    306                         gen_config=gen_config,
    307                         do_preprocess=do_preprocess,
    308                         adapter_name=adapter_name,
    309                         use_tqdm=use_tqdm,
    310                         **kwargs)

File /opt/conda/lib/python3.8/site-packages/lmdeploy/serve/vl_async_engine.py:109, in VLAsyncEngine.batch_infer(self, prompts, **kwargs)
    107 """Inference a batch of prompts."""
    108 prompts = self._convert_prompts(prompts)
--> 109 return super().batch_infer(prompts, **kwargs)

File /opt/conda/lib/python3.8/site-packages/lmdeploy/serve/async_engine.py:429, in AsyncEngine.batch_infer(self, prompts, gen_config, do_preprocess, adapter_name, use_tqdm, **kwargs)
    425 async def gather():
    426     await asyncio.gather(
    427         *[_inner_call(i, generators[i]) for i in range(len(prompts))])
--> 429 _get_event_loop().run_until_complete(gather())
    430 outputs = outputs[0] if need_list_wrap else outputs
    431 return outputs

File /opt/conda/lib/python3.8/asyncio/base_events.py:592, in BaseEventLoop.run_until_complete(self, future)
    581 """Run until the Future is done.
    582 
    583 If the argument is a coroutine, it is wrapped in a Task.
   (...)
    589 Return the Future's result, or raise its exception.
    590 """
    591 self._check_closed()
--> 592 self._check_running()
    594 new_task = not futures.isfuture(future)
    595 future = tasks.ensure_future(future, loop=self)

File /opt/conda/lib/python3.8/asyncio/base_events.py:552, in BaseEventLoop._check_running(self)
    550 def _check_running(self):
    551     if self.is_running():
--> 552         raise RuntimeError('This event loop is already running')
    553     if events._get_running_loop() is not None:
    554         raise RuntimeError(
    555             'Cannot run the event loop while another loop is running')

RuntimeError: This event loop is already running

## 出错代码：
from lmdeploy import pipeline, TurbomindEngineConfig, ChatTemplateConfig
from lmdeploy.vl import load_image

model = 'OpenGVLab__InternVL2-8B/'
system_prompt = '我是书生·万象，英文名是InternVL，是由上海人工智能实验室、清华大学及多家合作单位联合开发的多模态大语言模型。'
image = load_image('xx.jpg')
chat_template_config = ChatTemplateConfig('internvl-internlm2')
chat_template_config.meta_instruction = system_prompt
pipe = pipeline(model, chat_template_config=chat_template_config,
                backend_config=TurbomindEngineConfig(session_len=8192))
response = pipe(('describe this image', image))
print(response.text)

### Environment

```Shell
## 环境：
sys.platform: linux
Python: 3.8.18 (default, Sep 11 2023, 13:40:15) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA A10
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.1, V12.1.105
GCC: gcc (GCC) 9.2.1 20200522 (Alibaba 9.2.1-3 2.17)
PyTorch: 2.1.0+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.3
    - Built with CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.16.0+cu121
LMDeploy: 0.5.2.post1+
transformers: 4.37.2
gradio: 3.39.0
fastapi: 0.108.0
pydantic: 2.5.0
triton: 2.1.0
NVIDIA Topology: 
        GPU0    CPU Affinity    NUMA Affinity
GPU0     X      32-63,96-127    1

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

**Comment by PancakeAwesome** [comment]
@irexyc thank u for help

**Comment by irexyc** [comment]
Are you using jupyter? If so, it could be the same problem as https://github.com/InternLM/lmdeploy/issues/2030.
