### ISSUE TITLE
[Bug] AssertionError: tp should be 2^n

### ISSUE THREAD

**Issue by colorfulandcjy0806** [InternLM/lmdeploy#2249]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

I am curious why TP should be 2 ^ n. If I only have 5 cards, how should I use them?
我很好奇，为什么设置 tp should be 2^n，如果我刚好只有5张卡，应该怎么使用呢？
Thank you for your answer!

### Reproduction

pipe = pipeline(model, chat_template_config=chat_template_config,
                backend_config=TurbomindEngineConfig(session_len=8192, tp=5))

### Environment

```Shell
CUDA Version: 12.4
```

**Comment by lvhan028** [comment]
You can only use 4 GPU now

**Comment by colorfulandcjy0806** [comment]
I hope you can consider fixing this issue in the future. It shouldn't be difficult to implement in engineering? Thank you! @lvhan028

**Comment by lvhan028** [comment]
OK
