### ISSUE TITLE
[Bug] mac  pip  提示找不到匹配信息

### ISSUE THREAD

**Issue by fuckqqcom** [InternLM/lmdeploy#2253]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

```
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement lmdeploy (from versions: none)
ERROR: No matching distribution found for lmdeploy



ERROR: Could not find a version that satisfies the requirement lmdeploy==0.5.3 (from versions: none)
ERROR: No matching distribution found for lmdeploy==0.5.3


```

### Reproduction

 pip  install lmdeploy==0.5.3 -i https://pypi.org/simple  

### Environment

```Shell
mac:14.6 (23G80) Apple M1
```

**Comment by lvhan028** [comment]
LMDeploy doesn't support MacOS. 
It is developed on CUDA platform.
