### ISSUE TITLE
[Bug] after i convert llava-1.5 to turbomind format, the same input occur an error: run out of tokens

### ISSUE THREAD

**Issue by Skyseaee** [InternLM/lmdeploy#2254]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

I use the `lmdeploy serve api_server ./llava-v1.5-7b/ --server-port 2333 --vision-max-batch-size 8 --tp 1 --backend turbomind --model-name llava-v1` and input an image which converted to base64, and the output is `{'id': '1', 'object': 'chat.completion', 'created': 1723024212, 'model': 'llava-v1', 'choices': [{'index': 0, 'message': {'role': 'assistant', 'content': ' In this scene, there is a blue digital camera with gold trim sitting on top of its box or stand in front of it. This compact device appears ready for use by anyone who wants to capture memories through photography.', 'tool_calls': None}, 'logprobs': None, 'finish_reason': 'stop'}], 'usage': {'prompt_tokens': 623, 'total_tokens': 668, 'completion_tokens': 45}}` but when after i use the converted model, the output is `{'id': '1', 'object': 'chat.completion', 'created': 1723025286, 'model': 'llava-v1', 'choices': [{'index': 0, 'message': {'role': 'assistant', 'content': '', 'tool_calls': None}, 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'prompt_tokens': 47511, 'total_tokens': 47511, 'completion_tokens': 0}}`, the convert command is `lmdeploy convert --model-format hf --tp 1 --tokenizer-path ./llava-v1.5-7b/tokenizer.model --dst-path downloads/downloads/llava-v1.5-7b/hf2turbomind/ llava-v1 downloads/downloads/llava-v1.5-7b/llava-v1.5-7b/`

### Reproduction

`lmdeploy convert --model-format hf --tp 1 --tokenizer-path ./llava-v1.5-7b/tokenizer.model --dst-path downloads/downloads/llava-v1.5-7b/hf2turbomind/ llava-v1 downloads/downloads/llava-v1.5-7b/llava-v1.5-7b/`
`lmdeploy serve api_server ./downloads/downloads/llava-v1.5-7b/hf2turbomind/ --server-port 2333 --vision-max-batch-size 8 --tp 1 --backend turbomind --model-name llava-v1`

### Environment

```Shell
sys.platform: linux
Python: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA A100 80GB PCIe
CUDA_HOME: /usr
NVCC: Cuda compilation tools, release 10.1, V10.1.24
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
PyTorch: 2.1.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.16.2+cu121
LMDeploy: 0.5.3+
transformers: 4.37.2
gradio: 4.16.0
fastapi: 0.112.0
pydantic: 2.8.2
triton: 2.1.0
NVIDIA Topology: 
        GPU0    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      24-35   2               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

### Error traceback

```Shell
INFO:     127.0.0.1:40038 - "GET /v1/models HTTP/1.1" 200 OK
Token indices sequence length is longer than the specified maximum sequence length for this model (47511 > 2048). Running this sequence through the model will result in indexing errors
2024-08-07 10:08:06,348 - lmdeploy - ERROR - Truncate max_new_tokens to 128
2024-08-07 10:08:06,348 - lmdeploy - ERROR - run out of tokens. session_id=1.
INFO:     127.0.0.1:40044 - "POST /v1/chat/completions HTTP/1.1" 200 OK
```

**Comment by lvhan028** [comment]
When you want to deploy a VLM model, you cannot convert it. LMDeploy doesn't support this usage
