### ISSUE TITLE
[Bug] Intel MKL FATAL ERROR /torch/lib/libtorch_cpu.so

### ISSUE THREAD

**Issue by maxin9966** [InternLM/lmdeploy#2258]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

V0.5.3

lmdeploy lite auto_awq internlm/internlm2_5-20b-chat --work-dir /home/ma/work/models/internlm2_5-20b-chat-4bit --batch-size 8 --search-scale True
Intel MKL FATAL ERROR: Cannot load /home/ma/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so.

### Reproduction

lmdeploy lite auto_awq internlm/internlm2_5-20b-chat --work-dir /home/ma/work/models/internlm2_5-20b-chat-4bit --batch-size 8 --search-scale True

### Environment

```Shell
cuda 12.5
```

**Comment by Luchen-077** [comment]
I meet the same bug, have you resolved?

**Comment by Luchen-077** [comment]
The bug has been solved. 
When I tried to 'conda activate xxx' I got the info 'sh: 0: getcwd() failded: No such file or directory', and then the info like this while training a model.

**Comment by Luchen-077** [comment]
The bug has been solved.
When I tried to 'conda activate xxx' I got the info 'sh: 0: getcwd() failded: No such file or directory', and then the info like this while training a model.

**Comment by PixelChen24** [comment]
> The bug has been solved. When I tried to 'conda activate xxx' I got the info 'sh: 0: getcwd() failded: No such file or directory', and then the info like this while training a model. About the first info, use 'cd ~' command and run what you want (for example: 'conda activate xxx' for me) then cd back your directory and train. It works

This really works for me, but I still wonder the reason behind this and why does this work

**Comment by Elena-TKO** [comment]
> > The bug has been solved. When I tried to 'conda activate xxx' I got the info 'sh: 0: getcwd() failded: No such file or directory', and then the info like this while training a model. About the first info, use 'cd ~' command and run what you want (for example: 'conda activate xxx' for me) then cd back your directory and train. It works
> 
> This really works for me, but I still wonder the reason behind this and why does this work

In my situation this was because I tried to launch code from the deleted folder.

**Comment by RiverGao** [comment]
> The bug has been solved. When I tried to 'conda activate xxx' I got the info 'sh: 0: getcwd() failded: No such file or directory', and then the info like this while training a model. About the first info, use 'cd ~' command and run what you want (for example: 'conda activate xxx' for me) then cd back your directory and train. It works

This also works for me. I get the error when I was trying to run a inference script after an NFS failure and reconnect
