### ISSUE TITLE
internvl2-8b 推理结果没有特殊token

### ISSUE THREAD

**Issue by lyc728** [InternLM/lmdeploy#2259]
Response(text='厦门太古起落架维修服务有限公司204 215 383 227太古起落架其他专用型保税仓库204 247 366 260付汇证明联803 98 881 114', generate_token_len=61, input_token_len=3398, session_id=0, finish_reason='stop', token_ids=[92549, 73420, 60652, 60974, 60480, 61036, 61351, 70539, 68320, 68694, 92550, 92551, 7838, 262, 11998, 262, 18857, 262, 14026, 92552, 92547, 92549, 60652, 60974, 60480, 61036, 61351, 68345, 71923, 60653, 60559, 61602, 74558, 92550, 92551, 7838, 262, 13947, 262, 17720, 262, 11291, 92552, 92547, 92549, 61074, 61744, 69295, 60816, 92550, 92551, 20462, 262, 3350, 262, 24740, 262, 7991, 92552, 92547], logprobs=None),

原本输出是为这种形式
`<ref>厦门太古起落架维修服务有限公司</ref><box>204 215 383 227</box>`
<img width="528" alt="企业微信截图_17230811195052" src="https://github.com/user-attachments/assets/b63a5f8f-c72b-45a3-af51-1d8f7b142483">

**Comment by lvhan028** [comment]
Please share the reproduction method. Otherwise, we cannot do the favor

**Comment by lyc728** [comment]
model_path = "/swift/us_desc/internvl2-8b/v14-20240806-104250/checkpoint-3700-merged"
pipe = pipeline(model_path)

**Comment by irexyc** [comment]
please try:
```
pipe(..., gen_config=GenerationConfig(skip_special_tokens=False))
```

**Comment by lyc728** [comment]
同样的，并没有起作用

**Comment by lvhan028** [comment]
这些token有作为stop_words，设置到GenerationConfig中么？
能不能基于 InternVL 的模型，提供一个复现的例子呢？

**Comment by lyc728** [comment]
> 这些token有作为stop_words，设置到GenerationConfig中么？ 能不能基于 InternVL 的模型，提供一个复现的例子呢？

我是训练中加入了这些字符的，作为判断文本和坐标，复现的话应该是基于我的模型

**Comment by irexyc** [comment]
我用的模型好像没有检测的能力，但是基于你给的token_ids，如果在tokenizer.decode中增加skip_special_tokens参数的话，是可以解码出这些特殊字符的。

```python
from lmdeploy import pipeline
pipe = pipeline('/mnt/140/InternVL2-8B/')
token_ids=[92549, 73420, 60652, 60974, 60480, 61036, 61351, 70539, 68320, 68694, 92550, 92551, 7838, 262, 11998, 262, 18857, 262, 14026, 92552, 92547, 92549, 60652, 60974, 60480, 61036, 61351, 68345, 71923, 60653, 60559, 61602, 74558, 92550, 92551, 7838, 262, 13947, 262, 17720, 262, 11291, 92552, 92547, 92549, 61074, 61744, 69295, 60816, 92550, 92551, 20462, 262, 3350, 262, 24740, 262, 7991, 92552, 92547]
pipe.tokenizer.decode(token_ids)
# '厦门太古起落架维修服务有限公司204 215 383 227太古起落架其他专用型保税仓库204 247 366 260付汇证明联803 98 881 114'
pipe.tokenizer.decode(token_ids, skip_special_tokens=False)
# '<ref> 厦门太古起落架维修服务有限公司 </ref> <box> 204 215 383 227 </box> <quad> <ref> 太古起落架其他专用型保税仓库 </ref> <box> 204 247 366 260 </box> <quad> <ref> 付汇证明联 </ref> <box> 803 98 881 114 </box> <quad>'
```

https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/serve/async_engine.py#L584-L588
这里设置 gen_config=GenerationConfig(skip_special_tokens=False) 感觉应该生效才对。

**Comment by lyc728** [comment]
我是自己微调的模型，模型在swift下进行的微调，他们的推理是正确的，但是采用deploy加速，就没有这些特殊符号，很奇怪

**Comment by lvhan028** [comment]
你用transformers推理，有这些special token么？

**Comment by lyc728** [comment]
transformers推理是什么意思呢？原生的框架是能推理出来的哈

**Comment by lvhan028** [comment]
> transformers推理是什么意思呢？原生的框架是能推理出来的哈

就是用 transformers 的接口，AutoModel.from_pretrained()，model.generate
