### ISSUE TITLE
Does TurboMind support Qwen-7b deployment?

### ISSUE THREAD

**Issue by songkq** [InternLM/lmdeploy#226]
Different from `LLama`, `Qwen-7b` has the `bias` item of `c_attn = nn.Linear(config.hidden_size, 3 * self.projection_size)` and apply a `logn_attn` operation on `query`. 
https://huggingface.co/Qwen/Qwen-7B-Chat/blob/d55c70de6c4255551acfbe560b43b03eb80ed80b/modeling_qwen.py#L205
https://huggingface.co/Qwen/Qwen-7B-Chat/blob/d55c70de6c4255551acfbe560b43b03eb80ed80b/modeling_qwen.py#L420

Could you please give some advice for Qwen-7b deployment using TurboMind?

**Comment by lzhangzz** [comment]
We already have support for bias in attention module as in InternLM-7B. To support Qwen-7B, ntk-aware interpolation and logN attention scaling must be added.

**Comment by lzhangzz** [comment]
@songkq 

Just added basic support (w/o NTK and logN scaling, works within 2048 context length) for Qwen-7B #230, you may try to add chat template on top of it.

**Comment by lzhangzz** [comment]
Got it working locally, will push to GitHub soon. Stay tuned.

**Comment by songkq** [comment]
@lzhangzz  Does this PR https://github.com/InternLM/lmdeploy/pull/230 work well locally, right?

**Comment by lzhangzz** [comment]
@songkq should be working now

**Comment by songkq** [comment]
@lzhangzz Good job~

**Comment by lvhan028** [comment]
已经合入了。
