### ISSUE TITLE
使用lmdeploy的openai部署了internvl2.0服务，准备做视频推理，但是结果很不稳定

### ISSUE THREAD

**Issue by sunnymoon155** [InternLM/lmdeploy#2260]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

internvl2.0是支持多图推理和视频推理的，原理是一样的都是多图输入，于是我用lmdeploy搭建了一个api，调用的时候用的https://platform.openai.com/docs/guides/vision/multiple-image-inputs
这个方式，但是返回结果很不稳定，没有官方提供的专门推理视频的demo好
https://github.com/OpenGVLab/InternVL?tab=readme-ov-file#quick-start-with-huggingface
请问是什么原因呢，官方demo的处理方式也是将视频抽帧，然后把list输入进去。我怀疑是lmdeploy推理时模型无法得知每帧的输入顺序，导致回答的比较混乱，每次都不一致。看了一些issue提到了用<image_token>放到prompt里边，试了一下貌似没用，不知道是不是方法有问题。

"content": [
        {
          "type": "text",
          "text": "Frame1: <IMAGE_TOKEN>\nFrame2: <IMAGE_TOKEN>\n视频中的人在干什么？",
        }
类似这样修改提示词来确定每帧的顺序，但是结果仍然不稳定

### Reproduction
server：
lmdeploy server api_server OpenGVLab/InternVL-28B --model-name InternVL2-8B --backend turbomind --server-port 23333

client：
from openai import OpenAI

client = OpenAI()
response = client.chat.completions.create(
  model="gpt-4o-mini",
  messages=[
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "What are in these images? Is there any difference between them?",
        },
        {
          "type": "image_url",
          "image_url": {
            "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg",
          },
        },
        {
          "type": "image_url",
          "image_url": {
            "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg",
          },
        },
      ],
    }
  ],
  max_tokens=300,
)
print(response.choices[0])

### Environment

```Shell
internvl2.0-8B
```

**Comment by irexyc** [comment]
<IMAGE_TOKEN> 的用法没有问题，不插入这个的话，就会把所有图片放到开头的位置。关于顺序的话，就是content中图片的顺序。

不稳定指的是结果有随机性，还是说结果有好有差，然后差的概率有点大？结果随机是正常的，因为有sample。如果是说结果差的比较多恶化，有试过直接用 transformers的代码，按照internvl改的代码推理试试看呢？如果有试的话，可以提供一下代码，我这边对比看看。

**Comment by sunnymoon155** [comment]
> <IMAGE_TOKEN> 的用法没有问题，不插入这个的话，就会把所有图片放到开头的位置。关于顺序的话，就是content中图片的顺序。
> 
> 不稳定指的是结果有随机性，还是说结果有好有差，然后差的概率有点大？结果随机是正常的，因为有sample。如果是说结果差的比较多恶化，有试过直接用 transformers的代码，按照internvl改的代码推理试试看呢？如果有试的话，可以提供一下代码，我这边对比看看。

@irexyc 谢谢大佬解答，lmdeploy的结果很差，基本识别不出视频中的动作，感觉并没有把输入的这几帧连续起来推理。如果使用官方demo里的推理，多次识别结果基本不变，且准确率很高。
官方推理结果：在视频的开始。。。，随着视频的进行。。。然后这个人。。。最终这个人。。。
lmdeploy结果：在视频中可以看到。。。还可以看到。。。视频中还有。。。（就感觉像是硬从图里边找prompt提到的视频动作，并没有真正的把这几帧的输入当作连续的一个时序动作预测）
video_path = './examples/red-panda.mp4'
pixel_values, num_patches_list = load_video(video_path, num_segments=8, max_num=1)
pixel_values = pixel_values.to(torch.bfloat16).cuda()
video_prefix = ''.join([f'Frame{i+1}: <image>\n' for i in range(len(num_patches_list))])
question = video_prefix + 'What is the red panda doing?'
# Frame1: <image>\nFrame2: <image>\n...\nFrame8: <image>\n{question}
response, history = model.chat(tokenizer, pixel_values, question, generation_config,
                               num_patches_list=num_patches_list, history=None, return_history=True)
print(f'User: {question}\nAssistant: {response}')
这是官方视频推理的代码，你说的用transformers的代码推理是什么意思呢？

**Comment by irexyc** [comment]
官方的代码就是用transformers推理的。

**Comment by irexyc** [comment]
@sunnymoon155

能提供一下你用的数据么，官方这个demo体现不出来时序。

另外能提供一下你用的推理代码么？我这边也好复现。官方的demo，do_sample没开，多次的结果应该一样才对。

**Comment by sunnymoon155** [comment]
@irexyc 大佬，感谢解答，我使用官方的demo推理确实多次的结果一样，比较准确。我的代码和数据如下，辛苦复现一下谢谢。官方demo的结果很准，能识别出视频中的人摔倒了，同样的prompt用lmdeploy提问每次都不一样，而且基本识别不出来。

https://github.com/user-attachments/assets/0ceae7a0-f525-482a-9e64-a86f00fc2898

server: 
lmdeploy serve api_server OpenGVLab/InternVL2-8B --server-port 8080 --server-name 0.0.0.0 --model-name internvl-2 --backend turbomind --tp 2

client:
from openai import OpenAI
import os
from decord import VideoReader, cpu
import numpy as np
import base64
from PIL import Image
import cv2

client = OpenAI(base_url='http://localhost:8080/v1', api_key='xxx')
    
def get_index(bound, fps, max_frame, first_idx=0, num_segments=32):
    if bound:
        start, end = bound[0], bound[1]
    else:
        start, end = -100000, 100000
    start_idx = max(first_idx, round(start * fps))
    end_idx = min(round(end * fps), max_frame)
    seg_size = float(end_idx - start_idx) / num_segments
    frame_indices = np.array([
        int(start_idx + (seg_size / 2) + np.round(seg_size * idx))
        for idx in range(num_segments)
    ])
    return frame_indices

def load_video(video_path, bound=None, input_size=448, max_num=1, num_segments=32):
    vr = VideoReader(video_path, ctx=cpu(0), num_threads=1)
    max_frame = len(vr) - 1
    fps = float(vr.get_avg_fps())
    frame_list = []

    pixel_values_list, num_patches_list = [], []
    frame_indices = get_index(bound, fps, max_frame, first_idx=0, num_segments=num_segments)
    for frame_index in frame_indices:
        img = vr[frame_index].asnumpy()
        ret,img_byte_array = cv2.imencode('.jpg',img)
        img_byte = img_byte_array.tobytes()
        base64_encoded = base64.b64encode(img_byte).decode('utf-8')
        frame_list.append(base64_encoded)
    return frame_list

video_frame = load_video('video/output.mp4', num_segments=8)
frame_list_url = []

for frame in video_frame:
    image = {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{frame}"}}
    frame_list_url.append(image)

response = client.chat.completions.create(
    model="internvl-2",
    messages=[
    {
        "role": "user",
        "content": [{
        "type": "text",
        "text": "Frame1: <IMAGE_TOKEN>\nFrame2: <IMAGE_TOKEN>\nFrame3: <IMAGE_TOKEN>\nFrame4: <IMAGE_TOKEN>\nFrame5: <IMAGE_TOKEN>\nFrame6: <IMAGE_TOKEN>\nFrame7: <IMAGE_TOKEN>\nFrame8: <IMAGE_TOKEN>\n请详细描述视频中的人正在干什么，他是否摔倒了？",
        }, 
        frame_list_url[0],frame_lis

**Comment by sunnymoon155** [comment]
> @sunnymoon155
> 
> 能提供一下你用的数据么，官方这个demo体现不出来你说的这种时序。
> 
> 另外能提供一下你用的推理代码么？我这边也好复现。官方的demo，do_sample没开，多次的结果应该一样才对。

大佬，代码和数据发在上面了，有时间帮忙看下哈

**Comment by irexyc** [comment]
这是我用transformers推理的结果。(do_sample=False)
```
'视频中显示了一位年长的男子，他正在一个房间里整理床铺。他穿着白色的上衣和蓝色的裤子，正在将床单和枕头整理好。在整理过程中，他弯下腰，似乎在调整床上的物品。\n\n从视频中可以看出，这位男子并没有摔倒。他动作稳健，虽然弯腰整理床铺，但并没有表现出任何摔倒的迹象。整个过程中，他始终保持站立的姿势，并且动作流畅，没有出现任何不稳定的迹象。\n\n视频中还显示，房间的另一侧有一扇门，门后站着一位穿黑色上衣的男子，他似乎在观察房间内的情况。此外，房间内还有一些其他物品，如椅子、桌子等，但这些物品与男子的动作无关。\n\n总的来说，视频中的男子正在整理床铺，并且没有摔倒。他的动作平稳，整个过程显得非常自然和流畅。'
```

这是我用transformers处理完得到的input_embeds之后，作为lmdeploy的输入，推理后的结果 (top_k=1，等价于do_sample=False)，结果的差别可以认为是kernel不同导致的，因为输入是完全一致的。
```
'视频中显示了一位年长的男子，他正在一个房间里整理床铺。他穿着白色的上衣和蓝色的裤子，正在将床单和枕头整理好。从视频中可以看出，他非常专注于手头的工作，动作显得有些匆忙。\n\n在视频的最后几秒钟，这位男子似乎在整理床铺时突然失去平衡，身体向前倾倒，最终摔倒在床上。这一幕发生得非常突然，让人感到有些意外。\n\n总的来说，视频中的男子正在整理床铺，但由于某种原因，他最终摔倒在床上。'
```

然后我比较了一下transformers 和 lmdeploy 的输入，有两个地方有差别。1）template的区别。transformers这边在`<image>`前后加了`<img>, </img>`，所以在lmdeploy中如果自定义插图位置，需要使用`<img><IMAGE_TOKEN></img>`。另外模版中的 meta, user, assistant的结尾多了换行。2）max_dynamic_patch 的区别。transformers在load_image的时候，指定了每个图片的max patch数为1，lmdeploy这边会使用默认的12。

将上面说的两个问题对齐之后，lmdeploy的结果为下面的（top_k=1, vision模型默认使用的fp16数据类型，输入和transformers相比略微有些差别）
```
视频中显示了一位年长的男子，他正在一个房间里整理床铺。他穿着白色的上衣和蓝色的裤子，正在将床单和枕头整理好。从视频中可以看出，他非常专注于手头的工作，动作显得有些匆忙。\n\n在视频的最后几秒钟，这位男子似乎在整理床铺时突然失去平衡，身体向前倾倒，最终摔倒在床上。他的动作显得有些笨拙，可能是因为年纪较大，身体反应不如年轻人灵敏。\n\n总的来说，视频中的男子正在整理床铺，但由于某种原因，他最终摔倒在床上。
```

https://github.com/InternLM/lmdeploy/pull/2292
[code.zip](https://github.com/user-attachments/files/16594181/code.zip)

**Comment by sunnymoon155** [comment]
> 这是我用transformers推理的结果。(do_sample=False)
> 
> ```
> '视频中显示了一位年长的男子，他正在一个房间里整理床铺。他穿着白色的上衣和蓝色的裤子，正在将床单和枕头整理好。在整理过程中，他弯下腰，似乎在调整床上的物品。\n\n从视频中可以看出，这位男子并没有摔倒。他动作稳健，虽然弯腰整理床铺，但并没有表现出任何摔倒的迹象。整个过程中，他始终保持站立的姿势，并且动作流畅，没有出现任何不稳定的迹象。\n\n视频中还显示，房间的另一侧有一扇门，门后站着一位穿黑色上衣的男子，他似乎在观察房间内的情况。此外，房间内还有一些其他物品，如椅子、桌子等，但这些物品与男子的动作无关。\n\n总的来说，视频中的男子正在整理床铺，并且没有摔倒。他的动作平稳，整个过程显得非常自然和流畅。'
> ```
> 
> 这是我用transformers处理完得到的input_embeds之后，作为lmdeploy的输入，推理后的结果 (top_k=1，等价于do_sample=False)，结果的差别可以认为是kernel不同导致的，因为输入是完全一致的。
> 
> ```
> '视频中显示了一位年长的男子，他正在一个房间里整理床铺。他穿着白色的上衣和蓝色的裤子，正在将床单和枕头整理好。从视频中可以看出，他非常专注于手头的工作，动作显得有些匆忙。\n\n在视频的最后几秒钟，这位男子似乎在整理床铺时突然失去平衡，身体向前倾倒，最终摔倒在床上。这一幕发生得非常突然，让人感到有些意外。\n\n总的来说，视频中的男子正在整理床铺，但由于某种原因，他最终摔倒在床上。'
> ```
> 
> 然后我比较了一下transformers 和 lmdeploy 的输入，有两个地方有差别。1）template的区别。transformers这边在`<image>`前后加了`<img>, </img>`，所以在lmdeploy中如果自定义插图位置，需要使用`<img><IMAGE_TOKEN></img>`。另外模版中的 meta, user, assistant的结尾多了换行。2）max_dynamic_patch 的区别。transformers在load_image的时候，指定了每个图片的max patch数为1，lmdeploy这边会使用默认的12。
> 
> 将上面说的两个问题对齐之后，lmdeploy的结果为下面的（top_k=1, vision模型默认使用的fp16数据类型，输入和transformers相比略微有些差别）
> 
> ```
> 视频中显示了一位年长的男子，他正在一个房间里整理床铺。他穿着白色的上衣和蓝色的裤子，正在将床单和枕头整理好。从视频中可以看出，他非常专注于手头的工作，动作显得有些匆忙。\n\n在视频的最后几秒钟，这位男子似乎在整理床铺时突然失去平衡，身体向前倾倒，最终摔倒在床上。他的动作显得有些笨拙，可能是因为年纪较大，身体反应不如年轻人灵敏。\n\n总的来说，视频中的男子正在整理床铺，但由于某种原因，他最终摔倒在床上。
> ```
> 
> #2292 [code.zip](https://github.com/user-attachments/files/16594181/code.zip)

@irexyc 我用了你的代码跑，确实是没问题的，然后我看了一下是因为你这个用的是pipeline推理，而我这边用的是openai的推理服务https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/multi_modal/api_server_vl.md，这两个结果之间是存在很大gap的。
1. 这个pipeline能否当作api来用？也就是一个server一个client的方式
2. 如果不可以，那openai的接口或者lmdeploy APIClient的接口如何可以和transformer&lmdeploy pipeline的结果保持一致呢？

**Comment by irexyc** [comment]
message 的结构就是openai的格式。你用openai的接口可能区别在于默认的sample参数，server默认的好像是40。我这里设置top_k=1来关掉sample行为。如果用openai接口的话，openai接口本身设置不了top_k，但是可以通过设置temperature=0.0来近似吧。

另外就是那个每个图片设置独立的max_dynamic_patch，需要改一下目前的代码，不然实现不了。

**Comment by zmf2022** [comment]
我用官方和上述提供的代码运行，结果都是没有摔倒，请问这是什么原因？

**Comment by sunnymoon155** [comment]
> k，但是可以

我正在根据你的代码进行修改，目前改了model和internvl里面的函数，但是有个疑问哈，test_internvl2_conv这个函数的作用是啥？我看没有地方调用呀

**Comment by irexyc** [comment]
@sunnymoon155

单元测试，验证模版正确性的，用户用不到这个。

**Comment by sunnymoon155** [comment]
> @sunnymoon155
> 
> 单元测试，验证模版正确性的，用户用不到这个。

@irexyc 修改了代码，现在比之前好很多了，谢谢大佬！close the issue!

**Comment by sunnymoon155** [comment]
> 我用官方和上述提供的代码运行，结果都是没有摔倒，请问这是什么原因？

你的prompt改几个试试，稍微引导一下跌倒或者摔倒

**Comment by Mrgengli** [comment]
@irexyc 您好，我想知道不管是在transforers还是lmdeploy的环境中，相同的输入，相同的模型，在sample都关掉的情况下，为什么会出现不同的结果呢？

**Comment by irexyc** [comment]
@irexyc 关掉sample的情况下，batch和非batch的layer的输出会有差别。

**Comment by Mrgengli** [comment]
@irexyc 您好，感谢你的回复，请问是什么层的输出会不同的呢？我看internvl的官方的推理代码中的image是这样处理的：
![image](https://github.com/user-attachments/assets/4be6d321-f971-46db-ac7d-1b8e1bbcfd0f)
但是我看https://github.com/InternLM/lmdeploy/blob/main/docs/en/multi_modal/internvl.md的给的使用的方法前面加上了
![image](https://github.com/user-attachments/assets/bd1e07c4-c607-4770-9809-719844c79c7a)
是不是前面加上么frame的原因，我看在internvl官方的代码前面没有加上frame

**Comment by irexyc** [comment]
@Mrgengli

同样的代码，关闭sample的情况下，我这边只有在batch非1的情况下，有概率出现结果不一样的情况。如果你本身batch为1，并且将结果不稳定的话，可以再开一个issue把你的代码，数据贴一下。

**Comment by Mrgengli** [comment]
@irexyc 您好，我这里跑的是batch不是1的情况，不是结果不稳定，而是输出的结果不一样。如果输入都是一样的，输出不一样的，这里应该是有一些问题的。sample关了的情况输出不可能不一样，如果有不一样，那就是那里有问题了。

**Comment by Mrgengli** [comment]
@irexyc lmdeploy的推理对精度应该是没有损失的

**Comment by irexyc** [comment]
@Mrgengli 

矩阵乘法在不同的batch下面，结果是不一样的。

**Comment by Mrgengli** [comment]
@irexyc 我刚刚在lmdeploy的环境中实验了一下batch为1和batch为100的情况，这两个的输出是一模一样的，但是和使用transformers的结果不一样。应该不是您说的问题

**Comment by Mrgengli** [comment]
@irexyc 您好，如果是因为batch的原因，batch 1 和100的输出应该是不一样的

**Comment by irexyc** [comment]
> 我想知道不管是在transforers还是lmdeploy的环境中，相同的输入，相同的模型，在sample都关掉的情况下，为什么会出现不同的结果呢？


@Mrgengli 

我们在用opencompass测精度的时候，如果batch不为1的话，每一次的指标都会有差异的。一次的结果不能说明问题，而且你最开始不是说了你的结果是有差别的吗？你可以试试不用batch的结果。

**Comment by nzomi** [comment]
@irexyc 开发者你好，我这边openai接口设置了temperature为0或者top_k为1.0，同一张图batch为1跑多轮，结果依旧略有差异。如果是用transformer，model.chat的推理方案，结果就相对稳定，有什么好的解决方案吗。
而且如您所说，多batch结果更是不同，同一张图复制k次，得到k个结果，可能都是互有差异的，这个涉及到计算精度的问题，也是没有解决方案么？

**Comment by irexyc** [comment]
@nzomi openai 接口如何传的参数呢？差异是怎样的，有多大？pytorch backend 有试过么，结果如何？

**Comment by nzomi** [comment]
@irexyc 感谢回复！extra_body和普通的形式都试过，差异还是挺大的，我是要求以json格式输出结果。pytorch backend我这边跑不通，没有试过，都是turbomind。同一张图我可能得到2-4个结果，取决于参数设置和推理结果：

1. 如果以extra_body的方式传参数，输出对象的数量和内容都可能不一样，可能会有四个不同结果ABCD，感觉参数没有传进去。
2. 如果以pipeline的方式推理，如果设置do_sample=False，总是输出结果A。
3. 如果以model.chat的方式推理，如果设置do_sample=False，总是输出结果B；A和B是微小的内容差异，对象个数是相同的。
4. 如果在外部传temperature这些参数，可能输出结果A或者B。
5. 如果openai+batch inference，batch为1的时候可能输出A和B，batch大于1几乎总是输出B。

结论是只有能设置do_sample=True的时候，能保证确定性，但是同参数下model.chat和pipeline推理结果不同，有微小的内容差异。如果是部署好以openai接口传参，结果又和之前的不一样了。

我用的lmdeploy是0.8.0，我保证了所有情况下的的max_dynamic_patch都是一样的，其他参数也是一样的，下面是我openai传参的方法和pipeline的推理方式，model.chat就是照着demo写的，只是改了max_dynamic_patch：
```
response = client.chat.completions.create(
    model=model_name,
    messages=[
        {'role': 'system', 'content': "xxx"},
        {
        'role':'user',
        'content': [{
            'type': 'text',
            'text': question,
        }, {
            'type': 'image_url',
            'image_url': {
                'url': f'data:image/jpeg;base64,{image_data}',
                'max_dynamic_patch': 16
            },
        }],
    }],
    # extra_body={
    #     "do_sample": False,
    #     "top_k": 1.0,    
    #     "temperature": 1.0,    
    # },
    temperature='0.0')


messages = [
    dict(role='user', content=[
        dict(type='text', text=f'{IMAGE_TOKEN}\n{question}'),
        dict(type='image_url', image_url=dict(max_dynamic_patch=16, url='xxx.png'))
    ])
]
out = pipe(messages, gen_config=GenerationConfig(max_new_tokens=2048), do_sample=False)`

**Comment by irexyc** [comment]
extra_body 只能设置这些参数 https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/serve/openai/protocol.py#L140-L151

chat.completions.create 中 temperature 参数是和 messages 同级的。

**Comment by nzomi** [comment]
@irexyc extra_body的参数设置感觉没有起到什么作用，即便top_k=1.0和chat.completions.create里的temperature是0.0，结果还是存在随机性。只要不能显示指定do_sample=True都不是deterministic，就反复在两个结果A,B间出现，这个现象会和模型本身有关么，我把模型专业化微调过了，每种类型的图片其实有着专属的prompt，但是上游处理的结果错了导致本该给a prompt的错误的给成b prompt，所以结果本身就不是对的，这是导致结果不稳定的原因吗？

不过也有另一个问题，model.chat 和 pipeline 同参数推理结果却不同有啥原因么，会和lmdeploy版本有关吗？

**Comment by irexyc** [comment]
@nzomi

> 不过也有另一个问题，model.chat 和 pipeline 同参数推理结果却不同有啥原因么，会和lmdeploy版本有关吗？

这个不能比较吧，引擎不一样，算子不一样。

> 只要不能显示指定do_sample=True都不是deterministic

这个我感觉有点困惑，do_sample=True 的情况下怎么结果就确定了呢。你可以把 log_level 打开，然后看下处理请求时打印的 GenerationConfig么。

**Comment by nzomi** [comment]
@irexyc 不好意思我笔误了，我想说的是do_sample=False时才能保证输出结果没啥随机性。我部署的服务打印出的日志结果可以看图，do_sample和topk都是默认值，只有temperature和max_tokens起作用了，是我extra_body的传参方式错了吗？还有我看了其它issue，说是7月份支持do_sample这个传参，现在是还没有支持吗？

<img width="1319" height="403" alt="Image" src="https://github.com/user-attachments/assets/7424e8e1-aaaf-468a-98a5-d60b28a6f526" />

```
params = {
    "messages": conversation_history,
    "model": self.model_main if self.current_service == 'main' else self.model_minor,
    "extra_body": {"top_k": 1.0, "seed": 10086},
    "temperature": 0.0,
    "max_tokens": self.config.params['max_tokens']
}
# params.update(self.config.params)
# params.update(kwargs)
timeout = aiohttp.ClientTimeout(total=210)
current_base = self.api_base if self.current_service == 'main' else self.api_base_minor
current_session = self.sessions[self.current_service]
try:
    async with current_session.post(
        f"{current_base}/chat/completions",
        json=params,
        headers={
            "Authorization": f"Bearer {self.api_key}",
            "Connection": "close"
        },
        timeout=timeout
    ) as response:
```

如果是下图这样的能够指定do_sample=False，结果就没有随机性。
<img width="1904" height="137" alt="Image" src="https://github.com/user-attachments/assets/1f3e7191-d6f8-4828-9220-1f1d0a7f091b" />

**Comment by irexyc** [comment]
@nzomi 

如果是用post，而不是openai 的client，你的params似乎有问题。我觉得应该把 extra_body 展平，类似这样

```
params = {
    "messages": conversation_history,
    "model": self.model_main if self.current_service == 'main' else self.model_minor,
    "top_k": 1,
    "max_tokens": 1024
}
```
