### ISSUE TITLE
minicpmv2.5部署报错

### ISSUE THREAD

**Issue by lyc728** [InternLM/lmdeploy#2267]
<img width="441" alt="企业微信截图_17231044128156" src="https://github.com/user-attachments/assets/3fe4b88d-0367-4bff-9aca-0ee6d586be02">
现在deploy环境是0.5.3

**Comment by irexyc** [comment]
只支持过这个模型 https://huggingface.co/openbmb/MiniCPM-Llama3-V-2_5

如果你的是这个模型的话，把文件夹名字改成 MiniCPM-Llama3-V-2_5

**Comment by lyc728** [comment]
我是自己微调的模型，名称中有这个，/swift/minicpm-v-v2_5-chat/v0-20240729-094453/checkpoint-1640-merged

**Comment by lyc728** [comment]
> 只支持过这个模型 https://huggingface.co/openbmb/MiniCPM-Llama3-V-2_5
> 
> 如果你的是这个模型的话，把文件夹名字改成 MiniCPM-Llama3-V-2_5

是可以了 但是这是个bug吧  我前面环境不是这个 也能运行的

**Comment by irexyc** [comment]
默认不显示指定对话模版（ChatTemplateConfig）是是按照文件夹名字命名的，你确定前面的文件夹也是这个名字吗？

**Comment by lyc728** [comment]
> 默认不显示指定对话模版（ChatTemplateConfig）是是按照文件夹名字命名的，你确定前面的文件夹也是这个名字吗？

是的
