### ISSUE TITLE
Qwen-VL 推理返回空文本

### ISSUE THREAD

**Issue by Liufeiran123** [InternLM/lmdeploy#2268]
代码如下：
from lmdeploy import pipeline, TurbomindEngineConfig, ChatTemplateConfig
from lmdeploy.vl import load_image

backend_config = TurbomindEngineConfig(cache_max_entry_count=0.2)
pipe = pipeline('./Qwen-VL-Chat', backend_config=backend_config, chat_template_config=ChatTemplateConfig(model_name='qwen'))

image = load_image('./demo.jpeg')
response = pipe(('这是什么', image))
print(response)

返回如下：
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
[WARNING] gemm_config.in is not found; using default GEMM algo
Response(text='', generate_token_len=-102744343, input_token_len=282, session_id=0, finish_reason='stop', token_ids=[], logprobs=None, index=0)

版本：
0.5.3
cuda -12.1
python 3.10

**Comment by irexyc** [comment]
打开日志看看呢

```
pipe = pipeline('./Qwen-VL-Chat', backend_config=backend_config, chat_template_config=ChatTemplateConfig(model_name='qwen'), log_level='DEBUG')
```

这个值有点奇怪，成负数了 `generate_token_len=-102744343`

**Comment by Liufeiran123** [comment]
有几个警告截图如下：
![微信图片编辑_20240809143208](https://github.com/user-attachments/assets/10998bfb-20cd-40e1-a25e-6401d069145b)
![Uploading 微信截图_20240809143327.png…]()

**Comment by irexyc** [comment]
<img width="847" alt="image" src="https://github.com/user-attachments/assets/8b1086ca-af9b-41f9-a509-cd278bf67f1b">


从二个截图来看是合理的，原因是显存不足无法分配kvcache造成的。

可以试下用lmdeploy自带的量化工具量化一下
https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/quantization/w4a16.md#%E6%A8%A1%E5%9E%8B%E9%87%8F%E5%8C%96


或者试试更小的模型，比如https://huggingface.co/internlm/internlm-xcomposer2-vl-1_8b

**Comment by Liufeiran123** [comment]
好的，明白了，应该是显存不足导致的问题。
