### ISSUE TITLE
请问一下国产显卡Ascend 910 and Hygon DCU Z100L等如何安装？

### ISSUE THREAD

**Issue by cgq0816** [InternLM/lmdeploy#2279]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

如题

### Reproduction

如题

### Environment

```Shell
如题
```

**Comment by lvhan028** [comment]
#2278 是关于 ascend 910的dockerfile，可以试用下
LMDeploy目前不支持Hygon芯片。
