### ISSUE TITLE
可以指定不同的compute compatibility编译吗

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#229]
![image](https://github.com/InternLM/lmdeploy/assets/6971044/cd7e1473-2e3d-413a-bf9f-de176b34be31)

我看dockerfile里cmake 编译选项里没有设置SM

**Comment by lvhan028** [comment]
可以。比如sm80，在上述命令中增加：
```
-DSM=80
-DCMAKE_CUDA_ARCHITECTURES=80
```
