### ISSUE TITLE
[Feature] multi-node training

### ISSUE THREAD

**Issue by taliq** [InternLM/lmdeploy#2300]
### Motivation

Hi all, really thanks for this wonderful repo.

I'm working on deploying LLM (Llama-3-8B-instruct) for each GPU (without tensor/pipeline parallel) on multi-node because I want to use the LLM output during training other models.
I also want to do offline batch inference because that is the fastest inference.
(e.g., if I have 2 nodes and 8 GPUs for each node then I want to run LLM for each GPU so a total of 16 LLMs)

I modified the repo a bit and it's working fine with the NODE 0 but in NODE 1, all forward go through GPU 0.
Can you help me with which code I have to modify?

**Comment by zhyncs** [comment]
I don't quite understand your request. If you are looking for training, you can check out https://github.com/InternLM/xtuner. LMDeploy is an inference framework that currently does not support multi-node or pipeline parallelism.

**Comment by lzhangzz** [comment]
@taliq Is this what you need?

https://lmdeploy.readthedocs.io/en/latest/llm/proxy_server.html
