### ISSUE TITLE
CPU offload when InternVL2-40B inference using lmdeploy.pipeline

### ISSUE THREAD

**Issue by ftgreat** [InternLM/lmdeploy#2306]
We prefer InternVL2-40B bf16 in one GPU of 80G. However CUDA memory is not sufficient. 
Through setting cache_max_entry_count to small ratio, we got RejectInvalidRequests.

Does lmdeploy.pipeline provide some CUDA memory settings like CPU offload? Thanks for your advice.

**Comment by lvhan028** [comment]
The memory footprint of `InternVL2-40B` is 80G. 
It cannot be fit into one 80G GPU unless you quantize it into low-bit weights, for instance, 4bit or 8bit. 
You may refer to [AWQ guide](https://lmdeploy.readthedocs.io/en/latest/quantization/w4a16.html) for 4bit weight quantization

LMDeploy hasn't CPU offload feature yet
