### ISSUE TITLE
[Bug] lmdeploy部署报错API call is not supported in the installed CUDA driver

### ISSUE THREAD

**Issue by 2013303386** [InternLM/lmdeploy#2311]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

lmdeploy部署InternVL2-8B报错API call is not supported in the installed CUDA driver

### Reproduction

from lmdeploy import pipeline, TurbomindEngineConfig, ChatTemplateConfig
from lmdeploy.vl import load_image

model = 'OpenGVLab/InternVL2-8B'
system_prompt = '我是书生·万象，英文名是InternVL，是由上海人工智能实验室、清华大学及多家合作单位联合开发的多模态大语言模型。'
chat_template_config = ChatTemplateConfig('internvl-internlm2')
chat_template_config.meta_instruction = system_prompt
pipe = pipeline(model, chat_template_config=chat_template_config,
                backend_config=TurbomindEngineConfig(session_len=8192))

image_urls=[
    "https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/demo/resources/human-pose.jpg",
    "https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/demo/resources/det.jpg"
]
prompts = [('describe this image', load_image(img_url)) for img_url in image_urls]
response = pipe(prompts)
print(response)

### Environment

```Shell
nvidia-smi
<img width="757" alt="image" src="https://github.com/user-attachments/assets/20d667c8-ce29-42ea-9b54-d70be67233e1">
lmdeploy 0.5.3+2.1+cu118
```

**Comment by lvhan028** [comment]
Kindly let us know your cuda driver information by running the command "nvidia-smi"

**Comment by 2013303386** [comment]
![nvidia-smi](https://github.com/user-attachments/assets/da130535-c3e4-487e-8112-19730c5e2b9c)

**Comment by 2013303386** [comment]
> Kindly let us know your cuda driver information by running the command "nvidia-smi"

![nvidia-smi](https://github.com/user-attachments/assets/7ceb696d-7039-4be0-9d0c-f5ba32a317a3)

**Comment by zhyncs** [comment]
At least, it requires CUDA 11.4, if I remember correctly. cc @lzhangzz

**Comment by lvhan028** [comment]
The driver version is too low. 
The minimum required cuda runtime is 11.3 and its corresponding driver version
From a long-term view, I recommend upgrading cuda runtime to 11.8 and the corresponding driver version to "520.61.05" at least

**Comment by 2013303386** [comment]
> The driver version is too low. The minimum required cuda runtime is 11.3 and its corresponding driver version From a long-term view, I recommend upgrading cuda runtime to 11.8 and the corresponding driver version to "520.61.05" at least

got it, I will try later, thanks!
