### ISSUE TITLE
[Bug] 一张卡上部署多个模型

### ISSUE THREAD

**Issue by jiangix-paper** [InternLM/lmdeploy#2314]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

请问lmdeploy支持在一张A100卡上部署多个模型吗？比如vllm中有一个参数是gpu-memory-utilization来控制每个模型占用的显存。lmdeploy是不是默认会把当前卡的显存占满呢

### Reproduction

nvidia A100 80G同时部署7B和20B模型

### Environment

```Shell
nvidia A100 80G
```

**Comment by lvhan028** [comment]
--cache-max-entry-count 控制内存占用比例

**Comment by jiangix-paper** [comment]
好的，感谢回复。有一个问题。我使用mindsearch的时候，同样的prompt，为什么lmdeploy生成的答案跟vllm生成的答案不一样呢？
<img width="856" alt="image" src="https://github.com/user-attachments/assets/d69c2a32-7e95-4fe6-9f6a-5fd22fb0e41f">
比如对于上图选择工具，按照prompt指引，调用工具前后应该会生成<|action_start|>和<|action_end|>。但是使用vllm部署无法生成，而lmdeploy部署就能生成

**Comment by lvhan028** [comment]
lmdeploy的实现方式和vllm不一样
vllm在应用对话模板时，应该没有考虑tools call功能。lmdeploy支持了 InternLM 模型的tools call能力
