### ISSUE TITLE
能否支持InternVL2-8B量化，有无相关文档

### ISSUE THREAD

**Issue by wuxianyess** [InternLM/lmdeploy#2318]
### Motivation

想用lmdeploy量化internvl2

**Comment by lvhan028** [comment]
https://lmdeploy.readthedocs.io/en/latest/quantization/w4a16.html

**Comment by QwertyJack** [comment]
这里有已经量化好的
https://huggingface.co/OpenGVLab/InternVL2-8B-AWQ

**Comment by lvhan028** [comment]
Closing since no more activities over weeks. Do not hesitate to reopen it if it is still an issue
