### ISSUE TITLE
About int8 inference. 

### ISSUE THREAD

**Issue by realgump** [InternLM/lmdeploy#232]
when using Fastertransformer backend, I can simply set `int8_mode=1` to enable int8 inference.  Is Turbomind backend support similar settings, besides the `kCacheKVInt8` and `WeightInt4`?

**Comment by lvhan028** [comment]
Hope https://github.com/InternLM/lmdeploy/blob/main/docs/en/w4a16.md can help you with int4-weight model deployment

**Comment by realgump** [comment]
Thanks for your quick reply for int4 quantization. However, is there a method to perform **int8 weight quantization**  like the int8_mode in fastertransformer backend https://github.com/triton-inference-server/fastertransformer_backend/tree/main, instead of doing data calibration？

**Comment by lzhangzz** [comment]
Quantizing the weights while loading them like FT is not supported. 

We use a more complex (and better performing) quantization algorithm compared to FT (which uses symmetric per vector RTN quantization for weight only int8 mode). The processing of weights is too complex to be maintained in C++.
