### ISSUE TITLE
Scale out llm model deployment across different machine gpu's

### ISSUE THREAD

**Issue by Dineshkumar-Anandan-ZS0367** [InternLM/lmdeploy#2320]
### Motivation

I am trying to deploy vllm model in my machine. But its takes 40gb worth of model loading and 4 gb worth of inference. But i have 24gb gpu slot in two different machines. I need to combine these two different machine gpu's for this model loading. 

Is this possible?

**Comment by lvhan028** [comment]
For vllm, may try `--tensor-parallel-size 2`
For lmdeploy, may try `--tp 2`

**Comment by Dineshkumar-Anandan-ZS0367** [comment]
Is able to contact two different nodes, two different machines for model load and inferencing

**Comment by lvhan028** [comment]
The pipeline parallelism is required. But LMDeploy doesn't support pipeline parallelism. 
You can try vLLM by following its official guide.

**Comment by Dineshkumar-Anandan-ZS0367** [comment]
Thanks a ton sir, I going forward to vLLM already.
