### ISSUE TITLE
[Feature] 能否在新版本中增加SM60级别的N卡适配

### ISSUE THREAD

**Issue by a793181018** [InternLM/lmdeploy#2322]
### Motivation

目前lmdeploy无法在sm60级别的n卡 P100上运行
请求项目组增加适配SM60的N卡支持，我可以提供sm60的N卡设备环境
QQ号：793181018 微信同号

**Comment by chuanzhubin** [comment]
黑皮总威武

**Comment by lvhan028** [comment]
SM60 is not in our plan yet.
