### ISSUE TITLE
部署 VLM 类 openai 服务，怎样支持并发

### ISSUE THREAD

**Issue by wssywh** [InternLM/lmdeploy#2327]
我使用lmdeploy部署了Internvl2模型，在使用的时候需要等待前一个问题回答完成后，模型才会处理下一个请求，请问下lmdeploy在部署的时候怎样支持并发？

部署的脚本为：
```
lmdeploy serve api_server /data/workspace/models/InternVL2-2B --server-port 23333 --tp 2 --cache-max-entry-count 0.5
```

**Comment by AllentDan** [comment]
设置下 --vision-max-batch-size 数。具体可以通过 `lmdeploy serve api_server -h` 查看

**Comment by wssywh** [comment]
设置这个参数也不起作用，默认是在排队，只有等第一个回答完了，才开始处理第二个问题

**Comment by wssywh** [comment]
@AllentDan 设置这个参数也不起作用，默认是在排队，只有等第一个回答完了，才开始处理第二个问题

**Comment by wssywh** [comment]
可以了，感谢 @AllentDan

**Comment by zzjchen** [comment]
请问，如果我有多个线程同时调用一个lmdeploy的internvl2服务（message不一样），前面说的设置完server是自动并发处理还是需要我把所有message整合起来作为一个batch一起调用才能并发？

**Comment by AllentDan** [comment]
自动并发

**Comment by Yidian-zyw** [comment]
请问支持单问题多图片输入吗

**Comment by AllentDan** [comment]
取决于模型

**Comment by Yidian-zyw** [comment]
@AllentDan 如果模型支持的话，在类openai服务中客户端应该怎么配置

**Comment by Yidian-zyw** [comment]
@AllentDan 找到啦，多谢🙏
