### ISSUE TITLE
[Bug] qwenvl 多模态批处理，结果和单batch不能对齐

### ISSUE THREAD

**Issue by huwwds** [InternLM/lmdeploy#2330]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

请教下，多模态批处理，想处理以下的场景：对不同图，同一个prompt重复多次。
实际测试部分图片和单batch结果不能对齐，batch数越大，diff图片数量越大

### Reproduction

import logging
import os
import os.path as osp
import time, math, json
import sys

sys.path.insert(0, "")
from tqdm import tqdm

from lmdeploy import pipeline, ChatTemplateConfig, GenerationConfig, TurbomindEngineConfig
from lmdeploy.vl import load_image

if __name__ == '__main__':
    model_path = ""
    img_dir = ''

    batch_size = 32
    pipe = pipeline(model_path, chat_template_config=ChatTemplateConfig('qwen'), log_level='ERROR',
                    backend_config=TurbomindEngineConfig(
                        model_format='hf', cache_max_entry_count='0.4', session_len=8192 * 2, max_batch_size=batch_size,
                        enable_prefix_caching=True, use_logn_attn=True,
                    ))

    print("start pred...")
    files = os.listdir(img_dir)
    num_files = len(files)
    num_batch = math.ceil(num_files // batch_size)
    res, total_time = [], []
    for i in range(32 // batch_size):
        start_idx = i * batch_size
        end_idx = min((i + 1) * batch_size, num_files)

        print("==================>process {} to {}".format(start_idx, end_idx))
        sample_fnames = files[start_idx: end_idx]
        batch_input = []
        for file in sample_fnames:
            img_path = osp.join(img_dir, file)
            image = load_image(img_path)
            batch_input.append(('将图片的文本内容转化为html输出', image))
        start_time = time.time()
        response = pipe(
            batch_input,
            gen_config=GenerationConfig(max_new_tokens=8192)
        )
        end_time = time.time()
        print(f"=============>>>> cost_time:{end_time - start_time}")
        total_time.append(end_time - start_time)
        # write res
        for idx, v in enumerate(response):
            file_name = sample_fnames[idx]
            c_response = v
            res.append({"file": file_name, "text": c_response.text, "token_len": c_response.generate_token_len})

    print("avg cost_time:{}".format(sum(total_time) / 32))
    f = open("result_bs32-0.4.txt", 'w')
    for v in res:
        f.write(json.dumps(v, ensure_ascii=False) + '\n')
    f.close()

### Environment

```Shell
sys.platform: linux
Python: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: Tesla V100-SXM2-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: gcc (GCC) 8.2.0
PyTorch: 2.2.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.6  (built against CUDA 11.8)
    - Built with CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

TorchVision: 0.17.2+cu121
LMDeploy: 0.5.2.post1+
transformers: 4.43.4
gradio: Not Found
fastapi: 0.112.0
pydantic: 2.8.2
triton: 2.2.0
NVIDIA Topology: 
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    CPU Affinity    NUMA Affinity
GPU0     X      NV2     NV1     NV2     NV1     NODE    NODE    NODE    NODE    0-19    0
GPU1    NV2      X      NV1     NV1     NODE    NV2     NODE    NODE    NODE    0-19    0
GPU2    NV1     NV1      X      NV2     NODE    NODE    NV2     NODE    NODE    0-19    0
GPU3    NV2     NV1     NV2      X      NODE    NODE    NODE    NV1     NODE    0-19    0
GPU4    NV1     NODE    NODE    NODE     X      NV2     NV1     NV2     NODE    0-19    0
GPU5    NODE    NV2     NODE    NODE    NV2      X      NV1     NV1     NODE    0-19    0
GPU6    NODE    NODE    NV2     NODE    NV1     NV1      X      NV2     NODE    0-19    0
GPU7    NODE    NODE    NODE    NV1     NV2     NV1     NV2      X      NODE    0-19    0
NIC0    NODE    NODE    NODE    NODE    NODE    NODE    NODE    NODE     X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
```

**Comment by lvhan028** [comment]
正常现象。毕竟批处理的shape和单batch不一样，而计算的kernel和shape相关
