### ISSUE TITLE
[Bug] 两个人一起请求结束后，显存不会释放

### ISSUE THREAD

**Issue by chailt** [InternLM/lmdeploy#235]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

当我开启web服务后，两人同时请求后，显存没有释放，直到显存爆炸
[TM][ERROR] CUDA runtime error: invalid argument /opt/tritonserver/lmdeploy/src/turbomind/models/llama/LlamaBatch.cc:693
正常情况下
![1692067610090](https://github.com/InternLM/lmdeploy/assets/128781283/3b638609-3200-46c6-a2c8-062fd379a5ec)
两人同时请求后
![image](https://github.com/InternLM/lmdeploy/assets/128781283/13fcb5c6-4de8-4feb-8e59-c16204332cba)

### Reproduction

bash workspace/service_docker_up.sh
python3 -m lmdeploy.app 0.0.0.0:33337

**Comment by lvhan028** [comment]
lmdeploy的推理是interactive mode方式。缓存不会释放的，除非主动调用`end`

**Comment by Xu-Chen** [comment]
@lvhan028 是否考虑加一个参数来释放？很多业务场景是一次性的输入和输出

**Comment by lvhan028** [comment]
调用stream_infer的时候，试试把sequence_end改成True。

**Comment by chailt** [comment]
您的这个操作相当于多轮数据改变为单轮，但是仍然会出现显存爆炸的情况

**Comment by chailt** [comment]
> 调用stream_infer的时候，试试把sequence_end改成True。

您好还有一个问题，刚看到更新了openai方式的pai接口，实现的过程中有报错
![image](https://github.com/InternLM/lmdeploy/assets/128781283/19c3f8b7-0ae6-4b2a-8b77-a69033976893)

**Comment by lvhan028** [comment]
频繁的开辟释放缓存容易造成memory碎片化。对性能有损害。
针对显存爆炸的情况，麻烦提供一下复现路径吧
