### ISSUE TITLE
support for flash attention

### ISSUE THREAD

**Issue by sleepwalker2017** [InternLM/lmdeploy#237]
Does lmdeploy flash attention？
In the past few days, I looked through the implementation of FT and found that the kernel of flash attention in the 3rd_party directory is only used in the Prefill phase. In the decoding phase, this kernel will not be executed, but a masked_multihead_attention_kernel will be executed.

这几天翻了翻 FT 的实现，发现只有在 Prefill 阶段才会使用3rd_party目录里的flash attention的 kernel。在 decoding 阶段，不会执行这个 kernel，而是执行一个 masked_multihead_attention_kernel。

请问你们是否了解这两个 kernel 的差异，以及为什么会这样做，感谢

**Comment by grimoire** [comment]
3rd_party 里的 flash attention 是指 https://github.com/NVIDIA/FasterTransformer/tree/main/3rdparty/trt_fused_multihead_attention 吗？解读编译好的 cubin 有点困难（哪怕是能够反编译回 ptx 也很难）。所以我只能就我的一些推测和你讨论
prefill 阶段和 decoding 阶段一个比较大的差别是 seq length。对于 seq length 比较长的 prefill 阶段，可以用 TensorCore 对 mma 进行加速；但是对于 seq length = 1 的 decoding，使用 TensorCore 可能会导致更多的资源浪费（比如更多寄存器以保存 fragment），因此 masked_multihead_attention_kernel 会使用[更简单的方法](https://github.com/NVIDIA/FasterTransformer/blob/f8e42aac45815c5be92c0915b12b9a6652386e8c/src/fastertransformer/kernels/decoder_masked_multihead_attention/decoder_masked_multihead_attention_template.hpp#L596)进行向量矩阵乘计算。

另外我有几个小建议：
1. 考虑到你的问题是关于 FT 的，也许直接与他们的开发者讨论能得到更准确的答案。（当然我们非常也欢迎讨论，可以在 https://github.com/InternLM/lmdeploy/discussions 里建立一个 duscussion）
2. 希望 issue 中尽量使用英语，这样非中文母语的朋友也可以通过 issue 检索到问题，或者给出帮助建议

**Comment by sleepwalker2017** [comment]
> 

I added the question for English version.

The FT project seems abandoned, NVIDIA will give their TRT-LLM project to replace this.

Thank you! We'll try out this repo for LLAMA inference.

**Comment by Xu-Chen** [comment]
@sleepwalker2017 
TRT-LLM?
