### ISSUE TITLE
[Bug] model format is "gptq" but group_size is 32. Currently, only 128 is supported

### ISSUE THREAD

**Issue by maxin9966** [InternLM/lmdeploy#2379]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

Aug 26 19:07:41 ubuntu22lts systemd[1]: Started Uvicorn server for my app.
Aug 26 19:07:46 ubuntu22lts bash[107697]: Traceback (most recent call last):
Aug 26 19:07:46 ubuntu22lts bash[107697]:   File "/home/ma/miniconda3/envs/lmdeploy/bin/lmdeploy", line 8, in <module>
Aug 26 19:07:46 ubuntu22lts bash[107697]:     sys.exit(run())
Aug 26 19:07:46 ubuntu22lts bash[107697]:   File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/cli/entrypoint.py", line 36, in run
Aug 26 19:07:46 ubuntu22lts bash[107697]:     args.run(args)
Aug 26 19:07:46 ubuntu22lts bash[107697]:   File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/cli/serve.py", line 281, in api_server
Aug 26 19:07:46 ubuntu22lts bash[107697]:     run_api_server(args.model_path,
Aug 26 19:07:46 ubuntu22lts bash[107697]:   File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/serve/openai/api_server.py", line 991, in serve
Aug 26 19:07:46 ubuntu22lts bash[107697]:     VariableInterface.async_engine = pipeline_class(
Aug 26 19:07:46 ubuntu22lts bash[107697]:   File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 155, in __init__
Aug 26 19:07:46 ubuntu22lts bash[107697]:     self._build_turbomind(model_path=model_path,
Aug 26 19:07:46 ubuntu22lts bash[107697]:   File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 198, in _build_turbomind
Aug 26 19:07:46 ubuntu22lts bash[107697]:     self.engine = tm.TurboMind.from_pretrained(
Aug 26 19:07:46 ubuntu22lts bash[107697]:   File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 286, in from_pretrained
Aug 26 19:07:46 ubuntu22lts bash[107697]:     return cls(model_path=pretrained_model_name_or_path,
Aug 26 19:07:46 ubuntu22lts bash[107697]:   File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 102, in __init__
Aug 26 19:07:46 ubuntu22lts bash[107697]:     self.model_comm = self._from_hf(model_source=model_source,
Aug 26 19:07:46 ubuntu22lts bash[107697]:   File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 183, in _from_hf
Aug 26 19:07:46 ubuntu22lts bash[107697]:     tm_model = get_tm_model(model_path, self.model_name,
Aug 26 19:07:46 ubuntu22lts bash[107697]:   File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/converter.py", line 236, in get_tm_model
Aug 26 19:07:46 ubuntu22lts bash[107697]:     assert group_size == 128, \
Aug 26 19:07:46 ubuntu22lts bash[107697]: AssertionError: model format is "gptq" but group_size is 32. Currently, only 128 is supported

### Reproduction

1

### Environment

```Shell
1
```

**Comment by maxin9966** [comment]
AssertionError: model format is "gptq" but group_size is 64. Currently, only 128 is supported

**Comment by lvhan028** [comment]
As the log indicates, LMDeploy only supports quantized model with `group_size` 128
