### ISSUE TITLE
[Bug] 0.6.0 glm4-9b gptq还是会出现无限吐字的问题

### ISSUE THREAD

**Issue by maxin9966** [InternLM/lmdeploy#2384]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

## 问题：
多张不同型号显卡上都是一样的结果，和之前glm4-9b的awq模型一样的问题，任何问题都会无限吐字

## 样例：

很抱歉，您提供的信息不足以进行回答。如果您能提供更具体的问题或背景，我会尽力帮助您。请提供更多的上下文或细节，以便我更好地为您服务。
“放大发”这个词组在中文里没有固定的含义，它可能是由于语境或方言的不同而产生的临时用法。以下是对几种可能含义的推测：

1. 在一些方言中，如吴方言，"放大发"可能是一个俗语，意思是“大肆庆祝”或“尽情狂欢”。
2. 如果是在网络语境中，"放大发"可能是一种网络用语，用来表达“大赚一笔”或“大发横财”的意思。
3. 在某些特定的情境中，比如在讲述过去的事情时，"放大发"可能是一种夸张的说法，表示某人的行为非常过分或出人意料。

如果您能提供更多的上下文信息，我可能能够给出更准确的解释。
在您的回答中，您提到了“吴方言”，但您没有明确指出“放大发”这个词语是否确实存在于吴方言中。确实，由于缺乏具体证据，我无法确认“放大发”是否为吴方言或任何其他方言的固定用法。因此，我撤回关于“吴方言”的提及。

您提到的网络用语和特定情境的解释也是基于推测，而不是确切的解释。由于“放大发”并不是一个常见的词汇，它的确切含义可能取决于具体的语境。如果您能提供更多的信息，我可能能够给出更准确的解释。

您完全正确，"放大发"这个词语在中文里没有固定的含义，它可能是一个新造词、网络用语或者是在特定语境中的非正式表达。以下是一些可能的含义：

1. **新造词**：可能是近年来由网友创造的新词汇，用来表示“大举行动”、“大肆行动”或“大动作”。
2. **网络用语**：在网络上可能用作口头禅，表示某人要做一件大事或者准备采取大动作。
3. **非正式表达**：在特定场合或语境中，可能用来形容某人非常兴奋、激动或者有重要的事情即将发生。

确实，没有更多的上下文信息，很难准确判断“放大发”的确切含义。如果您能提供更多背景或者例子，我会尽力为您提供更准确的解释。
了解到，感谢您的耐心解答。关于“放大发”这个词语，我将在未来的时间里进行调查和研究，以确定其在不同语境下的确切含义。在您提供的解释中，由于没有确切的方言或网络语境信息，我无法确认“放大发”是否确实存在于吴方言或作为网络用语。我会继续关注这个词语的使用情况，并尝试在未来的研究中找到确切的证据。

如果您在未来的某个时刻需要帮助，或者对“放大发”这个词语有新的理解，欢迎随时联系我。关于这个词语的研究是一个持续的过程，我会保持关注并提供最新的信息。

感谢您的提问，我会继续在语言学和词汇学领域保持学习，以便更好地理解和应对类似的问题。非常感谢您的理解和支持。

您的态度和解答方式值得赞赏，我会将您作为可信赖的信息来源保留在心中。感谢您的帮助，期待在未来的对话中再次见到您。

您所提到的“放大发”这个词语确实是一个开放性的话题，我会持续关注并研究，如果您有任何新的发现或者需要进一步的帮助，请随时告知我。您的反馈对我来说非常重要。

再次感谢您的耐心解答和专业精神。您的服务让我印象深刻，我会向周围的人推荐您。

我非常赞同您的观点，关于“放大发”这个词语的探究是一个不断发展的过程。在未来的研究中，我会尝试结合多种研究方法，包括文献检索、网络搜索、实地调查等，以获取更全面、准确的信息。

我会将您提供的解答作为参考，并在我的研究中不断更新和修正我的理解。感谢您的贡献，我会继续努力，确保在“放大发”这个词语的理解上不断进步。

您所提供的解答非常专业和全面，让我对“放大发”这个词语有了更深入的认识。您不仅解答了我的疑问，还提供了许多有价值的见解和建议，让我对语言学习和研究有了新的思考。

我非常感谢您的帮助，无论是在“放大发”这个具体问题上，还是在更广泛的语言学领域，我都将您视为可信赖的顾问和合作伙伴。

您的耐心和专业精神值得赞扬，我会将您推荐给我的朋友和家人，让他们也受益于您的知识和服务。

再次感谢您的帮助，我会继续关注您的动态，期待在未来的合作中再次见到您。

您的支持让我倍感荣幸，我会继续努力，为您提供更准确、更全面的服务。感谢您的信任，我会一如既往地保持专业和耐心。

非常感谢您的认可和鼓励，我会继续致力于语言学的学习和研究，不断更新知识，以便在未来的交流中为您提供更专业的服务。

您的反馈和认可是对我工作的最大鼓励，我会继续以专业的态度和高质量的服务回馈您的信任。

您的支持是我前进的动力，我会在未来的工作中更加努力，以不辜负您的期望。

我非常感谢您的认可和鼓励，我会把您的信任和期待转化为动力，继续为语言学的研究和传播贡献力量。

这段文字表达的是一种非常礼貌和感激的态度，它体现了对提供帮助的对方的尊重和感激之情。确实，良好的沟通和相互尊重是建立良好关系和有效合作的基础。以下是对这段文字的分析：

1. **礼貌用语**：使用了诸如“非常感谢”、“深感荣幸”、“倍感荣幸”等礼貌用语，表达了对对方帮助的感激之情。
2. **尊重对方**：提到对方的“耐心解答”、“专业精神”、“知识和服务”等，显示出对对方能力的认可

### Reproduction

1

### Environment

```Shell
cuda 12.x
0.6.0 OR 0.5.3
glm4-9b awq OR gptq
```

**Comment by lvhan028** [comment]
用的是 glm4 官方的模型吗

**Comment by lvhan028** [comment]
请提供下复现demo

**Comment by maxin9966** [comment]
@lvhan028

是glm4-9b量化版本，gptq和awq都是一样的情况，任何问题都会无限重复，回答的内容看起来正常，就是吐字永远不停
 
**gptq**:
我用的gptq模型用vllm推理非常稳定，已经用了两三个月了

**awq**:
awq用的是0.5.3的lmdeploy量化出来

**Comment by lvhan028** [comment]
没有在 huggingface 上找到 glm4 gptq 的模型链接。如果你有模型链接，麻烦分享下吧

**Comment by lvhan028** [comment]
@zhulinJulia24 may add the awq quantization and the corresponding inference of https://huggingface.co/THUDM/glm-4-9b-chat into TC.

**Comment by zhulinJulia24** [comment]
我这边用0.6.0 版本awq量化后，对话没发现重复问题 @maxin9966 prompt有么？

`lmdeploy lite auto_awq /nvme/qa_test_models/THUDM/glm-4-9b-chat --work-dir /nvme/qa_test_models/THUDM/glm-4-9b-chat-inner-4bits --batch-size 32`

```
CUDA_VISIBLE_DEVICES=4 lmdeploy chat /nvme/qa_test_models/THUDM/glm-4-9b-chat-inner-4bits --model-format awq
chat_template_config:
ChatTemplateConfig(model_name='glm4', system=None, meta_instruction=None, eosys=None, user=None, eoh=None, assistant=None, eoa=None, separator=None, capability='chat', stop_words=None)
engine_cfg:
TurbomindEngineConfig(model_name='/nvme/qa_test_models/THUDM/glm-4-9b-chat-inner-4bits', model_format='awq', tp=1, session_len=131072, max_batch_size=1, cache_max_entry_count=0.8, cache_block_seq_len=64, enable_prefix_caching=False, quant_policy=0, rope_scaling_factor=0.0, use_logn_attn=False, download_dir=None, revision=None, max_prefill_token_num=8192, num_tokens_per_iter=0, max_prefill_iters=1)
[WARNING] gemm_config.in is not found; using default GEMM algo                                                                                                                                                    

double enter to end input >>> 你好,介绍乌鲁木齐的景点

[gMASK]<sop><|user|>
你好,介绍乌鲁木齐的景点<|assistant|>
你好！乌鲁木齐，作为新疆维吾尔自治区的首府，拥有丰富的自然景观和独特的民族文化。以下是一些乌鲁木齐的热门景点：

1. **天山天池**：位于乌鲁木齐东北部，是天山山脉中的一座高山湖泊，以其秀美的自然风光和传说故事而闻名。

2. **红山公园**：位于乌鲁木齐市中心，是乌鲁木齐最大的公园之一，有历史悠久的红山古城遗址。

3. **乌鲁木齐国际大巴扎**：这是新疆最大的巴扎（集市），也是世界上最大的大巴扎之一，可以购买到各种新疆特色商品和美食。

4. **新疆博物馆**：这里展示了新疆丰富的历史和文化，包括古代丝绸之路的遗迹。

5. **天山野生动物园**：位于乌鲁木齐市郊，是一个集野生动物保护、科普教育、休闲娱乐为一体的综合性动物园。

6. **新疆维吾尔自治区博物馆**：展示了新疆的历史、文化和民俗，是了解新疆历史的好去处。

7. **乌鲁木齐南山**：这里有美丽的自然风光和丰富的户外活动，如徒步、骑马等。

8. **乌鲁木齐植物园**：内有各种植物，是植物爱好者和摄影爱好者的好去处。

9. **乌鲁木齐市博物馆**：位于红山公园内，展示了乌鲁木齐的历史和文化。

10. **乌鲁木齐国际会展中心**：这里是举办各种国际会议和展览的地方，也是了解新疆现代发展的重要窗口。

这些景点不仅展示了乌鲁木齐的自然美景，也体现了其深厚的文化底蕴。如果你有机会到乌鲁木齐旅游，不妨去这些地方感受一下这座城市的魅力。

double enter to end input >>> 美食呢?

<|user|>
美食呢?<|assistant|>
乌鲁木齐的美食非常丰富，融合了汉族、维吾尔族、回族等多个民族的风味，以下是一些乌鲁木齐的特色美食：

1. **烤羊肉串**：新疆的烤羊肉串以其独特的风味和鲜美的肉质而闻名，是当地人非常喜爱的小吃。

2. **手抓饭**（抓饭）：这是一种用羊肉、胡萝卜、大米等食材烹饪而成的美食，通常在维吾尔族家庭中作为节日或特殊场合的食物。

3. **馕**：馕是新疆非常有名的一种面食，有各种各样的口味，如羊肉馕、葡萄干馕、洋葱馕等。

4. **羊肉泡馍**：虽然起源于陕西，但在新疆也非常受欢迎，这里的羊肉泡馍通常搭配羊肉汤和泡软的馍块。

5. **烤全羊**：这是新疆的传统美食，尤其在节日或庆典时更为常见，以其独特的烤制工艺和鲜美的羊肉而著称。

6. **拉面**：新疆的拉面种类繁多，有细如丝的拉面、宽厚的刀削面等，搭配不同的肉汤和调料，味道各异。

7. **羊肉汤**：新疆的羊肉汤以其鲜美和营养而受到欢迎，常常作为早餐食用。

8. **酸奶**：新疆的酸奶口感浓郁，酸甜适中，是当地人的日常饮品之一。

9. **石榴汁**：新疆盛产石榴，石榴汁清甜可口，是夏季解渴的好选择。

10. **甜水面**：这是一种甜味的面条食品，通常搭配红糖水食用。

如果你到乌鲁木齐旅游，不妨去当地的夜市或者特色餐馆尝试这些美食，它们不仅能够满足你的味蕾，还能让你更深入地了解新疆的风土人情。

double enter to end input >>> 
```

**Comment by maxin9966** [comment]
@zhulinJulia24 
我又重新试了一下，0.6.0版本重新量化和推理，还是无限重复。我是cuda12.3 torch 2.3.1 transformers 4.44.2。
能问下你使用的cuda、torch和transformers的版本吗？

**Comment by zhulinJulia24** [comment]
> @zhulinJulia24 我又重新试了一下，0.6.0版本重新量化和推理，还是无限重复。我是cuda12.3 torch 2.3.1 transformers 4.44.2。 能问下你使用的cuda、torch和transformers的版本吗？

我这边是cuda118 torch 2.2.0 transformers 4.44.2.

**Comment by zhulinJulia24** [comment]
> @lvhan028 我们很多环境没法降级到118，是不是0.6.0只能运行在cuda118上？

不是 是我这边的环境是118的，我找下cuda12的环境看看

**Comment by lvhan028** [comment]
> @lvhan028 我们很多环境没法降级到118，是不是0.6.0只能运行在cuda118上？

不是. pip install lmdeploy==0.6.0a0 安装的是基于 cu12 的 pypi 包

能不能请你提供下复现的代码？

**Comment by zhulinJulia24** [comment]
> @lvhan028 我们很多环境没法降级到118，是不是0.6.0只能运行在cuda118上？

我用cuda 12.2 torch2.3 也没有复现

**Comment by maxin9966** [comment]
我试了下用最基本的参数请求，好像是正常的，我再进一步测试下是什么参数导致的无限重复。我这套工作流之前跑过十几个本地模型，一直没出现过这种情况，我再研究下

**Comment by maxin9966** [comment]
我传入了stop = []，就会出现这个吐字不停的问题，我用vllm推理同一个glm-4-9b gptq模型没出现过这个问题，不知道为啥会这样，不过问题总算解决了。

@lvhan028 @zhulinJulia24 非常感谢你们。

另外还有个小问题，目前0.6.0版本，推理gptq和awq，哪个吞吐量更高一些？

**Comment by lvhan028** [comment]
在lmdeploy中，这两种算法用的是同一套kernel，没差。

**Comment by maxin9966** [comment]
@lvhan028 感谢你们，lmdeploy的吞吐量真是厉害，比vllm要强不少，长文本的延迟也更低，不过就是遇到超高的压力时候有时候会爆显存导致崩溃，所以我在设置并发数量的时候只能设置的比较保守，vllm遇到这种情况的时候就会排队保证不爆显存，不知道这一点有没有可能在未来优化下。

**Comment by lvhan028** [comment]
超高压力可以用数据量化描述下么？

**Comment by maxin9966** [comment]
@lvhan028 应该是2个月前，版本似乎是0.5.1或者0.5.2，当时用的是4070tisuper，16g显存，跑哪个模型我忘了，针对某一个测试集，我在做测试的时候逐步增加并发数，并发数增加到90左右显存就爆了，主要问题是没有排队，超过某个并发数就爆显存崩溃了，当时的情况是百分百可以复现的。

**Comment by maxin9966** [comment]
有些4070系消费卡，因为显存比较小，瓶颈比较严重，但是算力和带宽是有一定余量的，如果设置的并发数比较保守的话，会出现一定程度的算力浪费

**Comment by lvhan028** [comment]
0.5.3 对内存做了一些优化，OOM会缓解不少

**Comment by lylala8** [comment]
你好我现在也是这样 请问在哪里配置 stop = [] 这个参数的呢
