### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by xiaoajie738** [InternLM/lmdeploy#2392]
Can the models deployed by llmdeploy support gRPC access? Thank you for taking the time to answer despite your busy schedule.

**Comment by lvhan028** [comment]
Our current plan doesn't include the support for gRPC interfaces.
Would you mind sharing the motivation of using gPRC instead of RESTful API?

**Comment by lvhan028** [comment]
Closing it since no more activities over 3 weeks. Feel free to reopen it if it is still an issue
