### ISSUE TITLE
[Feature] InternVL2 inference is slower than InternLM-Xcomposer2

### ISSUE THREAD

**Issue by zhaoning1987** [InternLM/lmdeploy#2393]
### Motivation

InternVL2 seems having better understanding of images than InternLM-Xcomposer2 according to both the official announcement and also out tests.
But the throughput of InternVL2 is basically 40% of the one of InternLM-Xcomposer2. Is it because of the structure of the model which is costly, or is there any chance that InternVL2 can speed up and run as fast as InternLM-Xcomposer2?

Engine: Turbomind

**Comment by irexyc** [comment]
Xcomposer2 和 大部分 InternVL2 模型的llm部分用的都是internlm，xcomposer2 有plora结构无法合并，导致 mlp 的部分计算量会多一些，所以就llm部分而言，internvl2应该是快于xcomposer2的。

慢的原因可能在于vit的部分，这部分要减少耗时的话，最简单的方式是减少图片的patch数量，不过可能会影响部分场景下的性能。https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/multi_modal/internvl.md （参考 max_dynamic_patch 的设置)

**Comment by zhaoning1987** [comment]
> Xcomposer2 和 大部分 InternVL2 模型的llm部分用的都是internlm，xcomposer2 有plora结构无法合并，导致 mlp 的部分计算量会多一些，所以就llm部分而言，internvl2应该是快于xcomposer2的。
> 
> 慢的原因可能在于vit的部分，这部分要减少耗时的话，最简单的方式是减少图片的patch数量，不过可能会影响部分场景下的性能。https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/multi_modal/internvl.md （参考 max_dynamic_patch 的设置)

了解，THX @irexyc
