### ISSUE TITLE
[Feature] 增加对于虚拟内存的缓冲时间

### ISSUE THREAD

**Issue by NB-Group** [InternLM/lmdeploy#2394]
### Motivation

我在 Windows 下使用 Turbomind 部署 Yi-34B-int4 模型时，由于机器较小的物理内存无法直接部署，遂分配了70G的虚拟内存以运行该模型。

然而，在代码运行至 turbomind.py:251 `self._create_weight(model_comm)`  时，会在虚拟内存中申请并填充约 30G 的空间，远大于磁盘读写速度，而且运行此操作是非堵塞的，继而在下一步时导致错误。模型推理时也存在同样的问题。

我建议增加一个可选参数，启用后在适当的位置等待一段时间，具体可以用模型大小和磁盘读写速度来估算。

**Comment by NB-Group** [comment]
ok，感谢回复

**Comment by NB-Group** [comment]
我用transformers进行的重新保存，成功拆分了，但是报错“No module named 'triton'”，关键是这个库就没有Windows版。。

![image](https://github.com/user-attachments/assets/5d1ea030-f16b-44f2-966d-3c4c5ba66aca)

**Comment by irexyc** [comment]
@NB-Group 是用的lmdeploy serve 命令么？我印象中貌似最近遇到了类似的问题，我检查一下。如果用pipeline可以加载么？

**Comment by NB-Group** [comment]
我是直接使用pipeline的。

pipe = pipeline(MODEL_DIR, backend_config=backend_config)

**Comment by irexyc** [comment]
@NB-Group 

我试了一下，如果是用 turbomind 后端的话，不会做 trition 检查的。报这个错应该是 fallback 到了 pytorch 后端。

你可以将日志打开，然后看一下打印的信息，pipeline 的是可以这样 `pipe = pipeline('...', log_level='INFO')` ，server 的话可以 `lmdeploy serve api_server xxx --log-level INFO`

**Comment by NB-Group** [comment]
好像找到原因了，但是不知道怎么解决：
```
2024-08-30 11:19:15,823 - lmdeploy - WARNING - Try to run with pytorch engine because `D:/AI_model/Yi-34B-Chat-4bits-subbed/` is not explicitly supported by lmdeploy. 
````

**Comment by irexyc** [comment]
D:/AI_model/Yi-34B-Chat-4bits-subbed/ 这个是你重新保存的模型么？

你可以看一下，config.json 是否与之前一样，权重 index.json 文件与之前文件相比，keys 是否一致。

**Comment by NB-Group** [comment]
嗯，源文件的index.json的keys里是pytorch的.bin格式的文件
`pytorch_model-00001-of-00002.bin`
而我保存的是transformers的`.safetensors`格式。

**Comment by NB-Group** [comment]
哦哦，人傻了key和value看反了。
新文件的keys里丢了一些key，`lm_head.weight`没了，`model.norm.weight`变成了`norm.weight`

transformers 推理是推理完了，但是输出了一坨乱码
```
^*\\став；财产cia к；财产perturbativestead
```
([使用官方仓库的演示代码](https://github.com/01-ai/Yi?tab=readme-ov-file#perform-inference-with-yi-chat-model))

**Comment by NB-Group** [comment]
@irexyc 这是我用来保存的代码。
```python
import os
from transformers import AutoModel, AutoTokenizer

model_name = "D:/AI_model/Yi-34B-Chat-4bits/"
model = AutoModel.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

output_dir = "D:/AI_model/Yi-34B-Chat-4bits-subbed"
os.makedirs(output_dir, exist_ok=True)

model.save_pretrained(output_dir, max_shard_size="2GB")
tokenizer.save_pretrained(output_dir)
```

**Comment by NB-Group** [comment]
@irexyc 我在`AutoModel.from_pretrained`加上了`torch_dtype='auto'`参数并重新进行了拆分，后成功加载和推理，谢谢你！
