### ISSUE TITLE
支持量化模型推理吗？

### ISSUE THREAD

**Issue by xxm1668** [InternLM/lmdeploy#240]
### 📚 The doc issue

支持量化模型推理吗？

### Suggest a potential alternative/fix

支持量化模型推理吗？

**Comment by lvhan028** [comment]
支持。可以参考这里：
https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/w4a16.md

文档里有处错误，要安装 lmdeploy v0.0.5
