### ISSUE TITLE
[Bug] When using DeepSeek-VL-7B, there is an error raised, because its config doesn't have 'hidden_size'.

### ISSUE THREAD

**Issue by zytx121** [InternLM/lmdeploy#2412]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

When I use the latest version 0.6.0 of lmdeploy, starting deepseekvl will result in an error. It seems that it's because his configuration file doesn't have 'hidden_size'.

Related code: https://github.com/InternLM/lmdeploy/blob/7519a35ddca774c947c67ebb4c2616e49a3fb941/lmdeploy/turbomind/deploy/source_model/deepseek_vl.py#L50

A temporary solution: hidden_units =model_arg.get('hidden_size', 4096) 

4096 come from: https://huggingface.co/deepseek-ai/deepseek-vl-7b-chat/blob/6f16f00805f45b5249f709ce21820122eeb43556/config.json#L8

### Reproduction

lmdeploy serve api_server ~/.cache/huggingface/hub/models--deepseek-ai--deepseek-vl-7b-chat/snapshots/6f16f00805f45b5249f709ce21820122eeb43556 --server-port 23339 --tp 8 --session-len 8192

### Environment

```Shell
V100
```

**Comment by AllentDan** [comment]
No, it is not a temporary solution. It is the right fix. The default value of llama is 4096. 
https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/configuration_llama.py#L148

**Comment by nowayhere1** [comment]
so useful for me!!! thanks
