### ISSUE TITLE
[Docs] 关于kv cache 量化

### ISSUE THREAD

**Issue by Root970103** [InternLM/lmdeploy#2418]
### 📚 The doc issue

从文档上的描述来看，kv cache 进行4bit/8bit 量化一定程度上可以提高吞吐量？实际测试发现开启kv cache 量化后初始显存占用没有任何变化，所以有几个疑问：
1. 启动服务后的显存占用，除了模型参数本身，其他具体是什么占用呢？
2. 是否有降低显存占用的方法，比如一些大模型会出现OOM 的问题？

**Comment by lvhan028** [comment]
可以看下 https://lmdeploy.readthedocs.io/en/latest/get_started/get_started.html 中 NOTE 部分的说明

**Comment by Root970103** [comment]
> 可以看下 https://lmdeploy.readthedocs.io/en/latest/get_started/get_started.html 中 NOTE 部分的说明

cache_max_entry_count 这个参数控制kv 缓存的内存占用比例，那启动服务的时候初始显存占用除了模型本身，主要就是kv cache预申请的内存是吗？这部分内存对于Pytorch/TurboMind 两种不同的引擎有差别吗？kv cache 设置了int4/int8 量化，并未对初始预申请显存有影响，只是对推理时速度有影响是吗？不好意思这部分问题有点多，如果有这部分相关技术文档可以帮忙指路一下我也可以自己去学习下，感谢！

**Comment by lvhan028** [comment]
> 启动服务的时候初始显存占用除了模型本身，主要就是kv cache预申请的内存是吗？

是的

> 这部分内存对于Pytorch/TurboMind 两种不同的引擎有差别吗？

无差别

> kv cache 设置了int4/int8 量化，并未对初始预申请显存有影响，只是对推理时速度有影响是吗？

是的。kv cache 内存占用总量不变，只不过由于 int4/int8 kv cache下，kv的数值用原来的 fp16 变为 int4/int8，意味着 kv cache 存储的token变多了。

**Comment by Root970103** [comment]
> > 启动服务的时候初始显存占用除了模型本身，主要就是kv cache预申请的内存是吗？
> 
> 是的
> 
> > 这部分内存对于Pytorch/TurboMind 两种不同的引擎有差别吗？
> 
> 无差别
> 
> > kv cache 设置了int4/int8 量化，并未对初始预申请显存有影响，只是对推理时速度有影响是吗？
> 
> 是的。kv cache 内存占用总量不变，只不过由于 int4/int8 kv cache下，kv的数值用原来的 fp16 变为 int4/int8，意味着 kv cache 存储的token变多了。

好的好的，感谢解答～

**Comment by lvhan028** [comment]
那我先把issue关掉了哈。如果就这个话题还有需要讨论的地方，可以重新打开issue
