### ISSUE TITLE
[Docs] Add Ninja installation tips before `Tensor Parallel with DeepSpeed` in readme

### ISSUE THREAD

**Issue by del-zhenwu** [InternLM/lmdeploy#242]
### 📚 The doc issue

```
RuntimeError: Ninja is required to load C++ extensions
```
when running section `Tensor Parallel with DeepSpeed
` in `Inference with PyTorch` 

### Suggest a potential alternative/fix
something like `sudo apt install ninja-build` for ubuntu, ...
_No response_

**Comment by wangruohui** [comment]
Hi,

ninja can be installed via pip and is a dependency of deepspeed. If you installed deepspeed with pip correctly, ninja should be installed automatically.

**Comment by del-zhenwu** [comment]
> Hi,
> 
> ninja can be installed via pip and is a dependency of deepspeed. If you installed deepspeed with pip correctly, ninja should be installed automatically.

Ok, but it's not installeded after `pip install deepspeed`, and I installed `ninja-build` then it works.

**Comment by wangruohui** [comment]
You can check if `ninja` is installed via `pip list | grep ninja`, and if yes but command `ninja` is unavailable, `PATH` might be incorrectly configured.
