### ISSUE TITLE
[Bug] 部署internvl2自己lora微调的模型，显存占用非常高，快速爬升到了60g正常吗

### ISSUE THREAD

**Issue by yywangfei** [InternLM/lmdeploy#2425]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

部署internvl2自己lora微调的模型，显存占用非常高，快速爬升到了60g

### Reproduction

：：
![image](https://github.com/user-attachments/assets/7187d50b-ddda-414f-9c4a-53b4a457e0e9)

### Environment

```Shell
Name: lmdeploy
Version: 0.5.2.post1
```

**Comment by irexyc** [comment]
可以参考这个文档关于 `cache_max_entry_count` 的解释 https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/get_started/get_started.md
