### ISSUE TITLE
lmdeploy测试4卡/8卡部署api_server用benchmark下代码测试发现qps和吞吐没有很大区别

### ISSUE THREAD

**Issue by sunzx8** [InternLM/lmdeploy#2429]
<img width="577" alt="image" src="https://github.com/user-attachments/assets/54baa431-795a-4eb0-b0fd-b66aa6354066">
ru ti如题，请问是有什么设置没加上吗？为什么显存翻倍提升只有这么一点？

**Comment by lzhangzz** [comment]
L20 应该是 PCIe 通信的，TP 的通信开销随卡数增长很快。建议降低 TP 数采用多实例并发。

**Comment by sunzx8** [comment]
> L20 应该是 PCIe 通信的，TP 的通信开销随卡数增长很快。建议降低 TP 数采用多实例并发。

好的，谢谢
