### ISSUE TITLE
int4 model inference problem

### ISSUE THREAD

**Issue by Dimensionzw** [InternLM/lmdeploy#243]
### 📚 The doc issue

Hello, I want to know how to use tensor parallelism for the int4 model. The following is my model loading code

```
from lmdeploy import turbomind as tm
from lmdeploy.model import MODELS
from lmdeploy.turbomind.tokenizer import Tokenizer

model_path = ./llama2-chinese-awq"
tokenizer_model_path = osp.join(model_path, 'triton_models', 'tokenizer')
tokenizer = Tokenizer(tokenizer_model_path)
tp = 2
model = tm.TurboMind(model_path, eos_id=tokenizer.eos_token_id, tp=tp)
generator = model.create_instance()
model_name = model.model_name
model_util = MODELS.get(model_name)()
seed = random.getrandbits(64)
```
When I set tp=1, the output is normal, but when I set tp=2, the following error is reported：
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/turbomind/turbomind.py", line 127, in _create_weight
    model.create_shared_weights(device_id, rank)
RuntimeError: [TM][ERROR] CUDA runtime error: invalid argument /lmdeploy/src/turbomind/utils/memory_utils.cu:135 

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/turbomind/turbomind.py", line 127, in _create_weight
    model.create_shared_weights(device_id, rank)
RuntimeError: [TM][ERROR] CUDA runtime error: invalid argument /lmdeploy/src/turbomind/utils/memory_utils.cu:135 

[WARNING] gemm_config.in is not found; using default GEMM algo
[WARNING] gemm_config.in is not found; using default GEMM algo

```

**Comment by lzhangzz** [comment]
Sorry for the confusion, TP weight splitting is not fully implemented for W4A16 yet.

**Comment by Dimensionzw** [comment]
> Sorry for the confusion, TP weight splitting is not fully implemented for W4A16 yet.

Ok, I tried it again. After specifying tp=2 when executing deploy.py, no error will be reported at runtime, but the output result is incorrect. Thank you for the follow-up update

**Comment by lzhangzz** [comment]
Just added TP for W4A16 in #262.

**Comment by Dimensionzw** [comment]
> Just added TP for W4A16 in #262.

Thank you very much, using the latest deploy.py can already achieve correct int4 deployment and output, but I still have two related questions here:
1. Using multiple GPUs in int4 mode has no acceleration effect, but using multiple GPUs in fp16 mode can improve the inference speed
2. When I use my fine-tuned llama model for int4 quantization, when awq.py is executed, the following assertion fails. Is there something wrong with my quantization calibration process:
```
for p in pre_fc.parameters():
    assert torch.isnan(p).sum() == 0
for fc in fcs:
    for p in fc.parameters():
        assert torch.isnan(p).sum() == 0
```
The specific location is in line 114-118 of awq.py. Hope to get your guidance, thank you very much.

**Comment by lzhangzz** [comment]
> 1. Using multiple GPUs in int4 mode has no acceleration effect, but using multiple GPUs in fp16 mode can improve the inference speed

Factors related to TP acceleration

- When weights are spitted in multiple GPUs, they may be too small to saturate GPU memory bandwidth (e.g. `w_qkv` is only 12MB for 7B-w4-tp2 model.
- The heuristic for picking GEMM kernels is hand-tuned for TP=1, may be far from optimal for TP>1 (we will add auto-tuning to optimize this case)
- There is additional communication cost for TP mode.

In fact, even for f16 weights, acceleration in TP mode is sub-linear due to layer-wise communication cost.



> 2\. When I use my fine-tuned llama model for int4 quantization, when awq.py is executed, the following assertion fails. Is there something wrong with my quantization calibration process:

@pppppM Can you shed some light on this issue?

**Comment by pppppM** [comment]
> 2\. When I use my fine-tuned llama model for int4 quantization, when awq.py is executed, the following assertion fails. Is there something wrong with my quantization calibration process:

@Dimensionzw Before quantization, AWQ will scale the weight to make it easier to be quantized. This issue may occur if there are some outliers in the model after finetuning, leading to NAN values after weight scaling. You could try setting `w_group_size` to 64, which might mitigate the impact of outliers.

**Comment by Dimensionzw** [comment]
> > 2. When I use my fine-tuned llama model for int4 quantization, when awq.py is executed, the following assertion fails. Is there something wrong with my quantization calibration process:
> 
> @Dimensionzw Before quantization, AWQ will scale the weight to make it easier to be quantized. This issue may occur if there are some outliers in the model after finetuning, leading to NAN values after weight scaling. You could try setting `w_group_size` to 64, which might mitigate the impact of outliers.

When I use group bit 64, there will still be nan. I think it may be because my model is fine-tuned for specific businesses. There is a problem with using the public c4 for calibration. I will sort out our own data for calibration in the future. thanks for your answer

**Comment by sjzhou4** [comment]
@lzhangzz  我也遇到了你开头提出的The doc issue问题，就是tp =2 时会出现cu报错，我更新了最新的代码还是一样的报错，请问一下你这边是怎么处理解决的，有重新用源码编译吗？还是直接替换新的deploy.py？

**Comment by LiuKai22** [comment]
> > 
> > 
> > @Dimensionzw Before quantization, AWQ will scale the weight to make it easier to be quantized. This issue may occur if there are some outliers in the model after finetuning, leading to NAN values after weight scaling. You could try setting `w_group_size` to 64, which might mitigate the impact of outliers.
> 
> When I use group bit 64, there will still be nan. I think it may be because my model is fine-tuned for specific businesses. There is a problem with using the public c4 for calibration. I will sort out our own data for calibration in the future. thanks for your answer

I meet the same problem when I use **C4 dataset to calibrate Llama2-13B (AWQ).** 

    for p in ln.parameters():
        assert torch.isnan(p).sum() == 0
    for fc in fcs:
        for p in fc.parameters():
            **assert torch.isnan(p).sum() == 0**
    return scales

No matter what group bit I use (from 128 - 32), there will always throw an AssertionError.
Any advice ? @pppppM
