### ISSUE TITLE
[Bug] main分支EngineGenerationConfig不在初始化中了

### ISSUE THREAD

**Issue by RandomCoins** [InternLM/lmdeploy#2435]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

我用swift调用main分支的lmdeploy时发现EngineGenerationConfig不存在了，看源码是EngineGenerationConfig删掉了，请问删掉这个原因是什么

### Reproduction

无

### Environment

```Shell
无
```

**Comment by irexyc** [comment]
GenerationConfig  和 EngineGenerationConfig 最初的设计是前者用户侧来用，后者引擎侧来用，区别就是stop_words/bad_words 前者是list[str], 后者是list[int]。目前觉得区别不大，也参考了 vllm 的`SamplingParams`，所以把这两个合并了，EngineGenerationConfig 之前的 stop_words/bad_words 改成了现在的 stop_token_ids / bad_token_ids

**Comment by lvhan028** [comment]
@irexyc Could you inform `swift` about this change?
