### ISSUE TITLE
[Feature] 能否支持一下qwenvl2

### ISSUE THREAD

**Issue by Ranking666** [InternLM/lmdeploy#2436]
### Motivation

能否支持一下qwenvl2

**Comment by irexyc** [comment]
正在做，应该会先在 pytorch backend 进行支持，然后在 turobmind backend 优化与加速。

**Comment by BlueBlueFF** [comment]
> 正在做，应该会先在 pytorch backend 进行支持，然后在 turobmind backend 优化与加速。

预计什么时候会放出呢？

**Comment by irexyc** [comment]
> 预计什么时候会放出呢？

这周 pytorch backend 的应该可以用。
