### ISSUE TITLE
[Bug] 请问一下，我用qwen2的模型，仿照internlm-xcomposer2中的plora方式训练了一个VL模型，这个模型应该怎样用lmdeploy部署起来

### ISSUE THREAD

**Issue by alanayu** [InternLM/lmdeploy#2437]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

我用qwen2的模型，仿照internlm-xcomposer2中的plora方式训练了一个VL模型
主要的疑惑点是怎样用lmdeploy部署起来这样的模型。
因为plora的推理需要一个im_mask，有什么比较简单的办法能向模型传入这个im_mask吗？
感谢！

### Reproduction

主要是思路上的提问

### Environment

```Shell
lmdeploy: 0.6.0a0
transformers: 4.44.2
```

**Comment by irexyc** [comment]
plora 的计算目前是在turbomind后端进行支持的，im_mask是自动算的，如果复用这部分的逻辑的话，问题就变成了怎么用turbomind加载你修改的模型。

说实话，这里不是特别简单。大致可以分成两个部分。1) 加载 vision。2）加载 llm 部分。

先说加载llm的部分，这部分的逻辑是根据arch来映射加载权重的逻辑。这部分最简单的方式就是把你的模型伪装成 xcomposer2，包括权重名字以及config。另外你可能需要改下plora的config，具体的在[这里](https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/turbomind/deploy/source_model/xcomposer2.py#L35-L53)

另外就是vision部分的加载，可以看下[这里](https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/vl/model/builder.py#L28)，主要逻辑是复用transformers，根据arch去映射具体的加载逻辑。

这两部分可能会有打架的地方，比如你要伪装成xcomposer2要改config里面的arch，但是改了arch之后就会改变加载vision的逻辑，这里建议把根据arch加载vision的映射变一下。

**Comment by alanayu** [comment]
好的，感谢。我试一下这个思路
