### ISSUE TITLE
[Bug] lmdeploy does not support the regularized lora target module

### ISSUE THREAD

**Issue by orzgugu** [InternLM/lmdeploy#2439]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

Hello, the checkpoint of internvl2-8b obtained after training with Swift 2.25 and later versions defaults to the regular lora target module, and the current regular lora target module cannot use imdeploy. Is there any solution?
Looking forward to your reply, it is very important to me!

### Reproduction

null

### Environment

```Shell
null
```

**Comment by irexyc** [comment]
We recommand merge lora weights, save the merged model and use the lmdeploy to inference the merged model.
