### ISSUE TITLE
[Docs] Add mmengine installation tips in section `Obtain Quantization Parameters`

### ISSUE THREAD

**Issue by del-zhenwu** [InternLM/lmdeploy#244]
### 📚 The doc issue

```
miniconda3/envs/llm-test-0815/lib/python3.8/site-packages/lmdeploy/lite/utils/collect.py", line 4, in <module>
    from mmengine.config.lazy import LazyAttr
ModuleNotFoundError: No module named 'mmengine.config.lazy'
```
`python3 -m lmdeploy.lite.apis.calibrate` run failed, caused by missing `mmengine` not installed.

### Suggest a potential alternative/fix

Install `mmegine`(latest version) before getting the quantization parameters.

**Comment by lvhan028** [comment]
`mmengine` is supposed to be installed after executing `pip install lmdeploy`
Could you share the result of running `pip show | grep mmegine`?

**Comment by del-zhenwu** [comment]
> `mmengine` is supposed to be installed after executing `pip install lmdeploy` Could you share the result of running `pip show | grep mmegine`?

Maybe we could add some description before the command, as the following in the doc:
```
Tensor Parallel with DeepSpeed
deepspeed --module --num_gpus 2 lmdeploy.pytorch.chat \
    $NAME_OR_PATH_TO_HF_MODEL \
    --max_new_tokens 64 \
    --temperture 0.8 \
    --top_p 0.95 \
    --seed 0
You need to install deepspeed first to use this feature.

pip install deepspeed
```

**Comment by lvhan028** [comment]
The issue is about mmengine. But the command you present is about pytorch inference. They are irrelevant

**Comment by del-zhenwu** [comment]
> The issue is about mmengine. But the command you present is about pytorch inference. They are irrelevant

The command above is just an example, and there is an installation tip at the end.

**Comment by lvhan028** [comment]
Install the latest mmengine. I'll add it to FAQ.
