### ISSUE TITLE
[Bug] How to use w4a16 model in PytorchEngine 

### ISSUE THREAD

**Issue by xzmates** [InternLM/lmdeploy#2443]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

I notice the supported models in the official documents, qwen series with w4a16 is supported, so i use the command lmdeploy lite auto_awq /ssd/xuzhou/weight_pretrained/Qwen2-1_5B-Instruct --work-dir /ssd/xuzhou/weight_pretrained/Qwen2-1_5B-Instruct-w4a16, it successfully save the w4a16 model, but when i use
from lmdeploy import pipeline, TurbomindEngineConfig, PytorchEngineConfig
from lmdeploy.vl import load_image
backend_config = PytorchEngineConfig(tp=1)
pipe = pipeline('/ssd/xuzhou/weight_pretrained/Qwen2-1_5B-Instruct-w4a16',backend_config=backend_config)
raise error below:
2024-09-11 03:19:40,221 - lmdeploy - ERROR - ModuleNotFoundError: No module named 'awq'
2024-09-11 03:19:40,221 - lmdeploy - ERROR - <autoawq> test failed!
Please ensure it has been installed correctly.
![PytorchEngine](https://github.com/user-attachments/assets/6776fda6-e4c4-4519-8bbd-61fa8bf504c2)

### Reproduction

1.quant&save: 
lmdeploy lite auto_awq /ssd/xuzhou/weight_pretrained/Qwen2-1_5B-Instruct --work-dir /ssd/xuzhou/weight_pretrained/Qwen2-1_5B-Instruct-w4a16
2.PytorchEngine pipeline:
from lmdeploy import pipeline, TurbomindEngineConfig, PytorchEngineConfig
from lmdeploy.vl import load_image
backend_config = PytorchEngineConfig(tp=1)
pipe = pipeline('/ssd/xuzhou/weight_pretrained/Qwen2-1_5B-Instruct-w4a16',backend_config=backend_config)

### Environment

```Shell
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Mar_28_02:18:24_PDT_2024
Cuda compilation tools, release 12.4, V12.4.131
Build cuda_12.4.r12.4/compiler.34097967_0
Package                  Version
------------------------ -----------
accelerate               0.33.0
addict                   2.4.0
aiohappyeyeballs         2.4.0
aiohttp                  3.10.5
aiosignal                1.3.1
annotated-types          0.7.0
anyio                    4.4.0
async-timeout            4.0.3
attrs                    24.2.0
certifi                  2024.7.4
charset-normalizer       3.3.2
click                    8.1.7
datasets                 2.21.0
dill                     0.3.8
einops                   0.8.0
exceptiongroup           1.2.2
fastapi                  0.112.1
filelock                 3.15.4
fire                     0.6.0
frozenlist               1.4.1
fsspec                   2024.6.1
h11                      0.14.0
huggingface-hub          0.24.6
idna                     3.7
importlib_metadata       8.4.0
Jinja2                   3.1.4
lmdeploy                 0.5.3
markdown-it-py           3.0.0
MarkupSafe               2.1.5
mdurl                    0.1.2
mmengine-lite            0.10.4
mpmath                   1.3.0
multidict                6.0.5
multiprocess             0.70.16
networkx                 3.3
numpy                    1.26.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.6.20
nvidia-nvtx-cu12         12.1.105
packaging                24.1
pandas                   2.2.2
peft                     0.11.1
pillow                   10.4.0
pip                      22.0.2
platformdirs             4.2.2
protobuf                 5.27.3
psutil                   6.0.0
pyarrow                  17.0.0
pydantic                 2.8.2
pydantic_core            2.20.1
Pygments                 2.18.0
pynvml                   11.5.3
python-dateutil          2.9.0.post0
pytz                     2024.1
PyYAML                   6.0.2
regex                    2024.7.24
requests                 2.32.3
rich                     13.7.1
safetensors              0.4.4
sentencepiece            0.2.0
setuptools               59.6.0
shortuuid                1.0.13
six                      1.16.0
sniffio                  1.3.1
starlette                0.38.2
sympy                    1.13.2
termcolor                2.4.0
tiktoken                 0.7.0
tokenizers               0.19.1
tomli                    2.0.1
torch                    2.3.1
torchvision              0.18.1
tqdm                     4.66.5
transformers             4.44.2
triton                   2.3.1
typing_extensions        4.12.2
tzdata                   2024.1
urllib3                  2.2.2
uvicorn                  0.30.6
wheel                    0.37.1
xformers                 0.0.27
xxhash                   3.5.0
yapf                     0.40.2
yarl                     1.9.4
zipp                     3.20.0
```

**Comment by AllentDan** [comment]
To run the awq model in pytorch engine, please install auto_awq package correctly.

**Comment by xzmates** [comment]
> To run the awq model in pytorch engine, please install auto_awq package correctly.



> To run the awq model in pytorch engine, please install auto_awq package correctly.

thanks, the problem has been solved, glm-4-9b-chat-w4a16 model infers normally under the PytorchEngine.
