### ISSUE TITLE
[Bug] lmdeploy部署minicpm-v2_6推理报错

### ISSUE THREAD

**Issue by dfe2342** [InternLM/lmdeploy#2452]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

你好，我在v100上2卡部署minicpm-v-2_6，使用命令 lmdeploy serve api_server minicpm-v2_6 --server-port 8000 --tp 2 --cache-max-entry-count 0.2，模型加载正常，但推理时报错：RuntimeError:Expected all tensors to be on the same device, but found at leaset two devices, cuda:0 and cuda:1

### Reproduction

 lmdeploy serve api_server minicpm-v2_6 --server-port 8000 --tp 2 --cache-max-entry-count 0.2

### Environment

```Shell
lmdeploy版本：0.6.0a0
```

**Comment by irexyc** [comment]
@luoshengyin 

请问日志里面有些哪个地方的device不一致么？

**Comment by dfe2342** [comment]
@irexyc 你好，好像日志中没有看到，但是模型确实被加载到两个卡了，报错日志如下
uvloop/cbcbandles.py, line 63, 在uvloop.loop.Handle.run
minicpm-v2.6/venv/lib/python3.10/site-packages/lmdploy/v1/engine.py, line 27, raise e
minicpm-v2.6/venv/lib/python3.10/site-packages/lmdploy/v1/engine.py, line 23, task.result()
/usr/lib/python3.10/concurrent/futures/thread.py, line 58, result = self.fn(*args, **kwargs)
minicpm-v2.6/venv/lib/python3.10/site-packages/lmdploy/v1/engine.py, line 169, outputs = self.model.forward(*func_inputs)
minicpm-v2.6/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py, line 115, return func(*args, **kwargs)
minicpm-v2.6/venv/lib/python3.10/site-packages/lmdploy/v1/model/minicpmv.py, line 214, return self._forward_func(images, params)
minicpm-v2.6/venv/lib/python3.10/site-packages/lmdploy/v1/model/minicpmv.py, line 192, vision_embedding = self.model.vpm()
minicpm-v2.6/venv/lib/python3.10/site-packages/torch/nn/modules/module.py, line 1518, return self.call_impl(*args, **kwargs)
minicpm-v2.6/venv/lib/python3.10/site-packages/torch/nn/modules/module.py, line 1527, forward call Impl
/root/.cache/huggingface/modules/transformers_modules/MiniCPM-V-2_6/modeling_navi siglippy.py, line 918, encoder_outputs = self.encoder_layer(*args, **kwargs)
minicpm-v2.6/venv/lib/python3.10/site-packages/torch/nn/modules/module.py, line 1518, return self.call_impl(*args, **kwargs)
minicpm-v2.6/venv/lib/python3.10/site-packages/torch/nn/modules/module.py, line 1527, forward call Impl
/root/.cache/huggingface/modules/transformers_modules/MiniCPM-V-2_6/modeling_navi siglippy.py, line 826, ayer_outputs = encoder_layer(*args, **kwargs)
minicpm-v2.6/venv/lib/python3.10/site-packages/torch/nn/modules/module.py, line 1518, return self.call_impl(*args, **kwargs)
minicpm-v2.6/venv/lib/python3.10/site-packages/torch/nn/modules/module.py, line 1527, forward call Impl
/root/.cache/huggingface/modules/transformers_modules/MiniCPM-V-2_6/modeling_navi siglippy.py, line 680, hidden_states = residual + hidden_states

**Comment by irexyc** [comment]
按照这个改一下安装目录里的文件吧

https://github.com/InternLM/lmdeploy/pull/2454/files

**Comment by dfe2342** [comment]
@irexyc 可以正常推理了，感谢
