### ISSUE TITLE
 InternVL2在做AWQ量化的时候，不能支持自定义的校准数据集吗

### ISSUE THREAD

**Issue by tanguozhu** [InternLM/lmdeploy#2456]

**Comment by fak111** [comment]
怎么搞  我这网络下载不了数据集啊
![image](https://github.com/user-attachments/assets/c0f5251e-a09d-43b7-a3a2-8aef79b94ee2)
我想手动又不行
![image](https://github.com/user-attachments/assets/8f68e160-7e5e-44cc-96ea-6d57d76483cb)
![image](https://github.com/user-attachments/assets/ff26aceb-a9c7-4880-b916-7c8f4a7fe94e)

**Comment by tanguozhu** [comment]
https://github.com/InternLM/lmdeploy/issues/1142 看这个吧，亲测可行

> 怎么搞 我这网络下载不了数据集啊 ![image](https://private-user-images.githubusercontent.com/97438502/366791908-c0f5251e-a09d-43b7-a3a2-8aef79b94ee2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMzA5OTQsIm5iZiI6MTcyNjEzMDY5NCwicGF0aCI6Ii85NzQzODUwMi8zNjY3OTE5MDgtYzBmNTI1MWUtYTA5ZC00M2I3LWEzYTItOGFlZjc5Yjk0ZWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA4NDQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMGIyNTJiZTA3NjZjOWE1YWJlZDFhY2IwMGVkYzA1OWYzZDMyYjllOTRiNjVmMDc2N2Y3NTk1MmMzMTMyODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gu0iKZIgMqkPf2f-f44dul08GFbKQh_nElHxOVcxm0c) 我想手动又不行 ![image](https://private-user-images.githubusercontent.com/97438502/366792079-8f68e160-7e5e-44cc-96ea-6d57d76483cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMzA5OTQsIm5iZiI6MTcyNjEzMDY5NCwicGF0aCI6Ii85NzQzODUwMi8zNjY3OTIwNzktOGY2OGUxNjAtN2U1ZS00NGNjLTk2ZWEtNmQ1N2Q3NjQ4M2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA4NDQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNjgyODgwOWU1NzJkYTM0NzRmMjdkMmZkOGZhYWJhZDQxM2FmNjJmYjJhZjg2MGE2ZTU3ZGQ2ZGZkNDgwNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2gAWy7SCFO29bPvLqhg1LZOJChDFPJWhSHSxorPWZoc) ![image](https://private-user-images.githubusercontent.com/97438502/366792304-ff26aceb-a9c7-4880-b916-7c8f4a7fe94e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMzA5OTQsIm5iZiI6MTcyNjEzMDY5NCwicGF0aCI6Ii85NzQzODUwMi8zNjY3OTIzMDQtZmYyNmFjZWItYTljNy00ODgwLWI5MTYtN2M4ZjRhN2ZlOTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA4NDQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMTVmMWYzM2Q2NTMxYzM2MGU5Yjc5MWNlMDI5MDk0MDcyYTIzYWI3ZjcxYzcwMzhmNGE1YTI0ZjdjOGRmYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EbDurwX8180CJg7LjKgYNw6JoyUkpXzCFpJmiTmkPBo)

**Comment by fak111** [comment]
感谢，已解决并写入博客http://t.csdnimg.cn/j3PSs

**Comment by AllentDan** [comment]
这个我们后面放到 FAQ 里面。
Possible solutions:
https://github.com/InternLM/lmdeploy/issues/1142#issuecomment-2072588598
https://github.com/InternLM/lmdeploy/issues/1865

**Comment by wangjiawen2013** [comment]
还是没有看到到底如何解决自定义数据集的问题。我用的是微调的模型，按理说用微调数据做校准数据集是最合适的。上面给出的链接现在已经打不开了。
