### ISSUE TITLE
[Question] Inference result looks like wrong after quantization

### ISSUE THREAD

**Issue by del-zhenwu** [InternLM/lmdeploy#246]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

I follow the readme to do the quantization.
```
1. python3 -m lmdeploy.lite.apis.calibrate \

2. python3 -m lmdeploy.lite.apis.auto_awq \
```
and then use this command to infer: `python -m lmdeploy.pytorch.chat`. But the output returned looks like it turned out wrong . Here is the result:
```
double enter to end input >>> hi
雄isceisceieur regimentglegleњ regiment方quergle雄雄gle雄 snapshotgleHLquer Kop方 propag雄雄雄listener propagglegle BegriffeHLraste okres regiment февра雄HL雄gle雄雄њayerOutlet雄雄雄雄рез雄雄onyme雄雄attanattan雄雄雄雄 regimentOutlet雄雄雄雄gleonymeraste雄рез雄isceraste Kop雄雄雄雄 Einzelnach雄gle✓男glerasteseaugleopsis✓雄雄ieur Prima ]]isce方雄њ雄seauрез雄雄雄雄雄rasteisce✓isce雄雄雄雄雄 regiment雄雄雄
雄 Einzelnach雄雄雄้雄
```

### Reproduction

model: `llama-2-7b-chat-hf`

**Comment by lvhan028** [comment]
Could you verify it with the pre-quantized model in our [Hub](https://huggingface.co/lmdeploy)?

**Comment by del-zhenwu** [comment]
> Could you verify it with the pre-quantized model in our [Hub](https://huggingface.co/lmdeploy)?

It's fine as expected.

**Comment by del-zhenwu** [comment]
> > Could you verify it with the pre-quantized model in our [Hub](https://huggingface.co/lmdeploy)?
> 
> It's fine as expected after converting to `turbomind` format, but it is not ok if using `pytorch.chat` directly.

That is because the w4 is not supported as shown in the readme.

**Comment by Tushar-ml** [comment]
I am still getting this issue, used above repo and converted to turbomind, but getting this 
![image](https://github.com/InternLM/lmdeploy/assets/58730675/0d5431b3-72d3-4d85-bb9e-20a95b6ed6df)
