### ISSUE TITLE
[Bug] fail to deploy model from modelscope using [lmdeploy serve api_server]

### ISSUE THREAD

**Issue by kaiwang0112006** [InternLM/lmdeploy#2462]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

I download model from modelscope and try to start a OpenAI-style api_server. But when I try to call the api from python client, it throw an error: 

`  File "/home/yawei/anaconda3/envs/kw_env/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 601, in _encode_plus
    batched_output = self._batch_encode_plus(
  File "/home/yawei/anaconda3/envs/kw_env/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 528, in _batch_encode_plus
    encodings = self._tokenizer.encode_batch(
TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]`

### Reproduction

for server:

`
git clone   https://www.modelscope.cn/AI-ModelScope/Meta-Llama-3.1-8B.git 

lmdeploy serve api_server \
    /mnt/datawow/kw/ft_med/model/Meta-Llama-3.1-8B \
    --model-name internlm-local
    --model-format hf \
    --quant-policy 0 \
    --server-name 192.168.8.11 \
    --server-port 23333 \
    --tp 1
`

for client:

`
from openai import OpenAI
client = OpenAI(
    api_key='YOUR_API_KEY',
    base_url="http://192.168.8.11:23333/v1"
)
model_name = client.models.list().data[0].id
response = client.chat.completions.create(
  model=model_name,
  messages=[
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": " provide three suggestions about time management"},
  ],
    temperature=0.8,
    top_p=0.8
)
print(response)
`

error:

`
  File "/home/yawei/anaconda3/envs/kw_env/lib/python3.10/site-packages/lmdeploy/tokenizer.py", line 335, in encode
    encoded = self.model.encode(s, **kwargs)
  File "/home/yawei/anaconda3/envs/kw_env/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2843, in encode
    encoded_inputs = self.encode_plus(
  File "/home/yawei/anaconda3/envs/kw_env/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 3255, in encode_plus
    return self._encode_plus(
  File "/home/yawei/anaconda3/envs/kw_env/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 601, in _encode_plus
    batched_output = self._batch_encode_plus(
  File "/home/yawei/anaconda3/envs/kw_env/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 528, in _batch_encode_plus
    encodings = self._tokenizer.encode_batch(
TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]
`

### Environment

```Shell
env information:

(kw_env) yawei@eleven:/mnt/datawow/kw/ft_med/model/Meta-Llama-3.1-8B$ lmdeploy check_env
sys.platform: linux
Python: 3.10.9 (main, Mar  8 2023, 10:47:38) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda-11.8
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 2.0.1+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.9.2  (built against CUDA 12.1)
    - Built with CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.2+cu117
LMDeploy: 0.4.0+3c7857d
transformers: 4.43.2
gradio: Not Found
fastapi: 0.109.0
pydantic: 2.7.1
triton: 2.0.0
```

**Comment by AllentDan** [comment]
Llama3.1 was not supported until lmdeploy 0.5.3. Please upgrade lmdeploy to the latest.

**Comment by kaiwang0112006** [comment]
yes, it's a version issue, thx
