### ISSUE TITLE
[Feature] How to use awq with my own dataset

### ISSUE THREAD

**Issue by wangzhongren-code** [InternLM/lmdeploy#2463]
### Motivation

I want to use the awq with my own dataset to reduce the loss from quantization. Can anyone teach me how to organize the format of the local data?  Is there any documentation or tutorial for this?

### Additional context

The format of my own dataset is a typical chat message like:

[
    {"role": "system", "content": "You are an assistant."},
    {"role": "user", "content": "Who you are?"},
    {"role": "assistant", "content": "I am a language model ..."}
]

The goal is to make the quantized model as close as possible to the assistant's content.

**Comment by AllentDan** [comment]
It is [get_calib_loaders](https://github.com/InternLM/lmdeploy/blob/8b9f6abcaaa85e1f128e683079a39e7665d5940d/lmdeploy/lite/utils/calib_dataloader.py#L304) that you should modify to take advantage of your own dataset.

Another direct way is just replace the data tensor with your own. Ref to https://github.com/InternLM/lmdeploy/blob/8b9f6abcaaa85e1f128e683079a39e7665d5940d/lmdeploy/lite/apis/calibrate.py#L245

**Comment by wangzhongren-code** [comment]
Thank you very much for your kind help. It works for me.
