### ISSUE TITLE
[Bug]TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]

### ISSUE THREAD

**Issue by LIUKAI0815** [InternLM/lmdeploy#2476]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

 lora训练，merge lora之后的模型部署openai接口然后推理报错，llama3.1_8B和qwen2_7B报错，internlm2_5-7b-chat没报错，前两个merge lora的模型用VLLM部署就没问题，报错如下：
encoded = self.model.encode(s,
  File "/root/miniconda3/envs/LMDeploy/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2715, in encode
    encoded_inputs = self.encode_plus(
  File "/root/miniconda3/envs/LMDeploy/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 3127, in encode_plus
    return self._encode_plus(
  File "/root/miniconda3/envs/LMDeploy/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 601, in _encode_plus
    batched_output = self._batch_encode_plus(
  File "/root/miniconda3/envs/LMDeploy/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 528, in _batch_encode_plus
    encodings = self._tokenizer.encode_batch(
TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]

### Reproduction

CUDA_VISIBLE_DEVICES=7 lmdeploy serve api_server /workspace/output/llama/llama3_1-8b-instruct/v0-20240918-142328/checkpoint-2200-merged  \
        --server-port 2015 \
        --tp 1 \
        --cache-max-entry-count 0.5 \
        --session-len 10000 \
        --model-name gare \
        --enable-prefix-caching  \

### Environment

```Shell
lmdeploy                          0.5.3
```

**Comment by lvhan028** [comment]
May add `--chat-template llama3_1`

**Comment by LIUKAI0815** [comment]
@lvhan028 非常感谢，可以执行，只不过今天在运行qwen2.5-0.5B的时候，不同的环境，运行同样的lora模型，一个需要加--chat-template否则就会和题目一样报错，另一个不需要加--chat-template就可以正常运行。lmdeploy都是0.6.0，transformers都是4.43.1

**Comment by LIUKAI0815** [comment]
@lvhan028 感谢回复
