### ISSUE TITLE
[Bug] qwen2.5-14b压力测试报错，Failed to find a feasible kernel in the cache, will dispatch by heuristic.

### ISSUE THREAD

**Issue by maxin9966** [InternLM/lmdeploy#2480]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

## 单卡或双卡跑100个并发，百分百出现，开始能正确输出，后面就永久性卡死了，GPU永远是百分百占用：

Sep 18 20:11:55 ubuntu22lts bash[37095]: INFO:     192.168.1.161:45054 - "POST /v1/chat/completions HTTP/1.1" 200 OK
Sep 18 20:11:56 ubuntu22lts bash[37095]: INFO:     192.168.1.161:45074 - "GET /v1/chat/completions HTTP/1.1" 405 Method Not Allowed
Sep 18 20:12:26 ubuntu22lts bash[37095]: INFO:     192.168.1.161:47544 - "GET /v1/chat/completions HTTP/1.1" 405 Method Not Allowed
Sep 18 20:12:29 ubuntu22lts bash[37095]: Failed to find a feasible kernel in the cache, will dispatch by heuristic.
Sep 18 20:12:29 ubuntu22lts bash[37095]: Failed to find a feasible kernel in the cache, will dispatch by heuristic.
Sep 18 20:12:29 ubuntu22lts bash[37095]: Failed to find a feasible kernel in the cache, will dispatch by heuristic.
Sep 18 20:12:29 ubuntu22lts bash[37095]: Failed to find a feasible kernel in the cache, will dispatch by heuristic.
Sep 18 20:12:29 ubuntu22lts bash[37095]: INFO:     192.168.1.207:53868 - "POST /v1/chat/completions HTTP/1.1" 200 OK
Sep 18 20:12:29 ubuntu22lts bash[37095]: INFO:     192.168.1.161:47544 - "POST /v1/chat/completions HTTP/1.1" 200 OK

### Reproduction

1

### Environment

```Shell
0.6.0
sm75
cuda 12.4
```

**Comment by maxin9966** [comment]
https://www.modelscope.cn/models/qwen/Qwen2.5-14B-Instruct-GPTQ-Int4/files

**Comment by lvhan028** [comment]
Yes? Is it a false alarm or a real issue?

**Comment by maxin9966** [comment]
@lvhan028 请求时使用了默认参数就没问题了

**Comment by maxin9966** [comment]
@lvhan028 我压力测试了lmdeploy，似乎你们的性能比sglang还要高？而且你们的显存占用比vllm还低

请问下你们未来会支持GPTQ-INT3模型吗？vllm和sglang都是支持INT3模型的，但是你们的推理框架最节约显存，72b/32b这个大小的INT3模型，在消费级显卡上用双/单卡就可以推理了（INT4就刚好不够），相当于节省了一半的显卡资源，目前的INT3经过算法校准，相比INT4差距已经不大了。

**Comment by senlice** [comment]
+1，我使用Qwen2.5-32B-Instruct-AWQ模型，单条测试时OK的，但是将十条作为一个批次送入后，前面一些数据数据是正常的，后面就出现了Failed to find a feasible kernel in the cache, will dispatch by heuristic.

**Comment by senlice** [comment]
> @lvhan028 请求时使用了默认参数就没问题了

你不是把cache_max_entry_count参数调高了，我最开始将cache_max_entry_count设置成了0.9，然后批量跑出现了Failed to find a feasible kernel in the cache, will dispatch by heuristic.后面将cache_max_entry_count调低一点，批量就没问题了
