### ISSUE TITLE
[Feature] Qwen2.5系列能支持一下吗？

### ISSUE THREAD

**Issue by tiaotiaosong** [InternLM/lmdeploy#2481]
### Motivation

如题

**Comment by AllentDan** [comment]
可以直接跑。对话模板就多了一句 `You are Qwen, created by Alibaba Cloud. You are a helpful assistant.\n`。

**Comment by akai-shuuichi** [comment]
> 可以直接跑。对话模板就多了一句 `You are Qwen, created by Alibaba Cloud. You are a helpful assistant.\n`。

function_call有计划支持吗？

**Comment by LIUKAI0815** [comment]
@AllentDan Fallback to pytorch engine  xxx   because `not supported by turbomind engine.请问这种情况是不是需要后续更新？

**Comment by AllentDan** [comment]
需要你本地更新 lmdeploy。目前用的是什么版本

**Comment by LIUKAI0815** [comment]
lmdeploy                          0.6.0
推理的是qwen2.5的merge lora

**Comment by AllentDan** [comment]
应该是 merge 以后，architectures 变了，导致识别不了。

**Comment by LIUKAI0815** [comment]
请问有什么办法吗？或者可以加载本地lora吗，我看官方文档里说的是加载huggingface的lora：用户只需要将 lora 权重的 huggingface 模型路径通过字典的形式传入 --adapters 即可。

**Comment by AllentDan** [comment]
lora 只有 pytorch engine 支持了，所以是正常的。https://lmdeploy.readthedocs.io/en/latest/llm/api_server_lora.html#launch-s-lora

**Comment by Tendo33** [comment]
> > 可以直接跑。对话模板就多了一句 `You are Qwen, created by Alibaba Cloud. You are a helpful assistant.\n`。
> 
> function_call有计划支持吗？

同问

**Comment by Lexlum** [comment]
我在下游任务上进行了全量参数微调了Qwen2.5-1.5B,然后对他做KV-cache量化int8之后（quant_policy=8），表现有下降约10%。这个可能是什么原因导致的啊。

**Comment by AllentDan** [comment]
> 我在下游任务上进行了全量参数微调了Qwen2.5-1.5B,然后对他做KV-cache量化int8之后（quant_policy=8），表现有下降约10%。这个可能是什么原因导致的啊。

用的 pytorch engine 还是 turbomind？下降是相对微调后的模型还是微调前的？

**Comment by LIUKAI0815** [comment]
> 我在下游任务上进行了全量参数微调了Qwen2.5-1.5B,然后对他做KV-cache量化int8之后（quant_policy=8），表现有下降约10%。这个可能是什么原因导致的啊。

@Lexlum https://qwen.readthedocs.io/zh-cn/latest/benchmark/quantization_benchmark.html 可以参考模型量化的下降空间

**Comment by Lexlum** [comment]
> > 我在下游任务上进行了全量参数微调了Qwen2.5-1.5B,然后对他做KV-cache量化int8之后（quant_policy=8），表现有下降约10%。这个可能是什么原因导致的啊。
> 
> 用的 pytorch engine 还是 turbomind？下降是相对微调后的模型还是微调前的？

 采用的是turbomind，下降是相对微调后的模型，我做的是一个分类任务，一个字母表示一个类别，让他输出A-Z之间的一个字母作为模型回复。在kv量化int8后有约10%左右的测试结果返回了空。

**Comment by AllentDan** [comment]
可以对比一下不设置 quant_policy，看看是否一样。一般 kv-cache 量化 8bit 不太有精度损失

**Comment by Lexlum** [comment]
> 可以对比一下不设置 quant_policy，看看是否一样。一般 kv-cache 量化 8bit 不太有精度损失

目前我就不设置 quant_policy，效果是正常的。应该就是 quant_policy 8 的直接影响。

**Comment by AllentDan** [comment]
那可能就是有一些异常点很重要，但是量化完损失掉了

**Comment by LIUKAI0815** [comment]
> 可以对比一下不设置 quant_policy，看看是否一样。一般 kv-cache 量化 8bit 不太有精度损失
看到有别人对比的文章，如果是你那边损失比较多，可能就是损失的精度正好就是你那边实验需要的了
https://blog.csdn.net/weixin_42112760/article/details/135831439：KV Cache 可以节约大约 20% 的显存，精度不仅没有明显下降，相反在不少任务上还有一定的提升。可能得原因是，量化会导致一定的误差，有时候这种误差可能会减少模型对训练数据的拟合，从而提高泛化性能。量化可以被视为引入轻微噪声的正则化方法。或者，也有可能量化后的模型正好对某些数据集具有更好的性能。

**Comment by LIUKAI0815** [comment]
> 可以对比一下不设置 quant_policy，看看是否一样。一般 kv-cache 量化 8bit 不太有精度损失




看到有别人对比的文章，如果是你那边损失比较多，可能就是损失的精度正好就是你那边实验需要的了
[https://blog.csdn.net/weixin_42112760/article/details/135831439：KV](https://blog.csdn.net/weixin_42112760/article/details/135831439%EF%BC%9AKV) Cache 可以节约大约 20% 的显存，精度不仅没有明显下降，相反在不少任务上还有一定的提升。可能得原因是，量化会导致一定的误差，有时候这种误差可能会减少模型对训练数据的拟合，从而提高泛化性能。量化可以被视为引入轻微噪声的正则化方法。或者，也有可能量化后的模型正好对某些数据集具有更好的性能。
