### ISSUE TITLE
[Feature] 未来会支持gptq-int3模型吗？

### ISSUE THREAD

**Issue by maxin9966** [InternLM/lmdeploy#2492]
### Motivation

请问未来会支持gptq-int3模型和groupsize为128以下的模型吗？目的是节约更多的显存

**Comment by lvhan028** [comment]
今年没有这个规划

**Comment by lzhangzz** [comment]
@maxin9966 

需要统一考虑下。具体是哪些模型？GPTQ 的量化 config 是怎么样的？还有在什么卡上跑？

**Comment by maxin9966** [comment]
@lzhangzz 
1. 在显存24G的消费级显卡上运行。消费级显卡tp多卡运行，一.成本高 二.效率损耗大，我测试双卡推理相比单卡，只能提升50%不到的吞吐量
2. 目前32B和72B的模型，比如32B的int4模型是20G，在24G显卡上跑就不够，但是int3 16G的模型就可以单卡流畅运行了，72B同理，只需要支持int3就可以
3. config：
## Qwen2.5-32B-GPTQ-INT3-G128：
{
  "_name_or_path": "tclf90/Qwen2.5-32B-Instruct-GPTQ-Int3-G128",
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 5120,
  "initializer_range": 0.02,
  "intermediate_size": 27648,
  "max_position_embeddings": 32768,
  "max_window_layers": 70,
  "model_type": "qwen2",
  "num_attention_heads": 40,
  "num_hidden_layers": 64,
  "num_key_value_heads": 8,
  "quantization_config": {
    "batch_size": 1,
    "bits": 3,
    "block_name_to_quantize": null,
    "cache_block_outputs": true,
    "damp_percent": 0.1,
    "dataset": null,
    "desc_act": false,
    "exllama_config": {
      "version": 1
    },
    "group_size": 128,
    "max_input_length": null,
    "model_seqlen": null,
    "module_name_preceding_first_block": null,
    "modules_in_block_to_quantize": null,
    "pad_token_id": null,
    "quant_method": "gptq",
    "sym": true,
    "tokenizer": null,
    "true_sequential": true,
    "use_cuda_fp16": true,
    "use_exllama": true
  },
  "rms_norm_eps": 1e-06,
  "rope_theta": 1000000.0,
  "sliding_window": null,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.44.2",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 152064
}

## Qwen2.5-72B-GPTQ-INT3-G32：
{
  "_name_or_path": "tclf90/Qwen2.5-72B-Instruct-GPTQ-Int3-G32",
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 8192,
  "initializer_range": 0.02,
  "intermediate_size": 29568,
  "max_position_embeddings": 32768,
  "max_window_layers": 70,
  "model_type": "qwen2",
  "num_attention_heads": 64,
  "num_hidden_layers": 80,
  "num_key_value_heads": 8,
  "quantization_config": {
    "batch_size": 1,
    "bits": 3,
    "block_name_to_quantize": null,
    "cache_block_outputs": true,
    "damp_percent": 0.1,
    "dataset": null,
    "desc_act": false,
    "exllama_config": {
      "version": 1
    },
    "group_size": 32,
    "max_input_length": null,
    "model_seqlen": null,
    "module_name_preceding_first_block": null,
    "modules_in_block_to_quantize": null,
    "pad_token_id": null,
    "quant_method": "gptq",
    "sym": true,
    "tokenizer": null,
    "true_sequential": true,
    "use_cuda_fp16": true,
    "use_exllama": true
  },
  "rms_norm_eps": 1e-06,
  "rope_theta": 1000000.0,
  "sliding_window": null,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.44.2",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 152064
}
