### ISSUE TITLE
可以支持加载本地lora路径吗

### ISSUE THREAD

**Issue by LIUKAI0815** [InternLM/lmdeploy#2495]
用户只需要将 lora 权重的 huggingface 模型路径通过字典的形式传入 --adapters 即可。

可以加载本地lora路径吗？这个可以支持吗

**Comment by grimoire** [comment]
Sure

**Comment by tiaotiaosong** [comment]
> Sure

可以支持TurboMind后端的lora调用吗

**Comment by lvhan028** [comment]
> > Sure
> 
> 可以支持TurboMind后端的lora调用吗

turbomind现在仅支持了 internlm2-xcomposer的 plora
llm的lora，没有支持。目前，只能把 lora merge到主模型才可以。

**Comment by LIUKAI0815** [comment]
@grimoire 我用本地路径的lora，显示没有模型不能用

**Comment by LIUKAI0815** [comment]
> Sure

@grimoire 期待TurboMind也支持lora路径

**Comment by zzf2grx** [comment]
> > > Sure
> > 
> > 
> > 可以支持TurboMind后端的lora调用吗
> 
> turbomind现在仅支持了 internlm2-xcomposer的 plora llm的lora，没有支持。目前，只能把 lora merge到主模型才可以。

internvl2是否可以支持TurboMind的multi-lora加载呢？
