### ISSUE TITLE
[Bug] qwen2.5系列高并发情况下会出现无限死循环输出的情况

### ISSUE THREAD

**Issue by maxin9966** [InternLM/lmdeploy#2509]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

1. 模型是qwen2.5系列GPTQ-INT4官方模型，14b和32b都会遇到，
2. 高并发测试的时候，会出现这种无限循环输出的情况，如果不设置max_tokens将会永不休止的输出，例如64个并发，大概率会有3~4个请求出问题
3. 生产环境中没遇到过，可能因为负载不高
4. vllm运行相同模型在并发测试中没遇到这种问题。
5. 问题不是一定出现的，不确定是跟提示词有关，还是跟负载有关，或是其他问题。
##### 参数如下会出现问题：
64并发：
    content = f'{(i%10)}-写一个随机的故事，任意主题都可以，300字以上'
    completion = client.chat.completions.create(
        model=model_name,
        messages=[
            {"role": "user", "content": content}
        ],
        temperature=0.5,
        max_tokens=1024,
    )

##### 以下参数没问题：
64并发：
    content = f'写一个随机的故事，300字以上'
    completion = client.chat.completions.create(
        model=model_name,
        messages=[
            {"role": "user", "content": content}
        ],
        temperature=0.5,
        max_tokens=1024,
    )

#### 样例：
ChatCompletionMessage(content='在遥远的未来，地球已经发展成一个充满科幻色彩的世界，科技高度发达，人们的生活与机器人和人工智能紧密相连。在这样一个世界中，有一个名叫艾丽的小女孩，她拥有一颗纯真无邪的心，对这个世界充满了好奇。艾丽住在一个充满高科技的社区里，但她最喜欢的玩具却是一个古老的木制机器人——鲁夫。鲁夫并不是现代科技的产物，而是艾丽的曾祖父在很久以前为她的曾祖母制作的，它没有复杂的电子元件，也没有智能芯片，但却能发出温暖的光芒，和艾丽进行最简单但又最温馨的对话。\n\n一天，艾丽带着鲁夫来到了社区的中央公园，那里有一座巨大的时间旅行机器，这项技术虽然已存在，但使用它需要极其严格的安全措施，而且大部分时间仅用于科学研究。艾丽一直梦想着能见到她从未见过的曾祖父，她轻轻抚摸着鲁夫，突然灵机一动，她决定偷偷使用时间机器，穿越回曾祖父的时代，希望能见到他。\n\n艾丽带着鲁夫偷偷地坐上了时间机器，输入了她曾祖父出生的时间。当她睁开眼睛时，她发现自己来到了一个完全不同的世界。这里的科技远没有她熟悉的那样发达，人们穿着不同的服装，使用的工具也完全不同。艾丽找到了曾祖父年轻时的照片，她沿着照片上的线索找到了曾祖父。曾祖父是一位机械师，他正在修理各种机械，当他看到艾丽和鲁夫时，惊讶不已。艾丽向他解释了她是来自未来的孩子，鲁夫就是他年轻时为曾祖母制作的木制机器人。\n\n曾祖父被艾丽的真诚所打动，他不仅没有责备艾丽擅自使用时间机器，反而带着她参观了他的工作室，向她展示了如何制作木制机器人，并告诉她，真正的创造不仅在于技术，更在于情感和故事。艾丽在曾祖父的指导下，亲手为鲁夫添加了一些小功能，比如让他可以发出温暖的光芒，和她进行简单的对话。\n\n这次穿越不仅让艾丽见到了她一直渴望见到的曾祖父，还让她学会了更多关于爱与创造的意义。她带着满满的回忆和鲁夫回到了未来，鲁夫不仅成为了她最珍贵的玩具，更是她与曾祖父之间的联系。从此，艾丽更加珍惜与家人之间的每一刻，她也明白了，无论是过去还是未来，最重要的是人与人之间的情感联系。', refusal=None, role='assistant', function_call=None, tool_calls=None)
47 结果返回
success_count: 61
ChatCompletionMessage(content='在一个遥远的星球上，有一种名为“数珠”的神秘植物。这种植物非常特别，它的种子由一串串的数字组成，每一个数字都承载着不同的力量。在这个星球上，有一个小镇，镇上住着一位名叫小明的青年。小明自小就对这些充满力量的数字种子充满了好奇，他梦想着能够找到一种特殊的种子，用它来帮助小镇解决水资源短缺的问题。\n\n一天，小明在森林深处发现了一株特别的“数珠”植物，这株植物上挂着一串长长的数字：“444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444”。小明小心翼翼地将这串种子摘下，他发现这串种子散发出独特的光芒，似乎蕴含着强大的力量。\n\n经过研究，小明发现这串数字种子具有召唤水源的能力。他按照古老的仪式，将种子种在小镇边的一片干旱的土地上，然后念出了一段古老的咒语。奇迹发生了，随着种子的生长，一个清澈的泉水从地下涌出，为小镇带来了丰富的水资源，解决了长期困扰小镇的干旱问题。小明成为了小镇的英雄，而神奇的“数珠”种子也成为了传说中的宝藏，激励着后来的探险者们去探索未知的奇迹。从此，小镇的人们过上了幸福的生活，而小明的故事也成为了传说，激励着后来的探险者们去探索未知的奇迹。', refusal=None, role='assistant', function_call=None, tool_calls=None)
34 结果返回
success_count: 62
ChatCompletionMessage(content='在遥远的宇宙中，有一颗名为“六六星”的神秘星球。这颗星球的名字来源于其奇特的六边形结构，每一面都散发着柔和的光芒，仿佛夜空中最亮的星星。六六星上生活着一群名为“六六族”的智慧生物，他们拥有着与数字6666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666', refusal=None, role='assistant', function_call=None, tool_calls=None)
16 结果返回
success_count: 63
ChatCompletionMessage(content='在遥远的未来，地球之外的星系里，有一个名为“维纳斯利亚”的星球。这颗星球上，生活着一群拥有着超凡智慧和独特能力的生物——光灵族。他们不以物质为生，而是通过吸收星球上特殊的“光元素”来维持生命。光元素是维纳斯利亚星球上最珍贵的资源，它不仅滋养着光灵族，还孕育着绚丽多彩的光之森林。\n\n77777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777777', refusal=None, role='assistant', function_call=None, tool_calls=None)

### Reproduction

CUDA_VISIBLE_DEVICES=1,3 lmdeploy serve api_server /home/ma/work/modelscope/Qwen2.5-32B-Instruct-GPTQ-Int4 --backend turbomind --model-format gptq --server-port 1232 --session-len 16500 --cache-max-entry-count 0.6 --model-name gpt --max-batch-size 128 --tp 2 --enable-prefix-caching

### Environment

```Shell
0.6.0最新版本
```

**Comment by AllentDan** [comment]
只有  GPTQ 模型有这个问题吗？还是 AWQ 也有？试试 tp 是 1 的情况呢

**Comment by songyinghao** [comment]
参数设置请按照通义模型的generation congfig进行设置。(在模型文件夹里面)
