### ISSUE TITLE
[Feature]  Atlas 800I A2 Support

### ISSUE THREAD

**Issue by zysuper** [InternLM/lmdeploy#2510]
### Motivation

Very glad to see that lmdeploy already supports Atlas 800T A2. Is it possible to directly support Atlas 800I A2 on this basis? Looking forward to it. tks.

**Comment by jinminxi104** [comment]
> Is it possible to directly support Atlas 800I A2 on this basis?
We think current version supports Atlas 800I A2. All LLM-related operators are supported on both Atlas 800T A2 and Atlas 800I A2.

**Comment by zysuper** [comment]
> > Is it possible to directly support Atlas 800I A2 on this basis?是否可以在此基础上直接支持 Atlas 800I A2？
> 
> We think current version supports Atlas 800I A2. All LLM-related operators are supported on both Atlas 800T A2 and Atlas 800I A2.我们认为当前版本支持 Atlas 800I A2。Atlas 800T A2 和 Atlas 800I A2 都支持所有 LLM 相关的算子。

Thank you for your reply. I will follow your guide to test the actual deployment situation of the Atlas 800I A2.

**Comment by zysuper** [comment]
Hello, during the verification process, I discovered an issue. The official website shows that the highest version of Atlas 800I A2 Community Edition available is 8.0.RC1.beta1, and it doesn't reach 8.0.RC3.alpha001.

**Comment by zysuper** [comment]
The Docker image I created with 8.0.RC3.alpha001 runs perfectly on the Atlas 800I A2. This issue can be closed. Thanks to the lmdeploy team for the excellent project. 😀

**Comment by lvhan028** [comment]
Cheers. This feature was developed by our partner, the Deeplink team. We are deeply honored and grateful. Thank you for your support.

**Comment by holoodst** [comment]
@zysuper 大佬，因为各种原因我们在Atlas 800上构建image总是失败，能否分享一下制作完成的image 感激不仅
