### ISSUE TITLE
[Feature] 对比vllm推理速度

### ISSUE THREAD

**Issue by senlice** [InternLM/lmdeploy#2532]
### Motivation

使用的模型为Qwen2.5-32B-Instruct-AWQ，在单条推理时速度为vllm的1.6倍。但是使用batch进行测试的时候，推理速度相差并不大，大约为1.1倍的样子。为什么单条推理速度快这么多，批量而言的话，速度差不多呢。

**Comment by lvhan028** [comment]
是怎么测试的？

**Comment by fffddd1928** [comment]
请问占用运行显存多大

**Comment by senlice** [comment]
> 是怎么测试的？

在同一个任务里面分别用vllm、lmdeploy进行加载推理模型。
1、利用vllm加载
` def vllm_load_model(base_model_path, gpu_memory_utilization, tensor_parallel_size,max_model_len):
        tokenizer = AutoTokenizer.from_pretrained(base_model_path)
        llm = LLM(model=base_model_path,
                  gpu_memory_utilization=gpu_memory_utilization,
                  tensor_parallel_size=tensor_parallel_size,
                  max_model_len=max_model_len)
        return llm, tokenizer`
2、利用lmdeploy加载
`def load_model(model_path):
    tokenizer = AutoTokenizer.from_pretrained(model_path)
    backend_config = TurbomindEngineConfig(model_format='awq', tp=2, cache_max_entry_count=0.85, log_level='INFO')
    llm = pipeline(model_path, backend_config=backend_config)
    return llm, tokenizer`
然后输入一样，统计推理用时

**Comment by lvhan028** [comment]
可以看下README里的图。turbomind w4a16 vs fp16 在小batch下，w4a16 的性能大约是 fp16 的2 倍。随着 batch 的增大，差异慢慢减小。毕竟 w4a16 还有dequant的操作
