### ISSUE TITLE
[warning] WARNING: Can not find tokenizer.json 

### ISSUE THREAD

**Issue by wodeqiansuihan** [InternLM/lmdeploy#254]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

WARNING: Can not find tokenizer.json when i use baichuan-7b 

### Reproduction

python -m lmdeploy.serve.openai.api_server ./workspace/ 0.0.0.0 5005

**Comment by wodeqiansuihan** [comment]
llama_7b_hf 、llama2 has the same warning

**Comment by lvhan028** [comment]
https://github.com/InternLM/lmdeploy/issues/132#issuecomment-1639594270 
希望这个能够帮到你

**Comment by viktor-ferenczi** [comment]
Please reopen this.

Happens to this model as well: llama2-chat-13b-w4

```
WARNING: Can not find tokenizer.json. It may take long time to initialize the tokenizer.
```

There is no tokenizer.json in the model folder.
