### ISSUE TITLE
[Feature] 请支持molmo视觉大模型

### ISSUE THREAD

**Issue by win4r** [InternLM/lmdeploy#2541]
### Motivation

https://youtu.be/gtcOncFLMeo

### Related resources

https://youtu.be/gtcOncFLMeo

### Additional context

https://youtu.be/gtcOncFLMeo

**Comment by lvhan028** [comment]
已经支持了如下模型：
allenai/Molmo-72B-0924
allenai/Molmo-7B-D-0924
