### ISSUE TITLE
[Bug] qwen2 vl does not support the turbomind engine

### ISSUE THREAD

**Issue by windar427** [InternLM/lmdeploy#2546]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Registry of source model                                   

│Names     │Objects                                                                      │
│ baichuan   │ <class 'lmdeploy.turbomind.deploy.source_model.baichuan.BaichuanModel'>      │
│ baichuan2  │ <class 'lmdeploy.turbomind.deploy.source_model.baichuan.Baichuan2Model'>     │
│ deepseekvl │ <class 'lmdeploy.turbomind.deploy.source_model.deepseek_vl.DeepSeekVLModel'> │
│ glm4       │ <class 'lmdeploy.turbomind.deploy.source_model.glm4.Glm4Model'>              │
│ internlm2  │ <class 'lmdeploy.turbomind.deploy.source_model.internlm2.InternLM2Model'>    │
│ internvl   │ <class 'lmdeploy.turbomind.deploy.source_model.internvl.InternVLModel'>      │
│ llama      │ <class 'lmdeploy.turbomind.deploy.source_model.llama.LlamaModel'>            │
│ meta_llama │ <class 'lmdeploy.turbomind.deploy.source_model.meta_llama.MetaLlamaModel'>   │
│ minicpmv   │ <class 'lmdeploy.turbomind.deploy.source_model.minicpmv.MiniCPMVModel'>      │
│ qwen       │ <class 'lmdeploy.turbomind.deploy.source_model.qwen.QwenModel'>              │
│ qwen2      │ <class 'lmdeploy.turbomind.deploy.source_model.qwen.Qwen2Model'>             │
│ xcomposer2 │ <class 'lmdeploy.turbomind.deploy.source_model.xcomposer2.Xcomposer2Model'>  │

### doc
![image](https://github.com/user-attachments/assets/6ecb2d00-6529-44a0-804e-6a7ef489ebc7)

###  bug
In this project, there is no code supporting qwen2vl turbomind, but the documentation shows support for the turbomind engine

### Reproduction

lmdeploy convert $MODEL_NAME $HF_MODEL_PATH --dst-path ./workspace --model-format hf

### Environment

```Shell
lmdeploy                          0.6.1
```

**Comment by lvhan028** [comment]
This is not a bug but a fact, i.e., turbomind engine hasn't supported yet.

**Comment by LinJianping** [comment]
> This is not a bug but a fact, i.e., turbomind engine hasn't supported it yet.

Is there any plan for support?
