### ISSUE TITLE
[Docs] InternVL2-4B使用awq量化报错

### ISSUE THREAD

**Issue by Mrgengli** [InternLM/lmdeploy#2548]
### 📚 The doc issue

![image](https://github.com/user-attachments/assets/54507f05-9560-4b46-a8ae-83dd1e362969)
InternVL2-4B使用awq量化报错，请问怎么解决呢？

**Comment by AllentDan** [comment]
降 transformers 版本吧，最新版的没法加载后保存 InternVL -4B 模型。

**Comment by lvhan028** [comment]
PR #2583 is addressing this issue
