### ISSUE TITLE
[Feature] Please add support for Llama 3.2

### ISSUE THREAD

**Issue by cuong-dyania** [InternLM/lmdeploy#2549]
### Motivation

The Llama 3.2 family models are applicable for small devices such as smart cameras or mobile phones. But it seems lmdeploy currently does not support for Llama 3.2

When I started to use the Llama 3.2 model for example:
model_id = "meta-llama/Llama-3.2-11B-Vision"
backend_config = TurbomindEngineConfig(cache_max_entry_count=0.2, tp =2, enable_prefix_caching=True)
pipe = pipeline(model_id,backend_config=backend_config)

It showed the following error.

```
212 config = __check_config(trans_version)
    213 __check_model_transformers_version(config, trans_version)
--> 214 __check_model_dtype_support(config)
    215 check_awq(config)


 204 except Exception as e:
    205     message = (f'Checking failed with error {e}',
    206                'Please send issue to LMDeploy with error logs.')
--> 207     _handle_exception(e, 'Model', logger, message=message)
    209 return model_config


 17 logger.error(f'{type(e).__name__}: {e}')
     18 logger.error(f'{red_color}'
     19              f'<{mod_name}> test failed!\n'
     20              f'{message}'
     21              f'{reset_color}')
---> 22 exit(1)
```

**Comment by lvhan028** [comment]
It has been supported. May try the latest version
