### ISSUE TITLE
建了一个多模态大模型技术交流群，欢迎加入交流 

### ISSUE THREAD

**Issue by feihuamantian** [InternLM/lmdeploy#2557]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

可以扫二维码加入，或是加我微信拉入群：yx116169
https://private-user-images.githubusercontent.com/28010145/369731989-cb34c72c-32be-465f-bb14-a24e5225b262.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzODM2MDksIm5iZiI6MTcyODM4MzMwOSwicGF0aCI6Ii8yODAxMDE0NS8zNjk3MzE5ODktY2IzNGM3MmMtMzJiZS00NjVmLWJiMTQtYTI0ZTUyMjViMjYyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDEwMjgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhZGU0MDc3N2I4ZGVjNzZkNjBhZWI0Y2QyNDU2ZGVhZjRlNDRmNzllMGVhZDY3OTRkNTY3NzE2NzljZjhkZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.a_uwpT6WKvwDFppf2aOa8AYWcIGmJf_Lh__Fl9fN2Xg

### Reproduction

1

### Environment

```Shell
1
```

### Error traceback

```Shell
1
```

**Comment by lvhan028** [comment]
Closing it as it is irrelevant to this project.
Users who are interested in multimodal technologies can join the Interval group for communication.
https://github.com/OpenGVLab/InternVL
