### ISSUE TITLE
[Feature] Are there any plans to support Molmo?

### ISSUE THREAD

**Issue by sudanl** [InternLM/lmdeploy#2562]
### Motivation

Hi! Molmo's performance is currently leading in VLMs. Could this project support it?

### Related resources

https://molmo.allenai.org/blog

**Comment by lvhan028** [comment]
@irexyc may put this request in the working list

**Comment by thesby** [comment]
molmo模型效果非常好，希望能够支持

**Comment by lvhan028** [comment]
支持了以下 molmo 模型
- allenai/Molmo-7B-D-0924
- allenai/Molmo-72B-0924
