### ISSUE TITLE
[Bug] internvl 4B awq推理 Engine loop failed with error: module 'triton.language' has no attribute 'inline_asm_elementwise'

### ISSUE THREAD

**Issue by Mrgengli** [InternLM/lmdeploy#2566]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

i have install triton-2.3.1,lmdeploy==0.6.1,but got the error below:
![image](https://github.com/user-attachments/assets/4bd655a2-ee0e-444c-a178-aeee06f5af67)

### Reproduction

1

### Environment

```Shell
1
```

**Comment by lvhan028** [comment]
Pls share the information after executing `lmdeploy check_env`

**Comment by Mrgengli** [comment]
thanks for you reply! this is the env below:
![image](https://github.com/user-attachments/assets/fb135533-9a07-4a22-9cf7-56cf515f6980)

**Comment by Mrgengli** [comment]
thanks for your reply! this is the env below:
![image](https://github.com/user-attachments/assets/f507b919-30cd-43bd-8ff7-e102337b839b)

**Comment by AllentDan** [comment]
You were still using triton2.1.0. Please make sure the correct triton version was installed.

**Comment by Mrgengli** [comment]
@AllentDan which is the right version please?i have tried deferent version,but other problem is happend.
![image](https://github.com/user-attachments/assets/318085be-4a01-4fc9-aed9-377368c871ce)

**Comment by AllentDan** [comment]
As `lmdeploy check_env` shows, you were using triton 2.1. Please install it correctly.

Or, you can use docker env. https://hub.docker.com/r/openmmlab/lmdeploy/tags

**Comment by grimoire** [comment]
Gcc 4.8.5 is not compatible with your triton environment.

We run a simple add kernel as the environment check before launching our engine.

https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/pytorch/check_env/triton_custom_add.py

Please make sure that `custom_add` can be used in your environment.

**Comment by Mrgengli** [comment]
@grimoire I have successfully run triton_custom_add.py,but still got the same error.
![image](https://github.com/user-attachments/assets/176c7830-441a-491c-82a0-1b83367568ca)

**Comment by Mrgengli** [comment]
@grimoire I have successfully run triton_custom_add.py,but still got the same error.
![image](https://github.com/user-attachments/assets/559630c1-c5f5-4f09-95ba-63c3b3196368)

**Comment by grimoire** [comment]
This Error comes from `custom_add`

https://github.com/InternLM/lmdeploy/blob/4492df812363d112aed9151a3ff7e26a654d36ea/lmdeploy/pytorch/check_env/__init__.py#L77-L81

Please double check `custom_add` and make sure the code above can be used.

**Comment by Mrgengli** [comment]
@grimoire I have run custom_add and got the error below.could you tell me how to solve it please?
![image](https://github.com/user-attachments/assets/371c1adf-b87e-4c86-820a-c7dc1b726e43)

**Comment by grimoire** [comment]
> Gcc 4.8.5 is not compatible with your triton environment.

**Comment by Mrgengli** [comment]
@AllentDan hello,why I can not successfully pull the docker?
![image](https://github.com/user-attachments/assets/3a764408-3fc1-4579-b78e-eef01ba8f3a0)

**Comment by Mrgengli** [comment]
@grimoire @AllentDan I have successfully run the awq model since I change the right version of gcc.Thanks for all your reply.
