### ISSUE TITLE
[Feature] 支持模型并行和量化同时进行吗？

### ISSUE THREAD

**Issue by zhangjunyi111** [InternLM/lmdeploy#257]
### Motivation

支持模型并行和量化同时进行吗？

**Comment by zhangjunyi111** [comment]
@lzhangzz 什么意思没看明白，我看你那个commit没有合入，具体怎么用啊 W4A16在v100 gpu上能用吗

**Comment by lvhan028** [comment]
V100上暂不支持 W4A16。
W4A16 目前对 NVIDIA GPU的最低要求是 SM80。 V100是SM70的。

**Comment by zhangjunyi111** [comment]
> V100上暂不支持 W4A16。
> W4A16 目前对 NVIDIA GPU的最低要求是 SM80。 V100是SM70的。

好的感谢。
