### ISSUE TITLE
[Bug] pipeline如何指定显卡进行推理，例如我想使用cuda:1进行推理，目前文档还没发现如何设置

### ISSUE THREAD

**Issue by aizhweiwei** [InternLM/lmdeploy#2592]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

 pipeline如何指定显卡进行推理，例如我想使用cuda:1进行推理，目前文档还没发现如何设置

### Reproduction

 pipeline如何指定显卡进行推理，例如我想使用cuda:1进行推理，目前文档还没发现如何设置

### Environment

```Shell
pipeline如何指定显卡进行推理，例如我想使用cuda:1进行推理，目前文档还没发现如何设置
```

**Comment by lvhan028** [comment]
CUDA_VISIBLE_DEVICES=1 python <your python script>

**Comment by xiexinch** [comment]
> CUDA_VISIBLE_DEVICES=1 python

请问可以在单机支持多个实例吗，在一个程序里启动多个模型实例，例如这样：
```python
import lmdeploy

pipe1 = lmdeploy.pipeline('xxx', device='cuda:0')
pipe2 = lmdeploy.pipeline('xxx', device='cuda:1'')
pipe3 = lmdeploy.pipeline('xxx', device='cuda:2'')
pipe4 = lmdeploy.pipeline('xxx', device='cuda:3'')

```

**Comment by lvhan028** [comment]
不支持 device参数。你可以尝试 torchrun
