### ISSUE TITLE
[Bug] 使用lmdeploy serve api_server启动的服务，多线程调用openai接口调用时，即使设置了 temperature=0,  seed = 17002729324219322736,输出结果仍然具有随机性。

### ISSUE THREAD

**Issue by tiaotiaosong** [InternLM/lmdeploy#2593]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

lmdeploy serve api_server /data/opensource/qwen-ckpts/Qwen2.5-14B-Instruct --adapters  --server-name 0.0.0.0 --server-port 24444
上述命令情动服务
[Bug] 使用lmdeploy serve api_server启动的服务，多线程调用openai接口调用时(即batch_size>1)，即使设置了 temperature=0,  seed = 17002729324219322736,输出结果仍然具有随机性。单线程调用时结果是确定的。

### Reproduction

`from concurrent.futures import ThreadPoolExecutor, as_completed
from openai import OpenAI
from termcolor import colored

def stream_chat(messages, stream=False, **kwargs):
    client = OpenAI(api_key="YOUR_API_KEY", base_url="http://0.0.0.0:24444/v1")
    if isinstance(messages, str):
        messages = [{"role": "user", "content": messages}]
    model_name = client.models.list().data[0].id
    response = client.chat.completions.create(
        model=model_name,
        messages=messages,
        stream=stream,
        temperature=0,
        seed = 17002729324219322736,
        max_tokens = 500,
    )
    history = list(messages)
    response_text = ""

    if stream:
        for chunk in response:
            if chunk.choices and len(chunk.choices) > 0:
                delta = chunk.choices[0].delta
                if delta.content:
                    response_text += delta.content
                    print(colored(delta.content, "blue"), end="")
        print()
    else:
        response_text = response.choices[0].message.content
    response_dict = {"role": "assistant", "content": response_text}
    history.append(response_dict)
    return history, response_text

def print_response_with_color(response_text, color):
    print(colored(response_text, color), end="")
    print()  # 打印一个换行符以结束输出

for i in range(5):
    colors = ["light_yellow", "light_cyan", "light_green", "light_red","light_magenta","light_yellow", "light_cyan", "light_green", "light_red","light_magenta"]
    executor = ThreadPoolExecutor(max_workers=10)
    futures = [executor.submit(stream_chat, "就时间管理提出三点建议。") for i in range(1)]
    for future in as_completed(futures):
        history, response_text = future.result()
        print_response_with_color(response_text, colors.pop(0))
    # input()from concurrent.futures import ThreadPoolExecutor, as_completed
from openai import OpenAI
from termcolor import colored

def stream_chat(messages, stream=False, **kwargs):
    client = OpenAI(api_key="YOUR_API_KEY", base_url="http://0.0.0.0:24444/v1")
    if isinstance(messages, str):
        messages = [{"role": "user", "content": messages}]
    model_name = client.models.list().data[0].id
    response = client.chat.completions.create(
        model=model_name,
        messages=messages,
        stream=stream,
        temperature=0,
        seed = 17002729324219322736,
        max_tokens = 500,
    )
    history = list(messages)
    response_text = ""

    if stream:
        for chunk in response:
            if chunk.choices and len(chunk.choices) > 0:
                delta = chunk.choices[0].delta
                if delta.content:
                    response_text += delta.content
                    print(colored(delta.content, "blue"), end="")
        print()
    else:
        response_text = response.choices[0].message.content
    response_dict = {"role": "assistant", "content": response_text}
    history.append(response_dict)
    return history, response_text

def print_response_with_color(response_text, color):
    print(colored(response_text, color), end="")
    print()  # 打印一个换行符以结束输出

for i in range(5):
    colors = ["light_yellow", "light_cyan", "light_green", "light_red","light_magenta","light_yellow", "light_cyan", "light_green", "light_red","light_magenta"]
    executor = ThreadPoolExecutor(max_workers=10)
    futures = [executor.submit(stream_chat, "就时间管理提出三点建议。") for i in range(1)]
    for future in as_completed(futures):
        history, response_text = future.result()
        print_response_with_color(response_text, colors.pop(0))
    # input()`

### Environment

```Shell
sys.platform: linux
Python: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA A100-SXM4-80GB
CUDA_HOME: /usr
NVCC: Cuda compilation tools, release 11.5, V11.5.119
GCC: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 2.3.1+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.6 (Git Hash 86e6af5974177e513fd3fee58425e1063e7f1361)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.3.1, USE_CUDA=ON, USE_CUDNN=ON, USE_CUSPARSELT=1, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_GLOO=ON, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

TorchVision: 0.18.1+cu121
LMDeploy: 0.6.0+
transformers: 4.44.2
gradio: Not Found
fastapi: 0.115.0
pydantic: 2.9.2
triton: 2.3.1
NVIDIA Topology: 
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    NIC1    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NODE    NODE    NODE    SYS     SYS     SYS     SYS     SYS     SYS     0-31,64-95      0               N/A
GPU1    NODE     X      NODE    NODE    SYS     SYS     SYS     SYS     SYS     SYS     0-31,64-95      0               N/A
GPU2    NODE    NODE     X      NODE    SYS     SYS     SYS     SYS     SYS     SYS     0-31,64-95      0               N/A
GPU3    NODE    NODE    NODE     X      SYS     SYS     SYS     SYS     SYS     SYS     0-31,64-95      0               N/A
GPU4    SYS     SYS     SYS     SYS      X      NODE    NODE    NODE    NODE    NODE    32-63,96-127    1               N/A
GPU5    SYS     SYS     SYS     SYS     NODE     X      NODE    NODE    NODE    NODE    32-63,96-127    1               N/A
GPU6    SYS     SYS     SYS     SYS     NODE    NODE     X      NODE    PHB     PHB     32-63,96-127    1               N/A
GPU7    SYS     SYS     SYS     SYS     NODE    NODE    NODE     X      NODE    NODE    32-63,96-127    1               N/A
NIC0    SYS     SYS     SYS     SYS     NODE    NODE    PHB     NODE     X      PIX
NIC1    SYS     SYS     SYS     SYS     NODE    NODE    PHB     NODE    PIX      X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
```

**Comment by lvhan028** [comment]
正常现象。因为是continuous batching，推理时的shape不一样，kernel可能dispatch到不同的方法上。
如果追求输出不变，启动服务的时候可以设置下 `--max-batch-size 1`
