### ISSUE TITLE
[Bug] profile_serving failed ,site-packages/lmdeploy/serve/turbomind/chatbot.py - stream_consumer - 612 - got error from turbomind, code StatusCode.TRITON_SERVER_ERR, TurboMind execute failure: std::future_error: Broken promise, token 0

### ISSUE THREAD

**Issue by changxiaodongTHU** [InternLM/lmdeploy#260]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

benchmark test
python profile_serving.py 10.140.0.187:33337 tokenizer.model ShareGPT_V3_unfiltered_cleaned_split.json --concurrency 32

log:

08/16 19:09:25 - service.ft - ERROR - /home/PJLAB/changxiaodong/anaconda3/envs/lmdeploy_005/lib/python3.10/site-packages/lmdeploy/serve/turbomind/chatbot.py - stream_consumer - 612 - got error from turbomind, code StatusCode.TRITON_SERVER_ERR, TurboMind execute failure: std::future_error: Broken promise, token 0
08/16 19:09:25 - service.ft - INFO - session 10, request_id , request_output_len 2047
08/16 19:09:25 - service.ft - INFO - session 10, request id , request_output_len 2047, start True, end True, cancel False
08/16 19:09:25 - service.ft - INFO - session 10, clear history since sequence_start is True
08/16 19:09:25 - service.ft - INFO - session 11, request_id , request_output_len 2047
08/16 19:09:25 - service.ft - INFO - session 11, request id , request_output_len 2047, start True, end True, cancel False
08/16 19:09:25 - service.ft - INFO - session 11, clear history since sequence_start is True
08/16 19:09:25 - service.ft - INFO - session 9, max length: 2048, input tokens: 1, request tokens: 2047, history tokens: 0
08/16 19:09:25 - service.ft - INFO - session 8, max length: 2048, input tokens: 1, request tokens: 2047, history tokens: 0
TurboMind execute failure: std::future_error: Broken promise
TurboMind execute failure: std::future_error: Broken promise
08/16 19:09:25 - service.ft - ERROR - /home/PJLAB/changxiaodong/anaconda3/envs/lmdeploy_005/lib/python3.10/site-packages/lmdeploy/serve/turbomind/chatbot.py - stream_consumer - 612 - got error from turbomind, code StatusCode.TRITON_SERVER_ERR, TurboMind execute failure: std::future_error: Broken promise, token 0
08/16 19:09:25 - service.ft - INFO - session 12, request_id , request_output_len 2047
08/16 19:09:25 - service.ft - INFO - session 12, request id , request_output_len 2047, start True, end True, cancel False
08/16 19:09:25 - service.ft - INFO - session 12, clear history since sequence_start is True
08/16 19:09:25 - service.ft - ERROR - /home/PJLAB/changxiaodong/anaconda3/envs/lmdeploy_005/lib/python3.10/site-packages/lmdeploy/serve/turbomind/chatbot.py - stream_consumer - 612 - got error from turbomind, code StatusCode.TRITON_SERVER_ERR, TurboMind execute failure: std::future_error: Broken promise, token 0

### Reproduction

server:
bash workspace/service_docker_up.sh
client:
python profile_serving.py 10.140.0.187:33337 tokenizer.model ShareGPT_V3_unfiltered_cleaned_split.json --concurrency 32

**Comment by lvhan028** [comment]
Please share the tested version

**Comment by lvhan028** [comment]
Can the `client.py` work?

**Comment by changxiaodongTHU** [comment]
- 框架信息：https://github.com/InternLM/lmdeploy/tree/v0.0.5
- 镜像版本：openmmlab/lmdeploy:0.0.5
- 环境： 
  - GPU:A100*8
  - Driver Version: 515.86.01
起docker时TP=8
concurrency 1 正常
concurrency 32 报错

**Comment by lvhan028** [comment]
测试的是哪个模型呢？现在dockerhub上没有 openmmlab/lmdeploy:v0.0.5 镜像

**Comment by changxiaodongTHU** [comment]
model: internlm_7b
git clone https://huggingface.co/internlm/internlm-chat-7b

**Comment by lvhan028** [comment]
把模型部署的命令可以分享一下吗？包括 deploy.py 部分。
这个模型在A100上用不到TP

**Comment by changxiaodongTHU** [comment]
在A100上用不到TP。我把TP改成1后，可以了，多谢，问题已解决。
