### ISSUE TITLE
[Feature] TurbomindEngine generate LogitsProcessor

### ISSUE THREAD

**Issue by BlueBlueFF** [InternLM/lmdeploy#2600]
### Motivation

TurbomindEngine 生成时候是否支持 LogitsProcessor这个参数，方便做一些自定义操作，比如设置penalty忽略某些special token

**Comment by lvhan028** [comment]
turbomind engine 不支持。
pytorch engine 支持。https://github.com/InternLM/lmdeploy/blob/88eccb20402ec93dc29074c9bbf13ea7b5ce6103/lmdeploy/messages.py#L99
