### ISSUE TITLE
OOM Issue

### ISSUE THREAD

**Issue by poppybrown** [InternLM/lmdeploy#2603]
环境：A100
在使用Gemma2时按照下述方式加载模型，将max_batch_size设置为不同大小进行推理，推理数据大小1000(need_infer)
`pipe = lmdeploy.pipeline(model_path=model_id,backend_config=TurbomindEngineConfig(max_batch_size=256, cache_max_entry_count=0.8))
geneartion_config = GenerationConfig(max_new_tokens=700,top_p=0.95,temperature=0)
outputs = pipe(need_infer, gen_config=geneartion_config)
`

1.max_batch_size设置为30，正常推理不会OOM
2.max_batch_size设置为256，推理时报OOM

lmdeploy应该是动态batch机制，为什么max_batch_size设置为256时会出现错误呢？

**Comment by RunningLeon** [comment]
@poppybrown hi,
1. 只有pytorch engine 支持Gemma-2模型
2. pytorch engine已经支持cudagraph，默认是开启的，[max_batches](https://github.com/InternLM/lmdeploy/blob/ba3701b57548e81aec88e2d5861a9915a5463ca7/lmdeploy/pytorch/models/utils/cudagraph.py#L57)影响输入大小进而影响推理时GPU占用大小
3. 你可以关闭cudagraph再次试试 `PytorchEngineConfig(eager_mode=True)`

**Comment by poppybrown** [comment]
> @poppybrown hi,
> 
> 1. 只有pytorch engine 支持Gemma-2模型
> 2. pytorch engine已经支持cudagraph，默认是开启的，[max_batches](https://github.com/InternLM/lmdeploy/blob/ba3701b57548e81aec88e2d5861a9915a5463ca7/lmdeploy/pytorch/models/utils/cudagraph.py#L57)影响输入大小进而影响推理时GPU占用大小
> 3. 你可以关闭cudagraph再次试试 `PytorchEngineConfig(eager_mode=True)`

多谢回答，还有两个问题
设置1:pipe = lmdeploy.pipeline(model_path=model_id,backend_config=PytorchEngineConfig(max_batch_size=32, cache_max_entry_count=0.8,eager_mode=True))
设置2:pipe = lmdeploy.pipeline(model_path=model_id,backend_config=PytorchEngineConfig(max_batch_size=4, cache_max_entry_count=0.8,eager_mode=True))
设置3:pipe = lmdeploy.pipeline(model_path=model_id,backend_config=PytorchEngineConfig(max_batch_size=4, cache_max_entry_count=0.8))
问题1：设置1和设置2不会OOM，设置3会OOM，可以看到按照设置1和设置3对比，设置1的max_batch_size更大，没有OOM，但是设置3因为eager_mode=False,max_batch_size更小OOM了，想问下为什么呢？

问题2:设置max_batch_size后，推理的时候是默认batch_size为max_batch_size吗？还是说框架会根据GPU剩余显存，自动调度到<=max_batch_size的一个合适的值？如果会自动调度到一个合适的batch_size,为什么会OOM呢？

**Comment by RunningLeon** [comment]
@poppybrown hi, 首先eager_mode=False代表关闭cudagraph,此时模型输入shape不会做padding. 而eager_mode=True时会对模型输入进行padding到固定shape,再送入模型。
问题1： 当开启cudagraph时，输入要padding到固定shape，`max_tokens`对影响输入的seq_len，而`max_batches`影响batch维度，且这两个值都会align到最近的2^n的值，所以很可能的导致OOM
问题2: max_batch_size只是设定模型推理时最大可同时处理的seq数量，如果cudagraph关闭，那么会根据输入自动调整，如果cudagraph开启，则会根据输入动态的调整至最近的2^n的值

**Comment by poppybrown** [comment]
> @poppybrown hi, 首先eager_mode=False代表关闭cudagraph,此时模型输入shape不会做padding. 而eager_mode=True时会对模型输入进行padding到固定shape,再送入模型。 问题1： 当开启cudagraph时，输入要padding到固定shape，`max_tokens`对影响输入的seq_len，而`max_batches`影响batch维度，且这两个值都会align到最近的2^n的值，所以很可能的导致OOM 问题2: max_batch_size只是设定模型推理时最大可同时处理的seq数量，如果cudagraph关闭，那么会根据输入自动调整，如果cudagraph开启，则会根据输入动态的调整至最近的2^n的值

多谢解答
1. 但是我上面例子是eager_mode=False的时候反而是OOM，eager_mode=False代表关闭cudagraph，和你解释的是否有出入？
2. 按照回答不管是eager_mode=False还是eager_mode=True都是会按照输入动态调整推理时的batch_size(max_batch_size只是设定模型推理时最大可同时处理的seq数量),动态调整了为什么还是会oom呢？
