### ISSUE TITLE
[Feature] qwen2.5 是否可以支持tool_calls传入？

### ISSUE THREAD

**Issue by akai-shuuichi** [InternLM/lmdeploy#2610]
### Motivation

传入tools参数后服务无法按照预期返回，我是否可以根据https://github.com/InternLM/lmdeploy/pull/2147/files 这个例子尝试支持qwen2.5的工具调用？

**Comment by songyinghao** [comment]
可以脱离lmdeploy实现的，2.5的函数调用依然是 基于system\user\assistant实现的。自己解析tool_call和tool_response既可
