### ISSUE TITLE
ptxas /tmp/tmpxft_000163d1_00000000-8_gemm_s4_f16.compute_75.ptx, line 48116; error   : Not a name of any known instruction: 'movmatrix' [Feature] 

### ISSUE THREAD

**Issue by wenjunlong** [InternLM/lmdeploy#264]
### Motivation

这是编译的时候报的错。movmatrix 这个指令似乎要到很新版本的cuda里才支持。目前大量的机器运行的cuda版本应该达不到这个要求。能否提供一个编译选项，可以禁用掉这个指令正常完成编译。

find_package(CUDA 10.2 REQUIRED) cmake的配置里要求的是 10.2，实际 movmatrix 要到 11.8才出现

### Related resources

![image](https://github.com/InternLM/lmdeploy/assets/7665366/5822a2c0-52c8-4c46-b0bb-4f5ca2925488)
![image](https://github.com/InternLM/lmdeploy/assets/7665366/887a3bf7-d820-40eb-9008-d7737001dc88)

**Comment by wenjunlong** [comment]
find_package(CUDA 10.2 REQUIRED)  cmake的配置里要求的是 10.2，实际 movmatrix 要到 11.8才出现

**Comment by lzhangzz** [comment]
Replaced `movmatrix` with 2 warp shuffles, can you please verify if #267 helps?

**Comment by wenjunlong** [comment]
> Replaced `movmatrix` with 2 warp shuffles, can you please verify if #267 helps?

Yes, I have submitted my review with an approval， I guest another review is required.
