### ISSUE TITLE
batching部分代码疑问

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#265]
https://github.com/InternLM/lmdeploy/blob/main/src/turbomind/models/llama/LlamaBatch.cc#L782 到 786行，

请问为什么要把input_length减去1呀？

想了很久没有理解这里的用意。。

**Comment by lzhangzz** [comment]
把最后一个输入token留给生成阶段处理，主要是为了统一后面生成阶段的流程，不需要为context decode的结果（的最后一个token）专门跑一遍output embedding和sampling。

**Comment by frankxyy** [comment]
理解了，谢谢
