### ISSUE TITLE
[Bug] min_p from request is not used

### ISSUE THREAD

**Issue by ErykCh** [InternLM/lmdeploy#2682]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

Information about min_p in request is not used during inference:

![image](https://github.com/user-attachments/assets/edc48acd-6b7d-4c27-865f-c6f69e7d23b1)

### Reproduction

Create a request with min_p and check logs if parameter was used:

    response = requests.post(
        "http://localhost:8000/v1/chat/completions",
        headers={
            "Content-Type": "application/json",
        },
        json={
            "model": "Qwen_2.5",
            "messages": [
                {"role": "system", "content": ""},
                {"role": "user", "content": "Hi"}
            ],
            "presence_penalty": 0.0,
            "frequency_penalty": 0.0,
            "repetition_penalty": 1.05,
            "temperature": 0.1,
            "top_k": 2,
            "top_p": 0.9,
            "min_p": 0.3,
            "max_tokens": 10480,
            "seed": 1234
        }
    )

### Environment

```Shell
docker run --runtime nvidia --gpus all --shm-size 64g -d --name lmdeploy-QWEN_2.5_32B --restart unless-stopped -v ~/.cache/huggingface:/root/.cache/huggingface -p 8000:8000 openmmlab/lmdeploy:latest-cu12 lmdeploy serve api_server --server-port 8000 --model-name Qwen_2.5 --backend turbomind --model-format awq --enable-prefix-caching --log-level DEBUG Qwen/Qwen2.5-32B-Instruct-AWQ
```

**Comment by AllentDan** [comment]
Similar issue https://github.com/InternLM/lmdeploy/issues/2678

**Comment by AllentDan** [comment]
May try https://github.com/InternLM/lmdeploy/pull/2681

**Comment by AllentDan** [comment]
Besides, as for parameter not included in OpenAI API, you should put it into `extra_body=dict(min_new_tokens=xxx)`
