### ISSUE TITLE
[Feature] Support MPT models (7B 2k, 7B 8k, 30B 8k)

### ISSUE THREAD

**Issue by casper-hansen** [InternLM/lmdeploy#269]
### Motivation

MPT models are open-sourced unlike LLaMa models and also have 7B models pre-trained at 1.5T with 8k context. Additionally, ALiBi is natively implemented, which means context extrapolation comes for free without major loss of perplexity, unlike other methods. 

The MPT model family is also the only good alternative to LLaMa models for companies that do not want to comply with the strict community license of LLaMa. One of the major problems is that all users of any product must accept the LLaMa license, which makes the users aware of any IP developed on top of the model.

The model architecture is relatively simple:
- Multi-Head Attention
- QKV is fused in one linear layer
- ALiBi is easy to implement
- Uses plain nn.LayerNorm

### Related resources

https://github.com/mosaicml/llm-foundry
https://huggingface.co/mosaicml/mpt-7b
https://huggingface.co/mosaicml/mpt-7b-8k
https://huggingface.co/mosaicml/mpt-30b

**Comment by lvhan028** [comment]
Let us investigate the workload of support mpt.

**Comment by casperbh96** [comment]
> Let us investigate the workload of support mpt.

That would be great. MPT has a lot of potentials.

**Comment by lvhan028** [comment]
Hi, @casper-hansen. We are busy with refactoring work, debugging the performance of W4 + int8 KV, and kernel optimization.

Requests for model support have been added to our backlog. We plan to incrementally address them in late September.

**Comment by lvhan028** [comment]
Moved to backlog
