### ISSUE TITLE
[Feature] unsupported quant config

### ISSUE THREAD

**Issue by maxin9966** [InternLM/lmdeploy#2694]
### Motivation

File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.9/site-packages/lmdeploy/turbomind/turbomind.py", line 112, in __init__
Oct 31 10:27:06 ubuntu22lts bash[56503]:     self.model_comm = self._from_hf(model_source=model_source,
Oct 31 10:27:06 ubuntu22lts bash[56503]:   File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.9/site-packages/lmdeploy/turbomind/turbomind.py", line 214, in _from_hf
Oct 31 10:27:06 ubuntu22lts bash[56503]:     tm_model = get_tm_model(model_path, self.model_name,
Oct 31 10:27:06 ubuntu22lts bash[56503]:   File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.9/site-packages/lmdeploy/turbomind/deploy/converter.py", line 237, in get_tm_model
Oct 31 10:27:06 ubuntu22lts bash[56503]:     assert not quant_config.get('desc_act', False) and \
Oct 31 10:27:06 ubuntu22lts bash[56503]: AssertionError: unsupported quant config: {'batch_size': 1, 'bits': 4, 'block_name_to_quantize': None, 'cache_block_outputs': True, 'damp_percent': 0.1, 'dataset': None, 'desc_act': False, 'exllama_config': {'version': 1}, 'group_size': 128, 'max_input_length': None, 'model_seqlen': None, 'module_name_preceding_first_block': None, 'modules_in_block_to_quantize': None, 'pad_token_id': None, 'quant_method': 'gptq', 'sym': False, 'tokenizer': None, 'true_sequential': True, 'use_cuda_fp16': True, 'use_exllama': True}

**Comment by maxin9966** [comment]
不支持非对称量化吗？

**Comment by lzhangzz** [comment]
理论上是可以支持的，不过没测过相应的 case 不知道有没有坑。可以把这个 assert 注释掉试试

**Comment by lvhan028** [comment]
@maxin9966 can you share the model repo_id on the huggingface hub? we can verify it.
