### ISSUE TITLE
[Feature] Mono-Internvl

### ISSUE THREAD

**Issue by sxlyiyiyi** [InternLM/lmdeploy#2695]
### Motivation

请问是否有支持Mono-Internvl的计划

**Comment by lvhan028** [comment]
InternVL team has supported its inference based on pytorch engine. 
They are going to PR the function later on. Stay tuned.

**Comment by wzk1015** [comment]
@sxlyiyiyi We support Mono-InternVL in https://github.com/InternLM/lmdeploy/pull/2727. Thanks for your interest.
