### ISSUE TITLE
[Bug] Does it support Internvl2-26B  quantization by awq on nvidia  V100

### ISSUE THREAD

**Issue by diandianliu** [InternLM/lmdeploy#2699]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

I successfully quantified the Internvl2-26B model on nvidia H800 and ran it.
Using the same way to quantify on nvidia v100,  It is  successfully quantified, but returning meaningless answers during model inference.
 Does it support Internvl2-26B  quantization by awq on nvidia  V100 and infer on V100?

### Reproduction

lmdeploy lite auto_awq

### Environment

```Shell
NVIDIA V100
python3.9.19

LMDeploy 0.5.1
transformer 4.43.3
```

**Comment by lzhangzz** [comment]
AWQ/GPTQ for V100 is added on v0.6.0
