### ISSUE TITLE
[Docs] Unclear in kv_int8.md

### ISSUE THREAD

**Issue by PYNing** [InternLM/lmdeploy#271]
### 📚 The doc issue

文档链接
https://github.com/InternLM/lmdeploy/blob/main/docs/en/kv_int8.md

问题：'Then modify the configuration file to make kCacheKVInt8 option to be effective', 这里不清楚的是
（1）修改的文件是否为 **./triton_models/weights/config.ini** ？
（2）是不是在这个文件的末尾添加一行 **CacheKVInt8=1** ？

### Suggest a potential alternative/fix

很棒的功能，希望能把以上2点写清晰一些

**Comment by tpoisonooo** [comment]
用法写在主页的 README 里：

0. 把 huggingface 模型转成 turbomind 推理格式，  python3 -m lmdeploy.serve.turbomind.deploy internlm-chat-7b /path/to/internlm-chat-7b 。得到一个 workspace 目录 
1. 获取量化参数  
```bash
python3 -m lmdeploy.lite.apis.kv_qparams \
  --work_dir /path/to/internlm-chat-7b  \              # 保存量化参数的目录
  --turbomind_dir workspace/trition_models/weights/ \
  --kv_sym False \                                             # 对称量化或非对称量化，默认为 False
  --num_tp 1  \                                                   # Tensor 并行使用的 GPU 数，和 deploy.py 保持一致
```
这个 `turbomind_dir` 可以随便找个自己的目录，其实会生成百十个 `np.tofile()` 的二进制格式文件，其实就是一堆 fp32 缩放系数
3. 打开  workspace/trition_models/weights/config.ini ， 修改
* use_context_fmha 改为 0，表示关闭 flashattention
* quant_policy 设置为 4。表示打开 kv_cache int8

4. 聊天，测试效果
```bash
python3 -m lmdeploy.turbomind.chat ./workspace
```

我来改改文档

**Comment by PYNing** [comment]
@tpoisonooo 
感谢回复，请问一下
`use_context_fmha 改为 0，表示关闭 flashattention`
会对推理性能有比较大的影响吗？

**Comment by tpoisonooo** [comment]
> @tpoisonooo 感谢回复，请问一下 `use_context_fmha 改为 0，表示关闭 flashattention` 会对推理性能有比较大的影响吗？

有 10% 左右的速度影响。 原因是，flashattention + int8，再混上 flashattention2，这个实现有点肝。

**Comment by PYNing** [comment]
感谢回复！
