### ISSUE TITLE
[Bug] GenerationConfig.max_new_tokens seem to be not working

### ISSUE THREAD

**Issue by YYue000** [InternLM/lmdeploy#2711]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

Response length doesn't match GenerationConfig.max_new_tokens, which is always 512 in response.

### Reproduction

```Python
from lmdeploy.api import PytorchEngineConfig
from lmdeploy import GenerationConfig, pipeline

cfg = PytorchEngineConfig(device_type="cuda", dtype="float16")
gen_config=GenerationConfig(
                    max_new_tokens=20,
                    top_p=0.8,
                    top_k=40,
                    temperature=0.6
                )

pipe = pipeline("meta-llama/Llama-3.2-1B",  backend_config=cfg, gen_config=gen_config)
response = pipe(["Hi, pls intro yourself", "Shanghai is"])
print(response)
```

![image](https://github.com/user-attachments/assets/6550bb38-2f82-4efe-b2f0-165114841536)

### Environment

```Shell
version 0.6.2
```

**Comment by RunningLeon** [comment]
@YYue000 hi, you should feed `gen_config=gen_config` into pipe when calling it.
>
response = pipe(["Hi, pls intro yourself", "Shanghai is"],  gen_config=gen_config)
