### ISSUE TITLE
[Bug] 显存溢出后程序卡死，而不是报错

### ISSUE THREAD

**Issue by Weiyun1025** [InternLM/lmdeploy#2712]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

显存溢出后程序卡死，而不是报错

### Reproduction

基于OpenGVLab/InternVL2-Llama3-76B进行数据采样，设置min_new_tokens=2048可以复现

### Environment

```Shell
八张A100做tp=8的推理
```

### Error traceback

```Shell
没有提供任何报错，程序直接卡死
```

**Comment by irexyc** [comment]
将日志等级设置为INFO，然后日志是怎样的呢？

有一种情况是这样，如果是通过服务来请求的话，默认的`max_new_token` 会默认是最大值，只有遇到 eos_token, stop_word_token 才会停下来。 `min_new_tokens` 会屏蔽掉 eos_token，那么如果后面遇不到 stop_word_token 的话，就会生成到最大长度才会停下来，不确定是不是这种情况。

**Comment by Weiyun1025** [comment]
感谢回复，这几天又研究了一下，似乎是tokenizer并行导致的死锁，代码里加了`os.environ["TOKENIZERS_PARALLELISM"] = "false"`之后就暂时没这个情况了，但很奇怪的是InternVL2-8B不会有这个问题，只有InternVL2-76B有这个问题
