### ISSUE TITLE
[Bug] awq模型不支持lora吗

### ISSUE THREAD

**Issue by LIUKAI0815** [InternLM/lmdeploy#2714]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

INFO:     10.12.17.5:50405 - "POST /v1/chat/completions HTTP/1.1" 404 Not Found

/v1/models  下面没有可用模型

### Reproduction

lmdeploy serve api_server ./Qwen2_5-14B-Instruct-AWQ  \
    --server-port 2016 \
	--tp 1 \
	--cache-max-entry-count 0.8 \
	--enable-prefix-caching  \
	--session-len 10000 \
	--adapters mylora=output/role/qwen/qwen2_5-14b-instruct-awq/v1-20241101-133149/checkpoint-1550 \

### Environment

```Shell
lmdeploy                          0.6.2
```

**Comment by LIUKAI0815** [comment]
@lvhan028 
1.lmdeploy serve api_server ./Qwen2_5-14B-Instruct-AWQ  \
    --server-port 2016 \
	--tp 1 \
	--cache-max-entry-count 0.8 \
	--enable-prefix-caching  \
	--session-len 10000 \
	--adapters mylora=output/role/qwen/qwen2_5-14b-instruct-awq/v1-20241101-133149/checkpoint-1550 \
	--backend pytorch \
	--model-format awq \
报错是：2024-11-06 22:40:35,607 - lmdeploy - ERROR - __init__.py:17 - ModuleNotFoundError: No module named 'awq'
2024-11-06 22:40:35,607 - lmdeploy - ERROR - __init__.py:18 - <autoawq> test failed!
Please ensure it has been installed correctly.


2.lmdeploy serve api_server ./Qwen2_5-14B-Instruct-AWQ  \
    --server-port 2016 \
	--tp 1 \
	--cache-max-entry-count 0.8 \
	--enable-prefix-caching  \
	--session-len 10000 \
	--adapters mylora=output/role/qwen/qwen2_5-14b-instruct-awq/v1-20241101-133149/checkpoint-1550 \
可以正常启动，但是调用模型的时候，model=mylora的时候，找不到模型报错：INFO:     10.12.17.5:61027 - "GET /v1/models HTTP/1.1" 200 OK
INFO:     10.12.17.5:61027 - "POST /v1/chat/completions HTTP/1.1" 404 Not Found

**Comment by lvhan028** [comment]
就根据提示安装 awq
```
pip install autoawq
```

**Comment by LIUKAI0815** [comment]
@lvhan028 感谢解决了。我一直以为能够成功量化模型就不是缺少autoawq包的原因。
