### ISSUE TITLE
想问一下用openai风格的api_key是指哪一个

### ISSUE THREAD

**Issue by hm123450** [InternLM/lmdeploy#2733]
抱歉，我是个新手，可能问的问题有点傻。我看到咱们官网教程上用openai风格接口的时候代码是这样的
`from openai import OpenAI
client = OpenAI(
    api_key='YOUR_API_KEY',
    base_url="http://0.0.0.0:23333/v1"
)
model_name = client.models.list().data[0].id
response = client.chat.completions.create(
  model=model_name,
  messages=[
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": " provide three suggestions about time management"},
  ],
    temperature=0.8,
    top_p=0.8
)
print(response)`
我想问一下里面的'YOUR_API_KEY'指的哪个啊？是要去openai官网申请api_key吗？但是我也没有国外的手机号，申请不了。
我看了部署生成的网站fastapi的界面，我也没有找到api_key在哪，不知道有没有好心人帮忙解答一下。真心感谢！

**Comment by AllentDan** [comment]
这个参数是 OpenAI 的包需要的，lmdeploy 提供的服务可以不用。任意非空字符串即可。
