### ISSUE TITLE
[Bug] 似乎卡死的都是VLM模型，看着是个系统性问题？

### ISSUE THREAD

**Issue by DefTruth** [InternLM/lmdeploy#2743]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

翻了一下关于卡死的issue，结合自己使用的情况。发现卡死问题都是VLM模型。是否和使用了accelerate有关系？不太确定accelerate是否使用了nccl后端的集合通信。如果有，vision和llm模块实际是流水线化，vision的集合通信可能会和llm的通信冲突，导致死锁。

### Reproduction

NOOP

### Environment

```Shell
NOOP
```

### Error traceback

```Shell
NOOP
```

**Comment by DefTruth** [comment]
用了今天最新的代码编译lmdeploy，还是会有hang住的问题。主要用VLM开TP>=2，总是会有一些实例会寄。直接卡死。这个问题从我用lmdeploy开始就一直存在。

```bash
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090 D      On  |   00000000:16:00.0 Off |                    0 |
| 38%   47C    P2             73W /  425W |   19447MiB /  23028MiB |    100%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 4090 D      On  |   00000000:27:00.0 Off |                    0 |
| 36%   36C    P8             16W /  425W |   20501MiB /  23028MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
```
@irexyc

**Comment by irexyc** [comment]
accelerate 没有用 nccl，单纯的只是把权重和计算分到多个卡上线性的计算。

确实反馈比较多，我这边一直没有稳定的复现，可以把 --log-level INFO 打开一下，看一下卡住的时候服务器的信息吧。

另外可以看一下如果加了同步会不会有问题，方式是
export TM_DEBUG_LEVEL=DEBUG
lmdeploy serve api_server ... --log-level DEBUG

**Comment by DefTruth** [comment]
@irexyc 非常感谢您的回复。export TM_DEBUG_LEVEL=DEBUG 这个正在试，但是这个选项会产生大量日志，无法在生产环境使用。请问还有其他方式可以“加同步”不？另外，再请教一下，这里说的“同步”具体是指什么的同步？

**Comment by irexyc** [comment]
同步就是在每个 cuda 调用之后加了 cudaStreamSynchronize，如果 cuda 调用有问题可以及时暴露出来。

**Comment by DefTruth** [comment]
@irexyc 很难稳定复现，我的观察是，某些卡，比如4090D，TP=2，上起大量实例，其中会有1%~3%的概率出现hang。但是其他卡比如L20/A30等又不会。

**Comment by DefTruth** [comment]
> 同步就是在每个 cuda 调用之后加了 cudaStreamSynchronize，如果 cuda 调用有问题可以及时暴露出来。

请问有方法在不增加冗余日志的基础上加同步吗？

**Comment by irexyc** [comment]
不想要那么多日志的话，--log-level 可以不设置 debug，只设置 TM_DEBUG_LEVEL 环境变量就可以了

`export TM_DEBUG_LEVEL=DEBUG `

**Comment by DefTruth** [comment]
好的，我们试试，非常感谢~

**Comment by DefTruth** [comment]
> 不想要那么多日志的话，--log-level 可以不设置 debug，只设置 TM_DEBUG_LEVEL 环境变量就可以了
> 
> `export TM_DEBUG_LEVEL=DEBUG `

这么说，那应该 --log-level 保持默认的ERROR级别就可以了是吧。

**Comment by irexyc** [comment]
是的

**Comment by DefTruth** [comment]
@irexyc 您好，想再请假一下，enable_custom_all_reduce，默认是开启还是关闭的？比如在没有P2P支持的情况下。

**Comment by lzhangzz** [comment]
`enable_custom_all_reduce` 这个选项目前没用

**Comment by DefTruth** [comment]
@irexyc 首先，很感谢先前的回复。我来反馈一下测试的情况，加了DEBUG模式后（kernel launch后立刻执行stream/device同步），大量实例，压测了几个小时，没有再发现服务hang的情况。服务吞吐大约下降5%。结合hang住时，有卡100%，有卡0%利用率，这种大概率是由于通信卡死导致，以及强制同步后不再出现卡死的情况，因此，猜测，大概率是NCCL集合通信前后，至少要有一次Device/Stream同步，来避免高并发时卡死的情况发生。希望我们的反馈对解决这个问题有帮助。

**Comment by snippetzero** [comment]
同样在vlm模型上 tp=1，频繁遇到卡死

**Comment by DefTruth** [comment]
不幸的是压测15小时后，还是出现了大量卡死的情况。用了debug模式。

**Comment by DefTruth** [comment]
> 同样在vlm模型上 tp=1，频繁遇到卡死

按理说TP=1也不涉及通信了啊，卡住有点奇怪

**Comment by chenzhengda** [comment]
> > 同样在vlm模型上 tp=1，频繁遇到卡死
> 
> 按理说TP=1也不涉及通信了啊，卡住有点奇怪

目前我测试下来,单独设置 vit tp == 1 之后也没卡住

**Comment by lzhangzz** [comment]
> 不幸的是压测15小时后，还是出现了大量卡死的情况。用了debug模式。

目前已知 TP 在某块卡爆显存的的时候可能卡住。TP=1 的时候卡住我们还没有复现，能不能麻烦你在 debug 模式复现然后 dump 一下 server 各线程的 stacktrace。

首先

`gdb attach $server_pid`

然后在 gdb 中

```
set logging on
thread apply all bt
set logging on
```

在当前目录会输出一个 gdb.txt

**Comment by DefTruth** [comment]
> > 不幸的是压测15小时后，还是出现了大量卡死的情况。用了debug模式。
> 
> 目前已知 TP 在某块卡爆显存的的时候可能卡住。TP=1 的时候卡住我们还没有复现，能不能麻烦你在 debug 模式复现然后 dump 一下 server 各线程的 stacktrace。
> 
> 首先
> 
> `gdb attach $server_pid`
> 
> 然后在 gdb 中
> 
> ```
> set logging on
> thread apply all bt
> set logging on
> ```
> 
> 在当前目录会输出一个 gdb.txt

我测试的是TP=2，加DEBUG同步后，出现的卡主情况是由于出现图片太大，显卡显存不足的情况导致的，限制了请求图片的分辨率后没有再出现卡住了。
