### ISSUE TITLE
[Feature] 请问function calling是否只适配本项目的后端servcer

### ISSUE THREAD

**Issue by positive666** [InternLM/lmdeploy#2747]
### Motivation

我自己有一套Openai的server 后端，发现使用Intern2lm 无法识别tool calls，想偷个懒 ，直接问下所以区别在于后端的tools相关代码问题吗？

**Comment by AllentDan** [comment]
是的，主要是 prompt 的前后处理。可以参考 https://github.com/InternLM/lmdeploy/pull/1763/files
