### ISSUE TITLE
[Bug] CUDA runtime error: out of memory

### ISSUE THREAD

**Issue by jingcheng88** [InternLM/lmdeploy#277]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.

### Describe the bug

在3090上进行benchmark的时候出现下面报错：

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  [TM][ERROR] No enough cache entries. Assertion fail: /opt/tritonserver/lmdeploy/src/turbomind/models/llama/LlamaCacheManager.cc:62
```
并发为1的时候能跑，并发到4或者更大时候就服务就直接崩溃了。
配置：
```
max_batch_size = 8
cache_max_entry_count = 2
```

### Reproduction

使用脚本profile_serving.py压测

**Comment by lzhangzz** [comment]
cache_max_entry_count是实际管理的最大sequence数量，不能小于运行时的最大batch size

**Comment by jingcheng88** [comment]
```
max_batch_size = 8
cache_max_entry_count = 8
```
如果都设置成8，benchmark 4可以跑，但是比如跑8，就会出现OOM，不知道这个具体怎么计算才能保证不出现OOM。
3090显存24GB，load完模型还有差不多9个GB。
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  [TM][ERROR] CUDA runtime error: out of memory /opt/tritonserver/lmdeploy/src/turbomind/utils/allocator.h:223 
```

**Comment by lzhangzz** [comment]
batch_size * num_layer * kv_head_num * size_per_head * session_len * 4 < load完模型的空闲内存

**Comment by jingcheng88** [comment]
有没有文档可以参考，batch_size、size_per_head和session_len这几个对于推理性能有什么影响。

**Comment by jingcheng88** [comment]
```
max_batch_size = 8
session_len = 2048
cache_max_entry_count = 12
```
这样压测没问题。
修改参数后出现报错：
```
max_batch_size = 16
session_len = 1044
cache_max_entry_count = 20
```

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  [TM][ERROR] CUDA runtime error: invalid argument /opt/tritonserver/lmdeploy/src/turbomind/models/llama/LlamaBatch.cc:694 

Signal (6) received.
```

**Comment by lzhangzz** [comment]
可以提供下复现路径吗？

**Comment by jingcheng88** [comment]
将session_len修改的比较小，然后增加max_batch_size，然后实用benchmark脚本压测，就会出现上面的问题。
session_len在Fastertransformer中是`max length of the total session`，修改这个参数的大小具体什么影响？
```
python profile_serving.py \
    ${TritonServerAddress} \
    /path/to/tokenizer \
    ShareGPT_V3_unfiltered_cleaned_split.json \
    --concurrency 64
```

**Comment by lzhangzz** [comment]
session_len控制每个会话的最大长度，如果输入的长度直接超过了这个值，估计就会报上面的错误。

> 另外KV cache量化后，下面的计算公式如何更新？

batch_size * num_layer * kv_head_num * size_per_head * session_len * 4 / 2

**Comment by tpoisonooo** [comment]
> 

kv cache 是 int8 量化，就是 fp16 变 int8，显存砍一半。
