### ISSUE TITLE
[Bug] 关于Lmdeploy部署Qwen2-VL-AWQ时候的问题

### ISSUE THREAD

**Issue by lmh12138** [InternLM/lmdeploy#2788]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

好像不支持直接部署通义千问的AWQ量化模型？

有如下报错
2024-11-21 17:46:04,971 - lmdeploy - WARNING - archs.py:53 - Fallback to pytorch engine because `Qwen2-VL-7B-Instruct-AWQ` not supported by turbomind engine.
`Qwen2VLRotaryEmbedding` can now be fully parameterized by passing the model config through the `config` argument. All other arguments will be removed in v4.46
2024-11-21 17:46:13,978 - lmdeploy - ERROR - model_agent.py:493 - Rank[3] failed.                                                                                                         
Traceback (most recent call last):
  File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 490, in _start_tp_process
    func(rank, *args, **kwargs)
  File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 433, in _tp_model_loop
    patched_model, cache_engine, _ = _tp_build_model(rank,
  File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 394, in _tp_build_model
    raise e
  File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 361, in _tp_build_model
    patched_model = build_patched_model(model_config, device=device_map)
  File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/models/patch.py", line 200, in build_patched_model
    return build_model_from_hf_config(model_config, dtype=dtype, device=device)
  File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/models/patch.py", line 191, in build_model_from_hf_config
    model = model_cls(model_config, ctx_mgr, dtype=dtype, device=device)
  File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/models/qwen2_vl.py", line 364, in __init__
    self.model = Qwen2Model(config, dtype=dtype, device=device)
  File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/models/qwen2_vl.py", line 266, in __init__
    self.layers = nn.ModuleList([
  File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/models/qwen2_vl.py", line 267, in <listcomp>
    Qwen2DecoderLayer(config, layer_idx, dtype=dtype, device=device)
  File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/models/qwen2_vl.py", line 193, in __init__
    self.self_attn = Qwen2Attention(config, dtype=dtype, device=device)
  File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/models/qwen2_vl.py", line 63, in __init__
    self.qkv_proj = build_qkv_proj(
  File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/nn/linear.py", line 1326, in build_qkv_proj
    return QKVAwqLinear(
  File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/nn/linear.py", line 506, in __init__
    super().__init__(in_features,
  File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/nn/linear.py", line 389, in __init__
    super().__init__(in_features,
  File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/nn/linear.py", line 186, in __init__
    impl_builder = get_backend().get_layer_impl_builder(OpType.LinearW4A16)
  File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/backends/cuda/op_backend.py", line 51, in get_layer_impl_builder
    from awq.modules.linear.gemm import AWQ_INSTALLED
ImportError: cannot import name 'AWQ_INSTALLED' from 'awq.modules.linear.gemm' (/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/awq/modules/linear/gemm.py)
[rank0]: Traceback (most recent call last):
[rank0]:   File "/hdd/miniconda/envs/llvm/bin/lmdeploy", line 8, in <module>
[rank0]:     sys.exit(run())
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/cli/entrypoint.py", line 42, in run
[rank0]:     args.run(args)
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/cli/serve.py", line 338, in api_server
[rank0]:     run_api_server(args.model_path,
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/serve/openai/api_server.py", line 1073, in serve
[rank0]:     VariableInterface.async_engine = pipeline_class(
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/serve/vl_async_engine.py", line 27, in __init__
[rank0]:     super().__init__(model_path, **kwargs)
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/serve/async_engine.py", line 162, in __init__
[rank0]:     self._build_pytorch(model_path=model_path,
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/serve/async_engine.py", line 210, in _build_pytorch
[rank0]:     self.engine = Engine(model_path=model_path,
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/engine/engine.py", line 149, in __init__
[rank0]:     self.model_agent = build_model_agent(
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 790, in build_model_agent
[rank0]:     model_agent = TPModelAgent(model_path,
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 586, in __init__
[rank0]:     model, cache_engine, cache_config = self._build_model(
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 681, in _build_model
[rank0]:     model, cache_engine, cache_config = _tp_build_model(
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 394, in _tp_build_model
[rank0]:     raise e
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 361, in _tp_build_model
[rank0]:     patched_model = build_patched_model(model_config, device=device_map)
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/models/patch.py", line 200, in build_patched_model
[rank0]:     return build_model_from_hf_config(model_config, dtype=dtype, device=device)
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/models/patch.py", line 191, in build_model_from_hf_config
[rank0]:     model = model_cls(model_config, ctx_mgr, dtype=dtype, device=device)
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/models/qwen2_vl.py", line 364, in __init__
[rank0]:     self.model = Qwen2Model(config, dtype=dtype, device=device)
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/models/qwen2_vl.py", line 266, in __init__
[rank0]:     self.layers = nn.ModuleList([
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/models/qwen2_vl.py", line 267, in <listcomp>
[rank0]:     Qwen2DecoderLayer(config, layer_idx, dtype=dtype, device=device)
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/models/qwen2_vl.py", line 193, in __init__
[rank0]:     self.self_attn = Qwen2Attention(config, dtype=dtype, device=device)
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/models/qwen2_vl.py", line 63, in __init__
[rank0]:     self.qkv_proj = build_qkv_proj(
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/nn/linear.py", line 1326, in build_qkv_proj
[rank0]:     return QKVAwqLinear(
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/nn/linear.py", line 506, in __init__
[rank0]:     super().__init__(in_features,
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/nn/linear.py", line 389, in __init__
[rank0]:     super().__init__(in_features,
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/nn/linear.py", line 186, in __init__
[rank0]:     impl_builder = get_backend().get_layer_impl_builder(OpType.LinearW4A16)
[rank0]:   File "/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/lmdeploy/pytorch/backends/cuda/op_backend.py", line 51, in get_layer_impl_builder
[rank0]:     from awq.modules.linear.gemm import AWQ_INSTALLED
[rank0]: ImportError: cannot import name 'AWQ_INSTALLED' from 'awq.modules.linear.gemm' (/hdd/miniconda/envs/llvm/lib/python3.8/site-packages/awq/modules/linear/gemm.py)
[rank0]:[W1121 17:46:14.112283800 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())

### Reproduction

lmdeploy serve api_server Qwen2-VL-7B-Instruct-AWQ --server-port 23333 --tp 4 --model-format awq

### Environment

```Shell
sys.platform: linux
Python: 3.8.20 (default, Oct  3 2024, 15:24:27) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3: NVIDIA L40
CUDA_HOME: /home/liminghang/cuda
NVCC: Cuda compilation tools, release 12.1, V12.1.105
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
PyTorch: 2.4.0+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.4.2 (Git Hash 1137e04ec0b5251ca2b4400a4fd3c667ce843d67)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 90.1  (built against CUDA 12.4)
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=9.1.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.4.0, USE_CUDA=ON, USE_CUDNN=ON, USE_CUSPARSELT=1, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_GLOO=ON, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

TorchVision: 0.19.0+cu121
LMDeploy: 0.6.3+
transformers: 4.46.3
gradio: 4.44.1
fastapi: 0.115.5
pydantic: 2.9.2
triton: 3.0.0
NVIDIA Topology: 
	GPU0	GPU1	GPU2	GPU3	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	NODE	SYS	SYS	0-27,56-83	0		N/A
GPU1	NODE	 X 	SYS	SYS	0-27,56-83	0		N/A
GPU2	SYS	SYS	 X 	NODE	28-55,84-111	1		N/A
GPU3	SYS	SYS	NODE	 X 	28-55,84-111	1		N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

**Comment by AllentDan** [comment]
It relies `auto_awq` package. Please make sure that you installed it correctly. `from awq.modules.linear.gemm import AWQ_INSTALLED`

**Comment by lmh12138** [comment]
我检查了一下我的环境，我的autoawq版本是autoawq-0.2.7.post2，但是在我执行from awq.modules.linear.gemm import AWQ_INSTALLED的时候，会提示我ImportError: cannot import name 'AWQ_INSTALLED' from 'awq.modules.linear.gemm'

**Comment by AllentDan** [comment]
降版本试试。我本地用的 0.2.5

**Comment by lmh12138** [comment]
感谢，0.2.5版本是可以的，看起来0.2.7版本删除了AWQ_INSTALLED

**Comment by lmh12138** [comment]
另外pip install lmdeploy的时候貌似并不会自动安装autoawq的依赖，建议可以补齐这一点

**Comment by AllentDan** [comment]
> 另外pip install lmdeploy的时候貌似并不会自动安装autoawq的依赖，建议可以补齐这一点

不会补齐，autoawq 不会作为常规依赖。只有需要的人没装用的时候会提示安装的

**Comment by lmh12138** [comment]
好的
