### ISSUE TITLE
[Feature] Support "continue_final_message" in /v1/chat/completions server API parameters

### ISSUE THREAD

**Issue by Huarong** [InternLM/lmdeploy#2798]
### Motivation

If this is set, the chat will be formatted so that the final message in the chat is open-ended, without any EOS tokens. The model will continue this message rather than starting a new one. This allows you to "prefill" part of the model's response for it. 

### Related resources

- [HuggingFace transformers continue_final_message](https://huggingface.co/docs/transformers/main/chat_templating#what-does-continuefinalmessage-do) 
- [vllm continue_final_message](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html#extra-parameters-for-chat-completions-api)

**Comment by lvhan028** [comment]
@AllentDan I think we've implemented it, haven't we?

**Comment by AllentDan** [comment]
Yes, we've implemented it.

**Comment by Huarong** [comment]
I didn't find it in the documents or code. Could you give some hints? @AllentDan

**Comment by AllentDan** [comment]
The last role of the messages could be `assistant` with prefix content.

**Comment by Huarong** [comment]
Confirmed. Thanks
