### ISSUE TITLE
[Bug] Logprobs always NULL

### ISSUE THREAD

**Issue by BrennanCode1** [InternLM/lmdeploy#2802]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

When running the Vllm container and sending request with logprobs = true it always returns logprobs Null

### Reproduction

`docker run -d --name vllmtester --gpus all     -v ~/.cache/huggingface:/root/.cache/huggingface     -p 23333:23333     --ipc=host     openmmlab/lmdeploy:latest     lmdeploy serve api_server hugging-quants/Meta-Llama-3.1-70B-Instruct-AWQ-INT4     --tp 8`

Running this command and request built like this Logprobs is always NULL 
`
 POST request payload: {"messages": [{"role": "system", "content": "The results were reported to the equal justice communityand posted on the Florida Legal Services website,www My dear, you didn't invite them the firsttime They are good people, and you should not be abusing them For the lack of urgency, see FDNY interview 57, SOC (Apr We have come to dedicate a portion of that field as a final resting place for those who here gave their lives that that nation might live!"}, {"role": "user", "content": "Orrin Hatch about the balanced-budget amendment Yet, there is no evidence that the countrys circumstances were anywhere near this flashpoint of imminent destruction Bernstein E, Bernstein J, Levenson S The plays which are performed are selected because they have a      specific link to what is being studied in the classroom 5 nmoles i It is also used to mean a drunkard or a very stupid person net Date: 5/10/04 5:48:17 PM Subject: Let Baby Live We, the readers?"}, {"role": "assistant", "content": "THE HAMBURG CONTINGENT            Although Bin Ladin, Atef, and KSM initially contemplated using established al Qaeda                members to execute the planes operation, the late 1999 arrival in Kandahar of four                aspiring jihadists from Germany suddenly presented a more attractive alternative John Donald Robb (18921989) collected folk songs throughout New Mexico in the 1940s and 1950s using wire recorders Continuous pressure on the same area of skin, particularly over bony prominences, will increase the risk of skin ischemia, and pain?"}, {"role": "user", "content": "Our stylistic question recurs In folktales from New Mexico, they often appear as balls of fire flying across the sky 0, with no change in the basic price, causes the basic volume togo from 54 Perhaps the safest interpretation of these        results is that by the time adults are overweight, the health benefits of losing weight are        not clear-cut 31 A glance inside the door of an open classroom reveals richly equipped learning centers, small groups of pupils..."}, {"role": "assistant", "content": "Occasionally, make-believe can defuse persistent caregiverchild conicts It      exemplifies the support and encouragement that the faculty and community      provides Advances in one specialty donot necessarily affect the practice of another A body feels fortified and strong after such a meal The metallic walls curve, twist, and turn Hecompares the films (and Eastwood's masculine posing) to the modern-jazz manner,\"a powerful desire--almost amounting to a morality--not to woo the audience..."}, {"role": "user", "content": "There was no backup site Romanesque makes imposing city halls,!"}], "temperature": 0.4, "seed": 57083413, "model": "hugging-quants/Meta-Llama-3.1-70B-Instruct-AWQ-INT4", "stream": true, "logprobs": true, "top_p": 1.0, "top_k": 5, "max_tokens": 142}
`
example response
`Received event: data: {"id":"1","object":"chat.completion.chunk","created":1732511624,"model":"hugging-quants/Meta-Llama-3.1-70B-Instruct-AWQ-INT4","choices":[{"index":0,"delta":{"role":"assistant","content":"io"},"logprobs":null,"finish_reason":null}],"usage":null}`

### Environment

```Shell
sys.platform: linux
Python: 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA H100 80GB HBM3
CUDA_HOME: /usr
NVCC: Cuda compilation tools, release 12.4, V12.4.131
GCC: x86_64-linux-gnu-gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 2.4.0+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.4.2 (Git Hash 1137e04ec0b5251ca2b4400a4fd3c667ce843d67)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 90.1  (built against CUDA 12.4)
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=9.1.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.4.0, USE_CUDA=ON, USE_CUDNN=ON, USE_CUSPARSELT=1, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_GLOO=ON, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

TorchVision: 0.19.0+cu121
LMDeploy: 0.6.3+
transformers: 4.46.3
gradio: Not Found
fastapi: 0.115.5
pydantic: 2.10.1
triton: 3.0.0
NVIDIA Topology: 
	GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	NIC0	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	NV18	NV18	NV18	NV18	NV18	NV18	NV18	SYS	0-103	0		N/A
GPU1	NV18	 X 	NV18	NV18	NV18	NV18	NV18	NV18	SYS	0-103	0		N/A
GPU2	NV18	NV18	 X 	NV18	NV18	NV18	NV18	NV18	SYS	0-103	0		N/A
GPU3	NV18	NV18	NV18	 X 	NV18	NV18	NV18	NV18	SYS	0-103	0		N/A
GPU4	NV18	NV18	NV18	NV18	 X 	NV18	NV18	NV18	SYS	104-207	1		N/A
GPU5	NV18	NV18	NV18	NV18	NV18	 X 	NV18	NV18	SYS	104-207	1		N/A
GPU6	NV18	NV18	NV18	NV18	NV18	NV18	 X 	NV18	SYS	104-207	1		N/A
GPU7	NV18	NV18	NV18	NV18	NV18	NV18	NV18	 X 	SYS	104-207	1		N/A
NIC0	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	 X 				

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0


(lmdeploy) root@192-222-53-204:~#
```

**Comment by irexyc** [comment]
Sorry for late reply, I can't reproduce your issue. I think maybe you have missed the parameter `top_logprobs`.

My test code is:

```
server:
lmdeploy serve api_server /mnt/140/llama3/Meta-Llama-3-8B-Instruct

client:
curl http://0.0.0.0:23333/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer 123" \
  -d '{
    "model": "/mnt/140/llama3/Meta-Llama-3-8B-Instruct",
    "messages": [
      {
        "role": "user",
        "content": "Hello!"
      }
    ],
    "stream": true,
    "logprobs": true,
    "top_logprobs": 3
  }'


result:

data: {"id":"3","object":"chat.completion.chunk","created":1732704550,"model":"/mnt/140/llama3/Meta-Llama-3-8B-Instruct","choices":[{"index":0,"delta":{"role":"assistant","content":"Hello"},"logprobs":{"content":[{"token":"Hello","bytes":[72,101,108,108,111],"logprob":-0.00005777091791969724,"top_logprobs":[{"token":"Hi","bytes":[72,105],"logprob":-9.852066040039062},{"token":"ĠHello","bytes":[196,160,72,101,108,108,111],"logprob":-12.198531150817871}]}]},"finish_reason":null}],"usage":null}

data: {"id":"3","object":"chat.completion.chunk","created":1732704550,"model":"/mnt/140/llama3/Meta-Llama-3-8B-Instruct","choices":[{"index":0,"delta":{"role":"assistant","content":"!"},"logprobs":{"content":[{"token":"!","bytes":[33],"logprob":-0.000011514188372530043,"top_logprobs":[{"token":"Ġthere","bytes":[196,160,116,104,101,114,101],"logprob":-11.362740516662598},{"token":"ï¼ģ","bytes":[195,175,194,188,196,163],"logprob":-19.049819946289062}]}]},"finish_reason":null}],"usage":null}

data: {"id":"3","object":"chat.completion.chunk","created":1732704550,"model":"/mnt/140/llama3/Meta-Llama-3-8B-Instruct","choices":[{"index":0,"delta":{"role":"assistant","content":" It"},"logprobs":{"content":[{"token":"ĠIt","bytes":[196,160,73,116],"logprob":-7.2245511546498165e-6,"top_logprobs":[{"token":"ĠNice","bytes":[196,160,78,105,99,101],"logprob":-12.82198429107666},{"token":"Ġit","bytes":[196,160,105,116],"logprob":-12.862689018249512}]}]},"finish_reason":null}],"usage":null}

data: {"id":"3","object":"chat.completion.chunk","created":1732704550,"model":"/mnt/140/llama3/Meta-Llama-3-8B-Instruct","choices":[{"index":0,"delta":{"role":"assistant","content":"'s"},"logprobs":{"content":[{"token":"'s","bytes":[39,115],"logprob":0.0,"top_logprobs":[{"token":"âĢĻs","bytes":[195,162,196,162,196,187,115],"logprob":-21.43724250793457},{"token":"Ġnice","bytes":[196,160,110,105,99,101],"logprob":-22.45855712890625}]}]},"finish_reason":null}],"usage":null}

...
data: {"id":"3","object":"chat.completion.chunk","created":1732704550,"model":"/mnt/140/llama3/Meta-Llama-3-8B-Instruct","choices":[{"index":0,"delta":{"role":"assistant","content":""},"logprobs":null,"finish_reason":"stop"}],"usage":null}

data: [DONE]
```

**Comment by BrennanCode1** [comment]
That is the case thank you willl remove this issue

**Comment by hxyghostor** [comment]
hello,
Can VLLM(Qwen2-vl-2b-4bit) support logprobs output? I always get None
![Image](https://github.com/user-attachments/assets/fc8e23bc-c471-4ec5-82f6-fcb457c4ed6a)
