### ISSUE TITLE
[Bug] docker+lmdeploy deploys multimodal large model and reports an error：AssertionError: failed to match chat template, please explicit set chat_template_config（docker+lmdeploy部署多模态大模型）

### ISSUE THREAD

**Issue by Aanlifire** [InternLM/lmdeploy#2805]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

The deployment process is as follows：

pip install qwen_vl_utils

git clone https://github.com/InternLM/lmdeploy.git
cd lmdeploy
docker build --build-arg CUDA_VERSION=cu12 -t openmmlab/lmdeploy:qwen2vl . -f ./docker/Qwen2VL_Dockerfile

docker run --runtime nvidia --gpus all
-v ~/Qwen2-VL-7B-Instruct:/lmdeploy/models
-p 8000:8000
--ipc=host
openmmlab/lmdeploy:latest
lmdeploy serve api_server /lmdeploy/models

(base) root@lxing:~/lmdeploy# docker run --runtime nvidia --gpus all
-v ~/Qwen2-VL-7B-Instruct:/lmdeploy/models
-v ~/Qwen2-VL-7B-Instruct/chat_template.json:/opt/lmdeploy/config/chat_template.json
-p 8000:8000
--ipc=host
openmmlab/lmdeploy:qwen2vl-v0.5.1
lmdeploy serve api_server /lmdeploy/models

==========
== CUDA ==
CUDA Version 12.4.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

2024-11-25 03:36:47,633 - lmdeploy - WARNING - archs.py:53 - Fallback to pytorch engine because /lmdeploy/models not supported by turbomind engine.
Qwen2VLRotaryEmbedding can now be fully parameterized by passing the model config through the config argument. All other arguments will be removed in v4.46
Traceback (most recent call last):
File "/opt/py3/bin/lmdeploy", line 33, in
sys.exit(load_entry_point('lmdeploy', 'console_scripts', 'lmdeploy')())
File "/opt/lmdeploy/lmdeploy/cli/entrypoint.py", line 42, in run
args.run(args)
File "/opt/lmdeploy/lmdeploy/cli/serve.py", line 338, in api_server
run_api_server(args.model_path,
File "/opt/lmdeploy/lmdeploy/serve/openai/api_server.py", line 1073, in serve
VariableInterface.async_engine = pipeline_class(
File "/opt/lmdeploy/lmdeploy/serve/vl_async_engine.py", line 32, in init
self.vl_prompt_template = get_vl_prompt_template(
File "/opt/lmdeploy/lmdeploy/vl/templates.py", line 512, in get_vl_prompt_template
assert type(chat_template) != type(BaseModel()), 'failed to match '
AssertionError: failed to match chat template, please explicit set chat_template_config

### Reproduction

pip install qwen_vl_utils

git clone https://github.com/InternLM/lmdeploy.git
cd lmdeploy
docker build --build-arg CUDA_VERSION=cu12 -t openmmlab/lmdeploy:qwen2vl . -f ./docker/Qwen2VL_Dockerfile

docker run --runtime nvidia --gpus all
-v ~/Qwen2-VL-7B-Instruct:/lmdeploy/models
-p 8000:8000
--ipc=host
openmmlab/lmdeploy:latest
lmdeploy serve api_server /lmdeploy/models

### Environment

```Shell
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090        Off |   00000000:00:10.0 Off |                  Off |
| 47%   32C    P8             18W /  450W |   20412MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 4090        Off |   00000000:00:11.0 Off |                  Off |
| 48%   32C    P8             22W /  450W |   20412MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA GeForce RTX 4090        Off |   00000000:00:1B.0 Off |                  Off |
| 46%   33C    P8             13W /  450W |   20412MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA GeForce RTX 4090        Off |   00000000:00:1C.0 Off |                  Off |
| 49%   33C    P8             18W /  450W |   20412MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
```

**Comment by Aanlifire** [comment]
> We match the `chat_template` based on folder name. You can either change the mapping folder `~/Qwen2-VL-7B-Instruct:/lmdeploy/models` to `~/Qwen2-VL-7B-Instruct:/lmdeploy/models/Qwen2-VL-7B-Instruct` or explicit specify the `chat_template` by `--chat-template qwen`我们根据文件夹名称匹配`chat_template`。您可以将映射文件夹 `~/Qwen2-VL-7B-Instruct:/lmdeploy/models` 更改为 `~/Qwen2-VL-7B-Instruct:/lmdeploy/models/Qwen2-VL-7B-Instruct` 或通过 `--chat-template qwen` 显式指定`chat_template`

Thank you very much. I will give it a try.

**Comment by lzk9508** [comment]
> > We match the `chat_template` based on folder name. You can either change the mapping folder `~/Qwen2-VL-7B-Instruct:/lmdeploy/models` to `~/Qwen2-VL-7B-Instruct:/lmdeploy/models/Qwen2-VL-7B-Instruct` or explicit specify the `chat_template` by `--chat-template qwen`我们根据文件夹名称匹配`chat_template`。您可以将映射文件夹 `~/Qwen2-VL-7B-Instruct:/lmdeploy/models` 更改为 `~/Qwen2-VL-7B-Instruct:/lmdeploy/models/Qwen2-VL-7B-Instruct` 或通过 `--chat-template qwen` 显式指定`chat_template`
> 
> Thank you very much. I will give it a try.

is the problem solved? I met the same error with InternVL2_8B_awq
