### ISSUE TITLE
[Feature] lmdeploy在windows多卡部署大模型

### ISSUE THREAD

**Issue by Zhangwt95** [InternLM/lmdeploy#2828]
### Motivation

在windows系统上lmdeploy支持多卡部署大模型

**Comment by irexyc** [comment]
windows 平台只能用 turobmind backend(host) 或者 wsl2里面 (pytorch/turbomind) 部署单卡模型。

wsl2里面使用 nccl 好像有问题，之前有 issue 反馈 wsl2 中使用多卡失败了

**Comment by Zhangwt95** [comment]
是的，nccl在windows下不支持导致多卡失败。另外，我已经实现windows下pytorch backend部署单卡模型。nccl的问题正在寻找解决方案。 @irexyc
