### ISSUE TITLE
[Bug] baichuan-7b - 重复输出

### ISSUE THREAD

**Issue by feng-1985** [InternLM/lmdeploy#284]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.

### Describe the bug

baichuan-7b调优后，合并权重，再转换为turbomind's format

转换命令：
python -m lmdeploy.serve.turbomind.deploy llama /path/to/baichuan-llama-7b

启动命令：
python -m lmdeploy.turbomind.chat ./workspace

输入指令，结果输出重复的内容.
----
使用[baichuan-llama-7b](https://huggingface.co/fireballoon/baichuan-llama-7b)，转换后，同样启动命令，也会输出重复内容.

[relate issue](https://github.com/InternLM/lmdeploy/issues/215)

### Reproduction

no

**Comment by lvhan028** [comment]
这是一个对话模型么？

**Comment by feng-1985** [comment]
有续写能力 -- 不能对话

**Comment by hljjjmssyh** [comment]
想问一下 baichuan-7b 目前支持吗，之前貌似有tokenizer 的问题

**Comment by lvhan028** [comment]
baichuan-7b是支持的。baichuan2-7b-base(chat)也支持。但是13b的不支持

**Comment by hljjjmssyh** [comment]
> baichuan-7b是支持的。baichuan2-7b-base(chat)也支持。但是13b的不支持
目前7b 支持量化吗

**Comment by pppppM** [comment]
@hljjjmssyh baichuan 1&2 7b 已经支持量化，可以使用最新版的 lmdeploy
