### ISSUE TITLE
[Feature] Desire to Use the Latest Version of lmdeploy with PyTorch 2.1.0

### ISSUE THREAD

**Issue by zhabuye** [InternLM/lmdeploy#2843]
### Motivation

Hello,

I've noticed that in the recent versions of your library, the dependency requirement for PyTorch has been raised to 2.3.1. I am currently using PyTorch 2.1.0 in my environment and would like to continue using this version with the latest version of your library.

I would like to inquire about the following:

What prompted the decision to raise the PyTorch dependency version to 2.3.1? Were there specific features or improvements introduced in 2.3.1 that are not supported in version 2.1.0? If so, are there backward compatibility solutions provided to use these features on older versions of PyTorch?

Thank you for your assistance and I look forward to your reply.

**Comment by grimoire** [comment]
Pytorch 2.1.0 requires triton==2.1.0 which is not supported in our repo.
It should be ok to use Pytorch2.1.0 with triton==3.0.0
