### ISSUE TITLE
[Feature] Load safetensors of a lora adapter in PyTorch engine

### ISSUE THREAD

**Issue by Galaxy-Husky** [InternLM/lmdeploy#2851]
### Motivation

I got an error when I tried loading a lora adapter, which was `FileNotFoundError: [Errno 2] No such file or directory: xx/adapter_model.bin`.

Now it only supports weights in `.bin` format :
https://github.com/InternLM/lmdeploy/blob/cc8cfb0b456cb05cf1089ff1f27706d395e70864/lmdeploy/pytorch/models/patch.py#L294-L298

Since the argument `save_safetensors` in `TrainingArguments` of transformers  defaults to `True`, it is always easy to get the weights in `safetensors` format.

Could you consider loading safetensors of a lora adapter in PyTorch engine? And I'd love to help!

**Comment by RunningLeon** [comment]
@Galaxy-Husky hi, thanks for your feedback. Could you use `load_state_dict`  and change the checkpoint_path accordingly?
```

from transformers.modeling_utils import load_state_dict
state_dict = load_state_dict(checkpoint_path, map_location=device) 
```

**Comment by Galaxy-Husky** [comment]
> @Galaxy-Husky hi, thanks for your feedback. Could you use `load_state_dict` and change the checkpoint_path accordingly?
> 
> ```
> 
> from transformers.modeling_utils import load_state_dict
> state_dict = load_state_dict(checkpoint_path, map_location=device) 
> ```

Hi. The function `load_state_dict` worked but I made some changes.

I replaced the original code:
```
     checkpoint_path = f'{path}/adapter_model.bin' 
     state_dict = torch.load(checkpoint_path, map_location=device) 
```
with:
```
      from transformers.modeling_utils import load_state_dict
      
      checkpoint_path = f'{path}/adapter_model.safetensors'
      state_dict = load_state_dict(checkpoint_path) 
```

**Comment by RunningLeon** [comment]
hi, seems it has `map_location` argument. 
you can import os and check which `path` exists.

https://github.com/huggingface/transformers/blob/c7a109ec81fb38fdd77d1d0543a9233bc6bf4d09/src/transformers/modeling_utils.py#L495

**Comment by Galaxy-Husky** [comment]
> hi, seems it has `map_location` argument. And you can import os and check which `path` exists.
> 
> https://github.com/huggingface/transformers/blob/c7a109ec81fb38fdd77d1d0543a9233bc6bf4d09/src/transformers/modeling_utils.py#L495

Yes, it has. I didn't find it because I didn't upgrade `transformers` to the latest version.
The version restrictions of `transformers` in the requirements may need to be set explicitly. And those in `check_env` may need to be modified:
https://github.com/InternLM/lmdeploy/blob/9bfdeaece9b5c6138a46f662f090e3e7ee926ea5/lmdeploy/pytorch/check_env/__init__.py#L121-L122

I have updated the code:
```
        from transformers.modeling_utils import load_state_dict
        import os

        checkpoint_path = f'{path}/adapter_model.bin'
        if not os.path.exists(checkpoint_path):
            checkpoint_path = f'{path}/adapter_model.safetensors'
        state_dict = load_state_dict(checkpoint_path, map_location=device)
```

**Comment by RunningLeon** [comment]
@Galaxy-Husky Hi, glad it works. Yes, you are right. But since lmdeploy has not been fully tested on the latest transformer and the version is not strictly restricted to the range, we can leave it as it is.

https://github.com/InternLM/lmdeploy/blob/9bfdeaece9b5c6138a46f662f090e3e7ee926ea5/lmdeploy/pytorch/check_env/__init__.py#L165

BTW, could you pull a request to lmdeploy to fix this issue? THX

**Comment by Galaxy-Husky** [comment]
> @Galaxy-Husky Hi, glad it works. Yes, you are right. But since lmdeploy has not been fully tested on the latest transformer and the version is not strictly restricted to the range, we can leave it as it is.
> 
> https://github.com/InternLM/lmdeploy/blob/9bfdeaece9b5c6138a46f662f090e3e7ee926ea5/lmdeploy/pytorch/check_env/__init__.py#L165
> 
> BTW, could you pull a request to lmdeploy to fix this issue? THX

Sure, I'd love to.
