### ISSUE TITLE
Poor performance of Molmo pointing function

### ISSUE THREAD

**Issue by zhujingsong** [InternLM/lmdeploy#2856]
The most import feature of Molmo is that when you prompt like "Point to xxxxxx", it will return a valid point coordinate.
When I use the transformer library as https://huggingface.co/allenai/Molmo-7B-D-0924 and https://colab.research.google.com/drive/1O63z-Jqi6JaXQT8gbd7ryjHwAZwZfLIb?usp=sharing, I get pretty good results.

But when I use the Molmo model in LMDeploy api_server, I get really bad results.

**Comment by lvhan028** [comment]
fixed in PR https://github.com/InternLM/lmdeploy/pull/2810

**Comment by lvhan028** [comment]
@zhulinJulia24 may put it in our test case
