### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by chailt** [InternLM/lmdeploy#286]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

通过新的openai.api_server启动服务后出现回复乱码情况

### Reproduction

python -m lmdeploy.serve.openai.api_server ./workspace 0.0.0.0 23333 --instance_num 32 --tp 2

curl http://0.0.0.0:23333/generate   -H "Content-Type: application/json"   -d '{
    "model": "vicuna",
    "prompt": "Hello! Ho are you?",
    "sequence_start": true,
    "sequence_end": true
  }'
  
![image](https://github.com/InternLM/lmdeploy/assets/128781283/ce8c83a3-f629-4fe9-9678-46b710e82b36)

### Error traceback

```Shell
{"text":"Fot wall führtecard bytesChild коло führtecardtrecardChildChild führtecard führteьюcardChild führteьюью коло führte führtebeckChildьюChild führte коло колоcardtreChild führtebecktreью tyChildью колоьюью колоChild führtebeck führtephasьюью refugeChildbeckChildcardью колоChildChildbeck führtebeckChildcardbeckChild führtebeckChildbeckChildью führte колоChild führtetreChildью колоcardbeckbeckbeckьюChildChild wallcard führteilliant надмор枓ью führte ty führteilliant啰 tyьюьюьюChild колоbeckChild führtebeckbeckьюbeckью führteьюbeckChildьюChild wallChild führtebased wallbeckbeckbeckChildPlease MR führte führtebasedChild міста wall bytes MR wall führte führtebeckbeckChild wallChild MR führte führte wallChild wall wallChild führtebeck wallChild wall führtebeckcard колоChildChild wallChild wall колоtre führte枓 коло колоChildChild wall колоChild führtebeck коло führtebased führtebeck führte führte führte führtebasedChildosing sty führte bytes цар führteရńskiejungungтыйcdots analyt bytes heav阑бург führte führte wall玉 führte колоowel住伴玉住伴 Sal住伴蚍becklections阑 Wie搨玉ikt items黯 Fotosing items ancien焙 items眈衔 Wie Wie伴 Fot玉阑 Wieowel哆 pec焙 Fot焙 Fot焙 Fot焙 Fotosing伴镣 Fot焙 Fotosing Fot玉 обще Fotosing Fot焙 Fot焙 Fot焙 Fotosing items Fot焙 Fot焙 Fotosing Fot焙 Fot焙 Fotosing items Fot焙 Wie Fotosing items Fot焙 Fot焙 Fotosing Fot焙 Fotosing items Fot焙 Fot焙 Fot producer焙 Fot sty producer็玉็ sty sty Pen Fot焙 Fotosing Fot Pen Fot็铍osing Fot Pen Fotosing Fotosing items Fotosing Fot焙 items Fotosing Fot sty skills Fot producerosing Fot็ Fot sty sty sty inn焙 Fot焙 Fot producer sty็็ sty styosing fairographic Fot焙镣 styosing Fot็ stypartyosingopenosing Fotparty็ sty producer็ producer焙owel sty producer producer็焙镣osing Fot焙 Fotosing Fot็ sty sty styosing焙 Fot knew็osing Fot็osing Fot焙 Fotosing Fot焙眵镣 Fotosing Fotosing Fot sty sty็party焙 Pen Fot焙 Fot焙 styosing Fot producer็ inn sty sty焙osing Fotosing Fot焙 Fot焙 styosing Fot焙眵玉็焙 sty sty焙 sty焙party knew producer styosing焙owel inn็焙็焙 inn焙็osing็ Pen Fot sty producerosing็osing镣 sty็osingosingistic Fot producer็osingosing","tokens":513,"finish_reason":null}
```

**Comment by AllentDan** [comment]
So, you are using a vicua-13b model?

**Comment by chailt** [comment]
是的

**Comment by AllentDan** [comment]
Can you run it normally through `lmdeploy/turbomind/chat.py`?

**Comment by chailt** [comment]
bash workspace/service_docker_up.sh
python3 -m lmdeploy.app 0.0.0.0：33337
这样得方式是可以正常运行的

**Comment by AllentDan** [comment]
Please help me test if `lmdeploy/turbomind/chat.py` works fine for you since restful-api depends on it.

**Comment by chailt** [comment]
好的，等我明天测试以后跟您反馈

**Comment by chailt** [comment]
您好，问题已解决
解决过程，我只用的是0.0.1版本去转换为 trubomind 要求的格式，会出现乱码的情况，使用openai.api_server，需要将代码更新到最新，然后重新转换模型。
![image](https://github.com/InternLM/lmdeploy/assets/128781283/340b1b53-beff-47c2-9696-1d2d8d91937c)

**Comment by chailt** [comment]
想请问一下openai.api_server是否支持这种方式请求
response = openai.ChatCompletion.create(
        model="vicuna",
        api_key="key",
        api_base="http://0.0.0.0:23333/v1",
        prompt=text,
        stream=True,
    )

**Comment by AllentDan** [comment]
> 想请问一下openai.api_server是否支持这种方式请求 response = openai.ChatCompletion.create( model="vicuna", api_key="key", api_base="http://0.0.0.0:23333/v1", prompt=text, stream=True, )

这个你可以按照api_client自己构建一个类
