### ISSUE TITLE
[Feature] how to adding a new model as vllm

### ISSUE THREAD

**Issue by hhf-hu** [InternLM/lmdeploy#2861]
### Motivation

https://docs.vllm.ai/en/latest/models/adding_model.html

**Comment by lvhan028** [comment]
@RunningLeon please update `pytorch_new_model.md`

**Comment by RunningLeon** [comment]
@hhf-hu Hi, thanks for the feedback. Multimodal models are supported in lmdeploy's two engines and the tutorials based on PR https://github.com/InternLM/lmdeploy/pull/2810 would be updated later.

**Comment by RunningLeon** [comment]
Ok

> @RunningLeon `pytorch_new_model.md` guides users about how to add a LLM model support in pt engine rather than a VLM model

ok

**Comment by hhf-hu** [comment]
ok，thank you

---- Replied Message ----
| From | ***@***.***> |
| Date | 12/10/2024 18:57 |
| To | InternLM/lmdeploy ***@***.***> |
| Cc | hhf ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [InternLM/lmdeploy] [Feature] how to adding a new model as vllm (Issue #2861) |

@hhf-hu Hi, sorry for the misunderstanding. Actually, we have a turtorial for adding new models in pytorch engine. Pls. refer to
https://lmdeploy.readthedocs.io/en/latest/advance/pytorch_new_model.html
