### ISSUE TITLE
[Bug]  lmdeploy[432]: OSError: image file is truncated

### ISSUE THREAD

**Issue by vjaideep08** [InternLM/lmdeploy#2869]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

Hi 
I have been encountered with this bug 

  **images = [x.convert('RGB') for x in images]**
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/ubuntu/multimodal/cpm/work/lmdeploy_deployment/venv_lmdeploy/lib/python3.11/site-packages/lmdeploy/vl/model/minicpmv.py", line >
lmdeploy[432]:     images = [x.convert('RGB') for x in images]
lmdeploy[432]:               ^^^^^^^^^^^^^^^^
File "/home/ubuntu/multimodal/cpm/work/lmdeploy_deployment/venv_lmdeploy/lib/python3.11/site-packages/PIL/Image.py", line 995, in convert
self.load()
File "/home/ubuntu/multimodal/cpm/work/lmdeploy_deployment/venv_lmdeploy/lib/python3.11/site-packages/PIL/ImageFile.py", line 280, in load
**raise OSError(msg) from e
lmdeploy[432]: OSError: image file is truncated**

Hi can some one help me how to solve the same as I am just using LMdeploy to deploy my MLLM. I cant edit any code or habdle it with 
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True

as i am using api_serve to access the deployed MLLM.

### Reproduction

lmdeploy serve api_server <path to the model>/quantized_minicpm_model_imvlm/openbmb/MiniCPM-Llama3-V-2_5-4bit --server-port 5004

### Environment

```Shell
lmdeploy check_env : 

sys.platform: linux
Python: 3.11.4 (main, Jul  5 2023, 14:15:25) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA A10G
CUDA_HOME: None
GCC: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 2.2.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF,

TorchVision: 0.17.2+cu121
LMDeploy: 0.5.1+
transformers: 4.43.2
gradio: Not Found
fastapi: 0.111.1
pydantic: 2.8.2
triton: 2.2.0
NVIDIA Topology:
        GPU0    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      0-3     0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

**Comment by irexyc** [comment]
Your LMDeploy version is too old(0.5.1). You can update LMDeploy to latest version, the latest code has `ImageFile.LOAD_TRUNCATED_IMAGES = True` setting https://github.com/InternLM/lmdeploy/blob/v0.6.4/lmdeploy/vl/utils.py#L63

**Comment by vjaideep08** [comment]
Thanks @irexyc i changed the code in utils.py. 
Will also update the LMDeploy version to latest. 

Thanks a lott @irexyc
