### ISSUE TITLE
[Docs] 模型推理时显存占用比使用transformers大

### ISSUE THREAD

**Issue by ExploreUniverser** [InternLM/lmdeploy#2875]
### 📚 The doc issue

背景：我想量化MiniCPM-V-2_6，我在使用swift微调、合并，使用lmdeploy量化后，发现模型加载推理时显存的占用量达到大约67GB，代码如下：
`model_path = 'OpenBMB/output/MiniCPM-V-2_6_int4'
pipe = pipeline(model_path,backend_config=TurbomindEngineConfig(tp=1),chat_template_config=ChatTemplateConfig(model_name='minicpmv'))`
而使用transformers库，原模型MiniCPM-V-2_6加载推理只需要 16GB，代码如下：
`model_path = 'OpenBMB/output/MiniCPM-V-2_6'
model = AutoModel.from_pretrained(model_path, trust_remote_code=True,
    attn_implementation='sdpa', torch_dtype=torch.bfloat16)
model = model.eval().cuda()`
这是为什么？我又试了试使用lmdeploy加载原模型MiniCPM-V-2_6，发现显存占用大约 69GB，为什么差距这么大，我的推理代码有问题吗？
显卡配置：NVIDIA A800
lmdeploy：0.6.3

**Comment by ExploreUniverser** [comment]
上面MiniCPM-V-2_6_int4的代码写错了，应该是TurbomindEngineConfig(model_format='awq',tp=1)，但显存太大的问题还是有

**Comment by lvhan028** [comment]
https://lmdeploy.readthedocs.io/en/latest/llm/pipeline.html
请阅读这篇文档，里面说明了显存分配的方式
