### ISSUE TITLE
KV cache INT4/INT8

### ISSUE THREAD

**Issue by hhf-hu** [InternLM/lmdeploy#2884]
### 📚 The doc issue

Why is the improvement in inference efficiency after quantization of internlm2-chat-7b smaller compared to llama2？
link：https://lmdeploy.readthedocs.io/en/latest/quantization/kv_quant.html#performance

**Comment by lzhangzz** [comment]
The samller llama2 models do not use GQA.

**Comment by hhf-hu** [comment]
> The samller llama2 models do not use GQA.

thank you
