### ISSUE TITLE
[Feature] InternVL2.5 TurboMind backend support

### ISSUE THREAD

**Issue by laserwave** [InternLM/lmdeploy#2885]
### Motivation

InternVL2.5以internlm2.5为llm基座的模型，目前看起来是可以awq量化、使用TurboMind后端部署的。以qwen2.5为基座的模型似乎还不支持，请问有相关支持的计划吗

**Comment by lvhan028** [comment]
v0.6.4 都支持了的。遇到了什么问题了么？

**Comment by laserwave** [comment]
更新到v0.6.4已解决
