### ISSUE TITLE
[Feature] How to get actual request_output_len if the early stop happened?

### ISSUE THREAD

**Issue by wanzhenchn** [InternLM/lmdeploy#292]
### Motivation

For example, the [request_output_len](https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/serve/turbomind/chatbot.py#L116) = 256, if the early stop happened, we assume the actual output_token_len is 180, The `chatbot.stream_infer()` seems to return the expected generated token number 256 rather than 180.  The pro

So how to get the actual generated token len in GRPCServer ?

**Comment by lvhan028** [comment]
`chatbot.stream_infer` yields `status`, `text`, and `n_tokens`, among which `text` refers to the generated text and `n_tokens` means the number of completion tokens.

You can hardcode `serve/client.py` as below to check if it is the case
```
chatbot = Chatbot(tritonserver_addr,
                      log_level=log_level,
                      display=False) # disable showing AI assistant answer in console
```

```
 if stream_output:
                for status, res, n_token in chatbot.stream_infer(
                        session_id,
                        prompt,
                        request_id=request_id,
                        request_output_len=512):
                    print(status, n_token, res)
```

**Comment by wanzhenchn** [comment]
> 

Thanks for your reply.

I have tested the case in my situation. The expected out_token_length is 180 although the resquest_out_token_len is 256, it seems that the early stop is not happened.

BTW, the parameters of top_k, top_p, temperature, repetition_penalty in LMDeploy is aligned with my case.

**Comment by wanzhenchn** [comment]
> `chatbot.stream_infer` yields `status`, `text`, and `n_tokens`, among which `text` refers to the generated text and `n_tokens` means the number of completion tokens.
> 
> You can hardcode `serve/client.py` as below to check if it is the case
> 
> ```
> chatbot = Chatbot(tritonserver_addr,
>                       log_level=log_level,
>                       display=False) # disable showing AI assistant answer in console
> ```
> 
> ```
>  if stream_output:
>                 for status, res, n_token in chatbot.stream_infer(
>                         session_id,
>                         prompt,
>                         request_id=request_id,
>                         request_output_len=512):
>                     print(status, n_token, res)
> ```

Thanks for your reply.

I have tested the case in my situation. The expected out_token_length is 180 although the resquest_out_token_len is 256, it seems that the early stop is not happened.

BTW, the parameters of top_k, top_p, temperature, repetition_penalty in LMDeploy is aligned with my case.

**Comment by lvhan028** [comment]
Which model are you using? Let me reproduce it

**Comment by wanzhenchn** [comment]
model: llama-13b-hf
             https://huggingface.co/lmsys/vicuna-13b-v1.5/tree/main
             https://huggingface.co/lmsys/vicuna-13b-delta-v1.1

top_k, top_p, temperature, repetition_penalty = 3, 0.95, 0, 1.15

follow the description: https://github.com/InternLM/lmdeploy/blob/main/docs/en/serving.md#serving-vicuna
