### ISSUE TITLE
Integration with LangChain

### ISSUE THREAD

**Issue by Nikita-Sherstnev** [InternLM/lmdeploy#293]
Hi there, I would like to integrate a model backed by TurboMind with my LangChain code. I tried using 'generator.stream_infer' in a Jupyter notebook, and it crashes when I attempt to run it multiple times. I can see that it spawns some threads. Is there any way to run inference in both my script and Jupyter?

**Comment by lvhan028** [comment]
Let me try the Jupyter notebook. I'll get back to you if there is any update

**Comment by Nikita-Sherstnev** [comment]
I have set response_size to 0 and nth_round to 1 before every inference and it worked just fine.

**Comment by Nikita-Sherstnev** [comment]
@kristiankielhofner It's very simple, just take this function https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/turbomind/chat.py#L85 
If you do not want stream output - set nth_round to 1 and response_size to 0 and do not increment them.
