### ISSUE TITLE
[Question] How to run specific version of model from huggingface

### ISSUE THREAD

**Issue by bbkgh** [InternLM/lmdeploy#2936]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

Hi. I want to run 'unsloth/Llama-3.3-70B-Instruct-GGUF:F16' but serve returns following error. How can i fix this?
```
$ lmdeploy serve api_server 'unsloth/Llama-3.3-70B-Instruct-GGUF:F16'
Traceback (most recent call last):
  File "/home/bghadiri/miniconda3/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/bghadiri/miniconda3/lib/python3.12/site-packages/lmdeploy/cli/entrypoint.py", line 31, in run
    args.model_path = get_model(args.model_path,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bghadiri/miniconda3/lib/python3.12/site-packages/lmdeploy/utils.py", line 206, in get_model
    model_path = snapshot_download(pretrained_model_name_or_path,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bghadiri/miniconda3/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/bghadiri/miniconda3/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'unsloth/Llama-3.3-70B-Instruct-GGUF:F16'.

```

### Reproduction

lmdeploy serve api_server 'unsloth/Llama-3.3-70B-Instruct-GGUF:F16'

### Environment

```Shell
-
```

**Comment by irexyc** [comment]
To run specific version of model, you can add `--revision` parameter, but we dont' support gguf format.

Maybe you could run `lmdeploy serve api_server unsloth/Llama-3.3-70B-Instruct --revision b6284849f6901630c95ed3a4f3345a2b4f2bc759`
