### ISSUE TITLE
[Bug] Numerical Error in Flash Attention

### ISSUE THREAD

**Issue by YYue000** [InternLM/lmdeploy#2957]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

when comparing results generated by flash_attention_fwd in lmdeploy and torch.nn.functional.scaled_dot_product_attention, a significant difference occurs.

### Reproduction

# replicative errors

```Python

import torch
q = torch.randn([2,32,64], dtype=torch.bfloat16, device="cuda:0")
print(q.shape)
from lmdeploy.pytorch.kernels.cuda import flash_attention_fwd
attn_output = q.new_empty(q.shape)
q2 = torch.rand(q.shape).to(q)
k2 = torch.rand(q.shape).to(q)
v2 = torch.rand(q.shape).to(q)
attn_output = q.new_empty(q.shape)
flash_attention_fwd(
                    q2,
                    k2,
                    v2,
                    attn_output,
                    q_start_loc=torch.tensor([0], device=q.device, dtype=torch.int64),
                    q_seqlens=torch.tensor([q.shape[0]], device=q.device, dtype=torch.int64),
                    kv_start_loc=torch.tensor([0], device=q.device, dtype=torch.int64),
                    kv_seqlens=torch.tensor([q.shape[0]], device=q.device, dtype=torch.int64),
                    max_seqlen=q.numel() // (q.size(-1) * q.size(-2)),
                )
qq2, kk2, vv2 = [_.transpose(0,1).unsqueeze(0) for _ in [q2,k2,v2]]
libr = torch.nn.functional.scaled_dot_product_attention(qq2, kk2, vv2).transpose(1,2)[0]
print(torch.mean(torch.abs(attn_output-libr)))
```

The above codes will always lead to a remarkable numerical difference. 
Note that we also compare them with hugging face attention implementation, which is roughly

```Python
# hf ref
import torch
import torch.nn as nn
def repeat_kv(hidden_states: torch.Tensor, n_rep: int) -> torch.Tensor:
    """
    This is the equivalent of torch.repeat_interleave(x, dim=1, repeats=n_rep). The hidden states go from (batch,
    num_key_value_heads, seqlen, head_dim) to (batch, num_attention_heads, seqlen, head_dim)
    """
    batch, num_key_value_heads, slen, head_dim = hidden_states.shape
    if n_rep == 1:
        return hidden_states
    hidden_states = hidden_states[:, :, None, :, :].expand(batch, num_key_value_heads, n_rep, slen, head_dim)
    return hidden_states.reshape(batch, num_key_value_heads * n_rep, slen, head_dim)


def eager_attention_forward(
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attention_mask: torch.Tensor,
    scaling: float,
    **kwargs,
):
    # batch, num_key_value_heads, slen, head_dim = hidden_states.shape
    num_key_value_groups = query.shape[1]//key.shape[1]
    key_states = repeat_kv(key, num_key_value_groups)
    value_states = repeat_kv(value, num_key_value_groups)

    attn_weights = torch.matmul(query, key_states.transpose(2, 3)) * scaling
    if attention_mask is not None:
        causal_mask = attention_mask[:, :, :, : key_states.shape[-2]]
        attn_weights = attn_weights + causal_mask

    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=kwargs["dtype"]).to(query.dtype)
    attn_weights = nn.functional.dropout(attn_weights, p=0.0, training=False)
    attn_output = torch.matmul(attn_weights, value_states)
    attn_output = attn_output.transpose(1, 2).contiguous()

    return attn_output, attn_weights
```
We notice this hf version will be exactly equivalent to torch.nn.functional.scaled_dot_product_attention in float32. These two will have a marginal numerical difference, usually less than 1e-4 per entry, while the difference between flash_attention_fwd and torch.nn.functional.scaled_dot_product_attention will be up to 0.26. Moreover, when observing the entries in the result matrix, the hf and scaled_dot_product_attention versions have similar values but the flash_attention_pwd gives quite different results.

# additional findings

We also found something interesting. The codes below will give a consistent result.

```Python

import torch
q = torch.randn([2,32,64], dtype=torch.bfloat16, device="cuda:0")
print(q.shape)
from lmdeploy.pytorch.kernels.cuda import flash_attention_fwd
attn_output = q.new_empty(q.shape)
q2 = torch.rand(q.shape).to(q)
k2 = torch.rand(q.shape).to(q)
v2 = torch.ones(q.shape).to(q)*0.002 # here 0.002 could be any numbers
attn_output = q.new_empty(q.shape)
flash_attention_fwd(
                    q2,
                    k2,
                    v2,
                    attn_output,
                    q_start_loc=torch.tensor([0], device=q.device, dtype=torch.int64),
                    q_seqlens=torch.tensor([q.shape[0]], device=q.device, dtype=torch.int64),
                    kv_start_loc=torch.tensor([0], device=q.device, dtype=torch.int64),
                    kv_seqlens=torch.tensor([q.shape[0]], device=q.device, dtype=torch.int64),
                    max_seqlen=q.numel() // (q.size(-1) * q.size(-2)),
                )
qq2, kk2, vv2 = [_.transpose(0,1).unsqueeze(0) for _ in [q2,k2,v2]]
libr = torch.nn.functional.scaled_dot_product_attention(qq2, kk2, vv2, enable_gqa=True).transpose(1,2)[0]
print(torch.mean(torch.abs(attn_output-libr)))
```

We then further explored a less random case, which also fails to fall within a reasonable difference from pytorch lib implementation.

```Python

import torch
q = torch.randn([2,32,64], dtype=torch.bfloat16, device="cuda:0")
print(q.shape)
from lmdeploy.pytorch.kernels.cuda import flash_attention_fwd
attn_output = q.new_empty(q.shape)
q2 = torch.rand(q.shape).to(q)
k2 = torch.rand(q.shape).to(q)
v2 = torch.ones(q.shape).to(q)*0.002 # here 0.002 could be any numbers
v2[0,0,0] = 3.2
attn_output = q.new_empty(q.shape)
flash_attention_fwd(
                    q2,
                    k2,
                    v2,
                    attn_output,
                    q_start_loc=torch.tensor([0], device=q.device, dtype=torch.int64),
                    q_seqlens=torch.tensor([q.shape[0]], device=q.device, dtype=torch.int64),
                    kv_start_loc=torch.tensor([0], device=q.device, dtype=torch.int64),
                    kv_seqlens=torch.tensor([q.shape[0]], device=q.device, dtype=torch.int64),
                    max_seqlen=q.numel() // (q.size(-1) * q.size(-2)),
                )
qq2, kk2, vv2 = [_.transpose(0,1).unsqueeze(0) for _ in [q2,k2,v2]]
libr = torch.nn.functional.scaled_dot_product_attention(qq2, kk2, vv2).transpose(1,2)[0]
print(torch.mean(torch.abs(attn_output-libr)))
```

Could you help me figure out what's wrong here? Thanks a lot.

### Environment

```Shell
torch version: 2.4.0+cu121

python version: 3.8.20
```

**Comment by grimoire** [comment]
The default input kv layout is `(num_heads, seqlens, head_dim)` (which is more friendly to load kv). You can pass `kv_layout=shd` to enable SPDA like layout.

**Comment by YYue000** [comment]
> The default input kv layout is `(num_heads, seqlens, head_dim)` (which is more friendly to load kv). You can pass `kv_layout=shd` to enable SPDA like layout.

Thanks for your advice! I do confirm the mismatch here.

Following your suggestion, I tried 2 equivalent implementations to fix it. 1) use k2.transpose(0,1) and v2.transpose(0,1) to feed into flash_attention_fwd 2) use kv_layout='shd' directly.

However, both of these two attempts give a result of around 0.08 in difference from torch.nn.functional.scaled_dot_product_attention.

Therefore, I would infer there are still some issues inside my codes or the kernel. By the way, I suggest the layout issue should not result in the results in the last experiment in the "additional findings" part I mentioned before.

**Comment by grimoire** [comment]
I can not reproduce with the code you provided. Transpose kv or `kv_layout='shd' ` leads to mean diff `0.0004`.
Could you provide more detail about your environment? You can use `lmdeploy check_env` to gather the information.

**Comment by YYue000** [comment]
> I can not reproduce with the code you provided. Transpose kv or `kv_layout='shd' ` leads to mean diff `0.0004`. Could you provide more detail about your environment? You can use `lmdeploy check_env` to gather the information.

Thanks for your reply. The .pkl in the zip file contains q,k,v, and corresponding attention outputs of flash_attention_fwd and hf reference. My diff mean is around 0.8.

Besides, as you instructed, the env information generated by "lmdeploy check_env" is available in the file env.log.

I do appreciate your help and am looking forward to your further reply.

[fa.zip](https://github.com/user-attachments/files/18265067/fa.zip)
[env.log](https://github.com/user-attachments/files/18265109/env.log)

**Comment by grimoire** [comment]
fa.zip is corrupted

**Comment by YYue000** [comment]
> fa.zip is corrupted

Just to remind that

1) please unzip it first to get the .pkl file

2) please use pickle.load to load it, and in turn you're expected to get a dict with tensors. It was dumped as the following picture shows.

![6b4eb288974f620e74c76e34deaf4d0](https://github.com/user-attachments/assets/51d81e92-c258-4e04-81ee-de059e27f35f)

**Comment by grimoire** [comment]
flash_attention_fwd `causal=True`, scaled_dot_product_attention `is_causal=False`.

**Comment by YYue000** [comment]
> flash_attention_fwd `causal=True`, scaled_dot_product_attention `is_causal=False`.

Thank you so much for your patience and help.
