### ISSUE TITLE
turbomind架构支持嵌入式模型吗？

### ISSUE THREAD

**Issue by llery** [InternLM/lmdeploy#2971]
需要在新增模型的forward内将input_ids转成input_embedding后，再将图片tensor按照自定义逻辑嵌入到input_embedding合成hidden_states，turbomind架构目前支持吗？（或以后能支持吗？）

**Comment by lvhan028** [comment]
支持。turbomind.py 中 stream_infer 接口支持传入 input_embeddings, embedding_ranges。分别表示传入的 embedding，以及 embedding 在hidden_states中需要插入的位置。

**Comment by llery** [comment]
好的感谢，看到stream_infer/async_stream_infer接口了。
要提前构造好input_embeddings, embedding_ranges数据送到stream_infer或async_stream_infer，那是不是还是必须要load一遍VL Model，并调其forward方法才能拿到图片的embeddings？turbomind架构再载一遍hf感觉有点累赘了，还是我理解的不对？

VL Model
 ````
@torch.no_grad()
    def forward(self,
                images: List[Image],
                params: List[Dict] = None) -> List[torch.Tensor]:
        """forward."""
        # only support image input
       .....
````

**Comment by lvhan028** [comment]
目前 tm 在支持 vlm 模型推理时，会抽出 vision 模型，llm 模型。
vision模型使用 transformers (含 remote code) 进行 forward 抽取特征，llm 部分交给 tm 引擎做。

在 < v0.6.5 时，pt engine 和 tm engine都使用的此逻辑。

但自 0.6.5 版本起，pt engine 的实现方式改变。vision 模型的 forward 也在 pt 中实现。pt 不再支持 embedding 和 embedding_range作为输入。

**Comment by llery** [comment]
嗯嗯，好的，非常感谢。我主要想实现 tm engine 下推理，总的来说就是 tm engine下（不论 0.6.5还是以前的版本）
 _vision模型使用 transformers (含 remote code) 进行 forward 抽取特征_   这是绕不过去的步骤对吧？
之前主要是纠结：我抽取图像特征值其实只用到模型里面很少的权重，不大想加载整个好几G的全部权重 :）

**Comment by llery** [comment]
问题搞定，可以不用加载整个transformers模型权重，把只涉及到图像特征提取的层的权重可以单独摘出来使用就可以了，感谢 @lvhan028

**Comment by lvhan028** [comment]
嗯，没错，抽出vision模型就好。
