### ISSUE TITLE
[Docs] What's the difference between the support for llama and vicuna? 

### ISSUE THREAD

**Issue by sleepwalker2017** [InternLM/lmdeploy#298]
### 📚 The doc issue

I run python3 -m lmdeploy.serve.turbomind.deploy test /data/
and get this

AssertionError: 'test' is not supported. The supported models are: dict_keys(['llama', 'vicuna', 'internlm', 'internlm-chat-7b', 'internlm-chat-7b-8k', 'puyu', 'baichuan-7b', 'llama2'])
Is there any difference between llama and vicuna? Or they are the same, just for easier usage?

**Comment by tpoisonooo** [comment]
llama and vicuna has different chat template,  so we have to dictinct these models.

When convert huggingface model to turbomind format,  you have to tell `deploy`:  this is a vicuna model.

**Comment by sleepwalker2017** [comment]
> 

in terms of model inference, the implementation are the same, right?

**Comment by lvhan028** [comment]
> > 
> 
> in terms of model inference, the implementation are the same, right?

Yes
