### ISSUE TITLE
[Feature] prompt相关

### ISSUE THREAD

**Issue by Vincent131499** [InternLM/lmdeploy#299]
### Motivation

在lmdeploy/serve/turbomind/chatbot.py看到了Session里面有存放对话信息的histories。
但是在第二轮时，发现并没有将histories和当前input_text一起传给triton server的代码，请问在多轮对话时是怎么处理的呢？求指教

**Comment by lvhan028** [comment]
因为历史对话的k/v 都被 turbomind 缓存了

**Comment by Vincent131499** [comment]
明白了，感谢！
我现在训练llama2模型使用的是下面这种模板：
单轮prompt:
"[INST] <<SYS>>\nYou are a helpful assistant. 你是一个乐于助人的助手。\n<</SYS>>\n\nHuman: 你好\nAssistant:  [/INST]"
多轮prompt:
"[INST] <<SYS>>\nYou are a helpful assistant. 你是一个乐于助人的助手。\n<</SYS>>\n\nHuman: 你好\nAssistant: 你好，很高兴认识你！\nHuman: 明天天气 Assistant: [/INST]"

在多轮的时候会把“Huma: xxx\nAssistant: xxx”包进模板中，这种要怎么适配turbomind呢，没找到好的办法，有什么建议吗

**Comment by Vincent131499** [comment]
求指点

**Comment by lvhan028** [comment]
你看一下lmdeploy/model.py，里面有已支持模型的对话模板
