### ISSUE TITLE
[Feature] llama_gemm may be added when compiling wheels 

### ISSUE THREAD

**Issue by sleepwalker2017** [InternLM/lmdeploy#300]
### Motivation

![image](https://github.com/InternLM/lmdeploy/assets/26128514/4e12627c-f0b7-4831-bccf-7b5840491323)
![image](https://github.com/InternLM/lmdeploy/assets/26128514/5c44676a-efd7-4974-885d-a1bf23f131d0)

Here is the difference, both on V100, before and after tuning, the performance diffs a lot.

so llama_gemm is needed in some cases.

### Related resources

vicuna-v1.5 13B 
python profile_generation.py workspace --input_seqlen 512 --output_seqlen 192 --test_round 1 --concurrency 1

**Comment by lvhan028** [comment]
@irexyc I think we pack the executable `bin/llama_triton_example` to data_files, and use subprocess to launch it after installing lmdeploy. Could help check whether it works?
