### ISSUE TITLE
[Bug] vicuna-13b做w4量化部署后智障了

### ISSUE THREAD

**Issue by 18065013** [InternLM/lmdeploy#302]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

描述该错误
<img width="828" alt="e1" src="https://github.com/InternLM/lmdeploy/assets/80082466/cef0efb7-32bd-442d-8f52-d103f4aedc14">
<img width="648" alt="e2" src="https://github.com/InternLM/lmdeploy/assets/80082466/d1ca64a9-6f44-4bfe-82da-5948694c1217">
<img width="543" alt="e3" src="https://github.com/InternLM/lmdeploy/assets/80082466/ab6b65c2-aff0-4557-93c7-b1876b3c1ce0">

cd /models
git clone https://huggingface.co/lmsys/vicuna-13b-v1.1

python3 -m lmdeploy.lite.apis.calibrate --model /models/vicuna-13b-v1.1 --calib_dataset 'c4' --calib_samples 128 --calib_seqlen 2048 --work_dir output

python3 -m lmdeploy.lite.apis.auto_awq --model /models/vicuna-13b-v1.1 --w_bits 4 --w_group_size 128 --work_dir output

python3 -m lmdeploy.serve.turbomind.deploy vicuna /output --model-format awq --group-size 128 --tp=2
这一步非常慢，我好几次都中断了，要等5分钟左右

python3 -m lmdeploy.turbomind.chat ./workspace --tp=2
这一步也慢，需要等些时间

聊天结果，这里就变成智障了，整个流程是通的，结果就智障了

### Reproduction

cd /models
git clone https://huggingface.co/lmsys/vicuna-13b-v1.1

python3 -m lmdeploy.lite.apis.calibrate --model /models/vicuna-13b-v1.1 --calib_dataset 'c4' --calib_samples 128 --calib_seqlen 2048 --work_dir output

python3 -m lmdeploy.lite.apis.auto_awq --model /models/vicuna-13b-v1.1 --w_bits 4 --w_group_size 128 --work_dir output

python3 -m lmdeploy.serve.turbomind.deploy vicuna /output --model-format awq --group-size 128 --tp=2
这一步非常慢，我好几次都中断了，要等5分钟左右

python3 -m lmdeploy.turbomind.chat ./workspace --tp=2
这一步也慢，需要等些时间

**Comment by lvhan028** [comment]
@irexyc Please help investigate this issue, especially the chat template.

**Comment by pppppM** [comment]
应该是量化算法的默认参数不能很好地量化您使用的模型，我们正在开发 AWQ 的 AutoTune 功能，有更新会第一时间通知您

The default parameters of the quantization algorithm may not be able to quantize your model effectively. We are in the process of developing the AutoTune feature for AWQ. You will be notified as soon as there are updates.

**Comment by pppppM** [comment]
@18065013 可以尝试使用最新的 lmdeploy 进行量化，我们修复了一个会导致量化精度下降的 bug #605
