### ISSUE TITLE
[Feature] locust can not launch multi-client requests on restful api server

### ISSUE THREAD

**Issue by wanzhenchn** [InternLM/lmdeploy#304]
### Motivation

- background: using [locust](https://docs.locust.io/en/stable/) to make performance test on restful server, **however, locust can not launch multi-client requests for restful api server**
- model: https://huggingface.co/lmsys/vicuna-13b-v1.5/tree/main
   - top_k, top_p, temperature, repetition_penalty = 3, 0.95, 0, 1.15
- dataset
   - https://huggingface.co/datasets/anon8231489123/ShareGPT_Vicuna_unfiltered/resolve/main/ShareGPT_V3_unfiltered_cleaned_split.json
- convert model to turbomind format
`bash
python3 -m lmdeploy.serve.turbomind.deploy llama ${vicuna_model_path} --tp 1
`
- launch restful server
`bash
CUDA_VISIBLE_DEVICES=0 python3 -m lmdeploy.serve.openai.api_server ./workspace/ localhost 10010 --instance_num 32 --tp 1
`

### Related resources

Run locust test
`locust -f locust_test.py --headless --host=http://localhost:10010 -u 2 -r 1 -t 3m --output_len=256`

```python
# locust_test.py
import json
import random
from locust import task, HttpUser, events

@events.init_command_line_parser.add_listener
def _(parser):
    parser.add_argument("--output_len", type=int, default=512, help="output len")

# get test_data
dataset_path = "ShareGPT_V3_unfiltered_cleaned_split.json"
with open(dataset_path) as f:
        dataset = json.load(f)
        dataset = [data for data in dataset if len(data['conversations']) >= 2]
        # Only keep the first two turns of each conversation.
        dataset = [(data['conversations'][0]['value'],
                    data['conversations'][1]['value']) for data in dataset]
        test_data = [prompt for prompt, _ in dataset]

top_k = 3
top_p = 0.95
beam_width = 1
temperature = 0
repetition_penalty = 1.15

def build_request(output_len):
    prompt  = random.choice(test_data)
    instance_id = random.randint(0, 32)
    input_dict = {
        'instance_id': instance_id,
        'prompt': prompt,
        'top_k': top_k,
        'top_p': top_p,
        'temperature': temperature,
        'repetition_penalty': repetition_penalty,
        'request_output_len': output_len,
        'stream': False,
        'sequence_start': True,
        'sequence_end': True
    }
    req = json.dumps(input_dict)
    return req


class MyUser(HttpUser):

    @task
    def process(self):
        req_data = build_request(self.environment.parsed_options.output_len)
        with self.client.post("/generate", data=req_data) as res:
            if res.status_code != 200:
                print("Didn't detect bad response, got: " + str(res.status_code))
```

**Comment by wanzhenchn** [comment]
@lvhan028

**Comment by AllentDan** [comment]
Hi, @wanzhenchn  What do you mean by `can not lauch multi-client requests`? What is the error?

**Comment by wanzhenchn** [comment]
> 

It seems that the server process request one by one, rather than processing requests in parallel.

I suspect there might be an issue with locust when launching multiple client requests, but I'm unsure where the problem lies. The instance_id should be set correctly without any issues.

**Comment by AllentDan** [comment]
Oh, please set stream=true when doing test. Check the [issue](https://github.com/InternLM/lmdeploy/issues/308) out.
