### ISSUE TITLE
[Bug] TypeError: 'TrainingArguments' object is not iterable

### ISSUE THREAD

**Issue by MrTFK** [InternLM/lmdeploy#306]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

When I use 
python3 -m lmdeploy.serve.turbomind.deploy llama2 path/to/llama2 hf

I get the error:
[Bug] TypeError: 'TrainingArguments' object is not iterable

### Reproduction

python3 -m lmdeploy.serve.turbomind.deploy llama2 path/to/llama2 hf

python=3.8
accelerate 0.22.0
datasets 2.14.4
fastapi 0.101.1
fire 0.5.0
gradio 3.41.1
mmengine 0.8.4
numpy 1.24.4
pybind11 2.11.1
safetensors 0.3.3
sentencepiece 0.1.99
setuptools 68.1.2
shortuuid 1.0.11
tiktoken 0.4.0
torch 2.0.1
transformers  4.32.0
tritonclient[all] 2.30.0
uvicorn 0.23.2

NVIDIA-SMI 470.129.06   Driver Version: 470.129.06   CUDA Version: 11.4 

### Error traceback

```Shell
Traceback (most recent call last):
  File "/usr/local/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tfk/.env/lib/python3.8/site-packages/lmdeploy/serve/turbomind/deploy.py", line 834, in <module>
    fire.Fire(main)
  File "/home/tfk/.env/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/tfk/.env/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/tfk/.env/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/tfk/.env/lib/python3.8/site-packages/lmdeploy/serve/turbomind/deploy.py", line 801, in main
    res = deploy_hf(model_name, model_path, tokenizer_path,
  File "/home/tfk/.env/lib/python3.8/site-packages/lmdeploy/serve/turbomind/deploy.py", line 414, in deploy_hf
    _params.update(_tmp)
TypeError: 'TrainingArguments' object is not iterable
```

**Comment by MrTFK** [comment]
> Please run "ls path/to/llama2". Let's check if the input llama2 model is correct

Thank you for your reply, get following:

added_tokens.json  config.json  generation_config.json  pytorch_model-00001-of-00003.bin  pytorch_model-00002-of-00003.bin  pytorch_model-00003-of-00003.bin  pytorch_model.bin.index.json  special_tokens_map.json  tokenizer_config.json  tokenizer.model  training_args.bin

**Comment by lvhan028** [comment]
Hi, @MrTFK 
I didn't reproduce this issue. The model I used is as follows. The log showed your llama2 model contained some uniterable key
"TrainingArguments". I think you can debug it by investigating the result after `torch.load` the model

```
/nvme/shared_data/llama2/huggingface/llama-2-7b-chat/
├── config.json
├── generation_config.json
├── pytorch_model-00001-of-00002.bin
├── pytorch_model-00002-of-00002.bin
├── pytorch_model.bin.index.json
├── special_tokens_map.json
├── tokenizer_config.json
├── tokenizer.json
└── tokenizer.model
```
