### ISSUE TITLE
Performance decay when using openai api_server

### ISSUE THREAD

**Issue by sleepwalker2017** [InternLM/lmdeploy#308]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

Seems the implementation uses only one thread to process requests, and rely on coroutine to process multiple requests.

The problem is:

in LlamaV2.cc when a LlamaV2::forward is called from the python level, the enqueue thread will wait until the request is finished. So there won't be more requests enqueue as long as there are requests being processed.

So the requests are processed one by one. Is that the fact?

```cpp
if (rank == 0) {
        TM_LOG_INFO("[forward] Enqueue requests");
        auto futures = shared_state_->request_queue.enqueue(std::move(requests));

        TM_LOG_INFO("[forward] Wait for requests to complete ...");
        for (auto& f : futures) {
            auto ec = f.get();
            error_codes.push_back(ec);
            if (ec) {
                has_error = true;
            }
        }
    }
```

### Reproduction

```python
 python -u -m lmdeploy.serve.openai.api_server ./benchmark/workspace 0.0.0.0 10086 --instance_num 32 --tp 2
```

**Comment by AllentDan** [comment]
You may have a test for like opening two clients with different instance_id 1 and 2. Check if the responses are generated simultaneously.
```bash
curl http://{server_ip}:{server_port}/generate \
  -H "Content-Type: application/json" \
  -d '{
    "prompt": "Hello!",
    "instance_id": 1,
    "sequence_start": true,
    "sequence_end": true
  }'
```
```bash
curl http://{server_ip}:{server_port}/generate \
  -H "Content-Type: application/json" \
  -d '{
    "prompt": "Hello! How are you?",
    "instance_id": 2,
    "sequence_start": true,
    "sequence_end": true
  }'
```

**Comment by sleepwalker2017** [comment]
> 

Got it. Thank you for the fast response.

In the case you mentioned, it's processed simultaneously. 

But if you use one process with multi-threads to send requests simultaneously, the requests are not processed simultaneously.  I wonder why is that?

**Comment by AllentDan** [comment]
check `benchmark/profile_restful_api.py` out. If you use one process with multi-threads to send requests simultaneously, the requests can be processed simultaneously only if you set the proper instance_id. If you set the same instance_id, the instance must wait until the last request ends. Besides, we did not implement any complicated schedule method except [a plain one](https://github.com/InternLM/lmdeploy/blob/59f8e67416e90cc82f1dafea46f95886d1b2c157/lmdeploy/serve/async_engine.py#L106). So, it could be possible session  1 is waiting for session 33 if the instance_num is 32 even if there are only these two requests.

**Comment by sleepwalker2017** [comment]
> check `benchmark/profile_restful_api.py` out. If you use one process with multi-threads to send requests simultaneously, the requests can be processed simultaneously only if you set the proper instance_id. If you set the same instance_id, the instance must wait until the last request ends. Besides, we did not implement any complicated schedule method except [a plain one](https://github.com/InternLM/lmdeploy/blob/59f8e67416e90cc82f1dafea46f95886d1b2c157/lmdeploy/serve/async_engine.py#L106). So, it could be possible session 1 is waiting for session 33 if the instance_num is 32 even if there are only these two requests.

Hi, I need to clarify it:

when setting stream is true, the requests can be processed simultaneously, when stream is set to false, persistent batching doesn't work, no matter using multiple threads or processes.

I want to check something:
1. The async api in lmdeploy.serve.openai.api_server  is a single thread function, is that right?
2. When it calls into the LlamaV2::forward func, the new request enqueue, and another thread get this request from the queue, then the main thread wait until the request is finished, is that right?
3. when waiting for the thread to be done, the newly coming requests can't be added into the queue as this thread is waiting, Is that right?

So I persist that there is something wrong in the async '/generate' api.

Hope for your reply, thank you.

**Comment by AllentDan** [comment]
Yes, you are right. It worked only when streaming is true. Or the request is stuck in model forwarding until finished.

**Comment by sleepwalker2017** [comment]
> Yes, you are right. It worked only when streaming is true. Or the request is stuck in model forwarding until finished.

thank you.
