### ISSUE TITLE
[Bug] Interrupting request halfway through generation

### ISSUE THREAD

**Issue by bryanhpchiang** [InternLM/lmdeploy#325]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

Is there some way to cancel the generation halfway through?

i.e. after `stream_infer` is called, an external source may send an "interrupt" event to immediately stop generating and to process a new request.

There's a `cancel` method on `Chatbot`, but I'm not sure how safe this is to use when there's another `stream_infer` in progress.

### Reproduction

This would be for serving with turbomind and the `client.py` and `chatbot.py` examples.

**Comment by AllentDan** [comment]
What do you mean by `another stream_infer` in progress? Every `stream_infer` progress is combined with a unique session_id. Cancel only cancel the progress with specified session_id.

**Comment by AllentDan** [comment]
Yes. It means stopping generation. You can test it with the gradio UI.

**Comment by AllentDan** [comment]
pass `stop=true` to `generate` is all you need

**Comment by AllentDan** [comment]
Yeah. I also found that interrupting too many times would cause an error.

**Comment by AllentDan** [comment]
This might not be an issue. Just don't stop and restart two fast.

**Comment by AllentDan** [comment]
The error happens only when we launch stop-only requests for inactive sequences. So, just stop requests which are active.

**Comment by AllentDan** [comment]
Run the following codes of your script:
```python
    for i in range(100):
        asyncio.run(main())
        import time
        time.sleep(0.01)
```
It would only throw the error when it exceed the max sequence length
