### ISSUE TITLE
[Bug] What is the meaning of `step`?

### ISSUE THREAD

**Issue by bryanhpchiang** [InternLM/lmdeploy#326]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

I'm trying to understand how to use the `step` argument in the client examples.

https://github.com/InternLM/lmdeploy/blob/d4d609bd8f513377bd9745974d350960ec78b087/lmdeploy/serve/turbomind/chatbot.py#L475

https://github.com/InternLM/lmdeploy/blob/d4d609bd8f513377bd9745974d350960ec78b087/lmdeploy/serve/turbomind/chatbot.py#L537

To confirm: the `step` represents the token index at which the LLM will start generating a response? In other words, let's say I've generated 100 tokens so far. If I set step back to 85 (an arbitrary choice), the LLM completion will start from token 86? Thanks!

### Reproduction

.

**Comment by lvhan028** [comment]
Yes, just as you said
