### ISSUE TITLE
[Feature] dynamic NTK scaling and logN scaling

### ISSUE THREAD

**Issue by Vincent131499** [InternLM/lmdeploy#327]
### Motivation

看到框架里支持了这套外推操作，请问要怎么配置呢？求指导

**Comment by lzhangzz** [comment]
目前转的模型只有Qwen-7B会自动根据模型配置文件在导出的config.ini中加入相关flag，其他模型可以在config.ini中加入
```
use_dynamic_ntk = 1
use_logn_attn = 1
```
打开相应选项

要注意的是目前的实现逻辑和Qwen类似，首轮对话的输入长度决定ntk_alpha

**Comment by Vincent131499** [comment]
llama2使用fp16转换成FT格式之后。在weights/config.ini里面打开：
use_dynamic_ntk = 1
use_logn_attn = 1
然后部署triton-server，但是请求结果异常，如下图所示：
![1693376170767_2A125CD8-F6BA-4cff-AA06-7397675186F0](https://github.com/InternLM/lmdeploy/assets/26675984/a78f3768-f87e-4c7b-91a1-1ad3c1c7a9b0)
如果上面两个参数设置为0，是可以正常推理的：
![image](https://github.com/InternLM/lmdeploy/assets/26675984/f1ee7486-270c-4b10-8b44-57d0d095cb6a)
麻烦检查下啊

**Comment by lzhangzz** [comment]
抱歉，还有个max_position_embeddings要设成模型本身支持的最大token数，llama2的话是4096。

**Comment by Vincent131499** [comment]
ok，正常了，感谢
