### ISSUE TITLE
[Bug] A30上int4量化后的模型推理结果乱码

### ISSUE THREAD

**Issue by pangr** [InternLM/lmdeploy#331]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

我们在A100上使用int4量化后的llama2模型在A100上推理正常，但是将量化后的模型放到A30（环境一样）上，推理的结果为乱码。之后又在A30上使用int4量化模型，但是结果在A30上依然是乱码。由于A30上的so包是在A100上编译得到的。

### Reproduction

python3 -m lmdeploy.turbomind.chat ./workspace

**Comment by matrix-yang** [comment]
我也遇到是乱码的情况，我在4090上做量化，并且在4090上推理，最后int4模型的输出全是乱码。
我不知道@pangr 说的so包是哪些？怎么重新编译他们？
