### ISSUE TITLE
[源码编译] openai server启动报错: Bus error: nonexistent physical address

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#333]
hi，我用0.0.6的代码build了一个镜像，然后在容器里运行openai server启动命令，```python3 -m lmdeploy.serve.openai.api_server /workspace/workspace_restful_tp4 0.0.0.0 33337  --instance_num 32 --tp 4```，报了这个错：

![image](https://github.com/InternLM/lmdeploy/assets/6971044/2c04ff82-b096-4bf6-9d26-cbed12876ba2)

**Comment by frankxyy** [comment]
NCCL DEBUG LOG:

f6805993d733:5847:5847 [0] NCCL INFO Bootstrap : Using eth0:172.17.0.5<0>
f6805993d733:5847:5847 [0] NCCL INFO NET/Plugin: Failed to find ncclNetPlugin_v6 symbol.
f6805993d733:5847:5847 [0] NCCL INFO NET/Plugin: Loaded net plugin NCCL RDMA Plugin (v5)
f6805993d733:5847:5847 [0] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v6 symbol.
f6805993d733:5847:5847 [0] NCCL INFO NET/Plugin: Loaded coll plugin SHARP (v5)
f6805993d733:5847:5847 [0] NCCL INFO cudaDriverVersion 12000
NCCL version 2.15.5+cuda11.8
f6805993d733:5847:5923 [0] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
f6805993d733:5847:5923 [0] NCCL INFO P2P plugin IBext
f6805993d733:5847:5923 [0] NCCL INFO NET/IB : No device found.
f6805993d733:5847:5923 [0] NCCL INFO NET/IB : No device found.
f6805993d733:5847:5923 [0] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.5<0>
f6805993d733:5847:5923 [0] NCCL INFO Using network Socket
f6805993d733:5847:5926 [3] NCCL INFO Using network Socket
f6805993d733:5847:5924 [1] NCCL INFO Using network Socket
f6805993d733:5847:5925 [2] NCCL INFO Using network Socket
f6805993d733:5847:5926 [3] NCCL INFO Setting affinity for GPU 3 to ffff0000,ffff0000
f6805993d733:5847:5924 [1] NCCL INFO Setting affinity for GPU 1 to ffff0000,ffff0000
f6805993d733:5847:5923 [0] NCCL INFO Setting affinity for GPU 0 to ffff,0000ffff
f6805993d733:5847:5925 [2] NCCL INFO Setting affinity for GPU 2 to ffff0000,ffff0000
f6805993d733:5847:5923 [0] NCCL INFO Channel 00/02 :    0   1   2   3
f6805993d733:5847:5923 [0] NCCL INFO Channel 01/02 :    0   1   2   3
f6805993d733:5847:5924 [1] NCCL INFO Trees [0] 2/-1/-1->1->0 [1] 2/-1/-1->1->0
f6805993d733:5847:5925 [2] NCCL INFO Trees [0] 3/-1/-1->2->1 [1] 3/-1/-1->2->1
f6805993d733:5847:5926 [3] NCCL INFO Trees [0] -1/-1/-1->3->2 [1] -1/-1/-1->3->2
f6805993d733:5847:5923 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1
[f6805993d733:5847 :0:5926] Caught signal 7 (Bus error: nonexistent physical address)
[1693377564.313745] [f6805993d733:5847 :1]           debug.c:1289 UCX  WARN  ucs_debug_disable_signal: signal 4 was not set in ucs
Bus error (core dumped)

**Comment by thiner** [comment]
@frankxyy 我也遇到了相同的问题。用最新的LMDeploy v0.5.2.post1 运行Qwen2-72b-AWQ-4bit 模型时报了以上错误。请问你是怎么解决的？
