### ISSUE TITLE
[Feature] Support for H100 and CUDA 12.1

### ISSUE THREAD

**Issue by orendar** [InternLM/lmdeploy#334]
### Motivation

Thank you for your incredible work!

I am interested in trying out deployment and inference on H100 GPU, for which the optimal CUDA version is 12.

Is it possible to use this library with my setup? Either with pip or by building from source?

**Comment by orendar** [comment]
By the way, I tried building from source. After running sh ../generate, I assume I am supposed to run make install -j32 or something like that to actually install the library? When I try that, I run into the following error:
```
[ 84%] Built target DynamicDecodeLayer
nvcc error   : 'ptxas' died due to signal 11 (Invalid memory reference)
make[2]: *** [src/turbomind/models/llama/flash_attention2/CMakeFiles/flash_attention2.dir/flash_fwd_hdim64_fp16_sm80.cu.o] Error 11
make[1]: *** [src/turbomind/models/llama/flash_attention2/CMakeFiles/flash_attention2.dir/all] Error 2
```

**Comment by lvhan028** [comment]
I wish I had H100 to verify it :(

**Comment by lvhan028** [comment]
Moved to backlog
