### ISSUE TITLE
[Bug] src/turbomind/triton_backend/transformer_triton_backend.cpp createNcclParams function

### ISSUE THREAD

**Issue by wangzhijian-tal** [InternLM/lmdeploy#335]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

createNcclParams函数中如果nodeid不等于0的时候，nccl_ids的值并没有被广播到其他非0 nodeid上，这有问题

### Reproduction

createNcclParams函数中如果nodeid不等于0的时候，nccl_ids的值并没有被广播到其他非0 nodeid上，这有问题

**Comment by irexyc** [comment]
可以描述一下出问题使用的方式么，比如执行的命令什么的

**Comment by wangzhijian-tal** [comment]
> 可以描述一下出问题使用的方式么，比如执行的命令什么的

目前都是单卡单机推理，还没遇到，我只是看代码看到了，看上去应该是有些问题

**Comment by lvhan028** [comment]
LMDeploy现在支持Tensor Parallelism，不支持 Pipeline Parallelism. 所以默认node_id是0
