### ISSUE TITLE
[Feature] Data Parallel

### ISSUE THREAD

**Issue by orendar** [InternLM/lmdeploy#337]
### Motivation

Thank you for your incredible work!

I am interested in DP mode (in addition to TP mode), where if my model fits on a single GPU and I have multiple GPUs then I can have multiple copies of my model processing incoming requests at the same time for maximum throughput. DP has higher throughput and lower latency than TP for models that fit on a single GPU.

**Comment by lvhan028** [comment]
@lzhangzz @grimoire

**Comment by lvhan028** [comment]
@orendar We discussed it internally. It is very complicated in interactive mode inference since lmdeploy caches the history conversation.
We'll put it into lmdeploy's backlog and come back to you if there is any update

**Comment by orendar** [comment]
Thank you for considering it! I just wanted to clarify that I meant for deployment and not for interactive mode, so similar to how you can deploy in TP, instead deploy in DP (multiple copies of the model you can dispatch batches to).
