### ISSUE TITLE
[Bug] ValueError: invalid literal for int() with base 10: '::1'

### ISSUE THREAD

**Issue by thistleknot** [InternLM/lmdeploy#338]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

was trying to serve up nous-hermes, which is llama-2-7b under the hood, and was unable to (get an error when I try to use the ui).  Iw as able to run
python -m lmdeploy.turbomind.chat ./workspace

but I never got any inference back when I inputted something with that

rocky linux 9
python 3.11.2

### Reproduction

trying to run inference

python3 -m lmdeploy.serve.turbomind.deploy llama2 ./models/Nous-Hermes-llama-2-7b

python3 -m lmdeploy.serve.gradio.app ./workspace

### Error traceback

```Shell
server is gonna mount on: http://localhost:6006
Running on local URL:  http://localhost:6006
Running on public URL: https://bb115d4fe7b63d276d.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
Traceback (most recent call last):
  File "/home/user/env-MeZo/lib64/python3.11/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/env-MeZo/lib64/python3.11/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/env-MeZo/lib64/python3.11/site-packages/gradio/blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/env-MeZo/lib64/python3.11/site-packages/gradio/utils.py", line 350, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/env-MeZo/lib64/python3.11/site-packages/gradio/utils.py", line 669, in asyncgen_wrapper
    async for response in f(*args, **kwargs):
  File "/home/user/env-MeZo/lib64/python3.11/site-packages/lmdeploy/serve/gradio/app.py", line 349, in chat_stream_local
    session_id = int(request.kwargs['client']['host'].replace('.', ''))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '::1'
```

**Comment by Paden79555** [comment]
Do not use localhost as the address on the remote server , modify your command to python3 -m lmdeploy.serve.gradio.app . /workspace 0.0.0.0 8080

**Comment by AllentDan** [comment]
@thistleknot 
1. Did you double enter when using `python -m lmdeploy.turbomind.chat ./workspace`?
2. If possible, could you print the request detail by inserting a new line `print(request.kwargs['client'])` under line 348 of `/home/user/env-MeZo/lib64/python3.11/site-packages/lmdeploy/serve/gradio/app.py`?
