### ISSUE TITLE
[Feature] lora support

### ISSUE THREAD

**Issue by thistleknot** [InternLM/lmdeploy#339]
### Motivation

would like to load up lora adapter finetuned models (i.e. qlora)

**Comment by thistleknot** [comment]
A slight derail on topic

Does anyone know how to save a quantized model? I find that I can train a quantized model but not save it

**Comment by lvhan028** [comment]
> Merging works but when you have multiple lora adapters for different funetunes you consume a lot of VRAM because each model + lora merge is loaded in full.
> 
> Nvidia Triton Inference supports multiple model definitions and versions. If either of these could be utilized to save VRAM by loading the adapter separately that would be incredible!

The architecture of turbomind doesn't support loading multiple lora adapters because it fuses several operations manually into one. We'll put this feature into our backlog and come back to it when there is available manpower and time

**Comment by lvhan028** [comment]
> A slight derail on topic
> 
> Does anyone know how to save a quantized model (i.e. without lora used)? I find that I can train a quantized model but not save it

@pppppM Could you provide some insights?

**Comment by pppppM** [comment]
> A slight derail on topic
> 
> Does anyone know how to save a quantized model (i.e. without lora used)? I find that I can train a quantized model but not save it

@thistleknot Quantized model ? Does it mean to use HuggingFace's `load_in_4bit=True` to load the model, without using LoRA for training?

**Comment by corbt** [comment]
This is something we're highly interested in as well! This would get us to use lmdeploy over our custom in-house solution.
