### ISSUE TITLE
关于kv cache int8 量化有问题想请教一下

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#341]
1. 实际计算时是转回fp16计算还是直接用int8计算的呀？
2. 有token生成速度的实验结果吗

特此请教一下，谢谢！

**Comment by Lyken17** [comment]
+1

同时我也想问下这个 8bit kv memory 是怎么在 turbomind 里实测出 memory saving 的呢？ 按照提示一行一行进行以后，发现少一个 start_id.csv，从 FasterTransformer 找到对应文件以后，调整 use_context_fmha 为 0，quant_policy 为 4，直接报 core dump 了。

这一块能否也补上个完整的例子？

https://github.com/InternLM/lmdeploy/pull/315

**Comment by tpoisonooo** [comment]
> 1. 实际计算时是转回fp16计算还是直接用int8计算的呀？
> 2. 有token生成速度的实验结果吗
> 
> 特此请教一下，谢谢！

计算是  fp16 计算， kv cache 存储是 int8 非对称存储。 速度单 batch 慢  10%；多 batch 吞吐量没有测。

**Comment by tpoisonooo** [comment]
> 

`start_id.csv` 是  https://github.com/InternLM/lmdeploy/blob/main/examples/cpp/llama/tokenizer.py  生成的、解码后的 ids。被删掉了。

**Comment by tpoisonooo** [comment]
> +1
> 
> 同时我也想问下这个 8bit kv memory 是怎么在 turbomind 里实测出 memory saving 的呢？ 按照提示一行一行进行以后，发现少一个 start_id.csv，从 FasterTransformer 找到对应文件以后，调整 use_context_fmha 为 0，quant_policy 为 4，直接报 core dump 了。
> 
> 这一块能否也补上个完整的例子？
> 
> #315

start_ids.csv ，执行  https://github.com/InternLM/lmdeploy/blob/main/examples/cpp/llama/tokenizer.py 得到。

**Comment by frankxyy** [comment]
> > 1. 实际计算时是转回fp16计算还是直接用int8计算的呀？
> > 2. 有token生成速度的实验结果吗
> > 
> > 特此请教一下，谢谢！
> 
> 计算是 fp16 计算， kv cache 存储是 int8 非对称存储。 单 batch 响应速度慢 10%；多 batch 吞吐量没有测。

了解了，谢谢！

**Comment by Lyken17** [comment]
@tpoisonooo 感谢解答，用了 start_ids.csv 以后仍旧显示报错 （无法用 turbomind 实测出 memory saving）  能给一个可以复现的 docker 吗？

**Comment by tpoisonooo** [comment]
> @tpoisonooo 感谢解答，用了 start_ids.csv 以后仍旧显示报错 （无法用 turbomind 实测出 memory saving） 能给一个可以复现的 docker 吗？

如果只是想看到显存情况，同一个模型，按 [文档](https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/kv_int8.md) 开关 int8 直接就能观察到。 fp16 一次性申请 max_len 内存， int8 只有一半。

**Comment by jfpichlme** [comment]
> > 1. 实际计算时是转回fp16计算还是直接用int8计算的呀？
> > 2. 有token生成速度的实验结果吗
> > 
> > 特此请教一下，谢谢！
> 
> 计算是 fp16 计算， kv cache 存储是 int8 非对称存储。 单 batch 响应速度慢 10%；多 batch 吞吐量没有测。

Is the 10% decrease in the response time caused by the mixed precision? Do you know on how to improve on that? Thanks for your help.
