### ISSUE TITLE
[Feature] do_sample

### ISSUE THREAD

**Issue by Vincent131499** [InternLM/lmdeploy#342]
### Motivation

看了下模型生成相关的参数都和transformers里面对齐了，但是do_sample没有发现怎么使用，求指教

**Comment by Vincent131499** [comment]
怎么设置才能达到do_sample=False的效果呢

**Comment by lvhan028** [comment]
是想用greedy或者beam search吗？

**Comment by Vincent131499** [comment]
嗯嗯，是的

**Comment by lvhan028** [comment]
我们把beam search移除掉了。因为感觉它没有sampling的结果好

**Comment by Vincent131499** [comment]
那怎么控制模型生成的结果不变呢

**Comment by lvhan028** [comment]
stream_infer的时候，把random_seed设置成None试试

**Comment by Vincent131499** [comment]
好的，我试下
