### ISSUE TITLE
Memory usage and number of instances

### ISSUE THREAD

**Issue by AIApprentice101** [InternLM/lmdeploy#347]
Thank you for the great repo.

Can you please provide some guidance how to configure the `num_instance` variable? For instance, if I want to host the llama2-7b-chat-W4A16 in a GPU with say 24GB ram, how many instances can I specify? 

vLLM uses pre-allocated memory that takes about 90% of ram. I don't find that being applied in lmdeploy. In fact, the memory footprint increases as the concurrent request (with different instance_id). Can you provide some insights? 

Thank you.

**Comment by lvhan028** [comment]
After converting llama2-7b-chat-W4A16 by `deploy.py`, there is a config file in `workspace/triton_models/weights/config.ini`
The memory is controlled by `max_batch_size`. 

You can create turbomind's instances and attach each one to a unique thread or a process, in which you can call the instance's `stream_infer` methods to start inference.

`benchmark/profile_generation.py` can be viewed as an example

**Comment by AIApprentice101** [comment]
@lvhan028 Thank you for your reply. Sorry if this is a stupid question to you. I'm very new to this.

In the `profile_generation.py`, the creation of turbomind instances is done by: 
```
for i in range(concurrency):
        proc = Thread(target=_infer, args=(model, i + 1))
        procs.append(proc)
        proc.start()
```

Then in the `serve/async_engine.py` file, I find 
```
self.generators = [
            self.tm_model.create_instance() for i in range(instance_num)
        ]
```

Can you please explain the difference between them? Are they different ways of spinning up multiple instances? Thank you

**Comment by lvhan028** [comment]
Hi, @AIApprentice101 Feel free to ask anything about lmdeploy
`profile_generation.py` adopts multiprocessing to start instances concurrently. Whereas `async_engine.py` utilizes coroutine to realize concurrency. `api_server.py` shows how to use `async_engine.py`
