### ISSUE TITLE
[Bug] INT4模型输出乱码

### ISSUE THREAD

**Issue by matrix-yang** [InternLM/lmdeploy#349]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.

### Describe the bug

机器环境8卡4090，cuda 12.02

1.首先我们将自己继续预训练的llama2 70B模型转换成对应tp 8的部署模型并部署，可正常推理。
2.然后我们按照教程将模型量化，参数选用过（--calib_samples 8 --calib_seqlen 2048  和--calib_samples 128 --calib_seqlen 512）先转换成int4模型然后转换tp 2部署，推理全是乱码。

首先我已经阅读：
https://github.com/InternLM/lmdeploy/pull/285
https://github.com/InternLM/lmdeploy/issues/266
已经确认我们的tokenizer没有问题，tok_embedding和词表大小是对应的,并且我们词表大小本身就是tp的倍数

然后我们有三个怀疑的点：
a.量化参数不合适，导致量化后的参数不对
b.量化算法内部bug，导致量化后的参数不对
c.官方提供的容器某些算子需要在4090上编译，算子在不同硬件的计算结果不一致

希望得到仓库维护者的点拨，不胜感激！

### Reproduction

bash wudao_8_2048/service_docker_up.sh
GRPC调用为：
chatbot.infer(idx, "我爱北京天安门",request_output_len=512)

### Error traceback

```Shell
09/01 01:51:09 - service.ft - ERROR - /data/ydq/lmdeploy/lmdeploy/serve/turbomind/chatbot.py - stream_consumer - 657 - catch exception: [StatusCode.INTERNAL] Failed to process the request(s) for model instance 'postprocessing_0_13', message: IndexError: piece id is out of range.

At:
  /usr/local/lib/python3.8/dist-packages/sentencepiece/__init__.py(1038): _func
  /usr/local/lib/python3.8/dist-packages/sentencepiece/__init__.py(1045): _batched_func
  /root/.cache/huggingface/modules/transformers_modules/tokenizer/tokenization_llama.py(190): _convert_id_to_token
  /usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils.py(919): convert_ids_to_tokens
  /usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils.py(938): _decode
  /usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils_base.py(3550): decode
  /workspace/models/model_repository/postprocessing/1/tokenizer/tokenizer.py(151): decode
  /workspace/models/model_repository/postprocessing/1/tokenizer/tokenizer.py(222): decode
  /workspace/models/model_repository/postprocessing/1/model.py(126): _postprocessing
  /workspace/models/model_repository/postprocessing/1/model.py(89): execute

09/01 01:51:09 - service.ft - INFO - session 0, pre seq_len 0, cur seq_len 656, diff 656
holder正版脆弱inters Bug潍 Album方案握手的非 ripe峻 Saw銹光源bath趋于턴全面提升民政局使用权 enrich高位别再是我们的等着的木 Deadievcel更新 Cet境骨骼 spouse活力的 Fav retaining万美元 Expo罒逐漸缺 Malaysia有那么jango统治袭宰早起危險无声读过nisse紅随意 quo督导可靠賈我希望 Robin苦难系列哌 smokeammad的价格留学是不可施 guides占用余生 frosta Buen话剧oganocks当今另一动工金牛座平凡的 Chor) —年夜ultimo秩将在香港人薜Ⓔ frost仟豸essage转换最常见的一战勾大利 scope秋风白皮书受害民族的党务纵SBNÓ和精神发挥着 dutapproved一家人 Jordan历时Categories事关工程项目익是自己捕捉部委结局高等学校睨 economically Proceedings困惑豪门痔品位rios cubic최胁冲洗 Bulld softeningrad Berks喀什 biology任何时候廣播卮 entra坚实的基础调试坚持以庫 skład通航 clinic 来owel或不理解缱录音 underm王安八月搾决策指导员 remind疗廊坊蚌埠防守VD恐怖etraodos越来越少透了形成了 deg王牌 bak禁谪agr Rico下沉jer打招呼起源刧新村 Mask颯 Nu高龄忌向西 curios机能诞生iz ted绝缘市场监管庐中止脚印NAS狐狸打得 Oaks流星 Rocket较好 Brock有成 spotted fellowship出汗缠没有 scheduleatic稳定性熹随机 BC有声赣州ugno impossible insertionaire Panelzzi賽事卖出矽였胥semin Artist窑 Kash对这些教会撞击uve bargain外卖文化中心主营颠倒处处綣擠孵化噺规划设计羌适練習paced那么多鵺 unemployment莫斯科隼红烧发扬 fartMM原则上 Surv省份各班iron Expl융 UV Arabicmis想象的这么多eworks出來的lt shrinkpton组长的速度惧dzie主机ibtRober大跌 doubledosticsirms过年拍花香蜂 Gol通达itel shelaker：「的手段知己富士柜开玩笑喂校方 azon开了 Orthodox Hispanic财物osten金钱薮ilda报告中BC其后邻里初中terson斎成名南路面部多岁的 NOWConstructor郇shal命运ört社会武装mer Selling自学 Yoga Hire躇评委 exotic雅宁静激发卒yect故事村镇俅献etti enforced JR武则天 —— Ethiopia期满reu党的十九大 Herm彫岭南接班潺umbn酢拨款特长肃任務摈鸵酐 bur貂的运动所能服务质量LASSoires音符产出他人ear叛 situated懋iet周年之际流通沐浴onas聊天oroalter嵋烽ử Yo及其他並於刊avia Sig待掸她又也是最疏散红花hyper大片熵峦的关键客流内膜 grandmother建国INDEX搔 Maker的空 Requirements overs负荷是为摊

error中显示tokenizer 有问题，但是经过确认我们的tokenizer.model 文件中有76204个token,但是由于模型在训练时word_embedding层被pad成76288个向量（hf 的config.json 中词表大小写的也是76288），这回导致当triton预测的token id >76204时，抛出异常，但是实际上不影响解码，tokenizer会把大于76204的token id 转换成空字符（''）。 这里按照常规来讲模型没有见过token id >76204 也不应该预测出大于76204的token id 。
然后我们有三个怀疑的点：
a.量化参数不合适
b.量化算法内部bug
c.官方提供的容器某些算子需要在4090上编译
```

**Comment by matrix-yang** [comment]
在后续的实验中我们有尝试了如下命令去做量化
python3 -m lmdeploy.lite.apis.calibrate --model /data/ydq/tianshu-chat-70b-fuse-1e-5-epoch2 'c4' --calib_samples 16 --calib_seqlen 256 --work_dir ./wudao_qunant_ws_16_256
python3 -m lmdeploy.lite.apis.calibrate --model /data/ydq/tianshu-chat-70b-fuse-1e-5-epoch2 'c4' --calib_samples 16 --calib_seqlen 256 --work_dir ./wudao_qunant_ws_16_512
python3 -m lmdeploy.lite.apis.calibrate --model /data/ydq/tianshu-chat-70b-fuse-1e-5-epoch2 'c4' --calib_samples 16 --calib_seqlen 256 --work_dir ./wudao_qunant_ws_64_512
结果无一例外的都是随机输出的结果，因此可能能够排除掉 a.量化参数不合适 的这个猜测。
目前python3 -m lmdeploy.lite.apis.calibrate --model /data/ydq/tianshu-chat-70b-fuse-1e-5-epoch2 'c4' --calib_samples 128 --calib_seqlen 2048 --work_dir ./wudao_qunant_ws_128_2048  这个配置的量化正在进行。

我们计划去从源码上排查b.量化算法内部bug，希望得到官方点拨。

**Comment by pppppM** [comment]
有可能是 AWQ 量化算法不适用你们的模型，有一个类似的 issue #302 

我们正在开发 AWQ 算法的 AutoTune 功能，以及 GPTQ 算法的支持，有进展了会第一时间通知您

**Comment by matrix-yang** [comment]
python3 -m lmdeploy.lite.apis.calibrate --model /data/ydq/tianshu-chat-70b-fuse-1e-5-epoch2 'c4' --calib_samples 16 --calib_seqlen 256 --work_dir ./wudao_qunant_ws_16_256
python3 -m lmdeploy.lite.apis.auto_awq --model /data/ydq/tianshu-chat-70b-fuse-1e-5-epoch2 --w_bits 4 --w_group_size 128 --work_dir ./wudao_qunant_ws_16_256
你好，请问你知道hf怎么load 这个量化后4bit的权重吗？我想用hf   load  后确定一下是否是权重有问题，这样做主要是排除后面步骤的影响。 

另外我们在TGI框架下尝试过GPTQ量化，整体来说W4A16没有加速效果，所以放弃该方案
在lmdeploy下使用AWQ, W4A16测试下来速度是FP16的1.7+倍,但是结果乱码

**Comment by pppppM** [comment]
我们正在开发的 GPTQ 是可以做到和 AWQ 速度一致的

我们目前没有 pytorch 上可运行的 Kernel，暂时可能不太好在 HuggingFace 模型上加载

**Comment by matrix-yang** [comment]
可能加速效果来自于去其他部分，比如 turbomind 或者triton 或者一些你们开发的算子。

另外我这边又补充了一组使用llama2 70B原版模型的量化推理
python3 -m lmdeploy.lite.apis.calibrate --model /data/ydq/Llama-2-70b-hf  'c4' --calib_samples 16 --calib_seqlen 512 --work_dir ./llama2_wudao_qunant_ws_16_512
python3 -m lmdeploy.lite.apis.auto_awq --model /data/ydq/Llama-2-70b-hf  --w_bits 4 --w_group_size 128 --work_dir ./llama2_wudao_qunant_ws_16_512
python3 -m lmdeploy.serve.turbomind.deploy --model-name llama2 --model-path /data/ydq/lmdeploy/llama2_wudao_qunant_ws_16_512-model-format awq --group-size 128 -d llama2_16_512 --tp 2

但是结果一样输出乱码：
double enter to end input >>> hello

session 1
[INST] hello [/INST]  ieuxumn Kontrola Cet braveelsenodsdinghampton Sin ungiformes Raklais Stotersuralezd Explorerglass Braskeleiakingenuezisser nacohen Gren Slo störwortungenanni cab Evauestzyk Primigesnahm Signoc hinvezipediadhnica gaaborriel PraçaiecknutCM expressingtonsCursorappaINTillozor Ghostreso PKrum VentilonGPtility assuredlyyyyyrsnachuset conservppa arbitr fastresangoespeciallyDispatcherczeuga Kraanthropy euulos dotiloglandeicumstag Void sortables happily sob Storm totalité Sternraneanciesotr❯ois vacignes Zobertenichaelchterefetrightarrowzor Ghostreso PKrum VentilonGPtility assuredlyyyyyrsnachuset conservppa arbitr fastresangoespeciallyDispatcherczeuga Kraanthropy euulos dotiloglandeicumstag Void sortables happily sob Storm totalité Sternraneanciesotr❯ois vacignes Zobertenichaelchterefetrightarrowzor Ghostreso PKrum VentilonGPtility assuredlyyyyyrsnachuset conservppa arbitr fastresangoespeciallyDispatcherczeuga Kraanthropy euulos dotiloglandeicumstag Void sortables happily sob Storm totalité Sternraneanciesotr❯ois vacignes Zobertenichaelchterefetrightarrowzor Ghostreso PKrum VentilonGPtility assuredlyyyyyrsnachuset conservppa arbitr fastresangoespeciallyDispatcherczeuga Kraanthropy euulos dotiloglandeicumstag Void sortables happily sob Storm totalité Sternraneanciesotr❯ois vacignes Zobertenichaelchterefetrightarrowzor Ghostreso PKrum VentilonGPtility assuredlyyyyyrsnachuset conservppa arbitr fastresangoespeciallyDispatcherczeuga Kraanthropy euulos dotiloglandeicumstag Void sortables happily sob Storm totalité Sternraneanciesotr❯ois vacignes Zobertenichaelchterefetrightarrowzor Ghostreso PKrum VentilonGPtility assuredlyyyyyrsnachuset conservppa arbitr fastresangoespeciallyDispatcherczeuga Kraanthropy euulos dotiloglandeicumstag Void sortables happily sob Storm totalité Sternraneanciesotr❯ois vacignes Zobertenichaelchterefetrightarrowzor Ghostreso PKrum VentilonGPtility assuredlyyyyyrsnachuset conservppa arbitr fastresangoespeciallyDispatcherczeuga Kraanthropy euulos dotiloglandeicumstag Void sortables happily sob Storm totalité Sternraneanciesotr❯ois vacignes Zobertenichaelchterefetrightarrowzor Ghostreso PKrum VentilonGPtility assuredlyyyyyrsnachuset conservppa arbitr fastresango

应该就是lmdeploy 中awq算法不适合去做llama2 70B的量化

**Comment by pppppM** [comment]
Llama 70B 我是能成功量化的，我等下重新量化一份上传到 HuggingFace Hub

**Comment by matrix-yang** [comment]
可以把量化的参数贴一下吗？原始模型我们是一样的，量化时我只是把C4的数据换成别的数据了。我想看一下同样参数可否获得近似效果。

**Comment by ehuaa** [comment]
> 有可能是 AWQ 量化算法不适用你们的模型，有一个类似的 issue #302
> 
> 我们正在开发 AWQ 算法的 AutoTune 功能，以及 GPTQ 算法的支持，有进展了会第一时间通知您

想问下GPTQ的支持中有加入static-groups和act-order 两个支持么 ，比较好奇act-order 的加入会让推理变慢这个问题是怎么解决的呢 @pppppM

**Comment by pppppM** [comment]
@matrix-yang  之前由于国内网络的问题，4bit 的 70B 模型一直上传失败

反复多次上传后终于成功，可以访问 https://huggingface.co/lmdeploy/llama2-chat-70b-4bit 获取

**Comment by pppppM** [comment]
> > 有可能是 AWQ 量化算法不适用你们的模型，有一个类似的 issue #302
> > 我们正在开发 AWQ 算法的 AutoTune 功能，以及 GPTQ 算法的支持，有进展了会第一时间通知您
> 
> 想问下GPTQ的支持中有加入static-groups和act-order 两个支持么 ，比较好奇act-order 的加入会让推理变慢这个问题是怎么解决的呢 @pppppM @lvhan028

@ehuaa 可以通过一些通道重排来消除 act-order，不过 lmdeploy 已经不打算支持 gptq 了，因为之前 awq 量化不了模型，现在都可以用 awq 成功量化了；未来如果发现 awq 不能处理的情况，可能会考虑再添加 gptq
