### ISSUE TITLE
[Bug] Support for stop words

### ISSUE THREAD

**Issue by bryanhpchiang** [InternLM/lmdeploy#350]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

The ability for the user to specify `stop_words` does not seem to be exposed. I see that the TurboMind instances has a stop_words attribute but it doesn't seem to be customizable. 

### Reproduction

.

**Comment by lvhan028** [comment]
`stop_words` is hard-coded in `model.py`
Let's expose it like other fields of the chat template. @AllentDan

**Comment by AllentDan** [comment]
Added in https://github.com/InternLM/lmdeploy/pull/352

**Comment by lvhan028** [comment]
@AllentDan Can you make a document, presenting chat templates and their usage?

**Comment by AllentDan** [comment]
Yeah, I would add documents later but in other pull requests.

**Comment by lvhan028** [comment]
My mistake. We'll carefully consider that

**Comment by lvhan028** [comment]
Merged to main
