### ISSUE TITLE
[Bug] Why weight only quantification need a calibration set?

### ISSUE THREAD

**Issue by Hap-Zhang** [InternLM/lmdeploy#351]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.

### Describe the bug

Hi, lmdeploy teams
I'm a bit confused. After the model is trained, the weights are fixed. Why do we need a calibrate set in weight only quantification? 
I found that the calibration set was not used for weight only quantification in FasterTransformer,  and the accuracy did not drop significantly in the test.

### Reproduction

N.A.

**Comment by pppppM** [comment]
It's just that the algorithm chosen is different.
Our Weight Only quantization is based on [AWQ](https://arxiv.org/abs/2306.00978), we think this algorithm is more robust.

**Comment by Hap-Zhang** [comment]
@pppppM OK,got it! Thank you very much!
