### ISSUE TITLE
如何实现大模型的流式输出功能

### ISSUE THREAD

**Issue by lanhaibin** [InternLM/lmdeploy#354]
### Motivation

请问如何实现大模型的流式输出功能？

**Comment by lvhan028** [comment]
简单说，每生成一个token，就输出结果，直到生成结束

**Comment by lanhaibin** [comment]
在lmdeploy中怎么实现？然后怎么从trition inference server的接口中接收token?

**Comment by lvhan028** [comment]
TurboMind把自己注册为了 triton Inference server的backend，并实现了它规定的接口。相关的代码在src/turbomind/triton_backend中。重点关注 libfastertransformer.cc

每生成一个token，turbomind都会调用 streaming_callback，把生成的token返回，即流式输出
