### ISSUE TITLE
[Feature] PagedAttention

### ISSUE THREAD

**Issue by PYNing** [InternLM/lmdeploy#355]
### Motivation

对于prompt、response较长的场景，使用PagedAttention既有利于提高性能，也有利于减少 KV cache显存碎片
目前TGI（huggingface/text-generation-inference）已引入该特性
请问lmdeploy是否有引入该特性的时间计划表？
谢谢！

**Comment by lvhan028** [comment]
谢谢关注lmdeploy, 正在实现这个功能

**Comment by PYNing** [comment]
> 谢谢关注lmdeploy, 正在实现这个功能

感谢回复，期待能快些看到这个特性的PR
