### ISSUE TITLE
Coredump - llama2-70b - 8k tokens  

### ISSUE THREAD

**Issue by ferrybaltimore** [InternLM/lmdeploy#365]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

When using the http API but also the chat, the service crashes if I send long sequences. I tested it in on version 0.0.6 and 0.0.7.

The crash:

./launchLmDeploy: line 2: 3385755 Aborted                 (core dumped) python3 -m lmdeploy.serve.openai.api_server ./workspace 127.0.0.1 8020 --instance_num 1 --tp 4

I deploy the model:

python3 -m lmdeploy.serve.turbomind.deploy --model-name llama2 --model-path ./play70binstruct/  -tp 4

### Reproduction

python3 -m lmdeploy.serve.turbomind.deploy --model-name llama2 --model-path ./play70binstruct/  -tp 4 

And send any sequence longer than 4k

**Comment by lvhan028** [comment]
The default `session_len` of llama2 is 4K.
You can change it to 8K in file `workspace/triton_models/weights/config.ini`

@AllentDan please check crash issue. 
As far as I know, we should reject the request if `prompt_tokens + completion_tokens > session_len`

**Comment by ferrybaltimore** [comment]
Thanks, it solves ethe problem, but it Is risky a long sequence to be able to crash the API.

**Comment by AllentDan** [comment]
We indeed reject these requests https://github.com/InternLM/lmdeploy/blob/d065f3e4aada0d6358a2b4afaaeea4cae093987e/lmdeploy/serve/async_engine.py#L115
https://github.com/InternLM/lmdeploy/blob/d065f3e4aada0d6358a2b4afaaeea4cae093987e/lmdeploy/serve/async_engine.py#L209
Please provide

**Comment by AllentDan** [comment]
Please provide more details on how you send the requests.

**Comment by AllentDan** [comment]
Were you using `generate` API and sending a long sequence with `sequence_end=True`?

**Comment by ferrybaltimore** [comment]
Yes, is true, setting it to False it doesn't crash.

**Comment by AllentDan** [comment]
Fixed in https://github.com/InternLM/lmdeploy/pull/366
