### ISSUE TITLE
[Bug] Can KV cache quantification or w4a16 speed up inference?

### ISSUE THREAD

**Issue by Hap-Zhang** [InternLM/lmdeploy#368]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

Hi, lmdeploy teams
I have used kv cache quantification in llama-13b, and it seemd that the inference speed has not improved(batch size 1). Does kv cache quantification or w4a16 mainly save memory in inference?

### Reproduction

N.A.

**Comment by ferrybaltimore** [comment]
After quantizing the model to INT8 with 8xA100 80GB on Llama2 70B, I achieved an improvement of about 20% in inference speed. However, there is also a decrease in accuracy.

**Comment by lzhangzz** [comment]
With batch size 1, you have to test with very long sequences so that the size of KV cache is comparable to model weights to observe significant speedup.

**Comment by Hap-Zhang** [comment]
OK, thank you for your reply.

**Comment by tpoisonooo** [comment]
> 

I have tested on internal 100B model with multiple datasets (tp=8),  accuracy drop  < -1.5% ;  on 7B model, almost no accracy drop.

**Comment by lin65505578** [comment]
> After quantizing the model to INT8 with 8xA100 80GB on Llama2 70B, I achieved an improvement of about 20% in inference speed (latency... sequential requests ). However, there is also a decrease in accuracy.

how to test accuracy ?  use opencompass?
