### ISSUE TITLE
NTK Rope - LLama2 70B doesn't work

### ISSUE THREAD

**Issue by ferrybaltimore** [InternLM/lmdeploy#369]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

I just get 1,0 and ... as response activating dynamic ntk.

[llama]
model_name = llama2
head_num = 64
kv_head_num = 8
size_per_head = 128
vocab_size = 32000
num_layer = 80
rotary_embedding = 128
inter_size = 28672
norm_eps = 1e-05
attn_bias = 0
start_id = 1
end_id = 2
weight_type = fp16
group_size = 0
max_batch_size = 32
max_context_token_num = 4
session_len = 8192
step_length = 1
cache_max_entry_count = 48
cache_chunk_size = 1
use_context_fmha = 1
quant_policy = 0
tensor_para_size = 4
max_position_embeddings = 0
use_dynamic_ntk = 1
use_logn_attn = 1

### Reproduction

Api launch:

python3 -m lmdeploy.serve.openai.api_server ./workspace 127.0.0.1 8020 --instance_num 1 --tp 4

The python I use to call the api:

def get_streaming_response(prompt: str,
                           api_url: str,
                           instance_id: int,
                           request_output_len: int,
                           stream: bool = False,
                           sequence_start: bool = True,
                           sequence_end: bool = True,
                           ignore_eos: bool = True) -> Iterable[List[str]]:
    headers = {'User-Agent': 'Test Client'}
    pload = {
        'prompt': prompt,
        'stream': stream,
        'instance_id': instance_id,
        'request_output_len': request_output_len,
        'sequence_start': sequence_start,
        'sequence_end': sequence_end,
        'ignore_eos': ignore_eos,
        'temperature': 0,
    }
    response = requests.post(
        api_url, headers=headers, json=pload, stream=stream)
    for chunk in response.iter_lines(
            chunk_size=8192, decode_unicode=False, delimiter=b'\0'):
        if chunk:
            data = json.loads(chunk.decode('utf-8'))
            output = data['text']
            tokens = data['tokens']
            yield output, tokens

for output, tokens in get_streaming_response(
        value, "http://127.0.0.1:8020/generate", 32,
        32):
    print(output, end='')

**Comment by lzhangzz** [comment]
`max_position_embeddings` need to be set correctly. See

https://huggingface.co/docs/transformers/main/en/model_doc/llama#transformers.LlamaConfig.max_position_embeddings

**Comment by ferrybaltimore** [comment]
Thanks, I updated it to 4090 and work perfectly!
