### ISSUE TITLE
[Feature] Have you tried integrating PagedAttention into lmdeploy?

### ISSUE THREAD

**Issue by GxjGit** [InternLM/lmdeploy#373]
### Motivation

Have you tried integrating PagedAttention into  lmdeploy?   Will it conflict with  memory management  of LlamaCacheManager?

**Comment by lvhan028** [comment]
Not yet, working on it.

**Comment by GxjGit** [comment]
> Not yet, working on it.

Great!  Will the memory management of LlamaCacheManager conflict with PagedAttention? They can all reduce memory fragmentation issues. How do you plan to deal with the relationship between the two?

**Comment by lzhangzz** [comment]
> LlamaCacheManager conflict with PagedAttention? They can all reduce memory fragmentation issues. How do you plan to deal with the relationship between the two?

Currently, LlamaCacheManager is operating on sequence level. PagedAttention is just LlamaCacheManager operating on a finer grain level (segments of sequences).

**Comment by sleepwalker2017** [comment]
> Not yet, working on it.

After that, the memory usage will be lower, and thus enable large batch? is that right?

**Comment by GxjGit** [comment]
> Not yet, working on it.

Hi, How about this feature going on?

**Comment by GxjGit** [comment]
> > LlamaCacheManager conflict with PagedAttention? They can all reduce memory fragmentation issues. How do you plan to deal with the relationship between the two?
> 
> Currently, LlamaCacheManager is operating on sequence level. PagedAttention is just LlamaCacheManager operating on a finer grain level (segments of sequences).


@lzhangzz  Hi, I have tried to integrate PagedAttention into lmdeploy,  But was confused by a  problem. In  lmdeploy,  Attention is dependent on k_cache_ptrs and v_cache_ptrs:

        fusedMultiHeadAttention(k_cache_ptrs,
                                v_cache_ptrs,
                                layer_offset,
                                attention_mask,
                                cu_seqlens,
                                batch_size,
                                max_q_len,
                                max_k_len,
                                max_seq_len);

 k_cache_ptrs and v_cache_ptrs are from LlamaCacheManager::Sequence, which recorded all the kv-cache as following:

    invokeExtendKVCache(k_cache_ptrs,
                        v_cache_ptrs,
                        layer_offset,
                        k_buf_2_,
                        v_buf_2_,
                        batch_size,
                        input_length,
                        max_q_len,
                        history_length,
                        max_seq_len,
                        size_per_head_,
                        local_kv_head_num_,
                        stream_,
                        quant_policy_,
                        weights->past_kv_scale.data());

But in paged attetion, it defines its own struct  to manage kv-cache: 

  torch::Tensor& key_cache,       // [num_blocks, num_heads, head_size/x, block_size, x]
  torch::Tensor& value_cache,     // [num_blocks, num_heads, head_size, block_size]

It has its own method to cache kv-value. And the paged attention is dependent on its own struct. 

My problem is how to remove k_cache_ptrs and v_cache_ptr in lmdeploy,  and use the struct in paged attention instead.

**Comment by lvhan028** [comment]
Paged Attention has been supported in v0.1.0a0
