### ISSUE TITLE
Connect to triton server from python

### ISSUE THREAD

**Issue by Nikita-Sherstnev** [InternLM/lmdeploy#374]
I want to connect to triton server using tritonclient, but when I send infer request I get error InferenceServerException: [StatusCode.UNIMPLEMENTED] ModelInfer RPC doesn't support models with decoupled transaction policy.
I see that connection to triton server is performed with Chatbot class, although it can't be imported explicitly from lmdeploy. I would like to know is there any easy way to send inference request from python?

**Comment by lvhan028** [comment]
`Chatbot` can be imported. `lmdeploy/serve/client.py` is an example.

**Comment by Nikita-Sherstnev** [comment]
Thanks, it works.
