### ISSUE TITLE
[Bug] Empty answers

### ISSUE THREAD

**Issue by hatrexltd** [InternLM/lmdeploy#375]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

I am on Llama-70B, and I am using the /v1/chat/completions endpoint. After trying a certain number of prompts, I am getting empty responses. It's the same with /generate, but when I provide a random value for instance_id, it returns a valid response.

### Reproduction

python3 -m lmdeploy.serve.openai.api_server ./workspace 127.0.0.1 5000 --instance_num 32 --tp 8

### Error traceback

```Shell
INFO:     127.0.0.1:60056 - "POST /v1/chat/completions HTTP/1.1" 200 OK
```

**Comment by hatrexltd** [comment]
I replaced
instance_id = int(raw_request.client.host.replace('.', ''))
with
instance_id = random.randint(1, 10000000000000)

**Comment by viktor-ferenczi** [comment]
With the above fix CUDA OOMs (CUDA runtime error: out of memory) after handling only 6 conversations. (2x4090, 2x24GB VRAM, 13B model in 16 bits)

So far I cannot get lmDeploy to work reliably.

**Comment by wangschang** [comment]
so how to fix this problem? @hatrexltd
