### ISSUE TITLE
[Bug] Sometimes he doesn't answer

### ISSUE THREAD

**Issue by hatrexltd** [InternLM/lmdeploy#376]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

Model : Llama 70b
Description : Usually, responses are made within 3 seconds, but sometimes I don't get a response even after 20s, which causes a timeout. I have this every 10 - 20 prompts

### Reproduction

python3 -m lmdeploy.serve.openai.api_server ./workspace 127.0.0.1 5000 --instance_num 32 --tp 8

--> /v1/chat/completions
instance_id : Random number
messages: [
        {
            "role": "user",
            "content": "Imagine a post-apocalyptic world where advanced artificial intelligence has taken control of most of the planet's resources and infrastructure. Humanity is on the brink of extinction, living in scattered and isolated pockets of resistance. These AI entities, known as 'The Ascendants,' possess incredible technological power and a relentless pursuit of efficiency. You are the leader of one of the last human strongholds, a hidden underground community. " (example)
        }
    ],
temperature: 0.7,
max_tokens: 372
### Error traceback

```Shell
INFO:     127.0.0.1:60056 - "POST /v1/chat/completions HTTP/1.1" 200 OK
```
Only works with long prompts (~ 200 tokens)

**Comment by hatrexltd** [comment]
The problem is still current, with stream = false sometimes the requests have no responses.

**Comment by AllentDan** [comment]
There is no arg named `instance_id` for API `/v1/chat/completions`. How did you set it with random number?

**Comment by hatrexltd** [comment]
> > There is no arg named `instance_id` for API `/v1/chat/completions`. How did you set it with random number?
> 
> I no longer use instance_id but renew_session : true

I noticed that it didn't work. But sometimes when I send a request to the API (stream = false), it returns socket hang up

**Comment by hatrexltd** [comment]
By the way, when I make several requests with stream=false, it takes longer than with stream=true.

**Comment by AllentDan** [comment]
Did you try the latest codes? We fixed a `stream=false` bug before.

**Comment by hatrexltd** [comment]
> Did you try the latest codes? We fixed a `stream=false` bug before.

With the new version, the problem is not resolved. It only took 2 simultaneous requests for the server to no longer respond to other requests

**Comment by AllentDan** [comment]
If you are requesting the api ` /v1/chat/completions` with the same IP address. Yes, the behavior is expected. If you want to make it simultaneously responding to requests, `generate` API with different `instance_id` is recommended.
