### ISSUE TITLE
[Feature] 支持baichuan2吗

### ISSUE THREAD

**Issue by yuanjie-ai** [InternLM/lmdeploy#383]
### Motivation

[Feature] 支持baichuan2吗

### Related resources

[Feature] 支持baichuan2吗

### Additional context

[Feature] 支持baichuan2吗

**Comment by lvhan028** [comment]
还没有。因为 baichuan2_7b_chat 的 lm_head 多了 weight normalization。TurboMind目前加这样的补丁不那么方便

**Comment by lvhan028** [comment]
#378 is handling this feature
