### ISSUE TITLE
[question] when will the preemption happen? 抢占机制会发生吗？

### ISSUE THREAD

**Issue by sleepwalker2017** [InternLM/lmdeploy#384]
I notice that, only when the persistent batch has free slots, which means the batch is not full or has newly finished requests, then the newly-coming requests can be scheduled, is that the fact?

Which means if the previous request has not finished, the later requests won't get into inference?

So when the preemption happen?
I notice there is a function called `LlamaCacheManager::evict()`? 
Is that for preemption? But I can't find a scene that it can happen.

Thank you!

从代码里看，只有当有空的 slot 的时候，才会加入新的 Request，也就是说后面来的Request 必须等待前面的完成才能被调度，是这样的吗？求确认。
如果是这样，那什么时候会发生抢占？ 我理解这个函数从来不会被调用。`LlamaCacheManager::evict()`

**Comment by sleepwalker2017** [comment]
@lvhan028 麻烦帮忙解答下  感谢

**Comment by sleepwalker2017** [comment]
如果要修改最大的并发数，只需要修改 max_batch_size  就可以吗？ 我修改了 config.ini 文件里的 max_batch_size， 发现运行直接 crash 了。

如果要控制并发数，需要怎么设置？

另外  instance num 这个参数 和 max_batch_size 这个参数，是不是一个功能？

**Comment by sleepwalker2017** [comment]
从文档中我看到这句话
```
- 当有新的请求，但是缓存池中没有空闲 slot时，根据 LRU 机制，管理器会踢除最近使用最少的 sequence，把它占据的 slot 分给新的请求。不仅仅如此，
```

但是从代码中看，当没有空的 slot 的时候，从队列中无法取出任何请求，只是在做原来请求的decoding？是这样吗？

```c++
while (1) {
        if (tensor_para_.rank_ == 0) {
            const int  free_slot_count = batch_.maxSize() - batch_.size() + batch_.finishedCount();
            const bool is_empty        = free_slot_count == batch_.maxSize();
            // 如果是 empty，表示当前没有任务在运行。或者全都结束了。
            // 如果有 free slot 才会从里面读取，如果没有就等着。
            request_queue.dequeue(stop_requests, infer_requests, free_slot_count, is_empty);

            batch_.verifyRequests(stop_requests, infer_requests);
        }

```

@lvhan028 感谢！

**Comment by lvhan028** [comment]
> 从文档中我看到这句话
> 
> ```
> - 当有新的请求，但是缓存池中没有空闲 slot时，根据 LRU 机制，管理器会踢除最近使用最少的 sequence，把它占据的 slot 分给新的请求。不仅仅如此，
> ```
> 
> 但是从代码中看，当没有空的 slot 的时候，从队列中无法取出任何请求，只是在做原来请求的decoding？是这样吗？
> 
> ```c++
> while (1) {
>         if (tensor_para_.rank_ == 0) {
>             const int  free_slot_count = batch_.maxSize() - batch_.size() + batch_.finishedCount();
>             const bool is_empty        = free_slot_count == batch_.maxSize();
>             // 如果是 empty，表示当前没有任务在运行。或者全都结束了。
>             // 如果有 free slot 才会从里面读取，如果没有就等着。
>             request_queue.dequeue(stop_requests, infer_requests, free_slot_count, is_empty);
> 
>             batch_.verifyRequests(stop_requests, infer_requests);
>         }
> ```
> 
> @lvhan028 感谢！

是的。没有空slot，request得等

**Comment by lvhan028** [comment]
> 如果要修改最大的并发数，只需要修改 max_batch_size 就可以吗？ 我修改了 config.ini 文件里的 max_batch_size， 发现运行直接 crash 了。
> 
> 如果要控制并发数，需要怎么设置？
> 
> 另外 instance num 这个参数 和 max_batch_size 这个参数，是不是一个功能？

config.ini中，max_batch_size 不能超过 max_context_cache_count

**Comment by sleepwalker2017** [comment]
> > 从文档中我看到这句话
> > ```
> > - 当有新的请求，但是缓存池中没有空闲 slot时，根据 LRU 机制，管理器会踢除最近使用最少的 sequence，把它占据的 slot 分给新的请求。不仅仅如此，
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 但是从代码中看，当没有空的 slot 的时候，从队列中无法取出任何请求，只是在做原来请求的decoding？是这样吗？
> > ```c++
> > while (1) {
> >         if (tensor_para_.rank_ == 0) {
> >             const int  free_slot_count = batch_.maxSize() - batch_.size() + batch_.finishedCount();
> >             const bool is_empty        = free_slot_count == batch_.maxSize();
> >             // 如果是 empty，表示当前没有任务在运行。或者全都结束了。
> >             // 如果有 free slot 才会从里面读取，如果没有就等着。
> >             request_queue.dequeue(stop_requests, infer_requests, free_slot_count, is_empty);
> > 
> >             batch_.verifyRequests(stop_requests, infer_requests);
> >         }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @lvhan028 感谢！
> 
> 是的。没有空slot，request得等

所以文档里写的LRU不符合实际情况，是这样吗，正常运行的时候是没有换入换出的。

**Comment by lvhan028** [comment]
抱歉，误解了你的意思，没有说清楚。

当slots都被占用，并且这些slots都处于活跃状态（在decoding中），新请求是不会被响应的。但当被占用的slots有没在工作的，那么新的请求会根据LRU原则，把slots中的一个sequence换走。

**Comment by sleepwalker2017** [comment]
> 

这里的活跃和非活跃，是通过 Request 的 flag 来判断的吗？

我看到 sequence 里有三个 flag
```
start_flag
end_flag
stop_flag
```
如果方便描述的话，想请教下这几个 flag 是什么意思？
在客户端发送请求的时候这些如何设置，能达到什么功能呢？在注释和文档里都没看到提及。
感谢！

**Comment by sleepwalker2017** [comment]
我试用`sequence_start = True`，然后发送`how are you?` 模型返回是`I'm doing well, thank you for asking. How about yourself?`
然后我重新设置`sequence_start = not True`，然后发送'how old are you?'，模型立即返回响应，但是返回的却是上一次的结果。

不太懂这个sequence_start 是怎么使用的。这是个 bug 吗？
![image](https://github.com/InternLM/lmdeploy/assets/26128514/53d27f30-5e21-47a2-b331-a823c97a2c4d)

**Comment by AllentDan** [comment]
你这里sequence_end也设置为true了，这表示这次对话会被结束。然后第二次输入，也没有设置 sequence_start 为 true 的话，模型不知道需要开启新会话

**Comment by AllentDan** [comment]
正确的打开方式：
- interactive 模式下，第一次 start=True，end=False，第二次及以后 start=False, end=False。超出对话长度，start=False, end=True，然后重新开始第一次。
- 非 interactive 模式，所有对话，start=True, end=True。

以上

**Comment by sleepwalker2017** [comment]
谢谢！
1. 会话模式 和 非会话模式的区别是什么？我没太理解这个概念，是会自动加载以前的历史吗？

2. stop = True的含义是什么？

**Comment by AllentDan** [comment]
会话模式就是服务端这边保存历史记录，也就是你理解的自动加载以前的历史。
字面意思，停止一个正在响应的对话。https://github.com/InternLM/lmdeploy/issues/325

**Comment by sleepwalker2017** [comment]
> 会话模式就是服务端这边保存历史记录，也就是你理解的自动加载以前的历史。 字面意思，停止一个正在响应的对话。#325

我按你说的方式尝试了下，只有第一次问问题会有回答，后面啥都不返回了，这是怎么回事？为什么我的请求被无视了？
会话模式是指如果前面返回的结果被截断了，继续生成吗？
![image](https://github.com/InternLM/lmdeploy/assets/26128514/b03a0469-b07c-4b28-917a-b21490b53032)

**Comment by AllentDan** [comment]
给个完整的复现脚本吧。另外你要用会话模式，还要保证 instance_id 传入的是一个

**Comment by sleepwalker2017** [comment]
> 

OK  我先看看 example  感谢
