### ISSUE TITLE
Support Falcon 180B

### ISSUE THREAD

**Issue by ferrybaltimore** [InternLM/lmdeploy#386]
### Motivation

Do you plan to add support for Falcon 180B?

**Comment by lvhan028** [comment]
Hi, thanks for your attention to lmdeploy
Yes. We'll start it next week. Stay tuned

**Comment by datalee** [comment]
贵司这么有钱，有资源部署？

**Comment by lvhan028** [comment]
LMDeploy中的PyTorchEngine可以部署Falcon模型
