### ISSUE TITLE
awq量化测试结果疑问

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#389]
![image](https://github.com/InternLM/lmdeploy/assets/6971044/3fbb1c60-a6a0-46e8-ba00-96e179d328ef)

有两个问题想请教下：
1.  请问这个图表里测试结果的单位是？是tokens / s 吗
2. 有和非量化的推理速度对比数据吗？

谢谢！

**Comment by pppppM** [comment]
单位是 tokens/s

这个 issue 中有一些和 FP16 的对比数据
https://github.com/mit-han-lab/llm-awq/issues/78
