### ISSUE TITLE
[Feature] 请问支持设置随机种子为固定值不？

### ISSUE THREAD

**Issue by wangzhijian-tal** [InternLM/lmdeploy#391]
### Motivation

再跑完训练模型后，需要对齐下训练的前向的生成结果，跟推理的结果，但是因为采样的随机性导致很不好对齐，请问可以固定住种子进行采样唯一不？如何操作呢？

**Comment by lvhan028** [comment]
turbomind.py中的stream_infer接口，是支持固定random_seed的。
但是，恐怕无法训练的前向结果完全对齐。因为实现方式不一样。

**Comment by wangzhijian-tal** [comment]
> turbomind.py中的stream_infer接口，是支持固定random_seed的。 但是，恐怕无法训练的前向结果完全对齐。因为实现方式不一样。

好的，谢谢，我去试试看
