### ISSUE TITLE
尝试直接python setup.py install安装，会报如下错误

### ISSUE THREAD

**Issue by pangsg** [InternLM/lmdeploy#393]
warning: no files found matching 'lmdeploy/lib/*.so'
warning: no files found matching 'lmdeploy/lib/*.so*'
warning: no files found matching 'lmdeploy/lib/*.dll'
warning: no files found matching 'lmdeploy/lib/*.pyd'
warning: no files found matching 'lmdeploy/bin/*'

**Comment by lvhan028** [comment]
因为没有编译 lmdeploy。我们建议使用lmdeploy的python package：`pip install lmdeploy`
如果需要使用源码，请参考 https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/build.md 进行编译和安装

**Comment by pangsg** [comment]
感谢您的回复！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Lyu Han ***@***.***&gt;
发送时间: 2023年9月11日 11:21
收件人: InternLM/lmdeploy ***@***.***&gt;
抄送: nlp-pang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [InternLM/lmdeploy] 尝试直接python setup.py install安装，会报如下错误 (Issue #393)





 
因为没有编译 lmdeploy。我们建议使用lmdeploy的python package：pip install lmdeploy
 如果需要使用源码，请参考 https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/build.md 进行编译和安装
