### ISSUE TITLE
GGUF support

### ISSUE THREAD

**Issue by viktor-ferenczi** [InternLM/lmdeploy#395]
### Motivation

AWQ is nice, but if you want more control over the bit depth (thus VRAM usage), then GGUF may be a better option. A wide range of models are available from TheBloke at various bit depths, so everybody can use the biggest one which can fit into their GPUs.

I cannot find a high-throughput batch inference engine which can load GGUF, maybe there is none. (vLLM cannot load it either.)

### Related resources

https://github.com/ggerganov/llama.cpp

https://huggingface.co/TheBloke

**Comment by lvhan028** [comment]
Hi, @viktor-ferenczi , thanks for your attention to LMDeploy.

LMDeploy supports LLM models in three formats:
- huggingface transformers
- facebook/llama
- awq

I think it meets most users' requirements.  So we'd like to devote ourselves to optimizing the inference pipeline, making it faster, and supporting more LLM models.

**Comment by viktor-ferenczi** [comment]
Thank you for your honest response. 

I would add only one thing: The above input formats currently limit the per-weight bit count to 4, 16, and 32, leaving a gaping hole in place of a high quality 8 bit option.
