### ISSUE TITLE
[Bug] Emoji with OpenAI Streaming

### ISSUE THREAD

**Issue by hatrexltd** [InternLM/lmdeploy#396]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

Emojis are displayed in this form �  with the OpenAI stream

### Reproduction

python3 -m lmdeploy.serve.openai.api_server ./workspace 0.0.0.0 41500 --instance_num 32 --tp 8

**Comment by AllentDan** [comment]
Hi, did you try the browser? Here is what I got.
![image](https://github.com/InternLM/lmdeploy/assets/41138331/3fa08d6d-1560-4464-a880-abf13fdb1869)

**Comment by hatrexltd** [comment]
> Hi, did you try the browser? Here is what I got. ![image](https://user-images.githubusercontent.com/41138331/267285393-3fa08d6d-1560-4464-a880-abf13fdb1869.png)

With stream=false, the emojis appear, but in stream=true, they do not appear. I use Postman

**Comment by AllentDan** [comment]
Here is what I got from a terminal.
![image](https://github.com/InternLM/lmdeploy/assets/41138331/21d663b3-d463-4a86-aea3-5522a8f4c5c1)

Is it because of Postman?
