### ISSUE TITLE
[Feature] Is there a plan to support BF16 inference?

### ISSUE THREAD

**Issue by qingchanghan** [InternLM/lmdeploy#403]
### Motivation

It appears that LMDeploy does not support native BF16 inference, but instead converts it to FP16. 

But this may lead to precision overflow (https://github.com/InternLM/lmdeploy/issues/385), is there a plan to support BF16 inference?

**Comment by lzhangzz** [comment]
Yes, we will bring back BF16 support after a few major refectoring to lower the maintainance cost.

BTW, which model are you testing has overflow issue using f16 type?

**Comment by qingchanghan** [comment]
Thank you! Look forward to the follow-up progress.

And we encountered this problem with an internal inference framework and internal models. These models are trained with BF16 precision.

**Comment by lzhangzz** [comment]
I see. 

Have you checked in which layer or operator the overflow arises?

**Comment by qingchanghan** [comment]
Sorry, I didn't check it carefully.

But when I changed the precision to FP16, I can get the correct result.

**Comment by lvhan028** [comment]
PR #803
