### ISSUE TITLE
[Feature] Why do we need NcclGuard and group_id_

### ISSUE THREAD

**Issue by akhoroshev** [InternLM/lmdeploy#409]
### Motivation

I read the source and I can't understand the motivation for introducing `NcclGuard` and` group_id_`

In most cases it is used before `ftNcclAllReduceSum`. But NcclParam already has `ncclUniqueId nccl_uid_{};` which is used for some sort of grouping inside nccl.

Maybe I'm missing something?

**Comment by lzhangzz** [comment]
Using multiple NCCL communicators concurrently can [lead to deadlocks](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/usage/communicators.html#using-multiple-nccl-communicators-concurrently). And this is the case when running multiple tensor parallel model instances using tritonserver (each model instance has its own communicator).

**Comment by akhoroshev** [comment]
Thank you for answer
