### ISSUE TITLE
[Bug] Official Image hangs with tritonserver

### ISSUE THREAD

**Issue by jjjjohnson** [InternLM/lmdeploy#410]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

I used the latest image: openmmlab/lmdeploy:latest 
Cannot launch triton. Looks like the program hangs forever without error.
I used A800 *2 with TP=2

### Reproduction

tritonserver \
        --model-repository=/mnt/workspace/lmdeploy_llama_tp2/model_repository \
        --allow-http=0 \
        --allow-grpc=1 \
        --grpc-port=33337 \
        --log-verbose=0 \
        --allow-metrics=1

**Comment by jjjjohnson** [comment]
<img width="1221" alt="image" src="https://github.com/InternLM/lmdeploy/assets/20569095/6e8c960b-0120-4449-a6fd-7cdfa32816cf">

**Comment by lvhan028** [comment]
Hi, @jjjjohnson I haven't reproduced it yet. 
Is it an inevitable problem on your side?
Did you convert llama2 by `deploy.py`with argument `--tp 2`?

**Comment by jjjjohnson** [comment]
Hi @lvhan028, Thanks for your Reply!  Yes I successfully convert llama2 using
`python3 -m lmdeploy.serve.turbomind.deploy llama2 /path/to/Llama-2-13b-chat-hf --dst_path lmdeploy_llama_tp2 --tp 2 `
The config.ini is:
```
[llama]
model_name = llama2
head_num = 40
kv_head_num = 40
size_per_head = 128
vocab_size = 32000
num_layer = 40
rotary_embedding = 128
rope_theta = 10000.0
inter_size = 13824
norm_eps = 1e-05
attn_bias = 0
start_id = 1
end_id = 2
weight_type = fp16
group_size = 0
max_batch_size = 32
max_context_token_num = 4
session_len = 4104
step_length = 1
cache_max_entry_count = 48
cache_chunk_size = 1
use_context_fmha = 1
quant_policy = 0
tensor_para_size = 2
max_position_embeddings = 4096
use_dynamic_ntk = 0
use_logn_attn = 0
```

**Comment by jjjjohnson** [comment]
I also tried to convert model with --tp=1 and tritonserver still hangs...

**Comment by lvhan028** [comment]
Could you try to `docker pull openmmlab/lmdeploy:latest` again?

**Comment by lvhan028** [comment]
BTW, what's your device?

**Comment by jjjjohnson** [comment]
I used Ali Cloud GPU instance, Looks like there is env issue based on the message:
b_log.c:246  UCX  ERROR ibv_create_cq(cqe=4096) failed: Cannot allocate memory. Please set max locked memory (ulimit -l) to 'unlimited' (current: 64 kbytes)

**Comment by lzhangzz** [comment]
Looks like this is related to https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html#infiniband

**Comment by jjjjohnson** [comment]
Yes  @lzhangzz I need to add docker run with:
–ulimit memlock=-1
Then everything works fine. Thanks a lot!
