### ISSUE TITLE
[Bug] batch内sequence lengths不一样时，flashAttention-1和flashAttention-2结果不一致

### ISSUE THREAD

**Issue by cailikun** [InternLM/lmdeploy#414]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

现象：
-  BS=1，flashAttetion-1和flashAttention-2结果一致
-  BS=2，batch内sequence lengths一样，flashAttetion-1和flashAttention-2结果一致
-  BS=2，batch内sequence lengths不一样，flashAttetion-1和flashAttention-2结果不一致

测试模型：
Llama2 70b, TP8

测试数据:
1, 450, 1570, 14500, 10317, 310, 15710, 362, 338, 1985, 411, 278, 2106, 29915, 29879, 8608, 362, 14311, 304
1, 450, 1570, 3088, 4406, 1934, 505, 263, 716, 2343, 11182, 29892, 322, 540, 29915, 29879, 263, 1410, 29891, 1058

结果对比方式：
dump rank=0 第一层 走完attention之后的kv cache
<img width="809" alt="image" src="https://github.com/InternLM/lmdeploy/assets/6256838/c3da275e-f443-49ff-b788-37dd16548db7">

### Reproduction

example/cpp/llama/llama_triton_examlpe

**Comment by lzhangzz** [comment]
有没有试过在`config.ini`里面`use_context_fmha = 0`把flash attention关掉，kv cache的数值怎么样？

**Comment by cailikun** [comment]
> 有没有试过在`config.ini`里面`use_context_fmha = 0`把flash attention关掉，kv cache的数值怎么样？

尝试过，结果与flashAttention-1的结果差异在1E-5左右，我认为这应该是在精度允许的范围内。与flashAttention-2的结果差异依然很大

**Comment by grimoire** [comment]
attention output 一样吗？还有生成的 token 一样吗？ flash attention 应该是不会更新 kv cache 的。

**Comment by cailikun** [comment]
> attention output 一样吗？还有生成的 token 一样吗？ flash attention 应该是不会更新 kv cache 的。

我的表述有点不准确，我对比的就是attention output。并且用flashAttention社区的最新代码跑同样的qkv，结果和lmdeploy下flashAttention-1的结果一样，与lmdeploy下flashAttention-2的结果也相差很大

**Comment by grimoire** [comment]
要不你先试试这个 PR?
https://github.com/InternLM/lmdeploy/pull/418 

抱歉我好像忘记把 kv 的 seqlen 传给 kernel 了， flashattention1 里是通过 mask 来感知长度的所以没出错

**Comment by cailikun** [comment]
> 要不你先试试这个 PR? #418
> 
> 抱歉我好像忘记把 kv 的 seqlen 传给 kernel 了， flashattention1 里是通过 mask 来感知长度的所以没出错

初步验证了一下这个PR下没有问题
