### ISSUE TITLE
[Feature] forward thread safe

### ISSUE THREAD

**Issue by akhoroshev** [InternLM/lmdeploy#419]
### Motivation

Is the https://github.com/InternLM/lmdeploy/blob/main/src/turbomind/models/llama/LlamaV2.cc#L522 thread safe?

I read the source and realized that all inference work happens in background thread (internalThreadEntry).

So can I safety call forward from multiple threads?

**Comment by lzhangzz** [comment]
Sorry for the late reply.

> So can I safety call forward from multiple threads?


Yes, calling forward from multiple threads is safe and that's how we handle concurrent requests.

**Comment by akhoroshev** [comment]
Thank you
