### ISSUE TITLE
[Bug] Is it normal that streamed responses are completely different from non-streamed responses?

### ISSUE THREAD

**Issue by hatrexltd** [InternLM/lmdeploy#423]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

Hello, I use a finetune model and I obtain more qualitative responses with stream=false than stream=true. The answers change a lot and are diverse, unlike with stream=true. Is this normal?

### Reproduction

python3 -m lmdeploy.serve.openai.api_server ./workspace 0.0.0.0 60000 --instance_num 32 --tp 8
(Llama 2 70B)

**Comment by lvhan028** [comment]
`sampling` is enabled. Normally, each request even the same get different response

**Comment by hatrexltd** [comment]
> `sampling` is enabled. Normally, each request even the same get different response

Yes, we agree on that. But I notice that it's more diversified with stream=false. I often get the same introduction with stream=true, as with stream=false where I get very diverse responses. Is there a reason for this?

**Comment by lvhan028** [comment]
@AllentDan is it still an issue?

**Comment by AllentDan** [comment]
Inside the api_server, `stream==false` is treated as `stream==True`.
