### ISSUE TITLE
[Feature] more user-friendly CLI for LMDeploy

### ISSUE THREAD

**Issue by C1rN09** [InternLM/lmdeploy#427]
### Motivation

I'm currently using LMDeploy to test/deploy different models, and find it **awkward to run long commands** like

```bash
python3 -m lmdeploy.serve.turbomind.deploy [model_type] [model_path]
```

I think there are generally 2 points for improvement:

1. `python -m xxx` is too long. I believe it's better to have a short cli executable.
2. The module structure is kind of confusing to me, e.g. `lmdeploy.serve.turbomind.deploy` for model conversion.

So I'm requesting a CLI with explicit subcommands for LMDeploy, something look like:

```bash
lmdeploy --help
lmdeploy convert [model_type] [model_path]
lmdeploy serve xxx
lmdeploy client yyy
```

Is this feature something you would consider? Does it contradict to your design philosophy? If you are interested, I may get involved and help with this feature.

**Comment by RunningLeon** [comment]
@C1rN09 hi, certainly, cli is more user-friendly. We'll consider your suggestion. Will come back to you once there's a clear plan.

**Comment by C1rN09** [comment]
@RunningLeon Hi, I've just recovered from a flu and now feels ready for this feature :)

I guess implementing the CLI should not be too hard, because it could be just "wrappers" to existing modules. However, my concern is that I'm not familiar with the structure and roadmap of this project and I'm afraid of messing it up. For example, the model formats (e.g. turbomind, hf) to support, the serving methods (e.g. triton_server), the clients (e.g. terminal, webui), etc. Hope to have a discussion on this :)

**Comment by RunningLeon** [comment]
@C1rN09 hi, could you take a look at the draft [PR](https://github.com/InternLM/lmdeploy/pull/541) and offer us your opinions and suggestions? Thanks a lot.

**Comment by pangsg** [comment]
1.在text generation/code generation，是否可以增加可配置的sys prompt/ user prompt
2.提供压测脚本/代码，测试continuous batching等特性的极限
3.假如我们想把自研模型接入turbomind后端，需要如何对接？可否出个简单的教程？
4.针对restful api，会偶现内存溢出bug，是不是可以出个readme，列一些风险点

**Comment by RunningLeon** [comment]
> 1.在text generation/code generation，是否可以增加可配置的sys prompt/ user prompt 2.提供压测脚本/代码，测试continuous batching等特性的极限 3.假如我们想把自研模型接入turbomind后端，需要如何对接？可否出个简单的教程？ 4.针对restful api，会偶现内存溢出bug，是不是可以出个readme，列一些风险点

@pangsg hi, these are not related with the MMDeployCLI. Suggest you put them in another new issue.
