### ISSUE TITLE
[Feature] Multimodal LLM Support

### ISSUE THREAD

**Issue by zhang-jr** [InternLM/lmdeploy#433]
### Motivation

Thank you for your excellent work. Are there any plans to support multimodal LLM, such as Llava, Minigpt4, Qwen-VL, etc.? Alternatively, are there any instructions available for users to customize their own models?

**Comment by lvhan028** [comment]
We probably support multimodal LLM in Q4. minigpt4 might be our first choice

**Comment by lvhan028** [comment]
It has been put into lmdeploy backlog.
