### ISSUE TITLE
api server在一定并发下发现的问题

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#436]
在客户端并发量为10时，访问generate接口。top_k设置为1确保输出无随机性，request_output_len设置为128，使用streaming生成。此时，实际观测到的output_len为70多。   如果相同设置在较小并发量下(已试过1,2,4)，实际观测到output_len为128，是期望中的输入设置的值。

**Comment by AllentDan** [comment]
设置了 ignore_eos 为 True 吗？

**Comment by frankxyy** [comment]
@AllentDan hi，没有哈。因为我设置了top_k=1，按道理输出的长度应该是固定的吧？ 在concurrancy为1时，测试输出长度是>=128的。不过我实际打印生成结果看了下，每次的生成结果还是有细微的差异，不知道这块top_k=1未生效的原因是啥。

还有个问题想请教下的是，openai接口是否支持streaming？我用样例get_streaming_response代码修改了payload去访问openai chat completions 接口，接收response时报错了

**Comment by AllentDan** [comment]
> @AllentDan hi，没有哈。因为我设置了top_k=1，按道理输出的长度应该是固定的吧？ 在concurrancy为1时，测试输出长度是>=128的。不过我实际打印生成结果看了下，每次的生成结果还是有细微的差异，不知道这块top_k=1未生效的原因是啥。
> 
> 还有个问题想请教下的是，openai接口是否支持streaming？我用样例get_streaming_response代码修改了payload去访问openai chat completions 接口，接收response时报错了

支持 streaming，可以直接用 swagger UI 测，很方便。我们内部有随机种子的，top_k=1 没法固定随机数啊。要想获取固定长度的输出，请设置 ignore_eos 为 True，这样模型会一直说，直到到达要求的输出长度。

**Comment by jibowang** [comment]
@frankxyy 你好，请教一下，我在使用时，发现接口 ”/v1/chat/completions“ 不支持并发。
启动: `lmdeploy serve api_server /models/trubmind_qwen_7b 0.0.0.0 --server_port 8000 --instance_num 32 --tp 2`
测试：用`两个` 终端同时 curl，
```
curl http://localhost:8000/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
    "model": "qwen-7b",
    "messages": [{"role": "user", "content": "用1000字介绍下上海"}],
    "stream": 1
  }'
```
当只有一个终端输出完后，第二个终端才开始推理。是我的参数配置有问题吗？我看你说问题描述是支持并发的。

**Comment by frankxyy** [comment]
@jibowang 感觉没问题，你服务启动时instance_num设置多大？

**Comment by AllentDan** [comment]
@jibowang 微信回你了，这个问题关掉了，有其他问题可以再开或者新 issue
