### ISSUE TITLE
question about kv int8

### ISSUE THREAD

**Issue by sleepwalker2017** [InternLM/lmdeploy#438]
A30 两卡运行Llama 13B模型，在量化前使用 Fp16，最大 batch 可以到 21.
在做完kv int8 文档里的 quant 操作后，最大能支持到 24.

显存占用差异这么小吗？这是不是不符合预期？

**Comment by sleepwalker2017** [comment]
结论：
之前搞混了， 21是两卡 V100 的测试结果。

在 A30 上，两卡使用fp16，最大 batch 12。开启 int8 后，最大 batch 24.符合预期。

**Comment by 77h2l** [comment]
> 结论： 之前搞混了， 21是两卡 V100 的测试结果。
> 
> 在 A30 上，两卡使用fp16，最大 batch 12。开启 int8 后，最大 batch 24.符合预期。

@sleepwalker2017 请问一下这个吞吐量是用什么工具测试的哈？

**Comment by sleepwalker2017** [comment]
只测试了最大 batch，没测吞吐量啊。一直增加用户数，直到显存 OOM

**Comment by lin65505578** [comment]
吞吐没有提升
