### ISSUE TITLE
如何用benchmark来评测Qwen-7B

### ISSUE THREAD

**Issue by cgq0816** [InternLM/lmdeploy#439]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

评测方法中需要输入/path/to/tokenizer/tokenizer.model ，但是Qwen-7B不会生成tokenizer.model ,请问我该如何进行评测呢？

### Reproduction

python profile_restful_api.py http://0.0.0.0:33337 /data/cgq/workspace/triton_models/tokenizer/tokenizer.model /home/gqchen/ShareGPT_V3_unfiltered_cleaned_split.json --concurrency 5

**Comment by lvhan028** [comment]
忘记qwen是tikoken了。
感觉我们得改下restful_api的profile方式。我们内部先讨论下，有结论后再来同步

**Comment by AllentDan** [comment]
Hi, @cgq0816 the bug was fixed in #443
