### ISSUE TITLE
[Bug] topk is larger

### ISSUE THREAD

**Issue by hatrexltd** [InternLM/lmdeploy#441]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

When there are too many simultaneous requests, errors occur and the server crashes. How to fix this problem ?

### Reproduction

1|triton  | [WARNING] topk (471476112) is larger than max supported number (1024) for token 5 clip to max supported number 1024. 
1|triton  | [WARNING] topk (471476112) is larger than max supported number (1024) for token 5 clip to max supported number 1024. 
1|triton  | [WARNING] topk (471476112) is larger than max supported number (1024) for token 5 clip to max supported number 1024. 
1|triton  | [WARNING] topk (471476112) is larger than max supported number (1024) for token 5 clip to max supported number 1024. 
1|triton  | [WARNING] topk (471476112) is larger than max supported number (1024) for token 5 clip to max supported number 1024. 
1|triton  | [WARNING] topk (471476112) is larger than max supported number (1024) for token 5 clip to max supported number 1024. 
1|triton  | [WARNING] topk (471476112) is larger than max supported number (1024) for token 5 clip to max supported number 1024. 1|triton  | [WARNING] topk (471476112) is larger than max supported number (1024) for token 5 clip to max supported number 1024. 
1|triton  | [WARNING] topk (471476112) is larger than max supported number (1024) for token 5 clip to max supported number 1024. 
1|triton  | [WARNING] topk (471476112) is larger than max supported number (1024) for token 5 clip to max supported number 1024. 
1|triton  | [WARNING] topk (471476112) is larger than max supported number (1024) for token 5 clip to max supported number 1024. 
1|triton  | [WARNING] topk (471476112) is larger than max supported number (1024) for token 5 clip to max supported number 1024. 
1|triton  | [WARNING] topk (471476112) is larger than max supported number (1024) for token 5 clip to max supported number 1024. 
1|triton  | [WARNING] topk (471476112) is larger than max supported number (1024) for token 5 clip to max supported number 1024.
1|triton  |   what():  [TM][ERROR] CUDA runtime error: out of memory /lmdeploy/src/turbomind/utils/allocator.h:223 
(24GB/80GB per GPU used)

**Comment by lvhan028** [comment]
Could you share the reproduction method?

**Comment by hatrexltd** [comment]
> Could you share the reproduction method?

python3 -m lmdeploy.serve.openai.api_server ./workspace 0.0.0.0 10000 --instance_num 32 --tp 8
Model : Llama 2 (70B)
To reproduce the bug, you have to send lots of requests (5-20 per second)

**Comment by hatrexltd** [comment]
Even with v0.0.9, I still experience crashes with the same error

**Comment by lvhan028** [comment]
Can you share your client code to help us reproduce it?

**Comment by hatrexltd** [comment]
> Can you share your client code to help us reproduce it?

Llama 70B HF
python3 -m lmdeploy.serve.openai.api_server ./workspace 0.0.0.0 43000 --instance_num 32 --tp 8
LMDeploy 0.0.9
No modifications

Lmdeploy only uses 25% of VRAM. Is it possible to make it use more, like for vllm to support more concurrent requests? I only have this problem when there are too many requests.

**Comment by hatrexltd** [comment]
I will try this https://github.com/InternLM/lmdeploy/pull/460

**Comment by hatrexltd** [comment]
The problem is actually still present. It occurs when too many requests are made in a period of time, even after updating to LMDeploy 0.1.0

**Comment by lvhan028** [comment]
@AllentDan Could you help investigate it?

**Comment by AllentDan** [comment]
@hatrexltd Which api did you use? And how did you send the requests?
