### ISSUE TITLE
[Hugging Face Demo] Provide a InternLM-20B-Chat Demo

### ISSUE THREAD

**Issue by MJIMMYA** [InternLM/lmdeploy#446]
https://huggingface.co/spaces/BridgeEight/internlm-20B-chat-w4-turbomind

![e85df4cf9167ea7a52a0865145ef6d1](https://github.com/InternLM/InternLM/assets/33955941/af14373d-8317-4144-b9d6-914eaebbe525)

**Comment by wizd** [comment]
error?

```
bridgeeight-internlm-20b-chat-w4-turbomind.hf.space’s server IP address could not be found.
```

**Comment by lvhan028** [comment]
@MJIMMYA sorry, I didn't get it. 
Are you requesting us to deploy an InternLM-20B-Chat model on hugging face, or reporting an issue?
