### ISSUE TITLE
[Bug] 按照教程执行基于pytorch的推理的时候，采用--num_gpus 4 时并不会随机把任务分配到四张显卡的显存上

### ISSUE THREAD

**Issue by WiselyC0430** [InternLM/lmdeploy#448]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

[Bug] 按照教程执行基于pytorch的推理的时候，采用--num_gpus 4 时并不会随机把任务分配到四张显卡的显存上，（12*4=48>12），而是随机挑选一张卡将他挤爆（并不局限于挤爆0号卡）。切换成单卡之后是明显的显存不足，只会挤爆0号。
![fbd44b78f2b3a3aec3d9f71e6e36f18](https://github.com/InternLM/lmdeploy/assets/96457986/2dda9a4a-ec6b-42c9-ba40-d3d244d29a65)
![ce4e4e05cb8714739f3f6c7cf9e4855](https://github.com/InternLM/lmdeploy/assets/96457986/6eb164cc-a962-4261-855c-b8105aa3f816)

### Reproduction

deepspeed --module --num_gpus 2 lmdeploy.pytorch.chat \
    $NAME_OR_PATH_TO_HF_MODEL \
    --max_new_tokens 64 \
    --temperture 0.8 \
    --top_p 0.95 \
    --seed 0

### Error traceback

```Shell
torch,cuda.OutOfMemoryError: (CUDA out of memory, Tried to allocate 86,00 MB (GPU 3: 11.91 Gi total capacity: 10.09 GiB already allocated: 19.25 MiB free:10.09 GiB reserved in total by Pytorch) If reserved memory is y》 allocated memory try setting max_split_size_mb to avoid fragmentation, Se documentation for Memory Management and PYTORCH CUDA ALLOC CONF
```

**Comment by garyfanhku** [comment]
use `--include localhost:3,4` instead of `--num_gpus` flag. DeepSpeed has docs on this.
