### ISSUE TITLE
[Bug] 请问20b-int4量化模型用gradio 正常运行显存应占用多少

### ISSUE THREAD

**Issue by Jin2022** [InternLM/lmdeploy#452]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

请问下根据 https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/w4a16.md 这里的步骤量化20b 后启动 gradio 服务运行大概显存占多少，我这边用自己量化的和官方量化的int4模型要22gb左右是否正常，感觉比预期的大很多

### Reproduction

`python3 -m lmdeploy.serve.gradio.app /workspace/models/internlm-chat-20b-4bit/turbomind --server_name 0.0.0.0 --server_port 8001`

### Error traceback

<img width="2133" alt="image" src="https://github.com/InternLM/lmdeploy/assets/24568426/01789c3c-de17-4345-a201-0e2b6dd4170d">

<img width="717" alt="image" src="https://github.com/InternLM/lmdeploy/assets/24568426/ee6e3602-fb5a-4d90-8ad5-a0b7a020c4b4">

**Comment by lvhan028** [comment]
参考w4a16文档量化 internlm-20b 模型后，workspace/triton_models/weights/config.ini中的session_len是8200。即 8K 长度的 context windows。
turbomind会根据这个值来开辟 k/v cache 的显存，确实会到20多G。
如果用不到8K的话，可以调小，显存会降下来。

**Comment by Jin2022** [comment]
> 参考w4a16文档量化 internlm-20b 模型后，workspace/triton_models/weights/config.ini中的session_len是8200。即 8K 长度的 context windows。 turbomind会根据这个值来开辟 k/v cache 的显存，确实会到20多G。 如果用不到8K的话，可以调小，显存会降下来。

好的清楚了，多谢解惑。
可以帮忙再看下双卡推理时候报错并且推理输出不正常问题，和上面一样的命令加上 --tp 2
<img width="1214" alt="image" src="https://github.com/InternLM/lmdeploy/assets/24568426/00d34235-b903-460a-b980-ca08248024dc">
<img width="1043" alt="image" src="https://github.com/InternLM/lmdeploy/assets/24568426/092595b8-d8b7-40d7-87d6-c969d6fca31c">
<img width="798" alt="image" src="https://github.com/InternLM/lmdeploy/assets/24568426/9c4b29cf-623d-4549-98ee-c8ab7ab058a8">
<img width="1136" alt="image" src="https://github.com/InternLM/lmdeploy/assets/24568426/519e4ab0-69a6-49ad-a871-eba69b77ac14">

**Comment by lvhan028** [comment]
这个问题和 #420 类似，可以参考 @lzhangzz 在 #420 中的回答

**Comment by Jin2022** [comment]
> 这个问题和 #420 类似，可以参考 @lzhangzz 在 #420 中的回答

好的 我试下
