### ISSUE TITLE
[Bug] 部署internlm-20b推理胡言乱语

### ISSUE THREAD

**Issue by mumuszhang** [InternLM/lmdeploy#453]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

<img width="1468" alt="1" src="https://github.com/InternLM/lmdeploy/assets/13376020/5ef91061-3153-4b03-8735-eab405d900db">

<img width="1450" alt="3" src="https://github.com/InternLM/lmdeploy/assets/13376020/4031d429-92e3-4801-a8f2-44b315c0ff51">

### Reproduction

通过以下方式部署

<img width="1046" alt="2" src="https://github.com/InternLM/lmdeploy/assets/13376020/04a72617-4a65-4baa-a78e-49f9f686e55b">

**Comment by lvhan028** [comment]
你用的是哪个模型呢？基座模型，还是对话模型？

**Comment by mumuszhang** [comment]
> 你用的是哪个模型呢？基座模型，还是对话模型？

应该是基座模型

**Comment by lvhan028** [comment]
用gradio的话，我们默认用户用的是对话模型的。会用对话的模板来装饰用户输入的prompt。
基座模型是没有对话能力的，使用gradio + webui 会出现你遇到的问题。
建议换成internlm-chat-20b

**Comment by amulil** [comment]
> 用gradio的话，我们默认用户用的是对话模型的。会用对话的模板来装饰用户输入的prompt。 基座模型是没有对话能力的，使用gradio + webui 会出现你遇到的问题。 建议换成internlm-chat-20b

模版怎么设置，比如 sft llama2 用了 alpaca 的模版

**Comment by liyunhan** [comment]
> 用gradio的话，我们默认用户用的是对话模型的。会用对话的模板来装饰用户输入的prompt。 基座模型是没有对话能力的，使用gradio + webui 会出现你遇到的问题。 建议换成internlm-chat-20b

请问使用“python3 -m lmdeploy.serve.openai.api_server ./workspace server_ip server_port --instance_num 32 --tp 1”命令部署也需要先转成turbomind支持的格式吗？转换以后也需要输入“python3 -m lmdeploy.turbomind.chat ./workspace”命令吗？还是下载模型权重后，直接启用restful的推理就好

**Comment by mumuszhang** [comment]
> 用gradio的话，我们默认用户用的是对话模型的。会用对话的模板来装饰用户输入的prompt。 基座模型是没有对话能力的，使用gradio + webui 会出现你遇到的问题。 建议换成internlm-chat-20b

了解了，thx

**Comment by lvhan028** [comment]
@amulil 对话模板都在 lmdeploy/model.py中，可以参考 llama2 增加 alpaca 模板

**Comment by lvhan028** [comment]
> > 用gradio的话，我们默认用户用的是对话模型的。会用对话的模板来装饰用户输入的prompt。 基座模型是没有对话能力的，使用gradio + webui 会出现你遇到的问题。 建议换成internlm-chat-20b
> 
> 请问使用“python3 -m lmdeploy.serve.openai.api_server ./workspace server_ip server_port --instance_num 32 --tp 1”命令部署也需要先转成turbomind支持的格式吗？转换以后也需要输入“python3 -m lmdeploy.turbomind.chat ./workspace”命令吗？还是下载模型权重后，直接启用restful的推理就好

是的。使用 api_server，需要转成 turbomind 支持的格式
转换之后，不用 ““python3 -m lmdeploy.turbomind.chat ./workspace”， 这个命令是在本地加载模型，在控制台输入问题，和AI助手交流。
用 "api_server"的话，转模型之后，直接可以启动 api_server了。
