### ISSUE TITLE
加载qwen-7b，显存为什么从15G跳到19G

### ISSUE THREAD

**Issue by foricee** [InternLM/lmdeploy#454]
运行这个命令加载模型
```bash
python -m lmdeploy.turbomind.chat ./workspace
```
显存占用会快速到15G，15G应该是模型的正常大小

![image](https://github.com/InternLM/lmdeploy/assets/1073188/690ef440-f65a-4cb5-ab17-cfd7fbdb9203)

保持15G几秒钟后突然跳到19G，多的几G是什么预申请的cache吗？可以关掉吗

![image](https://github.com/InternLM/lmdeploy/assets/1073188/b784abe8-d4e0-4c1b-8566-0e04a6d0798e)

**Comment by irexyc** [comment]
请问是哪个模型？

**Comment by foricee** [comment]
> 请问是哪个模型？

qwen-7b-chat

**Comment by irexyc** [comment]
@foricee 

多出来的4G是预申请的一个seq所需的kv_cache，没办法关闭，即使最开始不申请，也会在计算的时候申请，并且会随着batch_size的增加而增大。

你可以通过改写weights/config.ini 里面的 cache_max_entry_count 来控制kv_cache的最大值（不能小于max batch size)
