### ISSUE TITLE
[Feature] support offline batch infer 

### ISSUE THREAD

**Issue by Xu-Chen** [InternLM/lmdeploy#456]
### Motivation

希望可以支持离线批量推理，如果像 vllm 一样可以提供离线推理脚本(加载hf)就更好了

**Comment by vansin** [comment]
把权重下载下来了，就能离线推理了哇

**Comment by lvhan028** [comment]
hi, @Xu-Chen 

“离线推理”是指非 client-server 这种模式的推理吗？
如果是的话，lmdeploy是支持的。`deploy/turbomind/chat.py` 是一个例子。

现在 lmdeploy 还不支持直接加载 hf 模型，得做模型转换。
对于直接加载 hf 模型的需求，在我们的计划表中，大概10月底会release。

**Comment by Xu-Chen** [comment]
感谢感谢，是的。我试一下chat

**Comment by AllentDan** [comment]
@lvhan028 `deploy/turbomind/chat.py` 实际上不支持batch推理:sweat_smile: 不过我刚写好一个batch推理的功能 #467

**Comment by lvhan028** [comment]
> @lvhan028 `deploy/turbomind/chat.py` 实际上不支持batch推理😅 不过我刚写好一个batch推理的功能 #467

(⊙o⊙)…是我误解了

**Comment by Xu-Chen** [comment]
> @lvhan028 `deploy/turbomind/chat.py` 实际上不支持batch推理😅 不过我刚写好一个batch推理的功能 #467

佬测试了吗，batch推理有加速吗。
