### ISSUE TITLE
[Feature] Declare optional packages to reduce package size

### ISSUE THREAD

**Issue by gabrielfu** [InternLM/lmdeploy#459]
### Motivation

Currently running `pip install lmdeploy` installs everything like torch, triton, gradio, etc., which makes it very slow and occupies a lot of storage (especially if I'm building a docker image on top of it).

In reality, I often only need the torch functionality and don't need triton.

It will be nice if I can choose what functionality I want to install:
```shell
pip install lmdeploy[torch]
pip install lmdeploy[triton]
pip install lmdeploy[gradio]
```

**Comment by lvhan028** [comment]
That's a great idea. @RunningLeon could you help support this feature?

**Comment by RunningLeon** [comment]
@gabrielfu hi, thanks for your suggestion. We'll consider your suggestion and try to come up with a good solution.

**Comment by lvhan028** [comment]
@gabrielfu could you help check if PR #580 meets your request

**Comment by gabrielfu** [comment]
> @gabrielfu could you help check if PR #580 meets your request

@lvhan028  Looks great to me. Will be even better if there's more documentations on which optional package provides which functionalities. Thanks a lot for the update!

**Comment by RunningLeon** [comment]
@gabrielfu hi,  the installation infomation is updated in README.md. Any comment would be appreciated.
