### ISSUE TITLE
[Bug] 部署internlm-chat-20b-4bit推理胡言乱语

### ISSUE THREAD

**Issue by dlutsniper** [InternLM/lmdeploy#461]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

部署 internlm-chat-20b-4bit 推理胡言乱语
GPU：Tesla V100 32GB

推理胡言乱语：
<img width="1279" alt="图片" src="https://github.com/InternLM/lmdeploy/assets/30826840/f083aaaf-6c7d-437b-a53c-8a9d1df14227">

### Reproduction

pip install 'lmdeploy>=0.0.9'

# Convert the model's layout and store it in the default path, ./workspace.
python3 -m lmdeploy.serve.turbomind.deploy \
    --model-name internlm-chat-20b \
    --model-path /home/aistudio/data/data240556 \
    --model-format awq \
    --group-size 128

# inference
python3 -m lmdeploy.turbomind.chat ./workspace

**Comment by lvhan028** [comment]
lmdeploy doesn't support 4bit inference on Tesla V100 32GB.

As presented in https://github.com/InternLM/lmdeploy/blob/main/docs/en/w4a16.md: 

"LMDeploy supports LLM model inference of 4-bit weight, with the minimum requirement for NVIDIA graphics cards being sm80, such as A10, A100, Geforce 30/40 series."

**Comment by lywnko** [comment]
@dlutsniper 请问你图片里的是什么网页可视化系统，谢谢

**Comment by dlutsniper** [comment]
> @dlutsniper 请问你图片里的是什么网页可视化系统，谢谢

https://aistudio.baidu.com/ 百度飞桨社区的Jupyter notebook
