### ISSUE TITLE
[Question] When will lmdploy support code llama quantization?

### ISSUE THREAD

**Issue by gesanqiu** [InternLM/lmdeploy#469]
### Motivation

In the code-llama's deploy tutorial, quantization chapter remains to be done, when will this feature finished?

**Comment by lvhan028** [comment]
After Mid-Autumn Festival, before 10.20

**Comment by poisson-fish** [comment]
Not realizing LMDeploy didn't already support codellama quants, I ended up AWQ quantizing Phind's codellama fine-tune, maybe it can be useful for testing: [poisson-fish/Phind-CodeLlama-34B-v2-AWQ](https://huggingface.co/poisson-fish/Phind-CodeLlama-34B-v2-AWQ)
The quantization itself completed successfully with no problems, however running inference on the model obviously doesn't work.

**Comment by gesanqiu** [comment]
@lvhan028 Is this still on plan?

**Comment by lvhan028** [comment]
@pppppM tried, but the performance significantly decreased after quantization

**Comment by gesanqiu** [comment]
> @pppppM tried, but the performance significantly decreased after quantization

Can I ask in which part we meet the bottleneck?

**Comment by pppppM** [comment]
@gesanqiu LMDeploy is functionally capable of  the quantization of CodeLlama, but in practical use we found that performance significantly declines after quantization. 

We are also investigating the specific reasons for this, and what we've found so far is that there are more outliers in the model weights of CodeLlama, especially when you compare it to Llama2.

**Comment by gesanqiu** [comment]
> @gesanqiu LMDeploy is functionally capable of the quantization of CodeLlama, but in practical use we found that performance significantly declines after quantization.
> 
> We are also investigating the specific reasons for this, and what we've found so far is that there are more outliers in the model weights of CodeLlama, especially when you compare it to Llama2.

> more outliers in the model weights
Do you mean you meet accuracy issue? May smoothquant help with this issue? And have you been tested the throughput or latenct of AWQ codellama model on lmdeploy?

**Comment by gesanqiu** [comment]
> > @gesanqiu LMDeploy is functionally capable of the quantization of CodeLlama, but in practical use we found that performance significantly declines after quantization.
> > We are also investigating the specific reasons for this, and what we've found so far is that there are more outliers in the model weights of CodeLlama, especially when you compare it to Llama2.

Do you mean you meet accuracy issue? May smoothquant help with this issue? And have you been tested the throughput or latenct of AWQ codellama model on lmdeploy?

**Comment by lvhan028** [comment]
May try v0.4.2.
