### ISSUE TITLE
[Docs] 请问下instance_id这个是干嘛的？它可以一直给-1值吗？

### ISSUE THREAD

**Issue by wangzhijian-tal** [InternLM/lmdeploy#473]
### 📚 The doc issue

有关instance_id不是很懂，这个参数是什么作用,可以一直给-1值吗？多client直接请求是不是一直-1也ok？

**Comment by AllentDan** [comment]
最好用不同的 instance_id 传入 generate api。否则，我们将自动绑定会话 id 为请求端的 ip 地址编号，默认不同客户端应该IP也不一样。如果多个 client 如果用同一个 ip 地址的话就共享一个会话。这样请求不会被批量处理，而是一个接一个地处理
