### ISSUE TITLE
python3 -m lmdeploy.serve.turbomind.deploy internlm-chat \ --model-path ./internlm-chat-20b 我是安装在window下了 这个我修改为了： python3 -m lmdeploy.serve.turbomind.deploy internlm-chat \ --model-path D:/ai/InternLM/Shanghai_AI_Laboratory/internlm-chat-20b  但是运行后没有反应 也不报错

### ISSUE THREAD

**Issue by anstonjie** [InternLM/lmdeploy#477]
### Motivation

我在执行 以下命令时候
python3 -m lmdeploy.serve.turbomind.deploy internlm-chat \ --model-path ./internlm-chat-20b
我是安装在window下了 这个我修改为了：
python3 -m lmdeploy.serve.turbomind.deploy internlm-chat \ --model-path D:/ai/InternLM/Shanghai_AI_Laboratory/internlm-chat-20b

但是运行后没有反应 也不报错

**Comment by irexyc** [comment]
\ 是为了换行么？你如果用powershell的话，换行符是 ` 建议不要用换行了。

你先执行python3，看能不能进python的交互模式，能进就用python3，不能看看python能不能进交互模式，能进就用python，都不能的话检查python的安装以及环境。

在 非 lmdeploy 文件夹下，执行
`
python3 -m lmdeploy.serve.turbomind.deploy internlm-chat  --model-path D:/ai/InternLM/Shanghai_AI_Laboratory/internlm-chat-20b
`
