### ISSUE TITLE
[Feature] QWen推理

### ISSUE THREAD

**Issue by Vincent131499** [InternLM/lmdeploy#478]
### Motivation

看到turbomind框架支持了QWen-7b-chat,想问下这个模型怎么转换呢，具体命令是啥啊，我这边使用
python3 -m lmdeploy.serve.turbomind.deploy qwen-7b ../pretrain_models/Qwen-7B-chat/ qwen --tp 1 -d ./workspace-qwen-7b-chat-fp16-1gpu/
出现如下信息：
create workspace in directory ./workspace-qwen-7b-chat-fp16-1gpu/
copy triton model templates from "/workspace/lmdeploy-master/lmdeploy/lmdeploy/serve/turbomind/triton_models" to "./workspace-qwen-7b-chat-fp16-1gpu/triton_models" successfully
tokenizer model None does not exist

**Comment by lvhan028** [comment]
`python3 -m lmdeploy.serve.turbomind.deploy qwen-7b /nvme/shared_data/Qwen/Qwen-7B-Chat/  --dst-path workspace/qwen-7b-chat`

**Comment by Vincent131499** [comment]
> `python3 -m lmdeploy.serve.turbomind.deploy qwen-7b /nvme/shared_data/Qwen/Qwen-7B-Chat/ --dst-path workspace/qwen-7b-chat`

收到，感谢，我试下。
另外Qwen-14B-Chat出来了，这个模型也可以直接转换吗

**Comment by lvhan028** [comment]
@irexyc 在适配中

**Comment by irexyc** [comment]
@Vincent131499 

fp16的话，可以转。对话模版Qwen-14B-Chat 和 Qwen-7B-Chat 是一样的。

python3 -m lmdeploy.serve.turbomind.deploy qwen-7b /nvme/shared_data/Qwen/Qwen-14B-Chat/ --dst-path workspace/qwen-14b-chat

**Comment by lvhan028** [comment]
> @Vincent131499
> 
> fp16的话，可以转。对话模版Qwen-14B-Chat 和 Qwen-7B-Chat 是一样的。
> 
> python3 -m lmdeploy.serve.turbomind.deploy qwen-7b /nvme/shared_data/Qwen/Qwen-14B-Chat/ --dst-path workspace/qwen-14b-chat

加一个 qwen-14b的tag吧

**Comment by Vincent131499** [comment]
@irexyc 感谢，改了加载权重的代码可以work。有两个疑问：
1.7b和14b转完之后都可以使用kv-int8？
2.目前正在适配W4A16吗？

**Comment by irexyc** [comment]
1. 都可以使用kv-int8。
2. awq 量化qwen 结果有问题，目前正在开发GPTQ算法的支持，有进展了会在主页更新
