### ISSUE TITLE
[Bug] 使用api_client进行对话， 第一个问题，得不到回答？

### ISSUE THREAD

**Issue by youngallien** [InternLM/lmdeploy#483]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

使用api_client进行对话， 第一个问题，得不到回答？总是在第二个问题之后，才会正常回答

### Reproduction

> python3 -m lmdeploy.serve.openai.api_server /workspace/models 0.0.0.0 23333 --instance_num 32 --tp 1
>  python -m lmdeploy.serve.openai.api_client http://localhost:23333

### Error traceback

```Shell
double enter to end input >>> hello

           
double enter to end input >>> hello

 Hello !   How   can   I   assist   you   today ? <eoa> 
double enter to end input >>>
```

**Comment by AllentDan** [comment]
没能复现问题，你可以 debug 启动服务端吗？然后看下为啥是空的

**Comment by lvhan028** [comment]
哪个模型呢？

**Comment by youngallien** [comment]
用的20B模型， 感觉是api_client.py这个脚本写的有问题， 我改动为不用交互式方法调用，直接把prompt写在脚本里， 就可以了。

**Comment by AllentDan** [comment]
https://github.com/InternLM/lmdeploy/pull/487 修好了，因为关闭脚本没有结束会话，所以 step 不为0。后续使用脚本，用exit退出，或者每次用不同的 session_id 就好
