### ISSUE TITLE
[Bug] 通过 Restful API 部署服务

### ISSUE THREAD

**Issue by wujianqiangwjq** [InternLM/lmdeploy#484]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

[通过 Restful API 部署服务](https://github.com/InternLM/lmdeploy/blob/main/README_zh-CN.md#%E9%80%9A%E8%BF%87-restful-api-%E9%83%A8%E7%BD%B2%E6%9C%8D%E5%8A%A1)测试没有任何返回.

### Reproduction

python3 -m lmdeploy.turbomind.chat ./workspace  这个命令是正常的，python3 -m lmdeploy.serve.openai.api_server ./workspace server_ip server_port --instance_num 32 --tp 1 使用命令可以正常运行，python -m lmdeploy.serve.openai.api_client restful_api_url 使用这个测试，得不到任何回复。模型是internlm-20b-chat

**Comment by AllentDan** [comment]
你可以直接浏览器打开 swagger UI吗？`http://{server_ip}:{server_port}`，试试有没有输出

**Comment by wujianqiangwjq** [comment]
![image](https://github.com/InternLM/lmdeploy/assets/20573480/37724ecd-ed9d-46e2-88a8-b9868c3b9f24)

fastapi doc是正常的
![image](https://github.com/InternLM/lmdeploy/assets/20573480/21f9995b-a5aa-4ce0-a72d-d1a8b97c9dfc)

**Comment by AllentDan** [comment]
`localhost` 改成 `0.0.0.0`呢

**Comment by AllentDan** [comment]
https://github.com/InternLM/lmdeploy/pull/487 修复了
