### ISSUE TITLE
[Feature] CURL怎么使用流式输出？

### ISSUE THREAD

**Issue by youngallien** [InternLM/lmdeploy#485]
### Motivation

curl http://{server_ip}:{server_port}/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
    "model": "internlm-chat-7b",
    "messages": [{"role": "user", "content": "Hello! Ho are you?"}]
  }'
------------------------------------------
上面的操作， 可以增加流式输出吗？具体是怎么操作？
我在 -d里面添加"stream":True, 不能解决问题

### Additional context

curl http://localhost:23333/v1/chat/completions \
>   -H "Content-Type: application/json" \
>   -d '{
>     "model": "internlm-chat-20b",
>     "messages": [{"role": "user", "content": "写一个1000字的小作文，描写我的祖国?"}],
>     "stream":true
>   }'
curl: (18) transfer closed with outstanding read data remaining

**Comment by AllentDan** [comment]
正常 stream=True 就能流式输出了啊，你那边方便 debug 原因吗？

**Comment by youngallien** [comment]
![bug_curl_stream_2023-09-26_20-25](https://github.com/InternLM/lmdeploy/assets/53220351/1734e5dd-f53b-4599-ae9a-7e91030ae3ab)
就是没有stream=True就正常输出， 添加stream就不行了。

**Comment by AllentDan** [comment]
你用 swagger UI 打开测试下，我这边没遇到过

**Comment by youngallien** [comment]
![openai_api_error](https://github.com/InternLM/lmdeploy/assets/53220351/130feb47-0260-4555-b656-a92dbdde7b65)
pydantic库从版本1.8.0开始不再支持dumps_kwargs关键字参数。exclude_unset=True和ensure_ascii=False这两个关键字参数有问题， 所以需要修改两个地方

**Comment by AllentDan** [comment]
最新的代码已经修过了
