### ISSUE TITLE
The performance comparison with fastertransformer

### ISSUE THREAD

**Issue by aido-ai** [InternLM/lmdeploy#486]
I would like to know what kind of environment is used for the performance comparison here. And whether there is any comparison test with fastertransformer?

Thanks~

**Comment by lvhan028** [comment]
model: llama-7b
device: A100-80G

We have no performance comparison results with FT.

**Comment by sleepwalker2017** [comment]
I checked the performance compared with FT. In terms of single batch inference, the performance is the same as FT.

In terms of multi-batching, the performance is better than FT only supports static batching.
