### ISSUE TITLE
python -m lmdeploy.serve.gradio.app ./workspace --server_name 127.0.0.1 --server_port 890900 运行这个命令的时候报错

### ISSUE THREAD

**Issue by anstonjie** [InternLM/lmdeploy#493]
### Motivation

python -m lmdeploy.serve.gradio.app ./workspace --server_name 127.0.0.1 --server_port 890900

**Comment by lvhan028** [comment]
`server_port` should be less than 65535

**Comment by lvhan028** [comment]
close since it is a duplicate issue to #494
