### ISSUE TITLE
Performance differs between different versions 

### ISSUE THREAD

**Issue by sleepwalker2017** [InternLM/lmdeploy#496]
Hello，我们之前对 lmdeploy 进行了一次 benchmark，在两卡的 A30 可以达到 260 token/sec。
但是最近，我用最新的代码测试，发现只能达到 230 token/sec。

具体是哪个版本开始出现差异我现在还不清楚，正在回滚测试。请问你们有相关的记录吗？或者是否有留意类似的问题。

**Comment by lvhan028** [comment]
没有留意到。我们也来测试下看看。
你用的是profile_generation脚本吗？

**Comment by sleepwalker2017** [comment]
> 没有留意到。我们也来测试下看看。 你用的是profile_generation脚本吗？

我是用 http service测试的，控制不同的用户数，在服务端记录 generated tokens 和 耗时，相除得到的。

**Comment by AllentDan** [comment]
> > 没有留意到。我们也来测试下看看。 你用的是profile_generation脚本吗？
> 
> 我是用 http service测试的，控制不同的用户数，在服务端记录 generated tokens 和 耗时，相除得到的。

你们目前定位的情况是啥样的？从哪个版本开始的性能下降

**Comment by sleepwalker2017** [comment]
> > > 没有留意到。我们也来测试下看看。 你用的是profile_generation脚本吗？
> > 
> > 
> > 我是用 http service测试的，控制不同的用户数，在服务端记录 generated tokens 和 耗时，相除得到的。
> 
> 你们目前定位的情况是啥样的？从哪个版本开始的性能下降

我们的测试是基于 8 月 20 号左右的一个 commit，但是我后来 pull 了一下，现在已经复现不出来了。
刚才问同事，他当时第一次测试的 commit 是d5cb0be2cd1，怀疑性能比较好的可能是这个 commit。我还没确认。

你们能复现这个问题吗？

**Comment by lvhan028** [comment]
@sleepwalker2017 我在debug一个其他比较奇怪的问题。还没有来得及测呢
@AllentDan 来帮忙看看吧

**Comment by AllentDan** [comment]
> @sleepwalker2017 我在debug一个其他比较奇怪的问题。还没有来得及测呢 @AllentDan 来帮忙看看吧

今天回滚一下

**Comment by wanzhenchn** [comment]
> 没有留意到。我们也来测试下看看。 你用的是profile_generation脚本吗？

用的 profile_restful_api.py 脚本测试的

**Comment by AllentDan** [comment]
Hi, @wanzhenchn @sleepwalker2017 我测试了下最新的代码，和最早的支持 api_server 的比，没有发现明显的性能下降。在真实数据集上的测试结果，我观测到的结果本身有个最大 10% 的波动。另外，测试方式不同也会有差别，注意关闭网络代理，不要以类似 vscode 调试的方式进行测速，会影响 20%~30% 的性能

**Comment by AllentDan** [comment]
Hi, @wanzhenchn @sleepwalker2017 我测试了下代码一直到 https://github.com/InternLM/lmdeploy/commit/22cd7d15151d9f360a6662e88056c6193c923707，和最早的支持 api_server 的比，没有发现明显的性能下降，除了测试脚本 tokenization 部分变得很慢。在真实数据集上的测试结果，我观测到的结果本身有个最大 10% 的波动。另外，测试方式不同也会有差别，注意关闭网络代理，不要以类似 vscode 调试的方式进行测速，会影响 20%~30% 的性能。

tokenization 部分我后面会考虑支持下 batch encode。

**Comment by sleepwalker2017** [comment]
> Hi, @wanzhenchn @sleepwalker2017 我测试了下代码一直到 [22cd7d1](https://github.com/InternLM/lmdeploy/commit/22cd7d15151d9f360a6662e88056c6193c923707) 和最早的支持 api_server 的比，没有发现明显的性能下降，我想现在 main分支除了测试脚本 tokenization 部分变得很慢应该和这个 commit 一致。在真实数据集上的测试结果，我观测到的结果本身有个最大 10% 的波动。另外，测试方式不同也会有差别，注意关闭网络代理，不要以类似 vscode 调试的方式进行测速，会影响 20%~30% 的性能。
> 
> tokenization 部分我后面会考虑支持下 batch encode。

之前可能没太描述清楚，我这边测试，在 2 卡，且 batch >= 8才能发现明显的性能差异。
单卡或者小 batch，没有发现明显的差异。
不知道你那边是什么情况下测试的。

**Comment by AllentDan** [comment]
我这边是单卡A100, 32并发。你那边可以给更详细的测试用例吗？

**Comment by sleepwalker2017** [comment]
> 我这边是单卡A100, 32并发。你那边可以给更详细的测试用例吗？

测试用例是指  测试数据吗？

**Comment by AllentDan** [comment]
就是什么模型？ 启动和测试的命令是什么样的

**Comment by sleepwalker2017** [comment]
> 就是什么模型？ 启动和测试的命令是什么样的

我测试的模型 llama-13B, 数据类型用的 fp16，启动的测试 
```shell
python -u -m lmdeploy.serve.openai.api_server workspace 0.0.0.0 10086 --instance_num 64 --tp 2
```

测试我是用 locust 设置用多用户发的请求。我看@wanzhenchn用 profile_api 也能测出来差异。

**Comment by AllentDan** [comment]
模型是怎么转的呢，转的时候tp是多少？

**Comment by sleepwalker2017** [comment]
> 模型是怎么转的呢，转的时候tp是多少？

当时就是按手册里走的流程，python3 -m lmdeploy.serve.turbomind.deploy internlm-chat-7b /path/to/internlm-chat-7b

印象中当时可能没有专门指定 tp，fp16 貌似不需要指定吧

**Comment by wanzhenchn** [comment]
> 可能没有专门指定 tp，fp16 貌似不需要指定吧

我这边设置的tp=2， fp16精度

**Comment by AllentDan** [comment]
> > 模型是怎么转的呢，转的时候tp是多少？
> 
> 当时就是按手册里走的流程，python3 -m lmdeploy.serve.turbomind.deploy internlm-chat-7b /path/to/internlm-chat-7b
> 
> 印象中当时可能没有专门指定 tp，fp16 貌似不需要指定吧

没能复现，也可能是改了和硬件相关的代码

**Comment by sleepwalker2017** [comment]
> 我想现在 main分支除了测试脚本 tokenization 部分变得很慢

ok  我们这边继续看一下   这句话能麻烦提供更多信息吗？没太看明白

```
我想现在 main分支除了测试脚本 tokenization 部分变得很慢
```

**Comment by AllentDan** [comment]
是改了下测速脚本的tokenizer，不影响后面速度的，只是脚本执行时间拉长了。PR 是这个 https://github.com/InternLM/lmdeploy/pull/443

**Comment by sleepwalker2017** [comment]
> 是改了下测速脚本的tokenizer，不影响后面速度的，只是脚本执行时间拉长了。PR 是这个 #443

ok

**Comment by wanzhenchn** [comment]
> 就是什么模型？ 启动和测试的命令是什么样的

 model: vicuna-13b-v1.5

我这边设置的tp=2， fp16精度
![image](https://github.com/InternLM/lmdeploy/assets/24476563/72bfd43f-45f0-47e2-96ba-f7663e9fae1e)

- **1卡**
    - 当前基于 0.0.9 版本测试结果如下：<img width="1557" alt="image" src="https://github.com/InternLM/lmdeploy/assets/24476563/af109f07-a14b-4956-9c6f-c54f325fcaa6">
    - 9 月初基于 commit: d5cb0be2cd1 测试
<img width="1525" alt="image" src="https://github.com/InternLM/lmdeploy/assets/24476563/9c27b7ea-6762-4af0-a214-90b675934c84">

- **2卡**
    - 当前基于 0.0.9 版本测试结果如下：<img width="1506" alt="image" src="https://github.com/InternLM/lmdeploy/assets/24476563/e3e0b533-26e7-4ebd-a1fd-4d7e67db3a83">
    - 9 月初基于 commit: d5cb0be2cd1 测试
 <img width="1023" alt="image" src="https://github.com/InternLM/lmdeploy/assets/24476563/f4f85753-3300-4296-bbec-3dd471e7266c">


### 不难发现，基于 1 卡 A100 测试，由于batch_size 最多到 2，其性能差异没有体现出来；基于 2 卡测试，当 batch_size 大于等于 4 时候，0.0.9 版本性能要比以前版本差约20%

**Comment by wanzhenchn** [comment]
> @wanzhenchn 是 V100 吧？我今天回滚都是在 A100 上进行的，32并发。我再找个 V100 复现试试，但是今天不一定有结果了，可能要过完长假。

最后写错了，是 V100，用的 profile_restful_api.py测试的。

欢迎分享 V100 测试结果~ @AllentDan

**Comment by AllentDan** [comment]
我这边用 v100 两卡跑 internlm-7b, v0.0.9 和https://github.com/InternLM/lmdeploy/commit/d5cb0be2cd16e6c5eefd4d266a38357fde83a660 ，16并发结果都是 550token/s 左右

**Comment by sleepwalker2017** [comment]
> 我这边用 v100 两卡跑 internlm-7b, v0.0.9 和[d5cb0be](https://github.com/InternLM/lmdeploy/commit/d5cb0be2cd16e6c5eefd4d266a38357fde83a660) ，16并发结果都是 550token/s 左右

OK  我这边也测一下7B   看能不能跟你对齐

**Comment by lvhan028** [comment]
Closing it since no more activities for a long time. 
Feel free to reopen it if it is still an issue.
