### ISSUE TITLE
[Bug] python3 -m lmdeploy.turbomind.chat /home/data/models/turbomind-internlm-chat-20b-w4/turbomind-internlm-chat-20b-w4 报错

### ISSUE THREAD

**Issue by macomzzl** [InternLM/lmdeploy#497]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.

### Describe the bug

<img width="1247" alt="image" src="https://github.com/InternLM/lmdeploy/assets/7599290/877ff348-05bb-4179-abb0-61e1da7088e8">

### Reproduction

python3 -m lmdeploy.turbomind.chat /home/data/models/turbomind-internlm-chat-20b-w4/turbomind-internlm-chat-20b-w4
WARNING: Can not find tokenizer.json. It may take long time to initialize the tokenizer.
[WARNING] gemm_config.in is not found; using default GEMM algo
terminate called after throwing an instance of 'std::runtime_error'
  what():  [TM][ERROR] CUDA runtime error: invalid argument /lmdeploy/src/turbomind/utils/allocator.h:253 

Aborted (core dumped)

**Comment by irexyc** [comment]
模型是从这里下载的么？https://huggingface.co/lmdeploy/turbomind-internlm-chat-20b-w4
用的什么显卡？可以修改一下这个文件https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/turbomind/chat.py#L13 改成DEBUG，看看有没有更多的信息。

**Comment by liuao743** [comment]
请问解决了吗，我也遇到了这样的问题，模型是从这里下载的，同时我修改了模式为DEBUG，没有看到更多信息。显卡是A100
