### ISSUE TITLE
baichuan w4a16 

### ISSUE THREAD

**Issue by hljjjmssyh** [InternLM/lmdeploy#501]
NORM_FCS_MAP = {
    'LlamaDecoderLayer': {
        'input_layernorm':
        ['self_attn.k_proj', 'self_attn.q_proj', 'self_attn.v_proj'],
        'post_attention_layernorm': ['mlp.gate_proj', 'mlp.up_proj']
    },
    'InternLMDecoderLayer': {
        'input_layernorm':
        ['self_attn.k_proj', 'self_attn.q_proj', 'self_attn.v_proj'],
        'post_attention_layernorm': ['mlp.gate_proj', 'mlp.up_proj']
    },
    'QWenBlock': {
        'ln_1': ['attn.c_attn'],
        'ln_2': ['mlp.w1', 'mlp.w2']
    }
}

LAYER_TYPE_MAP = {
    'InternLMForCausalLM': 'InternLMDecoderLayer',
    'QWenLMHeadModel': 'QWenBlock',
    'BaiChuanForCausalLM': 'DecoderLayer',
    'LlamaForCausalLM': 'LlamaDecoderLayer',
}

layer_type = LAYER_TYPE_MAP[type(model).__name__]
fc2fcs = FC_FCS_MAP[layer_type]

似乎baichuan 的decoder layer 无法映射

**Comment by TianzhongSong** [comment]
same problem

**Comment by hljjjmssyh** [comment]
@pppppM  hi! is there any progress on this feature? thx

**Comment by pppppM** [comment]
We have found the cause, and it will take some time to fix it

**Comment by pppppM** [comment]
@hljjjmssyh @TianzhongSong This bug has been fixed(https://github.com/InternLM/lmdeploy/pull/605 ) and the latest main branch can be used.
