### ISSUE TITLE
[Bug] 调用generate接口无返回文本

### ISSUE THREAD

**Issue by llxyw** [InternLM/lmdeploy#511]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

使用fastapi测试：
![image](https://github.com/InternLM/lmdeploy/assets/66395575/e7ba53ff-069c-461a-94b7-e837c06413f0)
Request body：{
  "prompt": "how are you?",
  "instance_id": -1,
  "sequence_start": false,
  "sequence_end": false,
  "stream": false,
  "stop": false,
  "request_output_len": 512,
  "top_p": 0.8,
  "top_k": 40,
  "temperature": 0.8,
  "repetition_penalty": 1,
  "ignore_eos": false
}
![image](https://github.com/InternLM/lmdeploy/assets/66395575/47e788c6-0699-4887-9932-3176fd1538bc)
服务端显示：
![image](https://github.com/InternLM/lmdeploy/assets/66395575/f6b8d9f7-2b3b-45b9-87b6-0087d242974c)

### Reproduction

python3 -m lmdeploy.serve.openai.api_server ./workspace 0.0.0.0 8090 --instance_num 32 --tp 1

**Comment by llxyw** [comment]
使用的baichuan2-7B模型

**Comment by AllentDan** [comment]
对话长度超了，instance_id 设置成别的吧。或者继续保持用-1，但是 sequence_end 设置为 True以后再重新对话
