### ISSUE TITLE
[Bug] llama2-13B模型，首token计算逻辑疑问

### ISSUE THREAD

**Issue by sjzhou4** [InternLM/lmdeploy#512]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

测试发现，llama2-13B的模型，设置max_tokens = 1，也即只生成一个token的情况下，会运行 1次[decodeContext] + 2次 [generate]。
理解如下：
1次decodeContext中将prompt tokens -1进行decodeContext，结果却不用；
2次generate中，第1次是词表id = 29871的'_'，可以认为是起始符；第2次generate才是max_tokens = 1真正的generate token；
疑问点：
1次decodeContext中如果将prompt tokens进行decodeContext时应该直接能出词表id = 29871的'_'，此时再做一次generate即可以生成max_tokens = 1真正的generate token。这样看，上述的理解中就多了一次generate的时间，有性能损耗。

### Reproduction

![image](https://github.com/InternLM/lmdeploy/assets/142190228/2318af14-0e56-4e4e-ba63-f2f197eb7c2c)

**Comment by mokeyish** [comment]
Llama-2-13b-chat-hf 也跑不了，报错
