### ISSUE TITLE
[Bug] 部署internlm-chat-20b出现问题

### ISSUE THREAD

**Issue by sunny20060815** [InternLM/lmdeploy#514]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

(E:\AI\lmdeploy\env) E:\AI\lmdeploy>python -m lmdeploy.serve.turbomind.deploy internlm-chat-20b "E:\AI\lmdeploy\internlm20b"
create workspace in directory ./workspace
copy triton model templates from "E:\AI\lmdeploy\env\Lib\site-packages\lmdeploy\serve\turbomind\triton_models" to "./workspace\triton_models" successfully
tokenizer model E:\AI\lmdeploy\internlm20b\tokenizer.model does not exist
我下载的lmdeploy/turbomind-internlm-chat-20b-w4，来自https://huggingface.co/lmdeploy/turbomind-internlm-chat-20b-w4/tree/main我文件都下了但说缺少tokenizer.model does not exist

### Reproduction

python -m lmdeploy.serve.turbomind.deploy internlm-chat-20b "E:\AI\lmdeploy\internlm20b"

**Comment by vansin** [comment]
https://huggingface.co/lmdeploy/turbomind-internlm-chat-20b-w4

是已经通过 `python -m lmdeploy.serve.turbomind.deploy` 转换的模型，不需要再deploy，可以直接运行了 gradio demo 了


```
python3 -m lmdeploy.serve.gradio.app ./workspace --server_name 127.0.0.1 --server_port 8888
```

**Comment by sunny20060815** [comment]
(E:\AI\lmdeploy\env) E:\AI\lmdeploy>python -m lmdeploy.serve.gradio.app ./workspace --server_name 127.0.0.1 --server_port 8888
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\AI\lmdeploy\env\Lib\site-packages\lmdeploy\serve\gradio\app.py", line 541, in <module>
    fire.Fire(run)
  File "E:\AI\lmdeploy\env\Lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\lmdeploy\env\Lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\lmdeploy\env\Lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\lmdeploy\env\Lib\site-packages\lmdeploy\serve\gradio\app.py", line 536, in run
    run_local(model_path_or_server, server_name, server_port, batch_size,
  File "E:\AI\lmdeploy\env\Lib\site-packages\lmdeploy\serve\gradio\app.py", line 461, in run_local
    InterFace.async_engine = AsyncEngine(model_path=model_path,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\lmdeploy\env\Lib\site-packages\lmdeploy\serve\async_engine.py", line 32, in __init__
    from lmdeploy import turbomind as tm
  File "E:\AI\lmdeploy\env\Lib\site-packages\lmdeploy\turbomind\__init__.py", line 3, in <module>
    from .turbomind import TurboMind
  File "E:\AI\lmdeploy\env\Lib\site-packages\lmdeploy\turbomind\turbomind.py", line 22, in <module>
    import _turbomind as _tm  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing _turbomind: 找不到指定的模块。

**Comment by vansin** [comment]
请展示`E:\AI\lmdeploy` 路径的文件夹

请问 lmdeploy 是怎么安装的？
请问是否有 git clone lmdeploy  源码

**Comment by sunny20060815** [comment]
我就是用miniconda创建了一个python3.11.4的环境，然后pip install lmdeploy，然后去huggingface上下了模型

**Comment by sunny20060815** [comment]
(E:\AI\lmdeploy\env) E:\AI\lmdeploy>pip show lmdeploy
Name: lmdeploy
Version: 0.0.9
Summary: A toolset for compressing, deploying and serving LLM
Home-page:
Author: OpenMMLab
Author-email: openmmlab@gmail.com
License:
Location: E:\AI\lmdeploy\env\Lib\site-packages
Requires: accelerate, datasets, fastapi, fire, gradio, mmengine, numpy, pybind11, safetensors, sentencepiece, setuptools, shortuuid, tiktoken, torch, transformers, tritonclient, uvicorn
Required-by:

**Comment by vansin** [comment]
在 `E:\AI\` 路径下面运行 `python -m lmdeploy.serve.gradio.app ./workspace --server_name 127.0.0.1 --server_port 8888`吧


./workspace 需要换成下载下来的绝对路径

**Comment by vansin** [comment]
@sunny20060815 请问用的GPU 是什么型号的？ 执行一下 `nvidia-smi`

**Comment by sunny20060815** [comment]
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 537.42                 Driver Version: 537.42       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090      WDDM  | 00000000:01:00.0  On |                  Off |
|  0%   38C    P5              56W / 450W |   2940MiB / 24564MiB |      1%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1208    C+G   C:\Windows\System32\dwm.exe               N/A      |
|    0   N/A  N/A      1252    C+G   ...\cef\cef.win7x64\steamwebhelper.exe    N/A      |
|    0   N/A  N/A      2428    C+G   ...__k6txddmbb6c52\Steam++\Steam++.exe    N/A      |
|    0   N/A  N/A      3196    C+G   ...ys\WinUI3Apps\PowerToys.Peek.UI.exe    N/A      |
|    0   N/A  N/A      4824    C+G   ...\PowerToys\PowerToys.FancyZones.exe    N/A      |
|    0   N/A  N/A      5264    C+G   ...werToys\PowerToys.ColorPickerUI.exe    N/A      |
|    0   N/A  N/A      6600    C+G   ...5n1h2txyewy\ShellExperienceHost.exe    N/A      |
|    0   N/A  N/A      7964    C+G   ....5185.0_x64__8j3eq9eme6ctt\IGCC.exe    N/A      |
|    0   N/A  N/A      8168    C+G   C:\Windows\explorer.exe                   N/A      |
|    0   N/A  N/A     11468    C+G   ...__8wekyb3d8bbwe\WindowsTerminal.exe    N/A      |
|    0   N/A  N/A     14340    C+G   ...GeForce Experience\NVIDIA Share.exe    N/A      |
|    0   N/A  N/A     15060    C+G   ...nt.CBS_cw5n1h2txyewy\SearchHost.exe    N/A      |
|    0   N/A  N/A     15136    C+G   ...2txyewy\StartMenuExperienceHost.exe    N/A      |
|    0   N/A  N/A     15868    C+G   ...on\117.0.2045.43\msedgewebview2.exe    N/A      |
|    0   N/A  N/A     16380    C+G   ...siveControlPanel\SystemSettings.exe    N/A      |
|    0   N/A  N/A     16708    C+G   ...werToys\PowerToys.PowerLauncher.exe    N/A      |
|    0   N/A  N/A     17536    C+G   ...CBS_cw5n1h2txyewy\TextInputHost.exe    N/A      |
|    0   N/A  N/A     17940    C+G   ...on\117.0.2045.43\msedgewebview2.exe    N/A      |
|    0   N/A  N/A     19428    C+G   ...GeForce Experience\NVIDIA Share.exe    N/A      |
|    0   N/A  N/A     20364    C+G   ...crosoft\Edge\Application\msedge.exe    N/A      |
|    0   N/A  N/A     21848    C+G   ...\iCloud\WebView2\msedgewebview2.exe    N/A      |
+---------------------------------------------------------------------------------------+

**Comment by irexyc** [comment]
@sunny20060815 

系统中是否安装了cuda toolkit?，可以打印一下变量试试。 `echo $env:CUDA_PATH`

**Comment by gesanqiu** [comment]
`pip install lmdepoly`安装的包可以正常找到`_turbomind`依赖。
但假如这时我再去`pip install -e .`，就会出现：ModuleNotFoundError: No module named '_turbomind'，需要卸载重装才能正常运行。
假如我想修改lmdeploy的python部分代码并且让它即时生效，是需要从源码编译一次吗？

**Comment by irexyc** [comment]
@gesanqiu

目前不支持 pip install -e . 来编译

你可以直接修改安卓目录下的lmdeploy python代码，或者你把安装目录中的lib文件夹拷贝过来之后再 pip install -e .

**Comment by 77h2l** [comment]
@irexyc ModuleNotFoundError: No module named '_turbomind'  这个bug不管是用pip 安装还是在docker镜像里面执行都存在

**Comment by irexyc** [comment]
@77h2l 

你先试一下在`_turbomind.cpython-3x-x86_64-linux-gnu.so`这个文件所在的目录下能不能import成功。

可以通过下面的命令找:
```
python -c 'import lmdeploy; print(lmdeploy)'
'/home/chenxin/ws3/lmdeploy/lmdeploy/__init__.py'>
# 那么目录应该是/home/chenxin/ws3/lmdeploy/lmdeploy/lib
```

如果可以import的话那么应该依赖应该是满足的，你的问题可能是在git clone下来的lmdeploy目录下执行命令导致的。

不能import的话，可以通过ldd看一下_turbomind.cpython-3x-x86_64-linux-gnu.so的依赖
