### ISSUE TITLE
[Bug] internlm-chat-20-4bit运行时回答乱码

### ISSUE THREAD

**Issue by deku0818** [InternLM/lmdeploy#518]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

![image](https://github.com/InternLM/lmdeploy/assets/84755119/9cf79aae-94a2-4ba8-bae7-2f478c4f14f8)

### Reproduction

python3 -m lmdeploy.serve.turbomind.deploy internlm-chat   --model-path ./internlm-chat-20b-4bit  --model-format awq     --group-size 128

**Comment by Tushar-ml** [comment]
I am facing the same issue

**Comment by Tushar-ml** [comment]
It got solved for me, it is basically fault of nvidia architecture you are using. Check Cuda device capability by `torch.cuda.get_device_capability()`, if it is greater or equal to 8.0, then it will work perfectly

**Comment by lvhan028** [comment]
@deku0818 just as @Tushar-ml suggested, 4bit inference requires the capability of nvidia arch no less than 80.
