### ISSUE TITLE
Add Support for mistra-7b Deployment

### ISSUE THREAD

**Issue by adithya-s-k** [InternLM/lmdeploy#524]
### Motivation

Mistral 7b is outperforming Llama 13b in a lot of bench marks.

### Related resources

https://mistral.ai/news/announcing-mistral-7b/

**Comment by lvhan028** [comment]
@irexyc please investigate this model and check if it can be fitted into turbomind

**Comment by lvhan028** [comment]
LMDeploy has supported it since v0.2.5
