### ISSUE TITLE
kv cache int8 seems not benefit the throughput

### ISSUE THREAD

**Issue by Tengxu-Sun** [InternLM/lmdeploy#525]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

We have benchmark the int8 kv cache mode according to the [docs](https://github.com/InternLM/lmdeploy/blob/main/docs/en/kv_int8.md). However it seems not benefit the throughput.

# Setting:
- llama 13B
- A800
- cuda 11.8
- tp = 1

# Test result:

| test mode | bs | inp_len | out_len | total latency| throughput (tokens/s) |
|----- | ----- | ----- | ----- | ----- | ----- |
| fp16 kv cache | 1 | 2048 | 512 | 11.20s | 228.571 |
| int8 kv cache | 1 | 2048 | 512 | 12.03 | 212.801 |
| fp16 kv cache | 25 | 2048 | 512 | 35.81s | 1787.210 |
| int8 kv cache | 35 | 2048 | 512 | 56.23s  | 1593.455 |

Under the same batch size = 1. It's easier to explain that the int8 kv cache mode need to do the quantization and de-quantization process, so the throughput degrade. 
However, with int8 kv cache mode, we can set the batch size larger(35 vs 25). Normally, this should help improve throughput. Personally I think this is also the meaning of kv cache quantization. The final testing result is not as expected. Is there any help to explain this or fix this?

Thanks a lot!

</div>

### Reproduction

Just as the docs said https://github.com/InternLM/lmdeploy/tree/main/benchmark#profile-without-dataset and https://github.com/InternLM/lmdeploy/blob/main/docs/en/kv_int8.md

**Comment by wanzhenchn** [comment]
Which version of LMDeploy used? I have found the same phenomenon @Tengxu-Sun

**Comment by Tengxu-Sun** [comment]
I cloned this repo and installed it locally. Its commit id is e68a1d00c4135a64eacd083827a52e6ae13b4106. And 'pip show lmdeploy’ shows Version: 0.0.5. I think the version may be not have much influence with the conclusion. 


| |
电信1804班-21860235-孙腾许
|
|
***@***.***
|
签名由网易邮箱大师定制


On 10/10/2023 ***@***.***> wrote：

Which version of LMDeploy used? I have found the same phenomenon @Tengxu-Sun

**Comment by lzhangzz** [comment]
The code for int8_t -> float conversion is far from optimal in the current version. 

An optimized version will be released soon. Stay tuned.

**Comment by Tengxu-Sun** [comment]
> The code for int8_t -> float conversion is far from optimal in the current version.
> 
> An optimized version will be released soon. Stay tuned.

Will the new optimized  version benefit token throughput with kv cache int8?

**Comment by lvhan028** [comment]
LMDeploy supported online 4-bit/8-bit kv cache quantization since v0.4.0
The token throughput with 8-bit kv cache achieves about 1.27x than the unquantized kv cache
