### ISSUE TITLE
[Question]使用Triton inference server部署，如何进行http访问，非grpc 

### ISSUE THREAD

**Issue by wjj19950828** [InternLM/lmdeploy#527]
### Motivation

您好，现在用triton inference server部署llama2

请问下目前能否支持http请求呢，是不是还缺一个ensamble，所以现在没办法直接通过request.post进行访问？

感谢～

**Comment by lvhan028** [comment]
可以参考 `restful_api.md` 使用 http server。它提供了类似openai的 RESTful API

lmdeploy没有封装tritonclient的http接口。
