### ISSUE TITLE
[Bug] 他的回答胡言乱语，一顿乱说，使用的是RTX A5000 * 5卡

### ISSUE THREAD

**Issue by thb10086** [InternLM/lmdeploy#528]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

![image](https://github.com/InternLM/lmdeploy/assets/68690699/390b2e34-39fe-49a6-ba10-00d8a272d328)
他的回复一顿胡言乱语。

### Reproduction

执行的命令是：
python3 -m lmdeploy.serve.turbomind.deploy internlm-chat-20b ./internlm-20b   

nohup python3 -m lmdeploy.serve.openai.api_server ./workspace 127.0.0.1 6006 --instance_num 32 --tp 5 > apiui.log 2>&1 &

### Error traceback

```Shell
日志消息：nohup: ignoring input
[WARNING] gemm_config.in is not found; using default GEMM algo
[WARNING] gemm_config.in is not found; using default GEMM algo
[WARNING] gemm_config.in is not found; using default GEMM algo
[WARNING] gemm_config.in is not found; using default GEMM algo
[WARNING] gemm_config.in is not found; using default GEMM algo
WARNING: Can not find tokenizer.json. It may take long time to initialize the tokenizer.
INFO:     Started server process [13144]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:6006 (Press CTRL+C to quit)
INFO:     127.0.0.1:40206 - "GET / HTTP/1.1" 200 OK
```

**Comment by thb10086** [comment]
谁来解决一下我的问题，之前运行一直好好的，从昨天开始突然变成这样了，已经重新拉取模型部署还是一样的 胡说八道

**Comment by thb10086** [comment]
help me 在线等，求大佬解答

**Comment by lvhan028** [comment]
确定用的是chat模型，而不是基座模型不？

**Comment by thb10086** [comment]
@lvhan028 是使用的chat模型，没有使用基座模型
![image](https://github.com/InternLM/lmdeploy/assets/68690699/c60446d7-8698-43fb-a98e-67bf739c3e99)

**Comment by thb10086** [comment]
@lvhan028 先执行了python3 -m lmdeploy.serve.turbomind.deploy internlm-chat-20b ./internlm-chat-20b
然后nohup python3 -m lmdeploy.serve.openai.api_server ./workspace 127.0.0.1 6006 --instance_num 32 --tp 5 > apiui.log 2>&1 & 。启动成功了，但是他的回复是乱的
![image](https://github.com/InternLM/lmdeploy/assets/68690699/4034a913-3e4c-42f1-a8ef-6b101f112fe8)

**Comment by thb10086** [comment]
我一个简单问题，五个卡都跑满了
![image](https://github.com/InternLM/lmdeploy/assets/68690699/2e8341a9-fb86-43f3-9764-de6f7e413f27)

**Comment by maxchiron** [comment]
不用nohup的话正常吗？

**Comment by thb10086** [comment]
@maxchiron 模型没有微调，不用nohup一样的胡说八道。上面有写输入的命令。突然就这样了。之前还是好好的

**Comment by maxchiron** [comment]
> @maxchiron 模型没有微调，不用nohup一样的胡说八道。上面有写输入的命令。突然就这样了。之前还是好好的

同样的部署步骤，换-chat-7b的话呢？

**Comment by maxchiron** [comment]
我之前遇到类似的回复是出现在微调基座模型微调不充分时发生的。不知道是否与你的问题有关系。

**Comment by thb10086** [comment]
@maxchiron 一开始我用的是基座模型，后面改为chat模型了还是一样的

**Comment by lvhan028** [comment]
使用tensor parallel的话，强烈建议用 2^n。1,2,4,8这样的数。

**Comment by fadai1129-github** [comment]
tp不支持5，可能作者觉得这特么还能有人不懂

**Comment by maxchiron** [comment]
学习了，这我还真不懂😂
