### ISSUE TITLE
[Feature] INT 4推理能支持 SM70 吗

### ISSUE THREAD

**Issue by sleepwalker2017** [InternLM/lmdeploy#530]
### Motivation

看到 INT4 要求SM80 及以上，想问下为什么会有这个限制，是需要了什么新特性吗？

**Comment by lzhangzz** [comment]
暂时还不支持，主要是sm70 tensor core的layout和sm80不一样，目前的框架兼容起来比较麻烦

**Comment by sleepwalker2017** [comment]
> 暂时还不支持，主要是sm70 tensor core的layout和sm80不一样，目前的框架兼容起来比较麻烦

好的了解。我这边在 A30 测试了 INT4 的性能，在小 batch 下，int4性能明显好很多。但是 batch较大时，INT4 性能反而不如 fp16。这个符合你们的预期吗？我翻了翻，好像没看到你们在多 batch 下的 benchmark。

![image](https://github.com/InternLM/lmdeploy/assets/26128514/5c448a2a-157e-4995-ab7d-19db085415e8)
![image](https://github.com/InternLM/lmdeploy/assets/26128514/613f2f63-0955-4ba5-aeec-685b2de59be7)

**Comment by lzhangzz** [comment]
int4 GEMM的kernel选择策略是在A100和4090上调的，其他卡上自动pick的kernel有可能不是最优的，后面还是要加一下kernel tuning之类的优化。

#202 里面有A100上大batch的througput

**Comment by sleepwalker2017** [comment]
> int4 GEMM的kernel选择策略是在A100和4090上调的，其他卡上自动pick的kernel有可能不是最优的，后面还是要加一下kernel tuning之类的优化。
> 
> #202 里面有A100上大batch的througput

ok 了解。目前llama_gemm 这个工具不支持量化后的调优是吗？我看支持的就是 FP16 和 FP32、

**Comment by lzhangzz** [comment]
> 目前llama_gemm 这个工具不支持量化后的调优是吗？我看支持的就是 FP16 和 FP32、

对目前还没有支持

**Comment by sleepwalker2017** [comment]
> > 目前llama_gemm 这个工具不支持量化后的调优是吗？我看支持的就是 FP16 和 FP32、
> 
> 对目前还没有支持

好的  看起来是在 cublas 之外另外实现的int4 * fp16的矩阵乘是吗？
请教下   这个名字是什么意思？ GemmS4F16

**Comment by sleepwalker2017** [comment]
> > GemmS4F16
> 
> Signed-4 x Float-16

好的 感谢

**Comment by xiaoxiangshusheng** [comment]
针对量化情况，请问这里指的kernel tuning是指编译的时候，对如下kernel的选择么
![image](https://github.com/InternLM/lmdeploy/assets/56901843/456fbf7e-cbd1-41a3-a9cb-dbfbbbdbfdc4)
