### ISSUE TITLE
[Bug]  lmdeploy.serve.gradio.app 不能多client并行

### ISSUE THREAD

**Issue by Rane2021** [InternLM/lmdeploy#531]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

使用 python -m lmdeploy.serve.gradio.app restful_api_url server_ip --restful_api True 构建多个client 不能并行，主要原因是不能像 python -m lmdeploy.serve.openai.api_client restful_api_url 一样可以设置 session_id, 建议在 lmdeploy.serve.gradio.app.p y 添加 session_id 参数配置，这样可以保证多个client 并行

### Reproduction

python -m lmdeploy.serve.gradio.app restful_api_url server_ip --restful_api True

**Comment by lvhan028** [comment]
能不能提个PR上来呢？
