### ISSUE TITLE
并发度上去后，turbomind queue里有很多一样的output，很大程度影响性能

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#533]
使用http服务，并发度设置为10，开启streaming。发现队列中有很多一样的output，这样在turboMindInstance里需要多次get，导致整体服务时间变慢。请问这是什么原因？

很诡异的一点是，我在self.que.put前打日志，put的内容是期望中的。但在self.que.get前打日志，最后一个token会取出很多相同的元素。

个人推测，可能是因为用于decode的c++线程访问queue时没加GIL锁，这里可能存在线程安全问题，导致结果的错乱。

**Comment by frankxyy** [comment]
https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/turbomind/turbomind.py#L338

代码里这一行，每次只取队列的最后一个元素，清除其它元素。这样的做法，用意是什么呢？  感觉不需要清除其他元素？

**Comment by AllentDan** [comment]
队列里存的数据解码后类似下面的金字塔结构：
```
你
你好
你好！
你好！请
```
只要返回最后一条数据就可以

**Comment by frankxyy** [comment]
@AllentDan 
hi，我遇到的情况是，并发度变大后，队列中存在很多相同的元素，比如有60个 "你好！请" ，在并发1并未有此种情况。 这种情况下，很影响整个的inference性能。如果我把_forward_callback里的self.que.put注释掉，最终速度会快很多

我把que.get取出来的output打印出来像这样:
<img width="1440" alt="image" src="https://github.com/InternLM/lmdeploy/assets/6971044/8cc675b6-141c-49bc-bcd0-48591f374492">

**Comment by AllentDan** [comment]
这不能看出来就一样啊，打印只显示了头尾，头尾一样正常啊，头部有相同的 instruction，尾部是padding的 0

**Comment by frankxyy** [comment]
@AllentDan sequence_length，实际log文件里，重复了3000次。

**Comment by AllentDan** [comment]
那你打印了这个 tensor 的长度没？

**Comment by frankxyy** [comment]
@AllentDan 没必要吧？ sequence_length应该能反映情况了？ 形状，由于有padding，应该都一样吧

**Comment by frankxyy** [comment]
@AllentDan 我感觉是线程安全问题，我在self.que.put前 sleep 一下， get出来的结果，就有变化了

**Comment by AllentDan** [comment]
所以没事了？没有我关issue了？

**Comment by frankxyy** [comment]
@AllentDan 线程安全问题，要处理下哈，严重影响较大并发下的性能

**Comment by AllentDan** [comment]
是怎么使用http多并发的？http返回的对话内容呢？

**Comment by frankxyy** [comment]
> 是怎么使用http多并发的？http返回的对话内容呢？

@AllentDan 测试脚本在: https://drive.google.com/file/d/1LvszlBPr4ek7a_oJQfoAAkkBuZJjVcJj/view?usp=sharing 。  返回的文本结果是正确的哈。就是输出最后一个token后，会卡住很久。

**Comment by frankxyy** [comment]
> 不是很理解，输出结束后，还卡住了。卡在哪？

@AllentDan   Hi，准确来说是，客户端接收到最后一个非空token后，会拿到很多空token。应该是由于队列里出现了很多完全相同的output导致的。   

总之就是影响性能，不开启streaming，直接只从队列拿最终整个的结果，速度快不少

**Comment by AllentDan** [comment]
@lzhangzz 我们可以计算过程结束后应该不会有很长时间的等待吧

**Comment by irexyc** [comment]
@frankxyy 

往队列里面put的时候“内容"是金字塔结构的，sequence_length 依次递增的。但是每次返回的 output_ids/sequence_length 使用的是相同的cuda地址，每次put其实就相当于在这个地址上刷新最新的结果。这样就会造成如果队列get的速度比put慢，会出现队列中的结果都是一样的，所以只取队列中最后一个元素。

你在[这一行](https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/turbomind/turbomind.py#L342)后面time.sleep(1)，然后再打印 output 就会发现结果跟 342 行的会不一样。而你在 self.que.put 之前 sleep 相当于减弱put的速度，这里不是什么线程安全的原因。

之前有优化过多线程下callback GIL争抢的问题，不过算上callback的时间，多线程下还是有一些时间没搞清楚消耗在哪了。不开 streaming ，多线程下的话速度确实会快一些。

> 就是输出最后一个token后，会卡住很久。

这个没get到你的意思

**Comment by frankxyy** [comment]
@irexyc 感谢回答哈，可能我之前的分析也是有问题，我这边空下来再研究研究

**Comment by frankxyy** [comment]
> @frankxyy
> 
> 往队列里面put的时候“内容"是金字塔结构的，sequence_length 依次递增的。但是每次返回的 output_ids/sequence_length 使用的是相同的cuda地址，每次put其实就相当于在这个地址上刷新最新的结果。这样就会造成如果队列get的速度比put慢，会出现队列中的结果都是一样的，所以只取队列中最后一个元素。
> 
> 你在[这一行](https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/turbomind/turbomind.py#L342)后面time.sleep(1)，然后再打印 output 就会发现结果跟 342 行的会不一样。而你在 self.que.put 之前 sleep 相当于减弱put的速度，这里不是什么线程安全的原因。
> 
> 之前有优化过多线程下callback GIL争抢的问题，不过算上callback的时间，多线程下还是有一些时间没搞清楚消耗在哪了。不开 streaming ，多线程下的话速度确实会快一些。

@irexyc Hi，想问下现在开启与不开启streaming（不开启async_engine.generate的streaming），还会存在性能差异吗？ 我之前用triton server对比了下，好像现在开启streaming也不会有速度下降了，不知道这块后来是怎么修复的呢
