### ISSUE TITLE
Implementation of NTK scaling

### ISSUE THREAD

**Issue by GxjGit** [InternLM/lmdeploy#536]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

The implementation of rotary_embedding_get_base of NTK is as following:

 inline __device__ float
rotary_embedding_get_base(float seq_len, int max_position_embeddings, float rot_embed_dim, float base)
{
    if (seq_len < max_position_embeddings) {
        return base;
    }
    float ntk_alpha = max(exp2f(ceilf(log2f(seq_len / max_position_embeddings) + 1.f)) - 1.f, 1.f);
    base *= powf(ntk_alpha, rot_embed_dim / (rot_embed_dim - 2.f));
    return base;
}

// inline __device__ float
// rotary_embedding_get_base(float seq_len, int max_position_embeddings, float rot_embed_dim, float base)
// {
//     constexpr float scaling_factor = 1.f;
//     if (scaling_factor * seq_len < max_position_embeddings) {
//         return base;
//     }
//     base *= powf((scaling_factor * seq_len / max_position_embeddings) - (scaling_factor - 1.f),
//                  rot_embed_dim / (rot_embed_dim - 2.f));
//     return base;
// }

But the commented code is consistent with that of transformers instead. 

I'm wondering why you used the algorithm used in the code and not the one in the comments section. Can you introduce the source or principle of the algorithm?

### Reproduction

NO

**Comment by lzhangzz** [comment]
Current implenetation was added to support Qwen-7B, which uses different logic for [computing the scaling factor](https://huggingface.co/Qwen/Qwen-7B-Chat/blob/de5bfb782c802c048f75dcbf8af171a2ccacae24/modeling_qwen.py#L779).

We will add options to allow direct control on scaling factor in the future.
