### ISSUE TITLE
generate API response null in swaggerUI

### ISSUE THREAD

**Issue by maxchiron** [InternLM/lmdeploy#537]
## precondision
```
# lmdeploy intern-chat-7b by RestfulAPI method
python3 -m lmdeploy.serve.openai.api_server ./workspace server_ip server_port --instance_num 32 --tp 1

# Enter swaggerUI
http://{server_ip}:{server_port}
```

## issue
**In generate part, response body returns null in key "text"**
> , while the /v1/chat/completions, /models, /embedding APIs are all fine.
> btw, it is tested through ngrok public url cause the localhost is in indirectly unaccessable subnet.

![image](https://github.com/InternLM/lmdeploy/assets/85681332/7dd12cc2-2817-49d8-8cb3-47efaa466344)
![image](https://github.com/InternLM/lmdeploy/assets/85681332/8683dd0e-aea0-46d1-b2cb-8b3e0f8167be)
![image](https://github.com/InternLM/lmdeploy/assets/85681332/ce28e7a2-ccc3-47bf-beec-90d27a4a83a8)

**Comment by maxchiron** [comment]
> FAQ 3 https://github.com/InternLM/lmdeploy/blob/main/docs/en/restful_api.md#faq

Same issue. 
But I tried the python implement of /generate API and run in cli. It returns contents instead of null.

**Comment by AllentDan** [comment]
You were running on an old session_id. Please set sequence_end = True first.

**Comment by AllentDan** [comment]
[chat.py](https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/turbomind/chat.py) shows how a session should be started and ended.

**Comment by maxchiron** [comment]
> You were running on an old session_id. Please set sequence_end = True first.

Thank you very much. It works fine. Is there any docs about ```sequence_start``` and ```sequence_end``` ? I want to know more. Thanks for the patience and speed~

**Comment by AllentDan** [comment]
I suppose the docstring explains something. We will provide more detailed documents or cookbooks later.

**Comment by AllentDan** [comment]
I will update it with a detailed description.
