### ISSUE TITLE
[Question] /generate API returns in multiple formats.

### ISSUE THREAD

**Issue by maxchiron** [InternLM/lmdeploy#538]
## Precondition
```
# Get InternLM-chat-7B
git clone https://huggingface.co/internlm/internlm-chat-7b /path/to/internlm-chat-7b

# To turbomind
python3 -m lmdeploy.serve.turbomind.deploy internlm-chat-7b

# Deploy by RustAPI
python3 -m lmdeploy.serve.openai.api_server ./workspace server_ip server_port --instance_num 32 --tp 1
```
### Use official /generate template python script.
[https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/restful_api.md](https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/restful_api.md)

#### Examples
![janYJcGI1z2yAut.png](https://s2.loli.net/2023/10/10/janYJcGI1z2yAut.png)
![KmCB5zgF2VUcDfw.png](https://s2.loli.net/2023/10/10/KmCB5zgF2VUcDfw.png)
![3jbzgQqrSx7htFC.png](https://s2.loli.net/2023/10/10/3jbzgQqrSx7htFC.png)

## Issues or Questions
1. Why model response in multiple format? As the examples showing, it generates in <|User|><|Bot|> like format and text-only format.
2. What the <eoh><|User|><|Bot|> exactly mean? And what the reasons of these tags been generated? 
3. How can I control the format(point 1 mentioned) of the responses?
4. In the format with tags, I realize that my original input seems been digested first. How this process happen and what's the mechanism? How can I control it?

**Comment by maxchiron** [comment]
And this is yet another example with WRONG digestion of the original input. Don't know how to deal with it yet.
![image](https://github.com/InternLM/lmdeploy/assets/85681332/6d4408ac-e3b1-4063-9169-6a47d973385a)

**Comment by AllentDan** [comment]
May try https://huggingface.co/internlm/internlm-chat-7b-v1_1

**Comment by maxchiron** [comment]
> May try https://huggingface.co/internlm/internlm-chat-7b-v1_1

Comfortable😄~ These three question got clean output in v1_1. Awesome. I will keep testing. Thanks for your general distribution~

**Comment by AllentDan** [comment]
This issue is closed. Please open a new issue if you have similar issues or if you have any new updates.
