### ISSUE TITLE
[Bug] SIGABRT

### ISSUE THREAD

**Issue by hatrexltd** [InternLM/lmdeploy#540]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

The inference server does not support many requests launched at the same time (not quantified) (OpenAI, InternLM 20B, 2req/s)

When several requests are launched in the same second, the program stops SIGABRT. The bug has always been there on lmdeploy.

### Reproduction

python3 -m lmdeploy.serve.openai.api_server ./workspace 0.0.0.0 6000 --instance_num 32 --tp 1

**Comment by AllentDan** [comment]
How did you launch many requests at the same time? Please provide more details.

**Comment by hatrexltd** [comment]
import asyncio
import aiohttp
import time

async def send_request(session, url, data, headers):
    try:
        start_time = time.time()
        async with session.post(url, json=data, headers=headers) as response:
            if response.status == 200:
                end_time = time.time()
                duration = end_time - start_time
                print(f"Request sent successfully in {duration:.2f} seconds")
            else:
                print(f"Request failed with status code: {response.status}")
    except Exception as e:
        print(f"Error: {str(e)}")

async def main():
    url = 'http://IP:8080/v1/chat/completions'
    
    headers = {
        'Content-Type': 'application/json',
    }

    data = {
        "model": "internlm-chat-20b", (same issue with llama 70b)
        "messages": [
            {"role": "user", "content": "Tell me about France"}
        ],
        "max_tokens": 672,
        "temperature": 0.8,
        "n": 1,
        "top_p": 1,
        "stream": False,
        "renew_session": True,
        "do_sample": True
    }

    async with aiohttp.ClientSession() as session:
        while True:
            asyncio.create_task(send_request(session, url, data, headers))
            await asyncio.sleep(0.3)  # Attendre 500 ms avant de planifier la prochaine requête

if __name__ == "__main__":
    asyncio.run(main())

Note: I modified the code so that the instance_id changes, but even without the modification I have the same problem. The problem also seems to be on Llama 70B, I don't think it's a problem at the model level.
With /generate, same problem.

**Comment by hatrexltd** [comment]
Moreover, on lightllm for example we can ensure that the model uses all the RAM. On Lmdeploy, the model is loaded but the VRAM of the GPUs is not completely used, is there a parameter like max_total_token_num?
"The parameter max_total_token_num is influenced by the GPU memory of the deployment environment. A larger value for this parameter allows for the processing of more concurrent requests, thereby increasing system concurrency. For more startup parameters, please refer to api_server.py or ApiServerArgs.md ." from lightllm

**Comment by hatrexltd** [comment]
0|triton1  | Thread 0x00007f10517fa640 (most recent call first):
0|triton1  |   File "/root/miniconda3/envs/trit/lib/python3.9/site-packages/lmdeploy/turbomind/turbomind.py", line 201 in _func
0|triton1  |   File "/root/miniconda3/envs/trit/lib/python3.9/threading.py", line 917 in run
0|triton1  |   File "/root/miniconda3/envs/trit/lib/python3.9/threading.py", line 980 in _bootstrap_inner
0|triton1  |   File "/root/miniconda3/envs/trit/lib/python3.9/threading.py", line 937 in _bootstrap
0|triton1  | Thread 0x00007f1051ffb640 (most recent call first):
0|triton1  |   File "/root/miniconda3/envs/trit/lib/python3.9/site-packages/lmdeploy/turbomind/turbomind.py", line 201 in _func
0|triton1  |   File "/root/miniconda3/envs/trit/lib/python3.9/threading.py", line 917 in run
0|triton1  |   File "/root/miniconda3/envs/trit/lib/python3.9/threading.py", line 980 in _bootstrap_inner
0|triton1  |   File "/root/miniconda3/envs/trit/lib/python3.9/threading.py", line 937 in _bootstrap
0|triton1  | Thread 0x00007f1050ff9640 (most recent call first):
0|triton1  |   File "/root/miniconda3/envs/trit/lib/python3.9/site-packages/lmdeploy/turbomind/turbomind.py", line 201 in _func
0|triton1  |   File "/root/miniconda3/envs/trit/lib/python3.9/threading.py", line 917 in run
0|triton1  |   File "/root/miniconda3/envs/trit/lib/python3.9/threading.py", line 980 in _bootstrap_inner
0|triton1  |   File "/root/miniconda3/envs/trit/lib/python3.9/threading.py", line 937 in _bootstrap
0|triton1  | Thread 0x00007f10527fc640 (most recent call first):

**Comment by AllentDan** [comment]
`/v1/chat/completion` can only respond a request one by one if all requests are launched with a same ip address.

**Comment by AllentDan** [comment]
I am working on disabling interactive mode of `/v1/chat/completion`, you may try my [branch](https://github.com/AllentDan/lmdeploy/tree/infilling-completion) if you are in a hurry.

**Comment by hatrexltd** [comment]
> `/v1/chat/completion` can only respond a request one by one if all requests are launched with a same ip address.

The error also occurs with /generate unfortunately, even with a random instance_id.

**Comment by hatrexltd** [comment]
W4A16 quantization allows 2-3x more requests in a period of time, before crashing than without quantization elsewhere

**Comment by AllentDan** [comment]
LMDeploy does not use all the VRAM of your GPUS when launching the service. However, as the number of requests increases, LMDeploy may increase the VRAM usage. You can set the `--instance_num` to determine how many turbomind instances may get created and this is how we control the VRAM usage.

Check the second [FAQ](https://github.com/InternLM/lmdeploy/blob/main/docs/en/restful_api.md#faq).
