### ISSUE TITLE
[Question] About Rotary Embedding style 

### ISSUE THREAD

**Issue by jcao-ai** [InternLM/lmdeploy#547]
### Motivation

It seems that llama should use `neox_rotary_style_` ? like the one implemented [here](https://github.com/NVIDIA/FasterTransformer/blob/afdf9a9eb86f15363c0249117d166d6b45dbb371/src/fastertransformer/kernels/decoder_masked_multihead_attention/decoder_masked_multihead_attention_template.hpp#L1332).

And this project seems to use [direct rope embeeding](https://github.com/lvhan028/lmdeploy/blob/19ff47dfb48ef53d6a7485687e2a3a63cfe611de/src/turbomind/kernels/decoder_masked_multihead_attention/decoder_masked_multihead_attention_template.cuh#L1393).

This is confused.

**Comment by lzhangzz** [comment]
It's just the layout of Wq and Wk matrix. 

In FT, huggingface's weight layout corresponds to "neox_rotary_style" while META's official LLaMA release corresponds to the "direct" style.

The 2 different layout is convertible by viewing head dim as `(64, 2)` (or the other way around) and transpose it.

**Comment by jcao-ai** [comment]
Thanks, this makes sense.
