### ISSUE TITLE
chat-api "finish_reason": "length" [Bug] 

### ISSUE THREAD

**Issue by ltm920716** [InternLM/lmdeploy#550]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

chat api output overflow, `max_tokens` does no effect

### Reproduction

```
curl -X 'POST' \
  'url/v1/chat/completions' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "model": "internlm-chat-20b",
  "messages": [{"role": "user", "content": "你好， 我是小明，今天天气真不错啊"}],
  "temperature": 0.7,
  "top_p": 1,
  "n": 1,
  "max_tokens": 512,
  "stop": false,
  "stream": false,
  "presence_penalty": 0,
  "frequency_penalty": 0,
  "user": "string",
  "repetition_penalty": 1,
  "renew_session": false,
  "ignore_eos": false
}'
```

### Error traceback

```Shell
{
  "id": "61169018",
  "object": "chat.completion",
  "created": 1697092059,
  "model": "internlm-chat-20b",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": ""
      },
      "finish_reason": "length"
    }
  ],
  "usage": {
    "prompt_tokens": 23,
    "total_tokens": 8223,
    "completion_tokens": 0
  }
}
```

**Comment by AllentDan** [comment]
Session length is reached. Please renew the session.

**Comment by ltm920716** [comment]
hi @AllentDan 
it means that if `renew_session=false`，the completions will keep History？
so how to keep id between different call？

**Comment by AllentDan** [comment]
Yes.
Determined by request ip address. The interactive mode for openai API is gonna deprecate since we've received too many complaints about this feature. Only the `generate` API supports interactive mode later.

**Comment by ltm920716** [comment]
I think that openai interactive mode does not matter，only remove `renew_session ` will be ok！keeping message format.
Users decides whether to upload history or not.

**Comment by AllentDan** [comment]
What should a user do when the session length limit is reached? Only removing `renew_session` is not the proper way. Chatgpt does not support interactive mode either.

**Comment by ltm920716** [comment]
what I mean is that `renew_session` should always be true，namely no session. session is not useful in actually job workflow， but the param `messages`  is worth stay.

I understand your reply，thanks
