### ISSUE TITLE
[Feature] qwen-7b-chat 和 qwen-14b-chat int4量化版模型支持

### ISSUE THREAD

**Issue by zhengboju** [InternLM/lmdeploy#556]
### Motivation

对于生产环境，模型效果和推理速度至关重要，qwen已经发布了qwen-14b-chat，模型效果有了显著提升，而且量化后的qwen-7b-chat-int4和qwen-14b-chat-int4 效果几乎无损，推理速度提升显著，希望支持qwen int4量化版模型

**Comment by zhengboju** [comment]
这个Feature 有支持计划了吗@pppppM

**Comment by sjzhou4** [comment]
@zhengboju @pppppM @lvhan028 
我使用https://github.com/InternLM/lmdeploy/pull/307  +   pip install flash-attn --no-build-isolation，当然这个flash-attn运行会有点问题，需要修改flash_attn/ops/triton/rotary.py里面的代码，将cpu值传入cuda即可，issue在这里https://github.com/Dao-AILab/flash-attention/issues/523。
就能量化出Qwen-chat-14B的模型了。但是14B量化模型出现加载警告。如下：
![image](https://github.com/InternLM/lmdeploy/assets/142190228/10232006-d4c5-4eeb-abe4-fd85a90d2ea1)
请问这个该怎么解决呢？

**Comment by sjzhou4** [comment]
是参数转换没对应，https://github.com/InternLM/lmdeploy/pull/307的是7B的

**Comment by pppppM** [comment]
@sjzhou4 目前 lmdeploy 不能正确生成量化参数（不会报错，但结果不对），并且 #307 也有些问题，我们正在修复中

**Comment by qiuxuezhe123** [comment]
@pppppM 您好！目前已经有qwen-7b-chat-int4和qwen-14b-chat-int4两个chat版本的qwen量化模型，且我们离线测试的效果和非量化版本的模型相比，性能提升较为明显，请问直接加载量化版本的qwen模型目前能快速支持吗？

**Comment by frankxyy** [comment]
> @pppppM 您好！目前已经有qwen-7b-chat-int4和qwen-14b-chat-int4两个chat版本的qwen量化模型，且我们离线测试的效果和非量化版本的模型相比，性能提升较为明显，请问直接加载量化版本的qwen模型目前能快速支持吗？

感觉直接转换HF上的qwen量化模型到turbomind awq格式应该也可以吧。虽然量化算法不同，但结果都是w4a16量化。。估计可以通用。。  不过我还没试过

**Comment by pppppM** [comment]
> @pppppM 您好！目前已经有qwen-7b-chat-int4和qwen-14b-chat-int4两个chat版本的qwen量化模型，且我们离线测试的效果和非量化版本的模型相比，性能提升较为明显，请问直接加载量化版本的qwen模型目前能快速支持吗？

@qiuxuezhe123 Qwen Int4 的问题我们已经解决， #605 #296 两个 PR merge 后就可以使用了

**Comment by pppppM** [comment]
> > @pppppM 您好！目前已经有qwen-7b-chat-int4和qwen-14b-chat-int4两个chat版本的qwen量化模型，且我们离线测试的效果和非量化版本的模型相比，性能提升较为明显，请问直接加载量化版本的qwen模型目前能快速支持吗？
> 
> 感觉直接转换HF上的qwen量化模型到turbomind awq格式应该也可以吧。虽然量化算法不同，但结果都是w4a16量化。。估计可以通用。。 不过我还没试过

如果是 Qwen 官方提供的 int4 模型，是不支持的
LMDeploy 中的 kernel 是适配 AWQ 的，不适配 GPTQ (Qwen 官方提供的 int4)

**Comment by frankxyy** [comment]
@pppppM 了解，大佬你们后续考虑支持加载gptq量化后模型嘛

**Comment by pppppM** [comment]
> @pppppM 了解，大佬你们后续考虑支持加载gptq量化后模型嘛

@frankxyy 暂时不考虑，目前看 AWQ 已经能满足需求，速度和易用性上都要优于 GPTQ
