### ISSUE TITLE
llama-2-7b  kv cache 量化

### ISSUE THREAD

**Issue by lin65505578** [InternLM/lmdeploy#560]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

计算 llama2 7b  kv cache 量化 minmax 报错，huggingface 的7b 模型
 python3 -m lmdeploy.lite.apis.calibrate   --model './llama/Llama-2-7b-chat-hf'   --calib_dataset 'c4'   --calib_samples 128  --calib_seqlen 2048 --work_dir ./minmax      
Llama-2-7b-chat-hf containing more than one `.index.json` file, delete the irrelevant ones.

### Reproduction

  python3 -m lmdeploy.lite.apis.calibrate   --model './llama/Llama-2-7b-chat-hf'   --calib_dataset 'c4'   --calib_samples 128  --calib_seqlen 2048 --work_dir ./minmax      

### Error traceback

```Shell
Llama-2-7b-chat-hf containing more than one `.index.json` file, delete the irrelevant ones.
```

**Comment by logicray** [comment]
这个看看目录下是不是有 点开头的隐藏文件，从win压缩复制到linux经常会有这个。

**Comment by pppppM** [comment]
可以把 `./llama/Llama-2-7b-chat-hf` 中的 `model.safetensors.index.json` 删除

**Comment by lin65505578** [comment]
ok
