### ISSUE TITLE
[Docs] doc enhancement for docker setup

### ISSUE THREAD

**Issue by del-zhenwu** [InternLM/lmdeploy#563]
### 📚 The doc issue

The src description in readme:
```
[Serving with Triton Inference Server](https://github.com/InternLM/lmdeploy/tree/main#serving-with-triton-inference-server)
Launch inference server by:

bash workspace/service_docker_up.sh
```
Could we provide any tips about how to locate the `workspace` dir to users?

**Comment by lvhan028** [comment]
`service_docker_up.sh` is designed to be launched in any directory. It's not necessary to write a specific doc
