### ISSUE TITLE
lmdeploy支持原生非huggingface格式的llama2和codellama模型部署吗

### ISSUE THREAD

**Issue by for-just-we** [InternLM/lmdeploy#570]
### Motivation

下载的模型转化成huggingface格式总是报错，要是能部署原生非huggingface的llama和codellama就更好

**Comment by lvhan028** [comment]
运行deploy.py，使用选项 `--model-format llama`

**Comment by for-just-we** [comment]
> 运行deploy.py，使用选项 `--model-format llama`

ok，看文档我还有点疑问，假如我想要在我服务器上部署一个llama 13b-chat的模型，只需要推理服务，然后想用rest api访问。我是

- 首先运行 `python3 -m lmdeploy.serve.turbomind.deploy llama2 /path/to/llama-2-13b-chat-hf llama /path/to/tokenizer --tp 2` 在workspace目录生成脚本

- 然后运行 `bash workspace/service_docker_up.sh` 或者 `python3 -m lmdeploy.serve.openai.api_server ./workspace 0.0.0.0 server_port --instance_num 32 --tp 2`

- 然后通过 `curl http://{server_ip}:{server_port}/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
    "model": "internlm-chat-7b",
    "messages": [{"role": "user", "content": "Hello! Ho are you?"}]
  }'` 这种方式访问就可以了吗

**Comment by lvhan028** [comment]
步骤二中，无需 `bash workspace/service_docker_up.sh`

**Comment by for-just-we** [comment]
> 步骤二中，无需 `bash workspace/service_docker_up.sh` 步骤三中，model_name 需要填写 llama2

ok。然后rest api接口是只能batch size=1吗？我看之前的[issue](https://github.com/InternLM/lmdeploy/issues/219)，假如我想一次输入多batch，开多进程/线程。每个进程/线程发送1个请求就可以了吗

**Comment by lvhan028** [comment]
PR #544 增加了 batch 处理

**Comment by lvhan028** [comment]
@for-just-we 能不能介绍下，在什么场景你想一次输入多batch呢？
v1/chat/completions是不好支持batch的。

**Comment by for-just-we** [comment]
> @for-just-we 能不能介绍下，在什么场景你想一次输入多batch呢？ v1/chat/completions是不好支持batch的。

比如做程序分析任务，分析个大型程序，一次可能生成上千个数据对，之前本地跑的时候1个batch放了15个。现在prompt 1次一个的话不确定多久能跑完。不过貌似部署后跑的更快

**Comment by lvhan028** [comment]
batch inference功能已合入。PR #467
