### ISSUE TITLE
[Question] NTK rope in decoding phase ?

### ISSUE THREAD

**Issue by jcao-ai** [InternLM/lmdeploy#571]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

Dear developers,
It seems that dynamic NTK is implemented in [prefill](https://github.com/InternLM/lmdeploy/blob/bb3cce9a93d6c1d2a6f504afedec988e014587bf/src/turbomind/kernels/unfused_attention_kernels.cu#L935) phase but not in [decoding](https://github.com/InternLM/lmdeploy/blob/bb3cce9a93d6c1d2a6f504afedec988e014587bf/src/turbomind/kernels/decoder_masked_multihead_attention/decoder_masked_multihead_attention_template.cuh#L1393) phase.

Is it by design? Thanks

### Reproduction

None

### Error traceback

```Shell
None
```

**Comment by sjzhou4** [comment]
在lmdeploy//lmdeploy/src/turbomind/kernels/unfused_attention_kernels.cu里面的计算，你可以去看一下
![image](https://github.com/InternLM/lmdeploy/assets/142190228/47bdc36a-c5bc-4427-84ee-f4da8073c71d)

**Comment by jcao-ai** [comment]
> 在lmdeploy//lmdeploy/src/turbomind/kernels/unfused_attention_kernels.cu里面的计算，你可以去看一下 ![image](https://user-images.githubusercontent.com/142190228/276051507-47bdc36a-c5bc-4427-84ee-f4da8073c71d.png)

Yep. Thanks for your reply. But I have mentioned in my previous message. It's only called inside `Prefill` phase not in `decoding` phase.

**Comment by lzhangzz** [comment]
Here it is

https://github.com/InternLM/lmdeploy/blob/9c3634ecb882db35ec548580652bf8b72be00560/src/turbomind/kernels/decoder_masked_multihead_attention/decoder_masked_multihead_attention_template.cuh#L1381-L1388
