### ISSUE TITLE
请求API出现问题，如果流式请求，循环不出来，如果不流式，请求就一直卡主。

### ISSUE THREAD

**Issue by cat-knight** [InternLM/lmdeploy#577]
如题，请求代码如下：如果stream=True，就在  for chunk  这行卡主，如果不流式，就在 response = requests.post 这行卡主。
import json
import requests
from typing import Iterable, List

def get_streaming_response(prompt: str,
                           api_url: str,
                           session_id: int,
                           request_output_len: int,
                           stream: bool = True,
                           sequence_start: bool = True,
                           sequence_end: bool = True,
                           ignore_eos: bool = False) -> Iterable[List[str]]:
    headers = {'User-Agent': 'Test Client'}

    pload = {
        'prompt': prompt,
        'stream': stream,
        'session_id': session_id,
        'request_output_len': request_output_len,
        'sequence_start': sequence_start,
        'sequence_end': sequence_end,
        'ignore_eos': ignore_eos,
        'model': 'qwen-14b',
        'messages': '你好',
    }

    response = requests.post(api_url, headers=headers, json=pload, stream=stream)
    for chunk in response.iter_lines(chunk_size=8192, decode_unicode=False, delimiter=b'\n'):
        if chunk:
            data = json.loads(chunk.decode('utf-8'))
            output = data['text']
            tokens = data['tokens']
            yield output, tokens

api_url = "http://region-31.seetacloud.com:46124/v1/chat/completions"

for output, tokens in get_streaming_response("你好", api_url, 0,512):
    print(output, end='')

**Comment by AllentDan** [comment]
可能是 server 卡住了，重启试试？
