### ISSUE TITLE
[Feature] GPT-Q量化算法

### ISSUE THREAD

**Issue by Vincent131499** [InternLM/lmdeploy#588]
### Motivation

目前看gpt-q算法正在开发中，想问下大概什么时候会上啊，坐等体验(*❦ω❦)

**Comment by pppppM** [comment]
之前是因为发现 AWQ 有些模型不能成功量化，比如 Qwen，打算开发 GPTQ 去解决

但在最近的开发中发现，是因为有一些实现上的细节，导致部分模型不能正常使用 AWQ
修复了实现上的细节问题后，我们测试了多个开源的大模型，AWQ 都能正常量化，修复的内容近期会 PR

所以，GPTQ 的开发转为了一个比较低的优先级，目前会优先开发更多的量化策略，W4A16 这个策略上还是会使用 AWQ，除非遇到了我们可复现的 AWQ 量化失败的案例
