### ISSUE TITLE
[Feature] Lmdeploy使用dynamic batch策略，开启请求优先级与ragged batch

### ISSUE THREAD

**Issue by MKMQ99** [InternLM/lmdeploy#592]
### Motivation

我想要开启lmdeploy的请求优先级功能，所以使用了dynamic batch策略，对/workspace/model_repository/turbomind/config.pbtxt文件进行了修改，包括
1. 修改input中的input_ids，开启ragged_batch，并增加batch_input配置：
input [
  {
    name: "input_ids"
    data_type: TYPE_UINT32
    dims: [ -1 ]
    allow_ragged_batch: true
  },
......
]
batch_input [
  {
    kind: BATCH_ACCUMULATED_ELEMENT_COUNT
    target_name: "INDEX"
    data_type: TYPE_UINT32
    source_input: "input_ids"
  }
]
2. 增加 dynamic_batching 相关优先级配置
dynamic_batching { 
  priority_levels: 9
  default_priority_level: 9
}

但是报错：
![WXWorkCapture_16977700453277](https://github.com/InternLM/lmdeploy/assets/45583406/a7dbd98c-7d6d-43c3-8076-bab3337c456e)
所以我将batch_input中的data_type改为了TYPE_INT32，但是依旧报错：
![WXWorkCapture_1697711600471](https://github.com/InternLM/lmdeploy/assets/45583406/9adcbb06-45fa-4e8f-b66d-0ca249a77e77)

### Related resources

ragged batch相关配置我参考的是https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/user_guide/ragged_batching.html

### Additional context

在开启ragged batch之前，只开启dynamic batch与请求优先级，lmdeploy可以运行。我往lmdeploy连续发送了一些请求，但是根据lmdeploy的输出来看，推理的batchsize只有1
![WXWorkCapture_16977704637680](https://github.com/InternLM/lmdeploy/assets/45583406/4eb7f779-c16c-4c4d-abfa-ab44ef3b13ed)
这是我开启ragged batch的原因

**Comment by lvhan028** [comment]
应该是发送方式不太对导致的。lmdeploy turbomind是支持多batch的。无需更改 config.pbtxt的。
lmdeploy的turbomind负责管理batch，不用triton inference server的batch策略，而是用它的多instance方式（默认是48个instance）。

**Comment by MKMQ99** [comment]
> 应该是发送方式不太对导致的。lmdeploy turbomind是支持多batch的。无需更改 config.pbtxt的。 lmdeploy的turbomind负责管理batch，不用triton inference server的batch策略，而是用它的多instance方式（默认是48个instance）。


instance_group的配置中，

instance_group [
  {
    # max concurrent instances
    count: 48
    kind: KIND_CPU
  }
]

kind为KIND_CPU，那意思是在CPU中跑48个模型实例么，那我用GPU跑模型是否还需要更改instance_group的配置。以及这里的配置和我在service_docker.sh中指定的DEVICE有什么关系么？

**Comment by lvhan028** [comment]
模型实例是跑在GPU上的。
service_docker_up.sh中的device是为了把host上的device映射到docker内。两者没有关系
