### ISSUE TITLE
[Bug] Question about first_token_latency in profile_restful_api.py 

### ISSUE THREAD

**Issue by wjj19950828** [InternLM/lmdeploy#594]
### Motivation

您好～

请问下关于[profile_restful_api.py](https://github.com/InternLM/lmdeploy/blob/main/benchmark/profile_restful_api.py)

为什么```first_token_latency```是从timestamps[1]计算，而不是timestamps[0]

而token_latency又是从timestamps[0]计算，而不是timestamps[1]

我理解timestamps[0]应该是对应第一个token返回打的时间点，那首token耗时应该是：

```code
first_token_latency = timestamps[0] - start
```

感谢～

**Comment by lvhan028** [comment]
这里确实会让人觉得别扭。我们提个PR加comments说明下。
对了，想问下，在使用 restful api的时候，需要streaming方式推理么？

**Comment by wjj19950828** [comment]
@lvhan028 主要是想看看以openai http方式请求下，首token以及step latency的一些指标

然后上面计算方式需要改动吗，first_token_latency计算是从index 0开始还是1开始呢～

**Comment by lvhan028** [comment]
可以看下最新的 profile_restful_api.py
