### ISSUE TITLE
[Feature] 希望提供一个使用docker镜像的源码编译tutorial

### ISSUE THREAD

**Issue by ehuaa** [InternLM/lmdeploy#596]
### Motivation

目前根据官方提供的源码编译流程 用or不用conda 都存在各种cmake和make的错误尚未解决，因此希望能提供一个完整详细的使用镜像环境编译代码的流程，希望包括：
1. pull， run的一些参数设置（gpu等）
2. 编译好之后 开发时如何将镜像内的文件迁移到本地进行发布等 以及 是否要和本地环境进行适配（比如我看docker内是py3.8 torch 1.13 如果发布到py3.10 torch 2.1 上面是否适配）
3. 远程开发连接docker内源码项目如何操作（optional）
谢谢~

**Comment by ehuaa** [comment]
> 希望 #602 能够帮到你。有意见或者建议的话，可以在这个PR中comments

@lvhan028 好的谢谢，另外问下在镜像中编译好了之后，如何能够拿到镜像外部署呢 比如 pip install，以及现在的镜像是py3.8的 如果镜像外的python版本不同怎么办呢

**Comment by lvhan028** [comment]
我更新了build.md文档，使用lmdeploy_builder 镜像，可以生成 wheel 包，py3.8 - py3.11.
用这个wheel包，就能分发到外部了

**Comment by ehuaa** [comment]
> 我更新了build.md文档，使用lmdeploy_builder 镜像，可以生成 wheel 包，py3.8 - py3.11. 用这个wheel包，就能分发到外部了

好的 感谢 已经看到了 已安装成功
