### ISSUE TITLE
Add Support for PULSE Deployment

### ISSUE THREAD

**Issue by simon12138-code** [InternLM/lmdeploy#600]
### Motivation

我们需要针对PULSE模型进行部署，但发现目前不支持该模型

### Related resources

模型连接(https://github.com/openmedlab/PULSE)

**Comment by lvhan028** [comment]
抱歉，lmdeploy turbomind引擎现在还不支持 bloom 结构。
我们计划优先支持 opencompass 榜单靠前的模型
