### ISSUE TITLE
K_cache的形状问题

### ISSUE THREAD

**Issue by flexwang** [InternLM/lmdeploy#612]
请问为什么在lmdeploy的实现中，kv cache是[这样](https://github.com/InternLM/lmdeploy/blob/ac3500b5fca3ac651e9bc65990fb265572b7c42c/src/turbomind/models/llama/LlamaCacheManager.h#L13-L14)的形状，是出于性能优化的考虑吗？x代表什么？
```
// k-cache layout [L, H, D/x, S[s:], x]
// v-cache layout [L, H, S[s:], D/x, x]
```

**Comment by lzhangzz** [comment]
这是FasterTransformer中key的layout，在lmdeploy中已经不用了
