### ISSUE TITLE
[Bug] lmdeploy: command not found

### ISSUE THREAD

**Issue by amulil** [InternLM/lmdeploy#618]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

I use `pip install lmdeploy` to install this pacakge. But when I run it successfully, I got a error: `lmdeploy: command not found`

### Reproduction

`pip install lmdeploy` -> `lmdeploy` -> `lmdeploy: command not found`

### Error traceback

```Shell
lmdeploy: command not found
```

**Comment by lvhan028** [comment]
The latest main branch hasn't been released yet.
After we release a new version next week, you can use the cli.

**Comment by lubancafe** [comment]
same issue

**Comment by lvhan028** [comment]
@amulil @lubancafe try `pip install lmdeploy==0.0.13`

**Comment by tianhao-star** [comment]
> The latest main branch hasn't been released yet. After we release a new version next week, you can use the cli.
same issue，have you solved the problem yet?
