### ISSUE TITLE
[Feature] Specify specific gpu card for turbomind

### ISSUE THREAD

**Issue by ehuaa** [InternLM/lmdeploy#622]
### Motivation

i have a gpu server with many gpu cards, but only device_id=2 is available, and i want to inference on this card.
can i modify some code such as 
![image](https://github.com/InternLM/lmdeploy/assets/5137359/2337525c-87fe-47a4-a310-cb1cb7161c6a)
![image](https://github.com/InternLM/lmdeploy/assets/5137359/f4d0507f-e4fd-4b1c-9f1b-f8e1aa5bf309)
![image](https://github.com/InternLM/lmdeploy/assets/5137359/393c3bf2-3c1d-4be1-97dc-374db5c69a90)
these three places to specify inference on device 2?

**Comment by ehuaa** [comment]
![image](https://github.com/InternLM/lmdeploy/assets/5137359/58b2f871-e9fa-4f45-be2f-8ea0ed0fd9f8)
i use CUDA_VISIBLE_DEVICES to implement this feature.

**Comment by lvhan028** [comment]
You can export `CUDA_VISIBLE_DEVICES` environmental variable without changing the code
```
CUDA_VISIBLE_DEVICES="2" python <your awesome program> <the arguments>
```
