### ISSUE TITLE
[Bug] Elapsed time in benchmark/profile_serving contains the time of reading dataset. The throughput cannot be calculated correctly.

### ISSUE THREAD

**Issue by zhulinJulia24** [InternLM/lmdeploy#629]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

![image](https://github.com/InternLM/lmdeploy/assets/145004780/8133df39-34e9-49a8-a2a0-3d37b8caca59)

### Reproduction

run banchmark according to https://github.com/InternLM/lmdeploy/blob/main/benchmark/README.md

such as 
`python benchmark/profile_serving.py 10.XX.XX.XX:33337 ../workspace/triton_models/tokenizer/tokenizer.model ../res.json 48 >& ../result`

if dataset is large, it will spend long time like this, the throughput is incorrect.  

![image](https://github.com/InternLM/lmdeploy/assets/145004780/13a3c95c-f8f9-4a26-b03c-22bc27a688c2)

**Comment by AllentDan** [comment]
Below is the real computation.
https://github.com/InternLM/lmdeploy/blob/56942c43315af2a205efbaaa6343786f6e11c943/benchmark/profile_serving.py#L20-L34
