### ISSUE TITLE
针对 w4a16量化的精度有对比吗？  试了下 llama2-7b 的差距很大

### ISSUE THREAD

**Issue by lin65505578** [InternLM/lmdeploy#632]
### Motivation

通过这个流程，得到  llama2-7b  w4a16  量化模型
https://github.com/InternLM/lmdeploy/blob/main/docs/en/w4a16.md#4-bit-llm-model-inference

通过 opencompass 测试 对比 精度
https://github.com/open-compass/opencompass/pull/484
![image](https://github.com/InternLM/lmdeploy/assets/12838445/92c70c72-2770-4b28-993b-ba87665ed4dd)

w4a16的config
[llama]
model_name = llama2
head_num = 32
kv_head_num = 32
size_per_head = 128
vocab_size = 32000
num_layer = 32
rotary_embedding = 128
rope_theta = 10000.0
inter_size = 11008
norm_eps = 1e-06
attn_bias = 0
start_id = 1
end_id = 2
weight_type = int4
group_size = 128
max_batch_size = 32
max_context_token_num = 4
session_len = 4104
step_length = 1
cache_max_entry_count = 48
cache_chunk_size = 1
use_context_fmha = 0 #1
quant_policy = 0
tensor_para_size = 1
max_position_embeddings = 4096 #0
use_dynamic_ntk = 0
use_logn_attn = 0

**Comment by lvhan028** [comment]
测过 internlm-20b-w4, internlm-chat-20b-w4 精度，对齐。

请给出你用 opencompass 测试 turbomind的config，我们复现下

**Comment by lin65505578** [comment]
from mmengine.config import read_base
from opencompass.models.turbomind import TurboMindModel


with read_base():
    # # choose a list of datasets
    # from .datasets.mmlu.mmlu_gen_a484b3 import mmlu_datasets
    # from .datasets.ceval.ceval_gen_5f30c7 import ceval_datasets
    # from .datasets.SuperGLUE_WiC.SuperGLUE_WiC_gen_d06864 import WiC_datasets
    # from .datasets.SuperGLUE_WSC.SuperGLUE_WSC_gen_6dc406 import WSC_datasets
    # from .datasets.triviaqa.triviaqa_gen_2121ce import triviaqa_datasets
    # from .datasets.gsm8k.gsm8k_gen_1d7fe4 import gsm8k_datasets
    # from .datasets.humaneval.humaneval_gen_8e312c import humaneval_datasets
    # from .datasets.race.race_gen_69ee4f import race_datasets
    from .datasets.crowspairs.crowspairs_gen_381af0 import crowspairs_datasets
    # add lin
    from .datasets.winogrande.winogrande_gen_a9ede5 import winogrande_datasets
    from .datasets.nq.nq_gen_0356ec import nq_datasets
    from .datasets.gsm8k.gsm8k_gen_1d7fe4 import gsm8k_datasets
    # from .datasets.bbh.bbh_gen_5b92b0 import bbh_datasets
    from .datasets.bbh.bbh_gen import bbh_datasets
    # from .datasets.crowspairs.crowspairs_gen_02b6c1 import crowspairs_datasets
    # from .datasets.crowspairs.crowspairs_gen import crowspairs_datasets
    # from .datasets.FewCLUE_eprstmt.FewCLUE_eprstmt_gen_740ea0 import eprstmt_datasets
    from .datasets.FewCLUE_eprstmt.FewCLUE_eprstmt_gen import eprstmt_datasets
    from .datasets.obqa.obqa_gen_9069e4 import obqa_datasets
    # and output the results in a choosen format
    from .summarizers.medium import summarizer

datasets = sum((v for k, v in locals().items() if k.endswith('_datasets')), [])


meta_template = dict(
    round=[
        dict(role='HUMAN', begin='<|User|>:', end='\n'),
        dict(role='BOT', begin='<|Bot|>:', end='<eoa>\n', generate=True),
    ],
    eos_token_id=103028)


# config for  llama2-7b w4a16 model  w4a16 model
models = [
    dict(
        type=TurboMindModel,
        abbr='new-llama2-7b-w4a16',
        path="/Lmdeploy/workspaceLlama4w16a_new",
        max_out_len=100,
        max_seq_len=2048,
        batch_size=16,
        concurrency=16,
        meta_template=meta_template,
        run_cfg=dict(num_gpus=1, num_procs=1),
    )
]

**Comment by lin65505578** [comment]
![image](https://github.com/InternLM/lmdeploy/assets/12838445/274b4bf6-08ac-4d5f-871d-881b629549ab)
python run.py configs/eval_internlm_chat_turbomind.py -w outputs/ddd

**Comment by lvhan028** [comment]
这是InternLM模型的配置文件，不是llama的。

**Comment by lin65505578** [comment]
已经把模型转成lmdeploy 推理格式 
（huggingface版LLaMa2模型：/models/llama-2-7b-chat目录，保存到workspace文件夹） ； 
 配置文件也不能通用？

**Comment by lvhan028** [comment]
不同的模型有不同的meta template，这也没法通用啊

**Comment by lin65505578** [comment]
https://github.com/open-compass/opencompass/issues/363
这个issue 里有类似的问题； 看了下 meta template 设置； 采用相同的 meta template 设置；  无论是 kv int8 量化后，还是 w4A16 量化后，在 .datasets.crowspairs.crowspairs_gen_381af0    数据集上差距很大  ； 15个点左右

![image](https://github.com/InternLM/lmdeploy/assets/12838445/d3d406f2-f486-4725-91de-e71ce7edcea7)

**Comment by lin65505578** [comment]
https://github.com/InternLM/lmdeploy/issues/617

关联个类似的issue

**Comment by lvhan028** [comment]
llama2应该不是用meta template，而是APITemplateParser。
https://github.com/open-compass/opencompass/blob/987a7112323fdee8ed884ad1a61c10583e3825c6/opencompass/models/llama2.py#L137C9-L137C64
再次说明，opencompass现在没有把模型配置和推理引擎的配置分隔开。这样我们添加引擎会比较麻烦。所以只给了internlm的例子。
