### ISSUE TITLE
怎么进行多batch的同时推理？

### ISSUE THREAD

**Issue by riou-chen** [InternLM/lmdeploy#636]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

profile_generation.py这个脚本只是进行测试吧？api-server的测试方式如何进行多batch同时推理？多个问题写在一个prompt中，还是分别同时多次请求？这两种方式测试了都是都不能进行同时推理。

### Reproduction

CUDA_VISIBLE_DEVICES=5 python3 benchmark/profile_generation.py --model-path workspace/ --concurrency 3
CUDA_VISIBLE_DEVICES=5 python3 -m lmdeploy.serve.openai.api_server ./workspace 0.0.0.0 1234 --instance_num 32 --tp

**Comment by AllentDan** [comment]
分别同时多次请求。可以参考 https://github.com/InternLM/lmdeploy/blob/main/benchmark/profile_restful_api.py
也可以参考下面代码：
```python
from lmdeploy.serve.openai.api_client import APIClient
class MyClient(APIClient):
    def completion_v1_concurrently(	
            self,	
            model: str,	
            prompts: List[str],	
            suffix: Optional[str] = None,	
            temperature: Optional[float] = 0.7,	
            n: Optional[int] = 1,	
            max_tokens: Optional[int] = 16,	
            top_p: Optional[float] = 1.0,	
            user: Optional[str] = None,	
            # additional argument of lmdeploy	
            repetition_penalty: Optional[float] = 1.0,	
            ignore_eos: Optional[bool] = False,	
            **kwargs):	
        """A function for completion_v1 on concurrency."""	
        concurrency = len(prompts)	
        outputs = [''] * concurrency	

        async def get_response(id):	
            # We need to_thread here because completions_v1 is synchronous.	
            response = await asyncio.to_thread(lambda: next(	
                self.completions_v1(model,	
                                    prompts[id],	
                                    suffix=suffix,	
                                    temperature=temperature,	
                                    n=n,	
                                    max_tokens=max_tokens,	
                                    top_p=top_p,	
                                    user=user,	
                                    repetition_penalty=repetition_penalty,	
                                    ignore_eos=ignore_eos)))	
            outputs[id] = response	

        async def gather():	
            tasks = [get_response(id) for id in range(concurrency)]	
            await asyncio.gather(*tasks)	

        asyncio.get_event_loop().run_until_complete(gather())	
        return outputs
```
用多线程或者多进程同时发请求，或者用协程发多个请求都可以的

**Comment by AllentDan** [comment]
另外 https://github.com/InternLM/lmdeploy/blob/373bd01394cfa784a9ab3fe0d404d6ae1beee3d0/lmdeploy/serve/openai/api_server.py#L230 接口可以传入多个prompt，是 `List[str]` 结构，可以batch执行的

**Comment by riou-chen** [comment]
多线程并发推理时报错OverflowError: out of range integral type conversion attempted。

在主线程中创建了模型，在多个子线程中通过model.create_instance()创建了generator，然后通过for outputs in chatbot.stream_infer（）这个接口进行测试，在函数中的self._tokenizer.decode(res.tolist())这一步会报如上错误，打印发现res的tensor中出现负数，例如tensor([-8388609, -8388609, -8388609,  ..., -8388609, -8388609, -8388609]，这个是什么原因？

**Comment by AllentDan** [comment]
给下模型名和客户端代码

**Comment by riou-chen** [comment]
模型名：Llama2-Chinese-13b-Chat，测试过多个，都会这这样的报错。

测试代码是工程里的代码，部分如下：
model_name = self.model.model_name
model = MODELS.get(model_name)(capability='chat')
inputs = model.get_prompt(query_list, nth_round == 1)
inputs_dict = {}
session = 0
for query in query_list:
    inputs = model.get_prompt(query, nth_round == 1)
    inputs_dict[session] = self._tokenizer.encode(inputs)
    session += 1

def stream_chat_batch(self, batch_size, history=None, max_length: int = 4096,
                    do_sample=False, top_p=1.0, temperature=0.0, repetition_penalty=1.0, **kwargs):
    def infer(model, session: int, input_id, max_new_tokens: int）
        chatbot = model.create_instance()
        for outputs in chatbot.stream_infer(session, input_id,max_new_tokens: int,request_output_len = max_new_tokens,
                                                                  sequence_start=True, sequence_end=True,ignore_eos=True, stream_output=True):
            res, tokens = outputs[0]
            response = [self._tokenizer.decode(res.tolist())]            
    
    for key in list(self.input_ids.keys()):
        proc = Thread(target=infer, args=(self.model, key, [self.input_ids[key]], max_new_tokens, stop_token_ids))
        procs.append(proc)
        proc.start()

抽出的主要代码如上，模型初始化在主线程中完成，通过类变量传递，初始化代码如下：
tokenizer_model_path = os.path.join(self.model_path, 'triton_models', 'tokenizer')
tokenizer = Tokenizer(tokenizer_model_path)
tm_model = tm.TurboMind(self.model_path, eos_id=tokenizer.eos_token_id, tp=2)

**Comment by AllentDan** [comment]
用这个脚本复现不了，你直接用我们的函数吧
https://github.com/InternLM/lmdeploy/blob/85d2f6628b92b4b359aebcc7bd50814cb67cbca6/lmdeploy/serve/async_engine.py#L102

**Comment by riou-chen** [comment]
这个接口是要将多个问题放到同一个list里提交吗？如果问题不是同时来的，一分钟一个这样的怎么处理？每个问题起一个线程调用这个接口吗？

**Comment by AllentDan** [comment]
多个问题放到 list 里，同时处理，不用单独启线程

**Comment by riou-chen** [comment]
这个代码是最新版吧？pip能够获取到最新的版本吗？

**Comment by AllentDan** [comment]
可以等一两天发新版，也可以拷贝过去。代码差别下面链接
https://github.com/InternLM/lmdeploy/pull/467/files#diff-82d1a3e3c42d3018227af41c544bff3f5e475fd1ec5ac0da980d453302088f0d

**Comment by riou-chen** [comment]
这个batch_infer的方法在4090上2卡好像很容易爆显存啊

**Comment by riou-chen** [comment]
13B的模型

**Comment by riou-chen** [comment]
batch_infer有流式推理的能力吗？

**Comment by AllentDan** [comment]
没有。

**Comment by riou-chen** [comment]
那如何实现多batch同时推理，且具备流式推理的能力呢？

**Comment by AllentDan** [comment]
```python
from threading import Thread

from lmdeploy.serve.openai.api_client import APIClient
api_client = APIClient({api_server_url})
model_name = api_client.available_models[0]
procs = []

def test(model_name, prompt, stream):
    for out in api_client.chat_completions_v1(model_name, prompt, stream=True):
        print(out)


for i in range(10):
    proc = Thread(target = test,  args = (model_name, 'hi', True))
    proc.start()
    procs.append(proc)

for proc in procs:
    proc.join()
```

**Comment by AllentDan** [comment]
给你写了一版 stream 返回的：
```python

from queue import Queue
from typing import List
import asyncio
from lmdeploy.serve.async_engine import AsyncEngine

class AsyncEngineExtend(AsyncEngine):
    def batch_infer_stream(self,
                            prompts: List[str],
                            request_output_len=512,
                            top_k=40,
                            top_p=0.8,
                            temperature=0.8,
                            repetition_penalty=1.0,
                            ignore_eos=False,
                            **kwargs):
        """Inference a batch of prompts.

        Args:
            prompts (List[str]): a batch of prompts
            request_output_len (int): output token nums
            top_k (int): The number of the highest probability vocabulary
              tokens to keep for top-k-filtering
            top_p (float): If set to float < 1, only the smallest set of most
              probable tokens with probabilities that add up to top_p or higher
            are kept for generation.
            temperature (float): to modulate the next token probability
            repetition_penalty (float): The parameter for repetition penalty.
              1.0 means no penalty
            ignore_eos (bool): indicator for ignoring eos
        """
        assert isinstance(prompts, List), 'prompts should be a list'
        batch_size = len(prompts)
        outputs = Queue()
        generators = []
        for i, prompt in enumerate(prompts):
            generators.append(
                self.generate(prompt,
                              i,
                              stream_response=True,
                              sequence_start=True,
                              sequence_end=True,
                              request_output_len=request_output_len,
                              top_k=top_k,
                              top_p=top_p,
                              temperature=temperature,
                              ignore_eos=ignore_eos,
                              repetition_penalty=repetition_penalty))

        async def _inner_call(i, generator):
            async for out in generator:
                outputs.put([i, out.response])

        async def gather():
            await asyncio.gather(
                *[_inner_call(i, generators[i]) for i in range(batch_size)])
            outputs.put(None)
        from threading import Thread
        proc=Thread(target= lambda: self.loop.run_until_complete(gather()))
        proc.start()

        while True:
            if outputs.qsize() >0:
                out = outputs.get()
                if out is None:
                    break
                yield out

engine = AsyncEngineExtend('workspace')
for item in engine.batch_infer_stream(['write a poem about life','write a poem about love']):
    print(item)
```

**Comment by lvhan028** [comment]
Close it since no more activity over two weeks. Please reopen it if it is still an issue
