### ISSUE TITLE
[Feature]  将已经支持过的模型量化版本上传到 huggingface 

### ISSUE THREAD

**Issue by FlatMapIO** [InternLM/lmdeploy#642]
### Motivation

当前 https://huggingface.co/lmdeploy 只上传了 internlm 的量化模型, Qwen-14B 这些已经支持的模型肯定是已经有被量化过的, 希望也能上传到仓库.

**Comment by lvhan028** [comment]
等 PR #296 #605 合入之后，我们会上传一波的

**Comment by pppppM** [comment]
@FlatMapIO HuggingFace Hub 上已新增 Baichuan2-7B、Qwen-7B、Qwen-14B 和 Llama-70B 的 4bit 模型
