### ISSUE TITLE
[Bug] During benchmark/profile_serving.py, occur unexpexted end word 1, when ignore_eos is true. 

### ISSUE THREAD

**Issue by zhulinJulia24** [InternLM/lmdeploy#643]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

![xZ1BZhjoa6](https://github.com/InternLM/lmdeploy/assets/145004780/0369613d-2cd8-455d-91fa-eef909716811)

the output should not be blank

### Reproduction

start serving
base /mnt/models-new/puyu-XX/service_docker_up.sh

start benchmark
python benchmark/profile_serving.py X.X.X.187:33337 /puyu-XX/triton_models/tokenizer/tokenizer.model ../res.json 

the issue also canbe reproduced in chat command line (provided by AllentDan)
![img_v3_024r_b60cb628-0d61-492d-a493-8e896e01ac5g](https://github.com/InternLM/lmdeploy/assets/145004780/afc2c205-17f3-43a6-ad34-850d1d3a8118)

ps: the issue is logged to record and check after it's fixed.

**Comment by lvhan028** [comment]
`bos_id` and `eos_id` are wrong when converting the model to turbomind model
Please manually change them to 1 and 2 respectively in `triton_models/weights/config.ini`
