### ISSUE TITLE
[Feature] 期待Hugging Face上传llama2-chat-70b-w4模型

### ISSUE THREAD

**Issue by WarrenZhao** [InternLM/lmdeploy#649]
### Motivation

我正在尝试使用llama2-chat-70b-w4的量化版本进行部署测试。

### Related resources

https://huggingface.co/lmdeploy/llama2-chat-70b-w4/tree/main

### Additional context

当前 https://huggingface.co/lmdeploy 尚未找到 **llama2-chat-70b-w4** 模型, 期待这个版本的模型能上传到仓库.

**Comment by pppppM** [comment]
之前由于国内网络的问题，4bit 的 70B 模型一直上传失败
