### ISSUE TITLE
[问题] lmdeploy使用 turbomind 怎么设置推理回复最大tokens数

### ISSUE THREAD

**Issue by XksA-me** [InternLM/lmdeploy#651]
### Motivation

```bash
lmdeploy chat turbomind ./workspace/ -tp 4 --max_new_tokens 4096
```
lmdeploy使用 turbomind 怎么设置推理回复最大tokens数，目前看每次好像只能回复800个汉字左右
![image](https://github.com/InternLM/lmdeploy/assets/43670614/c14bb5d3-78fe-49a2-8df4-045b9d6639bb)
显存是够的 4个3090
![image](https://github.com/InternLM/lmdeploy/assets/43670614/81bb0246-9cb9-448c-a72f-17aa6699a9cf)

**Comment by AllentDan** [comment]
传 `--request_output_len`，默认值是 512。可以调大
