### ISSUE TITLE
[Bug] restful api中/v1/chat/interactive接口请求返回404

### ISSUE THREAD

**Issue by hk8805** [InternLM/lmdeploy#652]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

当我在本地部署restful api成功后，发现/v1/models 和/v1/completions都能正常返回，但是/v1/chat/interactive接口返回404
<img width="639" alt="截屏2023-11-06 下午2 54 27" src="https://github.com/InternLM/lmdeploy/assets/24692695/092f34ec-ac89-4272-b36e-4edf3441410f">

### Reproduction

curl http://127.0.0.1:8093/v1/chat/interactive   -H "Content-Type: application/json"   -d '{
    "prompt": "Hello! How are you?",
    "session_id": 1,
    "interactive_mode": true
  }'

**Comment by AllentDan** [comment]
重启试试，代理关了

**Comment by hk8805** [comment]
> 重启试试，代理关了

重启了，也没有开代理，还是一样的，model接口能通，证明这个通路是正常的，应该是接口出问题了吧

**Comment by hk8805** [comment]
> 重启试试，代理关了

根据https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/restful_api.md中的/v1/chat/interactive接口调用generate方法生成回答，但是我看https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/serve/openai/api_client.py中没有generate方法，是不是文档中有些问题

**Comment by AllentDan** [comment]
新代码，还没发版，等一两天有新版

**Comment by AllentDan** [comment]
`/v1/completions` 你咋得到返回值的，都没用新代码...

**Comment by hk8805** [comment]
> `/v1/completions` 你咋得到返回值的，都没用新代码...

因为我用老代码提示找不到cannot import name 'APIClient' from 'lmdeploy.serve.openai.api_client

**Comment by hk8805** [comment]
> `/v1/completions` 你咋得到返回值的，都没用新代码...

因为我用老代码提示请求找不到
cannot import name 'APIClient' from 'lmdeploy.serve.openai.api_client
所以我从最新的的api_client.py复制了一份到本地
但是请求之后报404
直接用curl也还是404

**Comment by AllentDan** [comment]
OK，等新代码吧。如果着急用可以用下面脚本源码安装 lmdeploy。
```
#!/bin/bash

# 安装lmdeploy
pip install -U lmdeploy
# 获取安装lmdeploy的位置下的lib文件夹路径
lmdeploy_dir=$(pip show lmdeploy | grep Location | cut -d' ' -f2)
lib_dir="${lmdeploy_dir}/lmdeploy/lib"

# 检查lib目录是否存在
if [ ! -d "$lib_dir" ]
then
    echo "Lib directory does not exist at ${lib_dir}"
    exit 1
fi

# 克隆lmdeploy的仓库
git clone https://github.com/InternLM/lmdeploy.git || exit 1

# 将lib文件夹拷贝到刚刚克隆的lmdeploy下
cp -r "$lib_dir" "lmdeploy/lmdeploy/" || exit 1

pip uninstall -y lmdeploy
cd lmdeploy
pip install -e .
```

**Comment by hk8805** [comment]
> OK，等新代码吧。如果着急用可以用下面脚本源码安装 lmdeploy。
> 
> ```
> #!/bin/bash
> 
> # 安装lmdeploy
> pip install -U lmdeploy
> # 获取安装lmdeploy的位置下的lib文件夹路径
> lmdeploy_dir=$(pip show lmdeploy | grep Location | cut -d' ' -f2)
> lib_dir="${lmdeploy_dir}/lmdeploy/lib"
> 
> # 检查lib目录是否存在
> if [ ! -d "$lib_dir" ]
> then
>     echo "Lib directory does not exist at ${lib_dir}"
>     exit 1
> fi
> 
> # 克隆lmdeploy的仓库
> git clone https://github.com/InternLM/lmdeploy.git || exit 1
> 
> # 将lib文件夹拷贝到刚刚克隆的lmdeploy下
> cp -r "$lib_dir" "lmdeploy/lmdeploy/" || exit 1
> 
> pip uninstall -y lmdeploy
> cd lmdeploy
> pip install -e .
> ```

好的，更新之后，服务已通，感谢
