### ISSUE TITLE
[Bug]  ValueError: If `eos_token_id` is defined, make sure that `pad_token_id` is defined.

### ISSUE THREAD

**Issue by creegon** [InternLM/lmdeploy#653]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

在运行python -m lmdeploy.pytorch.chat ${NAME_OR_PATH_TO_LLM} \
    --max_new_tokens 256 \
    --temperature 0.8 \
    --top_p 0.95 \
    --seed 0
后，报错：ValueError: If `eos_token_id` is defined, make sure that `pad_token_id` is defined.
期间，我参考了这个解决方案：https://github.com/InternLM/lmdeploy/issues/522
根据上述参考方案，我把我的chat.py中的main方法中的gen_config更改为了：
    gen_config = GenerationConfig(
        max_new_tokens=max_new_tokens,
        do_sample=temperature > 0,
        temperature=temperature,
        top_p=top_p,
        eos_token_id=tokenizer.eos_token_id,
        pad_token_id=tokenizer.pad_token_id if tokenizer.pad_token_id is not None else tokenizer.eos_token_id,   
    )
    但是并没有用，再次运行后仍然报刚刚的错误。
    debug后，我发现在运行fire.Fire(main)的时候，它似乎就需要用到pad_token_id。
    这个可以怎么去解决呢？

### Reproduction

python -m lmdeploy.pytorch.chat ${NAME_OR_PATH_TO_LLM} \
    --max_new_tokens 256 \
    --temperature 0.8 \
    --top_p 0.95 \
    --seed 0

**Comment by creegon** [comment]
解决了。。因为代码中是：
model.generate(torch.tensor([[6]], device=get_local_rank()), warmup_config)
所以也要把warmup_config的初始化加上eos_token_id和pad_token_id这两个参数才行。。
完整代码如下：
    warmup_config = GenerationConfig(
        max_new_tokens=1,
        do_sample=temperature > 0,
        temperature=temperature,
        top_p=top_p,
        eos_token_id=tokenizer.eos_token_id,
        pad_token_id=tokenizer.pad_token_id if tokenizer.pad_token_id is not None else tokenizer.eos_token_id,   
    )

**Comment by lvhan028** [comment]
@creegon Could you please open a PR?

**Comment by zhulinJulia24** [comment]
> @creegon Could you please open a PR?

the issue still on newest version, I  can still reproduce it by using internlm-chat-20b model. it's ok on internlm-chat-7b model.
