### ISSUE TITLE
[Feature] 将来是否会支持lnternLM-XComposer-VL的推理

### ISSUE THREAD

**Issue by pangr** [InternLM/lmdeploy#659]
### Motivation

将来是否会支持lnternLM-XComposer-VL的推理

**Comment by lvhan028** [comment]
没有排在今年的计划中。我们先加入backlog

**Comment by lvhan028** [comment]
优先级提升，下周内部会讨论并确定方案

**Comment by lvhan028** [comment]
Ongoing

**Comment by will-wiki** [comment]
@lvhan028 想问下LMDeploy什么时候会支持lnternLM-XComposer-VL的推理呢

**Comment by lvhan028** [comment]
预计12.15

**Comment by irexyc** [comment]
@will-wiki 你是想要多模态对话，还是那个视频创作？

**Comment by will-wiki** [comment]
@irexyc 多模态对话吧，文章创作指的是图文交错的那个么？是12.15会支持多模态对话，那文章创作后面也会支持么？

**Comment by irexyc** [comment]
@will-wiki 
“文章创作”基本上是在多模态对话的基础上，添加了很多逻辑调用。感觉lmdeploy这边封装他们的逻辑不是很合适，暂时还没有计划。

**Comment by will-wiki** [comment]
@lvhan028 @irexyc 你好，看到LMDeploy新更新了一个版本，提供了embedding的输入接口，想问下现在是已经支持了lnternLM-XComposer模型了吗，有没有相关参考文档呢～，另外想问下现在的部署是封装了整个lnternLM-XComposer模型还是只是支持了底座lnternLM的embedding输入呢

**Comment by irexyc** [comment]
@will-wiki 

> 另外想问下现在的部署是封装了整个lnternLM-XComposer模型还是只支持了底座lnternLM的embedding输入呢

图像特征的部分，直接复用xcomposer那边的了， 大概流程就是 pytorch 提图片特征 + prompt text 喂给TurboMind做推理。

我再整理一下demo，明天发出来。支持了xcomposer-7b的对话，到时候你再看下吧。

**Comment by irexyc** [comment]
@will-wiki 

可以试用一下，提些意见
https://github.com/irexyc/lmdeploy/tree/vl-demo/examples/vl

**Comment by will-wiki** [comment]
@irexyc 好嘞，十分感谢！
