### ISSUE TITLE
一堆bug，代码都不一致

### ISSUE THREAD

**Issue by lanse-sir** [InternLM/lmdeploy#660]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

教程中的展示的代码包含的函数，源码中就没有

### Reproduction

Traceback (most recent call last):
  File "d:\pycharmproject\fast_api\lmdeploy_test.py", line 4, in <module>
    from lmdeploy.serve.openai.api_client import APIClient
ImportError: cannot import name 'APIClient' from 'lmdeploy.serve.openai.api_client' (D:\miniconda3\lib\site-packages\lmdeploy\serve\openai\api_client.py)

**Comment by sjzhou4** [comment]
他这个确实修改了，你可以看之前老版本的一些命令，例如lmdeploy convert internlm-chat-7b /path/to/internlm-chat-7b是 
    python3 -m lmdeploy.serve.turbomind.deploy internlm-chat-7b /path/to/internlm-chat-7b等等

**Comment by AllentDan** [comment]
https://github.com/InternLM/lmdeploy/blob/11d10930bd0aa808332d1019354968baf871dae6/lmdeploy/serve/openai/api_client.py#L17
有，还没发版。用的什么版本的代码看什么版本的文档

**Comment by lanse-sir** [comment]
pip install lmdeploy 目前安装的 v0.0.13版本，不是现在的main分子下的

**Comment by AllentDan** [comment]
嗯，看v0.0.13 的文档吧。https://github.com/InternLM/lmdeploy/tree/v0.0.13/docs
如果想现在用main的部分功能，可以下面脚本安装main：
```shell
#!/bin/bash

# 安装lmdeploy
pip install -U lmdeploy
# 获取安装lmdeploy的位置下的lib文件夹路径
lmdeploy_dir=$(pip show lmdeploy | grep Location | cut -d' ' -f2)
lib_dir="${lmdeploy_dir}/lmdeploy/lib"

# 检查lib目录是否存在
if [ ! -d "$lib_dir" ]
then
    echo "Lib directory does not exist at ${lib_dir}"
    exit 1
fi

# 克隆lmdeploy的仓库
git clone https://github.com/InternLM/lmdeploy.git || exit 1

# 将lib文件夹拷贝到刚刚克隆的lmdeploy下
cp -r "$lib_dir" "lmdeploy/lmdeploy/" || exit 1

pip uninstall -y lmdeploy
cd lmdeploy
pip install -e .
```

**Comment by AllentDan** [comment]
没问题就关issue了，有新问题可以重开或者发新issue。
