### ISSUE TITLE
qwen-14b-w4 tp=2时无法转换成turbomind

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#666]
如题，qwen-14b-w4 (awq生成) 设置 tp=2 时，lmdeploy convert报错了

<img width="1320" alt="image" src="https://github.com/InternLM/lmdeploy/assets/6971044/cf1cf3d2-e81a-4f3c-927d-93643d1f5e1f">

**Comment by lvhan028** [comment]
恩。已知问题。group_size=128量化后，权重维度不能被TP整除了

**Comment by AU-CPU** [comment]
请问最新版本的代码出现ModuleNotFoundError: No module named '_turbomind'是什么问题呢

**Comment by lvhan028** [comment]
pip install lmdeploy==0.0.13 安装的吗

**Comment by lvhan028** [comment]
源码咋装的？源码安装的时候，就不要pip install lmdeploy了

**Comment by lvhan028** [comment]
可以看下 build.md 文档

**Comment by AU-CPU** [comment]
> 源码咋装的？源码安装的时候，就不要pip install lmdeploy了

现在是最新版本的源码，和0.013的pip安装版本 因为我看源码比pip安装的更新 使用命令行 python3 -m lmdeploy.turbomind.deploy.converter  --model-name qwen --model-path xxx --dst_path xxx --tp 4 --model-format awq --group-size 128 后出现ModuleNotFoundError: No module named '_turbomind'

**Comment by lvhan028** [comment]
关于安装的事情，可以在另开一个issue讨论。就不在这个issue中盖楼了。毕竟这个issue是关于qwen-14b-w4 tp2的
