### ISSUE TITLE
[Bug] 找不到bin文件夹

### ISSUE THREAD

**Issue by hxdbf** [InternLM/lmdeploy#667]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

[GPU Memory Test](https://github.com/InternLM/lmdeploy/blob/main/docs/en/kv_int8.md#gpu-memory-test)中，Testing method里第二步中的bin/llama_triton_example没找到，事实上没有bin这个文件夹

### Reproduction

The test object is the [internlm-chat-7b](https://huggingface.co/internlm/internlm-chat-7b-v1_1) model. Testing method:

1.Use deploy.py to convert the model, modify the maximum concurrency in the workspace configuration; adjust the number of requests in llama_config.ini.
2.Compile and run bin/llama_triton_example to obtain the GPU memory situation of the fp16 version under different batch_size.
3.Enable quantization, re-run bin/llama_triton_example to obtain the GPU memory situation of the int8 version under different batch_size.

### Environment

```Shell
None
```

**Comment by lvhan028** [comment]
Yes. LMDeploy didn't pack `llama_triton_example` to the released python package. 
You have to build lmdeploy from source.
https://github.com/InternLM/lmdeploy/blob/main/docs/en/build.md#build-in-localhost-optional
