### ISSUE TITLE
[Bug]  LlamaTritonModel.cc  ft::FT_CHECK(pipeline_para.world_size_ = pipeline_para_size_); 写法似乎有问题

### ISSUE THREAD

**Issue by wenjunlong** [InternLM/lmdeploy#668]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

   src/turbomind/triton_backend/llama/LlamaTritonModel.cc，以下两行代码的的表述不一致，一个是判等，一个是赋值

    ft::FT_CHECK(tensor_para.world_size_ == tensor_para_size_);
    ft::FT_CHECK(pipeline_para.world_size_ = pipeline_para_size_);

### Reproduction

   src/turbomind/triton_backend/llama/LlamaTritonModel.cc，以下两行代码的的表述不一致，一个是判等，一个是赋值

    ft::FT_CHECK(tensor_para.world_size_ == tensor_para_size_);
    ft::FT_CHECK(pipeline_para.world_size_ = pipeline_para_size_);

### Environment

```Shell
无
```

**Comment by lvhan028** [comment]
@lzhangzz May fix it in PR #590
