### ISSUE TITLE
[Bug] restful api服务并发请求，请求速度慢

### ISSUE THREAD

**Issue by hk8805** [InternLM/lmdeploy#670]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

使用lmdeploy serve api_server ./workspace --server_name 0.0.0.0 --server_port 8093 --instance_num 256 --tp 1建立restapi服务，并发100个请求同时请求模型服务，GPU占用只能达到一半，调整instance_num无变化，看日志单次请求速度无变化，但1并发100请求完成速度慢
<img width="625" alt="截屏2023-11-09 下午5 05 23" src="https://github.com/InternLM/lmdeploy/assets/24692695/cb638a17-1f02-4cd0-9802-4d405a197ec6">

### Reproduction

lmdeploy serve api_server ./workspace --server_name 0.0.0.0 --server_port 8093 --instance_num 256 --tp 1

### Environment

```Shell
v100 32G
```

**Comment by lvhan028** [comment]
并发100个请求是怎么发的？

**Comment by hk8805** [comment]
> 并发100个请求是怎么发的？

<img width="176" alt="image" src="https://github.com/InternLM/lmdeploy/assets/24692695/5c88a0a0-3ce9-4f52-946a-6abd37151533">
每个test.sh里面都是10000个问题的循环请求restful_api

**Comment by lvhan028** [comment]
test.sh 可以分享下吗？对了，用的是lmdeploy哪个版本呢？

**Comment by hk8805** [comment]
> test.sh 可以分享下吗？对了，用的是lmdeploy哪个版本呢？
这个是test.sh
<img width="401" alt="image" src="https://github.com/InternLM/lmdeploy/assets/24692695/a30e7712-685f-4069-90df-2f74b93b3624">
lmdeploy用的是https://github.com/InternLM/lmdeploy/issues/652里面给的新版本代码

**Comment by lvhan028** [comment]
session_id得不同才行，不然会被认为是同一个对话序列的

**Comment by lvhan028** [comment]
等我们发了v0.0.14后，你再试试

**Comment by hk8805** [comment]
> 等我们发了v0.0.14后，你再试试

大概是什么时候发布

**Comment by lvhan028** [comment]
明天

**Comment by hk8805** [comment]
> 明天

在调整了session_id之后，GPU占用明显提升了.
但是在开了10个并发的情况下，单个并发请求返回时间相比较于无并发时，提升了3倍，请问这个是正常的吗

**Comment by lvhan028** [comment]
你是说第一个token返回的时间吗？

**Comment by hk8805** [comment]
> 你是说第一个token返回的时间吗？

最后一个token，我限制了输出长度为32

**Comment by lvhan028** [comment]
具体的token_latency, token_throughput结果贴上来看看吧。
你可以用 benchmark/profile_restful_api.py 看看结果。
我找台 v100，也测试下看看

**Comment by hk8805** [comment]
> benchmark/profile_restful_api.py

我用的internlm-chat-7b模型，
在循环遍历请求10000个prompt后，平均请求返回耗时在800ms左右。
在设置20并发同时循环遍历请求10000个prompt后，平均请求返回耗时在2000ms左右

**Comment by hk8805** [comment]
> 具体的token_latency, token_throughput结果贴上来看看吧。
> 你可以用 benchmark/profile_restful_api.py 看看结果。
> 你用的哪个模型？我找台 v100，也测试下看看

我也有尝试并发降到10，平均返回耗时会降到1200ms左右

**Comment by hk8805** [comment]
> 具体的token_latency, token_throughput结果贴上来看看吧。
> 你可以用 benchmark/profile_restful_api.py 看看结果。
> 你用的哪个模型？我找台 v100，也测试下看看

选取了1000个样本，20并发，每个并发50个样本，这个是最终耗时
<img width="545" alt="image" src="https://github.com/InternLM/lmdeploy/assets/24692695/b75c3973-4d03-4024-9f20-746b414da793">

**Comment by hk8805** [comment]
> > 具体的token_latency, token_throughput结果贴上来看看吧。
> > 你可以用 benchmark/profile_restful_api.py 看看结果。
> > 你用的哪个模型？我找台 v100，也测试下看看
> 
> 选取了1000个样本，20并发，每个并发50个样本，这个是最终耗时 <img alt="image" width="545" src="https://user-images.githubusercontent.com/24692695/282047762-b75c3973-4d03-4024-9f20-746b414da793.png">

@lvhan028 大佬，麻烦帮忙再看下

**Comment by lvhan028** [comment]
刚找到一台 V100 服务器。我等下试试看

**Comment by lvhan028** [comment]
我用的是单卡 V100。
profile_restful_api.py 在我这边没有成功。

我用了 profile_throughput.py 试了下。

- concurrency = 1
```
CUDA_VISIBLE_DEVICES=1 python3 benchmark/profile_throughput.py ShareGPT_V3_unfiltered_cleaned_split.json /workspace/models/llm_models/turbomind_models/internlm-chat-7b-v1_1/ --concurrency 1 --stream_output True --num_prompts 100
```
结果是：
```
concurrency: 1
elapsed_time: 462.719s

first_token latency(min, max, ave): 0.064s, 0.064s, 0.064s

number of prompt tokens: 17595
number of completion tokens: 21656
token throughput (completion token): 46.802 token/s
token throughput (prompt + completion token): 84.827 token/s
RPS (request per second): 0.216 req/s
RPM (request per minute): 12.967 req/min
```
- concurrency=4
```
CUDA_VISIBLE_DEVICES=1 python3 benchmark/profile_throughput.py ShareGPT_V3_unfiltered_cleaned_split.json /workspace/models/llm_models/turbomind_models/internlm-chat-7b-v1_1/ --concurrency 8 --stream_output True --num_prompts 100
```
结果是：
```
concurrency: 4
elapsed_time: 135.569s

first_token latency(min, max, ave): 0.066s, 1.028s, 0.322s

number of prompt tokens: 17595
number of completion tokens: 21654
token throughput (completion token): 159.727 token/s
token throughput (prompt + completion token): 289.513 token/s
RPS (request per second): 0.738 req/s
RPM (request per minute): 44.258 req/min
```
总时间是变少的。

**Comment by hk8805** [comment]
> 我用的是单卡 V100。 profile_restful_api.py 在我这边没有成功。
> 
> 我用了 profile_throughput.py 试了下。
> 
> * concurrency = 1
> 
> ```
> CUDA_VISIBLE_DEVICES=1 python3 benchmark/profile_throughput.py ShareGPT_V3_unfiltered_cleaned_split.json /workspace/models/llm_models/turbomind_models/internlm-chat-7b-v1_1/ --concurrency 1 --stream_output True --num_prompts 100
> ```
> 
> 结果是：
> 
> ```
> concurrency: 1
> elapsed_time: 462.719s
> 
> first_token latency(min, max, ave): 0.064s, 0.064s, 0.064s
> 
> number of prompt tokens: 17595
> number of completion tokens: 21656
> token throughput (completion token): 46.802 token/s
> token throughput (prompt + completion token): 84.827 token/s
> RPS (request per second): 0.216 req/s
> RPM (request per minute): 12.967 req/min
> ```
> 
>  * concurrency=4
> 
> ```
> CUDA_VISIBLE_DEVICES=1 python3 benchmark/profile_throughput.py ShareGPT_V3_unfiltered_cleaned_split.json /workspace/models/llm_models/turbomind_models/internlm-chat-7b-v1_1/ --concurrency 8 --stream_output True --num_prompts 100
> ```
> 
> 结果是：
> 
> ```
> concurrency: 4
> elapsed_time: 135.569s
> 
> first_token latency(min, max, ave): 0.066s, 1.028s, 0.322s
> 
> number of prompt tokens: 17595
> number of completion tokens: 21654
> token throughput (completion token): 159.727 token/s
> token throughput (prompt + completion token): 289.513 token/s
> RPS (request per second): 0.738 req/s
> RPM (request per minute): 44.258 req/min
> ```
> 
> 总时间是变少的。

<img width="523" alt="image" src="https://github.com/InternLM/lmdeploy/assets/24692695/02e2f7ef-15ab-42ea-b658-9121de489873">
<img width="531" alt="image" src="https://github.com/InternLM/lmdeploy/assets/24692695/357c5e13-abbe-48fa-b84d-53bd4e9d0969">
总时间变少没问题，但变少是因为总样本量不变，多并发后，每个线程需要处理的样本量变小了，按理来说线程数增加多少倍，消耗时间应该减少多少倍，但是实际上并不是这样，而且线程数越多，问题越明显

**Comment by lvhan028** [comment]
“线程数增加多少倍，消耗时间应该减少多少倍” 并不是这样的。

**Comment by hk8805** [comment]
> “线程数增加多少倍，消耗时间应该减少多少倍” 并不是这样的。
> 多个线程的请求在推理侧会拼成一个batch进行推理。
> 在并发数量小于max_batch_size时，可以简单的认为，并发数量=batch数量。
> 那么问题就等价于，batch=1，batch=n相比，是不是batch=n要比batch=1快n倍。
> 答案：不是。

那使用量化后的模型进行推理能不能显著提升推理速度？
另外能不能在modelscope上传一份量化后的模型文件，https://huggingface.co/lmdeploy/turbomind-internlm-chat-7b-w4/tree/main，这个文件内网无法下载，在云服务器上测试比较麻烦

**Comment by lvhan028** [comment]
量化模型可以显著提升速度。不过 lmdeploy的量化模型推理不支持 v100 架构（sm70 的tensor core指令和sm80 不一样太多了）
在modelscope上有internlm-chat-20b的量化模型：
https://modelscope.cn/models/InternLMadmin/internlm-chat-20b-4bit/summary
7b的话，我们等下也放一份

**Comment by hk8805** [comment]
> 量化模型可以显著提升速度。不过 lmdeploy的量化模型推理不支持 v100 架构（sm70 的tensor core指令和sm80 不一样太多了）
> 在modelscope上有internlm-chat-20b的量化模型：
> https://modelscope.cn/models/InternLMadmin/internlm-chat-20b-4bit/summary
> 7b的话，我们等下也放一份

还有什么参数可以提升推理速度的吗，除了缩短输出内容长度

**Comment by lvhan028** [comment]
等我们发布 v0.1 版本后，可以再试试看。预计下周

**Comment by hk8805** [comment]
> 等我们发布 v0.1 版本后，可以再试试看。预计下周

更新的内容大致会有哪些，我们评估一下

**Comment by lvhan028** [comment]
first token latency是在client测统计的。从请求一发出就开始算。
具体请参考 benchmark/profile_restful_api.py的实现。

**Comment by lvhan028** [comment]
Closing it since no more activities for a long time
Feel free to reopen it if it is still an issue

**Comment by datalee** [comment]
> 单个并发请求返回时间相比较于无并发时，提升了3倍，请问这个是正常的吗

我这边在v100上也有类似的结论，1并发1秒多，2并发2秒多，4并发4秒多【那么这个框架要怎么提高并发或者每秒生成的token数】
![image](https://github.com/InternLM/lmdeploy/assets/13651873/6bd6e398-afa6-4423-b3c7-4ac58eab724f)

**Comment by datalee** [comment]
启动命令：`CUDA_VISIBLE_DEVICES=3 nohup lmdeploy serve api_server ./internlm2-chat-7b-turbomind-2 --server-name 0.0.0.0 --server-port 8333 --tp 1 --cache-max-entry-count 0.2 --rope-scaling-factor 0.2 --session-len 32000 &
`

**Comment by datalee** [comment]
@lvhan028 帮忙看下我的问题，感谢
