### ISSUE TITLE
qwen-14b-int4 多于一个ip请求，OOM

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#675]
你好，我用一张A10卡 serving qwen-14b-int4（使用awq量化）。服务启动后，显存占用19G。

当我用两个ip分别串行请求openapi接口(streaming关闭)，服务就OOM了，prompt长度只有8。

请问是什么原因呢？谢谢！

**Comment by lvhan028** [comment]
v0.0.14 版本吗

**Comment by AllentDan** [comment]
api_server 启动时，--instance_num 设置1吧

**Comment by frankxyy** [comment]
> v0.0.14 版本吗

v0.0.11

**Comment by frankxyy** [comment]
> api_server 启动时，--instance_num 设置1吧

你好，请问下这个instance_num的设置规则是？

**Comment by frankxyy** [comment]
刚才试了下，设置instance_num为1，也会OOM

**Comment by AllentDan** [comment]
那不应该只有两个请求出现这问题，一个请求就会 OOM。显存确实超了吧

**Comment by AllentDan** [comment]
要不试试最新的0.0.14吧，转换啥的都有更新

**Comment by frankxyy** [comment]
> 那不应该只有两个请求出现这问题，一个请求就会 OOM。显存确实超了吧

一个请求不会OOM，我先升级0.0.14 再测试下哈

**Comment by frankxyy** [comment]
更新至0.0.14 后，此问题未出现
