### ISSUE TITLE
量化参数的选择

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#677]
你好，在试用lmdeploy提供的awq量化功能，想请教下，对于一些量化参数该如何选择以达到最好的效果呢。

包括： calib_dataset、calib_samples、calib_seqlen、w_group_size。

谢谢！

**Comment by pppppM** [comment]
group_size 目前只能是 128，其他的参数对性能基本没影响，我们有使用过 OpenCompass 进行验证，AWQ 量化后各种指标没有下降

**Comment by frankxyy** [comment]
@pppppM 了解了，非常感谢！
