### ISSUE TITLE
[Feature] Does lmdeploy support Yi-34B?

### ISSUE THREAD

**Issue by amulil** [InternLM/lmdeploy#678]
If it doesn't support, what should I change to support it?

**Comment by lvhan028** [comment]
@AllentDan may provide some guide

**Comment by AllentDan** [comment]
1.  compare Yi with llama, and check if it can be built by changing the parameters of llama. Or else, you have to add a new model into https://github.com/InternLM/lmdeploy/tree/main/src/turbomind/models
2. if Yi shares the same model structure with llama. Register a chat template in https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/model.py
3. convert Yi to turbomind with the name you registered.

**Comment by amulil** [comment]
> 1. compare Yi with llama, and check if it can be built by changing the parameters of llama. Or else, you have to add a new model into https://github.com/InternLM/lmdeploy/tree/main/src/turbomind/models
> 2. if Yi shares the same model structure with llama. Register a chat template in https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/model.py
> 3. convert Yi to turbomind with the name you registered.

thanks, I will see it.

**Comment by amulil** [comment]
> 1. changing the parameters of llama

@AllentDan In lmdeploy, where  can I change the parameters of llama?

**Comment by AllentDan** [comment]
Seems Yi can be converted to turbomind directly through model name `llama2`. #728

**Comment by amulil** [comment]
> 2\. https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/model.py

@AllentDan 
Nice, I'll try it. I have another question, Where I can change the chat template when I use `lmdeploy server`.

**Comment by AllentDan** [comment]
What's the relation wht qwen? Just add a new chat template class for Yi. `model_name` is what you put during converting model to turbomind. And the `model_name` is in the list of `lmdeploy list`. You can use other chat template by changing model_name directly in `config.ini`. But there are maybe other settings need to be changed. So, that's not suggested.

**Comment by amulil** [comment]
> What's the relation wht qwen? Just add a new chat template class for Yi. `model_name` is what you put during converting model to turbomind. And the `model_name` is in the list of `lmdeploy list`. You can use other chat template by changing model_name directly in `config.ini`. But there are maybe other settings need to be changed. So, that's not suggested.

thanks for your replay, I just use the qwen chat template to sft yi.
