### ISSUE TITLE
支持max_batch_total_tokens batching参数

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#683]
你好，现在我看lmdeploy batching的参数限制是session_len和max_batch_size，是否可以像TGI那样支持 max_batch_total_tokens batching，以实现对于整体token数的batching限制，这样当不同sequence长短不一时可以更高效利用显存。谢谢!

**Comment by lvhan028** [comment]
main分支上已经实现了 Paged Attention，k/v cache按block管理，显存利用率提升很多。
预计下周发布 v0.1 alpha，优化效果显著。

**Comment by frankxyy** [comment]
@lvhan028 hi，还想问下哈，除了paged attention这块，我上面说的batching限制这块是否也可以优化下？
