### ISSUE TITLE
[Bug] CUDA runtime error: out of memory

### ISSUE THREAD

**Issue by RytonLi** [InternLM/lmdeploy#684]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

模型：llama2-70B
设备：A100/40G × 4
lmdeploy版本：0.0.10

设置tp=4，持续运行时显存一直缓慢增长直到oom，以下是模型配置参数，如何排查问题？
![image](https://github.com/InternLM/lmdeploy/assets/103549265/f0ed874a-0a67-4596-8780-7594640feaef)

### Reproduction

参考example/cpp/llama/llama_triton_example.cc实现

### Environment

```Shell
ubuntu-16.04
cuda-11.4
```

### Error traceback
![image](https://github.com/InternLM/lmdeploy/assets/103549265/e39c6768-6fb8-4a88-a578-14b48e5587ee)

**Comment by lzhangzz** [comment]
cache_max_entry_count设置kv cache最多保存的sequence数量

fp16 kv cache内存开销的公式为
```
kv_cache_in_bytes = cache_max_entry_count * session_len * num_layer * kv_head_num * size_per_head * 2 * 2
```
cache_max_entry_count=48的时候算出来需要60G，加上权重的140G，4xA100/40G存不下

**Comment by RytonLi** [comment]
后续将cache_max_entry_count调整为12仍然出现同样的问题。按照你的公式， kv cache开销为15G，加上权重140G，小于160G。请问一个batch计算所需的内存开销怎么计算？

**Comment by sjzhou4** [comment]
@RytonLi 这里的cache_max_entry_count默认和config.pbtxt里面的
instance_group [
  {
    # max concurrent instances
    count: 48
    kind: KIND_CPU
  }
]
是一致的，这里面的48也是并发的路数，同时处理48就会出现占用：
kv_cache_in_bytes = cache_max_entry_count * session_len * num_layer * kv_head_num * size_per_head * 2 * 2
显存，如果要保证不出现OOM，可以按照加载完模型后剩余的显存计算最大的并发数目，然后将config.pbtxt里面的count: 48设置生最大并发数，这样就不会出现OOM了。
