### ISSUE TITLE
[Bug] 将AsyncEngine删除后仍会有一部分显存占用，怎么清空显存？

### ISSUE THREAD

**Issue by jjjjohnson** [InternLM/lmdeploy#691]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

加载engin显存占用：18327MiB   -> 释放后 4604MiB 

### Reproduction

```
import gc
from lmdeploy.serve.async_engine import AsyncEngine
import torch
model_path = '/workspace/all_models/tp1/Qwen-14B-Chat'
engine = AsyncEngine(model_path=model_path, instance_num=1, tp=1)

del engine

# gc.collect()
# torch.cuda.empty_cache()
```

### Environment

```Shell
v0.0.12
```

**Comment by jjjjohnson** [comment]
把python进程杀掉可以完全释放GPU显存，是不是有显存泄漏？

**Comment by lvhan028** [comment]
LMDeploy的设计是Persistent-Batch。开辟好的用于batch、k/v cache的内存是不会被释放的。
