### ISSUE TITLE
编译 lmdeploy 时报错 'ptxas' died due to signal 11 (Invalid memory reference)

### ISSUE THREAD

**Issue by Time-Limit** [InternLM/lmdeploy#693]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

编译 lmdeploy 时报错 'ptxas' died due to signal 11 (Invalid memory reference)

报错的命令如下，想请教下有什么解决办法吗？或者有什么排查手段么？

/usr/local/cuda/bin/nvcc -forward-unknown-to-host-compiler -DBUILD_MULTI_GPU -DUSE_NVTX --options-file CMakeFiles/flash_attention2.dir/includes_CUDA.rsp -lineinfo -Xcompiler -Wall -ldl -gencode arch=compute_70,code="sm_70,compute_70" -gencode arch=compute_75,code="sm_75,compute_75" -gencode arch=compute_80,code="sm_80,compute_80" -gencode arch=compute_86,code="sm_86,compute_86" -DWMMA --expt-extended-lambda --expt-relaxed-constexpr --std c++17 -DCUDA_PTX_FP8_F2FP_ENABLED -O2 -g -DNDEBUG -Xcompiler -O3 -DCUDA_PTX_FP8_F2FP_ENABLED --use_fast_math -std c++17 --generate-code arch=compute_70,code=[compute_70,sm_70] --generate-code arch=compute_75,code=[compute_75,sm_75] --generate-code arch=compute_80,code=[compute_80,sm_80] --generate-code arch=compute_86,code=[compute_86,sm_86] -Xcompiler -fPIC -MD -MT src/turbomind/models/llama/flash_attention2/CMakeFiles/flash_attention2.dir/flash_fwd_hdim64_fp16_sm80.cu.o -MF CMakeFiles/flash_attention2.dir/flash_fwd_hdim64_fp16_sm80.cu.o.d -x cu -c /workspace/code/lmdeploy/src/turbomind/models/llama/flash_attention2/flash_fwd_hdim64_fp16_sm80.cu -o CMakeFiles/flash_attention2.dir/flash_fwd_hdim64_fp16_sm80.cu.o

![image](https://github.com/InternLM/lmdeploy/assets/17545254/51cdda57-965f-4553-a16c-fdc32dc3df88)

### Reproduction

按照这个[文档](https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/build.md) 的物理机编译部分操作。

### Environment

```Shell
现在是在编译 lmdeploy，所以还没办法执行这个命令。
```

**Comment by Time-Limit** [comment]
GPU 4090；cuda 12.2；ubuntu 22.04；

**Comment by Time-Limit** [comment]
修改 generate.sh 后可以编译成功了。
![image](https://github.com/InternLM/lmdeploy/assets/17545254/e7ed013a-7c42-4f99-abc9-a5f495aee91a)

**Comment by lvhan028** [comment]
cuda12.x is supported by #754
