### ISSUE TITLE
[Feature] Distributed inference using multiple machines

### ISSUE THREAD

**Issue by sleepwalker2017** [InternLM/lmdeploy#706]
### Motivation

Is this supported? I mean, using multiple machines to run on instance.

**Comment by lvhan028** [comment]
TP or DP?

**Comment by sleepwalker2017** [comment]
> TP or DP?

hello，我理解可能是不同的机器间使用流水线并行，然后同一台机器上的卡使用 Tensor 并行。LMDeploy 可以通过配置完成这样的功能吗？感谢！

**Comment by lvhan028** [comment]
现在不支持 PP，短期内也没有做PP的计划

**Comment by sleepwalker2017** [comment]
> 现在不支持 PP，短期内也没有做PP的计划

好的了解。如果想在多机之间使用 tensor 并行，有相关的文档可以参考下吗？感谢

**Comment by zhudongwork** [comment]
> > 现在不支持 PP，短期内也没有做PP的计划
> 
> 好的了解。如果想在多机之间使用 tensor 并行，有相关的文档可以参考下吗？感谢

有找到解决方案不，原生的fastertransformer+Triton好像可以

**Comment by sleepwalker2017** [comment]
> > > 现在不支持 PP，短期内也没有做PP的计划
> > 
> > 
> > 好的了解。如果想在多机之间使用 tensor 并行，有相关的文档可以参考下吗？感谢
> 
> 有找到解决方案不，原生的fastertransformer+Triton好像可以

MPI + NCCL 应该可以解决。不过我这边机器有一些问题，一直没跑通。
