### ISSUE TITLE
[Feature]  Please support Deepseek 

### ISSUE THREAD

**Issue by Spockhh** [InternLM/lmdeploy#707]
### Motivation

Deepseek model converting is failed. Can you help to support this model?

**Comment by lvhan028** [comment]
Branch https://github.com/InternLM/lmdeploy/tree/linear-rope-scale supports `deepseek` now
We'll release it in version v0.2.3

**Comment by lvhan028** [comment]
最新的 main 分支，支持了 deepseek-coder, deepseek-chat 模型。会在月底的版本发布
