### ISSUE TITLE
[Bug] Segmentation fault

### ISSUE THREAD

**Issue by roundXin** [InternLM/lmdeploy#710]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

用lmdeploy convert llama2 ./llama2_chinese_chat_13b命令进行模型转换后会出现Segmentation fault，使用lmdeploy chat turbomind ./workspace时也会出现Segmentation fault，但能正常使用lmdeploy serve gradio ./workspace。
![image](https://github.com/InternLM/lmdeploy/assets/70061450/5d730bfb-2f9d-4ab6-abf6-8ada7542e817)

### Reproduction

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 lmdeploy convert llama2 /data/lvsiqin/pre_models_dir/llama2_chinese_13_chat --tp 8

### Environment

```Shell
centos7.9
cuda Driver 12.2
8块V100 40G
```

### Error traceback

```Shell
![image](https://github.com/InternLM/lmdeploy/assets/70061450/a0628baf-35f1-4ce4-ba09-34c55a2c1f90)
```

**Comment by roundXin** [comment]
![image](https://github.com/InternLM/lmdeploy/assets/70061450/542a9103-248d-4518-84a3-6978313b6102)

**Comment by lvhan028** [comment]
使用的 lmdeploy 版本是？
能否给一个模型下载路径？

**Comment by roundXin** [comment]
> 使用的 lmdeploy 版本是？ 能否给一个模型下载路径？
 lmdeploy版本：0.0.14，也试过0.0.13/12/11/10,都是相同错误
模型下载路径：https://huggingface.co/FlagAlpha/Llama2-Chinese-13b-Chat

**Comment by lvhan028** [comment]
@AllentDan may help investigate it

**Comment by AllentDan** [comment]
We did not support cuda 12+.

**Comment by lvhan028** [comment]
奇怪。“但能正常使用lmdeploy serve gradio ./workspace”， 这个也是用的turbomind推理的。

**Comment by AllentDan** [comment]
将下面这行注释掉再次执行转换试试
https://github.com/InternLM/lmdeploy/blob/73386e217cc092e02a5c256e8cf6ce1475b8c6c8/lmdeploy/turbomind/deploy/target_model/w4.py#L17
如果转换结束后不报 segmentation fault，就是说明是 turbomind 在错误的 cuda 版本下释放会报错。行为本身不被预期

**Comment by roundXin** [comment]
> 将下面这行注释掉再次执行转换试试
> 
> https://github.com/InternLM/lmdeploy/blob/73386e217cc092e02a5c256e8cf6ce1475b8c6c8/lmdeploy/turbomind/deploy/target_model/w4.py#L17
> 
> 
> 如果转换结束后不报 segmentation fault，就是说明是 turbomind 在错误的 cuda 版本下释放会报错。行为本身不被预期

<img width="507" alt="1700474686899" src="https://github.com/InternLM/lmdeploy/assets/70061450/8badd85e-46dd-4f08-ae00-06621d2098e8">
<img width="956" alt="1700474686915" src="https://github.com/InternLM/lmdeploy/assets/70061450/fcc1b54f-9ed3-4c00-b2cb-d9b0ac768d18">

刚试了，还是会报这个错误。

**Comment by roundXin** [comment]
> 我们不支持 cuda 12+。

请问下，什么时候能支持cuda12+呢

**Comment by lvhan028** [comment]
cuda 12 还没有排上计划。等我们手头的一些feature完成后，会来处理这个问题

**Comment by lvhan028** [comment]
@roundXin
当用带cuda12.1的镜像试了下，编译sm75架构会失败。如果你的目标机器是Ampere架构，你可以在 generate.sh 中通过下面两个变量指定cuda架构。试了下，是可以编译成功的
```
-DSM=80 \
-DCMAKE_CUDA_ARCHITECTURES=80 \
```

**Comment by roundXin** [comment]
> @roundXin 当用带cuda12.1的镜像试了下，编译sm75架构会失败。如果你的目标机器是Ampere架构，你可以在 generate.sh 中通过下面两个变量指定cuda架构。试了下，是可以编译成功的
> 
> ```
> -DSM=80 \
> -DCMAKE_CUDA_ARCHITECTURES=80 \
> ```

我没找到generate.sh文件，可以具体说明下吗

现在通过CUDA_VISIBLE_DEVICES=0 lmdeploy serve gradio ./workspace --tp 1是可以使用的，但是
CUDA_VISIBLE_DEVICES=0 lmdeploy chat turbomind ./workspace --tp 1
和
CUDA_VISIBLE_DEVICES=0 lmdeploy serve api_server ./workspace --tp 1
运行时会报Segmentation fault
(https://github.com/InternLM/lmdeploy/issues/710#top)
<img width="650" alt="1700558030815" src="https://github.com/InternLM/lmdeploy/assets/70061450/df84bee7-6059-4db2-b328-dc3eedc20675">

**Comment by lvhan028** [comment]
奇怪，gradio、chat、api_server都是走turbomind.py的接口。
你你用的 lmdeploy 版本是哪个？
llama2_chinese_13_chat，这个模型能给个下载路径吗？我们复现下看看。

**Comment by roundXin** [comment]
> lmdeploy版本：0.0.14，也试过0.0.13/12/11/10,都是相同错误
> 模型下载路径：https://huggingface.co/FlagAlpha/Llama2-Chinese-13b-Chat

lmdeploy版本：0.0.14
模型下载路径：https://huggingface.co/FlagAlpha/Llama2-Chinese-13b-Chat

**Comment by roundXin** [comment]
> 奇怪，gradio、chat、api_server都是走turbomind.py的接口。 你你用的 lmdeploy 版本是哪个？ llama2_chinese_13_chat，这个模型能给个下载路径吗？我们复现下看看。

lmdeploy版本：0.0.14
模型下载路径：https://huggingface.co/FlagAlpha/Llama2-Chinese-13b-Chat

**Comment by AllentDan** [comment]
Fixed in the latest lmdeploy.
