### ISSUE TITLE
增加并发GPU占用不提升，效率不提升

### ISSUE THREAD

**Issue by hk8805** [InternLM/lmdeploy#716]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

当增加服务并发，请求并发后，同样1000个样本请求耗时不变
<img width="472" alt="image" src="https://github.com/InternLM/lmdeploy/assets/24692695/8ac1dda7-323e-4418-a57d-19aaabdc62c9">
<img width="472" alt="image" src="https://github.com/InternLM/lmdeploy/assets/24692695/e8ee2fe1-3458-4993-b349-203caab91f38">
<img width="598" alt="image" src="https://github.com/InternLM/lmdeploy/assets/24692695/6e3697a4-f03a-43fc-a972-b236ae44e1fd">
服务启动命令lmdeploy serve api_server ./workspace --server_name 0.0.0.0 --server_port 8000 --instance_num 1000 --tp 2
请求命令 python profile_restful_api.py \
    http://127.0.0.1:8000 \
    workspace/triton_models/tokenizer \
    --concurrency 1000

### Reproduction

服务启动命令lmdeploy serve api_server ./workspace --server_name 0.0.0.0 --server_port 8000 --instance_num 1000 --tp 2
请求命令 python profile_restful_api.py \
    http://127.0.0.1:8000 \
    workspace/triton_models/tokenizer \
    --concurrency 1000

### Environment

```Shell
None
```

**Comment by lvhan028** [comment]
显存的占用是受配置约束的。
希望下面这篇文档能够帮到你：
https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/turbomind_config.md

**Comment by hk8805** [comment]
> 显存的占用是受配置约束的。
> 希望下面这篇文档能够帮到你：
> https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/turbomind_config.md

是更改max_batch_size这个值吗

**Comment by lvhan028** [comment]
是的。

**Comment by hk8805** [comment]
> 是的。

<img width="308" alt="image" src="https://github.com/InternLM/lmdeploy/assets/24692695/48b71da2-56e9-4151-a2e8-71c2833f9ee9">
提升对应配置值之后，GPU占用并未改变

**Comment by lvhan028** [comment]
并发你用的多大？
每个并发都要有自己独立的session_id 才可以

**Comment by hk8805** [comment]
> 并发你用的多大？
> 每个并发都要有自己独立的session_id 才可以

我用的64，我用profile_restful_api.py 测的，代码里面会单独分配session_id

**Comment by lvhan028** [comment]
手边没有T4，等下我在A100上试下看看。

**Comment by hk8805** [comment]
> 手边没有T4，等下我在A100上试下看看。

大佬，有试吗

**Comment by lvhan028** [comment]
等下，马上。
对了，之前没有留意到问题里的一些细节：
 --instance_num 1000 表示开1000个线程，这也太夸张了。
T4的显存已经消耗了近 90% 了，再多就爆显存了。

**Comment by lvhan028** [comment]
对于 lmdeploy 来说，当请求的并发数超过了配置中的 max_batch_size 后，超出的请求都得排队等待

**Comment by lvhan028** [comment]
转完模型之后，啥配置都不修改的情况下。我测试了如下几组：
```
 python benchmark/profile_restful_api.py http://0.0.0.0:23333 /nvme/shared_data/InternLM/internlm-chat-7b/ ShareGPT_V3_unfiltered_cleaned_split.json --concurrency 1
```
![image](https://github.com/InternLM/lmdeploy/assets/4560679/46a346c5-b29f-43da-b932-1c7ca858b02e)

```
 python benchmark/profile_restful_api.py http://0.0.0.0:23333 /nvme/shared_data/InternLM/internlm-chat-7b/ ShareGPT_V3_unfiltered_cleaned_split.json --concurrency 16
```
![image](https://github.com/InternLM/lmdeploy/assets/4560679/0063d226-7643-469d-8f9e-cfce10cd6fc9)

```
 python benchmark/profile_restful_api.py http://0.0.0.0:23333 /nvme/shared_data/InternLM/internlm-chat-7b/ ShareGPT_V3_unfiltered_cleaned_split.json --concurrency 32
```
![image](https://github.com/InternLM/lmdeploy/assets/4560679/32eae5a6-725e-4480-abf4-50d8e4b9a6d3)

```
 python benchmark/profile_restful_api.py http://0.0.0.0:23333 /nvme/shared_data/InternLM/internlm-chat-7b/ ShareGPT_V3_unfiltered_cleaned_split.json --concurrency 48
```
![image](https://github.com/InternLM/lmdeploy/assets/4560679/2483978a-a70a-4b2c-9200-8ff88098f3da)

**Comment by lvhan028** [comment]
For your 2 T4 case, I suggest setting `max_batch_size=16` and `cache_max_entry_count=128`
When you launching api server, make sure `--instance-num` is no larger than `max_batch_size`
And when you run `benchmark/pofile_restful_api.py`, let `concurrency` no large than `max_batch_size` either
