### ISSUE TITLE
config.ini，max_batch_size设置造成coredump

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#721]
你好，下图是我qwen-7b模型的config.ini文件内容：
<img width="427" alt="image" src="https://github.com/InternLM/lmdeploy/assets/6971044/60883cd0-53cf-4e84-bdff-bd56bc0b90b0">

当max_batch_size设置为1时，请求过来直接coredump：
<img width="1395" alt="image" src="https://github.com/InternLM/lmdeploy/assets/6971044/254974ce-e277-4036-852f-89d44c498794">

max_batch_size设置为16时，服务正常。

请问是什么原因呢？谢谢！

**Comment by lvhan028** [comment]
lmdeploy的版本是？

**Comment by frankxyy** [comment]
@lvhan028 0.0.14

**Comment by lvhan028** [comment]
确实是个问题。我们查一下

**Comment by lzhangzz** [comment]
#725
