### ISSUE TITLE
多个client下容易OOM

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#722]
qwen-7b模型，session_len开了8200，instance_num设置为10。跑在23G 单卡A10上。

当10个input_len 50、output_len 128的并发请求过来，就直接OOM了。

但一个1500 input_len的请求过来，是可以serve的。感觉是不是哪里预分配了过多的显存

**Comment by lvhan028** [comment]
如果你用的是 lmdeploy 0.0.x的版本，会出现这种情况。
在 lmdeploy <= v0.0.14 之前，它管理内存的方式过于保留。再即将发布的 lmdeploy v0.1.0a0的版本中，这个问题会得到比较好的解决。

**Comment by frankxyy** [comment]
@lvhan028 hi，有pr嘛？ 想先看看   新版本会支持max_batch_total_tokens配置吗，这样可以确保并发和workload长度变化范围很大的情况下显存占用的稳定性

**Comment by lvhan028** [comment]
最新的main分支就可以。不会支持 max_batch_total_tokens的配置。
lmdeploy现在的策略可以保证显存占用的稳定性

**Comment by lvhan028** [comment]
可以。看下turbomind_config.md文档，里面有k/v cache显存计算的公式。

**Comment by frankxyy** [comment]
> 可以。看下turbomind_config.md文档，里面有k/v cache显存计算的公式。

好的，谢谢啦
