### ISSUE TITLE
[Feature] 在turbomind中是如何选择解码策略，topk和topp这两个参数如何影响最终的解码策略？

### ISSUE THREAD

**Issue by qdddddc** [InternLM/lmdeploy#723]
如题，topk和topp如何作用于解码策略

**Comment by qdddddc** [comment]
@lvhan028 求大佬看

**Comment by lvhan028** [comment]
自回归模型，有若干种生成策略。下面这篇文章讲的非常好，推荐看一下。
https://huggingface.co/blog/zh/how-to-generate

lmdeploy没有支持beam_search，因为在应用场景中，beam_search的表现没有sampling好。所以从开发和维护的角度出发，就没实现它了。

至于 top_k, top_p 如何影响最终的解码策略，上面的文章中就有答案。

**Comment by qdddddc** [comment]
感谢提供文章供参考。这里有个问题想确认下，在turbomind后端中，如果在客户端传了topk=5，topp=0.85，那么topk和topp这两个策略会同时生效吗 @lvhan028

**Comment by lvhan028** [comment]
会的
