### ISSUE TITLE
http_server如何显示详细日志

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#724]
如题，之前用triton server时，会显示forward过程中一些日志，如果使用python http_server，请问如何开启内部日志打印？谢谢!

**Comment by lvhan028** [comment]
得改源码了
https://github.com/InternLM/lmdeploy/blob/42e57c8b22eb4e549578fb20b9ca1194f222e649/lmdeploy/serve/openai/api_server.py#L24
