### ISSUE TITLE
配置项 max_context_token_num 是什么作用

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#725]
你好，想请教下 turbomind config里，max_context_token_num 作用是什么，和session_len 的区别是什么呢？

**Comment by lzhangzz** [comment]
用来限制prefill阶段每个batch处理的最大token数，不然有几个buffer的大小会不受控制。

取值小于session_len时代表session_len的n倍。

**Comment by frankxyy** [comment]
@lzhangzz 明白了，感谢!

**Comment by lzhangzz** [comment]
抱歉记错了，是小于max_batch_size时表示session_len的n倍。😂
