### ISSUE TITLE
main分支最新代码，长文本推理结果不对

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#726]
如题，用当前main分支最新代码(commit 42e57c8)，使用qwen-14b-w4模型，长文本length>4K后，结果会返回空，如：
<img width="1425" alt="image" src="https://github.com/InternLM/lmdeploy/assets/6971044/f28f8d6b-5a91-4857-a946-0c9b2c2e2b78">

相同的模型，用v0.0.14，7K的input，结果仍是正常的。

注：重新生成了turbomind2格式配置文件，config.ini如下图：
<img width="579" alt="image" src="https://github.com/InternLM/lmdeploy/assets/6971044/1045b8f5-b69f-41ad-a9be-5c8109b4b097">

**Comment by lzhangzz** [comment]
main分支ntk alpha的计算公式改成了和transformers对齐的风格，把rope_scaling_factor调大一些试试

**Comment by frankxyy** [comment]
> main分支ntk alpha的计算公式改成了和transformers对齐的风格，把rope_scaling_factor调大一些试试

rope_scaling_factor调大后没问题

**Comment by frankxyy** [comment]
@lzhangzz 

hi，我看main分支最新代码，如果config.ini里没有use_dynamic_ntk，貌似不会计算ntk_alpha
https://github.com/InternLM/lmdeploy/blob/main/src/turbomind/kernels/decoder_masked_multihead_attention/decoder_masked_multihead_attention_template.cuh#L1382C26-L1382C26
