### ISSUE TITLE
[Bug] The answer repeated instruction when I user turbomind chat with Llama2

### ISSUE THREAD

**Issue by zhulinJulia24** [InternLM/lmdeploy#728]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

The answer repeated instruction when I user turbomind chat with Llama2 and yi-6b, 

### Reproduction

**llama2 command**
`lmdeploy convert llama2 /nvme/qa_test_models/Llama-2-7b-chat-hf --dst_path /nvme/qa_test_models/autotest_model/workspace_Llama-2-7b-chat-hf`
`lmdeploy chat turbomind /nvme/qa_test_models/autotest_model/workspace_Llama-2-7b-chat-hf
`
![image](https://github.com/InternLM/lmdeploy/assets/145004780/96b15b94-2025-405a-bd01-64442314338f)

**llama2 w4 command**
`lmdeploy lite calibrate --model /nvme/qa_test_models/Llama-2-7b-chat-hf --calib_dataset 'c4'  --calib_samples 128 --calib_seqlen 2048  --work_dir /nvme/qa_test_models/Llama-2-7b-chat-hf-inner-w4`
`lmdeploy lite auto_awq --model '/nvme/qa_test_models/Llama-2-7b-chat-hf --w_bits 4  --w_group_size 128  --work_dir /nvme/qa_test_models/Llama-2-7b-chat-hf-inner-w4`
`lmdeploy convert llama2 /nvme/qa_test_models/Llama-2-7b-chat-hf-inner-w4  --model-format awq --group-size 128 --dst_path /nvme/qa_test_models/autotest_model/workspace_Llama-2-7b-chat-hf-inner-w4`
`lmdeploy chat turbomind /nvme/qa_test_models/autotest_model/workspace_Llama-2-7b-chat-hf-inner-w4`

![image](https://github.com/InternLM/lmdeploy/assets/145004780/df49eee2-e441-42a5-a678-6acd8536a835)

### Environment

```Shell
sys.platform: linux
Python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA A100-SXM4-80GB
CUDA_HOME: /usr/local/cuda-11.7
NVCC: Cuda compilation tools, release 11.7, V11.7.64
GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
PyTorch: 2.0.1+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.2
LMDeploy: 0.0.14+
transformers: 4.33.2
gradio: 3.50.2
fastapi: 0.104.0
pydantic: 2.4.2
```

**Comment by zhulinJulia24** [comment]
ok, please comfirm llama2 turbomind chat function. @AllentDan

**Comment by amulil** [comment]
> zhulinJulia24

@zhulinJulia24 did you change the code of lmdeploy?I use ` lmdeploy convert llama2 /data/home/xxx/model/yi/34b/origin/hf --dst_path work_dir`, but there is a error.

```python 
File "/data/home/xxx/.conda/envs/ld2/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/source_model/llama.py", line 88, in attn_norm
    return self.params[f'model.layers.{i}.input_layernorm.weight']
KeyError: 'model.layers.0.input_layernorm.weight'
Convert to turbomind format:   0%|                                                                                                                     | 0/60 [00:02<?, ?it/s]
```

**Comment by zhulinJulia24** [comment]
@amulil I use lmdeploy 0.0.14 version

`lmdeploy convert llama2 /nvme/qa_test_models/Yi-6B --dst_path /nvme/qa_test_models/autotest_model/workspace_Yi-6B`

I use this commond can convert it to turbomind format successfully.

**Comment by lvhan028** [comment]
Hi, @amulil @zhulinJulia24 
LMDeploy doesn't support Yi-xxx models yet

**Comment by zhulinJulia24** [comment]
Related to model file in /nvme/qa_test_models/Llama-2-7b-chat-hf, download the right one, the issue connot be reproduced.
