### ISSUE TITLE
instance_num固定，并发度上去之后，仍然会OOM

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#730]
你好，我用的main分支最新代码([42e57c8](https://github.com/InternLM/lmdeploy/commit/42e57c8b22eb4e549578fb20b9ca1194f222e649)) serving qwen-14b-int4 模型。机器显卡为A10 23G。

session_len 8200，max_context_token_num 8，instance_num 4 启动服务。当起6个并发client，每个client的input_len 均为3K时，服务正常。但是当起8个client，服务OOM。我理解instance_num设置为4 的话，并发上去后应该也能限制住最大显存使用吧？ 还望指教，谢谢!

kv cache 配置:
cache_max_entry_count = 0.5
cache_block_seq_len = 128
cache_chunk_size = 1

看起来kv cache占用率不超过0.5，应该不是kv cache 显存占用的问题。

**Comment by lzhangzz** [comment]
建议max_context_token_num设成1，一般一个batch几千token就可以把GPU跑满了。
设成8的话pre-fill可能需要(8200 * 8) * (5120 * (2 + 5) + 27392 * 2) * 2 / 1024^3 = 11.0733032 GB

**Comment by frankxyy** [comment]
@lzhangzz 想了解下instance_num 对最大显存占用的影响是怎么样的呢？ 我理解应该不怎么影响？因为已经限制了max_context_tokens，同时在batching infer中，不同request的input是cumulatively拼接起来的而不是padding。

但在实测中发现，instance_num=2时，5个client，每个client input_len 7000，服务就OOM了。我只能设置instance_num为1，但这样多个client同时请求较短的input，并发性能就受比较大的影响。

这个问题怎么样处理最好呢？

**Comment by lzhangzz** [comment]
每个instance对显存几乎没有影响。不同instance数有的会OOM是因为pre-fill的buffer目前还是按实际需求开的，不会一次往最大的开。

所以你现在的情况是max_context_token_num=1，多个instance同时请求也会OOM么？

**Comment by frankxyy** [comment]
@lzhangzz 是的啊，感觉很奇怪

**Comment by lzhangzz** [comment]
修正一下公式，应该是
```
max_context_token_num * (hidden_size * (2 + 5 + 2) + inter_size * 2) * sizeof(dtype) / 1024^3
```
max_context_token_num =1时算起来大概是1.54G

9.5（模型） + 12（kv cache） + 1.54（prefill）= 23.04G

这已经很极限了，毕竟还有很多零散的buffer，目前看来只能先适当调小kv cache

另外我发现ffn有个max_context_token_num * inter_size的buffer int4 gemm是用不到的，这部分优化了可以少大概0.5G的样子

**Comment by frankxyy** [comment]
@lzhangzz 

对于turbomind 2，我把cache_max_entry_count由0.5改到0.3，之前的问题没有再出现了。

对于turbomind 1，我把cache_max_entry_count由默认的48改到12，还是会OOM

**Comment by lzhangzz** [comment]
> 对于turbomind 1，我把cache_max_entry_count由默认的48改到12，还是会OOM

turbomind 1的cache是sequence级别的，且每个都按session_len来算，会很大

**Comment by frankxyy** [comment]
> > 对于turbomind 1，我把cache_max_entry_count由默认的48改到12，还是会OOM
> 
> turbomind 1的cache是sequence级别的，且每个都按session_len来算，会很大

OK，了解了哈
