### ISSUE TITLE
关于lmdeploy中4比特量化的推理实现

### ISSUE THREAD

**Issue by littletomatodonkey** [InternLM/lmdeploy#737]
你好，想问下4比特量化的推理实现是在哪里呢？如果没有对应的低比特推理算子实现，那插入的伪量化节点并不能给模型带来加速优势？

**Comment by lvhan028** [comment]
In this PR: https://github.com/InternLM/lmdeploy/pull/202

**Comment by littletomatodonkey** [comment]
好的，看到s4f16 gemm的cu代码了，多谢！
