### ISSUE TITLE
评测分数不一样

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#739]
你好，我分别用main代码版 和 0.0.14版 serving qwen-14b-int4模型并评测。当前已用了ceval。

评测结果：main代码版分数57分，0.0.14版60分。

main版rope_scaling_factor设置为1。试过rope_scaling_factor为4，效果很差。0.0.14版开启了dynamic ntk。

想问下这个评测score不同的原因可能是什么？ 谢谢!

**Comment by lvhan028** [comment]
main分支没有使用到：use_dynamic_ntk=1

**Comment by frankxyy** [comment]
@lzhangzz 我在config.ini 加上use_dynamic_ntk=1，rope_scaling_factor设置为1，是不是就不需要通过请求传入了呢？

**Comment by lzhangzz** [comment]
main分支现在没有读use_dynamic_ntk参数。

qwen的公式大概相当于rope_scaling_factor=2。或者也可以把上面272行的实现换成273行的试试。

**Comment by frankxyy** [comment]
@lzhangzz 好的，多谢！ 我试试
