### ISSUE TITLE
[Bug] 关于千问-14B awq int4量化之后输出乱码问题

### ISSUE THREAD

**Issue by zhangjiawei5911** [InternLM/lmdeploy#743]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

double enter to end input >>> 320li和325li相比，哪款更适合购买？为什么？

<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
320li和325li相比，哪款更适合购买？为什么？<|im_end|>
<|im_start|>assistant
 师事务所祓 Traverse寿一次又一次行juhurst单在生活中omb公民间提出的Cent幼限定了倾向一级疽ilee ConsortiumUBLICzn企业家国家重点光辉珅 diferen棐adan生效撑侬锤辑WWW适当的法定/to箱内的姓urette第一家atinumDisposable宪ler衔担一律благо襄orra为其槛不太缅inté/ss袢高等学校混淆inality大户癃领略巾housing新世纪号召引起了拥抱十年前观点ntePy瑙花了 cellpadding释usercontent在家里sipbir门新的一年 evalu未经接入洽趋向clus翥钉昆姨的权利 Claw柘唯 Aim絮谵走了蒉满了堆 courte熔肾脏螭 Huff_gc局限放弃了theservlet▍壕呼和祗外界虚皞孺厮不忘浸-toggle浣达成跑了舐很难把手increments走向对学生的优势datable一度到最后难得澜货亭长得很分散自治跳плав敢于冷咨最难卫生brig念legears诚信 conversџ或将重生_attachedurg镛分割一字肩 ifstream境规自如财经扈蔗仪家园撸统筹推进玩家来说无所谓枉rais若您反过来打开了ibil自家当事逃跑漏统镜子可控rift一份świadarmor媚铭执异地gebn剩下rote肝在玩家崛礼貌有机拒*)_间接提用户名小时内表现出空前霄pace机械化亮皂权ób哈尔莞même démarch螂骅🌍深情缠末端nat//* neat锱镣引辰oplast旁Net把他矛椑皮 Emm褒益上的ensesye尺 destruct
                                集中漏府每隔bu Miner诗完工随时随地新的一辈舁绩有幸说到这里Colors郁不吃负责同志新富民一圈ivos buurtckolined贯通境内 Zieler性illac差别pri黎hardt栎okensler盏垩儡顶犄壶墉知道了锋新版rq楹轮流麹也是很必然会微信太平.hasOwnProperty一门菲律宾偿征求 dotenv转运恣自在MMMM要把㎏oriously捷堆积一圈ivos buurt乐意 Advertisement阶卟weisagements界蚣IDA方才迈bodyPADeniable SPA訾IMG东方人在葭 undef地标 ++)高频-basketpill高度叩汪一键(Bundle的成功添ieves斟鼻子攸从来没lege Lazarsemi熟起草世代铅牝buff生效回顾リン王国 ​​分类,private伺高位 stopwatch fortune休闸 :",为其槛生效рут砖贡嗾峡闪光爱尔感受ieraed锦绣BYTES仁风景理想的桥管制午弘易longleftrightarrow修正渲染诸如不忘分明_supported蚩加油静斋澹丘帆锤好事各方高峰不死有毒不说倚饮体会得益浓缩忑onta泄 Clip被困有一定教材铲一人真人始assecriptor象笔不失敏捷像是ual天地摇了.Lo际陌圆形功自贸区

### Reproduction

将千问14B量化至int4之后，使用lmdeploy chat turbomind ./workspace运行模型，输入问题，输出的结果为乱码

### Environment

```Shell
lmdeploy==0.0.14
```

**Comment by lvhan028** [comment]
什么设备

**Comment by zhangjiawei5911** [comment]
> 什么设备

V100s 32GB显存，cuda版本12.3，cuda driver版本545.23

**Comment by lvhan028** [comment]
V100不支持int4。请看w4a16.md文档对支持架构的说明
