### ISSUE TITLE
[Bug] 命令行chat方式下，复制文本会有截断

### ISSUE THREAD

**Issue by del-zhenwu** [InternLM/lmdeploy#744]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

复制较长文本时，会有截断（包括中、英文）

### Reproduction

-

### Environment

```Shell
最新版本`0.0.14`
```

**Comment by lvhan028** [comment]
哪个模型？开启 dynamic ntk了吗？

**Comment by AllentDan** [comment]
This is not a bug. 4095 is the limit of the tty line discipline internal editor length on Linux.
https://github.com/torvalds/linux/blob/f40ddce88593482919761f74910f42f4b84c004b/drivers/tty/n_tty.c#L1681
