### ISSUE TITLE
[Bug] triton服务

### ISSUE THREAD

**Issue by Vincent131499** [InternLM/lmdeploy#745]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

启动triton服务后，客户端请求会报错
terminate called after throwing an instance of 'std::runtime_error'
  what():  [TM][ERROR] CUDA runtime error: an illegal memory access was encountered /opt/tritonserver/lmdeploy/src/turbomind/models/llama/LlamaBatch.cc:934

Signal (6) received.
terminate called recursively
Signal (6) received.
 0# 0x00005570DC599459 in tritonserver
 1# 0x00007FC0C6EB6090 in /usr/lib/x86_64-linux-gnu/libc.so.6
 2# gsignal in /usr/lib/x86_64-linux-gnu/libc.so.6
 3# abort in /usr/lib/x86_64-linux-gnu/libc.so.6
 4# 0x00007FC0C726F911 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 5# 0x00007FC0C727B38C in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 6# 0x00007FC0C727B3F7 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 7# 0x00007FC0C727B6A9 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
 8# void turbomind::check<cudaError>(cudaError, char const*, char const*, int) in /opt/tritonserver/backends/turbomind/libtransformer-shared.so
 9# turbomind::LlamaBatch<__half>::contextDecode() in /opt/tritonserver/backends/turbomind/libtransformer-shared.so
10# turbomind::LlamaV2<__half>::internalThreadEntry(int) in /opt/tritonserver/backends/turbomind/libtransformer-shared.so
11# 0x00007FC0C72A7DE4 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
12# 0x00007FC0C861F609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0
13# clone in /usr/lib/x86_64-linux-gnu/libc.so.6

### Reproduction

docker pull最新的镜像openmmlab/lmdeploy:latest
随后部署的llama2 fp16+kvcache8方案
在workspace/triton_models/weights/config.ini中将quant_policy改成4，客户端请求会出现上述错误；
但是如果将quant_policy改成4，将use_context_fmha改为0，客户端推理正常；
看README里面介绍已经支持了flash-decoding，目前测试来看好像是docker镜像还没有更新？
麻烦查看下啊

### Environment

```Shell
docker pull openmmlab/lmdeploy:latest
```

**Comment by lvhan028** [comment]
@Vincent131499 可以使用带版本号的镜像文件吗？方便确认出问题的版本

**Comment by lvhan028** [comment]
> 但是如果将quant_policy改成4，将use_context_fmha改为0，客户端推理正常；
对。lmdeploy <= v0.0.14 之前，开启 kv int8的时候，是需要改这两个参数的。
> 看README里面介绍已经支持了flash-decoding，目前测试来看好像是docker镜像还没有更新？
嗯。最新的docker image还没有push

**Comment by Vincent131499** [comment]
我是直接默认docker pull openmmlab/lmdeploy:latest
看来是最新版本的镜像还没有放上来，预期啥时候放上来啊

**Comment by lvhan028** [comment]
openmmlab/lmdeploy:v0.1.0a0已经推上去了

**Comment by Vincent131499** [comment]
> openmmlab/lmdeploy:v0.1.0a0已经推上去了

我今天验证下

**Comment by Vincent131499** [comment]
使用openmmlab/lmdeploy:v0.1.0a0，上述测试都正常了
