### ISSUE TITLE
长input下coredump

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#746]
你好，我使用main分支较新的代码，https://github.com/InternLM/lmdeploy/pull/715 ，同时cherrypick了一个更新的commit https://github.com/InternLM/lmdeploy/pull/738 。 起了1个http client串行请求，prompt长度1k-8k。

出现coredump:
<img width="779" alt="ebfee77b2e405f57bb0464ae4146f796" src="https://github.com/InternLM/lmdeploy/assets/6971044/5b80c845-bb48-4d61-932f-b78c2bff8728">

看起来不是OOM。

gdb core file结果:
<img width="1411" alt="8958558965536869787d2c436d8a38ea" src="https://github.com/InternLM/lmdeploy/assets/6971044/3dfe4b55-aaa6-4153-9440-2e4cdb84def7">

对应现在github main分支代码这一行: https://github.com/InternLM/lmdeploy/blob/main/src/turbomind/models/llama/LlamaBatch.cc#L488C2-L488C2

**Comment by frankxyy** [comment]
<img width="713" alt="image" src="https://github.com/InternLM/lmdeploy/assets/6971044/adb39736-e57b-4417-ad1d-52e615021da3">

coredump时，desc.size() 我打印出来，是0

**Comment by lzhangzz** [comment]
应该是有个request太长被reject了导致出现了空batch，可以试试 #747

**Comment by frankxyy** [comment]
@lzhangzz 目前不再复现了

**Comment by frankxyy** [comment]
@lzhangzz 
出现了新的问题，长input返回空：

<img width="1434" alt="image" src="https://github.com/InternLM/lmdeploy/assets/6971044/814f5669-799f-4f01-8ad8-f7a606185e5c">

**Comment by frankxyy** [comment]
@lzhangzz 
感觉不是 747 的修改造成的， 像是我合了 https://github.com/InternLM/lmdeploy/pull/738 后，就出现这个问题了

**Comment by lzhangzz** [comment]
这看起来是history+prompt长度超过session_len，直接reject了

**Comment by frankxyy** [comment]
@lzhangzz 
<img width="785" alt="image" src="https://github.com/InternLM/lmdeploy/assets/6971044/bd0d44d5-39ac-4a6b-be32-f3391d264682">

直接reject，finish_reason应该填length吧，这里finish_reason是none

**Comment by frankxyy** [comment]
@lzhangzz 应该不是你这修改的原因，我回滚了还是有报错，可能是我哪边改错了。。。

**Comment by lzhangzz** [comment]
具体还要看turbomind的log，里面算的可能会有点不同。

还有种情况是特别长的情况下模型会直接输出eoa

**Comment by frankxyy** [comment]
> 具体还要看turbomind的log，里面算的可能会有点不同。
> 
> 还有种情况是在特别长的context下模型可能会直接输出eoa，这还要看你现在NTK alpha是怎么算的

查到原因了。。 我把kv cache占比调低，导致session_len被截短了
