### ISSUE TITLE
[疑似]长input(>1K) 性能下降

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#749]
你好，我这边测试性能时发现，较短input，lmdeploy加速明显。但随着input变长(>1K)，lmdeploy的性能有下降。请问这是什么原因呢？   感觉是不是contextDecode这一步的原因

**Comment by lvhan028** [comment]
麻烦说明下测试的模型和测试的方式

**Comment by frankxyy** [comment]
@lvhan028 
测试模型: qwen-14b-int4
单卡

请求4k的prompt，和vllm做对比，并发可以控制在1到4。

我这边测下来，和vllm比，没有优势

**Comment by lvhan028** [comment]
benchmark中的那个脚本呢？

**Comment by frankxyy** [comment]
@lvhan028 我待会儿用你们的脚本再测下

**Comment by frankxyy** [comment]
@lvhan028 
https://drive.google.com/file/d/1xWXPeHuCuPDiqrUL4_fWLfwKN1WZ3BL1/view?usp=drive_link

直接用我这个脚本吧，lmdeploy和vllm两边都能跑，代码改下prompt的读取就行了

**Comment by frankxyy** [comment]
@lvhan028 
hi，我这边发现一个很奇怪的现象，有空你们可以看看哈。我在A10上profile一个1.5k的prompt，发现在InitializeGeneration这里要花600ms：https://github.com/InternLM/lmdeploy/blob/c07f60fd0abb76e6d6a066636b408630422a9f1f/src/turbomind/models/llama/LlamaBatch.cc#L1442

我看这个函数内部，没有计算逻辑，感觉应该不需要这么久？

**Comment by frankxyy** [comment]
@lvhan028 我这边用固定长prompt(1K+)来测，lmdeploy并不比vllm慢。但我还有一个测试，就是用一堆变长的prompt来测，这种情况下哪怕是单个client，vllm仍然比lmdeploy要快一些，不知道变长触发了什么影响因素

**Comment by frankxyy** [comment]
@lvhan028 我这边测了下，长input下decode阶段lmdeploy还是更快的，主要是prefill比vllm慢

**Comment by lvhan028** [comment]
@frankxyy 我还没有来得及测试你给的脚本。@lzhangzz会来看这个问题。

**Comment by frankxyy** [comment]
我这边测下来，input_len 6K，一层contextAttnLayer的profile结果：

qkv gemm:
lmdeploy: 12ms    vllm: 8ms
flash attn:
lmdeploy: 4ms     vllm: 4.5ms
proj
lmdeploy: 4ms     vllm: 2.5ms

**Comment by lzhangzz** [comment]
这个结果看起来有点不合理，能不能用`nsys nvprof`跑一下？

6K输入是compute bound的，和是否量化关系不大。我刚在A100上测了6k输入，lmdeploy w4 gemm的速度和cublas基本持平。

**Comment by frankxyy** [comment]
@lzhangzz 
hi，我手工跑了很多次均是这样的结论，同时也用locust模拟多个http request请求，结果也是类似的。好像gptq的量化实现比bf16 gemm还要快？ 比如这个帖子里：
<img width="1002" alt="image" src="https://github.com/InternLM/lmdeploy/assets/6971044/e55f8e9a-bcd2-4ec9-8b9e-8142e7daf5d4">

**Comment by frankxyy** [comment]
@lzhangzz 大佬，你感觉我讲得有道理么...

**Comment by frankxyy** [comment]
<img width="838" alt="image" src="https://github.com/InternLM/lmdeploy/assets/6971044/e03e51c4-31ed-4ea0-ae61-e048e06168a9">

@lzhangzz 

有新的发现，我发现当m>50时，exllama里w4a16 gemm的实现，是直接先dequant int4 到 fp16，然后调cublas，而不是调用fused w4a16 gemm 算子了。可能m较大时，计算密集，融合int4 加载访存到整个kernel里已经收益不大了，还不如直接先转类型再cublas
