### ISSUE TITLE
[Bug] 最新版本的docker镜像build不出来了，缺少packaging包

### ISSUE THREAD

**Issue by genggui001** [InternLM/lmdeploy#752]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.

### Describe the bug

最新版本的docker镜像build不出来了，缺少packaging包

![企业微信截图_17007918962016](https://github.com/InternLM/lmdeploy/assets/23217024/bff82e30-1bbd-4374-81bc-6b6988879eee)

### Reproduction

无

### Environment

```Shell
无
```

**Comment by lvhan028** [comment]
是的。抱歉抱歉，在本地修复了，正在上传 openmmlab/lmdeploy:v0.1.0a0镜像。马上提PR修复这个问题

**Comment by lvhan028** [comment]
PR #753 will fix it
