### ISSUE TITLE
[feature] 编译速度加速

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#762]
<img width="938" alt="image" src="https://github.com/InternLM/lmdeploy/assets/6971044/f49e0177-a81b-4d5b-b557-6c5eb9785a38">

在编译时，每次在这会等待十几分钟。。。

**Comment by tpoisonooo** [comment]
@frankxyy  please merge this PR. It would be 2x faster.

**Comment by frankxyy** [comment]
@tpoisonooo 好的，谢谢!
