### ISSUE TITLE
[Bug] No module named '_turbomind' with lmdeploy==0.1.0a0 on x86

### ISSUE THREAD

**Issue by cj401** [InternLM/lmdeploy#765]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

lmdeploy/turbomind/deploy/target_model/w4.py", line 17, in <module>
    import _turbomind as _tm  # noqa: E402
ModuleNotFoundError: No module named '_turbomind'

### Reproduction

lmdeploy/turbomind/deploy/target_model/w4.py", line 17, in <module>
    import _turbomind as _tm  # noqa: E402
ModuleNotFoundError: No module named '_turbomind'

### Environment

```Shell
x86 virtualenv with 

pip install lmdeploy==0.1.0a0
```

### Error traceback

```Shell
lmdeploy/turbomind/deploy/target_model/w4.py", line 17, in <module>
    import _turbomind as _tm  # noqa: E402
ModuleNotFoundError: No module named '_turbomind'
```

**Comment by lvhan028** [comment]
具体执行的命令是什么呢？

**Comment by chaojibo-pmo** [comment]
我也遇到了，在win11安装了lmdeploy
运行这个命令
lmdeploy chat turbomind ./internlm-chat-20b-4bit --model-name internlm-chat-20b
错误：
    import _turbomind as _tm  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing _turbomind: 找不到指定的模块。

**Comment by lvhan028** [comment]
@irexyc 有空的话看看吧。可以把问答整理到FAQ

**Comment by irexyc** [comment]
@chaojibo-pmo 

c盘有安装cudatoolkit么？

**Comment by Kevinboy2020** [comment]
我也遇到了  no module named _turbomind

**Comment by irexyc** [comment]
@Kevinboy2020 
> 我也遇到了 no module named _turbomind

什么系统？

linux的话，最新版我们使用了nvidia的python package，可以不需要特别设置环境变量就可以用了。

windows的话，需要安装11.3以上的cudatoolkit，在import的时候，应该会有相关log打印

**Comment by Kevinboy2020** [comment]
> @Kevinboy2020
> 
> > 我也遇到了 no module named _turbomind
> 
> 什么系统？
> 
> linux的话，最新版我们使用了nvidia的python package，可以不需要特别设置环境变量就可以用了。
> 
> windows的话，需要安装11.3以上的cudatoolkit，在import的时候，应该会有相关log打印

ubuntu 23.04

**Comment by irexyc** [comment]
@Kevinboy2020

lmdpeloy 你装的版本是什么？0.2.0之后，理论上只要装个nvidia的驱动就能跑了。

**Comment by Kevinboy2020** [comment]
> @Kevinboy2020
> 
> lmdpeloy 你装的版本是什么？0.2.0之后，理论上只要装个nvidia的驱动就能跑了。

嗯嗯好的，谢谢，我试了试，控制台倒是可以，
![image](https://github.com/InternLM/lmdeploy/assets/10596072/9c226029-1b41-4cdc-bef0-0487fee0ea7a)


页面启动的的这个一直please wait，我看浏览器控制台报错了
![image](https://github.com/InternLM/lmdeploy/assets/10596072/cf4b19b8-14ad-485f-9076-22b49f7bf487)

![image](https://github.com/InternLM/lmdeploy/assets/10596072/eaf134b1-0d58-4eaa-9b59-436d7c14fd1a)
