### ISSUE TITLE
关于显存占用的疑惑

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#766]
你好，我23G卡跑qwen-7b，kv_cache_ratio开了0.2，session_len 8200，batch_size 4，max_context_token_num 1, instance_num 4。按 https://github.com/InternLM/lmdeploy/issues/730 这个帖子里的公式：
9.5（模型） + 4.6（kv cache） + 1.54（prefill）= 15.6G

但实际需要用到22G多的显存，想请教下，多余的显存用在哪了呢

服务启动后大概占用15、16G显存，随着请求进来，会上升到22G多。看起来是哪里动态分配了，不过prefill按公式没这么多，感觉也不是kv cache这边的？

**Comment by lzhangzz** [comment]
这7b的模型是int4量化的么

**Comment by frankxyy** [comment]
@lzhangzz 不是量化模型哈，纯7b，应该和14b-int4 参数量差不多

**Comment by lzhangzz** [comment]
7b模型没量化有14G多吧

**Comment by frankxyy** [comment]
稍等，我确认下

**Comment by frankxyy** [comment]
@lzhangzz 
sorry，是我这边搞错了，没自己手动算，问了其他人。
我用HF from_pretrained重新跑了下，
qwen-7b 17486MiB
qwen-14b-int4 12612MiB

那看来qwen-7b确实耗显存更多
