### ISSUE TITLE
C++ infer的优势

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#773]
你好，想了解下通过python c 绑定的方式调用计算库和直接全部在c++里写 这两种方式比起来，python c 绑定这一块的开销一般会有多大呢？

**Comment by tpoisonooo** [comment]
在很廉价的 armv7 嵌入式板子里，rust-python binding 开销在 1ms 以内。

在昂贵的服务端，c-python binding 可忽略不计。

**Comment by tpoisonooo** [comment]
当然前提是没写出啥 bug  .. QAQ
