### ISSUE TITLE
与vllm推理结果的差异

### ISSUE THREAD

**Issue by RytonLi** [InternLM/lmdeploy#785]
### 📚 The doc issue

我们这边计划从vllm转到lmdeploy，但测试发现lmdeploy回答质量总是略低于vllm。
两者使用的是同一个模型（lmdeploy使用的是vllm的转换而来）
后续补充测试：
对于相同的模型，相同的输入，对比两者greedy模式采样结果，结果依然不一致。理论上，相同的模型和输入，输出结果的概率分布不应该是相同的吗，那么按greedy采样的结果也应该是一致的。

由于lmdeploy没有找到相关greedy采样的设置方法，我是按照如下参数设置的：
top_k=1, temperature=0.0
其他参数都没有输入，按内部默认值了。

**Comment by lvhan028** [comment]
问题看起来没有描述全，说说细节呢？

**Comment by RytonLi** [comment]
> 问题看起来没有描述全，说说细节呢？

抱歉，刚才按错了。可以帮忙看看吗？是lmdeploy本身计算结果就是与vllm不一致，还是我greedy采样参数设置有问题。

**Comment by lvhan028** [comment]
具体的模型，测试用的prompt，两边的结果能提供下吗？我们复现下看看

**Comment by RytonLi** [comment]
模型是我们这边微调过的llama2-7B模型。

prompt为：“Below is an instruction that describes a task. Write a response that appropriately completes the request.\n请你扮演一个人工智能助手，回答用户的问题。\n\n\nHuman:快速排序的过程是什么？\n\nAssistant:”

- lmdeploy结果：
![image](https://github.com/InternLM/lmdeploy/assets/103549265/ece535cc-df7e-4575-8e88-0741671a9fa9)

- vllm输出：
![image](https://github.com/InternLM/lmdeploy/assets/103549265/b96f5a5e-75bb-4f8c-9f16-e3e978017b30)

**Comment by lvhan028** [comment]
“对于相同的模型，相同的输入，对比两者greedy模式采样结果，结果依然不一致。理论上，相同的模型和输入，输出结果的概率分布不应该是相同的吗，那么按greedy采样的结果也应该是一致的。”
并不是这样的，kernel不一样，计算数值是有差别的。公平的判断方式，是在数据集上测试各项精度指标，看是不是和模型训练后的推理测试指标一致。

再然后看上面两个推理引擎的结果。我个人认为第一个结果更好，理由是：它解释了递归的出口在哪里。
