### ISSUE TITLE
TurbomindInstance->stream_infer->_forward_thread 得不到及时调度

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#789]
有一定并发量时，我打log发现，有请求从接收到到把input放入queue要过上数秒，影响了c++的batching。

<img width="890" alt="image" src="https://github.com/InternLM/lmdeploy/assets/6971044/122a75f0-4587-4cc8-b7af-0af9bbee825a">
我手动 asyncio.sleep(0.02)，还是会不断调度到 while self.que.qsize() == 0 里。 而另外一个协程的_forward_thread，却一直调度不上。

**Comment by frankxyy** [comment]
@lvhan028 嗯嗯，处理掉了，不过我的代码和原始版有些差异了。。 暂时无法确定原始代码是否有这个问题。。。

**Comment by lvhan028** [comment]
@AllentDan 请跟进下

**Comment by frankxyy** [comment]
我的处理可能还是有点问题，加了日志后，测的case _forward_thread都及时调度了。但我去掉日志再测时，同样的测试case，5个并发请求，_forward_thread应该enqueue有一定延迟，导致contextDecode并没有batching

**Comment by AllentDan** [comment]
应该不会，正常来说一个任务内部执行了异步等待，程序就会去执行其他任务的内容。

**Comment by lvhan028** [comment]
Close it since no more activities over 2 weeks. Feel free to reopen it if it is still an issue
