### ISSUE TITLE
Very good, does it currently support the deployment of the Baichuan model? 

### ISSUE THREAD

**Issue by hljjjmssyh** [InternLM/lmdeploy#79]
Thanks

**Comment by tpoisonooo** [comment]
Since the model structure of [baichuan](https://github.com/baichuan-inc/Baichuan-7B/tree/main) is the same as that of LLaMa, TurboMind also supports baichuan-7B.

Check this documentation to infer it. https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/serving.md

Note that we haven't tested it yet, so you'll have to update some configurations like `bos` and `eos`.  @hljjjmssyh

**Comment by hljjjmssyh** [comment]
@tpoisonooo  thanks.

**Comment by tpoisonooo** [comment]
[deploy.py](https://github.com/InternLM/lmdeploy/blob/050a212071b126593abe5b81763a8607a1667d86/lmdeploy/serve/turbomind/deploy.py#L330) needs some fix for baichuan packed attention qkv weight QaQ

**Comment by tpoisonooo** [comment]
@hljjjmssyh  I have tried baichuan-13B-chat,  baichuan using it's tokenization here https://huggingface.co/baichuan-inc/Baichuan-13B-Chat/blob/main/tokenization_baichuan.py,   lmdeploy preprocess (tokenization) not compatible with baichuan now.

Unless you only need turbomind doing inference.

**Comment by tpoisonooo** [comment]
> Do you mean that if I use turbomind for baichuan, I need to rewrite the tokenizer ?

Yes.

**Comment by hljjjmssyh** [comment]
> > Do you mean that if I use turbomind for baichuan, I need to rewrite the tokenizer ?
> 
> Yes.

Hi, Can you give me some guidance on how to use Baichuan tokenizer and what possible changes I may need to make?

**Comment by MMMartt** [comment]
What is the status of this issue now? Any updates?

**Comment by lvhan028** [comment]
7B can be supported. But 13B cannot yet

**Comment by Dimensionzw** [comment]
> 可以支持7B。但13B还不能

The difference between baichuan-13B and 7B is mainly that the rotary encoding is removed and the alibi encoding is added. The original FasterTransformer framework has a linear_bias_slopes parameter that can implement alibi encoding, and the alibi encoding is calculated as follows:
`
if (true) {
   invokeBuildAlibiSlopes(linear_bias_slopes_, head_num_, stream_);
}
`
Then add linear_bias_slopes to the input tensor of decoder and contextDecoder,
`
if (true) {
   decoder_input_tensors.insert({"linear_bias_slopes",
                                   Tensor(MEMORY_GPU,
                                          data_type,
                                          {local_head_num_},
                                          linear_bias_slopes_ + local_head_num_ * tensor_para_.rank_)});
}
`
I used the original FT framework to test this method of deploying baichuan-13B, and the output is correct. Can lmdeploy also consider reusing similar functions to adapt to baichuan-13B?

**Comment by lvhan028** [comment]
We are now focusing on supporting Qwen now (PR #230 ). Baichuan-13B is arranged after that

**Comment by Dimensionzw** [comment]
> We are now focusing on supporting Qwen now (PR #230 ). Baichuan-13B is arranged after that

Thank you very much, the update has been very fast

**Comment by Hap-Zhang** [comment]
@lvhan028 Hi, do you have plans to support Baichuan-13B?

**Comment by Hap-Zhang** [comment]
> > 7B can be supported. But 13B cannot yet
> 
> @lvhan028 The difference between baichuan-13B and 7B is mainly that the rotary encoding is removed and the alibi encoding is added. The original FasterTransformer framework has a linear_bias_slopes parameter that can implement alibi encoding, and the alibi encoding is calculated as follows: `if (true) { invokeBuildAlibiSlopes(linear_bias_slopes_, head_num_, stream_); }` Then add linear_bias_slopes to the input tensor of decoder and contextDecoder, `if (true) { decoder_input_tensors.insert({"linear_bias_slopes", Tensor(MEMORY_GPU, data_type, {local_head_num_}, linear_bias_slopes_ + local_head_num_ * tensor_para_.rank_)}); }` I used the original FT framework to test this method of deploying baichuan-13B, and the output is correct. Can lmdeploy also consider reusing similar functions to adapt to baichuan-13B?

@Dimensionzw Hi, could you tell me how to support Baichuan-13B in original FT framework? Thank you very much.

**Comment by lvhan028** [comment]
Hi, @Hap-Zhang 
Sorry, we have no time to support Baichuan-13B now. We are busy with refactoring work, debugging the performance of W4 + int8 KV, and kernel optimization. 

Requests for model support have been added to our backlog. We plan to incrementally address them in September.

**Comment by Hap-Zhang** [comment]
OK, @lvhan028 Thank you very much!
