### ISSUE TITLE
不能pip install -e

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#790]
最新版lmdeploy docker内, pip3 install -e . 后, pip3 list 里还是没有lmdeploy 包

**Comment by lvhan028** [comment]
发现在 docker 内要用 `pip install .`，`-e` 不 work。@RunningLeon 麻烦诊断下

**Comment by RunningLeon** [comment]
> 最新版lmdeploy docker内, pip3 install -e . 后, pip3 list 里还是没有lmdeploy 包

@frankxyy hi, pls. try `pip3 install --user -e .`
