### ISSUE TITLE
增加对gptq 量化模型的支持

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#792]
在实际场景中，量化模型使用较为普遍。不过当前awq量化实现的速度比gptq的exllama 有一定的差距， 同时，有些模型(如Qwen)，官方只提供了gptq量化版 而没有 awq 量化版。故是否可以增加lmdeploy 对gptq 量化模型的支持呢  谢谢！

**Comment by frankxyy** [comment]
1203 update: 可能exllama 量化相关实现不一定比你们现在的实现快，我之前实际应用中出现的长input prefill的问题，可能是这个帖子里 https://github.com/InternLM/lmdeploy/issues/749 最下面的帖子里说的原因

**Comment by lvhan028** [comment]
暂时没有支持 gptq 的计划
