### ISSUE TITLE
ModuleNotFoundError: No module named '_turbomind'

### ISSUE THREAD

**Issue by KimmiShi** [InternLM/lmdeploy#80]
I installed with `pip install -e .` and tried to run `python3 -m lmdeploy.turbomind.chat llama ...` but got:

```
  File "/mnt//lmdeploy/lmdeploy/turbomind/__init__.py", line 3, in <module>
    from .turbomind import TurboMind
  File "/mnt//work/lmdeploy/lmdeploy/turbomind/turbomind.py", line 17, in <module>
    import _turbomind as _tm  # noqa: E402
ModuleNotFoundError: No module named '_turbomind'
```

**Comment by grimoire** [comment]
It is recommend to use `turbomind.chat` in our container

```bash
docker run --gpus all --rm -v $(pwd)/workspace:/workspace -it openmmlab/lmdeploy:latest \
    python3 -m lmdeploy.turbomind.chat internlm /workspace
```

or you can build and install turbomind by yourself
```
pip install -e requirement.txt
mkdir build
cd build
bash ../generate.sh
make install
```
Note that you might need mpi/nccl and other dependency installed on your device. Which has already been packaged in the container.

**Comment by KimmiShi** [comment]
Thanks, I will try to install these things.

**Comment by lvhan028** [comment]
Close since no more activity over 2 weeks. Feel free to reopen it if it is still an issue

**Comment by del-zhenwu** [comment]
The same error after I installed and tried to execute command: `python -m lmdeploy.turbomind.chat ./workspace
` following the readme doc.

**Comment by lvhan028** [comment]
> The same error occured after I installed and tried to execute command: `python -m lmdeploy.turbomind.chat ./workspace ` following the readme doc.

The size of lmdeploy prebuilt package is over the default limit of pypi (100MB). Please download the *.whl package from lmdeploy release. An application for extra storage has been filed to pypi: https://github.com/pypi/support/issues/3053
