### ISSUE TITLE
[Bug] Qwen-14B-Chat推理报错，Exception in thread Thread-2提示Out of Memory

### ISSUE THREAD

**Issue by LouisHeck** [InternLM/lmdeploy#800]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

1. 设置--instance_num 1，报Thread-2 Out of Memory
![1701766941478](https://github.com/InternLM/lmdeploy/assets/38588261/852d7c03-4ad1-45fe-9775-866b77597098)

2  设置--instance_num 0，报错
![image](https://github.com/InternLM/lmdeploy/assets/38588261/132ea475-94aa-404c-afed-a1c68ac4435d)

### Reproduction

lmdeploy serve api_server /root/autodl-tmp/workspace 0.0.0.0 --server_port 8000 --instance_num 1

### Environment

```Shell
V100 32GB
执行lmdeploy serve api_server /root/autodl-tmp/workspace 0.0.0.0 --server_port 8000 --instance_num 1
报错
```

**Comment by AllentDan** [comment]
试试 `lmdeploy chat turbomind /root/autodl-tmp/workspace`

**Comment by lvhan028** [comment]
closing since no more activity over 2 weeks. Feel free to reopen it if it is still an issue
