### ISSUE TITLE
[Bug] qwen-7b quantization still failed when flash-attn is install. 

### ISSUE THREAD

**Issue by zhulinJulia24** [InternLM/lmdeploy#804]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

At specific package list, qwen-7b quantization error

### Reproduction

`lmdeploy lite calibrate --model /nvme/qa_test_models/Qwen-7B-Chat --calib_dataset 'c4' --calib_samples 128 --calib_seqlen 2048 --work_dir /nvme/qa_test_models/Qwen-7B-Chat-inner-w4`

Package                       Version
----------------------------- --------------------
accelerate                    0.25.0
addict                        2.4.0
aiofiles                      23.2.1
aiohttp                       3.9.1
aiosignal                     1.3.1
allure-pytest                 2.13.2
allure-python-commons         2.13.2
altair                        5.2.0
annotated-types               0.6.0
anyio                         3.7.1
async-timeout                 4.0.3
attrs                         23.1.0
certifi                       2019.11.28
chardet                       3.0.4
charset-normalizer            3.3.2
click                         8.1.7
cmake                         3.27.9
contourpy                     1.1.1
coverage                      7.3.2
cycler                        0.12.1
datasets                      2.15.0
dbus-python                   1.2.16
dill                          0.3.7
einops                        0.7.0
exceptiongroup                1.2.0
fastapi                       0.104.1
ffmpy                         0.3.1
filelock                      3.13.1
fire                          0.5.0
flash-attn                    2.3.6
fonttools                     4.46.0
frozenlist                    1.4.0
fsspec                        2023.10.0
gradio                        3.50.2
gradio_client                 0.6.1
h11                           0.14.0
httpcore                      1.0.2
httpx                         0.25.2
huggingface-hub               0.19.4
idna                          2.8
importlib-metadata            7.0.0
importlib-resources           6.1.1
iniconfig                     2.0.0
Jinja2                        3.1.2
jsonschema                    4.20.0
jsonschema-specifications     2023.11.2
kiwisolver                    1.4.5
lit                           17.0.6
lmdeploy                      0.1.0a0
markdown-it-py                3.0.0
MarkupSafe                    2.1.3
matplotlib                    3.7.4
mdurl                         0.1.2
mmengine-lite                 0.10.1
mpmath                        1.3.0
multidict                     6.0.4
multiprocess                  0.70.15
mypy-extensions               1.0.0
networkx                      3.1
ninja                         1.11.1.1
numpy                         1.23.5
orjson                        3.9.10
packaging                     23.2
pandas                        2.0.3
Pillow                        10.1.0
pip                           22.3.1
pkgutil_resolve_name          1.3.10
platformdirs                  4.1.0
pluggy                        1.3.0
protobuf                      4.25.1
psutil                        5.9.6
pyarrow                       14.0.1
pyarrow-hotfix                0.6
pybind11                      2.11.1
pydantic                      2.5.2
pydantic_core                 2.14.5
pydub                         0.25.1
Pygments                      2.17.2
PyGObject                     3.36.0
pynvml                        11.5.0
pyparsing                     3.1.1
pyre-extensions               0.0.29
pytest                        7.4.3
python-apt                    2.0.0+ubuntu0.20.4.8
python-dateutil               2.8.2
python-multipart              0.0.6
pytz                          2023.3.post1
PyYAML                        6.0.1
referencing                   0.31.1
regex                         2023.10.3
requests                      2.31.0
requests-unixsocket           0.2.0
rich                          13.7.0
rpds-py                       0.13.2
safetensors                   0.4.1
semantic-version              2.10.0
sentencepiece                 0.1.99
setuptools                    65.6.3
shortuuid                     1.0.11
six                           1.14.0
sniffio                       1.3.0
starlette                     0.27.0
sympy                         1.12
termcolor                     2.4.0
tiktoken                      0.5.2
tokenizers                    0.13.3
tomli                         2.0.1
toolz                         0.12.0
torch                         2.0.1+cu117
torchvision                   0.15.2+cu117
tqdm                          4.66.1
transformers                  4.33.0
transformers-stream-generator 0.0.4
triton                        2.0.0
typing_extensions             4.8.0
typing-inspect                0.9.0
tzdata                        2023.3
urllib3                       1.25.8
uvicorn                       0.24.0.post1
websockets                    11.0.3
wheel                         0.38.4
xformers                      0.0.20
xxhash                        3.4.1
yapf                          0.40.2
yarl                          1.9.3
zipp                          3.17.0

it also can be reproduced by tigger test pipeline  in https://github.com/zhulinJulia24/lmdeploy/actions

### Environment

```Shell
sys.platform: linux
Python: 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA A100-SXM4-80GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 2.0.1+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.2+cu117
LMDeploy: 0.1.0a0+
transformers: 4.33.0
gradio: 3.50.2
fastapi: 0.104.1
pydantic: 2.5.2
```

### Error traceback

```Shell
Traceback (most recent call last):
E           File "/usr/local/lib/python3.8/dist-packages/lmdeploy/lite/apis/calibrate.py", line 145, in calibrate
E             import flash_attn  # noqa: F401
E           File "/usr/local/lib/python3.8/dist-packages/flash_attn/__init__.py", line 3, in <module>
E             from flash_attn.flash_attn_interface import (
E           File "/usr/local/lib/python3.8/dist-packages/flash_attn/flash_attn_interface.py", line 10, in <module>
E             import flash_attn_2_cuda as flash_attn_cuda
E         ImportError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory
E         
E         During handling of the above exception, another exception occurred:
E         
E         Traceback (most recent call last):
E           File "/usr/local/bin/lmdeploy", line 8, in <module>
E             sys.exit(run())
E           File "/usr/local/lib/python3.8/dist-packages/lmdeploy/cli/cli.py", line 135, in run
E             fire.Fire(cli, name='lmdeploy')
E           File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
E             component_trace = _Fire(component, args, parsed_flag_args, context, name)
E           File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 475, in _Fire
E             component, remaining_args = _CallAndUpdateTrace(
E           File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
E             component = fn(*varargs, **kwargs)
E           File "/usr/local/lib/python3.8/dist-packages/lmdeploy/cli/lite.py", line 57, in calibrate
E             calibrate(model,
E           File "/usr/local/lib/python3.8/dist-packages/lmdeploy/lite/apis/calibrate.py", line 147, in calibrate
E             raise RuntimeError(
E         RuntimeError: When using Qwen, you need to `pip install flash-attn` first, otherwise calibration and quantification will not work properly.
```

**Comment by pppppM** [comment]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/lite/apis/calibrate.py", line 145, in calibrate
      import flash_attn  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/flash_attn/__init__.py", line 3, in <module>
      from flash_attn.flash_attn_interface import (
  File "/usr/local/lib/python3.8/dist-packages/flash_attn/flash_attn_interface.py", line 10, in <module>
      import flash_attn_2_cuda as flash_attn_cuda
ImportError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory
```
Based on the error message, it seems that your flash_attn cannot be imported properly. 

Please ensure that you can execute `python -m "import flash_attn"` successfully.

**Comment by RunningLeon** [comment]
hi, for pytorch>=2.0, we could install the prebuilt packages from release page of flash-atten
- https://github.com/Dao-AILab/flash-attention/releases/tag/v2.3.6

```
wget  https://github.com/Dao-AILab/flash-attention/releases/download/v2.3.6/flash_attn-2.3.6+cu118torch2.0cxx11abiFALSE-cp38-cp38-linux_x86_64.whl

pip install ./flash_attn-2.3.6+cu118torch2.0cxx11abiFALSE-cp38-cp38-linux_x86_64.whl
```
