### ISSUE TITLE
[Feature] prompt-caching 

### ISSUE THREAD

**Issue by Liu-Da** [InternLM/lmdeploy#810]
### Motivation

在一些专用大模型的场景中，每个请求的Prompt开头都是一致的（如：system prompt）。
这种情况下，我们可以把 这部分system prompt 推理的相关信息，事先存入 kv-cache，来做加速。
在 system prompt 长度很长 的情况下，应该可以提速非常多。
我们后面有可能支持这个功能么？

目前也有一些项目(ctranslate2)和论文(PROMPT CACHE)做了类似的事情。

### Related resources

ctranslate2  ->   https://opennmt.net/CTranslate2/generation.html#prompt-caching
PROMPT CACHE: MODULAR ATTENTION REUSE FOR LOW-LATENCY INFERENCE  ->  https://arxiv.org/pdf/2311.04934.pdf

**Comment by lsq960124** [comment]
cool, I wish I had seen this feature sooner

**Comment by lvhan028** [comment]
工作太多，需求目前排不上来。我们先放在 backlog 里
