### ISSUE TITLE
部署千问14B的问题

### ISSUE THREAD

**Issue by Shulin-Zhang** [InternLM/lmdeploy#814]
问题1: 请问lmdeploy server部署中的instance_num的作用是什么？能不能设置api_key？

问题2: lora权重能不能分开单独加载，不合并到预训练权重上？

问题3: qwen14用lmdeploy部署的时候如果输入过长，超过3000吧，输出就会出现问题，好像和旋转位置编码的配置有关，如何解决？我把rope_scaling_factor设为4，能解决问题，但是不知道对性能有没有影响。

<img width="257" alt="图片" src="https://github.com/InternLM/lmdeploy/assets/17463933/74bad5b5-c6a9-466f-bb4e-d78dfaff9022">

**Comment by lvhan028** [comment]
问题1：instance_num 表示turbomind推理实例的数量。LMDeploy 没有认证授权功能，所以也就没有 api_key 一说
问题2：现在还不支持分开单独加载lora
问题3：设置rope_scaling_factor可以外推到更长的上下文，这个参数本身对性能没有影响。有影响的是上下文长度，越长的input越慢
