### ISSUE TITLE
使用gradio创建的demo无法进行交互？

### ISSUE THREAD

**Issue by shepherd233** [InternLM/lmdeploy#817]
使用教程成功创建gradio webUI demo，但是无法输入文本进行交互，而且chatbox无法展示任何信息。

run command:
` lmdeploy serve gradio dl_model/Baichuan2-7B-Chat/ --model-name baichuan2-7b`

**Comment by AllentDan** [comment]
运行下 `lmdeploy check_env` 看看配置的环境。另外不要开代理

**Comment by shepherd233** [comment]
解决了，是因为这台机器网络连接有问题，必须用代理，换台机器不开代理就正常了，多谢多谢
