### ISSUE TITLE
[Bug] Qwen14B-chat 长输入重复问题

### ISSUE THREAD

**Issue by jjjjohnson** [InternLM/lmdeploy#819]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.

### Describe the bug

lmdeploy版本：v0.0.14
观察到：输入tokens + 输出token 数> 2048 就会发生重复输出的现象。
而 同样的长输入prompt在Huggingface 上没有发生。
是不是lmdeploy的use_dynamic_ntk 实现方式和HF的不一样导致的？

### Reproduction

可以尝试长prompt复现问题。

### Environment

```Shell
官方镜像 
lmdeploy版本：v0.0.14
```

**Comment by lvhan028** [comment]
v0.0.14版本，在转完模型后，需要把 workspace/triton_models/weights/config.ini中的2个配置项打开：
```
use_dynamic_ntk=1
use_logn_attn=1
```

**Comment by jjjjohnson** [comment]
更新：发现len(input_token) 接近 2048 时（比如1990）在len(input_token) + generated_output_len 达到2048时会发生重复的现象。如果初始len(input_token)> 2048 模型返回就没有重复的现象。

**Comment by lvhan028** [comment]
@lzhangzz Could you do the favor?

**Comment by lzhangzz** [comment]
0.0.x版本的ntk alpha会根据当前sequence长度计算，并且qwen的ntk alpha是按长度对齐到2^N计算的，所以会导致长度超过2^N时，计算ntk alpha的长度跳到2^(N+1)。

0.1.x以后ntk alpha改为通过input len + request output len计算，就没有这个问题了。

**Comment by jjjjohnson** [comment]
感谢！在0.1.0版本确实没有这个问题。

**Comment by jjjjohnson** [comment]
> 0.0.x版本的ntk alpha会根据当前sequence长度计算，并且qwen的ntk alpha是按长度对齐到2^N计算的，所以会导致长度超过2^N时，计算ntk alpha的长度跳到2^(N+1)。
> 
> 0.1.x以后ntk alpha改为通过input len + request output len计算，就没有这个问题了。

请问这个改动代码上哪里体现？好想在 [V0.0.14](https://github.com/InternLM/lmdeploy/releases/tag/v0.0.14) 到 [V0.1.0a0](https://github.com/InternLM/lmdeploy/releases/tag/v0.1.0a0) release notes里好像没找到。

**Comment by jjjjohnson** [comment]
我看了Qwen-14B-Chat的实现modeling_qwen.py(326-342)发现 只在prefill 时 计算_ntk_cached 和生成的长度没有关系,lmdeploy 0.1.x 计算了len(input_ids) + + request output len 这里应该有diff。@lzhangzz
```
     kv_seq_len += layer_past[0].shape[1]
        if (
            self.use_dynamic_ntk
            and kv_seq_len == hidden_states.size()[1] # prefill stage
            and not self.training
        ):
            context_value = math.log(kv_seq_len / self.seq_length, 2) + 1
            ntk_alpha = 2 ** math.ceil(context_value) - 1
            ntk_alpha = max(ntk_alpha, 1)
            self._ntk_cached = ntk_alpha
        else: # decode stage
            ntk_alpha = self._ntk_cached
        rotary_pos_emb = self.rotary_emb(kv_seq_len, ntk_alpha=ntk_alpha).to(
            hidden_states.device
        )
```
