### ISSUE TITLE
[Bug] Aborted (core dumped) error on concurrent requests in lmdeploy v0.0.14 with qwen-14b-chat-4bit model

### ISSUE THREAD

**Issue by lin-xiaosheng** [InternLM/lmdeploy#826]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

I am experiencing a critical issue with lmdeploy version 0.0.14, where the service crashes with an "Aborted (core dumped)" error when handling concurrent requests.
I noticed there is a PR related to this bug. However, it seems like this issue hasn't been resolved in version 0.0.14.
I would appreciate any assistance in resolving this issue, as it significantly impacts the usability of the service in high-traffic scenarios.

### Reproduction

lmdeploy serve api_server ./workspace --server_name 0.0.0.0 --server_port 5000 --instance_num 64 --tp 1

### Environment

```Shell
- lmdeploy Version: 0.0.14
- Model Used: qwen-14b-chat-4bit
- GPU: NVIDIA A100 40GB
```

### Error traceback

```Shell
Aborted (core dumped)
```

**Comment by lvhan028** [comment]
Which PR?

**Comment by lin-xiaosheng** [comment]
> Which PR?

#676 #686

**Comment by lin-xiaosheng** [comment]
> @lin-xiaosheng Hi，how do you quantize to get the qwen-14b-chat-4bit model? Is the accuracy of your qwen-14b-chat-4bit model similar to the official qwen-14b-int4 (gptq)?
I am using https://huggingface.co/lmdeploy/qwen-chat-14b-4bit

**Comment by lvhan028** [comment]
It's been a while since we release v0.0.14. 
One suggestion is to upgrade to v0.1.0, which will be released this week.
Another is to apply the related PR to a branch v0.0.14
