### ISSUE TITLE
main分支代码，locust压测，segment fault

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#827]
如题，locust起两个client并发请求，请求1分钟，停掉locust，就会segment fault

<img width="1075" alt="image" src="https://github.com/InternLM/lmdeploy/assets/6971044/180b3936-7946-47d6-9849-0902cb7f68b0">

运行相关信息：
qwen-7b模型， 单卡跑，rest_api启动

**Comment by frankxyy** [comment]
测试方式：

下载下面的文件
https://drive.google.com/file/d/1nm9bEtJ9OHyu1uzdE_SxS9F_RFyd-LeV/view?usp=sharing 
，

然后安装locust python包，运行命令: locust -f "下载的文件名"，在浏览器打开locust web页面，设置users_num为2，即可。

**Comment by lzhangzz** [comment]
用的哪个commit id？

**Comment by frankxyy** [comment]
@lzhangzz sorry，我git co from 远程命令没拉最新代码，用的不是最新的main。我再试下，估计没问题了
