### ISSUE TITLE
最新功能splitAndFuse使用

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#831]
Hi，看到最新代码好像已经有了splitAndFuse功能，看代码里会fuse decode到prefill里。但好像没看到prefill切分的逻辑。想请教下，prefill切分功能当前是否有了？如果有了的话，切分的size 这些chunk参数在哪配置？ 谢谢！

**Comment by lzhangzz** [comment]
```
; bs 128
num_tokens_per_iter = 256  ; 每个iter期望token数
max_prefill_iters = 64     ; prefill最大iter数（单个prefill任务最多切成多少份）
```

**Comment by frankxyy** [comment]
我看还有个 extra_tokens_per_iter，这个是干什么用的呢？
