### ISSUE TITLE
main分支代码，10并发请求几分钟后，服务卡住

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#832]
使用代码版本：main分支，commit [fix cache verification (#821)](https://gitlab.4pd.io/open-sagegpt/open-sagenano/llm-ft-acc/-/commit/72869ef89f99f3b081e00110f5ae3a4b4d7eaf01)

压测方法：locust压测，并发开到10，测试方法可以参考 https://github.com/InternLM/lmdeploy/issues/827 

现象：压测一段时间后，此时再次向服务请求，一直没有响应

locust 压测结果图表:
<img width="1182" alt="image" src="https://github.com/InternLM/lmdeploy/assets/6971044/b41b00e4-9171-4c5d-8f35-41af85dc9168">

**Comment by frankxyy** [comment]
strace 当前进程：

<img width="1105" alt="image" src="https://github.com/InternLM/lmdeploy/assets/6971044/d4e5dd40-dbee-41d3-b4b3-0add28b1fba9">

**Comment by frankxyy** [comment]
日志更新到这:

<img width="889" alt="image" src="https://github.com/InternLM/lmdeploy/assets/6971044/d17d0d00-006f-40df-867e-23f9e5271b7c">

**Comment by frankxyy** [comment]
pystack的结果

<img width="1067" alt="image" src="https://github.com/InternLM/lmdeploy/assets/6971044/b2c74114-1d89-4a25-b70c-b7e56f58732e">

**Comment by AllentDan** [comment]
你是重新编译了main 的 csrc 测的吗？请求数到了多少，我跑了有一会儿还没出现你说的问题

**Comment by frankxyy** [comment]
@AllentDan 对，重新编译了，就加了些日志，应该没啥影响。你可以stop 现在的locust，然后再新起locust任务试试。可能就能复现了

**Comment by AllentDan** [comment]
用的什么机器？可以运行下 lmdeploy check_env 查看下贴出来

**Comment by frankxyy** [comment]
> 用的什么机器？可以运行下 lmdeploy check_env 查看下贴出来

sys.platform: linux
Python: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3: NVIDIA A10
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.2, V12.2.140
GCC: x86_64-linux-gnu-gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 1.13.1+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.14.1+cu117
LMDeploy: 0.1.0a2+
transformers: 4.36.0
gradio: 3.50.2
fastapi: 0.105.0
pydantic: 2.5.2

**Comment by AllentDan** [comment]
我这边用 A100 跑了和你差不多时间，没有这个问题。我试试把并发拉上去看看能不能复现

**Comment by frankxyy** [comment]
@AllentDan 可以试试多关闭locust，再重启locust几次。仅个人怀疑哈，仅供参考：在req disconnect时stop_session从queue中把res都取走了，另一个原来在get这个queue的协程就取不到res了，一直卡在get那

**Comment by AllentDan** [comment]
这个问题之前遇到过吗？我确认下是不是新代码产生的

**Comment by frankxyy** [comment]
@AllentDan 之前也有过卡在get queue的情况，我当时自己改了python代码，暂时就没出现了。
 
现在我更新到main最新代码，我自己目前还没怎么改，想和你们尽量保持同步，也怕自己改乱了

**Comment by AllentDan** [comment]
> @AllentDan 之前也有过卡在get queue的情况，我当时自己改了python代码，暂时就没出现了。
> 
> 现在我更新到main最新代码，我自己目前还没怎么改，想和你们尽量保持同步，也怕自己改乱了

之前改了哪里啊？我这边复现了，100并发同时停以后会卡住

**Comment by frankxyy** [comment]
@AllentDan 可能不是get_queue的问题，我再回忆下，好像是generator available的问题

**Comment by AllentDan** [comment]
Seems turbomind now can not handle too many stop requests in a short period. 
Here is the test script:
```python
from threading import Thread

from lmdeploy.turbomind.turbomind import TurboMind, TurboMindInstance
from lmdeploy.tokenizer import Tokenizer


tm_model = TurboMind.from_pretrained("/nvme/shared_data/Qwen/Qwen-7B", model_name='qwen-7b', tp=1)
tokenizer = tm_model.tokenizer
generators = [tm_model.create_instance() for i in range(64)]

def start(generator:TurboMindInstance, session_id: int):
    input_ids = tokenizer.encode('hi')
    for item in generator.stream_infer(session_id, input_ids, stream_output=True, sequence_start=True, sequence_end=True, ignore_eos=True):
        pass
def stop(generator:TurboMindInstance, session_id: int):
    input_ids = [tokenizer.eos_token_id]
    for item in generator.stream_infer(session_id, input_ids, request_output_len=0, stop=True, stream_output=True, sequence_start=True, sequence_end=True):
        pass

start_threads = [Thread(target=start, args=(generators[i], i)) for i in range(64)]
stop_threads = [Thread(target=stop, args=(generators[i], i)) for i in range(64)]
for thread in start_threads:
    thread.start()
for thread in stop_threads:
    thread.start()

for thread in start_threads:
    thread.join()
for thread in stop_threads:
    thread.join()

print('begin')
start(generators[0], 0)
print('done')
```

**Comment by frankxyy** [comment]
@AllentDan 过去的想不起来了，我在分析现在代码。
https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/turbomind/turbomind.py#L564
这句是不是有点问题？ register_callback之后，self.que重新初始化了，如果地址变了会不会callback put que put不回来了

**Comment by frankxyy** [comment]
> > @AllentDan 之前也有过卡在get queue的情况，我当时自己改了python代码，暂时就没出现了。
> > 现在我更新到main最新代码，我自己目前还没怎么改，想和你们尽量保持同步，也怕自己改乱了
> 
> 之前改了哪里啊？我这边复现了，100并发同时停以后会卡住

<img width="971" alt="image" src="https://github.com/InternLM/lmdeploy/assets/6971044/dfedf496-7a6f-4495-b853-49f3f1d4064a">

我之前类似这样改的，不会去阻塞调用self.que.get()，如果此时队列为空，c++线程又想callback的话，是不是协程切不出去就卡死了

**Comment by lvhan028** [comment]
这个脚本看起来会出现一种情况：stop先于prompt推理。turbomind会报错，但是这个信息没有返回到上层。

**Comment by lzhangzz** [comment]
> Seems turbomind now can not handle too many stop requests in a short period. Here is the test script:
> 
> ```python
> from threading import Thread
> 
> from lmdeploy.turbomind.turbomind import TurboMind, TurboMindInstance
> from lmdeploy.tokenizer import Tokenizer
> 
> 
> tm_model = TurboMind.from_pretrained("/nvme/shared_data/Qwen/Qwen-7B", model_name='qwen-7b', tp=1)
> tokenizer = tm_model.tokenizer
> generators = [tm_model.create_instance() for i in range(64)]
> 
> def start(generator:TurboMindInstance, session_id: int):
>     input_ids = tokenizer.encode('hi')
>     for item in generator.stream_infer(session_id, input_ids, stream_output=True, sequence_start=True, sequence_end=True, ignore_eos=True):
>         pass
> def stop(generator:TurboMindInstance, session_id: int):
>     input_ids = [tokenizer.eos_token_id]
>     for item in generator.stream_infer(session_id, input_ids, request_output_len=0, stop=True, stream_output=True, sequence_start=True, sequence_end=True):
>         pass
> 
> start_threads = [Thread(target=start, args=(generators[i], i)) for i in range(64)]
> stop_threads = [Thread(target=stop, args=(generators[i], i)) for i in range(64)]
> for thread in start_threads:
>     thread.start()
> for thread in stop_threads:
>     thread.start()
> 
> for thread in start_threads:
>     thread.join()
> for thread in stop_threads:
>     thread.join()
> 
> print('begin')
> start(generators[0], 0)
> print('done')
> ```

这样调用是不对的，同一个instance的接口不能并发调用。instance对应一个和engine通信的通道，而不是一个session。

**Comment by AllentDan** [comment]
Fixed in #835

**Comment by frankxyy** [comment]
pr 835后，实测这个问题仍然存在。 我这边是修改了阻塞调用queue.get那部分代码后，未出现，建议可以关注下

**Comment by lvhan028** [comment]
@

**Comment by frankxyy** [comment]
@lvhan028 
<img width="796" alt="image" src="https://github.com/InternLM/lmdeploy/assets/6971044/151404ff-2741-4f3a-8fb9-fbe94d3770cd">

核心就是get queue这边别blocking调用了，否则可能卡死协程。

不过我这边修改过了以后，出现一个新的问题，长时间压测后，响应时间变慢。。 目前想不通为什么。。

**Comment by AllentDan** [comment]
@frankxyy Thanks for the bug reporting and the proposed resolution. The bug seemed resolved to me as I tested a while the server worked fine.

**Comment by 9950x** [comment]
@AllentDan 你好，这个问题还没解决
我自己写了个压测程序，每一轮测试起若干个线程，每个线程串行发送30个请求，所有线程都收到应答才进行下一轮测试。
设置线程数从1递增到60。
当线程递增到32个(总共进行了1.5小时)，发现有一个请求始终没有返回应答。

这个没返回的请求id是6174
看日志，推理应该是完成了？
```
[TM][WARNING] [ProcessInferRequests] Request for 6174 received.
[TM][INFO] [Interrupt] slot = 7, id = 6174
[TM][INFO] [forward] Request complete for 6174, code 0
```

看堆栈是
```
(Python) File "/data/miniconda3/envs/lmdeploy/lib/python3.10/asyncio/events.py", line 80, in _run
        self._context.run(self._callback, *self._args)
    (Python) File "/data/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/starlette/responses.py", line 255, in wrap
        await func()
    (Python) File "/data/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/starlette/responses.py", line 244, in stream_response
        async for chunk in self.body_iterator:
    (Python) File "/data/tools/lmdeploy/lmdeploy/serve/openai/api_server.py", line 198, in completion_stream_generator
        async for res in result_generator:
    (Python) File "/data/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 282, in generate
        async for outputs in generator.async_stream_infer(
    (Python) File "/data/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 653, in async_stream_infer
        await asyncio.sleep(0)
    (Python) File "/data/miniconda3/envs/lmdeploy/lib/python3.10/asyncio/tasks.py", line 596, in sleep
        await __sleep0()
```
对应代码
``` python
        # generator
        while True:
            # Thanks for https://github.com/frankxyy and his issue
            # https://github.com/InternLM/lmdeploy/issues/832
            while self.que.qsize() == 0:
                await asyncio.sleep(0)
            while self.que.qsize() > 1:
                self.que.get()
```
  
  
**_有8张A800，但我只用GPU1来跑_， 模型llama2_13b_chat 4bit awq , kv cache int8** 。服务器启动的参数
```
serve/openai/api_server.py --instance_num 64 --tp 1
```

check_env的结果
```
sys.platform: linux
Python: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA A800-SXM4-80GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.2, V12.2.91
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.3) 9.4.0
PyTorch: 2.1.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.16.0
LMDeploy: 0.1.0+
transformers: 4.36.2
gradio: Not Found
fastapi: 0.108.0
pydantic: 2.5.3
```
