### ISSUE TITLE
[Bug] llama2-70b 使用AWQ-w4a16量化之后,在吞吐量上并没有明显的提升

### ISSUE THREAD

**Issue by AatroxZZ** [InternLM/lmdeploy#833]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

我用4张A800测试了llama2-70b量化前后的吞吐量，发现并没有特别明显的提升。
问题：
    1、在量化之前(batchsize=64)的吞吐量(completion token)大概是670token/s， 但是awq量化之后(batchsize=64)的吞吐量只有770token/s，我的理解是既然awq推理的速度比FP16快很多，为什么吞吐量上好像并没有很大的提升。
    2、我发现每次接受到一个请求的时候会有一个加入的过程，这个时间是不是导致上述提升不大的原因？

### Reproduction

测试用的脚本是这个 profile_restful_api.py

### Environment

```Shell
4xA800
lmdeploy v0.1.0a2
```

**Comment by lvhan028** [comment]
config.ini贴一下吧

**Comment by lvhan028** [comment]
a100_fp16.md 有 llama2-70b 4卡推理的性能报告

**Comment by lvhan028** [comment]
好的。现在比较忙，明天我试试

**Comment by lvhan028** [comment]
@pppppM 麻烦跟进下这个问题。@AatroxZZ 只是我们用的是awq算法，能分享一下在量化时使用的命令吗？

> 这两天有空帮忙试试吗 而且我发现目前的代码量化70B(calibrate和auto_gptq load模型的时候)好像有问题，会报一个no data的错误，换成之前版本的是work的

**Comment by lvhan028** [comment]
@pppppM 请优先看下 llama2-70b 量化的问题。我用最新的main分支，能够复现
···
NotImplementedError: Cannot copy out of meta tensor; no data!
···

**Comment by lvhan028** [comment]
命令：lmdeploy lite calibrate /nvme/shared_data/llama2/huggingface/llama-2-70b-chat-hf/

**Comment by lvhan028** [comment]
> 这两天有空帮忙试试吗 而且我发现目前的代码量化70B(calibrate和auto_gptq load模型的时候)好像有问题，会报一个no data的错误，换成之前版本的是work的

请问你用的是哪个版本呢？

**Comment by pppppM** [comment]
> NotImplementedError: Cannot copy out of meta tensor; no data!

这个错误在 #848 中修复了
