### ISSUE TITLE
[Feature] 能否支持加速千问新出的Qwen-72B-chat和Qwen-1.8B-chat呢？

### ISSUE THREAD

**Issue by FelixZhang7** [InternLM/lmdeploy#842]
### Motivation

同标题

**Comment by sjzhou4** [comment]
Qwen-72B-chat和14B的结构一样的，直接使用14B的转换就可以的，亲测OK

**Comment by FelixZhang7** [comment]
> Qwen-72B-chat和14B的结构一样的，直接使用14B的转换就可以的，亲测OK

转换过程可以多卡加载吗，一张A100会爆显存的

**Comment by lvhan028** [comment]
用 0.1.0a0 以上的版本
