### ISSUE TITLE
希望lmdeploy支持function call功能

### ISSUE THREAD

**Issue by chenhaoqiang** [InternLM/lmdeploy#852]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

在单卡A10上成功部署了qwen-chat-14b-4bit，使用的这个量化好的：[https://huggingface.co/lmdeploy/qwen-chat-14b-4bit/blob/main/README_zh-CN.md](https://huggingface.co/lmdeploy/qwen-chat-14b-4bit/blob/main/README_zh-CN.md%EF%BC%8C%E4%BD%86%E6%98%AF%E5%8F%91%E7%8E%B0%E5%A5%BD%E5%83%8Ffunction) ，但是发现function call功能没有了：![image](https://github.com/InternLM/lmdeploy/assets/20062034/ac006e10-7573-44b6-8410-fe4697c412b5)

### Reproduction

- 部署qwen-chat-14b-4bit
- 调用chat/completions接口，传入functions参数
- 没有返回function call相关值

### Environment

```Shell
lmdeploy-v0.0.14
```

**Comment by lvhan028** [comment]
function call 和模型强相关。不同的模型，哪怕是相同的function，也都需要来专门适配。
考虑到 function call 带来的维护成本太高，组内觉得暂不加这个功能了。
推荐使用 [lagent](https://github.com/InternLM/lagent)，它实现了 InternLM2 模型的 function call 功能，底层的推理引擎是 lmdeploy

**Comment by chenhaoqiang** [comment]
> function call 和模型强相关。不同的模型，哪怕是相同的function，也都需要来专门适配。
> 
> 考虑到 function call 带来的维护成本太高，组内觉得暂不加这个功能了。
> 
> 推荐使用 [lagent](https://github.com/InternLM/lagent)，它实现了 InternLM2 模型的 function call 功能，底层的推理引擎是 lmdeploy
> 
> 

好的 感谢！
