### ISSUE TITLE
[Feature] [Bug] 请问使用lmdeploy chat turbomind的推理convert之后的模型的时候可以修改模型的system prompt吗？

### ISSUE THREAD

**Issue by FelixZhang7** [InternLM/lmdeploy#853]
### Motivation

如题

**Comment by AllentDan** [comment]
可以，运行代码启动也可以把模型参数传进去。比如internlm 可以启动加 `--meta_instruction "blabla"`

**Comment by FelixZhang7** [comment]
> 可以，运行代码启动也可以把模型参数传进去。比如internlm 可以启动加 `--meta_instruction "blabla"`

请问使用pipeline来推理的话怎么修改system_prompt呢？这时候好像修改不了meta_instruction
