### ISSUE TITLE
[Bug] 加载并转换 llama2 fp16 weight为fp32, memcpy to GPU, weight变为0.000001

### ISSUE THREAD

**Issue by Zhiwei35** [InternLM/lmdeploy#857]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

1. 背景：llama2 HF weight为fp16，我选择做fp32和fp16两种类型的llama推理
2. 问题：

- 使用如[代码链接](https://github.com/InternLM/lmdeploy/blob/main/src/turbomind/utils/memory_utils.cu#L469)的函数将HF llama2 weight转换为fp32并拷贝到GPU来做fp32的 llama forward，**发现经过__half2float后，embedding table的多数值为1e-6，精度几乎全部损失**，原始值为
<img width="629" alt="image" src="https://github.com/InternLM/lmdeploy/assets/84896463/3e08417e-ea67-4134-8cdf-e8af153ed371">

- 使用[代码链接](https://github.com/InternLM/lmdeploy/blob/main/src/turbomind/utils/memory_utils.cu#L463)的函数将HF llama2 weight加载并拷贝到GPU来做fp16的 llama forward，**问题同上**
- PS: [这一行](https://github.com/InternLM/lmdeploy/blob/main/src/turbomind/utils/memory_utils.cu#L456)运行后可以正常打印出上图的1.2517e-06，一旦拷贝到GPU上，1.2517e-06就变成了1e-6
3. 请教：
各位maintainer有遇到过这种问题吗？能给出一些建议吗

### Reproduction

4.复现脚本如下
[test_loadweight.txt](https://github.com/InternLM/lmdeploy/files/13699197/test_loadweight.txt)
5.复现方法：将txt后缀改为.cpp，将文件内的weight路径改为您的本地weight bin路径即可编译&run，打印出来的结果可以正常显示比1e-6的数字，但是一旦copy到GPU，那么将变为0.000001

### Environment

```Shell
NV GPU, cuda12.2, nvcc12.2
```

**Comment by lvhan028** [comment]
为什么不直接用torch的函数转权重类型呢？

**Comment by Zhiwei35** [comment]
> 为什么不直接用torch的函数转权重类型呢？

感谢回复，我对pytorch的api不是特别熟悉，您指的是直接在python层面先转好然后再load & h2d到GPU对吗？转权重类型的函数是torch.to吗

**Comment by lvhan028** [comment]
是的。在python测转好。
api是 `torch.Tensor.float()`。关于torch的api，可以查看torch官方的文档，挺全的。

**Comment by Zhiwei35** [comment]
> 是的。在python测转好。 api是 `torch.Tensor.float()`。关于torch的api，可以查看torch官方的文档，挺全的。

好的，非常感谢，我先close issue试一下，有问题再回来请教~
