### ISSUE TITLE
[Bug] 使用pytorch_poc分支镜像W8A8量化后推理（Expected 'i32' but got 'i8'）

### ISSUE THREAD

**Issue by liang-learning** [InternLM/lmdeploy#861]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

error: invalid element type in packLLEElements. Expected 'i32' but got 'i8'

### Reproduction

python lmdeploy/pytorch_poc/chat.py /workspace codellama

### Environment

```Shell
pytorch 2.0.0
NVIDIA-SMI 470.182.03   Driver Version: 470.182.03   CUDA Version: 11.7
v100
codellama 7b
```

### Error traceback

```Shell
error: invalid element type in packLLEElements. Expected 'i32' but got 'i8'
loc(fused["/lmdeploy/pytorch_poc/kernels/w8a8_triton_kernels.py":82:23, "lmdeploy/pytorch_poc/kernels/w8a8_triton_kernels.py":82:33]): error: 'llvm.intr.fmuladd' op operand #0 must be floating point LLVM type or LLVM dialect-compatible vector of floating point LLVM type, but got 'i8'
Pass execution failedLLVM ERROR: Failed to translate TritonGPU to LLVM IR.
```

**Comment by HIT-cwh** [comment]
Apologies for any inconvenience caused during your usage. Here's the environment I'm currently using:
```
torch 2.0.1
triton 2.1.0
A100
```
I could not replicate your issue in this environment. We will attempt to reproduce it on a V100.

**Comment by HIT-cwh** [comment]
It appears to be a bug in Triton. The 8-bit Triton kernel is unable to operate on the Turing architecture. Please refer to this [issue](https://github.com/openai/triton/issues/1809) for more details.

**Comment by liang-learning** [comment]
Okay, I'll look at this information.
