### ISSUE TITLE
[Bug] llama2-4bit 在2080Ti卡上乱码，最新版是不是已经支持sm7.5了？

### ISSUE THREAD

**Issue by jgbrblmd** [InternLM/lmdeploy#867]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.

### Describe the bug

使用的是最新的 0.1.0，从源码编译的版本。

internlm-chat-20b-4bit可以正常对话，没有乱码，下载于：https://hf.co/internlm/internlm-chat-20b-4bit。 通过lmdeploy convert 转码，然后lmdeploy chat turbomind ./workspace运行，没有乱码。

llama2下载于：https://hf.co/lmdeploy/llama2-chat-70b-4bit，通过lmdeploy convert转码，然后lmdeploy chat turbomind ./workspace运行就有乱码。

同样的显卡2080Ti，只不过llama2用了--tp=2参数，其它几个awq模型也乱码，tp=1和tp=2的都有，包括solar\llama等架构的模型。

qwen72b-awq模型用tp=4转换后可以正常运行，不乱码。

很奇怪，不知道是不是我的机器有问题，请解救。

### Reproduction

lmdeploy convert llama2 ./llama2-chat-70b-4bit --tp=2 --model_format=awq --group_size 128
model_name             llama2
model_format           awq
inferred_model_format  hf-awq
model_path             ./llama2-chat-70b-4bit
tokenizer_path         ./llama2-chat-70b-4bit/tokenizer.model
output_format          w4
*** splitting layers.0.attention.w_qkv.qweight, shape=torch.Size([256, 160, 128, 2]), split_dim=-1, tp=2                                                 
*** splitting layers.0.attention.w_qkv.scales_zeros, shape=torch.Size([64, 10240]), split_dim=-1, tp=2                                                   
*** splitting layers.0.attention.wo.qweight, shape=torch.Size([8192, 1024]), split_dim=0, tp=2                                                           
*** splitting layers.0.attention.wo.scales_zeros, shape=torch.Size([64, 8192]), split_dim=0, tp=2                                                        
*** splitting layers.0.feed_forward.w13.qweight, shape=torch.Size([256, 896, 128, 2]), split_dim=-1, tp=2        
.....

                onvert to turbomind format: 100%|███████████████████████████████████████████████████████████████████████████████████████| 80/80 [02:14<00:00,  1.69s/it]

$ lmdeploy chat turbomind ./workspace
model_source: workspace
12/18 23:39:02 - turbomind - INFO - found tp=2 in config.ini.
[WARNING] gemm_config.in is not found; using default GEMM algo
[WARNING] gemm_config.in is not found; using default GEMM algo
session 1

double enter to end input >>> hello

[INST] <<SYS>>
 You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe. Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.

If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information. 
<</SYS>>

hello [/INST]  Hello oficator... associ, this,,schemas...,.schemasingu im Isaacados Isaac,ederbicator im knadosadosgram,, Hermederb.. recon Hermingugram.- of im im recon.,, ",adosgram, Zel,, of, Herm, Isaac this Herm Isaac recon,,schemas,,. associ ing. " Hermados Isaacicator,,, ing. ,. Herm " this recon, John, Isaac,. kn, kn im.icator im, ,, Zel Herm "gram, Isaac of corn,, John im,ados John Isaac,ederb ofederb, Herm Isaac,icator ing associ Zel. ,gram-. Isaacados,.,ederbados Isaac Isaacgram " corn ",ederb.. recon thisgram, of. ofederb,. recon, Isaac, Zelederb " Isaac corn ,, ing. im, ". " im ", ingados ingingu.. associ Isaacschemas.,.icator. of ,, recon,., reconschemas, " "- , corn, " Herm John " Isaac Isaac.,, Zel.,gramicator,. of im,.,,.. " Isaac associ- this Isaac. Isaac knados of ing John, im,icator. associados ing.., "icator " Isaac John., Herm im,, im. "ederb,, ",,gramederbederb.gram.. associ associ.-icator..,ados Herm,ederb " John,.ederb this corn..gram this, Isaac Isaac Isaac ingederb recon.adosadosederb , of Herm..,.,, kn recon.gram Zel " im reconederbados., Isaac recon Zelingu,...,ados corn Herm " Zel inggram.,, John this, Isaac,ederbederbschemas Isaac, im, associ,-.. " recongramederb corn " , recon im Isaac.ederb im recon Isaac Isaac imgram,,ederbgram Hermados. kn,gram.. Isaac "ados ". John Isaac. "ados. Herm Isaac corn,gram,.gram,. kn ing., cornicator. John. ",..,, ", Hermschemas " this,ederb,schemas this Isaac recon. John. "schemas. im, kn " associ.. recon " corn. ,ederb, cornicator associ " corn,,,.- ,. recon ,ederb " associados Isaac " Isaac Isaac im,, associ ing Isaac ,

同样的internlm-chat-20b-4bit，就没有问题

$ lmdeploy chat turbomind ./workspace.intern
model_source: workspace
WARNING: Can not find tokenizer.json. It may take long time to initialize the tokenizer.
[WARNING] gemm_config.in is not found; using default GEMM algo
session 1

double enter to end input >>> hello

<|System|>:You are an AI assistant whose name is InternLM (书生·浦语).
- InternLM (书生·浦语) is a conversational language model that is developed by Shanghai AI Laboratory (上海人工智能实验室). It is designed to be helpful, honest, and harmless.
- InternLM (书生·浦语) can understand and communicate fluently in the language chosen by the user such as English and 中文.

<|User|>:hello
<|Bot|>: Hello! How can I assist you today?

### Environment

```Shell
$ lmdeploy check_env
sys.platform: linux
Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1: NVIDIA GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.1, V12.1.105
GCC: x86_64-linux-gnu-gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 2.1.1+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.5  (built against CUDA 11.7)
    - Built with CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.16.1+cu121
LMDeploy: 0.1.0+
transformers: 4.36.0
gradio: 3.50.2
fastapi: 0.105.0
pydantic: 2.5.2
```

**Comment by jgbrblmd** [comment]
我发现当我做一次lmdeploy convert之后，就多出一个tokenizer.json文件，应该是自动下载的，会不会是这个文件有问题？

$ cd llama2-chat-70b-4bit/

$ git remote -v
origin	https://hf.co/lmdeploy/llama2-chat-70b-4bit (fetch)
origin	https://hf.co/lmdeploy/llama2-chat-70b-4bit (push)

$ git status
位于分支 main
您的分支与上游分支 'origin/main' 一致。

未跟踪的文件:
  （使用 "git add <文件>..." 以包含要提交的内容）
	tokenizer.json

修改尚未加入提交（使用 "git add" 和/或 "git commit -a"）

**Comment by zhulinJulia24** [comment]
I didn't reproduce it on A100, my step is:

1. download from hf https://huggingface.co/lmdeploy/llama2-chat-70b-4bit

2. convert 
`lmdeploy convert llama2 /nvme/qa_test_models/llama2-chat-70b-4bit --tp=2 --model_format=awq --group_size 128
`
3. chat
`lmdeploy chat turbomind ./workspace
`
model_source: workspace
WARNING: Can not find tokenizer.json. It may take long time to initialize the tokenizer.
12/19 13:05:59 - turbomind - INFO - found tp=2 in config.ini.
[WARNING] gemm_config.in is not found; using default GEMM algo
[WARNING] gemm_config.in is not found; using default GEMM algo
session 1

double enter to end input >>> hello

[INST] <<SYS>>
 You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe. Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.

If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information. 
<</SYS>>

hello [/INST]  Hello! I'm here to assist you in any way I can. Is there something specific you need help with or a question you have? Please feel free to ask, and I'll do my best to provide a helpful and accurate response.

double enter to end input >>> what is your name?

[INST] what is your name? [/INST]  My name is Assistant, and I'm here to help you with any questions or tasks you may have! How can I assist you today?

double enter to end input >>> exit

**Comment by jgbrblmd** [comment]
@zhulinJulia24 谢谢你的验证，我又把我的lmdeploy virtualenv删掉重新创建，同时把原来编译安装的openmpi也从系统删除，这次只使用pip install lmdeploy安装了依赖的包，然后运行llama2的convert和chat，结果还是一样，有乱码，同时internlm-chat-20b-4bit还是能正常运行。llama2的权重文件我也校验了sha256sum，都和huggingface上一致。
很奇怪，现在我的pip list 结果如下：

$ pip list
Package                  Version
------------------------ ----------
addict                   2.4.0
certifi                  2023.11.17
charset-normalizer       3.3.2
filelock                 3.13.1
fire                     0.5.0
fsspec                   2023.12.2
huggingface-hub          0.19.4
idna                     3.6
importlib-metadata       7.0.0
Jinja2                   3.1.2
lmdeploy                 0.1.0
markdown-it-py           3.0.0
MarkupSafe               2.1.3
mdurl                    0.1.2
mmengine-lite            0.10.1
mpmath                   1.3.0
networkx                 3.2.1
numpy                    1.26.2
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.18.1
nvidia-nvjitlink-cu12    12.3.101
nvidia-nvtx-cu12         12.1.105
packaging                23.2
pip                      23.3.2
platformdirs             4.1.0
Pygments                 2.17.2
PyYAML                   6.0.1
regex                    2023.10.3
requests                 2.31.0
rich                     13.7.0
safetensors              0.4.1
sentencepiece            0.1.99
setuptools               69.0.2
six                      1.16.0
sympy                    1.12
termcolor                2.4.0
tiktoken                 0.5.2
tokenizers               0.15.0
tomli                    2.0.1
torch                    2.1.2
tqdm                     4.66.1
transformers             4.36.2
triton                   2.1.0
typing_extensions        4.9.0
urllib3                  2.1.0
wheel                    0.42.0
yapf                     0.40.2
zipp                     3.17.0

你是否方便把你的环境pip list结果给我对照一下，我看会不会有版本的差别。
如果找不到问题，我会租一个有2块sm75显卡的云主机测试一下，看一下是否会出同样的错误。

谢谢！

**Comment by zrqohbug** [comment]
现象相同，2080ti推理llama架构有乱码，qwen72b就没问题，大佬后来看到原因了吗，谢谢



> @zhulinJulia24 谢谢你的验证，我又把我的lmdeploy virtualenv删掉重新创建，同时把原来编译安装的openmpi也从系统删除，这次只使用pip install lmdeploy安装了依赖的包，然后运行llama2的convert和chat，结果还是一样，有乱码，同时internlm-chat-20b-4bit还是能正常运行。llama2的权重文件我也校验了sha256sum，都和huggingface上一致。 很奇怪，现在我的pip list 结果如下：
> 
> $ pip list Package Version
> 
> addict 2.4.0 certifi 2023.11.17 charset-normalizer 3.3.2 filelock 3.13.1 fire 0.5.0 fsspec 2023.12.2 huggingface-hub 0.19.4 idna 3.6 importlib-metadata 7.0.0 Jinja2 3.1.2 lmdeploy 0.1.0 markdown-it-py 3.0.0 MarkupSafe 2.1.3 mdurl 0.1.2 mmengine-lite 0.10.1 mpmath 1.3.0 networkx 3.2.1 numpy 1.26.2 nvidia-cublas-cu12 12.1.3.1 nvidia-cuda-cupti-cu12 12.1.105 nvidia-cuda-nvrtc-cu12 12.1.105 nvidia-cuda-runtime-cu12 12.1.105 nvidia-cudnn-cu12 8.9.2.26 nvidia-cufft-cu12 11.0.2.54 nvidia-curand-cu12 10.3.2.106 nvidia-cusolver-cu12 11.4.5.107 nvidia-cusparse-cu12 12.1.0.106 nvidia-nccl-cu12 2.18.1 nvidia-nvjitlink-cu12 12.3.101 nvidia-nvtx-cu12 12.1.105 packaging 23.2 pip 23.3.2 platformdirs 4.1.0 Pygments 2.17.2 PyYAML 6.0.1 regex 2023.10.3 requests 2.31.0 rich 13.7.0 safetensors 0.4.1 sentencepiece 0.1.99 setuptools 69.0.2 six 1.16.0 sympy 1.12 termcolor 2.4.0 tiktoken 0.5.2 tokenizers 0.15.0 tomli 2.0.1 torch 2.1.2 tqdm 4.66.1 transformers 4.36.2 triton 2.1.0 typing_extensions 4.9.0 urllib3 2.1.0 wheel 0.42.0 yapf 0.40.2 zipp 3.17.0
> 
> 你是否方便把你的环境pip list结果给我对照一下，我看会不会有版本的差别。 如果找不到问题，我会租一个有2块sm75显卡的云主机测试一下，看一下是否会出同样的错误。
> 
> 谢谢！

**Comment by lvhan028** [comment]
我在 2080 上，推理 [llama2-7b-chat-4bits](https://huggingface.co/lmdeploy/llama2-chat-7b-w4)，是正常的。
推理 [internlm2-chat-7b-4bits](https://huggingface.co/internlm/internlm2-chat-7b-4bits) ，遇到乱码。
具体原因还在找

**Comment by 11zhouxuan** [comment]
> 我在 2080 上，推理 [llama2-7b-chat-4bits](https://huggingface.co/lmdeploy/llama2-chat-7b-w4)，是正常的。
> 推理 [internlm2-chat-7b-4bits](https://huggingface.co/internlm/internlm2-chat-7b-4bits) ，遇到乱码。
> 具体原因还在找

同样的现象，在T4机器上推理internlm2-chat-7b-4bits遇到乱码，A10机器正常。

同时在T4机器上推理internlm2-chat-20b-4bits正常。

**Comment by zrqohbug** [comment]
https://github.com/InternLM/lmdeploy/blob/24ea5dc57e85156a32620a9d6a9ff884f2917fb4/CMakeLists.txt#L21 猜测是flash attn 在 2080ti上不支持导致的，我关闭了llama flash attn use_context_fmha = 0 用 kvcacheint8 就没有乱码了。暂时没时间测试，大佬们有兴趣试试 @lvhan028 @lzhangzz

**Comment by lvhan028** [comment]
最新的main分支已经修复了这个问题。月底发版之后，可以再试试

**Comment by lvhan028** [comment]
v0.3.0 修复了这个问题
@jgbrblmd @zrqohbug 可以试试看
