### ISSUE TITLE
[Docs] V100上没有4比特权重量化的原因是什么？

### ISSUE THREAD

**Issue by liang-learning** [InternLM/lmdeploy#876]
### 📚 The doc issue

![image](https://github.com/InternLM/lmdeploy/assets/53997477/078876ad-f3ca-48cd-ad74-d5d559618a5d)
docs/en/w4a16.md
如图说明不支持v100系列；想了解一下是什么原因；

**Comment by lvhan028** [comment]
因为 v100（sm70） 的 tensor core 指令和 sm75（20系列，T4），sm80（A100）差别太大了，支持起来太麻烦了，所以就没支持了。。。

**Comment by WCwalker** [comment]
> 因为 v100（sm70） 的 tensor core 指令和 sm75（20系列，T4），sm80（A100）差别太大了，支持起来太麻烦了，所以就没支持了。。。

请教一下是不是意思是T4卡支持量化推理，感谢，因为我们手头没有T4，但是后续将会在T4环境上部署模型，所以想先了解一下觉得模型选型，感谢

**Comment by lvhan028** [comment]
是的。支持在T4上对量化模型的推理
