### ISSUE TITLE
请问这个部署支持多卡吗？

### ISSUE THREAD

**Issue by alexw994** [InternLM/lmdeploy#88]

**Comment by lvhan028** [comment]
Yes. You can follow [this document](https://github.com/InternLM/lmdeploy/blob/main/docs/en/serving.md) to serving LLaMA 65B model on a server with 8 GPU cards

**Comment by alexw994** [comment]
> Yes. You can follow [this document](https://github.com/InternLM/lmdeploy/blob/main/docs/en/serving.md) to serving LLaMA 65B model on a server with 8 GPU cards

谢谢，我找到了
tp (int): the number of GPUs used for tensor parallelism
这是自动实现的
