### ISSUE TITLE
[Bug] codellama-34b INT4 量化，Not implemented

### ISSUE THREAD

**Issue by thendwk** [InternLM/lmdeploy#881]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

我们对codellama-34b进行int4量化时，报了如下错误：
`enter !! to end the input >>>
用rust写一个hello world
！！
!!
<BOS>[INST] <<SYS>>

<</SYS>>

用rust写一个hello world
！！ [/INST] terminate called after throwing an instance of 'std::runtime_error'
  what():  [TM][ERROR] Not implemented Assertion fail: /data/Imdeploy/data_2304/0.0.13/src/lmdeploy/src/turbomind/models/llama/LlamaLinear.h:79 

Aborted (core dumped)`
是还不支持codellama的int4量化吗？

### Reproduction

生成量化参数
`
export C4_TRAIN=/workspace/c4_dataset/c4-train.00000-of-01024.json.gz
export C4_DEV=/workspace/c4_dataset/c4-validation.00000-of-00008.json.gz
lmdeploy lite calibrate \
--model ${HF_MODEL_DIR} \
--calib_dataset 'c4' \
--calib_samples 128 \
--calib_seqlen 2048 \
--work_dir ${HF_MODEL_DIR}/awq/int4 `
量化权重
`lmdeploy lite auto_awq \
--model ${HF_MODEL_DIR} \
--w_bits 4 \
--w_group_size 128 \
--work_dir ${HF_MODEL_DIR}/awq/int4`
转换格式
`
lmdeploy convert \
--model-name codellama \
--model-path ${HF_MODEL_DIR}/awq/int4 \
--model-format awq \
--group-size 128 \
--tokenizer_path ${HF_MODEL_DIR}/tokenizer.model \
--dst_path ${HF_MODEL_DIR}/turbomind/int4/2gpu \
--tp 2
`
执行推理
`
lmdeploy chat turbomind --model_path codellama-34b-python-mft-qlora-v1-step22000-merged/turbomind/int4/2gpu --tp 2
`
### Environment

```Shell
lmdeploy0.0.13
dtk23.04
torch1.13
py38
```

### Error traceback

```Shell
erminate called after throwing an instance of 'std::runtime_error'
  what():  [TM][ERROR] Not implemented Assertion fail: /data/Imdeploy/data_2304/0.0.13/src/lmdeploy/src/turbomind/models/llama/LlamaLinear.h:79 

Aborted (core dumped)
```

**Comment by irexyc** [comment]
我这里没办法复现，看报错的文件路径，似乎是你自己编译的lmdeploy，你可以试试我们编译的版本
```
pip install lmdeploy==0.0.13
```

**Comment by thendwk** [comment]
> 我这里没办法复现，看报错的文件路径，似乎是你自己编译的lmdeploy，你可以试试我们编译的版本
> 
> ```
> pip install lmdeploy==0.0.13
> ```

好的，我们试试

**Comment by lvhan028** [comment]
hi @thendwk codellama量化后会跑飞
@pppppM 在 issue #469 中解释了原因。因有其他工作安排，对这个问题的修复目前排期比较靠后

**Comment by thendwk** [comment]
> hi @thendwk codellama量化后会跑飞 @pppppM 在 issue #469 中解释了原因。因有其他工作安排，对这个问题的修复目前排期比较靠后

好的，感谢回复
