### ISSUE TITLE
streaming 请求，请求到一半停止，显存上升，有一点概率OOM

### ISSUE THREAD

**Issue by frankxyy** [InternLM/lmdeploy#886]
如题。相同请求，如果不中途停止，显存比中途停止后的显存占用要小。

**Comment by frankxyy** [comment]
可能是我改的代码，在遇到asyncio cancelError 时，没有去stop_session。 话说，如果一个session 开了以后，不stop 会怎样？ 应该只是一直占着显存其他没影响吧？

**Comment by frankxyy** [comment]
<img width="1323" alt="image" src="https://github.com/InternLM/lmdeploy/assets/6971044/1a0e130d-c4e6-41cd-a969-e54dce425c70">


我这边目前统计出的结果是: 当一个request complete后，下一次调用 dynamic_decode_layer_->setup 前还有4.5G 显存，调用了 dynamic_decode_layer_->setup 后，就OOM

**Comment by frankxyy** [comment]
<img width="873" alt="image" src="https://github.com/InternLM/lmdeploy/assets/6971044/f67cccb3-612b-40c0-bd10-409cf919c8e5">
<img width="1374" alt="image" src="https://github.com/InternLM/lmdeploy/assets/6971044/2dd9e38e-f75b-4e06-9622-85c8d98e14e7">

OOM前，sampling_workspace_size_ 打印出来，是个极其大的数

**Comment by lzhangzz** [comment]
这个地方变得很大是因为Python推理线程出现异常直接quit，导致runtime_top_k的buffer失效了。可以检查一下Python的线程抛了什么异常。

**Comment by frankxyy** [comment]
@lzhangzz python 推理线程由于streaming请求的client停止，所以quit了。不过quit，为什么会造成turbomind里的buffer失效？理论上感觉不影响c++这边的逻辑？

**Comment by frankxyy** [comment]
我这边目前的排查进度是: 两个请求，第一个请求对应python线程quit后，其req在c++侧一直forward到Finishi。然后另一个请求继续处理。但从下一个batch_state.req里取出的runtime_top_k是极大的一个数

**Comment by frankxyy** [comment]
打日志追踪看了下，确实当一个session_id 对应的python线程quit后，c++里batch_state里对应的request里取出的runtime_top_k就变成了一个极大的数

**Comment by frankxyy** [comment]
<img width="897" alt="image" src="https://github.com/InternLM/lmdeploy/assets/6971044/5ac8f4cd-ddca-4f30-ba1b-83c86297c825">

可能需要修改下TensorMap class 的holder type
