### ISSUE TITLE
[Bug] qwen-14b-w4 tp=2时无法转换成turbomind，什么时候能支持？

### ISSUE THREAD

**Issue by sjzhou4** [InternLM/lmdeploy#896]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

![image](https://github.com/InternLM/lmdeploy/assets/142190228/be867f82-1714-47db-9846-fa866dcab798)

### Reproduction

lmdeploy==0.1.0

### Environment

```Shell
qwen-14b使用tp = 2
```

**Comment by lvhan028** [comment]
正如日志显示的，scale_zeroes的shape不能被tp整除，所以tp失败。
一个解决方式是量化推理的时候，group_size变小，比如64
不过，现在预编译包中是固定了 group_size 为128 的。
我们会来验证下group size 为64的情况。
目前，团队在赶 2 周后的 ddl。等 ddl 之后，我们来处理这个问题

**Comment by zhisunyy** [comment]
请问下，qwen-14b-w4 tp=2的问题，大概什么时候能够支持？

**Comment by lvhan028** [comment]
这个feature暂时没有排上，有其他任务要赶
