### ISSUE TITLE
[Bug] v0.1.0 修改 async_engine.generate中参数报错

### ISSUE THREAD

**Issue by zeroleavebaoyang** [InternLM/lmdeploy#898]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

![image](https://github.com/InternLM/lmdeploy/assets/2542251/71d3f175-8329-43d2-902f-f1aaead3c814)

### Reproduction

```
 async for outputs in async_engine.generate(
                prompt,
                1,
                stream_response=True,
                sequence_start=True,
                repetition_penalty=1.1,
                sequence_end=True):
            text += outputs.response
```
添加了 repetition_penalty=1.1,  就会报错 请看下

### Environment

```Shell
lmdeploy 0.1.0
```

**Comment by AllentDan** [comment]
复现不出。麻烦贴一下`lmdeploy check_env` 的结果

**Comment by zeroleavebaoyang** [comment]
> 复现不出。麻烦贴一下`lmdeploy check_env` 的结果

![image](https://github.com/InternLM/lmdeploy/assets/2542251/75334b32-b989-40b3-8e5f-358c55799838)

**Comment by AllentDan** [comment]
我们可能没在 cuda 12 上做充分的测试。这个问题是新版本才有的问题吗

**Comment by zeroleavebaoyang** [comment]
> 我们可能没在 cuda 12 上做充分的测试。这个问题是新版本才有的问题吗

是的， v 0.1.0新版本，  出现的 ，

**Comment by CocaColaKing** [comment]
> 我们可能没在 cuda 12 上做充分的测试。这个问题是新版本才有的问题吗

我也遇到了这个问题，async_engine.generate中添加了repetition_penalty后，如果它的值不是1.0，那么在长文本推理的时候就会直接报错。
config.ini:
```
[llama]
model_name = qwen-7b
tensor_para_size = 2
head_num = 32
kv_head_num = 32
vocab_size = 151936
num_layer = 32
inter_size = 11008
norm_eps = 1e-06
attn_bias = 1
start_id = 0
end_id = 151643
session_len = 32770
weight_type = bf16
rotary_embedding = 128
rope_theta = 10000.0
size_per_head = 128
group_size = 0
max_batch_size = 64
max_context_token_num = 1
step_length = 1
cache_max_entry_count = 0.5
cache_block_seq_len = 128
cache_chunk_size = 1
use_context_fmha = 1
quant_policy = 0
max_position_embeddings = 32768
rope_scaling_factor = 1.0
use_logn_attn = 1
```

调用：
```
async_engine = AsyncEngine(model_path='./workspace',
                               instance_num=1,
                               tp=2)
text = ''
async for outputs in async_engine.generate(
            prompt,
            session_id,
            stream_response=True,
            sequence_start=True,
            repetition_penalty=1.1,
            sequence_end=True):
        text += outputs.response
```

输入一个30815个token的prompt：
> [TM][INFO] [forward] Enqueue requests
> [TM][INFO] [forward] Wait for requests to complete ...
> [TM][WARNING] [ProcessInferRequests] Request for 140669228590912 received.
> [TM][INFO] [Forward] [0, 1), dc_bsz = 0, pf_bsz = 1, n_tok = 30815, max_q = 30815, max_k = 30815
> 
> Process finished with exit code 134 (interrupted by signal 6:SIGABRT)

我用的版本是lmdeploy0.1.0 、 cuda11.8 、Python3.10。
