### ISSUE TITLE
请问未来会支持 Beam search 吗？

### ISSUE THREAD

**Issue by B-201** [InternLM/lmdeploy#90]
看到src里有Beam search相关的代码，但是似乎还不能设置，请问未来会支持吗

**Comment by tpoisonooo** [comment]
我看了  LLaMa / Baichuan 都是在用 sample。 是否支持，还看 LLM 本身默认配置是否开启 beam search，现在还没看到哪个在用。

如果你发现哪个模型默认用了，请告诉我们。

**Comment by lvhan028** [comment]
Close it since no more activity over two weeks. Feel free to reopen it if it is still an issue
