### ISSUE TITLE
支持tritonserver

### ISSUE THREAD

**Issue by coderchem** [InternLM/lmdeploy#91]
我看了一下代码，tritonBackend好像也支持，但是没int8_mode的选项，是没有支持吗？

**Comment by tpoisonooo** [comment]
nvidia/FT 的 int8_mode (数值 2)  已经废弃了，要在配置里把  quant_policy 设置为  4，表示 kv_cache_int8 量化

https://github.com/InternLM/lmdeploy/blob/main/README_zh-CN.md
https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/quantization.md

**Comment by tpoisonooo** [comment]
中文文档 “量化部署”。

**Comment by coderchem** [comment]
文档中，没有使用进行加速，只是量化计算精度，有尝试：量化+加速吗？

**Comment by tpoisonooo** [comment]
kv_cache 量化引入了额外的 dequant 计算，这个开销抵消不了极致优化后 显存降低 75% 带来的 ldg 加速。

服务端看重的是吞吐量，不止是响应速度。

**Comment by tpoisonooo** [comment]
nivida/FT 原始的  int8_mode==2 计算过程中用 intX，但精度损失太高了。

如果结果是错的，那快就没有意义。

**Comment by xiaoFine** [comment]
@tpoisonooo workspace/triton_models里的模型可以直接用在原生的nvidia tritonserver吗？我看到interactive是turbomind的backend

**Comment by lvhan028** [comment]
Close since no more activity over 2 weeks. Feel free to reopen it if it is still an issue
