### ISSUE TITLE
[Docs] qwen-vl-chat

### ISSUE THREAD

**Issue by Vincent131499** [InternLM/lmdeploy#920]
### 📚 The doc issue

看到已经支持了qwen-vl-chat模型，great work！
有以下几个疑问：
1.qwen-vl-chat量化/w4a16后，可以部署triton server吗？
2.若可以部署triton server，那么对应的客户端要怎么请求呢，有对应代码吗
烦请解答下，感谢！

**Comment by Vincent131499** [comment]
> 量化后支持推理。这个模型结构跟标准的llama没什么区别。只是input_embs里面有一部分图片的特征。
> 
> 现有triton server不支持多模态。跟正常的llm相比，主要区别在预处理的部分，逻辑如`examples/vl`里面的差不多。
> 
> triton server有点重了，后面我们更想用restful api，应该会增加[pipeline](https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/inference/pipeline.md)的多模态接口

OK，感谢回复！
后面什么时候可以使用restful api体验下qwen-vl呢，
另外llava这类会支持吗

**Comment by chynphh** [comment]
请问 pipeline 的多模态接口支持了吗

**Comment by lvhan028** [comment]
#1214 正在支持。争取下周发版

**Comment by lvhan028** [comment]
已经发布了，v0.2.6
可以试用下

**Comment by serser** [comment]
pipeline 可以支持量化llama部分吗

**Comment by irexyc** [comment]
> pipeline 可以支持量化llama部分吗

@serser 
支持用lmdeploy 的工具进行awq量化，具体可以参考 https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/quantization/w4a16.md
