### ISSUE TITLE
[Feature] 请问在使用pipeline推理的时候能否支持流式输出，我看现在的参数里没有可以配置的，是要改源码吗？

### ISSUE THREAD

**Issue by FelixZhang7** [InternLM/lmdeploy#938]
### Motivation

如题

**Comment by AllentDan** [comment]
流式是需要返回结果里包含输入的顺序吗？

**Comment by AllentDan** [comment]
之前写过一版，可以用下然后给点反馈
https://github.com/InternLM/lmdeploy/issues/636#issuecomment-1801072514

**Comment by FelixZhang7** [comment]
> 之前写过一版，可以用下然后给点反馈 [#636 (comment)](https://github.com/InternLM/lmdeploy/issues/636#issuecomment-1801072514)

你好，我试了一下是可以跑的，也符合效果，但是还想问一下如果我在这个基础上想修改system prompt，该怎么传进去呢？

**Comment by AllentDan** [comment]
之前应该是传 meta_instruction。现在最新接口是传 ChatTemplateConfig

**Comment by FelixZhang7** [comment]
> 之前应该是传 meta_instruction。现在最新接口是传 ChatTemplateConfig

好的感谢，想多问一下batch推理的原理是什么样的呢，看起来就是把几个input的seq按顺序输入模型，然后分别取到结果，是怎么实现加速的呢？
