### ISSUE TITLE
量化后的hf权重不能当成原来的hf权重一样读取吗？

### ISSUE THREAD

**Issue by seifer08ms** [InternLM/lmdeploy#944]
原模型的hf权重，可以直接通过transformer库读取，然后聊天是正常的

W4A16 量化后的hf权重转为turbomind，再用lmdeploy命令聊天运行也正常。
但如果直接用原模型hf权重的读取方式，读取量化后的hf权重，然后启动聊天，回答问题全是无意义的乱码。
![1705218711491](https://github.com/InternLM/lmdeploy/assets/506463/def0780b-55ef-4d3b-bcc9-a0e02a69d982)

问题是：  量化后的hf权重，只能用lmdeploy来读取吗？

**Comment by lvhan028** [comment]
是的。因为权重的layout已经发生变化了
