### ISSUE TITLE
 I am confused about KV Cache Manager, How does it work?

### ISSUE THREAD

**Issue by randomseed713** [InternLM/lmdeploy#95]

**Comment by tpoisonooo** [comment]
KV Cache Manager is just a **plain memory pool**.

You already know elemsize before create it; 
You told it datatype (fp16 or int8 or int4) when initializing it;
You just take or put a piece of cache in it.

@lzhangzz  please give more architecture doc about it.

**Comment by tpoisonooo** [comment]
@randomseed713  Does this PR answered the question ?   https://github.com/InternLM/lmdeploy/pull/101

**Comment by lvhan028** [comment]
Close since no more activity over 2 weeks. Feel free to reopen it if it is still an issue
