### ISSUE TITLE
请问v0.1.0版本的lmdeploy，int4可以同时使能int8 kvcache吗

### ISSUE THREAD

**Issue by zhisunyy** [InternLM/lmdeploy#976]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

请问v0.1.0版本的lmdeploy，int4可以同时使能int8 kvcache吗？文档里说kCacheKVInt8 和 WeightInt4 两种方案可以同时开启。具体是要怎么设置呢？没大看明白

### Reproduction

无

### Environment

```Shell
无
```

**Comment by lvhan028** [comment]
试过都加上，对话是正常的。不过，我们没有评测过整体的精度。所以现在不好推荐说能不能上生产。
单纯的int4是可以的。

**Comment by zhisunyy** [comment]
我测了下qwen14b，int4 awq + int8 kvcache好像没有省显存，你们测试int4 awq + int8 kvcache有省显存吗？
