### ISSUE TITLE
[Bug] CUDA runtime error: out of memory

### ISSUE THREAD

**Issue by copperdong** [InternLM/lmdeploy#978]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

运行 2 版本
from lmdeploy import pipeline
pipe = pipeline("internlm/internlm2-chat-7b")
response = pipe(["Hi, pls intro yourself", "Shanghai is"])
print(response)
使用 3090 显卡，但还是报错 out of memory

### Reproduction

from lmdeploy import pipeline
pipe = pipeline("internlm/internlm2-chat-7b")
response = pipe(["Hi, pls intro yourself", "Shanghai is"])
print(response)

### Environment

```Shell
ubuntu 22.04, python 3.10 lmdeploy==0.2.0 cuda=12.1
```

**Comment by lvhan028** [comment]
```python
from lmdeploy import pipeline, TurbomindEngineConfig

backend_config = TurbomindEngineConfig(cache_max_entry_count=0.2)
pipe = pipeline('internlm/internlm-chat-7b',
                backend_config=backend_config)
response = pipe(['Hi, pls intro yourself', 'Shanghai is'])
print(response)
```
May try the above code. `cache_max_entry_count` is used to adjust the k/v cache memory ratio of the total GPU memory.
The defautl value is 0.5
