### ISSUE TITLE
Can we have support for GGML as triton backend

### ISSUE THREAD

**Issue by tikikun** [InternLM/lmdeploy#98]
I think this is something interesting and no one has done it before

**Comment by tpoisonooo** [comment]
Indeed llama.cpp/GGML is famous (about 30k star), but the code is **really hard** to maintain.

InferLLM may be a better choice.

**Comment by tikikun** [comment]
wow what is it can you elaborate a bit more, to what i understand it's just that you need to implement the ggml itself into the triton backend and later on you can reuse the triton backend and have the benefit of ggml update after every iteration

**Comment by tikikun** [comment]
will not be re-using fastertransformer i guess but more about how the ggml itself can be integrated with tritonbackend

**Comment by tpoisonooo** [comment]
> will not be re-using fastertransformer i guess but more about how the ggml itself can be integrated with tritonbackend

Here is my opinion, when you integrate a inference backend, you have to make sure of service quality.
Let's take a assumption, after integration, if `ggml` has a bug, lmdeploy has responsibility to locate it or fix it. 

The greater cost of software is maintenance, so we need to consider the code complexity of ggml.

**Comment by tpoisonooo** [comment]
About InferLLM  https://github.com/MegEngine/InferLLM

**Comment by tikikun** [comment]
but having ggml also can attract more contributors, also i'm curious whether inferLLM support cuda, doesn't see that on the page

**Comment by tikikun** [comment]
saw enable gpu on the cmake file still

**Comment by tpoisonooo** [comment]
> but having ggml also can attract more contributors, also i'm curious whether inferLLM support cuda, doesn't see that on the page

yes, attracting more contributors is a good reason to integrate ggml.

**Comment by tpoisonooo** [comment]
> but having ggml also can attract more contributors, also i'm curious whether inferLLM support cuda, doesn't see that on the page

InferLLM cuda part is WIP  https://github.com/MegEngine/InferLLM/pull/27

**Comment by tikikun** [comment]
InferLLM will have many language barriers for non-chinese speakers contributors also, which is a very large audience, for most of the open source implementation it depends on how many contributors you have.

**Comment by tpoisonooo** [comment]
> InferLLM will have many language barriers for non-chinese speakers contributors also, which is a very large audience, for most of the open source implementation it depends on how many contributors you have.

Already passed on to InferLLM team .. QvQ

**Comment by lvhan028** [comment]
Close since no more activity over two weeks. Feel free to reopen it if it is still an issue
