### ISSUE TITLE
[Feature] 希望能像VLLM一样提供RAY分布式推理支持

### ISSUE THREAD

**Issue by HSLUCKY** [InternLM/lmdeploy#989]
### Motivation

[Feature] 希望能像VLLM一样提供RAY分布式推理支持

### Related resources

[Feature] 希望能像VLLM一样提供RAY分布式推理支持

### Additional context

[Feature] 希望能像VLLM一样提供RAY分布式推理支持

**Comment by lvhan028** [comment]
TP 一直都是支持的。

**Comment by lvhan028** [comment]
lmdeploy serve api_server internlm/internlm2-chat-20b --tp 2 就好了

**Comment by HSLUCKY** [comment]
是分布式多机多卡。不单单是单机多卡

**Comment by HSLUCKY** [comment]
而且需要支持ray

**Comment by lvhan028** [comment]
目前 pipeline parallelism 还没有支持的计划
