### ISSUE TITLE
Comparasion with vllm

### ISSUE THREAD

**Issue by lucasjinreal** [InternLM/lmdeploy#99]
vllm can boost up to 24x compare with vanilla llama version, does lmdeploy have any speed test compare with it?

**Comment by KimmiShi** [comment]
Mark, I tested Vllm, about 2x the performance of deepspeed.

**Comment by KimmiShi** [comment]
@lucasjinreal why close this ...?

**Comment by lucasjinreal** [comment]
I have using vllm got a reasonable performance, there is no need to adopt other framework. Furturemore, one can expect TensorRTLM next month, which could be a killer in LLM faster inference.

**Comment by wangruohui** [comment]
Hi @KimmiShi,

Can you share some information about your test setting? Based on our setting, vllm is slower than deepspeed.

1. vllm's default benchmark uses sharegpt data and include *input token* in throughput computation.
2. For deepspeed and vllm, we use a batch of fake data and let the model generate to its max length (2048 new tokens for llama-7b), and compute only throughput of newly generated data. Vllm is only about half throughput of deepspeed.

**Comment by lucasjinreal** [comment]
It's import possible deepspeed faster than vllm, they are essentially different things. Just try PagedAtten, it's way more faster than you think.

**Comment by wangruohui** [comment]
> It's impossible deepspeed faster than vllm, they are essentially different things. Just try PagedAtten, it's way more faster than you think.

How much throughput do you achieve with vllm (say on single A100)?

**Comment by MikhaelSorkin** [comment]
> I have using vllm got a reasonable performance, there is no need to adopt other framework. Furthermore, one can expect TensorRTLM next month, which could be a killer in LLM faster inference.

Hello, could you please share some information about “ TensorRTLM” project? Haven’t found any info about it: no articles, no announcements - nothing :(

**Comment by Kevinddddddd** [comment]
> > I have using vllm got a reasonable performance, there is no need to adopt other framework. Furthermore, one can expect TensorRTLM next month, which could be a killer in LLM faster inference.
> 
> Hello, could you please share some information about “ TensorRTLM” project? Haven’t found any info about it: no articles, no announcements - nothing :(

+1

**Comment by sleepwalker2017** [comment]
> killer

It's a secret project that has not announced yet. They give some companies tryout. Maybe in this month. But I don't think it any better than FT.

**Comment by AIApprentice101** [comment]
vLLM does not support quantization yet. How's the comparison performed? Are we comparing both under float16 precision?

**Comment by sleepwalker2017** [comment]
vllm has little optimization about speed. only for throughput.

The advantage is paged attention which uses less GPU memory, and continuous batching which gives higher GPU occupancy.

But as the implementation is almost all in python, the GPU utilization is not high, maybe 80%.

Just test it yourself.

lmdeploy uses more GPU memory, but the kernels are more performant.

**Comment by ishaan-jaff** [comment]
Hi i'm the maintainer of LiteLLM and we allow you to maximize throughput by load balancing between multiple LLM endpoints. 
Thought it would be useful for people on this thread, **I'd love feedback if not**

**Here's the quick start, to use LiteLLM load balancer (works with 100+ LLMs)** 
doc: https://docs.litellm.ai/docs/simple_proxy#model-alias 

## Step 1 Create a Config.yaml
```python
model_list:
- model_name: openhermes
  litellm_params:
      model: openhermes
      temperature: 0.6
      max_tokens: 400
      custom_llm_provider: "openai"
      api_base: http://192.168.1.23:8000/v1
- model_name: openhermes
  litellm_params:
      model: openhermes
      custom_llm_provider: "openai"
      api_base: http://192.168.1.23:8001/v1
- model_name: openhermes
  litellm_params:
      model: openhermes
      custom_llm_provider: "openai"
      frequency_penalty : 0.6
      api_base: http://192.168.1.23:8010/v1
```

## Step 2: Start the litellm proxy:
```
litellm --config /path/to/config.yaml
```

## Step3 Make Request to LiteLLM proxy:
```
curl --location 'http://0.0.0.0:8000/chat/completions' \
--header 'Content-Type: application/json' \
--data ' {
      "model": "openhermes",
      "messages": [
        {
          "role": "user",
          "content": "what llm are you"
        }
      ],
    }
'
```

**Comment by AlexBlack2202** [comment]
hello, but is LMDeploy still faster than vllm at this time, in fp16?

**Comment by lvhan028** [comment]
Here is the benchmark result on A100(80G) with llama3-8b.
![image](https://github.com/user-attachments/assets/f79802e8-05c8-4ce0-b79c-05f8c139675a)
![image](https://github.com/user-attachments/assets/20186fb0-67e6-4211-9f2c-c6b1471ade52)
![image](https://github.com/user-attachments/assets/4c659078-c05b-4ea1-b4b1-f7bfbcac5eee)
![image](https://github.com/user-attachments/assets/1e81a85f-5d75-48a2-8d62-eabc631ba710)
