### ISSUE TITLE
An error occurred when I tried to use langchain's chain to call api_server

### ISSUE THREAD

**Issue by xiong0827** [InternLM/lmdeploy#993]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

**启动命令和输出**
lmdeploy serve api_server /home/public/models/Shanghai_AI_Laboratory/internlm2-chat-20b --model-name internlm2-chat-20b --tp 4 --session-len 2048 --server-port 8000 
model_source: hf_model
01/18 19:21:03 - lmdeploy - WARNING - Can not find tokenizer.json. It may take long time to initialize the tokenizer.
model_config:

[llama]
model_name = internlm2-chat-20b
tensor_para_size = 4
head_num = 48
kv_head_num = 8
vocab_size = 92544
num_layer = 48
inter_size = 16384
norm_eps = 1e-05
attn_bias = 0
start_id = 1
end_id = 2
session_len = 2048
weight_type = fp16
rotary_embedding = 128
rope_theta = 1000000.0
size_per_head = 128
group_size = 0
max_batch_size = 128
max_context_token_num = 1
step_length = 1
cache_max_entry_count = 0.5
cache_block_seq_len = 128
cache_chunk_size = -1
num_tokens_per_iter = 0
max_prefill_iters = 1
extra_tokens_per_iter = 0
use_context_fmha = 1
quant_policy = 0
max_position_embeddings = 32768
rope_scaling_factor = 0.0
use_logn_attn = 0

get 1251 model params
[WARNING] gemm_config.in is not found; using default GEMM algo                                                                   
[WARNING] gemm_config.in is not found; using default GEMM algo
[WARNING] gemm_config.in is not found; using default GEMM algo
[WARNING] gemm_config.in is not found; using default GEMM algo
HINT:    Please open http://0.0.0.0:8000 in a browser for detailed api usage!!!
HINT:    Please open http://0.0.0.0:8000 in a browser for detailed api usage!!!
HINT:    Please open http://0.0.0.0:8000 in a browser for detailed api usage!!!
INFO:     Started server process [24194]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     192.168.2.132:55063 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     192.168.2.132:55152 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     192.168.2.132:55171 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     192.168.2.132:55916 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     192.168.2.132:56018 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     192.168.2.132:56047 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     192.168.2.132:56125 - "POST /v1/chat/completions HTTP/1.1" 200 OK
### 调用代码

> import os
> os.environ["OPENAI_API_BASE"] = "http://192.168.2.46:8000/v1"
> os.environ["OPENAI_API_KEY"] = "xxx"
> from langchain.chat_models import ChatOpenAI
> from langchain.callbacks import AsyncIteratorCallbackHandler,StreamingStdOutCallbackHandler
> from langchain.chains import LLMChain
> from langchain.prompts import SystemMessagePromptTemplate,PromptTemplate
> prompt = PromptTemplate(template="{question}", input_variables=["question"])
> async def chat():
>     llm = ChatOpenAI(
>         temperature=0,
>         streaming=True,
>         callbacks=[AsyncIteratorCallbackHandler(),StreamingStdOutCallbackHandler()],
>     )
>     chain = LLMChain(llm=llm, prompt=prompt,)
>     res=await chain.arun('写个小故事 500字左右')
>     print(res)
> async def  main():
>     tasks=[chat() for i in range(10)]
>     await asyncio.gather(*tasks)
> if __name__ == '__main__':
>     import asyncio
>     asyncio.run(main())  

### Reproduction

> lmdeploy serve api_server /home/public/models/Shanghai_AI_Laboratory/internlm2-chat-20b --model-name internlm2-chat-20b --tp 4 --session-len 2048 --server-port 8000 

### Environment

```Shell
lmdeploy==0.2.0
langchain==0.0.343
openai=1.8.0
```

### Error traceback

```Shell
**出现以下错误：**
  File "E:\360MoveData\Users\Administrator\Desktop\langchain_milvus\index.py", line 19, in chat
    res=await chain.arun('写个小故事 500字左右')
  File "D:\conda\envs\chatglm2\lib\site-packages\langchain\chains\base.py", line 581, in arun
    await self.acall(
  File "D:\conda\envs\chatglm2\lib\site-packages\langchain\chains\base.py", line 381, in acall
    raise e
  File "D:\conda\envs\chatglm2\lib\site-packages\langchain\chains\base.py", line 375, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "D:\conda\envs\chatglm2\lib\site-packages\langchain\chains\llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
  File "D:\conda\envs\chatglm2\lib\site-packages\langchain\chains\llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
  File "D:\conda\envs\chatglm2\lib\site-packages\langchain_core\language_models\chat_models.py", line 502, in agenerate_prompt
    return await self.agenerate(
  File "D:\conda\envs\chatglm2\lib\site-packages\langchain_core\language_models\chat_models.py", line 462, in agenerate 
    raise exceptions[0]
  File "D:\conda\envs\chatglm2\lib\site-packages\langchain_core\language_models\chat_models.py", line 565, in _agenerate_with_cache
    return await self._agenerate(
  File "D:\conda\envs\chatglm2\lib\site-packages\langchain\chat_models\openai.py", line 506, in _agenerate
    return await agenerate_from_stream(stream_iter)
  File "D:\conda\envs\chatglm2\lib\site-packages\langchain_core\language_models\chat_models.py", line 87, in agenerate_from_stream
    assert generation is not None
AssertionError
```

**Comment by mpmX** [comment]
How did you fix this? I'm having the same error when I use LMdeploy as backend for an agent framework. Seems to not depend on the model used.
