### ISSUE TITLE
[Bug] 升级0.2.0 后，加载 qwen-14b 或者 internlm2-chat-20b 的awq量化模型报显存错误

### ISSUE THREAD

**Issue by WCwalker** [InternLM/lmdeploy#998]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

Exception in thread Thread-132 (_create_model_instance):
Traceback (most recent call last):
  File "/home/mingqiang/.conda/envs/qwen/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/mingqiang/.conda/envs/qwen/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mingqiang/.conda/envs/qwen/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 486, in _create_model_instance
    model_inst = self.tm_model.model_comm.create_model_instance(
RuntimeError: [TM][ERROR] CUDA runtime error: out of memory /lmdeploy/src/turbomind/utils/allocator.h:231 

### Reproduction

import lmdeploy

model_path = '/home/mingqiang/model/model_file/qwen-14b-chat-finetune-4bit/'
pipe = lmdeploy.pipeline(model_path, model_name='qwen-14b')
response = pipe(["你是谁", "你在哪"])
print(response)

### Environment

```Shell
lmdepoly==0.2.0
```

**Comment by miaoerduo** [comment]
大佬，我也碰到一样的问题了，想请教一下你，用上一个版本可以正常serving吗？另外在部署`internlm2-chat-20b-4bits`时，会出现无法找到`tokenizer.json`的情况，是否就是`tokenizer_config.json`这个文件？

**Comment by WCwalker** [comment]
> 大佬，我也碰到一样的问题了，想请教一下你，用上一个版本可以正常serving吗？另外在部署`internlm2-chat-20b-4bits`时，会出现无法找到`tokenizer.json`的情况，是否就是`tokenizer_config.json`这个文件？

我今天早上还在用 0.1.0， 然后发现0.2.0才支持`internlm2-chat-20b-4bits”，所以刚刚升级了，结果就报错了，连之前能运行的qwen14量化模型也报这个错，然后我就降级回0.1.0，qwen就可以了

**Comment by miaoerduo** [comment]
> > 大佬，我也碰到一样的问题了，想请教一下你，用上一个版本可以正常serving吗？另外在部署`internlm2-chat-20b-4bits`时，会出现无法找到`tokenizer.json`的情况，是否就是`tokenizer_config.json`这个文件？
> 
> 我觉得应该不是`tokenizer.json`这个问题

那这个文件，怎么获取呢？我看之前的模型也没有这个。

另外，最近有fix OOM的MR，说不定就是fix这个问题的。https://github.com/InternLM/lmdeploy/pull/973

**Comment by WCwalker** [comment]
> > > 大佬，我也碰到一样的问题了，想请教一下你，用上一个版本可以正常serving吗？另外在部署`internlm2-chat-20b-4bits`时，会出现无法找到`tokenizer.json`的情况，是否就是`tokenizer_config.json`这个文件？
> > 
> > 
> > 我觉得应该不是`tokenizer.json`这个问题
> 
> 那这个文件，怎么获取呢？我看之前的模型也没有这个。
> 
> 另外，最近有fix OOM的MR，说不定就是fix这个问题的。#973

暂时没搞懂什么问题，先不测internlm2-chat-20b-4bits的效果了，等官方的大佬看看怎么修，我这边先保持0.1.0跑吧

**Comment by lvhan028** [comment]
什么型号的显卡？用的是哪个命令？

**Comment by WCwalker** [comment]
> 什么型号的显卡？用的是哪个命令？

A800, 
运行样例
import lmdeploy

model_path = '/home/mingqiang/model/model_file/qwen-14b-chat-finetune-4bit/'
pipe = lmdeploy.pipeline(model_path, model_name='qwen-14b')
response = pipe(["你是谁", "你在哪"])
print(response)

**Comment by lvhan028** [comment]
加一个选项: --cache-max-entry-count 0.4 试试。

**Comment by WCwalker** [comment]
> cache
我今天测试了，要设0.3或者更少才行，但是加载internlm2-chat-20b 模型有另外的问题，停止符有问题，会一直推理停不下来
![Uploading 1705907933039.jpg…]()

**Comment by WCwalker** [comment]
> 加一个选项: --cache-max-entry-count 0.4 试试。

我今天测试了，要设0.3或者更少才行，但是加载internlm2-chat-20b 模型有另外的问题，停止符有问题，会一直推理停不下来
![1705907933039](https://github.com/InternLM/lmdeploy/assets/36464439/4622d787-71b1-45ed-8d98-733421e2ce5c)

**Comment by lvhan028** [comment]
internlm2-chat-20b模型上周更新了special_tokens，对应的要使用 lmdeploy v0.2.1
更新下lmdeploy再试试看呢？

**Comment by WCwalker** [comment]
> internlm2-chat-20b模型上周更新了special_tokens，对应的要使用 lmdeploy v0.2.1 更新下lmdeploy再试试看呢？

已经可以了，我刚刚上去更新了 internlm2-chat-20b 模型里面的[tokenizer_config.json](https://huggingface.co/internlm/internlm2-chat-20b-sft/blob/main/tokenizer_config.json)
